PROJECT_CONTEXT_CONTENT_DICT = {}
PROJECT_CONTEXT_CONTENT_DICT[0] = "CONTEXT_INIT"
PROJECT_CONTEXT_CONTENT_DICT[0XFF00] = "PACKAGE_LOST"

VPN_UDP_SEND = 0X11
VPN_UDP_RECV = 0X12
VPN_PREPARE_RESET = 0X13

PROJECT_CONTEXT_CONTENT_DICT[VPN_UDP_SEND] = "VPN_UDP_SEND"
PROJECT_CONTEXT_CONTENT_DICT[VPN_UDP_RECV] = "VPN_UDP_RECV"
PROJECT_CONTEXT_CONTENT_DICT[VPN_PREPARE_RESET] = "VPN_PREPARE_RESET"

FORWARD_CONNECT_CLOSE = 0xff01
FORWARD_PIPE_BROKED = 0xff02
PROJECT_CONTEXT_CONTENT_DICT[FORWARD_CONNECT_CLOSE] = "FORWARD_CONNECT_CLOSE"
PROJECT_CONTEXT_CONTENT_DICT[FORWARD_PIPE_BROKED] = "FORWARD_PIPE_BROKED"

FORWARD_SEND_MTU_TOO_LOW = 0xf001
FORWARD_PACKAGE_TOO_LARGE = 0xf002
PROJECT_CONTEXT_CONTENT_DICT[FORWARD_SEND_MTU_TOO_LOW] = "FORWARD_SEND_MTU_TOO_LOW"
PROJECT_CONTEXT_CONTENT_DICT[FORWARD_PACKAGE_TOO_LARGE] = "FORWARD_PACKAGE_TOO_LARGE"
