VPN_CONTEXT_CONTENT_DICT = {}
VPN_CONTEXT_CONTENT_DICT[0] = "CONTEXT_INIT"
VPN_CONTEXT_CONTENT_DICT[0XFF00] = "PACKAGE_LOST"

TLS_SEND_DATA = 0x11
TLS_RECV_DATA = 0x12
TLS_HANDSHARK_DATA_NEED = 0x13
TLS_DO_HANDSHARK = 0x14
TLS_RECV_APPLICATION_DATA = 0x15
TLS_SEND_APPLICATION_DATA = 0x16
TLS_HANDSHARK_DONE = 0x17

SOCKET_RECV = 0x21

VPN_DATA_RECV = 0x31
VPN_RECORD_DATA_RECV_RESTRUCT = 0x32
VPN_RECORD_CONTROL_SEND_RESTRUCT = 0x33
VPN_RECORD_APPLICATION_SEND_RESTRUCT = 0x34
VPN_SEND_DATA = 0x35
VPN_APPLICATION_DATA_SEND = 0x36
VPN_CONTROL_RECV = 0x37
VPN_PREPARE_HARD_RESET = 0x38
VPN_HARD_RESET = 0x39

COMMUNICATE_SEND_DATA = 0x41
COMMUNICATE_RECV_UDP_DATA = 0x43
COMMUNICATE_SEND_UDP_DATA = 0x44

SOCKET_CONNECT_CLOSE = 0xFF01
TLS_SSL_ERROR = 0XFF02

VPN_CONTEXT_CONTENT_DICT[TLS_SEND_DATA] = "TLS_SEND_DATA"
VPN_CONTEXT_CONTENT_DICT[TLS_RECV_DATA] = "TLS_RECV_DATA"
VPN_CONTEXT_CONTENT_DICT[TLS_HANDSHARK_DATA_NEED] = "TLS_HANDSHARK_DATA_NEED"
VPN_CONTEXT_CONTENT_DICT[TLS_DO_HANDSHARK] = "TLS_DO_HANDSHARK"
VPN_CONTEXT_CONTENT_DICT[TLS_RECV_APPLICATION_DATA] = "TLS_RECV_APPLICATION_DATA"
VPN_CONTEXT_CONTENT_DICT[SOCKET_RECV] = "SOCKET_RECV"
VPN_CONTEXT_CONTENT_DICT[VPN_DATA_RECV] = "VPN_DATA_RECV"
VPN_CONTEXT_CONTENT_DICT[VPN_RECORD_DATA_RECV_RESTRUCT] = "VPN_RECORD_DATA_RECV_RESTRUCT"
VPN_CONTEXT_CONTENT_DICT[
    VPN_RECORD_CONTROL_SEND_RESTRUCT] = "VPN_RECORD_DATA_SEND_RESTRUCT"
VPN_CONTEXT_CONTENT_DICT[VPN_CONTROL_RECV] = "VPN_CONTROL_RECV"
VPN_CONTEXT_CONTENT_DICT[VPN_SEND_DATA] = "VPN_SEND_DATA"
VPN_CONTEXT_CONTENT_DICT[SOCKET_CONNECT_CLOSE] = "SOCKET_CONNECT_CLOSE"
VPN_CONTEXT_CONTENT_DICT[TLS_SSL_ERROR] = "TLS_SSL_ERROR"
VPN_CONTEXT_CONTENT_DICT[TLS_HANDSHARK_DONE] = "TLS_HANDSHARK_DONE"
VPN_CONTEXT_CONTENT_DICT[COMMUNICATE_SEND_DATA] = "COMMUNICATE_SEND_DATA"
