Mbed TLS v3.5.1: crypto_struct.h File Reference
crypto_struct.h File Reference
PSA cryptography module: Mbed TLS structured type implementations.
#include "mbedtls/private_access.h"
#include "mbedtls/build_info.h"
#include "psa/crypto_driver_contexts_primitives.h"
#include "psa/crypto_driver_contexts_composites.h"
#include "psa/crypto_driver_contexts_key_derivation.h"
Data Structures
struct psa_hash_operation_s
struct psa_cipher_operation_s
struct psa_mac_operation_s
struct psa_aead_operation_s
struct psa_key_derivation_s
struct psa_key_policy_s
struct psa_core_key_attributes_t
struct psa_key_attributes_s
struct psa_sign_hash_interruptible_operation_s
The context for PSA interruptible hash signing.
struct psa_verify_hash_interruptible_operation_s
The context for PSA interruptible hash verification.
Macros
#define PSA_HASH_OPERATION_INIT { 0, { 0 } }
#define PSA_CIPHER_OPERATION_INIT { 0, 0, 0, 0, { 0 } }
#define PSA_MAC_OPERATION_INIT { 0, 0, 0, { 0 } }
#define PSA_AEAD_OPERATION_INIT { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, { 0 } }
#define PSA_KEY_DERIVATION_OPERATION_INIT { 0, 0, 0, { 0 } }
#define PSA_KEY_POLICY_INIT { 0, 0, 0 }
#define PSA_KEY_BITS_TOO_LARGE ((psa_key_bits_t) -1)
#define PSA_MAX_KEY_BITS 0xfff8
#define MBEDTLS_PSA_KA_FLAG_HAS_SLOT_NUMBER ((psa_key_attributes_flag_t) 0x0001)
#define MBEDTLS_PSA_KA_MASK_EXTERNAL_ONLY
#define MBEDTLS_PSA_KA_MASK_DUAL_USE
#define PSA_CORE_KEY_ATTRIBUTES_INIT
#define PSA_KEY_ATTRIBUTES_INIT { PSA_CORE_KEY_ATTRIBUTES_INIT, 0, NULL, 0 }
#define PSA_SIGN_HASH_INTERRUPTIBLE_OPERATION_INIT { 0, { 0 }, 0, 0 }
#define PSA_VERIFY_HASH_INTERRUPTIBLE_OPERATION_INIT { 0, { 0 }, 0, 0 }
Typedefs
typedef struct psa_key_policy_s psa_key_policy_t
typedef uint16_t psa_key_bits_t
typedef uint16_t psa_key_attributes_flag_t
Functions
static struct psa_hash_operation_s psa_hash_operation_init (void)
static struct psa_cipher_operation_s psa_cipher_operation_init (void)
static struct psa_mac_operation_s psa_mac_operation_init (void)
static struct psa_aead_operation_s psa_aead_operation_init (void)
static struct psa_key_derivation_s psa_key_derivation_operation_init (void)
static struct psa_key_policy_s psa_key_policy_init (void)
static struct psa_key_attributes_s psa_key_attributes_init (void)
static void psa_set_key_id (psa_key_attributes_t *attributes, mbedtls_svc_key_id_t key)
static mbedtls_svc_key_id_t psa_get_key_id (const psa_key_attributes_t *attributes)
static void psa_set_key_lifetime (psa_key_attributes_t *attributes, psa_key_lifetime_t lifetime)
static psa_key_lifetime_t psa_get_key_lifetime (const psa_key_attributes_t *attributes)
static void psa_extend_key_usage_flags (psa_key_usage_t *usage_flags)
static void psa_set_key_usage_flags (psa_key_attributes_t *attributes, psa_key_usage_t usage_flags)
static psa_key_usage_t psa_get_key_usage_flags (const psa_key_attributes_t *attributes)
static void psa_set_key_algorithm (psa_key_attributes_t *attributes, psa_algorithm_t alg)
static psa_algorithm_t psa_get_key_algorithm (const psa_key_attributes_t *attributes)
psa_status_t psa_set_key_domain_parameters (psa_key_attributes_t *attributes, psa_key_type_t type, const uint8_t *data, size_t data_length)
static void psa_set_key_type (psa_key_attributes_t *attributes, psa_key_type_t type)
static psa_key_type_t psa_get_key_type (const psa_key_attributes_t *attributes)
static void psa_set_key_bits (psa_key_attributes_t *attributes, size_t bits)
static size_t psa_get_key_bits (const psa_key_attributes_t *attributes)
static struct psa_sign_hash_interruptible_operation_s psa_sign_hash_interruptible_operation_init (void)
static struct psa_verify_hash_interruptible_operation_s psa_verify_hash_interruptible_operation_init (void)
Detailed Description
PSA cryptography module: Mbed TLS structured type implementations.
Note
This file may not be included directly. Applications must include psa/crypto.h.
This file contains the definitions of some data structures with implementation-specific definitions.
In implementations with isolation between the application and the cryptography module, it is expected that the front-end and the back-end would have different versions of this file.
Design notes about multipart operation structures
For multipart operations without driver delegation support, each multipart operation structure contains a psa_algorithm_t alg field which indicates which specific algorithm the structure is for. When the structure is not in use, alg is 0. Most of the structure consists of a union which is discriminated by alg.
For multipart operations with driver delegation support, each multipart operation structure contains an unsigned int id field indicating which driver got assigned to do the operation. When the structure is not in use, 'id' is 0. The structure contains also a driver context which is the union of the contexts of all drivers able to handle the type of multipart operation.
Note that when alg or id is 0, the content of other fields is undefined. In particular, it is not guaranteed that a freshly-initialized structure is all-zero: we initialize structures to something like {0, 0}, which is only guaranteed to initializes the first member of the union; GCC and Clang initialize the whole structure to 0 (at the time of writing), but MSVC and CompCert don't.
In Mbed TLS, multipart operation structures live independently from the key. This allows Mbed TLS to free the key objects when destroying a key slot. If a multipart operation needs to remember the key after the setup function returns, the operation structure needs to contain a copy of the key.
Definition in file crypto_struct.h.
Macro Definition Documentation
MBEDTLS_PSA_KA_FLAG_HAS_SLOT_NUMBER
#define MBEDTLS_PSA_KA_FLAG_HAS_SLOT_NUMBER ((psa_key_attributes_flag_t) 0x0001)
Definition at line 219 of file crypto_struct.h.
MBEDTLS_PSA_KA_MASK_DUAL_USE
#define MBEDTLS_PSA_KA_MASK_DUAL_USE
Value:
        (          \
        0)
Definition at line 230 of file crypto_struct.h.
MBEDTLS_PSA_KA_MASK_EXTERNAL_ONLY
#define MBEDTLS_PSA_KA_MASK_EXTERNAL_ONLY
Value:
        (      \
        MBEDTLS_PSA_KA_FLAG_HAS_SLOT_NUMBER |    \
        0)
Definition at line 224 of file crypto_struct.h.
PSA_CORE_KEY_ATTRIBUTES_INIT
#define PSA_CORE_KEY_ATTRIBUTES_INIT
Value:
                                       { PSA_KEY_TYPE_NONE, 0,            \
                                       PSA_KEY_LIFETIME_VOLATILE,       \
                                       MBEDTLS_SVC_KEY_ID_INIT,         \
                                       PSA_KEY_POLICY_INIT, 0 }
Definition at line 242 of file crypto_struct.h.
PSA_KEY_BITS_TOO_LARGE
#define PSA_KEY_BITS_TOO_LARGE ((psa_key_bits_t) -1)
Definition at line 202 of file crypto_struct.h.
PSA_KEY_POLICY_INIT
#define PSA_KEY_POLICY_INIT { 0, 0, 0 }
Definition at line 190 of file crypto_struct.h.
PSA_MAX_KEY_BITS
#define PSA_MAX_KEY_BITS 0xfff8
Definition at line 208 of file crypto_struct.h.
PSA_SIGN_HASH_INTERRUPTIBLE_OPERATION_INIT
#define PSA_SIGN_HASH_INTERRUPTIBLE_OPERATION_INIT { 0, { 0 }, 0, 0 }
Definition at line 415 of file crypto_struct.h.
PSA_VERIFY_HASH_INTERRUPTIBLE_OPERATION_INIT
#define PSA_VERIFY_HASH_INTERRUPTIBLE_OPERATION_INIT { 0, { 0 }, 0, 0 }
Definition at line 445 of file crypto_struct.h.
Typedef Documentation
psa_key_attributes_flag_t
typedef uint16_t psa_key_attributes_flag_t
A mask of flags that can be stored in key attributes.
This type is also used internally to store flags in slots. Internal flags are defined in library/psa_crypto_core.h. Internal flags may have the same value as external flags if they are properly handled during key creation and in psa_get_key_attributes.
Definition at line 217 of file crypto_struct.h.
psa_key_bits_t
typedef uint16_t psa_key_bits_t
Definition at line 199 of file crypto_struct.h.
psa_key_policy_t
typedef struct psa_key_policy_s psa_key_policy_t
Definition at line 188 of file crypto_struct.h.
Function Documentation
psa_aead_operation_init()
static struct psa_aead_operation_s psa_aead_operation_init (void) inline static
Definition at line 157 of file crypto_struct.h.
References PSA_AEAD_OPERATION_INIT.
psa_cipher_operation_init()
static struct psa_cipher_operation_s psa_cipher_operation_init (void) inline static
Definition at line 101 of file crypto_struct.h.
References PSA_CIPHER_OPERATION_INIT.
psa_extend_key_usage_flags()
static void psa_extend_key_usage_flags (psa_key_usage_t * usage_flags) inline static
Definition at line 316 of file crypto_struct.h.
References PSA_KEY_USAGE_SIGN_HASH, PSA_KEY_USAGE_SIGN_MESSAGE, PSA_KEY_USAGE_VERIFY_HASH, and PSA_KEY_USAGE_VERIFY_MESSAGE.
Referenced by psa_set_key_usage_flags().
psa_get_key_algorithm()
static psa_algorithm_t psa_get_key_algorithm (const psa_key_attributes_t * attributes) inline static
Definition at line 346 of file crypto_struct.h.
psa_get_key_bits()
static size_t psa_get_key_bits (const psa_key_attributes_t * attributes) inline static
Definition at line 390 of file crypto_struct.h.
psa_get_key_id()
static mbedtls_svc_key_id_t psa_get_key_id (const psa_key_attributes_t * attributes) inline static
Definition at line 283 of file crypto_struct.h.
psa_get_key_lifetime()
static psa_key_lifetime_t psa_get_key_lifetime (const psa_key_attributes_t * attributes) inline static
Definition at line 310 of file crypto_struct.h.
psa_get_key_type()
static psa_key_type_t psa_get_key_type (const psa_key_attributes_t * attributes) inline static
Definition at line 374 of file crypto_struct.h.
psa_get_key_usage_flags()
static psa_key_usage_t psa_get_key_usage_flags (const psa_key_attributes_t * attributes) inline static
Definition at line 334 of file crypto_struct.h.
psa_hash_operation_init()
static struct psa_hash_operation_s psa_hash_operation_init (void) inline static
Definition at line 77 of file crypto_struct.h.
References PSA_HASH_OPERATION_INIT.
psa_key_attributes_init()
static struct psa_key_attributes_s psa_key_attributes_init (void) inline static
Definition at line 262 of file crypto_struct.h.
References PSA_KEY_ATTRIBUTES_INIT.
psa_key_derivation_operation_init()
static struct psa_key_derivation_s psa_key_derivation_operation_init (void) inline static
Definition at line 176 of file crypto_struct.h.
References PSA_KEY_DERIVATION_OPERATION_INIT.
psa_key_policy_init()
static struct psa_key_policy_s psa_key_policy_init (void) inline static
Definition at line 191 of file crypto_struct.h.
References PSA_KEY_POLICY_INIT.
psa_mac_operation_init()
static struct psa_mac_operation_s psa_mac_operation_init (void) inline static
Definition at line 125 of file crypto_struct.h.
References PSA_MAC_OPERATION_INIT.
psa_set_key_algorithm()
static void psa_set_key_algorithm (psa_key_attributes_t * attributes, psa_algorithm_t alg) inline static
Definition at line 340 of file crypto_struct.h.
psa_set_key_bits()
static void psa_set_key_bits (psa_key_attributes_t * attributes, size_t bits) inline static
Definition at line 380 of file crypto_struct.h.
References PSA_KEY_BITS_TOO_LARGE, and PSA_MAX_KEY_BITS.
psa_set_key_domain_parameters()
psa_status_t psa_set_key_domain_parameters (psa_key_attributes_t * attributes, psa_key_type_t type, const uint8_t * data, size_t data_length)
Referenced by psa_set_key_type().
psa_set_key_id()
static void psa_set_key_id (psa_key_attributes_t * attributes, mbedtls_svc_key_id_t key) inline static
Definition at line 268 of file crypto_struct.h.
References PSA_KEY_LIFETIME_FROM_PERSISTENCE_AND_LOCATION, PSA_KEY_LIFETIME_GET_LOCATION, PSA_KEY_LIFETIME_IS_VOLATILE, and PSA_KEY_LIFETIME_PERSISTENT.
psa_set_key_lifetime()
static void psa_set_key_lifetime (psa_key_attributes_t * attributes, psa_key_lifetime_t lifetime) inline static
Definition at line 297 of file crypto_struct.h.
References PSA_KEY_LIFETIME_IS_VOLATILE.
psa_set_key_type()
static void psa_set_key_type (psa_key_attributes_t * attributes, psa_key_type_t type) inline static
Definition at line 359 of file crypto_struct.h.
References psa_set_key_domain_parameters().
psa_set_key_usage_flags()
static void psa_set_key_usage_flags (psa_key_attributes_t * attributes, psa_key_usage_t usage_flags) inline static
Definition at line 327 of file crypto_struct.h.
References psa_extend_key_usage_flags().
psa_sign_hash_interruptible_operation_init()
static struct psa_sign_hash_interruptible_operation_s psa_sign_hash_interruptible_operation_init (void) inline static
Definition at line 418 of file crypto_struct.h.
References PSA_SIGN_HASH_INTERRUPTIBLE_OPERATION_INIT.
psa_verify_hash_interruptible_operation_init()
static struct psa_verify_hash_interruptible_operation_s psa_verify_hash_interruptible_operation_init (void) inline static
Definition at line 448 of file crypto_struct.h.
References PSA_VERIFY_HASH_INTERRUPTIBLE_OPERATION_INIT.