OpenVPN: src/openvpn/base64.h File Reference
base64.h File Reference
Macros
#define OPENVPN_BASE64_LENGTH(binary_length) ((((8 * binary_length) / 6) + 3) & ~3)
Compute resulting base64 length.
Functions
int openvpn_base64_encode (const void *data, int size, char **str)
int openvpn_base64_decode (const char *str, void *data, int size)
Macro Definition Documentation
OPENVPN_BASE64_LENGTH
#define OPENVPN_BASE64_LENGTH (binary_length) ((((8 * binary_length) / 6) + 3) & ~3)
Compute resulting base64 length.
6 bits per byte, padded to 4 bytes.
Definition at line 38 of file base64.h.
Function Documentation
openvpn_base64_decode()
int openvpn_base64_decode (const char * str, void * data, int size)
Definition at line 160 of file base64.c.
References base64_chars, DECODE_ERROR, and token_decode().
Referenced by generate_auth_token(), get_auth_challenge(), get_sig_from_man(), ntlm_phase_3(), set_auth_token_user(), tls_crypt_v2_write_client_key_file(), and verify_auth_token().
openvpn_base64_encode()
int openvpn_base64_encode (const void * data, int size, char ** str)
Definition at line 54 of file base64.c.
References base64_chars.
Referenced by generate_auth_token(), get_sig_from_man(), get_user_pass_cr(), and make_base64_string2().