OpenVPN: src/openvpn/buffer.h File Reference
buffer.h File Reference
#include "basic.h"
#include "error.h"
Data Structures
struct buffer
Wrapper structure for dynamically allocated memory.
struct gc_entry
Garbage collection entry for one dynamically allocated block of memory.
struct gc_entry_special
Garbage collection entry for a specially allocated structure that needs a custom free function to be freed like struct addrinfo.
struct gc_arena
Garbage collection arena used to keep track of dynamically allocated memory.
struct buffer_entry
struct buffer_list
Macros
#define BUF_SIZE_MAX 1000000
#define BPTR(buf) (buf_bptr(buf))
#define BEND(buf) (buf_bend(buf))
#define BLAST(buf) (buf_blast(buf))
#define BLEN(buf) (buf_len(buf))
#define BDEF(buf) (buf_defined(buf))
#define BSTR(buf) (buf_str(buf))
#define BCAP(buf) (buf_forward_capacity(buf))
#define PA_BRACKET (1<<0)
#define buf_init(buf, offset) buf_init_dowork(buf, offset)
#define FHE_SPACE_BREAK_MASK 0xFF /* space_break parameter in lower 8 bits */
#define FHE_CAPS 0x100 /* output hex in caps */
#define CC_ANY (1<<0)
#define CC_NULL (1<<1)
#define CC_ALNUM (1<<2)
#define CC_ALPHA (1<<3)
#define CC_ASCII (1<<4)
#define CC_CNTRL (1<<5)
#define CC_DIGIT (1<<6)
#define CC_PRINT (1<<7)
#define CC_PUNCT (1<<8)
#define CC_SPACE (1<<9)
#define CC_XDIGIT (1<<10)
#define CC_BLANK (1<<11)
#define CC_NEWLINE (1<<12)
#define CC_CR (1<<13)
#define CC_BACKSLASH (1<<14)
#define CC_UNDERBAR (1<<15)
#define CC_DASH (1<<16)
#define CC_DOT (1<<17)
#define CC_COMMA (1<<18)
#define CC_COLON (1<<19)
#define CC_SLASH (1<<20)
#define CC_SINGLE_QUOTE (1<<21)
#define CC_DOUBLE_QUOTE (1<<22)
#define CC_REVERSE_QUOTE (1<<23)
#define CC_AT (1<<24)
#define CC_EQUAL (1<<25)
#define CC_LESS_THAN (1<<26)
#define CC_GREATER_THAN (1<<27)
#define CC_PIPE (1<<28)
#define CC_QUESTION_MARK (1<<29)
#define CC_ASTERISK (1<<30)
#define CC_NAME (CC_ALNUM|CC_UNDERBAR)
#define CC_CRLF (CC_CR|CC_NEWLINE)
#define verify_align_4(ptr)
#define ALLOC_OBJ(dptr, type)
#define ALLOC_OBJ_CLEAR(dptr, type)
#define ALLOC_ARRAY(dptr, type, n)
#define ALLOC_ARRAY_GC(dptr, type, n, gc)
#define ALLOC_ARRAY_CLEAR(dptr, type, n)
#define ALLOC_ARRAY_CLEAR_GC(dptr, type, n, gc)
#define ALLOC_VAR_ARRAY_CLEAR_GC(dptr, type, atype, n, gc)
#define ALLOC_OBJ_GC(dptr, type, gc)
#define ALLOC_OBJ_CLEAR_GC(dptr, type, gc)
Functions
void buf_clear (struct buffer *buf)
void free_buf (struct buffer *buf)
bool buf_assign (struct buffer *dest, const struct buffer *src)
void string_clear (char *str)
int string_array_len (const char **array)
size_t array_mult_safe (const size_t m1, const size_t m2, const size_t extra)
char * print_argv (const char **p, struct gc_arena *gc, const unsigned int flags)
void buf_size_error (const size_t size)
struct buffer alloc_buf (size_t size)
struct buffer alloc_buf_gc (size_t size, struct gc_arena *gc)
struct buffer clone_buf (const struct buffer *buf)
void * gc_malloc (size_t size, bool clear, struct gc_arena *a)
char * string_alloc (const char *str, struct gc_arena *gc)
struct buffer string_alloc_buf (const char *str, struct gc_arena *gc)
void gc_addspecial (void *addr, void(*free_function)(void *), struct gc_arena *a)
static void gc_freeaddrinfo_callback (void *addr)
static struct buffer clear_buf (void)
Return an empty struct buffer.
static bool buf_defined (const struct buffer *buf)
static bool buf_valid (const struct buffer *buf)
static uint8_t * buf_bptr (const struct buffer *buf)
static int buf_len (const struct buffer *buf)
static uint8_t * buf_bend (const struct buffer *buf)
static uint8_t * buf_blast (const struct buffer *buf)
static bool buf_size_valid (const size_t size)
static bool buf_size_valid_signed (const int size)
static char * buf_str (const struct buffer *buf)
static void buf_reset (struct buffer *buf)
static void buf_reset_len (struct buffer *buf)
static bool buf_init_dowork (struct buffer *buf, int offset)
static void buf_set_write (struct buffer *buf, uint8_t *data, int size)
static void buf_set_read (struct buffer *buf, const uint8_t *data, int size)
static void strncpynt (char *dest, const char *src, size_t maxlen)
static bool has_digit (const unsigned char *src)
static void secure_memzero (void *data, size_t len)
Securely zeroise memory.
bool buf_printf (struct buffer *buf, const char *format,...)
bool buf_puts (struct buffer *buf, const char *str)
bool openvpn_snprintf (char *str, size_t size, const char *format,...)
void buf_null_terminate (struct buffer *buf)
void buf_chomp (struct buffer *buf)
void buf_rmtail (struct buffer *buf, uint8_t remove)
void chomp (char *str)
void rm_trailing_chars (char *str, const char *what_to_delete)
const char * skip_leading_whitespace (const char *str)
void string_null_terminate (char *str, int len, int capacity)
bool buffer_write_file (const char *filename, const struct buffer *buf)
Write buffer contents to file.
void buf_catrunc (struct buffer *buf, const char *str)
void convert_to_one_line (struct buffer *buf)
bool buf_parse (struct buffer *buf, const int delim, char *line, const int size)
char * format_hex_ex (const uint8_t *data, int size, int maxoutput, unsigned int space_break_flags, const char *separator, struct gc_arena *gc)
static char * format_hex (const uint8_t *data, int size, int maxoutput, struct gc_arena *gc)
struct buffer buf_sub (struct buffer *buf, int size, bool prepend)
static bool buf_safe (const struct buffer *buf, int len)
static bool buf_safe_bidir (const struct buffer *buf, int len)
static int buf_forward_capacity (const struct buffer *buf)
static int buf_forward_capacity_total (const struct buffer *buf)
static int buf_reverse_capacity (const struct buffer *buf)
static bool buf_inc_len (struct buffer *buf, int inc)
static uint8_t * buf_prepend (struct buffer *buf, int size)
static bool buf_advance (struct buffer *buf, int size)
static uint8_t * buf_write_alloc (struct buffer *buf, int size)
static uint8_t * buf_write_alloc_prepend (struct buffer *buf, int size, bool prepend)
static uint8_t * buf_read_alloc (struct buffer *buf, int size)
static bool buf_write (struct buffer *dest, const void *src, int size)
static bool buf_write_prepend (struct buffer *dest, const void *src, int size)
static bool buf_write_u8 (struct buffer *dest, int data)
static bool buf_write_u16 (struct buffer *dest, int data)
static bool buf_write_u32 (struct buffer *dest, int data)
static bool buf_copy (struct buffer *dest, const struct buffer *src)
static bool buf_copy_n (struct buffer *dest, struct buffer *src, int n)
static bool buf_copy_range (struct buffer *dest, int dest_index, const struct buffer *src, int src_index, int src_len)
static bool buf_copy_excess (struct buffer *dest, struct buffer *src, int len)
static bool buf_read (struct buffer *src, void *dest, int size)
static int buf_read_u8 (struct buffer *buf)
static int buf_read_u16 (struct buffer *buf)
static uint32_t buf_read_u32 (struct buffer *buf, bool *good)
static bool buf_equal (const struct buffer *a, const struct buffer *b)
Return true if buffer contents are equal.
static bool buf_string_match (const struct buffer *src, const void *match, int size)
Compare src buffer contents with match.
static bool buf_string_match_head (const struct buffer *src, const void *match, int size)
Compare first size bytes of src buffer contents with match.
bool buf_string_match_head_str (const struct buffer *src, const char *match)
bool buf_string_compare_advance (struct buffer *src, const char *match)
int buf_substring_len (const struct buffer *buf, int delim)
const char * np (const char *str)
bool char_class (const unsigned char c, const unsigned int flags)
bool string_class (const char *str, const unsigned int inclusive, const unsigned int exclusive)
bool string_mod (char *str, const unsigned int inclusive, const unsigned int exclusive, const char replace)
bool string_check_buf (struct buffer *buf, const unsigned int inclusive, const unsigned int exclusive)
Check a buffer if it only consists of allowed characters.
const char * string_mod_const (const char *str, const unsigned int inclusive, const unsigned int exclusive, const char replace, struct gc_arena *gc)
Returns a copy of a string with certain classes of characters of it replaced with a specified character.
void string_replace_leading (char *str, const char match, const char replace)
static bool strprefix (const char *str, const char *prefix)
Return true iff str starts with prefix.
void gc_transfer (struct gc_arena *dest, struct gc_arena *src)
void x_gc_free (struct gc_arena *a)
void x_gc_freespecial (struct gc_arena *a)
static bool gc_defined (struct gc_arena *a)
static void gc_init (struct gc_arena *a)
static void gc_detach (struct gc_arena *a)
static struct gc_arena gc_new (void)
static void gc_free (struct gc_arena *a)
static void gc_reset (struct gc_arena *a)
static void check_malloc_return (const void *p)
struct buffer_list * buffer_list_new (const int max_size)
Allocate an empty buffer list of capacity max_size.
void buffer_list_free (struct buffer_list *ol)
Frees a buffer list and all the buffers in it.
bool buffer_list_defined (const struct buffer_list *ol)
Checks if the list is valid and non-empty.
void buffer_list_reset (struct buffer_list *ol)
Empty the list ol and frees all the contained buffers.
void buffer_list_push (struct buffer_list *ol, const char *str)
Allocates and appends a new buffer containing str as data to ol.
struct buffer_entry * buffer_list_push_data (struct buffer_list *ol, const void *data, size_t size)
Allocates and appends a new buffer containing data of length size.
struct buffer * buffer_list_peek (struct buffer_list *ol)
Retrieve the head buffer.
void buffer_list_advance (struct buffer_list *ol, int n)
void buffer_list_pop (struct buffer_list *ol)
void buffer_list_aggregate (struct buffer_list *bl, const size_t max)
Aggregates as many buffers as possible from bl in a new buffer of maximum length max_len .
void buffer_list_aggregate_separator (struct buffer_list *bl, const size_t max_len, const char *sep)
Aggregates as many buffers as possible from bl in a new buffer of maximum length max_len .
struct buffer_list * buffer_list_file (const char *fn, int max_line_len)
struct buffer buffer_read_from_file (const char *filename, struct gc_arena *gc)
buffer_read_from_file - copy the content of a file into a buffer
Macro Definition Documentation
ALLOC_ARRAY
#define ALLOC_ARRAY (dptr, type, n)
Value:
    { \
        check_malloc_return((dptr) = (type *) malloc(array_mult_safe(sizeof(type), (n), 0))); \
    }
Definition at line 1065 of file buffer.h.
ALLOC_ARRAY_CLEAR
#define ALLOC_ARRAY_CLEAR (dptr, type, n)
Value:
    { \
        ALLOC_ARRAY(dptr, type, n); \
        memset((dptr), 0, (array_mult_safe(sizeof(type), (n), 0))); \
    }
Definition at line 1075 of file buffer.h.
ALLOC_ARRAY_CLEAR_GC
#define ALLOC_ARRAY_CLEAR_GC (dptr, type, n, gc)
Value:
    { \
        (dptr) = (type *) gc_malloc(array_mult_safe(sizeof(type), (n), 0), true, (gc)); \
    }
Definition at line 1081 of file buffer.h.
ALLOC_ARRAY_GC
#define ALLOC_ARRAY_GC (dptr, type, n, gc)
Value:
    { \
        (dptr) = (type *) gc_malloc(array_mult_safe(sizeof(type), (n), 0), false, (gc)); \
    }
Definition at line 1070 of file buffer.h.
ALLOC_OBJ
#define ALLOC_OBJ (dptr, type)
Value:
    { \
        check_malloc_return((dptr) = (type *) malloc(sizeof(type))); \
    }
Definition at line 1054 of file buffer.h.
ALLOC_OBJ_CLEAR
#define ALLOC_OBJ_CLEAR (dptr, type)
Value:
    { \
        ALLOC_OBJ(dptr, type); \
        memset((dptr), 0, sizeof(type)); \
    }
Definition at line 1059 of file buffer.h.
ALLOC_OBJ_CLEAR_GC
#define ALLOC_OBJ_CLEAR_GC (dptr, type, gc)
Value:
    { \
        (dptr) = (type *) gc_malloc(sizeof(type), true, (gc)); \
    }
Definition at line 1096 of file buffer.h.
ALLOC_OBJ_GC
#define ALLOC_OBJ_GC (dptr, type, gc)
Value:
    { \
        (dptr) = (type *) gc_malloc(sizeof(type), false, (gc)); \
    }
Definition at line 1091 of file buffer.h.
ALLOC_VAR_ARRAY_CLEAR_GC
#define ALLOC_VAR_ARRAY_CLEAR_GC (dptr, type, atype, n, gc)
Value:
    { \
        (dptr) = (type *) gc_malloc(array_mult_safe(sizeof(atype), (n), sizeof(type)), true, (gc)); \
    }
Definition at line 1086 of file buffer.h.
BCAP
#define BCAP (buf) (buf_forward_capacity(buf))
Definition at line 130 of file buffer.h.
BDEF
#define BDEF (buf) (buf_defined(buf))
Definition at line 128 of file buffer.h.
BEND
#define BEND (buf) (buf_bend(buf))
Definition at line 125 of file buffer.h.
BLAST
#define BLAST (buf) (buf_blast(buf))
Definition at line 126 of file buffer.h.
BLEN
#define BLEN (buf) (buf_len(buf))
Definition at line 127 of file buffer.h.
BPTR
#define BPTR (buf) (buf_bptr(buf))
Definition at line 124 of file buffer.h.
BSTR
#define BSTR (buf) (buf_str(buf))
Definition at line 129 of file buffer.h.
buf_init
#define buf_init (buf, offset) buf_init_dowork(buf, offset)
Definition at line 196 of file buffer.h.
BUF_SIZE_MAX
#define BUF_SIZE_MAX 1000000
Definition at line 30 of file buffer.h.
CC_ALNUM
#define CC_ALNUM (1<<2)
Definition at line 894 of file buffer.h.
CC_ALPHA
#define CC_ALPHA (1<<3)
Definition at line 895 of file buffer.h.
CC_ANY
#define CC_ANY (1<<0)
Definition at line 891 of file buffer.h.
CC_ASCII
#define CC_ASCII (1<<4)
Definition at line 896 of file buffer.h.
CC_ASTERISK
#define CC_ASTERISK (1<<30)
Definition at line 924 of file buffer.h.
CC_AT
#define CC_AT (1<<24)
Definition at line 918 of file buffer.h.
CC_BACKSLASH
#define CC_BACKSLASH (1<<14)
Definition at line 908 of file buffer.h.
CC_BLANK
#define CC_BLANK (1<<11)
Definition at line 904 of file buffer.h.
CC_CNTRL
#define CC_CNTRL (1<<5)
Definition at line 897 of file buffer.h.
CC_COLON
#define CC_COLON (1<<19)
Definition at line 913 of file buffer.h.
CC_COMMA
#define CC_COMMA (1<<18)
Definition at line 912 of file buffer.h.
CC_CR
#define CC_CR (1<<13)
Definition at line 906 of file buffer.h.
CC_CRLF
#define CC_CRLF (CC_CR|CC_NEWLINE)
Definition at line 928 of file buffer.h.
CC_DASH
#define CC_DASH (1<<16)
Definition at line 910 of file buffer.h.
CC_DIGIT
#define CC_DIGIT (1<<6)
Definition at line 898 of file buffer.h.
CC_DOT
#define CC_DOT (1<<17)
Definition at line 911 of file buffer.h.
CC_DOUBLE_QUOTE
#define CC_DOUBLE_QUOTE (1<<22)
Definition at line 916 of file buffer.h.
CC_EQUAL
#define CC_EQUAL (1<<25)
Definition at line 919 of file buffer.h.
CC_GREATER_THAN
#define CC_GREATER_THAN (1<<27)
Definition at line 921 of file buffer.h.
CC_LESS_THAN
#define CC_LESS_THAN (1<<26)
Definition at line 920 of file buffer.h.
CC_NAME
#define CC_NAME (CC_ALNUM|CC_UNDERBAR)
Definition at line 927 of file buffer.h.
CC_NEWLINE
#define CC_NEWLINE (1<<12)
Definition at line 905 of file buffer.h.
CC_NULL
#define CC_NULL (1<<1)
Definition at line 892 of file buffer.h.
CC_PIPE
#define CC_PIPE (1<<28)
Definition at line 922 of file buffer.h.
CC_PRINT
#define CC_PRINT (1<<7)
Definition at line 899 of file buffer.h.
CC_PUNCT
#define CC_PUNCT (1<<8)
Definition at line 900 of file buffer.h.
CC_QUESTION_MARK
#define CC_QUESTION_MARK (1<<29)
Definition at line 923 of file buffer.h.
CC_REVERSE_QUOTE
#define CC_REVERSE_QUOTE (1<<23)
Definition at line 917 of file buffer.h.
CC_SINGLE_QUOTE
#define CC_SINGLE_QUOTE (1<<21)
Definition at line 915 of file buffer.h.
CC_SLASH
#define CC_SLASH (1<<20)
Definition at line 914 of file buffer.h.
CC_SPACE
#define CC_SPACE (1<<9)
Definition at line 901 of file buffer.h.
CC_UNDERBAR
#define CC_UNDERBAR (1<<15)
Definition at line 909 of file buffer.h.
CC_XDIGIT
#define CC_XDIGIT (1<<10)
Definition at line 902 of file buffer.h.
FHE_CAPS
#define FHE_CAPS 0x100 /* output hex in caps */
Definition at line 503 of file buffer.h.
FHE_SPACE_BREAK_MASK
#define FHE_SPACE_BREAK_MASK 0xFF /* space_break parameter in lower 8 bits */
Definition at line 502 of file buffer.h.
PA_BRACKET
#define PA_BRACKET (1<<0)
Definition at line 144 of file buffer.h.
verify_align_4
#define verify_align_4 (ptr)
Definition at line 990 of file buffer.h.
Function Documentation
alloc_buf()
struct buffer alloc_buf (size_t size)
Definition at line 64 of file buffer.c.
References buf_size_error(), buf_size_valid(), buffer::capacity, check_malloc_return(), buffer::data, buffer::len, and buffer::offset.
Referenced by alloc_buf_sock_tun(), auth_token_init_secret(), buffer_list_aggregate_separator(), buffer_list_push_data(), check_inline_file(), command_line_new(), fragment_frame_init(), fragment_list_buf_init(), init_context_buffers(), key_state_init(), management_query_cert(), management_query_pk_sig(), mutate_ncp_cipher_list(), openvpn_PRF(), options_string(), read_inline_file(), reliable_init(), send_line_crlf(), status_open(), stream_buf_init(), test_tls_crypt_setup(), tls_crypt_v2_extract_client_key(), tls_crypt_v2_init_client_key(), tls_session_init(), tun_show_debug(), and tuntap_dhcp_mask().
alloc_buf_gc()
struct buffer alloc_buf_gc (size_t size, struct gc_arena * gc)
Definition at line 90 of file buffer.c.
References buf_size_error(), buf_size_valid(), buffer::capacity, buffer::data, gc_malloc(), buffer::len, and buffer::offset.
Referenced by __wrap_buffer_read_from_file(), add_option(), bio_read(), buffer_read_from_file(), ce_management_query_proxy(), ce_management_query_remote(), check_incoming_control_channel(), construct_name_value(), crypto_pem_encode(), extract_command_buffer(), foreign_option(), fork_dhcp_action(), fork_register_dns_action(), format_common_name(), format_hex_ex(), format_ip_addr_string(), format_route_entry(), frame_print(), generate_auth_token(), get_device_guid(), get_device_instance_id_interface(), get_unspecified_device_guid(), get_user_pass_cr(), hostname_randomize(), ifconfig_options_string(), ifconfig_pool_read(), ipset2ascii_all(), link_socket_connection_initiated(), log_entry_print(), management_callback_send_cc_message(), management_hold(), management_query_multiline(), management_query_user_pass(), mroute_addr_print_ex(), mroute_helper_regenerate(), msg_flags_string(), multi_instance_string(), netsh_get_id(), ntlm_phase_1(), options_string_version(), options_warning_safe_ml(), packet_id_net_print(), packet_id_persist_print(), platform_gen_path(), plugin_mask_string(), prepend_dir(), print_argv(), print_default_gateway(), print_in6_addr(), print_in_addr_t(), print_key_id(), print_link_socket_actual_ex(), print_netmask(), print_opt_route(), print_opt_route_gateway(), print_opt_route_gateway_dhcp(), print_opt_topology(), print_sockaddr_ex(), print_str(), print_str_int(), proto2ascii_all(), protocol_dump(), push_peer_info(), read_control_auth(), reliable_ack_print(), reliable_print_ids(), route_string(), send_auth_failed(), send_auth_pending_messages(), send_push_reply(), send_push_reply_auth_token(), server_pushed_info(), setenv_format_indexed_name(), setenv_route(), setenv_route_addr(), setenv_route_ipv6(), socket_stat(), strerror_win32(), system_error_message(), tap_win_getinfo(), test_buffer_free_gc_one(), test_buffer_free_gc_two(), test_crypto(), test_tls_crypt_v2_setup(), time_string(), tls_crypt_v2_wrap_client_key(), tls_crypt_v2_wrap_unwrap_dst_too_small(), tls_crypt_v2_wrap_unwrap_max_metadata(), tls_crypt_v2_wrap_unwrap_no_metadata(), tls_crypt_v2_write_client_key_file(), tun_stat(), tv_string(), username_password_as_base64(), wide_cmd_line(), win32_version_string(), window_title_generate(), write_key_file(), x509_get_sha1_fingerprint(), and x509_get_sha256_fingerprint().
array_mult_safe()
size_t array_mult_safe (const size_t m1, const size_t m2, const size_t extra)
Definition at line 43 of file buffer.c.
References M_FATAL, msg, and unlikely.
buf_advance()
static bool buf_advance (struct buffer * buf, int size) inline static
Definition at line 623 of file buffer.h.
References buf_valid(), buffer::len, and buffer::offset.
Referenced by buf_copy_excess(), buf_read_u8(), buf_string_compare_advance(), buffer_list_advance(), extract_command_buffer(), handle_data_channel_packet(), is_ipv_X(), key_method_2_read(), link_socket_write_post_size_adjust(), mroute_extract_addr_ether(), mss_fixup_ipv4(), mss_fixup_ipv6(), openvpn_decrypt_aead(), openvpn_decrypt_v1(), process_received_occ_msg(), read_control_auth(), receive_auth_failed(), receive_cr_response(), server_pushed_info(), server_pushed_signal(), tls_crypt_unwrap(), tls_crypt_v2_extract_client_key(), tls_crypt_v2_unwrap_client_key(), tls_pre_decrypt(), and vlan_decapsulate().
buf_assign()
bool buf_assign (struct buffer * dest, const struct buffer * src)
Definition at line 175 of file buffer.c.
References BLEN, BPTR, buf_init, buf_write(), dest, and buffer::offset.
Referenced by buffer_turnover().
buf_bend()
static uint8_t* buf_bend (const struct buffer * buf) inline static
Definition at line 253 of file buffer.h.
References buf_bptr(), and buf_len().
buf_blast()
static uint8_t* buf_blast (const struct buffer * buf) inline static
Definition at line 259 of file buffer.h.
References buf_bptr(), and buf_len().
buf_bptr()
static uint8_t* buf_bptr (const struct buffer * buf) inline static
Definition at line 227 of file buffer.h.
References buf_valid(), buffer::data, and buffer::offset.
Referenced by buf_bend(), buf_blast(), buf_str(), management_query_cert(), and management_query_pk_sig().
buf_catrunc()
void buf_catrunc (struct buffer * buf, const char * str)
Definition at line 318 of file buffer.c.
References buf_forward_capacity(), buf_forward_capacity_total(), buffer::capacity, buffer::data, buffer::len, and strncpynt().
Referenced by format_hex_ex().
buf_chomp()
void buf_chomp (struct buffer * buf)
Definition at line 570 of file buffer.c.
References BLAST, buf_inc_len(), buf_null_terminate(), CC_CRLF, CC_NULL, and char_class().
Referenced by command_line_get(), and extract_command_buffer().
buf_clear()
void buf_clear (struct buffer * buf)
Definition at line 164 of file buffer.c.
References buffer::capacity, buffer::data, buffer::len, buffer::offset, and secure_memzero().
Referenced by command_line_add(), command_line_next(), command_line_reset(), do_close_free_key_schedule(), key_method_2_read(), openvpn_PRF(), read_control_auth(), read_inline_file(), read_key_file(), read_pem_key_file(), tls_crypt_fail_msg_too_long(), tls_crypt_fail_replay(), tls_crypt_ignore_replay(), tls_crypt_loopback_max_len(), tls_crypt_loopback_zero_len(), tls_crypt_v2_unwrap_client_key(), tls_crypt_v2_write_client_key_file(), write_key_file(), and write_pem_key_file().
buf_copy()
static bool buf_copy (struct buffer * dest, const struct buffer * src) inline static
Definition at line 718 of file buffer.h.
References BLEN, BPTR, buf_write(), and dest.
Referenced by buf_copy_excess(), buffer_list_aggregate_separator(), command_line_next(), fragment_outgoing(), read_control_auth(), read_inline_file(), socket_send_queue(), stream_buf_read_setup_dowork(), tls_crypt_v2_unwrap_client_key(), tls_crypt_v2_wrap_client_key(), tls_pre_decrypt(), tls_rec_payload(), tun_write_queue(), and write_control_auth().
buf_copy_excess()
static bool buf_copy_excess (struct buffer * dest, struct buffer * src, int len) inline static
Definition at line 759 of file buffer.h.
References buf_advance(), buf_copy(), dest, and buffer::len.
Referenced by command_line_get(), and stream_buf_added().
buf_copy_n()
static bool buf_copy_n (struct buffer * dest, struct buffer * src, int n) inline static
Definition at line 724 of file buffer.h.
References buf_read_alloc(), buf_write(), and dest.
Referenced by fragment_ready_to_send(), and ipv6_send_icmp_unreachable().
buf_copy_range()
static bool buf_copy_range (struct buffer * dest, int dest_index, const struct buffer * src, int src_index, int src_len) inline static
Definition at line 735 of file buffer.h.
References buffer::data, dest, buffer::len, and buffer::offset.
Referenced by fragment_incoming().
buf_defined()
static bool buf_defined (const struct buffer * buf) inline static
Definition at line 215 of file buffer.h.
References buffer::data.
Referenced by buf_printf(), recv_line(), socks_process_outgoing_udp(), status_close(), status_flush(), status_read(), stream_buf_get_final(), and stream_buf_get_next().
buf_equal()
static bool buf_equal (const struct buffer * a, const struct buffer * b) inline static
Return true if buffer contents are equal.
Definition at line 843 of file buffer.h.
References BLEN, and BPTR.
Referenced by tls_crypt_v2_wrap_unwrap_max_metadata().
buf_forward_capacity()
static int buf_forward_capacity (const struct buffer * buf) inline static
Definition at line 546 of file buffer.h.
References buf_valid(), buffer::capacity, buffer::len, and buffer::offset.
Referenced by bio_read(), buf_catrunc(), buf_printf(), buf_puts(), mutate_ncp_cipher_list(), and tls_crypt_v2_wrap_client_key().
buf_forward_capacity_total()
static int buf_forward_capacity_total (const struct buffer * buf) inline static
Definition at line 564 of file buffer.h.
References buf_valid(), buffer::capacity, and buffer::offset.
Referenced by buf_catrunc(), and read_control_auth().
buf_inc_len()
static bool buf_inc_len (struct buffer * buf, int inc) inline static
Definition at line 595 of file buffer.h.
References buf_safe_bidir(), and buffer::len.
Referenced by buf_chomp(), buf_null_terminate(), buffer_read_from_file(), generate_ephemeral_key(), openvpn_decrypt_aead(), openvpn_decrypt_v1(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), status_read(), tls_crypt_unwrap(), tls_crypt_v2_extract_client_key(), tls_crypt_v2_unwrap_client_key(), tls_crypt_v2_wrap_client_key(), tls_crypt_v2_wrap_too_long_metadata(), tls_crypt_v2_write_client_key_file(), tls_crypt_wrap(), x509_get_sha1_fingerprint(), and x509_get_sha256_fingerprint().
buf_init_dowork()
static bool buf_init_dowork (struct buffer * buf, int offset) inline static
Definition at line 306 of file buffer.h.
References buffer::capacity, buffer::data, buffer::len, and buffer::offset.
buf_len()
static int buf_len (const struct buffer * buf) static
Definition at line 240 of file buffer.h.
References buf_valid(), and buffer::len.
Referenced by buf_bend(), buf_blast(), command_line_new(), mutate_ncp_cipher_list(), tls_crypt_unwrap(), and tls_crypt_v2_unwrap_client_key().
buf_null_terminate()
void buf_null_terminate (struct buffer * buf)
Definition at line 549 of file buffer.c.
References BLAST, buf_inc_len(), buf_safe(), and buf_write_u8().
Referenced by buf_chomp(), buffer_read_from_file(), mutate_ncp_cipher_list(), and status_read().
buf_parse()
bool buf_parse (struct buffer * buf, const int delim, char * line, const int size)
Definition at line 841 of file buffer.c.
References ASSERT, and buf_read_u8().
Referenced by apply_push_options(), get_auth_challenge(), get_user_pass_cr(), ifconfig_pool_read(), in_src_get(), make_inline_array(), man_kill(), options_warning_extract_parm1(), options_warning_safe_scan1(), options_warning_safe_scan2(), output_peer_info_env(), push_update_digest(), and read_config_string().
buf_prepend()
static uint8_t* buf_prepend (struct buffer * buf, int size) inline static
Definition at line 611 of file buffer.h.
References BPTR, buf_valid(), buffer::len, and buffer::offset.
Referenced by buf_sub(), buf_write_alloc_prepend(), buf_write_prepend(), openvpn_encrypt_v1(), and vlan_encapsulate().
buf_printf()
bool buf_printf (struct buffer * buf, const char * format, ...)
Definition at line 245 of file buffer.c.
References BEND, buf_defined(), buf_forward_capacity(), buffer::capacity, buffer::data, and buffer::len.
Referenced by add_option(), ce_management_query_proxy(), ce_management_query_remote(), check_inline_file(), construct_name_value(), foreign_option(), fork_dhcp_action(), fork_register_dns_action(), format_common_name(), format_hex_ex(), format_ip_addr_string(), format_route_entry(), frame_print(), get_device_guid(), get_unspecified_device_guid(), get_user_pass_cr(), hostname_randomize(), ifconfig_options_string(), ipset2ascii_all(), link_socket_connection_initiated(), log_entry_print(), management_callback_send_cc_message(), management_hold(), management_query_multiline(), management_query_user_pass(), mroute_addr_print_ex(), mroute_helper_regenerate(), msg_flags_string(), multi_instance_string(), ntlm_phase_1(), options_string(), options_warning_safe_ml(), packet_id_net_print(), packet_id_persist_print(), platform_gen_path(), plugin_mask_string(), prepend_dir(), print_argv(), print_default_gateway(), print_in6_addr(), print_in_addr_t(), print_key_id(), print_link_socket_actual_ex(), print_netmask(), print_opt_route(), print_opt_route_gateway(), print_opt_route_gateway_dhcp(), print_opt_topology(), print_sockaddr_ex(), print_str(), print_str_int(), proto2ascii_all(), protocol_dump(), push_peer_info(), read_inline_file(), reliable_ack_print(), reliable_print_ids(), route_string(), send_auth_failed(), send_auth_pending_messages(), send_push_options(), send_push_reply(), send_push_reply_auth_token(), server_pushed_info(), setenv_format_indexed_name(), setenv_route(), setenv_route_addr(), setenv_route_ipv6(), setenv_str_safe(), socket_stat(), strerror_win32(), system_error_message(), time_string(), tun_stat(), tv_string(), username_password_as_base64(), wide_cmd_line(), win32_version_string(), window_title_generate(), and write_key_file().
buf_puts()
bool buf_puts (struct buffer * buf, const char * str)
Definition at line 272 of file buffer.c.
References BEND, buf_forward_capacity(), buffer::capacity, buffer::data, buffer::len, and strncpynt().
Referenced by mutate_ncp_cipher_list(), and print_sockaddr_ex().
buf_read()
static bool buf_read (struct buffer * src, void * dest, int size) inline static
Definition at line 784 of file buffer.h.
References buf_read_alloc(), and dest.
Referenced by auth_token_init_secret(), buf_read_u16(), buf_read_u32(), fragment_incoming(), key_source2_read(), packet_id_read(), protocol_dump(), read_key(), read_string(), read_string_alloc(), reliable_ack_print(), reliable_ack_read(), reliable_ack_read_packet_id(), session_id_read(), socks_process_incoming_udp(), stream_buf_added(), and tls_crypt_v2_init_client_key().
buf_read_alloc()
static uint8_t* buf_read_alloc (struct buffer * buf, int size) inline static
Definition at line 659 of file buffer.h.
References BPTR, buffer::len, and buffer::offset.
Referenced by buf_copy_n(), buf_read(), key_des_check(), and key_des_fixup().
buf_read_u16()
static int buf_read_u16 (struct buffer * buf) inline static
Definition at line 809 of file buffer.h.
References buf_read().
Referenced by process_received_occ_msg(), read_string(), read_string_alloc(), and socks_process_incoming_udp().
buf_read_u32()
static uint32_t buf_read_u32 (struct buffer * buf, bool * good) inline static
Definition at line 820 of file buffer.h.
References buf_read().
buf_read_u8()
static int buf_read_u8 (struct buffer * buf) inline static
Definition at line 796 of file buffer.h.
References BLEN, BPTR, and buf_advance().
Referenced by buf_parse(), buf_substring_len(), init_static(), key_method_2_read(), process_incoming_push_reply(), process_received_occ_msg(), receive_cr_response(), server_pushed_info(), server_pushed_signal(), socks_process_incoming_udp(), status_read(), and tls_crypt_v2_verify_metadata().
buf_reset()
static void buf_reset (struct buffer * buf) inline static
Definition at line 290 of file buffer.h.
References buffer::capacity, buffer::data, buffer::len, and buffer::offset.
Referenced by multi_process_drop_outgoing_tun(), multi_tcp_process_outgoing_link(), process_incoming_link_part1(), process_incoming_link_part2(), process_incoming_tun(), process_outgoing_link(), process_outgoing_tun(), status_open(), and stream_buf_reset().
buf_reset_len()
static void buf_reset_len (struct buffer * buf) inline static
Definition at line 299 of file buffer.h.
References buffer::len, and buffer::offset.
Referenced by multi_process_incoming_tun(), send_push_options(), and send_push_reply().
buf_reverse_capacity()
static int buf_reverse_capacity (const struct buffer * buf) inline static
Definition at line 582 of file buffer.h.
References buf_valid(), and buffer::offset.
Referenced by vlan_encapsulate().
buf_rmtail()
void buf_rmtail (struct buffer * buf, uint8_t remove)
Definition at line 534 of file buffer.c.
References BLAST, and buffer::len.
buf_safe()
static bool buf_safe (const struct buffer * buf, int len) inline static
Definition at line 525 of file buffer.h.
References buf_size_valid(), buf_valid(), buffer::capacity, buffer::len, and buffer::offset.
Referenced by alloc_buf_sock_tun(), buf_null_terminate(), buf_write_alloc(), build_dhcp_options_string(), check_ping_send_dowork(), check_send_occ_msg_dowork(), ipv6_send_icmp_unreachable(), openvpn_decrypt_aead(), openvpn_decrypt_v1(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), push_peer_info(), read_incoming_tun(), read_inline_file(), stream_buf_set_next(), tls_crypt_unwrap(), tls_crypt_wrap(), write_dhcp_search_str(), write_dhcp_str(), write_dhcp_u32_array(), and write_dhcp_u8().
buf_safe_bidir()
static bool buf_safe_bidir (const struct buffer * buf, int len) inline static
Definition at line 532 of file buffer.h.
References buf_size_valid_signed(), buf_valid(), buffer::capacity, buffer::len, and buffer::offset.
Referenced by buf_inc_len().
buf_set_read()
static void buf_set_read (struct buffer * buf, const uint8_t * data, int size) inline static
Definition at line 335 of file buffer.h.
References buf_size_error(), buf_size_valid(), buffer::capacity, buffer::data, buffer::len, and buffer::offset.
Referenced by crypto_pem_encode_decode_loopback(), get_auth_challenge(), get_user_pass_cr(), key_des_check(), key_des_fixup(), make_inline_array(), man_kill(), openvpn_decrypt_v1(), output_peer_info_env(), read_config_string(), read_key_file(), read_pem_key_file(), string_alloc_buf(), and write_pem_key_file().
buf_set_write()
static void buf_set_write (struct buffer * buf, uint8_t * data, int size) inline static
Definition at line 318 of file buffer.h.
References buf_size_error(), buf_size_valid(), buffer::capacity, buffer::data, buffer::len, and buffer::offset.
Referenced by crypto_pem_encode_decode_loopback(), get_device_guid(), get_unspecified_device_guid(), get_user_pass_cr(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), setenv_str_safe(), tls_crypt_v2_init_server_key(), and tls_crypt_v2_unwrap_client_key().
buf_size_error()
void buf_size_error (const size_t size)
Definition at line 55 of file buffer.c.
References M_FATAL, and msg.
Referenced by alloc_buf(), alloc_buf_gc(), buf_set_read(), and buf_set_write().
buf_size_valid()
static bool buf_size_valid (const size_t size) inline static
Definition at line 272 of file buffer.h.
References BUF_SIZE_MAX, and likely.
Referenced by alloc_buf(), alloc_buf_gc(), buf_safe(), buf_set_read(), and buf_set_write().
buf_size_valid_signed()
static bool buf_size_valid_signed (const int size) inline static
Definition at line 278 of file buffer.h.
References BUF_SIZE_MAX, and likely.
Referenced by buf_safe_bidir().
buf_str()
static char* buf_str (const struct buffer * buf) inline static
Definition at line 284 of file buffer.h.
References buf_bptr().
Referenced by mutate_ncp_cipher_list().
buf_string_compare_advance()
bool buf_string_compare_advance (struct buffer * src, const char * match)
Definition at line 805 of file buffer.c.
References buf_advance(), buf_string_match_head_str(), and match().
Referenced by process_incoming_push_msg(), and receive_auth_failed().
buf_string_match()
static bool buf_string_match (const struct buffer * src, const void * match, int size) inline static
Compare src buffer contents with match.
NOT constant time. Do not use when comparing HMACs.
Definition at line 853 of file buffer.h.
References BPTR, buffer::len, and match().
Referenced by is_ping_msg().
buf_string_match_head()
static bool buf_string_match_head (const struct buffer * src, const void * match, int size) inline static
Compare first size bytes of src buffer contents with match.
NOT constant time. Do not use when comparing HMACs.
Definition at line 867 of file buffer.h.
References BPTR, buffer::len, and match().
Referenced by is_occ_msg().
buf_string_match_head_str()
bool buf_string_match_head_str (const struct buffer * src, const char * match)
Definition at line 794 of file buffer.c.
References BPTR, buffer::len, and match().
Referenced by buf_string_compare_advance(), parse_incoming_control_channel_command(), and receive_auth_failed().
buf_sub()
struct buffer buf_sub (struct buffer * buf, int size, bool prepend)
Definition at line 226 of file buffer.c.
References buf_prepend(), buf_write_alloc(), buffer::capacity, CLEAR, and buffer::data.
Referenced by reliable_ack_write(), and socks_process_outgoing_udp().
buf_substring_len()
int buf_substring_len (const struct buffer * buf, int delim)
Definition at line 819 of file buffer.c.
References buf_read_u8().
Referenced by command_line_get().
buf_valid()
static bool buf_valid (const struct buffer * buf) inline static
Definition at line 221 of file buffer.h.
References buffer::data, buffer::len, and likely.
Referenced by buf_advance(), buf_bptr(), buf_forward_capacity(), buf_forward_capacity_total(), buf_len(), buf_prepend(), buf_reverse_capacity(), buf_safe(), buf_safe_bidir(), connection_entry_preload_key(), read_key_file(), and read_pem_key_file().
buf_write()
static bool buf_write (struct buffer * dest, const void * src, int size) inline static
Definition at line 673 of file buffer.h.
References buf_write_alloc(), and dest.
Referenced by __wrap_buffer_read_from_file(), buf_assign(), buf_copy(), buf_copy_n(), buf_write_u16(), buf_write_u32(), buf_write_u8(), buffer_list_aggregate_separator(), check_ping_send_dowork(), check_send_occ_msg_dowork(), crypto_pem_encode(), extract_command_buffer(), generate_auth_token(), management_query_cert(), management_query_pk_sig(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), openvpn_PRF(), packet_id_write(), random_bytes_to_buf(), read_wintun(), reliable_ack_write(), send_line_crlf(), session_id_write(), socks_process_outgoing_udp(), test_tls_crypt_setup(), tls_crypt_v2_wrap_client_key(), tls_crypt_v2_write_client_key_file(), write_control_auth(), write_dhcp_search_str(), write_dhcp_str(), write_key(), and write_string().
buf_write_alloc()
static uint8_t* buf_write_alloc (struct buffer * buf, int size) inline static
Definition at line 640 of file buffer.h.
References BPTR, buf_safe(), and buffer::len.
Referenced by buf_sub(), buf_write(), buf_write_alloc_prepend(), crypto_pem_decode(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), test_crypto(), tls_crypt_fail_msg_too_long(), tls_crypt_loopback_max_len(), tls_crypt_v2_wrap_client_key(), tls_crypt_v2_wrap_unwrap_dst_too_small(), tls_crypt_v2_wrap_unwrap_max_metadata(), and tls_crypt_wrap().
buf_write_alloc_prepend()
static uint8_t* buf_write_alloc_prepend (struct buffer * buf, int size, bool prepend) inline static
Definition at line 653 of file buffer.h.
References buf_prepend(), and buf_write_alloc().
buf_write_prepend()
static bool buf_write_prepend (struct buffer * dest, const void * src, int size) inline static
Definition at line 685 of file buffer.h.
References buf_prepend(), and dest.
Referenced by fragment_prepend_flags(), ipv6_send_icmp_unreachable(), link_socket_write_tcp(), openvpn_encrypt_v1(), packet_id_write(), reliable_mark_active_outgoing(), session_id_write_prepend(), tls_prepend_opcode_v1(), tls_prepend_opcode_v2(), and write_control_auth().
buf_write_u16()
static bool buf_write_u16 (struct buffer * dest, int data) inline static
Definition at line 704 of file buffer.h.
References buf_write(), buffer::data, and dest.
Referenced by check_send_occ_msg_dowork(), socks_process_outgoing_udp(), write_empty_string(), and write_string().
buf_write_u32()
static bool buf_write_u32 (struct buffer * dest, int data) inline static
Definition at line 711 of file buffer.h.
References buf_write(), buffer::data, and dest.
Referenced by build_dhcp_options_string(), key_method_2_write(), and write_dhcp_u32_array().
buf_write_u8()
static bool buf_write_u8 (struct buffer * dest, int data) inline static
Definition at line 697 of file buffer.h.
References buf_write(), buffer::data, and dest.
Referenced by buf_null_terminate(), build_dhcp_options_string(), check_send_occ_msg_dowork(), command_line_add(), generate_auth_token(), key_method_2_write(), recv_line(), socks_process_outgoing_udp(), status_read(), write_dhcp_search_str(), write_dhcp_str(), write_dhcp_u32_array(), and write_dhcp_u8().
buffer_list_advance()
void buffer_list_advance (struct buffer_list * ol, int n)
Definition at line 1358 of file buffer.c.
References ASSERT, BLEN, buffer_entry::buf, buf_advance(), buffer_list_pop(), and buffer_list::head.
Referenced by init_static(), and man_write().
buffer_list_aggregate()
void buffer_list_aggregate (struct buffer_list * bl, const size_t max)
Aggregates as many buffers as possible from bl in a new buffer of maximum length max_len .
All the aggregated buffers are removed from the list and replaced by the new one, followed by any additional (non-aggregated) data.
Parameters
bl the list of buffer to aggregate
max the maximum length of the aggregated buffer
Definition at line 1335 of file buffer.c.
References buffer_list_aggregate_separator().
Referenced by init_static(), man_write(), and management_query_multiline_flatten().
buffer_list_aggregate_separator()
void buffer_list_aggregate_separator (struct buffer_list * bl, const size_t max_len, const char * sep)
Aggregates as many buffers as possible from bl in a new buffer of maximum length max_len .
sep is written after each copied buffer (also after the last one). All the aggregated buffers are removed from the list and replaced by the new one, followed by any additional (non-aggregated) data. Nothing happens if max_len is not enough to aggregate at least 2 buffers.
Parameters
bl the list of buffer to aggregate
max_len the maximum length of the aggregated buffer
sep the separator to put between buffers during aggregation
Definition at line 1289 of file buffer.c.
References alloc_buf(), ALLOC_OBJ_CLEAR, BLEN, buffer_entry::buf, buf_copy(), buf_write(), http-client::f, free_buf(), buffer_list::head, buffer_entry::next, buffer_list::size, and buffer_list::tail.
Referenced by buffer_list_aggregate(), management_query_multiline_flatten_newline(), test_buffer_list_aggregate_separator_all(), test_buffer_list_aggregate_separator_empty(), test_buffer_list_aggregate_separator_emptybuffers(), test_buffer_list_aggregate_separator_noop(), test_buffer_list_aggregate_separator_nosep(), test_buffer_list_aggregate_separator_two(), and test_buffer_list_aggregate_separator_zerolen().
buffer_list_defined()
bool buffer_list_defined (const struct buffer_list * ol)
Checks if the list is valid and non-empty.
Parameters
ol the list to check
Returns
true iff ol is not NULL and contains at least one buffer
Definition at line 1214 of file buffer.c.
References buffer_list::head.
Referenced by man_update_io_state(), management_query_multiline_flatten(), and management_query_multiline_flatten_newline().
buffer_list_file()
struct buffer_list* buffer_list_file (const char * fn, int max_line_len)
Definition at line 1372 of file buffer.c.
References buffer_list_new(), buffer_list_push(), and platform_fopen().
buffer_list_free()
void buffer_list_free (struct buffer_list * ol)
Frees a buffer list and all the buffers in it.
Parameters
ol the list to free
Definition at line 1204 of file buffer.c.
References buffer_list_reset().
Referenced by in_extra_dispatch(), in_extra_reset(), init_static(), key_state_free(), man_connection_close(), management_query_multiline_flatten(), management_query_multiline_flatten_newline(), and test_buffer_list_teardown().
buffer_list_new()
struct buffer_list* buffer_list_new (const int max_size)
Allocate an empty buffer list of capacity max_size.
Parameters
max_size the capacity of the list to allocate
Returns
the new list
Definition at line 1194 of file buffer.c.
References ALLOC_OBJ_CLEAR, buffer_list::max_size, and buffer_list::size.
Referenced by buffer_list_file(), in_extra_reset(), init_static(), man_connection_init(), test_buffer_list_setup(), and tls_send_payload().
buffer_list_peek()
struct buffer* buffer_list_peek (struct buffer_list * ol)
Retrieve the head buffer.
Parameters
ol the list to retrieve the buffer from
Returns
a pointer to the head buffer or NULL if the list is empty
Definition at line 1276 of file buffer.c.
References buffer_entry::buf, and buffer_list::head.
Referenced by flush_payload_buffer(), init_static(), man_write(), management_query_multiline_flatten(), management_query_multiline_flatten_newline(), test_buffer_list_aggregate_separator_all(), test_buffer_list_aggregate_separator_emptybuffers(), test_buffer_list_aggregate_separator_noop(), test_buffer_list_aggregate_separator_nosep(), test_buffer_list_aggregate_separator_two(), and test_buffer_list_aggregate_separator_zerolen().
buffer_list_pop()
void buffer_list_pop (struct buffer_list * ol)
Definition at line 1341 of file buffer.c.
References buffer_entry::buf, free_buf(), buffer_list::head, buffer_entry::next, buffer_list::size, and buffer_list::tail.
Referenced by buffer_list_advance(), and flush_payload_buffer().
buffer_list_push()
void buffer_list_push (struct buffer_list * ol, const char * str)
Allocates and appends a new buffer containing str as data to ol.
Parameters
ol the list to append the new buffer to
str the string to copy into the new buffer
Definition at line 1235 of file buffer.c.
References buffer_entry::buf, buffer_list_push_data(), and buffer::len.
Referenced by buffer_list_file(), init_static(), man_output_list_push_str(), man_read(), test_buffer_list_full(), and test_buffer_list_setup().
buffer_list_push_data()
struct buffer_entry* buffer_list_push_data (struct buffer_list * ol, const void * data, size_t size)
Allocates and appends a new buffer containing data of length size.
Parameters
ol the list to append the new buffer to
data the data to copy into the new buffer
size the length of data to copy into the buffer
Returns
the new buffer
Definition at line 1249 of file buffer.c.
References alloc_buf(), ALLOC_OBJ_CLEAR, ASSERT, buffer_entry::buf, buffer::data, buffer_list::head, buffer::len, buffer_list::max_size, buffer_entry::next, buffer_list::size, and buffer_list::tail.
Referenced by buffer_list_push(), test_buffer_list_setup(), and tls_send_payload().
buffer_list_reset()
void buffer_list_reset (struct buffer_list * ol)
Empty the list ol and frees all the contained buffers.
Parameters
ol the list to reset
Definition at line 1220 of file buffer.c.
References buffer_entry::buf, free_buf(), buffer_list::head, buffer_entry::next, buffer_list::size, and buffer_list::tail.
Referenced by buffer_list_free(), man_new_connection_post(), man_read(), and man_reset_client_socket().
buffer_read_from_file()
struct buffer buffer_read_from_file (const char * filename, struct gc_arena * gc)
buffer_read_from_file - copy the content of a file into a buffer
Parameters
file path to the file to read
gc the garbage collector to use when allocating the buffer. It is passed to alloc_buf_gc() and therefore can be NULL.
Returns
the buffer storing the file content or an invalid buffer in case of error
Definition at line 1395 of file buffer.c.
References alloc_buf_gc(), ASSERT, BPTR, buf_inc_len(), buf_null_terminate(), free_buf_gc(), platform_fopen(), platform_stat(), and ssize_t.
Referenced by connection_entry_preload_key(), read_key_file(), and read_pem_key_file().
buffer_write_file()
bool buffer_write_file (const char * filename, const struct buffer * buf)
Write buffer contents to file.
Parameters
filename The filename to write the buffer to.
buf The buffer to write to the file.
Returns
true on success, false otherwise.
Definition at line 349 of file buffer.c.
References BLEN, BPTR, M_ERRNO, msg, platform_open(), S_IRUSR, S_IWUSR, and write.
Referenced by tls_crypt_v2_verify_metadata(), tls_crypt_v2_write_client_key_file(), write_key_file(), and write_pem_key_file().
char_class()
bool char_class (const unsigned char c, const unsigned int flags)
Definition at line 893 of file buffer.c.
References CC_ALNUM, CC_ALPHA, CC_ANY, CC_ASCII, CC_ASTERISK, CC_AT, CC_BACKSLASH, CC_BLANK, CC_CNTRL, CC_COLON, CC_COMMA, CC_CR, CC_DASH, CC_DIGIT, CC_DOT, CC_DOUBLE_QUOTE, CC_EQUAL, CC_GREATER_THAN, CC_LESS_THAN, CC_NEWLINE, CC_NULL, CC_PIPE, CC_PRINT, CC_PUNCT, CC_QUESTION_MARK, CC_REVERSE_QUOTE, CC_SINGLE_QUOTE, CC_SLASH, CC_SPACE, CC_UNDERBAR, and CC_XDIGIT.
Referenced by buf_chomp(), char_inc_exc(), and command_line_add().
check_malloc_return()
static void check_malloc_return (const void * p) inline static
Definition at line 1102 of file buffer.h.
References out_of_memory().
Referenced by alloc_buf(), cipher_ctx_new(), clone_buf(), do_setenv_x509(), env_block(), err_put_ms_error(), gc_addspecial(), gc_malloc(), hmac_ctx_new(), management_query_multiline_flatten(), management_query_multiline_flatten_newline(), md_ctx_new(), prng_init(), read_string_alloc(), ssl_ctx_set_rsakey(), string_alloc(), tls_ctx_use_external_rsa_key(), wide_cmd_line(), and x509_setenv().
chomp()
void chomp (char * str)
Definition at line 630 of file buffer.c.
References rm_trailing_chars().
Referenced by establish_http_proxy_passthru(), get_console_input(), get_console_input_win32(), get_proxy_authenticate(), get_user_pass_cr(), make_inline_array(), output_peer_info_env(), and status_printf().
clear_buf()
static struct buffer clear_buf (void) inline static
Return an empty struct buffer.
Definition at line 209 of file buffer.h.
Referenced by get_device_guid(), get_unspecified_device_guid(), management_query_multiline(), read_control_auth(), test_crypto(), write_control_auth(), and write_pem_key_file().
clone_buf()
struct buffer clone_buf (const struct buffer * buf)
Definition at line 117 of file buffer.c.
References BLEN, BPTR, buffer::capacity, check_malloc_return(), buffer::data, buffer::len, and buffer::offset.
Referenced by mbuf_alloc_buf(), and tls_pre_decrypt_lite().
convert_to_one_line()
void convert_to_one_line (struct buffer * buf)
Definition at line 334 of file buffer.c.
References BLEN, BPTR, and buffer::len.
format_hex()
static char* format_hex (const uint8_t * data, int size, int maxoutput, struct gc_arena * gc) inline static
Definition at line 510 of file buffer.h.
References format_hex_ex().
Referenced by establish_http_proxy_passthru(), extract_command_buffer(), fixup_key(), generate_key_random(), init_key_ctx(), init_static(), key2_print(), key_source_print(), openvpn_decrypt_aead(), openvpn_decrypt_v1(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), protocol_dump(), session_id_print(), tls1_P_hash(), tls1_PRF(), tls_crypt_unwrap(), tls_crypt_v2_unwrap_client_key(), tls_crypt_v2_wrap_client_key(), tls_crypt_wrap(), and tuntap_dhcp_mask().
format_hex_ex()
char* format_hex_ex (const uint8_t * data, int size, int maxoutput, unsigned int space_break_flags, const char * separator, struct gc_arena * gc)
Definition at line 499 of file buffer.c.
References alloc_buf_gc(), buf_catrunc(), buf_printf(), buffer::data, FHE_CAPS, FHE_SPACE_BREAK_MASK, and static_assert.
Referenced by backend_x509_get_serial_hex(), format_hex(), hostname_randomize(), key_state_export_keying_material(), mroute_addr_print_ex(), print_default_gateway(), push_peer_info(), read_key_file(), show_adapter(), verify_cert_set_env(), write_key_file(), and x509_setenv_track().
free_buf()
void free_buf (struct buffer * buf)
Definition at line 185 of file buffer.c.
References CLEAR, and buffer::data.
Referenced by auth_token_init_secret(), buffer_list_aggregate_separator(), buffer_list_pop(), buffer_list_reset(), check_inline_file(), command_line_free(), do_close_free_key_schedule(), fragment_free(), fragment_list_buf_free(), free_context_buffers(), key_state_free(), link_socket_close(), management_query_cert(), management_query_pk_sig(), mbuf_free_buf(), mutate_ncp_cipher_list(), openvpn_PRF(), overlapped_io_close(), read_inline_file(), reliable_free(), send_line_crlf(), status_close(), stream_buf_close(), test_tls_crypt_teardown(), tls_crypt_v2_write_client_key_file(), tls_pre_decrypt_lite(), tls_wrap_free(), tun_show_debug(), and tuntap_dhcp_mask().
gc_addspecial()
void gc_addspecial (void * addr, void(*)(void *) free_function, struct gc_arena * a)
Definition at line 454 of file buffer.c.
References gc_entry_special::addr, ASSERT, check_malloc_return(), gc_entry_special::free_fnc, gc_arena::list_special, and gc_entry_special::next.
Referenced by do_preresolve_host(), and init_route_list().
gc_defined()
static bool gc_defined (struct gc_arena * a) inline static
Definition at line 1005 of file buffer.h.
References gc_arena::list.
gc_detach()
static void gc_detach (struct gc_arena * a) inline static
Definition at line 1018 of file buffer.h.
References gc_init().
Referenced by inherit_context_top(), and options_detach().
gc_free()
static void gc_free (struct gc_arena * a) inline static
Definition at line 1032 of file buffer.h.
References gc_arena::list, gc_arena::list_special, x_gc_free(), and x_gc_freespecial().
Referenced by adapter_index_of_ip(), add_option(), add_route(), add_route_ipapi(), add_route_ipv6(), argv_free(), argv_msg(), argv_msg_prefix(), argv_str__empty_argv__empty_output(), argv_str__multiple_argv__correct_output(), bio_read(), block_dns_msg_handler(), ccs_gen_config_file(), ccs_gen_deferred_ret_file(), ce_management_query_proxy(), ce_management_query_remote(), check_addr_clash(), check_file_access_chroot(), check_incoming_control_channel(), check_stale_routes(), check_subnet_conflict(), clear_route_ipv6_list(), clear_route_list(), close_instance(), close_tun(), context_gc_free(), crypto_pem_encode_decode_loopback(), del_route_ipapi(), delete_route(), delete_route_ipv6(), delete_temp_addresses(), dhcp_extract_router_msg(), dhcp_masq_addr(), dhcp_release_by_adapter_index(), dhcp_renew_by_adapter_index(), dhcp_status(), do_address_service(), do_close_tun(), do_compute_occ_strings(), do_dns_domain_service(), do_dns_service(), do_ifconfig_ipv4(), do_ifconfig_ipv6(), do_ifconfig_setenv(), do_open_tun(), do_route_service(), do_set_mtu_service(), drop_if_recursive_routing(), establish_http_proxy_passthru(), find_certificate_in_store(), fixup_key(), foreign_option(), fork_dhcp_action(), fork_register_dns_action(), frame_print(), gc_reset(), generate_auth_token(), generate_key_random(), generate_prefix(), get_adapter_index_flexible(), get_adapter_index_method_2(), get_bypass_addresses(), get_default_gateway(), get_default_gateway_ipv6(), get_default_gateway_row(), get_user_pass_cr(), handle_data_channel_packet(), helper_client_server(), ifconfig_pool_init(), ifconfig_pool_list(), ifconfig_pool_read(), ifconfig_pool_verify_range(), ifconfig_sanity_check(), incoming_push_message(), init_key_ctx(), init_route_ipv6_list(), init_route_list(), init_ssl(), init_static(), init_tun(), ip_addr_string_to_array(), key2_print(), key_method_2_read(), key_source_print(), key_state_export_keying_material(), learn_address_script(), link_socket_bad_incoming_addr(), link_socket_connection_initiated(), linksock_print_addr(), man_connect(), man_dispatch_command(), man_history(), man_io_error(), man_kill(), man_listen(), man_new_connection_post(), man_output_extra_env(), man_process_command(), man_record_peer_info(), management_callback_send_cc_message(), management_echo(), management_hold(), management_query_multiline(), management_query_user_pass(), management_set_state(), mroute_extract_addr_ip(), mroute_helper_regenerate(), multi_add_iroutes(), multi_bcast(), multi_client_connect_call_script(), multi_client_connect_late_setup(), multi_client_connect_setenv(), multi_client_connect_source_ccd(), multi_client_set_protocol_options(), multi_create_instance(), multi_create_instance_tcp(), multi_get_create_instance_udp(), multi_get_instance_by_virtual_addr(), multi_instance_dec_refcount(), multi_learn_addr(), multi_print_status(), multi_process_float(), multi_process_incoming_link(), multi_process_incoming_tun(), multi_reap_range(), multi_select_virtual_addr(), multi_tcp_post(), ncp_get_best_cipher(), netsh_ifconfig(), netsh_ifconfig_options(), netsh_set_dns6_servers(), open_tun(), openvpn_decrypt_aead(), openvpn_decrypt_v1(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), openvpn_execve(), openvpn_execve_check(), openvpn_getaddrinfo(), openvpn_popen(), options_cmp_equal_safe(), options_warning_extract_parm1(), options_warning_safe_ml(), options_warning_safe_scan1(), options_warning_safe_scan2(), packet_id_persist_load(), packet_id_persist_save(), platform_access(), platform_chdir(), platform_fopen(), platform_open(), platform_stat(), platform_unlink(), plugin_call_item(), plugin_call_ssl(), plugin_common_open(), plugin_init_item(), plugin_open_item(), plugin_option_list_print(), plugin_vlog(), print_client_nat_list(), print_default_gateway(), print_pkt(), print_route(), print_status(), process_incoming_link_part1(), process_incoming_push_request(), process_incoming_tun(), process_outgoing_link(), push_peer_info(), read_control_auth(), read_key_file(), read_pem_key_file(), recv_socks_reply(), redirect_stdout_stderr(), register_dns_service(), reliable_ack_read(), reliable_can_get(), reliable_can_send(), reliable_get_buf_output_sequenced(), reliable_not_replay(), reliable_send_timeout(), reliable_wont_break_sequentiality(), remove_iroutes_from_push_route_list(), resolve_bind_local(), resolve_remote(), route_quota_exceeded(), run_up_down(), send_auth_failed(), send_auth_pending_messages(), send_control_channel_string_dowork(), send_msg_iservice(), send_push_reply(), send_push_reply_auth_token(), server_pushed_info(), service_enable_dhcp(), service_register_ring_buffers(), setenv_int_i(), setenv_route(), setenv_route_addr(), setenv_route_ipv6(), setenv_str_ex(), setenv_str_i(), show_adapters(), show_dhcp_option_addrs(), show_p2mp_parms(), show_routes(), show_tap_win_adapters(), show_windows_version(), socket_bind(), socket_connect(), socket_do_listen(), socket_listen_accept(), socket_recv_queue(), socket_send_queue(), tap_allow_nonadmin_access(), tcp_connection_established(), test_buffer_free_gc_one(), test_buffer_free_gc_two(), test_check_ncp_ciphers_list(), test_cipher_names(), test_crypto(), test_extract_client_ciphers(), test_local_addr(), test_ncp_best(), test_poor_man(), test_routes(), test_tls_crypt_v2_teardown(), tls1_P_hash(), tls1_PRF(), tls_crypt_unwrap(), tls_crypt_v2_unwrap_client_key(), tls_crypt_v2_verify_metadata(), tls_crypt_v2_write_client_key_file(), tls_crypt_wrap(), tls_ctx_set_tls_groups(), tls_multi_process(), tls_pre_decrypt(), tls_pre_decrypt_lite(), tls_pre_encrypt(), tls_process(), tls_session_init(), tls_update_remote_addr(), trigger_ping_timeout_signal(), tun_read_queue(), tun_write_queue(), tuntap_dhcp_mask(), tuntap_set_ip_addr(), tuntap_set_ptp(), uninit_options(), verify_255_255_255_252(), verify_callback(), verify_cert(), verify_cert_call_command(), verify_cert_set_env(), verify_check_crl_dir(), verify_common_subnet(), verify_final_auth_checks(), verify_user_pass_script(), virtual_output_callback_func(), warn_on_use_of_common_subnets(), win_block_dns_service(), window_title_generate(), windows_route_find_if_index(), write_key_file(), write_pem_key_file(), x509_setenv_track(), x_check_status(), and x_msg_va().
gc_freeaddrinfo_callback()
static void gc_freeaddrinfo_callback (void * addr) inline static
Definition at line 202 of file buffer.h.
Referenced by do_preresolve_host(), and init_route_list().
gc_init()
static void gc_init (struct gc_arena * a) inline static
Definition at line 1011 of file buffer.h.
References gc_arena::list, and gc_arena::list_special.
Referenced by add_route(), add_route_ipv6(), delete_route(), delete_route_ipv6(), gc_detach(), gc_new(), init_instance(), init_options(), openvpn_decrypt_aead(), openvpn_decrypt_v1(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), openvpn_main(), plugin_vlog(), tls_crypt_unwrap(), tls_crypt_wrap(), and x_msg_va().
gc_malloc()
void* gc_malloc (size_t size, bool clear, struct gc_arena * a)
Definition at line 385 of file buffer.c.
References check_malloc_return(), gc_arena::list, and gc_entry::next.
Referenced by add_route_ipv6(), alloc_buf_gc(), argv_prep_format(), argv_printf_arglist(), delete_route_ipv6(), establish_http_proxy_passthru(), get_adapter_info_list(), get_auth_challenge(), get_interface_info_list(), get_ipv6_addr_no_netbits(), get_panel_reg(), get_per_adapter_info(), get_user_pass_cr(), get_windows_routing_table(), key_state_export_keying_material(), options_postprocess_cipher(), options_string_extract_option(), options_warning_extract_parm1(), options_warning_safe_scan1(), options_warning_safe_scan2(), parse_hash_fingerprint(), parse_line(), plugin_vlog(), sanitize_control_message(), setenv_str_incr(), string_alloc(), string_substitute(), tls1_PRF(), wide_cmd_line(), wide_string(), x509_get_subject(), and x_msg_va().
gc_new()
static struct gc_arena gc_new (void) inline static
Definition at line 1024 of file buffer.h.
References gc_init().
Referenced by adapter_index_of_ip(), add_option(), add_route_ipapi(), argv_init(), argv_msg(), argv_msg_prefix(), argv_str__empty_argv__empty_output(), argv_str__multiple_argv__correct_output(), bio_read(), block_dns_msg_handler(), ccs_gen_config_file(), ccs_gen_deferred_ret_file(), ce_management_query_proxy(), ce_management_query_remote(), check_addr_clash(), check_file_access_chroot(), check_incoming_control_channel(), check_stale_routes(), check_subnet_conflict(), close_tun(), crypto_pem_encode_decode_loopback(), del_route_ipapi(), delete_temp_addresses(), dhcp_extract_router_msg(), dhcp_masq_addr(), dhcp_release_by_adapter_index(), dhcp_renew_by_adapter_index(), dhcp_status(), do_address_service(), do_close_tun(), do_compute_occ_strings(), do_dns_domain_service(), do_dns_service(), do_ifconfig_ipv4(), do_ifconfig_ipv6(), do_ifconfig_setenv(), do_open_tun(), do_route_service(), do_set_mtu_service(), drop_if_recursive_routing(), establish_http_proxy_passthru(), find_certificate_in_store(), fixup_key(), foreign_option(), fork_dhcp_action(), fork_register_dns_action(), frame_print(), generate_auth_token(), generate_key_random(), generate_prefix(), get_adapter_index_flexible(), get_adapter_index_method_2(), get_bypass_addresses(), get_default_gateway(), get_default_gateway_ipv6(), get_default_gateway_row(), get_user_pass_cr(), handle_data_channel_packet(), helper_client_server(), ifconfig_pool_init(), ifconfig_pool_list(), ifconfig_pool_read(), ifconfig_pool_verify_range(), ifconfig_sanity_check(), incoming_push_message(), inherit_context_child(), init_key_ctx(), init_route_ipv6_list(), init_route_list(), init_ssl(), init_static(), init_tun(), ip_addr_string_to_array(), key2_print(), key_method_2_read(), key_source_print(), key_state_export_keying_material(), learn_address_script(), link_socket_bad_incoming_addr(), link_socket_connection_initiated(), linksock_print_addr(), man_connect(), man_dispatch_command(), man_history(), man_io_error(), man_kill(), man_listen(), man_new_connection_post(), man_output_extra_env(), man_process_command(), man_record_peer_info(), management_callback_send_cc_message(), management_echo(), management_hold(), management_query_multiline(), management_query_user_pass(), management_set_state(), mroute_extract_addr_ip(), mroute_helper_regenerate(), multi_add_iroutes(), multi_bcast(), multi_client_connect_call_script(), multi_client_connect_late_setup(), multi_client_connect_setenv(), multi_client_connect_source_ccd(), multi_client_set_protocol_options(), multi_create_instance(), multi_create_instance_tcp(), multi_get_create_instance_udp(), multi_get_instance_by_virtual_addr(), multi_learn_addr(), multi_print_status(), multi_process_float(), multi_process_incoming_link(), multi_process_incoming_tun(), multi_reap_range(), multi_select_virtual_addr(), multi_tcp_post(), ncp_get_best_cipher(), netsh_ifconfig(), netsh_ifconfig_options(), netsh_set_dns6_servers(), open_tun(), openvpn_execve(), openvpn_execve_check(), openvpn_getaddrinfo(), openvpn_popen(), options_cmp_equal_safe(), options_warning_extract_parm1(), options_warning_safe_ml(), options_warning_safe_scan1(), options_warning_safe_scan2(), packet_id_persist_load(), packet_id_persist_save(), platform_access(), platform_chdir(), platform_fopen(), platform_open(), platform_stat(), platform_unlink(), plugin_call_item(), plugin_call_ssl(), plugin_common_open(), plugin_init_item(), plugin_open_item(), plugin_option_list_print(), print_client_nat_list(), print_default_gateway(), print_pkt(), print_route(), print_status(), process_incoming_link_part1(), process_incoming_push_request(), process_incoming_tun(), process_outgoing_link(), push_peer_info(), read_control_auth(), read_key_file(), read_pem_key_file(), recv_socks_reply(), redirect_stdout_stderr(), register_dns_service(), reliable_ack_read(), reliable_can_get(), reliable_can_send(), reliable_get_buf_output_sequenced(), reliable_not_replay(), reliable_send_timeout(), reliable_wont_break_sequentiality(), remove_iroutes_from_push_route_list(), resolve_bind_local(), resolve_remote(), route_quota_exceeded(), run_up_down(), send_auth_failed(), send_auth_pending_messages(), send_control_channel_string_dowork(), send_msg_iservice(), send_push_reply(), send_push_reply_auth_token(), server_pushed_info(), service_enable_dhcp(), service_register_ring_buffers(), setenv_int_i(), setenv_route(), setenv_route_addr(), setenv_route_ipv6(), setenv_str_ex(), setenv_str_i(), show_adapters(), show_dhcp_option_addrs(), show_p2mp_parms(), show_routes(), show_tap_win_adapters(), show_windows_version(), socket_bind(), socket_connect(), socket_do_listen(), socket_listen_accept(), socket_recv_queue(), socket_send_queue(), tap_allow_nonadmin_access(), tcp_connection_established(), test_buffer_free_gc_one(), test_buffer_free_gc_two(), test_check_ncp_ciphers_list(), test_cipher_names(), test_crypto(), test_extract_client_ciphers(), test_local_addr(), test_ncp_best(), test_poor_man(), test_routes(), test_tls_crypt_v2_setup(), tls1_P_hash(), tls1_PRF(), tls_crypt_v2_unwrap_client_key(), tls_crypt_v2_verify_metadata(), tls_crypt_v2_write_client_key_file(), tls_ctx_set_tls_groups(), tls_multi_process(), tls_pre_decrypt(), tls_pre_decrypt_lite(), tls_pre_encrypt(), tls_process(), tls_session_init(), tls_update_remote_addr(), trigger_ping_timeout_signal(), tun_read_queue(), tun_write_queue(), tuntap_dhcp_mask(), tuntap_set_ip_addr(), tuntap_set_ptp(), verify_255_255_255_252(), verify_callback(), verify_cert(), verify_cert_call_command(), verify_cert_set_env(), verify_check_crl_dir(), verify_common_subnet(), verify_final_auth_checks(), verify_user_pass_script(), virtual_output_callback_func(), warn_on_use_of_common_subnets(), win_block_dns_service(), window_title_generate(), windows_route_find_if_index(), windows_set_mtu(), write_key_file(), write_pem_key_file(), x509_setenv_track(), and x_check_status().
gc_reset()
static void gc_reset (struct gc_arena * a) inline static
Definition at line 1045 of file buffer.h.
References gc_free().
Referenced by openvpn_main().
gc_transfer()
void gc_transfer (struct gc_arena * dest, struct gc_arena * src)
Definition at line 476 of file buffer.c.
References dest, gc_arena::list, and gc_entry::next.
Referenced by add_option().
has_digit()
static bool has_digit (const unsigned char * src) inline static
Definition at line 359 of file buffer.h.
np()
const char* np (const char * str)
Definition at line 876 of file buffer.c.
openvpn_snprintf()
bool openvpn_snprintf (char * str, size_t size, const char * format, ...)
Definition at line 299 of file buffer.c.
References buffer::len.
Referenced by add_proxy_headers(), add_route(), add_route_ipv6(), do_ifconfig_ipv4(), do_ifconfig_ipv6(), do_setenv_x509(), env_block(), establish_http_proxy_passthru(), get_panel_reg(), get_tap_reg(), init_key_ctx_bi(), man_bytecount_output_client(), openvpn_run_script(), options_postprocess_cipher(), platform_create_temp_file(), plugin_init_item(), plugin_vlog(), print_cert_details(), print_details(), set_user_script(), setenv_counter(), setenv_int(), setenv_long_long(), setenv_sockaddr(), setenv_str_incr(), socks_username_password_auth(), tap_allow_nonadmin_access(), tls_crypt_v2_verify_metadata(), tun_try_open_device(), verify_cert_set_env(), verify_check_crl_dir(), x509_setenv(), and x_msg_va().
print_argv()
char* print_argv (const char ** p, struct gc_arena * gc, const unsigned int flags)
Definition at line 733 of file buffer.c.
References alloc_buf_gc(), BSTR, buf_printf(), and PA_BRACKET.
Referenced by argv_str(), plugin_open_item(), plugin_option_list_print(), and push_options().
rm_trailing_chars()
void rm_trailing_chars (char * str, const char * what_to_delete)
Definition at line 639 of file buffer.c.
References buffer::len.
Referenced by chomp().
secure_memzero()
static void secure_memzero (void * data, size_t len) inline static
Securely zeroise memory.
This code and description are based on code supplied by Zhaomo Yang, of the University of California, San Diego (which was released into the public domain).
The secure_memzero function attempts to ensure that an optimizing compiler does not remove the intended operation if cleared memory is not accessed again by the program. This code has been tested under Clang 3.9.0 and GCC 6.2 with optimization flags -O, -Os, -O0, -O1, -O2, and -O3 on Ubuntu 16.04.1 LTS; under Clang 3.9.0 with optimization flags -O, -Os, -O0, -O1, -O2, and -O3 on FreeBSD 10.2-RELEASE; under Microsoft Visual Studio 2015 with optimization flags /O1, /O2 and /Ox on Windows 10.
Theory of operation:
On Windows, use the SecureZeroMemory which ensures that data is overwritten.
Under GCC or Clang, use a memory barrier, which forces the preceding memset to be carried out. The overhead of a memory barrier is usually negligible.
If none of the above are available, use the volatile pointer technique to zero memory one byte at a time.
Parameters
data Pointer to data to zeroise.
len Length of data, in bytes.
Definition at line 401 of file buffer.h.
Referenced by buf_clear(), crypto_read_openvpn_key(), generate_key_expansion(), get_console_input(), key_method_2_read(), key_method_2_write(), key_state_free(), management_query_user_pass(), move_session(), purge_user_pass(), read_config_file(), read_config_string(), read_inline_file(), remove_env_item(), string_clear(), tls1_P_hash(), tls1_PRF(), tls_crypt_v2_extract_client_key(), tls_crypt_v2_init_client_key(), tls_crypt_v2_init_server_key(), tls_crypt_v2_unwrap_client_key(), tls_crypt_v2_write_client_key_file(), tls_multi_free(), tls_session_free(), tls_session_generate_data_channel_keys(), wipe_auth_token(), write_key_file(), and write_pem_key_file().
skip_leading_whitespace()
const char* skip_leading_whitespace (const char * str)
Definition at line 595 of file buffer.c.
Referenced by make_inline_array().
string_alloc()
char* string_alloc (const char * str, struct gc_arena * gc)
Definition at line 665 of file buffer.c.
References check_malloc_return(), and gc_malloc().
Referenced by add_env_item(), argv_clone(), argv_insert_head(), argv_parse_cmd(), auth_set_client_reason(), backend_x509_get_serial(), ccs_gen_config_file(), ccs_gen_deferred_ret_file(), check_file_access(), check_inline_file(), cipher_kt_block_size(), clone_push_list(), do_close_tun(), do_init_route_ipv6_list(), fork_to_self(), get_auth_challenge(), get_device_instance_id_interface(), get_ipv6_addr_no_netbits(), get_pa_var(), get_panel_reg(), get_proxy_authenticate(), get_tap_reg(), ifconfig_pool_acquire(), ifconfig_pool_set(), init_options_dev(), key_method_2_read(), log_history_add(), make_arg_array(), make_base64_string2(), make_inline_array(), man_settings_init(), management_callback_proxy_cmd(), ms_error_text(), mutate_ncp_cipher_list(), ncp_get_best_cipher(), open_null(), open_syslog(), options_warning_extract_parm1(), parse_http_proxy_override(), push_option_fmt(), read_inline_file(), RSA_meth_new(), set_common_name(), set_win_sys_path(), ssl_put_auth_challenge(), status_open(), string_alloc_buf(), string_mod_const(), test_cipher_names(), tls_ctx_set_tls_groups(), tls_item_in_cipher_list(), tls_lock_common_name(), tls_lock_username(), tls_peer_ncp_list(), tls_poor_mans_ncp(), and tun_open_device().
string_alloc_buf()
struct buffer string_alloc_buf (const char * str, struct gc_arena * gc)
Definition at line 768 of file buffer.c.
References ASSERT, buf_set_read(), buffer::len, and string_alloc().
Referenced by options_warning_extract_parm1().
string_array_len()
int string_array_len (const char ** array)
Definition at line 719 of file buffer.c.
Referenced by make_arg_copy(), make_extended_arg_array(), no_more_than_n_args(), and openvpn_plugin_open_v3().
string_check_buf()
bool string_check_buf (struct buffer * buf, const unsigned int inclusive, const unsigned int exclusive)
Check a buffer if it only consists of allowed characters.
Parameters
buf The buffer to be checked.
inclusive The character classes that are allowed.
exclusive Character classes that are not allowed even if they are also in inclusive.
Returns
True if the string consists only of allowed characters, false otherwise.
Definition at line 1089 of file buffer.c.
References ASSERT, BLEN, BSTR, and char_inc_exc().
Referenced by extract_command_buffer().
string_class()
bool string_class (const char * str, const unsigned int inclusive, const unsigned int exclusive)
Definition at line 1038 of file buffer.c.
References ASSERT, and char_inc_exc().
Referenced by dns_addr_safe(), openvpn_inet_aton(), push_option_ex(), and wide_cmd_line().
string_clear()
void string_clear (char * str)
Definition at line 707 of file buffer.c.
References secure_memzero().
Referenced by do_init_crypto_tls_c1(), get_user_pass_cr(), and openvpn_plugin_string_list_item_free().
string_mod()
bool string_mod (char * str, const unsigned int inclusive, const unsigned int exclusive, const char replace)
Definition at line 1057 of file buffer.c.
References ASSERT, and char_inc_exc().
Referenced by do_setenv_x509(), get_user_pass_cr(), string_mod_const(), string_mod_remap_name(), verify_user_pass(), wide_cmd_line(), and x509_setenv().
string_mod_const()
const char* string_mod_const (const char * str, const unsigned int inclusive, const unsigned int exclusive, const char replace, struct gc_arena * gc)
Returns a copy of a string with certain classes of characters of it replaced with a specified character.
If replace is 0, characters are skipped instead of replaced.
Parameters
str The input string to be modified.
inclusive Character classes not to be replaced.
exclusive Character classes to be replaced even if they are also in inclusive.
replace The character to replace the specified character classes with.
gc The garbage collector arena to allocate memory from.
Returns
The modified string with characters replaced within the specified range.
Definition at line 1106 of file buffer.c.
References string_alloc(), and string_mod().
Referenced by platform_gen_path(), safe_print(), and setenv_str_ex().
string_null_terminate()
void string_null_terminate (char * str, int len, int capacity)
Definition at line 613 of file buffer.c.
References ASSERT, buffer::capacity, and buffer::len.
Referenced by get_console_input_win32().
string_replace_leading()
void string_replace_leading (char * str, const char match, const char replace)
Definition at line 1125 of file buffer.c.
References ASSERT, and match().
Referenced by verify_cert().
strncpynt()
static void strncpynt (char * dest, const char * src, size_t maxlen) inline static
Definition at line 348 of file buffer.h.
References dest.
Referenced by buf_catrunc(), buf_puts(), do_dns_domain_service(), do_set_mtu_service(), extract_x509_field_ssl(), generate_prefix(), get_console_input(), get_highest_preference_tls_cipher(), get_user_pass_cr(), key_method_2_write(), man_query_user_pass(), management_callback_remote_cmd(), options_string_version(), pem_password_callback(), set_auth_token(), and socks_proxy_new().
strprefix()
static bool strprefix (const char * str, const char * prefix) inline static
Return true iff str starts with prefix.
Definition at line 971 of file buffer.h.
Referenced by options_warning_safe_scan2(), push_update_digest(), and test_buffer_strprefix().
x_gc_free()
void x_gc_free (struct gc_arena * a)
Definition at line 419 of file buffer.c.
References gc_arena::list, and gc_entry::next.
Referenced by gc_free().
x_gc_freespecial()
void x_gc_freespecial (struct gc_arena * a)
Definition at line 438 of file buffer.c.
References gc_entry_special::addr, gc_entry_special::free_fnc, gc_arena::list_special, and gc_entry_special::next.
Referenced by gc_free().