OpenVPN: src/openvpnserv/common.c File Reference
common.c File Reference
#include "service.h"
#include "validate.h"
Functions
BOOL openvpn_vsntprintf (LPTSTR str, size_t size, LPCTSTR format, va_list arglist)
BOOL openvpn_sntprintf (LPTSTR str, size_t size, LPCTSTR format,...)
BOOL openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format,...)
static DWORD GetRegString (HKEY key, LPCTSTR value, LPTSTR data, DWORD size, LPCTSTR default_value)
DWORD GetOpenvpnSettings (settings_t *s)
LPCTSTR GetLastErrorText ()
DWORD MsgToEventLog (DWORD flags, LPCTSTR format,...)
wchar_t * utf8to16 (const char *utf8)
const wchar_t * get_win_sys_path (void)
Variables
LPCTSTR service_instance = TEXT("")
static wchar_t win_sys_path [MAX_PATH]
Function Documentation
get_win_sys_path()
const wchar_t* get_win_sys_path (void)
Definition at line 310 of file common.c.
References ASSERT, and win_sys_path.
GetLastErrorText()
LPCTSTR GetLastErrorText ()
Definition at line 229 of file common.c.
References openvpn_sntprintf().
Referenced by CmdInstallServices(), CmdRemoveServices(), CmdStartService(), and MsgToEventLog().
GetOpenvpnSettings()
DWORD GetOpenvpnSettings (settings_t * s)
Definition at line 101 of file common.c.
References settings_t::append, settings_t::config_dir, settings_t::exe_path, settings_t::ext_string, GetRegString(), settings_t::log_dir, M_ERR, M_SYSERR, MsgToEventLog(), openvpn_sntprintf(), OVPN_ADMIN_GROUP, settings_t::ovpn_admin_group, PACKAGE_NAME, settings_t::priority, service_instance, and status.
Referenced by ServiceStartAutomatic(), and ServiceStartInteractive().
GetRegString()
static DWORD GetRegString (HKEY key, LPCTSTR value, LPTSTR data, DWORD size, LPCTSTR default_value) static
Definition at line 76 of file common.c.
References M_SYSERR, MsgToEventLog(), openvpn_sntprintf(), PACKAGE_NAME, service_instance, and status.
Referenced by GetOpenvpnSettings().
MsgToEventLog()
DWORD MsgToEventLog (DWORD flags, LPCTSTR format, ...)
Definition at line 260 of file common.c.
References APPNAME, GetLastErrorText(), msg, MSG_FLAGS_ERROR, MSG_FLAGS_SYS_CODE, openvpn_sntprintf(), openvpn_vsntprintf(), and service_instance.
Referenced by _tmain(), BlockDNSErrHandler(), CheckConfigPath(), ConvertInterfaceNameToIndex(), CreateClientPipeInstance(), DuplicateAndMapRing(), ExecCommand(), GetOpenvpnSettings(), GetRegString(), GetStartupData(), GetTokenGroups(), HandleBlockDNSMessage(), HandleMessage(), HandleRegisterRingBuffers(), IsAuthorizedUser(), IsUserInGroup(), OvpnDuplicateHandle(), RegisterDNS(), ReportStatusToSCMgr(), ReturnError(), RunOpenvpn(), ServiceStartAutomatic(), and ServiceStartInteractive().
openvpn_sntprintf()
BOOL openvpn_sntprintf (LPTSTR str, size_t size, LPCTSTR format, ...)
Definition at line 47 of file common.c.
References openvpn_vsntprintf().
Referenced by CreateClientPipeInstance(), GetLastErrorText(), GetOpenvpnSettings(), GetRegString(), HandleEnableDHCPMessage(), MsgToEventLog(), netsh_dns_cmd(), RunOpenvpn(), ServiceStartAutomatic(), and wmic_nicconfig_cmd().
openvpn_swprintf()
BOOL openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format, ...)
Definition at line 61 of file common.c.
openvpn_vsntprintf()
BOOL openvpn_vsntprintf (LPTSTR str, size_t size, LPCTSTR format, va_list arglist)
Definition at line 35 of file common.c.
Referenced by MsgToEventLog(), and openvpn_sntprintf().
utf8to16()
wchar_t* utf8to16 (const char * utf8)
Definition at line 297 of file common.c.
Referenced by HandleDNSConfigMessage(), InterfaceLuid(), and SetDNSDomain().
Variable Documentation
service_instance
LPCTSTR service_instance = TEXT("")
Definition at line 27 of file common.c.
Referenced by _tmain(), CreateClientPipeInstance(), GetOpenvpnSettings(), GetRegString(), MsgToEventLog(), RunOpenvpn(), and ServiceStartAutomatic().
win_sys_path
wchar_t win_sys_path[MAX_PATH] static
Definition at line 28 of file common.c.
Referenced by get_win_sys_path().