OpenVPN: src/compat/compat.h File Reference
compat.h File Reference
Functions
char * dirname (char *str)
char * basename (char *str)
int daemon (int nochdir, int noclose)
const char * inet_ntop (int af, const void *src, char *dst, socklen_t size)
int inet_pton (int af, const char *src, void *dst)
char * strsep (char **stringp, const char *delim)
Function Documentation
basename()
char* basename (char * str)
Definition at line 39 of file compat-basename.c.
Referenced by init_options_dev().
daemon()
int daemon (int nochdir, int noclose)
Definition at line 57 of file compat-daemon.c.
Referenced by daemonize(), possibly_become_daemon(), and show_settings().
dirname()
char* dirname (char * str)
Definition at line 64 of file compat-dirname.c.
References __memrchr().
Referenced by check_file_access().
inet_ntop()
const char* inet_ntop (int af, const void * src, char * dst, socklen_t size)
Definition at line 46 of file compat-inet_ntop.c.
References dst.
Referenced by print_in6_addr().
inet_pton()
int inet_pton (int af, const char * src, void * dst)
Definition at line 48 of file compat-inet_pton.c.
References dst.
Referenced by do_route_ipv6_service(), init_route_ipv6(), init_route_ipv6_list(), init_tun(), ipv6_addr_safe(), ipv6_send_icmp_unreachable(), net__addr_v4_add(), net__addr_v6_add(), net__route_v4_add(), net__route_v4_add_gw(), net__route_v6_add(), and net__route_v6_add_gw().
strsep()
char* strsep (char ** stringp, const char * delim)
Definition at line 38 of file compat-strsep.c.
Referenced by ncp_get_best_cipher(), and tls_ctx_set_tls_groups().