OpenVPN: src/compat/compat-inet_pton.c File Reference
compat-inet_pton.c File Reference
#include "compat.h"
#include <windows.h>
#include <string.h>
Functions
int inet_pton (int af, const char *src, void *dst)
Function Documentation
inet_pton()
int inet_pton (int af, const char * src, void * dst)
Definition at line 48 of file compat-inet_pton.c.
References dst.
Referenced by do_route_ipv6_service(), init_route_ipv6(), init_route_ipv6_list(), init_tun(), ipv6_addr_safe(), ipv6_send_icmp_unreachable(), net__addr_v4_add(), net__addr_v6_add(), net__route_v4_add(), net__route_v4_add_gw(), net__route_v6_add(), and net__route_v6_add_gw().