OpenVPN: src/compat/compat-daemon.c File Reference
compat-daemon.c File Reference
Functions
int daemon (int nochdir, int noclose)
Function Documentation
daemon()
int daemon (int nochdir, int noclose)
Definition at line 57 of file compat-daemon.c.
Referenced by daemonize(), possibly_become_daemon(), and show_settings().