OpenVPN: src/openvpn/cryptoapi.h File Reference
cryptoapi.h File Reference
Functions
int SSL_CTX_use_CryptoAPI_certificate (SSL_CTX *ssl_ctx, const char *cert_prop)
Function Documentation
SSL_CTX_use_CryptoAPI_certificate()
int SSL_CTX_use_CryptoAPI_certificate (SSL_CTX * ssl_ctx, const char * cert_prop)
Definition at line 1128 of file cryptoapi.c.
References CAPI_DATA_free(), _CAPI_DATA::cert_context, CERT_STORE_OPEN_EXISTING_FLAG, CERT_STORE_READONLY_FLAG, CERT_SYSTEM_STORE_CURRENT_USER, _CAPI_DATA::crypt_prov, CRYPTOAPI_F_CERT_FIND_CERTIFICATE_IN_STORE, CRYPTOAPI_F_CERT_OPEN_SYSTEM_STORE, CRYPTOAPI_F_CRYPT_ACQUIRE_CERTIFICATE_PRIVATE_KEY, CRYPTOAPIerr, find_certificate_in_store(), _CAPI_DATA::free_crypt_prov, _CAPI_DATA::key_spec, M_NONFATAL, M_WARN, msg, SSL_CTX_get_max_proto_version(), SSL_CTX_get_min_proto_version(), SSL_CTX_set_max_proto_version(), ssl_ctx_set_rsakey(), and X509_get0_pubkey().
Referenced by tls_ctx_load_cryptoapi().