OpenVPN: src/openvpn/dhcp.h File Reference
dhcp.h File Reference
#include "common.h"
#include "buffer.h"
#include "proto.h"
Data Structures
struct dhcp
struct dhcp_full
Macros
#define DHCP_PAD 0
#define DHCP_ROUTER 3
#define DHCP_MSG_TYPE 53 /* message type (u8) */
#define DHCP_END 255
#define DHCPDISCOVER 1
#define DHCPOFFER 2
#define DHCPREQUEST 3
#define DHCPDECLINE 4
#define DHCPACK 5
#define DHCPNAK 6
#define DHCPRELEASE 7
#define DHCPINFORM 8
#define BOOTPS_PORT 67
#define BOOTPC_PORT 68
#define BOOTREQUEST 1
#define BOOTREPLY 2
#define DHCP_OPTIONS_BUFFER_SIZE 256
Functions
in_addr_t dhcp_extract_router_msg (struct buffer *ipbuf)
Macro Definition Documentation
BOOTPC_PORT
#define BOOTPC_PORT 68
Definition at line 51 of file dhcp.h.
BOOTPS_PORT
#define BOOTPS_PORT 67
Definition at line 50 of file dhcp.h.
BOOTREPLY
#define BOOTREPLY 2
Definition at line 55 of file dhcp.h.
BOOTREQUEST
#define BOOTREQUEST 1
Definition at line 54 of file dhcp.h.
DHCP_END
#define DHCP_END 255
Definition at line 37 of file dhcp.h.
DHCP_MSG_TYPE
#define DHCP_MSG_TYPE 53 /* message type (u8) */
Definition at line 36 of file dhcp.h.
DHCP_OPTIONS_BUFFER_SIZE
#define DHCP_OPTIONS_BUFFER_SIZE 256
Definition at line 78 of file dhcp.h.
DHCP_PAD
#define DHCP_PAD 0
Definition at line 34 of file dhcp.h.
DHCP_ROUTER
#define DHCP_ROUTER 3
Definition at line 35 of file dhcp.h.
DHCPACK
#define DHCPACK 5
Definition at line 44 of file dhcp.h.
DHCPDECLINE
#define DHCPDECLINE 4
Definition at line 43 of file dhcp.h.
DHCPDISCOVER
#define DHCPDISCOVER 1
Definition at line 40 of file dhcp.h.
DHCPINFORM
#define DHCPINFORM 8
Definition at line 47 of file dhcp.h.
DHCPNAK
#define DHCPNAK 6
Definition at line 45 of file dhcp.h.
DHCPOFFER
#define DHCPOFFER 2
Definition at line 41 of file dhcp.h.
DHCPRELEASE
#define DHCPRELEASE 7
Definition at line 46 of file dhcp.h.
DHCPREQUEST
#define DHCPREQUEST 3
Definition at line 42 of file dhcp.h.
Function Documentation
dhcp_extract_router_msg()
in_addr_t dhcp_extract_router_msg (struct buffer * ipbuf)
Definition at line 151 of file dhcp.c.
References BLEN, BOOTPC_PORT, BOOTPS_PORT, BOOTREPLY, BPTR, openvpn_udphdr::check, D_ROUTE, openvpn_iphdr::daddr, openvpn_udphdr::dest, dhcp_full::dhcp, DHCPACK, DHCPOFFER, do_extract(), gc_free(), gc_new(), get_dhcp_message_type(), in_addr_t, dhcp_full::ip, ip_checksum(), msg, dhcp::op, OPENVPN_IPPROTO_UDP, print_in_addr_t(), openvpn_iphdr::protocol, openvpn_iphdr::saddr, openvpn_udphdr::source, and dhcp_full::udp.
Referenced by process_ip_header().