OpenVPN: src/openvpn/dhcp.c File Reference
dhcp.c File Reference
#include "syshead.h"
#include "dhcp.h"
#include "socket.h"
#include "error.h"
#include "memdbg.h"
Functions
static int get_dhcp_message_type (const struct dhcp *dhcp, const int optlen)
static in_addr_t do_extract (struct dhcp *dhcp, int optlen)
in_addr_t dhcp_extract_router_msg (struct buffer *ipbuf)
Function Documentation
dhcp_extract_router_msg()
in_addr_t dhcp_extract_router_msg (struct buffer * ipbuf)
Definition at line 151 of file dhcp.c.
References BLEN, BOOTPC_PORT, BOOTPS_PORT, BOOTREPLY, BPTR, openvpn_udphdr::check, D_ROUTE, openvpn_iphdr::daddr, openvpn_udphdr::dest, dhcp_full::dhcp, DHCPACK, DHCPOFFER, do_extract(), gc_free(), gc_new(), get_dhcp_message_type(), in_addr_t, dhcp_full::ip, ip_checksum(), msg, dhcp::op, OPENVPN_IPPROTO_UDP, print_in_addr_t(), openvpn_iphdr::protocol, openvpn_iphdr::saddr, openvpn_udphdr::source, and dhcp_full::udp.
Referenced by process_ip_header().
do_extract()
static in_addr_t do_extract (struct dhcp * dhcp, int optlen) static
Definition at line 79 of file dhcp.c.
References dest, DHCP_END, DHCP_PAD, DHCP_ROUTER, and in_addr_t.
Referenced by dhcp_extract_router_msg().
get_dhcp_message_type()
static int get_dhcp_message_type (const struct dhcp * dhcp, const int optlen) static
Definition at line 39 of file dhcp.c.
References DHCP_END, DHCP_MSG_TYPE, and DHCP_PAD.
Referenced by dhcp_extract_router_msg().