OpenVPN: src/openvpn/event.c File Reference
event.c File Reference
#include "syshead.h"
#include "buffer.h"
#include "error.h"
#include "integer.h"
#include "event.h"
#include "fdmisc.h"
#include "memdbg.h"
Data Structures
struct we_set
Macros
#define SELECT 0
#define SELECT_MAX_FDS 256
Functions
static int tv_to_ms_timeout (const struct timeval *tv)
static void we_set_event (struct we_set *wes, int i, event_t event, unsigned int rwflags, void *arg)
static bool we_append_event (struct we_set *wes, event_t event, unsigned int rwflags, void *arg)
static void we_del_event (struct we_set *wes, event_t event)
static void we_del_index (struct we_set *wes, int index)
static void we_get_rw_indices (struct we_set *wes, event_t event, int *ri, int *wi)
static void we_free (struct event_set *es)
static void we_reset (struct event_set *es)
static void we_del (struct event_set *es, event_t event)
static void we_ctl (struct event_set *es, event_t event, unsigned int rwflags, void *arg)
static int we_wait (struct event_set *es, const struct timeval *tv, struct event_set_return *out, int outlen)
static struct event_set * we_init (int *maxevents, unsigned int flags)
static struct event_set * event_set_init_simple (int *maxevents, unsigned int flags)
static struct event_set * event_set_init_scalable (int *maxevents, unsigned int flags)
struct event_set * event_set_init (int *maxevents, unsigned int flags)
Macro Definition Documentation
SELECT
#define SELECT 0
Definition at line 52 of file event.c.
SELECT_MAX_FDS
#define SELECT_MAX_FDS 256
Definition at line 64 of file event.c.
Function Documentation
event_set_init()
struct event_set* event_set_init (int * maxevents, unsigned int flags)
Definition at line 1180 of file event.c.
References EVENT_METHOD_FAST, event_set_init_scalable(), and event_set_init_simple().
Referenced by do_event_set_init(), man_connection_init(), and multi_tcp_init().
event_set_init_scalable()
static struct event_set* event_set_init_scalable (int * maxevents, unsigned int flags) static
Definition at line 1162 of file event.c.
References ASSERT, event_set_init_simple(), M_WARN, and msg.
Referenced by event_set_init().
event_set_init_simple()
static struct event_set* event_set_init_simple (int * maxevents, unsigned int flags) static
Definition at line 1119 of file event.c.
References ASSERT, EVENT_METHOD_US_TIMEOUT, and we_init().
Referenced by event_set_init(), and event_set_init_scalable().
tv_to_ms_timeout()
static int tv_to_ms_timeout (const struct timeval * tv) inline static
Definition at line 68 of file event.c.
References max_int().
Referenced by we_wait().
we_append_event()
static bool we_append_event (struct we_set * wes, event_t event, unsigned int rwflags, void * arg) inline static
Definition at line 117 of file event.c.
References event_set_return::arg, we_set::capacity, EVENT_READ, EVENT_WRITE, we_set::n_events, event_set_return::rwflags, and we_set_event().
Referenced by we_ctl().
we_ctl()
static void we_ctl (struct event_set * es, event_t event, unsigned int rwflags, void * arg) static
Definition at line 231 of file event.c.
References ASSERT, D_EVENT_ERRORS, D_EVENT_WAIT, dmsg, EVENT_READ, EVENT_WRITE, we_set::fast, M_FATAL, msg, we_set::n_events, ptr_format, we_append_event(), we_del_event(), we_del_index(), we_get_rw_indices(), and we_set_event().
Referenced by we_init().
we_del()
static void we_del (struct event_set * es, event_t event) static
Definition at line 223 of file event.c.
References ASSERT, we_set::fast, and we_del_event().
Referenced by we_init().
we_del_event()
static void we_del_event (struct we_set * wes, event_t event) static
Definition at line 147 of file event.c.
References we_set::esr, we_set::events, we_set::n_events, rw_handle::read, and rw_handle::write.
Referenced by we_ctl(), and we_del().
we_del_index()
static void we_del_index (struct we_set * wes, int index) static
Definition at line 172 of file event.c.
References ASSERT, we_set::esr, we_set::events, and we_set::n_events.
Referenced by we_ctl().
we_free()
static void we_free (struct event_set * es) static
Definition at line 206 of file event.c.
References we_set::esr, and we_set::events.
Referenced by we_init().
we_get_rw_indices()
static void we_get_rw_indices (struct we_set * wes, event_t event, int * ri, int * wi) static
Definition at line 185 of file event.c.
References ASSERT, we_set::events, we_set::n_events, rw_handle::read, and rw_handle::write.
Referenced by we_ctl().
we_init()
static struct event_set* we_init (int * maxevents, unsigned int flags) static
Definition at line 481 of file event.c.
References ALLOC_ARRAY_CLEAR, ALLOC_OBJ_CLEAR, ASSERT, we_set::capacity, event_set_functions::ctl, D_EVENT_WAIT, event_set_functions::del, dmsg, we_set::esr, EVENT_METHOD_FAST, we_set::events, we_set::fast, event_set_functions::free, we_set::func, min_int(), we_set::n_events, event_set_functions::reset, event_set_functions::wait, we_ctl(), we_del(), we_free(), we_reset(), and we_wait().
Referenced by event_set_init_simple().
we_reset()
static void we_reset (struct event_set * es) static
Definition at line 215 of file event.c.
References ASSERT, we_set::fast, and we_set::n_events.
Referenced by we_init().
we_set_event()
static void we_set_event (struct we_set * wes, int i, event_t event, unsigned int rwflags, void * arg) inline static
Definition at line 93 of file event.c.
References event_set_return::arg, ASSERT, we_set::esr, EVENT_READ, EVENT_WRITE, we_set::events, M_FATAL, msg, rw_handle::read, event_set_return::rwflags, and rw_handle::write.
Referenced by we_append_event(), and we_ctl().
we_wait()
static int we_wait (struct event_set * es, const struct timeval * tv, struct event_set_return * out, int outlen) static
Definition at line 383 of file event.c.
References event_set_return::arg, check_debug_level(), D_EVENT_WAIT, dmsg, we_set::esr, we_set::events, we_set::n_events, ptr_format, event_set_return::rwflags, status, and tv_to_ms_timeout().
Referenced by we_init().