OpenVPN: src/openvpn/fdmisc.h File Reference
fdmisc.h File Reference
#include "basic.h"
#include "error.h"
#include "syshead.h"
Functions
bool set_nonblock_action (int fd)
bool set_cloexec_action (int fd)
void set_nonblock (int fd)
void set_cloexec (int fd)
static void openvpn_fd_set (int fd, fd_set *setp)
Function Documentation
openvpn_fd_set()
static void openvpn_fd_set (int fd, fd_set * setp) inline static
Definition at line 40 of file fdmisc.h.
References ASSERT.
Referenced by openvpn_connect(), recv_line(), recv_socks_reply(), socket_listen_accept(), socks_handshake(), and socks_username_password_auth().
set_cloexec()
void set_cloexec (int fd)
Definition at line 81 of file fdmisc.c.
References M_ERR, msg, and set_cloexec_action().
Referenced by create_socket_tcp(), create_socket_udp(), link_socket_init_phase1(), socket_do_accept(), and status_open().
set_cloexec_action()
bool set_cloexec_action (int fd)
Definition at line 58 of file fdmisc.c.
Referenced by set_cloexec().
set_nonblock()
void set_nonblock (int fd)
Definition at line 71 of file fdmisc.c.
References M_ERR, msg, and set_nonblock_action().
Referenced by man_listen(), man_new_connection_post(), openvpn_connect(), phase2_set_socket_flags(), and socket_do_listen().
set_nonblock_action()
bool set_nonblock_action (int fd)
Definition at line 39 of file fdmisc.c.
Referenced by set_nonblock().