OpenVPN: src/openvpn/fdmisc.c File Reference
fdmisc.c File Reference
#include "syshead.h"
#include "fdmisc.h"
#include "error.h"
#include "memdbg.h"
Functions
bool set_nonblock_action (int fd)
bool set_cloexec_action (int fd)
void set_nonblock (int fd)
void set_cloexec (int fd)
Function Documentation
set_cloexec()
void set_cloexec (int fd)
Definition at line 81 of file fdmisc.c.
References M_ERR, msg, and set_cloexec_action().
Referenced by create_socket_tcp(), create_socket_udp(), link_socket_init_phase1(), socket_do_accept(), and status_open().
set_cloexec_action()
bool set_cloexec_action (int fd)
Definition at line 58 of file fdmisc.c.
Referenced by set_cloexec().
set_nonblock()
void set_nonblock (int fd)
Definition at line 71 of file fdmisc.c.
References M_ERR, msg, and set_nonblock_action().
Referenced by man_listen(), man_new_connection_post(), openvpn_connect(), phase2_set_socket_flags(), and socket_do_listen().
set_nonblock_action()
bool set_nonblock_action (int fd)
Definition at line 39 of file fdmisc.c.
Referenced by set_nonblock().