OpenVPN: src/openvpn/forward.h File Reference
forward.h File Reference
#include "openvpn.h"
#include "occ.h"
#include "ping.h"
Macros
#define TUN_OUT(c) (BLEN(&(c)->c2.to_tun) > 0)
#define LINK_OUT(c) (BLEN(&(c)->c2.to_link) > 0)
#define ANY_OUT(c) (TUN_OUT(c) || LINK_OUT(c))
#define TO_LINK_FRAG(c) ((c)->c2.fragment && fragment_outgoing_defined((c)->c2.fragment))
#define TO_LINK_DEF(c) (LINK_OUT(c) || TO_LINK_FRAG(c))
#define IOW_TO_TUN (1<<0)
#define IOW_TO_LINK (1<<1)
#define IOW_READ_TUN (1<<2)
#define IOW_READ_LINK (1<<3)
#define IOW_SHAPER (1<<4)
#define IOW_CHECK_RESIDUAL (1<<5)
#define IOW_FRAG (1<<6)
#define IOW_MBUF (1<<7)
#define IOW_READ_TUN_FORCE (1<<8)
#define IOW_WAIT_SIGNAL (1<<9)
#define IOW_READ (IOW_READ_TUN|IOW_READ_LINK)
#define PIPV4_PASSTOS (1<<0)
#define PIP_MSSFIX (1<<1) /* v4 and v6 */
#define PIP_OUTGOING (1<<2)
#define PIPV4_EXTRACT_DHCP_ROUTER (1<<3)
#define PIPV4_CLIENT_NAT (1<<4)
#define PIPV6_IMCP_NOHOST_CLIENT (1<<5)
#define PIPV6_IMCP_NOHOST_SERVER (1<<6)
#define CONNECTION_ESTABLISHED(c) (get_link_socket_info(c)->connection_established)
Functions
void check_tls (struct context *c)
void check_tls_errors_co (struct context *c)
void check_tls_errors_nco (struct context *c)
void check_incoming_control_channel (struct context *c)
void check_scheduled_exit (struct context *c)
void check_push_request (struct context *c)
void check_fragment (struct context *c)
void check_connection_established (struct context *c)
void check_add_routes (struct context *c)
void check_inactivity_timeout (struct context *c)
void check_server_poll_timeout (struct context *c)
void check_status_file (struct context *c)
void io_wait_dowork (struct context *c, const unsigned int flags)
void pre_select (struct context *c)
void process_io (struct context *c)
const char * wait_status_string (struct context *c, struct gc_arena *gc)
void show_wait_status (struct context *c)
void encrypt_sign (struct context *c, bool comp_frag)
Process a data channel packet that will be sent through a VPN tunnel.
int get_server_poll_remaining_time (struct event_timeout *server_poll_timeout)
void read_incoming_link (struct context *c)
Read a packet from the external network interface.
bool process_incoming_link_part1 (struct context *c, struct link_socket_info *lsi, bool floated)
Starts processing a packet read from the external network interface.
void process_incoming_link_part2 (struct context *c, struct link_socket_info *lsi, const uint8_t *orig_buf)
Continues processing a packet read from the external network interface.
void process_outgoing_link (struct context *c)
Write a packet to the external network interface.
void read_incoming_tun (struct context *c)
Read a packet from the virtual tun/tap network interface.
void process_incoming_tun (struct context *c)
Process a packet read from the virtual tun/tap network interface.
void process_outgoing_tun (struct context *c)
Write a packet to the virtual tun/tap network interface.
bool send_control_channel_string (struct context *c, const char *str, int msglevel)
bool send_control_channel_string_dowork (struct tls_multi *multi, const char *str, int msglevel)
void process_ip_header (struct context *c, unsigned int flags, struct buffer *buf)
void schedule_exit (struct context *c, const int n_seconds, const int signal)
static struct link_socket_info * get_link_socket_info (struct context *c)
static void register_activity (struct context *c, const int size)
static unsigned int p2p_iow_flags (const struct context *c)
static void io_wait (struct context *c, const unsigned int flags)
Variables
counter_type link_read_bytes_global
counter_type link_write_bytes_global
Detailed Description
Interface functions to the internal and external multiplexers.
Definition in file forward.h.
Macro Definition Documentation
ANY_OUT
#define ANY_OUT (c) (TUN_OUT(c) || LINK_OUT(c))
Definition at line 40 of file forward.h.
CONNECTION_ESTABLISHED
#define CONNECTION_ESTABLISHED (c) (get_link_socket_info(c)->connection_established)
Definition at line 445 of file forward.h.
IOW_CHECK_RESIDUAL
#define IOW_CHECK_RESIDUAL (1<<5)
Definition at line 59 of file forward.h.
IOW_FRAG
#define IOW_FRAG (1<<6)
Definition at line 60 of file forward.h.
IOW_MBUF
#define IOW_MBUF (1<<7)
Definition at line 61 of file forward.h.
IOW_READ
#define IOW_READ (IOW_READ_TUN|IOW_READ_LINK)
Definition at line 65 of file forward.h.
IOW_READ_LINK
#define IOW_READ_LINK (1<<3)
Definition at line 57 of file forward.h.
IOW_READ_TUN
#define IOW_READ_TUN (1<<2)
Definition at line 56 of file forward.h.
IOW_READ_TUN_FORCE
#define IOW_READ_TUN_FORCE (1<<8)
Definition at line 62 of file forward.h.
IOW_SHAPER
#define IOW_SHAPER (1<<4)
Definition at line 58 of file forward.h.
IOW_TO_LINK
#define IOW_TO_LINK (1<<1)
Definition at line 55 of file forward.h.
IOW_TO_TUN
#define IOW_TO_TUN (1<<0)
Definition at line 54 of file forward.h.
IOW_WAIT_SIGNAL
#define IOW_WAIT_SIGNAL (1<<9)
Definition at line 63 of file forward.h.
LINK_OUT
#define LINK_OUT (c) (BLEN(&(c)->c2.to_link) > 0)
Definition at line 39 of file forward.h.
PIP_MSSFIX
#define PIP_MSSFIX (1<<1) /* v4 and v6 */
Definition at line 321 of file forward.h.
PIP_OUTGOING
#define PIP_OUTGOING (1<<2)
Definition at line 322 of file forward.h.
PIPV4_CLIENT_NAT
#define PIPV4_CLIENT_NAT (1<<4)
Definition at line 324 of file forward.h.
PIPV4_EXTRACT_DHCP_ROUTER
#define PIPV4_EXTRACT_DHCP_ROUTER (1<<3)
Definition at line 323 of file forward.h.
PIPV4_PASSTOS
#define PIPV4_PASSTOS (1<<0)
Definition at line 320 of file forward.h.
PIPV6_IMCP_NOHOST_CLIENT
#define PIPV6_IMCP_NOHOST_CLIENT (1<<5)
Definition at line 325 of file forward.h.
PIPV6_IMCP_NOHOST_SERVER
#define PIPV6_IMCP_NOHOST_SERVER (1<<6)
Definition at line 326 of file forward.h.
TO_LINK_DEF
#define TO_LINK_DEF (c) (LINK_OUT(c) || TO_LINK_FRAG(c))
Definition at line 48 of file forward.h.
TO_LINK_FRAG
#define TO_LINK_FRAG (c) ((c)->c2.fragment && fragment_outgoing_defined((c)->c2.fragment))
Definition at line 43 of file forward.h.
TUN_OUT
#define TUN_OUT (c) (BLEN(&(c)->c2.to_tun) > 0)
Definition at line 38 of file forward.h.
Function Documentation
check_add_routes()
void check_add_routes (struct context * c)
Definition at line 412 of file forward.c.
References context::c1, context::c2, check_add_routes_action(), D_ROUTE, ETT_DEFAULT, event_timeout_init(), event_timeout_reset(), event_timeout_trigger(), M_INFO, M_NOPREFIX, msg, event_timeout::n, now, context::persist, context_2::ping_rec_interval, register_signal(), context_persist::restart_sleep_seconds, context_1::route_list, context_2::route_wakeup, context_2::route_wakeup_expire, show_adapters(), show_routes(), SIGHUP, test_routes(), context_2::timeval, tun_standby(), context_1::tuntap, and update_time().
Referenced by process_coarse_timers().
check_connection_established()
void check_connection_established (struct context * c)
Definition at line 321 of file forward.c.
References context::c2, CONNECTION_ESTABLISHED, do_up(), event_timeout_clear(), event_timeout_init(), management_set_state(), now, OPENVPN_STATE_GET_CONFIG, context::options, options::pull, context_2::push_request_interval, reset_coarse_timers(), context_2::tls_multi, and context_2::wait_for_connect.
Referenced by process_coarse_timers().
check_fragment()
void check_fragment (struct context * c)
Definition at line 520 of file forward.c.
References ASSERT, context_2::buf, context::c2, options::ce, encrypt_sign(), context_2::fragment, fragment_housekeeping(), fragment_outgoing_defined(), fragment_ready_to_send(), frame_adjust_path_mtu(), context_2::frame_fragment, get_link_socket_info(), buffer::len, context_2::link_socket, link_socket::mtu, link_socket_info::mtu_changed, context::options, connection_entry::proto, context_2::timeval, and context_2::to_link.
Referenced by pre_select().
check_inactivity_timeout()
void check_inactivity_timeout (struct context * c)
Definition at line 450 of file forward.c.
References M_INFO, msg, register_signal(), and SIGTERM.
Referenced by process_coarse_timers().
check_incoming_control_channel()
void check_incoming_control_channel (struct context * c)
Definition at line 269 of file forward.c.
References alloc_buf_gc(), ASSERT, BLEN, context::c2, D_PUSH_ERRORS, extract_command_buffer(), gc_free(), gc_new(), buffer::len, msg, parse_incoming_control_channel_command(), context_2::tls_multi, tls_rec_payload(), and tls_test_payload_len().
Referenced by pre_select().
check_push_request()
void check_push_request (struct context * c)
Definition at line 301 of file forward.c.
References context::c2, event_timeout_modify_wakeup(), PUSH_REQUEST_INTERVAL, context_2::push_request_interval, and send_push_request().
Referenced by process_coarse_timers().
check_scheduled_exit()
void check_scheduled_exit (struct context * c)
Definition at line 496 of file forward.c.
References context::c2, register_signal(), and context_2::scheduled_exit_signal.
Referenced by process_coarse_timers().
check_server_poll_timeout()
void check_server_poll_timeout (struct context * c)
Definition at line 466 of file forward.c.
References ASSERT, context::c2, event_timeout_reset(), M_INFO, msg, context::persist, register_signal(), context_persist::restart_sleep_seconds, context_2::server_poll_interval, SIGUSR1, tls_initial_packet_received(), and context_2::tls_multi.
Referenced by process_coarse_timers().
check_status_file()
void check_status_file (struct context * c)
Definition at line 507 of file forward.c.
References context::c1, print_status(), and context_1::status_output.
Referenced by process_coarse_timers().
check_tls()
void check_tls (struct context * c)
Definition at line 142 of file forward.c.
References BIG_TIMEOUT, context::c2, context_reschedule_sec(), get_link_socket_info(), interval_action(), interval_future_trigger(), interval_schedule_wakeup(), interval_test(), register_signal(), SIGTERM, context_2::tls_multi, tls_multi_process(), TLSMP_ACTIVE, TLSMP_KILL, context_2::tmp_int, context_2::to_link, context_2::to_link_addr, and update_time().
Referenced by pre_select().
check_tls_errors_co()
void check_tls_errors_co (struct context * c)
Definition at line 173 of file forward.c.
References context::c2, D_STREAM_ERRORS, msg, register_signal(), and context_2::tls_exit_signal.
Referenced by check_tls_errors().
check_tls_errors_nco()
void check_tls_errors_nco (struct context * c)
Definition at line 180 of file forward.c.
References context::c2, register_signal(), and context_2::tls_exit_signal.
Referenced by check_tls_errors().
encrypt_sign()
void encrypt_sign (struct context * c, bool comp_frag)
Process a data channel packet that will be sent through a VPN tunnel.
This function controls the processing of a data channel packet which will be sent through a VPN tunnel to a remote OpenVPN peer. It's general structure is as follows:
Check that the client authentication has succeeded; if not, drop the packet.
If the comp_frag argument is true:
Call lzo_compress() of the Channel Compression module to (possibly) compress the packet.
Call fragment_outgoing() of the Channel Fragmentation module to (possibly) fragment the packet.
Activate the Channel Crypto module to perform security operations on the packet.
Call tls_pre_encrypt() to choose the appropriate security parameters for this packet.
Call openvpn_encrypt() to encrypt and HMAC signed the packet.
Call tls_post_encrypt() to prepend the one-byte OpenVPN header and do some TLS accounting.
Place the resulting packet in c->c2.to_link so that it can be sent over the external network interface to its remote destination by the External Multiplexer.
Parameters
c - The context structure of the VPN tunnel associated with this packet.
comp_frag - Whether to do packet compression and fragmentation. This flag is set to true the first time a packet is processed. If the packet then gets fragmented, this function will be called again once for each remaining fragment with this parameter set to false.
Definition at line 569 of file forward.c.
References ASSERT, context_2::buf, buf_init, buffer_turnover(), context_2::buffers, context::c2, CAS_SUCCEEDED, context_2::crypto_options, buffer::data, context_buffers::encrypt_buf, context_2::fragment, fragment_outgoing(), context_2::frame, context_2::frame_fragment, FRAME_HEADROOM, get_link_socket_info(), buffer::len, link_socket_get_outgoing_addr(), tls_multi::multi_state, openvpn_encrypt(), context_buffers::read_tun_buf, context_2::tls_multi, tls_post_encrypt(), tls_pre_encrypt(), tls_prepend_opcode_v1(), tls_prepend_opcode_v2(), context_2::to_link, context_2::to_link_addr, and tls_multi::use_peer_id.
Referenced by check_fragment(), check_ping_send_dowork(), check_send_occ_msg_dowork(), multi_get_queue(), and process_incoming_tun().
get_link_socket_info()
static struct link_socket_info* get_link_socket_info (struct context * c) inline static
Definition at line 336 of file forward.h.
References context::c2, link_socket::info, context_2::link_socket, and context_2::link_socket_info.
Referenced by check_fragment(), check_tls(), encrypt_sign(), initialization_sequence_completed(), multi_client_connect_setenv(), multi_client_disconnect_setenv(), multi_process_incoming_link(), and process_incoming_link().
get_server_poll_remaining_time()
int get_server_poll_remaining_time (struct event_timeout * server_poll_timeout)
Definition at line 457 of file forward.c.
References event_timeout_remaining(), max_int(), and update_time().
Referenced by establish_http_proxy_passthru(), phase2_socks_client(), and phase2_tcp_client().
io_wait()
static void io_wait (struct context * c, const unsigned int flags) inline static
Definition at line 392 of file forward.h.
References context::c1, context::c2, context_2::event_set_status, context_2::fast_io, io_wait_dowork(), IOW_MBUF, IOW_READ_TUN, IOW_TO_LINK, IOW_TO_TUN, SOCKET_WRITE, TUN_READ, TUN_WRITE, context_1::tuntap, and tuntap_is_wintun().
Referenced by multi_tcp_wait_lite(), tunnel_point_to_point(), and tunnel_server_udp_single_threaded().
io_wait_dowork()
void io_wait_dowork (struct context * c, const unsigned int flags)
Definition at line 1927 of file forward.c.
References event_set_return::arg, context::c1, context::c2, check_debug_level(), check_status(), D_EVENT_WAIT, dmsg, ES_ERROR, ES_TIMEOUT, event_ctl(), EVENT_READ, event_reset(), context_2::event_set, context_2::event_set_status, event_wait(), EVENT_WRITE, get_signal(), IOW_CHECK_RESIDUAL, IOW_FRAG, IOW_MBUF, IOW_READ_LINK, IOW_READ_TUN, IOW_READ_TUN_FORCE, IOW_SHAPER, IOW_TO_LINK, IOW_TO_TUN, IOW_WAIT_SIGNAL, context_2::link_socket, management_socket_set(), max_int(), options::mode, MODE_SERVER, context::options, event_set_return::rwflags, context_2::shaper, options::shaper, shaper_soonest_event(), show_wait_status(), context::sig, signal_info::signal_received, SIZE, SOCKET_READ, socket_read_residual(), socket_set(), status, context_2::timeval, TO_LINK_FRAG, tun_set(), context_1::tuntap, tuntap_is_wintun(), update_time(), and wait_signal().
Referenced by io_wait().
p2p_iow_flags()
static unsigned int p2p_iow_flags (const struct context * c) inline static
Definition at line 367 of file forward.h.
References context::c1, context::c2, IOW_CHECK_RESIDUAL, IOW_FRAG, IOW_READ, IOW_READ_TUN, IOW_SHAPER, IOW_TO_LINK, IOW_TO_TUN, IOW_WAIT_SIGNAL, buffer::len, context_2::to_link, context_2::to_tun, context_1::tuntap, and tuntap_ring_empty().
Referenced by tunnel_point_to_point().
pre_select()
void pre_select (struct context * c)
Definition at line 1853 of file forward.c.
References BIG_TIMEOUT, context::c1, context::c2, check_coarse_timers(), check_debug_level(), check_fragment(), check_incoming_control_channel(), check_send_occ_msg(), check_timeout_random_component(), check_tls(), check_tls_errors(), D_TAP_WIN_DEBUG, context_2::fragment, context::sig, signal_info::signal_received, context_2::timeval, context_2::tls_multi, tls_test_payload_len(), tun_show_debug(), context_1::tuntap, and tuntap_defined().
Referenced by multi_process_post(), and tunnel_point_to_point().
process_incoming_link_part1()
bool process_incoming_link_part1 (struct context * c, struct link_socket_info * lsi, bool floated)
Starts processing a packet read from the external network interface.
This function starts the processing of a data channel packet which has come out of a VPN tunnel. It's high-level structure is as follows:
Verify that a nonzero length packet has been received from a valid source address for the given context c.
Call tls_pre_decrypt(), which splits data channel and control channel packets:
If a data channel packet, the appropriate security parameters are loaded.
If a control channel packet, this function process is it and afterwards sets the packet's buffer length to 0, so that the data channel processing steps below will ignore it.
Call openvpn_decrypt() of the Data Channel Crypto module to authenticate and decrypt the packet using the security parameters loaded by tls_pre_decrypt() above.
Parameters
c - The context structure of the VPN tunnel associated with the packet.
lsi - link_socket_info obtained from context before processing.
floated - Flag indicates that peer has floated.
Returns
true if packet is authenticated, false otherwise.
Definition at line 912 of file forward.c.
References link_socket_info::af, BLEN, BPTR, context_2::buf, buf_reset(), context_2::buffers, context::c2, CAS_SUCCEEDED, context_2::crypto_options, D_LINK_RW, D_STREAM_ERRORS, context_buffers::decrypt_buf, event_timeout_reset(), context_2::frame, context_2::frame_fragment, context_2::frame_fragment_initial, context_2::frame_initial, context_2::from, gc_free(), gc_new(), interval_action(), is_hard_reset_method2(), buffer::len, context_2::link_read_bytes, link_read_bytes_global, context_2::link_socket, link_socket_bad_incoming_addr(), link_socket_connection_oriented(), link_socket_verify_incoming_addr(), context_2::link_write_bytes, context_2::log_rw, management_bytes_in(), msg, tls_multi::multi_state, openvpn_decrypt(), context::options, context_2::original_recv_size, P_OPCODE_SHIFT, context_2::ping_rec_interval, options::ping_rec_timeout, print_link_socket_actual(), link_socket_info::proto, proto2ascii(), PROTO_DUMP, register_signal(), SIGUSR1, context_2::tls_multi, tls_pre_decrypt(), context_2::tmp_int, and context_2::to_tun.
Referenced by multi_process_incoming_link(), and process_incoming_link().
process_incoming_link_part2()
void process_incoming_link_part2 (struct context * c, struct link_socket_info * lsi, const uint8_t * orig_buf)
Continues processing a packet read from the external network interface.
This function continues the processing of a data channel packet which has come out of a VPN tunnel. It must be called after process_incoming_link_part1() function.
It's high-level structure is as follows:
Call fragment_incoming() of the Data Channel Fragmentation module to reassemble the packet if it's fragmented.
Call lzo_decompress() of the Data Channel Compression module to decompress the packet if it's compressed.
Place the resulting packet in c->c2.to_tun so that it can be sent over the virtual tun/tap network interface to its local destination by the Internal Multiplexer.
Parameters
c - The context structure of the VPN tunnel associated with the packet.
lsi - link_socket_info obtained from context before processing.
orig_buf - Pointer to a buffer data.
Definition at line 1054 of file forward.c.
References BLEN, BPTR, context_2::buf, buf_reset(), buffer_turnover(), context_2::buffers, context::c1, context::c2, D_PING, dmsg, context_2::es, event_timeout_reset(), context_2::fragment, fragment_incoming(), context_2::frame, context_2::frame_fragment, context_2::from, is_occ_msg(), is_ping_msg(), buffer::len, context_2::link_read_bytes_auth, link_socket_set_outgoing_addr(), max_int(), context_2::max_recv_size_local, context::options, context_2::original_recv_size, context_2::ping_rec_interval, options::ping_rec_timeout, process_received_occ_msg(), context_buffers::read_link_buf, TLS_MODE, context_2::to_tun, TUNNEL_TYPE, context_1::tuntap, and tuntap_defined().
Referenced by multi_process_incoming_link(), and process_incoming_link().
process_incoming_tun()
void process_incoming_tun (struct context * c)
Process a packet read from the virtual tun/tap network interface.
This function calls encrypt_sign() of the Data Channel Control module to process the packet.
If an error occurs, it is logged and the packet is dropped.
Parameters
c - The context structure of the VPN tunnel associated with the packet.
Definition at line 1312 of file forward.c.
References options::allow_recursive_routing, BLEN, BPTR, context_2::buf, buf_reset(), context::c1, context::c2, D_TUN_RW, dmsg, drop_if_recursive_routing(), encrypt_sign(), gc_free(), gc_new(), buffer::len, context_2::log_rw, options::mode, MODE_POINT_TO_POINT, context::options, perf_pop(), PERF_PROC_IN_TUN, perf_push(), PIP_MSSFIX, PIPV4_CLIENT_NAT, PIPV4_PASSTOS, PIPV6_IMCP_NOHOST_CLIENT, process_ip_header(), context_2::to_link, context_2::tun_read_bytes, TUNNEL_TYPE, and context_1::tuntap.
Referenced by multi_process_incoming_tun(), and process_io().
process_io()
void process_io (struct context * c)
Definition at line 2136 of file forward.c.
References ASSERT, context::c2, context_2::event_set_status, IS_SIG, management_io(), MANAGEMENT_READ, MANAGEMENT_WRITE, process_incoming_link(), process_incoming_tun(), process_outgoing_link(), process_outgoing_tun(), read_incoming_link(), read_incoming_tun(), SOCKET_READ, SOCKET_WRITE, status, TUN_READ, and TUN_WRITE.
Referenced by tunnel_point_to_point().
process_ip_header()
void process_ip_header (struct context * c, unsigned int flags, struct buffer * buf)
Definition at line 1506 of file forward.c.
References options::block_ipv6, context::c1, context::c2, options::ce, options::client_nat, client_nat_transform(), CN_INCOMING, CN_OUTGOING, dhcp_extract_router_msg(), context_2::es, context_2::frame, in_addr_t, ipv6_send_icmp_unreachable(), is_ipv4(), is_ipv6(), buffer::len, context_2::link_socket, mss_fixup_ipv4(), mss_fixup_ipv6(), connection_entry::mssfix, MTU_TO_MSS, context::options, PASSTOS_CAPABILITY, PIP_MSSFIX, PIP_OUTGOING, PIPV4_CLIENT_NAT, PIPV4_EXTRACT_DHCP_ROUTER, PIPV4_PASSTOS, PIPV6_IMCP_NOHOST_CLIENT, PIPV6_IMCP_NOHOST_SERVER, options::route_gateway_via_dhcp, context_1::route_list, route_list_add_vpn_gateway(), TUN_MTU_SIZE_DYNAMIC, TUNNEL_TYPE, and context_1::tuntap.
Referenced by multi_get_queue(), process_incoming_tun(), and process_outgoing_tun().
process_outgoing_link()
void process_outgoing_link (struct context * c)
Write a packet to the external network interface.
This function writes the packet stored in c->c2.to_link to the external network device contained within c->c1.link_socket.
If an error occurs, it is logged and the packet is dropped.
Parameters
c - The context structure of the VPN tunnel associated with the packet.
Definition at line 1605 of file forward.c.
References link_socket_info::af, ASSERT, BLEN, context_2::buf, buf_reset(), context::c2, options::ce, check_status(), D_LINK_ERRORS, D_LINK_RW, datagram_overhead(), event_timeout_reset(), EXPANDED_SIZE, context_2::frame, gc_free(), gc_new(), link_socket::info, buffer::len, context_2::link_read_bytes, context_2::link_socket, link_socket_actual_defined(), link_socket_write(), link_socket_write_post_size_adjust(), context_2::link_write_bytes, link_write_bytes_global, context_2::log_rw, M_INFO, management_bytes_out(), max_int(), context_2::max_send_size_local, options::mode, MODE_POINT_TO_POINT, msg, openvpn_errno, context::options, perf_pop(), PERF_PROC_OUT_LINK, perf_push(), context_2::ping_send_interval, options::ping_send_timeout, print_link_socket_actual(), connection_entry::proto, link_socket_info::proto, proto2ascii(), PROTO_DUMP, register_activity(), register_signal(), context_2::shaper, options::shaper, SIGUSR1, socks_preprocess_outgoing_link(), tls_initial_packet_received(), context_2::tls_multi, context_2::to_link, and context_2::to_link_addr.
Referenced by multi_process_outgoing_link_dowork(), and process_io().
process_outgoing_tun()
void process_outgoing_tun (struct context * c)
Write a packet to the virtual tun/tap network interface.
This function writes the packet stored in c->c2.to_tun to the virtual tun/tap network device c->c1.tuntap.
If an error occurs, it is logged and the packet is dropped.
Parameters
c - The context structure of the VPN tunnel associated with the packet.
Definition at line 1763 of file forward.c.
References tuntap::actual_name, BLEN, BPTR, buf_reset(), context::c1, context::c2, check_status(), D_LINK_ERRORS, D_TUN_RW, dmsg, context_2::frame, buffer::len, context_2::log_rw, MAX_RW_SIZE_TUN, msg, perf_pop(), PERF_PROC_OUT_TUN, perf_push(), PIP_MSSFIX, PIP_OUTGOING, PIPV4_CLIENT_NAT, PIPV4_EXTRACT_DHCP_ROUTER, process_ip_header(), register_activity(), context_2::to_tun, context_2::tun_write_bytes, TUNNEL_TYPE, context_1::tuntap, write_tun(), and write_tun_buffered().
Referenced by multi_process_outgoing_tun(), and process_io().
read_incoming_link()
void read_incoming_link (struct context * c)
Read a packet from the external network interface.
The packet read from the external network interface is stored in c->c2.buf and its source address in c->c2.from. If an error occurred, the length of c->c2.buf will be 0.
OpenVPN running as client or as UDP server only has a single external network socket, so this function can be called with the single (client mode) or top level (UDP server) context as its argument. OpenVPN running as TCP server, on the other hand, has a network socket for each active VPN tunnel. In that case this function must be called with the context associated with the appropriate VPN tunnel for which data is available to be read.
Parameters
c - The context structure which contains the external network socket from which to read incoming packets.
Definition at line 846 of file forward.c.
References ASSERT, context_2::buf, buf_init, context_2::buffers, context::c2, check_status(), D_STREAM_ERRORS, event_timeout_defined(), context_2::explicit_exit_notification_interval, context_2::frame, FRAME_HEADROOM_ADJ, FRAME_HEADROOM_MARKER_READ_LINK, context_2::from, options::inetd, context_2::link_socket, link_socket_read(), management_sleep(), msg, context::options, perf_pop(), perf_push(), PERF_READ_IN_LINK, context_buffers::read_link_buf, register_signal(), SIGTERM, SIGUSR1, socket_connection_reset(), socks_postprocess_incoming_link(), and status.
Referenced by multi_process_io_udp(), multi_tcp_dispatch(), and process_io().
read_incoming_tun()
void read_incoming_tun (struct context * c)
Read a packet from the virtual tun/tap network interface.
This function reads a packet from the virtual tun/tap network device c->c1.tuntap and stores it in c->c2.buf.
If an error occurs, it is logged and the packet is dropped.
Parameters
c - The context structure in which to store the received packet.
Definition at line 1155 of file forward.c.
References ASSERT, BLEN, BPTR, context_2::buf, buf_init, buf_safe(), context_2::buffers, context::c1, context::c2, check_status(), context_2::frame, FRAME_HEADROOM, buffer::len, M_INFO, MAX_RW_SIZE_TUN, msg, perf_pop(), perf_push(), PERF_READ_IN_TUN, context::persist, read_tun(), context_buffers::read_tun_buf, read_tun_buffered(), read_wintun(), register_signal(), context_persist::restart_sleep_seconds, SIGHUP, SIGTERM, TUNNEL_TYPE, context_1::tuntap, tuntap_abort(), tuntap_stop(), tuntap::windows_driver, and WINDOWS_DRIVER_WINTUN.
Referenced by multi_process_io_udp(), multi_tcp_dispatch(), and process_io().
register_activity()
static void register_activity (struct context * c, const int size) inline static
Definition at line 349 of file forward.h.
References context::c2, event_timeout_reset(), context_2::inactivity_bytes, context_2::inactivity_interval, options::inactivity_minimum_bytes, options::inactivity_timeout, and context::options.
Referenced by multi_process_incoming_link(), process_outgoing_link(), and process_outgoing_tun().
schedule_exit()
void schedule_exit (struct context * c, const int n_seconds, const int signal)
Definition at line 482 of file forward.c.
References context::c2, D_SCHED_EXIT, event_timeout_init(), msg, now, reset_coarse_timers(), context_2::scheduled_exit, context_2::scheduled_exit_signal, context_2::tls_multi, tls_set_single_session(), and update_time().
Referenced by send_auth_failed(), and send_restart().
send_control_channel_string()
bool send_control_channel_string (struct context * c, const char * str, int msglevel)
Definition at line 377 of file forward.c.
References context::c2, context_immediate_reschedule(), interval_action(), send_control_channel_string_dowork(), context_2::tls_multi, and context_2::tmp_int.
Referenced by management_callback_send_cc_message(), multi_push_restart_schedule_exit(), send_auth_failed(), send_auth_pending_messages(), send_push_options(), send_push_reply(), send_push_request(), and send_restart().
send_control_channel_string_dowork()
bool send_control_channel_string_dowork (struct tls_multi * multi, const char * str, int msglevel)
Definition at line 358 of file forward.c.
References gc_free(), gc_new(), msg, sanitize_control_message(), tls_common_name(), and tls_send_payload().
Referenced by send_control_channel_string(), and send_push_reply_auth_token().
show_wait_status()
void show_wait_status (struct context * c)
Referenced by io_wait_dowork().
wait_status_string()
const char* wait_status_string (struct context * c, struct gc_arena * gc)
Variable Documentation
link_read_bytes_global
counter_type link_read_bytes_global
Definition at line 50 of file forward.c.
Referenced by man_load_stats(), and process_incoming_link_part1().
link_write_bytes_global
counter_type link_write_bytes_global
Definition at line 51 of file forward.c.
Referenced by man_load_stats(), and process_outgoing_link().