OpenVPN: Control_processor
Control_processor
Data Structures
struct key
Container for unidirectional cipher and HMAC key material.
struct key_ctx
Container for one set of cipher and/or HMAC contexts.
struct key2
Container for bidirectional cipher and HMAC key material.
struct key_direction_state
Key ordering of the key2.keys array.
struct key_ctx_bi
Container for two sets of OpenSSL cipher and/or HMAC contexts for both sending and receiving directions.
struct key_source
Container for one half of random material to be used in key method 2 data channel key generation.
struct key_source2
Container for both halves of random material to be used in key method 2 data channel key generation.
struct key_state
Security parameter state of one TLS and data channel key session.
struct tls_session
Security parameter state of a single session within a VPN tunnel.
struct tls_multi
Security parameter state for a single VPN tunnel.
Functions for initialization and cleanup of key_state structures
static void key_state_init (struct tls_session *session, struct key_state *ks)
Initialize a key_state structure.
static void key_state_free (struct key_state *ks, bool clear)
Cleanup a key_state structure.
Functions for initialization and cleanup of tls_session structures
static void tls_session_init (struct tls_multi *multi, struct tls_session *session)
Initialize a tls_session structure.
static void tls_session_free (struct tls_session *session, bool clear)
Clean up a tls_session structure.
Functions for initialization and cleanup of tls_multi structures
struct tls_multi * tls_multi_init (struct tls_options *tls_options)
Allocate and initialize a tls_multi structure.
void tls_multi_init_finalize (struct tls_multi *multi, const struct frame *frame)
Finalize initialization of a tls_multi structure.
struct tls_auth_standalone * tls_auth_standalone_init (struct tls_options *tls_options, struct gc_arena *gc)
void tls_auth_standalone_finalize (struct tls_auth_standalone *tas, const struct frame *frame)
void tls_multi_init_set_options (struct tls_multi *multi, const char *local, const char *remote)
void tls_multi_free (struct tls_multi *multi, bool clear)
Cleanup a tls_multi structure and free associated memory allocations.
Control channel negotiation states
These states represent the different phases of control channel negotiation between OpenVPN peers.
OpenVPN servers and clients progress through the states in a different order, because of their different roles during exchange of random material. The references to the key_source2 structure in the list below is only valid if key method 2 is being used. See the data channel key generation related page for more information.
Clients follow this order:
S_INITIAL, ready to begin three-way handshake and control channel negotiation.
S_PRE_START, have started three-way handshake, waiting for acknowledgment from remote.
S_START, initial three-way handshake complete.
S_SENT_KEY, have sent local part of key_source2 random material.
S_GOT_KEY, have received remote part of key_source2 random material.
S_ACTIVE, normal operation
Servers follow the same order, except for S_SENT_KEY and S_GOT_KEY being reversed, because the server first receives the client's key_source2 random material before generating and sending its own.
#define S_ERROR -1
Error state.
#define S_UNDEF 0
Undefined state, used after a key_state is cleaned up.
#define S_INITIAL 1
Initial key_state state after initialization by key_state_init() before start of three-way handshake.
#define S_PRE_START 2
Waiting for the remote OpenVPN peer to acknowledge during the initial three-way handshake.
#define S_START 3
Three-way handshake is complete, start of key exchange.
#define S_SENT_KEY 4
Local OpenVPN process has sent its part of the key material.
#define S_GOT_KEY 5
Local OpenVPN process has received the remote's part of the key material.
#define S_ACTIVE 6
Operational key_state state immediately after negotiation has completed while still within the handshake window.
Index of key_state objects within a tls_session structure
This is the index of tls_session.key
#define KS_PRIMARY 0
Primary key state index.
#define KS_LAME_DUCK 1
Key state index that will retire soon.
#define KS_SIZE 2
Size of the tls_session.key array.
Index of tls_session objects within a tls_multi structure
This is the index of tls_multi.session
Normally three tls_session objects are maintained by an active openvpn session. The first is the current, TLS authenticated session, the second is used to process connection requests from a new client that would usurp the current session if successfully authenticated, and the third is used as a repository for a "lame-duck" key in the event that the primary session resets due to error while the lame-duck key still has time left before its expiration. Lame duck keys are used to maintain the continuity of the data channel connection while a new key is being negotiated.
#define TM_ACTIVE 0
Active tls_session.
#define TM_UNTRUSTED 1
As yet un-trusted tls_session being negotiated.
#define TM_LAME_DUCK 2
Old tls_session.
#define TM_SIZE 3
Size of the tls_multi.session array.
Detailed Description
Macro Definition Documentation
KS_LAME_DUCK
#define KS_LAME_DUCK 1
Key state index that will retire soon.
Definition at line 382 of file ssl_common.h.
KS_PRIMARY
#define KS_PRIMARY 0
Primary key state index.
Definition at line 381 of file ssl_common.h.
KS_SIZE
#define KS_SIZE 2
Size of the tls_session.key array.
Definition at line 384 of file ssl_common.h.
S_ACTIVE
#define S_ACTIVE 6
Operational key_state state immediately after negotiation has completed while still within the handshake window.
Definition at line 92 of file ssl_common.h.
S_ERROR
#define S_ERROR -1
Error state.
Definition at line 76 of file ssl_common.h.
S_GOT_KEY
#define S_GOT_KEY 5
Local OpenVPN process has received the remote's part of the key material.
Definition at line 89 of file ssl_common.h.
S_INITIAL
#define S_INITIAL 1
Initial key_state state after initialization by key_state_init() before start of three-way handshake.
Definition at line 79 of file ssl_common.h.
S_PRE_START
#define S_PRE_START 2
Waiting for the remote OpenVPN peer to acknowledge during the initial three-way handshake.
Definition at line 82 of file ssl_common.h.
S_SENT_KEY
#define S_SENT_KEY 4
Local OpenVPN process has sent its part of the key material.
Definition at line 87 of file ssl_common.h.
S_START
#define S_START 3
Three-way handshake is complete, start of key exchange.
Definition at line 85 of file ssl_common.h.
S_UNDEF
#define S_UNDEF 0
Undefined state, used after a key_state is cleaned up.
Definition at line 77 of file ssl_common.h.
TM_ACTIVE
#define TM_ACTIVE 0
Active tls_session.
Definition at line 462 of file ssl_common.h.
TM_LAME_DUCK
#define TM_LAME_DUCK 2
Old tls_session.
Definition at line 465 of file ssl_common.h.
TM_SIZE
#define TM_SIZE 3
Size of the tls_multi.session array.
Definition at line 466 of file ssl_common.h.
TM_UNTRUSTED
#define TM_UNTRUSTED 1
As yet un-trusted tls_session being negotiated.
Definition at line 463 of file ssl_common.h.
Function Documentation
key_state_free()
static void key_state_free (struct key_state * ks, bool clear) static
Cleanup a key_state structure.
This function cleans up a key_state structure. It frees the associated SSL-BIO, and the structures allocated for the Reliability Layer.
Parameters
ks - A pointer to the key_state structure to be cleaned up.
clear - Whether the memory allocated for the ks object should be overwritten with 0s.
Definition at line 996 of file ssl.c.
References key_state::ack_write_buf, buffer_list_free(), key_state::crypto_options, free_buf(), free_key_ctx_bi(), crypto_options::key_ctx_bi, key_state::key_src, key_state_rm_auth_control_file(), key_state_ssl_free(), key_state::ks_ssl, crypto_options::packet_id, packet_id_free(), key_state::paybuf, key_state::plaintext_read_buf, key_state::plaintext_write_buf, key_state::rec_ack, key_state::rec_reliable, reliable_free(), S_UNDEF, secure_memzero(), key_state::send_reliable, and key_state::state.
Referenced by key_state_soft_reset(), tls_process(), and tls_session_free().
key_state_init()
static void key_state_init (struct tls_session * session, struct key_state * ks) static
Initialize a key_state structure.
This function initializes a key_state structure associated with a tls_session. It sets up the structure's SSL-BIO, sets the object's key_state.state to S_INITIAL, and sets the session ID and key ID two appropriate values based on the tls_session's internal state. It also initializes a new set of structures for the Reliability Layer.
Parameters
session - A pointer to the tls_session structure associated with the ks argument.
ks - A pointer to the key_state structure to be initialized. This structure should already have been allocated before calling this function.
Definition at line 916 of file ssl.c.
References key_state::ack_write_buf, alloc_buf(), ALLOC_OBJ_CLEAR, BUF_SIZE, CLEAR, key_state::crypto_options, FRAME_HEADROOM, key_state::initial_opcode, key_state::key_id, key_state::key_src, key_state_ssl_init(), key_state::ks_ssl, P_CONTROL_SOFT_RESET_V1, P_KEY_ID_MASK, crypto_options::packet_id, packet_id_init(), crypto_options::pid_persist, key_state::plaintext_read_buf, key_state::plaintext_write_buf, key_state::rec_ack, key_state::rec_reliable, reliable_init(), reliable_set_timeout(), S_INITIAL, key_state::send_reliable, key_state::state, TLS_CHANNEL_BUF_SIZE, TLS_RELIABLE_N_REC_BUFFERS, TLS_RELIABLE_N_SEND_BUFFERS, and update_time().
Referenced by key_state_soft_reset(), and tls_session_init().
tls_auth_standalone_finalize()
void tls_auth_standalone_finalize (struct tls_auth_standalone * tas, const struct frame * frame)
Definition at line 1323 of file ssl.c.
References tls_auth_standalone::frame, and tls_init_control_channel_frame_parameters().
Referenced by do_init_finalize_tls_frame().
tls_auth_standalone_init()
struct tls_auth_standalone* tls_auth_standalone_init (struct tls_options * tls_options, struct gc_arena * gc)
Definition at line 1300 of file ssl.c.
References ALLOC_OBJ_CLEAR_GC, CO_IGNORE_PACKET_ID, crypto_options::flags, tls_options::frame, tls_auth_standalone::frame, tls_wrap_ctx::opt, tls_options::tls_wrap, and tls_auth_standalone::tls_wrap.
Referenced by do_init_crypto_tls().
tls_multi_free()
void tls_multi_free (struct tls_multi * multi, bool clear)
Cleanup a tls_multi structure and free associated memory allocations.
This function cleans up a tls_multi structure. This includes cleaning up all associated tls_session structures.
Parameters
multi - The tls_multi structure to clean up in free.
clear - Whether the memory allocated for the multi object should be overwritten with 0s.
Definition at line 1348 of file ssl.c.
References ASSERT, auth_set_client_reason(), cert_hash_free(), tls_multi::locked_cert_hash_set, tls_multi::locked_cn, tls_multi::locked_username, tls_multi::peer_info, tls_multi::remote_ciphername, secure_memzero(), tls_multi::session, tls_session_free(), TM_SIZE, and wipe_auth_token().
Referenced by do_close_tls().
tls_multi_init()
struct tls_multi* tls_multi_init (struct tls_options * tls_options)
Allocate and initialize a tls_multi structure.
This function allocates a new tls_multi structure, and performs some amount of initialization. Afterwards, the tls_multi_init_finalize() function must be called to finalize the structure's initialization process.
Parameters
tls_options - The configuration options to be used for this VPN tunnel.
Returns
A newly allocated and initialized tls_multi structure.
Definition at line 1259 of file ssl.c.
References ALLOC_OBJ_CLEAR, ASSERT, tls_session::key, tls_multi::key_scan, KS_LAME_DUCK, KS_PRIMARY, tls_multi::opt, tls_multi::session, SIZE, TM_ACTIVE, TM_LAME_DUCK, and tls_multi::use_peer_id.
Referenced by do_init_crypto_tls().
tls_multi_init_finalize()
void tls_multi_init_finalize (struct tls_multi * multi, const struct frame * frame)
Finalize initialization of a tls_multi structure.
This function initializes the TM_ACTIVE tls_session, and in server mode also the TM_UNTRUSTED tls_session, associated with this tls_multi structure. It also configures the control channel's frame structure based on the data channel's frame given in argument frame.
Parameters
multi - The tls_multi structure of which to finalize initialization.
frame - The data channel's frame structure.
Definition at line 1281 of file ssl.c.
References tls_options::frame, tls_multi::opt, tls_multi::session, tls_options::single_session, tls_init_control_channel_frame_parameters(), tls_session_init(), TM_ACTIVE, and TM_UNTRUSTED.
Referenced by do_init_finalize_tls_frame().
tls_multi_init_set_options()
void tls_multi_init_set_options (struct tls_multi * multi, const char * local, const char * remote)
Definition at line 1335 of file ssl.c.
References tls_options::local_options, tls_multi::opt, and tls_options::remote_options.
Referenced by do_compute_occ_strings().
tls_session_free()
static void tls_session_free (struct tls_session * session, bool clear) static
Clean up a tls_session structure.
This function cleans up a tls_session structure. This includes cleaning up all associated key_state structures.
Parameters
session - A pointer to the tls_session structure to be cleaned up.
clear - Whether the memory allocated for the session object should be overwritten with 0s.
Definition at line 1151 of file ssl.c.
References cert_hash_free(), session::key, key_state_free(), KS_SIZE, secure_memzero(), and tls_wrap_free().
Referenced by move_session(), reset_session(), tls_multi_free(), and tls_multi_process().
tls_session_init()
static void tls_session_init (struct tls_multi * multi, struct tls_session * session) static
Initialize a tls_session structure.
This function initializes a tls_session structure. This includes generating a random session ID, and initializing the KS_PRIMARY key_state in the tls_session.key array.
Parameters
multi - A pointer to the tls_multi structure associated with the session argument.
session - A pointer to the tls_session structure to be initialized. This structure should already have been allocated before calling this function.
Definition at line 1088 of file ssl.c.
References alloc_buf(), BUF_SIZE, CLEAR, D_TLS_DEBUG, dmsg, gc_free(), gc_new(), session::key, key_state_init(), KS_PRIMARY, tls_multi::opt, P_CONTROL_HARD_RESET_CLIENT_V2, P_CONTROL_HARD_RESET_CLIENT_V3, P_CONTROL_HARD_RESET_SERVER_V2, packet_id_init(), packet_id_persist_load_obj(), session_id_defined(), session_id_print(), and session_id_random().
Referenced by move_session(), reset_session(), and tls_multi_init_finalize().