OpenVPN: src/openvpn/httpdigest.c File Reference
httpdigest.c File Reference
#include "syshead.h"
#include "crypto.h"
#include "httpdigest.h"
Functions
static void CvtHex (IN HASH Bin, OUT HASHHEX Hex)
void DigestCalcHA1 (IN char *pszAlg, IN char *pszUserName, IN char *pszRealm, IN char *pszPassword, IN char *pszNonce, IN char *pszCNonce, OUT HASHHEX SessionKey)
void DigestCalcResponse (IN HASHHEX HA1, IN char *pszNonce, IN char *pszNonceCount, IN char *pszCNonce, IN char *pszQop, IN char *pszMethod, IN char *pszDigestUri, IN HASHHEX HEntity, OUT HASHHEX Response)
Function Documentation
CvtHex()
static void CvtHex (IN HASH Bin, OUT HASHHEX Hex) static
Definition at line 38 of file httpdigest.c.
Referenced by DigestCalcHA1(), and DigestCalcResponse().
DigestCalcHA1()
void DigestCalcHA1 (IN char * pszAlg, IN char * pszUserName, IN char * pszRealm, IN char * pszPassword, IN char * pszNonce, IN char * pszCNonce, OUT HASHHEX SessionKey)
Definition at line 72 of file httpdigest.c.
References CvtHex(), md_ctx_cleanup(), md_ctx_final(), md_ctx_free(), md_ctx_init(), md_ctx_new(), md_ctx_update(), md_kt_get(), and strcasecmp.
Referenced by establish_http_proxy_passthru().
DigestCalcResponse()
void DigestCalcResponse (IN HASHHEX HA1, IN char * pszNonce, IN char * pszNonceCount, IN char * pszCNonce, IN char * pszQop, IN char * pszMethod, IN char * pszDigestUri, IN HASHHEX HEntity, OUT HASHHEX Response)
Definition at line 110 of file httpdigest.c.
References CvtHex(), md_ctx_cleanup(), md_ctx_final(), md_ctx_free(), md_ctx_init(), md_ctx_new(), md_ctx_update(), md_kt_get(), and strcasecmp.
Referenced by establish_http_proxy_passthru().