OpenVPN: src/openvpn/interval.h File Reference
interval.h File Reference
#include "otime.h"
Data Structures
struct interval
struct event_timeout
struct usec_timer
Macros
#define INTERVAL_DEBUG 0
#define ETT_DEFAULT (-1)
#define USEC_TIMER_MAX 60 /* maximum interval size in seconds */
#define USEC_TIMER_MAX_USEC (USEC_TIMER_MAX * 1000000)
Functions
void interval_init (struct interval *top, int horizon, int refresh)
static bool interval_test (struct interval *top)
static void interval_schedule_wakeup (struct interval *top, interval_t *wakeup)
static void interval_future_trigger (struct interval *top, interval_t wakeup)
static void interval_action (struct interval *top)
static bool event_timeout_defined (const struct event_timeout *et)
static void event_timeout_clear (struct event_timeout *et)
static struct event_timeout event_timeout_clear_ret (void)
static void event_timeout_init (struct event_timeout *et, interval_t n, const time_t local_now)
static void event_timeout_reset (struct event_timeout *et)
static void event_timeout_modify_wakeup (struct event_timeout *et, interval_t n)
static interval_t event_timeout_remaining (struct event_timeout *et)
bool event_timeout_trigger (struct event_timeout *et, struct timeval *tv, const int et_const_retry)
static void usec_timer_start (struct usec_timer *obj)
static void usec_timer_end (struct usec_timer *obj)
static bool usec_timer_interval_defined (struct usec_timer *obj)
static int usec_timer_interval (struct usec_timer *obj)
Macro Definition Documentation
ETT_DEFAULT
#define ETT_DEFAULT (-1)
Definition at line 213 of file interval.h.
INTERVAL_DEBUG
#define INTERVAL_DEBUG 0
Definition at line 35 of file interval.h.
USEC_TIMER_MAX
#define USEC_TIMER_MAX 60 /* maximum interval size in seconds */
Definition at line 223 of file interval.h.
USEC_TIMER_MAX_USEC
#define USEC_TIMER_MAX_USEC (USEC_TIMER_MAX * 1000000)
Definition at line 225 of file interval.h.
Function Documentation
event_timeout_clear()
static void event_timeout_clear (struct event_timeout * et) inline static
Definition at line 150 of file interval.h.
References event_timeout::defined, event_timeout::last, and event_timeout::n.
Referenced by check_add_routes_action(), check_connection_established(), check_send_occ_load_test_dowork(), check_send_occ_req_dowork(), event_timeout_clear_ret(), incoming_push_message(), process_explicit_exit_notification_timer_wakeup(), process_received_occ_msg(), and status_open().
event_timeout_clear_ret()
static struct event_timeout event_timeout_clear_ret (void) inline static
Definition at line 158 of file interval.h.
References event_timeout_clear().
event_timeout_defined()
static bool event_timeout_defined (const struct event_timeout * et) inline static
Definition at line 144 of file interval.h.
References event_timeout::defined.
Referenced by check_send_occ_load_test(), check_send_occ_req(), ignore_restart_signals(), and read_incoming_link().
event_timeout_init()
static void event_timeout_init (struct event_timeout * et, interval_t n, const time_t local_now) inline static
Definition at line 166 of file interval.h.
References event_timeout::defined, event_timeout::last, and event_timeout::n.
Referenced by check_add_routes(), check_connection_established(), do_init_server_poll_timeout(), do_init_timers(), do_up(), fragment_init(), multi_init(), process_explicit_exit_notification_init(), schedule_exit(), and status_open().
event_timeout_modify_wakeup()
static void event_timeout_modify_wakeup (struct event_timeout * et, interval_t n) inline static
Definition at line 183 of file interval.h.
References event_timeout::defined, and event_timeout::n.
Referenced by check_push_request().
event_timeout_remaining()
static interval_t event_timeout_remaining (struct event_timeout * et) inline static
Definition at line 197 of file interval.h.
References event_timeout::last, event_timeout::n, and now.
Referenced by get_server_poll_remaining_time().
event_timeout_reset()
static void event_timeout_reset (struct event_timeout * et) inline static
Definition at line 174 of file interval.h.
References event_timeout::defined, event_timeout::last, and now.
Referenced by check_add_routes(), check_send_occ_req_dowork(), check_server_poll_timeout(), process_incoming_link_part1(), process_incoming_link_part2(), process_outgoing_link(), and register_activity().
event_timeout_trigger()
bool event_timeout_trigger (struct event_timeout * et, struct timeval * tv, const int et_const_retry)
Definition at line 45 of file interval.c.
References D_INTERVAL, event_timeout::defined, dmsg, event_timeout::last, event_timeout::n, and now.
Referenced by check_add_routes(), check_ping_restart(), check_ping_send(), check_send_occ_load_test(), check_send_occ_req(), process_coarse_timers(), process_explicit_exit_notification_timer_wakeup(), stale_route_check_trigger(), and status_trigger().
interval_action()
static void interval_action (struct interval * top) inline static
Definition at line 124 of file interval.h.
References D_INTERVAL, dmsg, interval::last_action, and now.
Referenced by check_tls(), process_incoming_link_part1(), and send_control_channel_string().
interval_future_trigger()
static void interval_future_trigger (struct interval * top, interval_t wakeup) inline static
Definition at line 108 of file interval.h.
References D_INTERVAL, dmsg, interval::future_trigger, and now.
Referenced by check_tls().
interval_init()
void interval_init (struct interval * top, int horizon, int refresh)
Definition at line 37 of file interval.c.
References CLEAR, interval::horizon, and interval::refresh.
Referenced by do_init_timers().
interval_schedule_wakeup()
static void interval_schedule_wakeup (struct interval * top, interval_t * wakeup) inline static
Definition at line 94 of file interval.h.
References D_INTERVAL, dmsg, interval::future_trigger, interval_earliest_wakeup(), interval::last_test_true, now, and interval::refresh.
Referenced by check_tls().
interval_test()
static bool interval_test (struct interval * top) inline static
Definition at line 66 of file interval.h.
References D_INTERVAL, dmsg, interval::future_trigger, interval::horizon, interval::last_action, interval::last_test_true, now, and interval::refresh.
Referenced by check_tls().
usec_timer_end()
static void usec_timer_end (struct usec_timer * obj) inline static
Definition at line 242 of file interval.h.
References usec_timer::end, and openvpn_gettimeofday().
usec_timer_interval()
static int usec_timer_interval (struct usec_timer * obj) inline static
Definition at line 256 of file interval.h.
References usec_timer::end, usec_timer::start, tv_subtract(), and USEC_TIMER_MAX.
usec_timer_interval_defined()
static bool usec_timer_interval_defined (struct usec_timer * obj) inline static
Definition at line 250 of file interval.h.
References usec_timer::end, and usec_timer::start.
usec_timer_start()
static void usec_timer_start (struct usec_timer * obj) inline static
Definition at line 235 of file interval.h.
References CLEAR, openvpn_gettimeofday(), and usec_timer::start.