OpenVPN: src/openvpnserv/interactive.c File Reference
interactive.c File Reference
#include "service.h"
#include <ws2tcpip.h>
#include <iphlpapi.h>
#include <userenv.h>
#include <accctrl.h>
#include <aclapi.h>
#include <stdio.h>
#include <sddl.h>
#include <shellapi.h>
#include <mstcpip.h>
#include "compat-versionhelpers.h"
#include "openvpn-msg.h"
#include "validate.h"
#include "block_dns.h"
#include "ring_buffer.h"
Data Structures
struct STARTUP_DATA
struct _list_item
struct block_dns_data_t
struct ring_buffer_handles_t
union pipe_message_t
Macros
#define IO_TIMEOUT 2000 /*ms*/
#define ERROR_OPENVPN_STARTUP 0x20000000
#define ERROR_STARTUP_DATA 0x20000001
#define ERROR_MESSAGE_DATA 0x20000002
#define ERROR_MESSAGE_TYPE 0x20000003
#define RDNS_TIMEOUT 600 /* seconds to wait for the semaphore */
#define TUN_IOCTL_REGISTER_RINGS CTL_CODE(51820U, 0x970U, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
Typedefs
typedef struct _list_item list_item_t
typedef list_item_t * undo_lists_t[_undo_type_max]
typedef BOOL(* match_fn_t) (LPVOID item, LPVOID ctx)
Enumerations
enum undo_type_t {
address, route, block_dns, undo_dns4,
undo_dns6, undo_domain, _undo_type_max
}
enum async_op_t { peek, read, write }
Functions
static DWORD AddListItem (list_item_t **pfirst, LPVOID data)
static LPVOID RemoveListItem (list_item_t **pfirst, match_fn_t match, LPVOID ctx)
static HANDLE CloseHandleEx (LPHANDLE handle)
static HANDLE OvpnUnmapViewOfFile (LPHANDLE handle)
static void CloseRingBufferHandles (ring_buffer_handles_t *ring_buffer_handles)
static HANDLE InitOverlapped (LPOVERLAPPED overlapped)
static BOOL ResetOverlapped (LPOVERLAPPED overlapped)
static DWORD AsyncPipeOp (async_op_t op, HANDLE pipe, LPVOID buffer, DWORD size, DWORD count, LPHANDLE events)
static DWORD PeekNamedPipeAsync (HANDLE pipe, DWORD count, LPHANDLE events)
static DWORD ReadPipeAsync (HANDLE pipe, LPVOID buffer, DWORD size, DWORD count, LPHANDLE events)
static DWORD WritePipeAsync (HANDLE pipe, LPVOID data, DWORD size, DWORD count, LPHANDLE events)
static VOID ReturnProcessId (HANDLE pipe, DWORD pid, DWORD count, LPHANDLE events)
static VOID ReturnError (HANDLE pipe, DWORD error, LPCWSTR func, DWORD count, LPHANDLE events)
static VOID ReturnLastError (HANDLE pipe, LPCWSTR func)
static BOOL ValidateOptions (HANDLE pipe, const WCHAR *workdir, const WCHAR *options, WCHAR *errmsg, DWORD capacity)
static BOOL GetStartupData (HANDLE pipe, STARTUP_DATA *sud)
static VOID FreeStartupData (STARTUP_DATA *sud)
static SOCKADDR_INET sockaddr_inet (short family, inet_address_t *addr)
static DWORD InterfaceLuid (const char *iface_name, PNET_LUID luid)
static DWORD ConvertInterfaceNameToIndex (const wchar_t *ifname, NET_IFINDEX *index)
static BOOL CmpAddress (LPVOID item, LPVOID address)
static DWORD DeleteAddress (PMIB_UNICASTIPADDRESS_ROW addr_row)
static DWORD HandleAddressMessage (address_message_t *msg, undo_lists_t *lists)
static BOOL CmpRoute (LPVOID item, LPVOID route)
static DWORD DeleteRoute (PMIB_IPFORWARD_ROW2 fwd_row)
static DWORD HandleRouteMessage (route_message_t *msg, undo_lists_t *lists)
static DWORD HandleFlushNeighborsMessage (flush_neighbors_message_t *msg)
static void BlockDNSErrHandler (DWORD err, const char *msg)
static BOOL CmpEngine (LPVOID item, LPVOID any)
static DWORD HandleBlockDNSMessage (const block_dns_message_t *msg, undo_lists_t *lists)
static DWORD ExecCommand (const WCHAR *argv0, const WCHAR *cmdline, DWORD timeout)
static DWORD WINAPI RegisterDNS (LPVOID unused)
static DWORD HandleRegisterDNSMessage (void)
static DWORD netsh_dns_cmd (const wchar_t *action, const wchar_t *proto, const wchar_t *if_name, const wchar_t *addr)
Run the command: netsh interface $proto $action dns $if_name $addr [validate=no].
static DWORD wmic_nicconfig_cmd (const wchar_t *action, const NET_IFINDEX if_index, const wchar_t *data)
Run command: wmic nicconfig (InterfaceIndex=$if_index) call $action ($data)
static DWORD DeleteDNS (short family, wchar_t *if_name)
static DWORD AddDNS (short family, wchar_t *if_name, wchar_t *addr)
static BOOL CmpWString (LPVOID item, LPVOID str)
static DWORD SetDNSDomain (const wchar_t *if_name, const char *domain, undo_lists_t *lists)
Set interface specific DNS domain suffix.
static DWORD HandleDNSConfigMessage (const dns_cfg_message_t *msg, undo_lists_t *lists)
static DWORD HandleEnableDHCPMessage (const enable_dhcp_message_t *dhcp)
static DWORD OvpnDuplicateHandle (HANDLE ovpn_proc, HANDLE orig_handle, HANDLE *new_handle)
static DWORD DuplicateAndMapRing (HANDLE ovpn_proc, HANDLE orig_handle, HANDLE *new_handle, struct tun_ring **ring)
static DWORD HandleRegisterRingBuffers (const register_ring_buffers_message_t *rrb, HANDLE ovpn_proc, ring_buffer_handles_t *ring_buffer_handles)
static DWORD HandleMTUMessage (const set_mtu_message_t *mtu)
static VOID HandleMessage (HANDLE pipe, HANDLE ovpn_proc, ring_buffer_handles_t *ring_buffer_handles, DWORD bytes, DWORD count, LPHANDLE events, undo_lists_t *lists)
static VOID Undo (undo_lists_t *lists)
static DWORD WINAPI RunOpenvpn (LPVOID p)
static DWORD WINAPI ServiceCtrlInteractive (DWORD ctrl_code, DWORD event, LPVOID data, LPVOID ctx)
static HANDLE CreateClientPipeInstance (VOID)
static DWORD UpdateWaitHandles (LPHANDLE *handles_ptr, LPDWORD count, HANDLE io_event, HANDLE exit_event, list_item_t *threads)
static VOID FreeWaitHandles (LPHANDLE h)
static BOOL CmpHandle (LPVOID item, LPVOID hnd)
VOID WINAPI ServiceStartInteractiveOwn (DWORD dwArgc, LPTSTR *lpszArgv)
VOID WINAPI ServiceStartInteractive (DWORD dwArgc, LPTSTR *lpszArgv)
Variables
static SERVICE_STATUS_HANDLE service
static SERVICE_STATUS status = { .dwServiceType = SERVICE_WIN32_SHARE_PROCESS }
static HANDLE exit_event = NULL
static settings_t settings
static HANDLE rdns_semaphore = NULL
openvpn_service_t interactive_service
Macro Definition Documentation
ERROR_MESSAGE_DATA
#define ERROR_MESSAGE_DATA 0x20000002
Definition at line 52 of file interactive.c.
ERROR_MESSAGE_TYPE
#define ERROR_MESSAGE_TYPE 0x20000003
Definition at line 53 of file interactive.c.
ERROR_OPENVPN_STARTUP
#define ERROR_OPENVPN_STARTUP 0x20000000
Definition at line 50 of file interactive.c.
ERROR_STARTUP_DATA
#define ERROR_STARTUP_DATA 0x20000001
Definition at line 51 of file interactive.c.
IO_TIMEOUT
#define IO_TIMEOUT 2000 /*ms*/
Definition at line 48 of file interactive.c.
RDNS_TIMEOUT
#define RDNS_TIMEOUT 600 /* seconds to wait for the semaphore */
Definition at line 60 of file interactive.c.
TUN_IOCTL_REGISTER_RINGS
#define TUN_IOCTL_REGISTER_RINGS CTL_CODE(51820U, 0x970U, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
Definition at line 62 of file interactive.c.
Typedef Documentation
list_item_t
typedef struct _list_item list_item_t
match_fn_t
typedef BOOL(* match_fn_t) (LPVOID item, LPVOID ctx)
Definition at line 142 of file interactive.c.
undo_lists_t
typedef list_item_t* undo_lists_t[_undo_type_max]
Definition at line 97 of file interactive.c.
Enumeration Type Documentation
async_op_t
enum async_op_t
Enumerator
peek
read
write
Definition at line 223 of file interactive.c.
undo_type_t
enum undo_type_t
Enumerator
address
route
block_dns
undo_dns4
undo_dns6
undo_domain
_undo_type_max
Definition at line 88 of file interactive.c.
Function Documentation
AddDNS()
static DWORD AddDNS (short family, wchar_t * if_name, wchar_t * addr) static
Definition at line 1147 of file interactive.c.
References netsh_dns_cmd().
Referenced by HandleDNSConfigMessage().
AddListItem()
static DWORD AddListItem (list_item_t ** pfirst, LPVOID data) static
Definition at line 127 of file interactive.c.
References _list_item::data, and _list_item::next.
Referenced by HandleAddressMessage(), HandleBlockDNSMessage(), HandleDNSConfigMessage(), HandleRouteMessage(), ServiceStartInteractive(), and SetDNSDomain().
AsyncPipeOp()
static DWORD AsyncPipeOp (async_op_t op, HANDLE pipe, LPVOID buffer, DWORD size, DWORD count, LPHANDLE events) static
Definition at line 230 of file interactive.c.
References CloseHandleEx(), InitOverlapped(), IO_TIMEOUT, peek, and write.
Referenced by PeekNamedPipeAsync(), ReadPipeAsync(), and WritePipeAsync().
BlockDNSErrHandler()
static void BlockDNSErrHandler (DWORD err, const char * msg) static
Definition at line 771 of file interactive.c.
References M_ERR, msg, and MsgToEventLog().
Referenced by HandleBlockDNSMessage().
CloseHandleEx()
static HANDLE CloseHandleEx (LPHANDLE handle) static
Definition at line 169 of file interactive.c.
Referenced by AsyncPipeOp(), CloseRingBufferHandles(), CreateClientPipeInstance(), RunOpenvpn(), and ServiceStartInteractive().
CloseRingBufferHandles()
static void CloseRingBufferHandles (ring_buffer_handles_t * ring_buffer_handles) static
Definition at line 191 of file interactive.c.
References CloseHandleEx(), ring_buffer_handles_t::device, OvpnUnmapViewOfFile(), ring_buffer_handles_t::receive_ring_handle, ring_buffer_handles_t::receive_tail_moved, ring_buffer_handles_t::send_ring_handle, and ring_buffer_handles_t::send_tail_moved.
Referenced by HandleRegisterRingBuffers(), and RunOpenvpn().
CmpAddress()
static BOOL CmpAddress (LPVOID item, LPVOID address) static
Definition at line 598 of file interactive.c.
References address.
Referenced by HandleAddressMessage().
CmpEngine()
static BOOL CmpEngine (LPVOID item, LPVOID any) static
Definition at line 800 of file interactive.c.
Referenced by HandleBlockDNSMessage().
CmpHandle()
static BOOL CmpHandle (LPVOID item, LPVOID hnd) static
Definition at line 2093 of file interactive.c.
Referenced by ServiceStartInteractive().
CmpRoute()
static BOOL CmpRoute (LPVOID item, LPVOID route) static
Definition at line 676 of file interactive.c.
References route.
Referenced by HandleRouteMessage().
CmpWString()
static BOOL CmpWString (LPVOID item, LPVOID str) static
Definition at line 1154 of file interactive.c.
Referenced by HandleDNSConfigMessage(), and SetDNSDomain().
ConvertInterfaceNameToIndex()
static DWORD ConvertInterfaceNameToIndex (const wchar_t * ifname, NET_IFINDEX * index) static
Definition at line 580 of file interactive.c.
References M_ERR, and MsgToEventLog().
Referenced by SetDNSDomain().
CreateClientPipeInstance()
static HANDLE CreateClientPipeInstance (VOID) static
Definition at line 1963 of file interactive.c.
References CloseHandleEx(), M_SYSERR, MsgToEventLog(), openvpn_sntprintf(), PACKAGE, and service_instance.
Referenced by ServiceStartInteractive().
DeleteAddress()
static DWORD DeleteAddress (PMIB_UNICASTIPADDRESS_ROW addr_row) static
Definition at line 604 of file interactive.c.
Referenced by HandleAddressMessage(), and Undo().
DeleteDNS()
static DWORD DeleteDNS (short family, wchar_t * if_name) static
Definition at line 1139 of file interactive.c.
References netsh_dns_cmd().
Referenced by HandleDNSConfigMessage(), and Undo().
DeleteRoute()
static DWORD DeleteRoute (PMIB_IPFORWARD_ROW2 fwd_row) static
Definition at line 682 of file interactive.c.
Referenced by HandleRouteMessage(), and Undo().
DuplicateAndMapRing()
static DWORD DuplicateAndMapRing (HANDLE ovpn_proc, HANDLE orig_handle, HANDLE * new_handle, struct tun_ring ** ring) static
Definition at line 1361 of file interactive.c.
References M_SYSERR, MsgToEventLog(), and OvpnDuplicateHandle().
Referenced by HandleRegisterRingBuffers().
ExecCommand()
static DWORD ExecCommand (const WCHAR * argv0, const WCHAR * cmdline, DWORD timeout) static
Definition at line 899 of file interactive.c.
References M_ERR, M_INFO, M_SYSERR, and MsgToEventLog().
Referenced by HandleEnableDHCPMessage(), netsh_dns_cmd(), RegisterDNS(), and wmic_nicconfig_cmd().
FreeStartupData()
static VOID FreeStartupData (STARTUP_DATA * sud) static
Definition at line 538 of file interactive.c.
References STARTUP_DATA::directory.
Referenced by RunOpenvpn().
FreeWaitHandles()
static VOID FreeWaitHandles (LPHANDLE h) static
Definition at line 2087 of file interactive.c.
Referenced by ServiceStartInteractive().
GetStartupData()
static BOOL GetStartupData (HANDLE pipe, STARTUP_DATA * sud) static
Definition at line 462 of file interactive.c.
References STARTUP_DATA::directory, ERROR_STARTUP_DATA, exit_event, M_ERR, M_SYSERR, MsgToEventLog(), STARTUP_DATA::options, PeekNamedPipeAsync(), read, ReadPipeAsync(), ReturnError(), ReturnLastError(), and STARTUP_DATA::std_input.
Referenced by RunOpenvpn().
HandleAddressMessage()
static DWORD HandleAddressMessage (address_message_t * msg, undo_lists_t * lists) static
Definition at line 610 of file interactive.c.
References AddListItem(), address, CmpAddress(), DeleteAddress(), InterfaceLuid(), msg, msg_add_address, RemoveListItem(), and sockaddr_inet().
Referenced by HandleMessage().
HandleBlockDNSMessage()
static DWORD HandleBlockDNSMessage (const block_dns_message_t * msg, undo_lists_t * lists) static
Definition at line 806 of file interactive.c.
References add_block_dns_filters(), AddListItem(), block_dns, BLOCK_DNS_IFACE_METRIC, BlockDNSErrHandler(), CmpEngine(), delete_block_dns_filters(), block_dns_data_t::engine, settings_t::exe_path, get_interface_metric(), block_dns_data_t::index, M_ERR, block_dns_data_t::metric_v4, block_dns_data_t::metric_v6, msg, msg_add_block_dns, MsgToEventLog(), RemoveListItem(), set_interface_metric(), and settings.
Referenced by HandleMessage().
HandleDNSConfigMessage()
static DWORD HandleDNSConfigMessage (const dns_cfg_message_t * msg, undo_lists_t * lists) static
Definition at line 1208 of file interactive.c.
References AddDNS(), AddListItem(), CmpWString(), DeleteDNS(), dns_cfg_message_t::domains, ERROR_MESSAGE_DATA, dns_cfg_message_t::iface, msg, msg_del_dns_cfg, interface_t::name, RemoveListItem(), SetDNSDomain(), undo_dns4, undo_dns6, and utf8to16().
Referenced by HandleMessage().
HandleEnableDHCPMessage()
static DWORD HandleEnableDHCPMessage (const enable_dhcp_message_t * dhcp) static
Definition at line 1307 of file interactive.c.
References ExecCommand(), get_win_sys_path(), and openvpn_sntprintf().
Referenced by HandleMessage().
HandleFlushNeighborsMessage()
static DWORD HandleFlushNeighborsMessage (flush_neighbors_message_t * msg) static
Definition at line 760 of file interactive.c.
References msg.
Referenced by HandleMessage().
HandleMessage()
static VOID HandleMessage (HANDLE pipe, HANDLE ovpn_proc, ring_buffer_handles_t * ring_buffer_handles, DWORD bytes, DWORD count, LPHANDLE events, undo_lists_t * lists) static
Definition at line 1455 of file interactive.c.
References ERROR_MESSAGE_DATA, ERROR_MESSAGE_TYPE, ack_message_t::error_number, HandleAddressMessage(), HandleBlockDNSMessage(), HandleDNSConfigMessage(), HandleEnableDHCPMessage(), HandleFlushNeighborsMessage(), HandleMTUMessage(), HandleRegisterDNSMessage(), HandleRegisterRingBuffers(), HandleRouteMessage(), ack_message_t::header, message_header_t::message_id, msg, msg_acknowledgement, msg_add_address, msg_add_block_dns, msg_add_dns_cfg, msg_add_route, msg_del_address, msg_del_block_dns, msg_del_dns_cfg, msg_del_route, msg_enable_dhcp, MSG_FLAGS_ERROR, msg_flush_neighbors, msg_register_dns, msg_register_ring_buffers, msg_set_mtu, MsgToEventLog(), read, ReadPipeAsync(), message_header_t::type, and WritePipeAsync().
Referenced by RunOpenvpn().
HandleMTUMessage()
static DWORD HandleMTUMessage (const set_mtu_message_t * mtu) static
Definition at line 1432 of file interactive.c.
References set_mtu_message_t::family, set_mtu_message_t::iface, interface_t::index, and set_mtu_message_t::mtu.
Referenced by HandleMessage().
HandleRegisterDNSMessage()
static DWORD HandleRegisterDNSMessage (void) static
Definition at line 1005 of file interactive.c.
References RegisterDNS().
Referenced by HandleMessage().
HandleRegisterRingBuffers()
static DWORD HandleRegisterRingBuffers (const register_ring_buffers_message_t * rrb, HANDLE ovpn_proc, ring_buffer_handles_t * ring_buffer_handles) static
Definition at line 1382 of file interactive.c.
References CloseRingBufferHandles(), ring_buffer_handles_t::device, register_ring_buffers_message_t::device, DuplicateAndMapRing(), M_SYSERR, MsgToEventLog(), OvpnDuplicateHandle(), ring_buffer_handles_t::receive_ring_handle, register_ring_buffers_message_t::receive_ring_handle, ring_buffer_handles_t::receive_tail_moved, register_ring_buffers_message_t::receive_tail_moved, register_ring_buffers(), ring_buffer_handles_t::send_ring_handle, register_ring_buffers_message_t::send_ring_handle, ring_buffer_handles_t::send_tail_moved, and register_ring_buffers_message_t::send_tail_moved.
Referenced by HandleMessage().
HandleRouteMessage()
static DWORD HandleRouteMessage (route_message_t * msg, undo_lists_t * lists) static
Definition at line 688 of file interactive.c.
References AddListItem(), CmpRoute(), DeleteRoute(), InterfaceLuid(), msg, msg_add_route, RemoveListItem(), route, and sockaddr_inet().
Referenced by HandleMessage().
InitOverlapped()
static HANDLE InitOverlapped (LPOVERLAPPED overlapped) static
Definition at line 201 of file interactive.c.
Referenced by AsyncPipeOp(), and ServiceStartInteractive().
InterfaceLuid()
static DWORD InterfaceLuid (const char * iface_name, PNET_LUID luid) static
Definition at line 562 of file interactive.c.
References status, and utf8to16().
Referenced by get_default_gateway_ipv6(), HandleAddressMessage(), and HandleRouteMessage().
netsh_dns_cmd()
static DWORD netsh_dns_cmd (const wchar_t * action, const wchar_t * proto, const wchar_t * if_name, const wchar_t * addr) static
Run the command: netsh interface $proto $action dns $if_name $addr [validate=no].
Parameters
action "delete" or "add"
proto "ipv6" or "ip"
if_name "name_of_interface"
addr IPv4 (for proto = ip) or IPv6 address as a string
If addr is null and action = "delete" all addresses are deleted.
Definition at line 1040 of file interactive.c.
References ExecCommand(), get_win_sys_path(), and openvpn_sntprintf().
Referenced by AddDNS(), and DeleteDNS().
OvpnDuplicateHandle()
static DWORD OvpnDuplicateHandle (HANDLE ovpn_proc, HANDLE orig_handle, HANDLE * new_handle) static
Definition at line 1346 of file interactive.c.
References M_SYSERR, and MsgToEventLog().
Referenced by DuplicateAndMapRing(), and HandleRegisterRingBuffers().
OvpnUnmapViewOfFile()
static HANDLE OvpnUnmapViewOfFile (LPHANDLE handle) static
Definition at line 180 of file interactive.c.
Referenced by CloseRingBufferHandles().
PeekNamedPipeAsync()
static DWORD PeekNamedPipeAsync (HANDLE pipe, DWORD count, LPHANDLE events) static
Definition at line 294 of file interactive.c.
References AsyncPipeOp(), and peek.
Referenced by GetStartupData(), and RunOpenvpn().
ReadPipeAsync()
static DWORD ReadPipeAsync (HANDLE pipe, LPVOID buffer, DWORD size, DWORD count, LPHANDLE events) static
Definition at line 300 of file interactive.c.
References AsyncPipeOp(), and read.
Referenced by GetStartupData(), and HandleMessage().
RegisterDNS()
static DWORD WINAPI RegisterDNS (LPVOID unused) static
Definition at line 960 of file interactive.c.
References ExecCommand(), exit_event, get_win_sys_path(), M_ERR, M_SYSERR, MsgToEventLog(), openvpn_swprintf(), rdns_semaphore, and RDNS_TIMEOUT.
Referenced by HandleRegisterDNSMessage().
RemoveListItem()
static LPVOID RemoveListItem (list_item_t ** pfirst, match_fn_t match, LPVOID ctx) static
Definition at line 145 of file interactive.c.
References _list_item::data, match(), and _list_item::next.
Referenced by HandleAddressMessage(), HandleBlockDNSMessage(), HandleDNSConfigMessage(), HandleRouteMessage(), ServiceStartInteractive(), and SetDNSDomain().
ResetOverlapped()
static BOOL ResetOverlapped (LPOVERLAPPED overlapped) static
Definition at line 210 of file interactive.c.
Referenced by ServiceStartInteractive().
ReturnError()
static VOID ReturnError (HANDLE pipe, DWORD error, LPCWSTR func, DWORD count, LPHANDLE events) static
Definition at line 327 of file interactive.c.
References ERROR_OPENVPN_STARTUP, MSG_FLAGS_ERROR, MsgToEventLog(), and WritePipeAsync().
Referenced by GetStartupData(), ReturnLastError(), RunOpenvpn(), and ServiceStartInteractive().
ReturnLastError()
static VOID ReturnLastError (HANDLE pipe, LPCWSTR func) static
Definition at line 370 of file interactive.c.
References exit_event, and ReturnError().
Referenced by GetStartupData(), and RunOpenvpn().
ReturnProcessId()
static VOID ReturnProcessId (HANDLE pipe, DWORD pid, DWORD count, LPHANDLE events) static
Definition at line 312 of file interactive.c.
References msg, openvpn_swprintf(), and WritePipeAsync().
Referenced by RunOpenvpn().
RunOpenvpn()
static DWORD WINAPI RunOpenvpn (LPVOID p) static
Definition at line 1608 of file interactive.c.
References CloseHandleEx(), CloseRingBufferHandles(), STARTUP_DATA::directory, ERROR_OPENVPN_STARTUP, ERROR_STARTUP_DATA, settings_t::exe_path, exit_event, FreeStartupData(), GetStartupData(), HandleMessage(), IO_TIMEOUT, IsAuthorizedUser(), MSG_FLAGS_ERROR, MsgToEventLog(), openvpn_sntprintf(), openvpn_swprintf(), STARTUP_DATA::options, settings_t::ovpn_admin_group, PACKAGE, PeekNamedPipeAsync(), settings_t::priority, ReturnError(), ReturnLastError(), ReturnProcessId(), service_instance, settings, STARTUP_DATA::std_input, Undo(), and ValidateOptions().
Referenced by ServiceStartInteractive().
ServiceCtrlInteractive()
static DWORD WINAPI ServiceCtrlInteractive (DWORD ctrl_code, DWORD event, LPVOID data, LPVOID ctx) static
Definition at line 1939 of file interactive.c.
References exit_event, ReportStatusToSCMgr(), service, and status.
Referenced by ServiceStartInteractive().
ServiceStartInteractive()
VOID WINAPI ServiceStartInteractive (DWORD dwArgc, LPTSTR * lpszArgv)
Definition at line 2108 of file interactive.c.
References AddListItem(), CloseHandleEx(), CmpHandle(), CreateClientPipeInstance(), exit_event, FreeWaitHandles(), GetOpenvpnSettings(), InitOverlapped(), interactive_service, M_SYSERR, MsgToEventLog(), openvpn_service_t::name, rdns_semaphore, RemoveListItem(), ReportStatusToSCMgr(), ResetOverlapped(), ReturnError(), RunOpenvpn(), service, ServiceCtrlInteractive(), settings, status, and UpdateWaitHandles().
Referenced by _tmain(), and ServiceStartInteractiveOwn().
ServiceStartInteractiveOwn()
VOID WINAPI ServiceStartInteractiveOwn (DWORD dwArgc, LPTSTR * lpszArgv)
Definition at line 2100 of file interactive.c.
References ServiceStartInteractive(), and status.
Referenced by _tmain().
SetDNSDomain()
static DWORD SetDNSDomain (const wchar_t * if_name, const char * domain, undo_lists_t * lists) static
Set interface specific DNS domain suffix.
Parameters
if_name name of the the interface
domain a single domain name
lists pointer to the undo lists. If NULL undo lists are not altered. Will delete the currently set value if domain is empty.
Definition at line 1168 of file interactive.c.
References AddListItem(), CmpWString(), ConvertInterfaceNameToIndex(), RemoveListItem(), undo_domain, utf8to16(), and wmic_nicconfig_cmd().
Referenced by HandleDNSConfigMessage(), and Undo().
sockaddr_inet()
static SOCKADDR_INET sockaddr_inet (short family, inet_address_t * addr) static
Definition at line 545 of file interactive.c.
References inet_address_t::ipv4, and inet_address_t::ipv6.
Referenced by HandleAddressMessage(), and HandleRouteMessage().
Undo()
static VOID Undo (undo_lists_t * lists) static
Definition at line 1551 of file interactive.c.
References _undo_type_max, address, block_dns, _list_item::data, delete_block_dns_filters(), DeleteAddress(), DeleteDNS(), DeleteRoute(), block_dns_data_t::engine, block_dns_data_t::index, block_dns_data_t::metric_v4, block_dns_data_t::metric_v6, _list_item::next, route, set_interface_metric(), SetDNSDomain(), undo_dns4, undo_dns6, and undo_domain.
Referenced by RunOpenvpn().
UpdateWaitHandles()
static DWORD UpdateWaitHandles (LPHANDLE * handles_ptr, LPDWORD count, HANDLE io_event, HANDLE exit_event, list_item_t * threads) static
Definition at line 2037 of file interactive.c.
References _list_item::data, exit_event, _list_item::next, and pos().
Referenced by ServiceStartInteractive().
ValidateOptions()
static BOOL ValidateOptions (HANDLE pipe, const WCHAR * workdir, const WCHAR * options, WCHAR * errmsg, DWORD capacity) static
Definition at line 381 of file interactive.c.
References CheckOption(), IsOption(), openvpn_swprintf(), settings_t::ovpn_admin_group, and settings.
Referenced by RunOpenvpn().
wmic_nicconfig_cmd()
static DWORD wmic_nicconfig_cmd (const wchar_t * action, const NET_IFINDEX if_index, const wchar_t * data) static
Run command: wmic nicconfig (InterfaceIndex=$if_index) call $action ($data)
Parameters
if_index "index of interface"
action e.g., "SetDNSDomain"
data data if required for action
a single word for SetDNSDomain, empty or NULL to delete
comma separated values for a list
Definition at line 1099 of file interactive.c.
References ExecCommand(), get_win_sys_path(), and openvpn_sntprintf().
Referenced by SetDNSDomain().
WritePipeAsync()
static DWORD WritePipeAsync (HANDLE pipe, LPVOID data, DWORD size, DWORD count, LPHANDLE events) static
Definition at line 306 of file interactive.c.
References AsyncPipeOp(), and write.
Referenced by HandleMessage(), ReturnError(), and ReturnProcessId().
Variable Documentation
exit_event
HANDLE exit_event = NULL static
Definition at line 57 of file interactive.c.
Referenced by GetStartupData(), RegisterDNS(), ReturnLastError(), RunOpenvpn(), ServiceCtrlInteractive(), ServiceStartInteractive(), and UpdateWaitHandles().
interactive_service
openvpn_service_t interactive_service
Initial value:
= {
    interactive,
    TEXT(PACKAGE_NAME "ServiceInteractive"),
    TEXT(PACKAGE_NAME " Interactive Service"),
    TEXT(SERVICE_DEPENDENCIES),
    SERVICE_AUTO_START
}
Definition at line 64 of file interactive.c.
Referenced by _tmain(), and ServiceStartInteractive().
rdns_semaphore
HANDLE rdns_semaphore = NULL static
Definition at line 59 of file interactive.c.
Referenced by RegisterDNS(), and ServiceStartInteractive().
service
SERVICE_STATUS_HANDLE service static
Definition at line 55 of file interactive.c.
Referenced by ServiceCtrlInteractive(), and ServiceStartInteractive().
settings
settings_t settings static
Definition at line 58 of file interactive.c.
Referenced by HandleBlockDNSMessage(), RunOpenvpn(), ServiceStartAutomatic(), ServiceStartInteractive(), and ValidateOptions().
status
SERVICE_STATUS status = { .dwServiceType = SERVICE_WIN32_SHARE_PROCESS } static
Definition at line 56 of file interactive.c.
Referenced by InterfaceLuid(), ServiceCtrlInteractive(), ServiceStartInteractive(), and ServiceStartInteractiveOwn().