OpenVPN: src/openvpn/interval.c File Reference
interval.c File Reference
#include "syshead.h"
#include "interval.h"
#include "memdbg.h"
Functions
void interval_init (struct interval *top, int horizon, int refresh)
bool event_timeout_trigger (struct event_timeout *et, struct timeval *tv, const int et_const_retry)
Function Documentation
event_timeout_trigger()
bool event_timeout_trigger (struct event_timeout * et, struct timeval * tv, const int et_const_retry)
Definition at line 45 of file interval.c.
References D_INTERVAL, event_timeout::defined, dmsg, event_timeout::last, event_timeout::n, and now.
Referenced by check_add_routes(), check_ping_restart(), check_ping_send(), check_send_occ_load_test(), check_send_occ_req(), process_coarse_timers(), process_explicit_exit_notification_timer_wakeup(), stale_route_check_trigger(), and status_trigger().
interval_init()
void interval_init (struct interval * top, int horizon, int refresh)
Definition at line 37 of file interval.c.
References CLEAR, interval::horizon, and interval::refresh.
Referenced by do_init_timers().