OpenVPN: src/openvpn/integer.h File Reference
integer.h File Reference
#include "error.h"
Macros
#define htonll(x)
#define ntohll(x)
Functions
static int max_int (int x, int y)
static int min_int (int x, int y)
static int constrain_int (int x, int min, int max)
static int modulo_subtract (int x, int y, int mod)
static int modulo_add (int x, int y, int mod)
static size_t adjust_power_of_2 (size_t u)
static int index_verify (int index, int size, const char *file, int line)
Macro Definition Documentation
htonll
#define htonll (x)
Value:
                   ((1==htonl(1)) ? (x) : \
                   ((uint64_t)htonl((x) & 0xFFFFFFFF) << 32) | htonl((x) >> 32))
Definition at line 30 of file integer.h.
ntohll
#define ntohll (x)
Value:
                   ((1==ntohl(1)) ? (x) : \
                   ((uint64_t)ntohl((x) & 0xFFFFFFFF) << 32) | ntohl((x) >> 32))
Definition at line 35 of file integer.h.
Function Documentation
adjust_power_of_2()
static size_t adjust_power_of_2 (size_t u) inline static
Definition at line 136 of file integer.h.
References ASSERT.
Referenced by argv_grow(), hash_init(), and mbuf_init().
constrain_int()
static int constrain_int (int x, int min, int max) inline static
Definition at line 70 of file integer.h.
Referenced by convert_tls_list_to_openssl(), frame_set_mtu_dynamic(), reap_buckets_per_pass(), set_debug_level(), and tv_subtract().
index_verify()
static int index_verify (int index, int size, const char * file, int line) inline static
Definition at line 150 of file integer.h.
References M_FATAL, and msg.
max_int()
static int max_int (int x, int y) inline static
Definition at line 44 of file integer.h.
Referenced by add_option(), crypto_max_overhead(), do_init_crypto_tls(), get_server_poll_remaining_time(), io_wait_dowork(), multi_tcp_init(), process_incoming_link_part2(), process_outgoing_link(), socket_restart_pause(), tv_to_ms_timeout(), and verify_cert().
min_int()
static int min_int (int x, int y) inline static
Definition at line 57 of file integer.h.
Referenced by check_send_occ_msg_dowork(), ipv6_send_icmp_unreachable(), man_write(), multi_tcp_init(), optimal_fragment_size(), prng_bytes(), reliable_send_timeout(), socket_restart_pause(), tls_init_control_channel_frame_parameters(), and we_init().
modulo_add()
static int modulo_add (int x, int y, int mod) inline static
Definition at line 116 of file integer.h.
References ASSERT.
Referenced by fragment_list_get_buf(), fragment_outgoing(), and log_index().
modulo_subtract()
static int modulo_subtract (int x, int y, int mod) inline static
Definition at line 101 of file integer.h.
References ASSERT.
Referenced by fragment_list_get_buf().