OpenVPN: tests/unit_tests/engine-key/libtestengine.c File Reference
libtestengine.c File Reference
#include <string.h>
#include <openssl/engine.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
Functions
static int engine_init (ENGINE *e)
static int engine_finish (ENGINE *e)
static EVP_PKEY * engine_load_key (ENGINE *e, const char *key_id, UI_METHOD *ui_method, void *cb_data)
static int engine_bind_fn (ENGINE *e, const char *id)
Variables
static char * engine_id = "testengine"
static char * engine_name = "Engine for testing openvpn engine key support"
static int is_initialized = 0
Function Documentation
engine_bind_fn()
static int engine_bind_fn (ENGINE * e, const char * id) static
Definition at line 98 of file libtestengine.c.
References engine_finish(), engine_id, engine_init(), engine_load_key(), and engine_name.
engine_finish()
static int engine_finish (ENGINE * e) static
Definition at line 20 of file libtestengine.c.
References is_initialized.
Referenced by engine_bind_fn().
engine_init()
static int engine_init (ENGINE * e) static
Definition at line 12 of file libtestengine.c.
References is_initialized.
Referenced by engine_bind_fn().
engine_load_key()
static EVP_PKEY* engine_load_key (ENGINE * e, const char * key_id, UI_METHOD * ui_method, void * cb_data) static
Definition at line 28 of file libtestengine.c.
References is_initialized.
Referenced by engine_bind_fn().
Variable Documentation
engine_id
char* engine_id = "testengine" static
Definition at line 6 of file libtestengine.c.
Referenced by engine_bind_fn().
engine_name
char* engine_name = "Engine for testing openvpn engine key support" static
Definition at line 7 of file libtestengine.c.
Referenced by crypto_init_lib_engine(), and engine_bind_fn().
is_initialized
int is_initialized = 0 static
Definition at line 9 of file libtestengine.c.
Referenced by engine_finish(), engine_init(), and engine_load_key().