OpenVPN: src/openvpn/lladdr.c File Reference
lladdr.c File Reference
#include "syshead.h"
#include "error.h"
#include "misc.h"
#include "run_command.h"
#include "lladdr.h"
#include "proto.h"
Functions
int set_lladdr (openvpn_net_ctx_t *ctx, const char *ifname, const char *lladdr, const struct env_set *es)
Function Documentation
set_lladdr()
int set_lladdr (openvpn_net_ctx_t * ctx, const char * ifname, const char * lladdr, const struct env_set * es)
Definition at line 19 of file lladdr.c.
References argv_free(), argv_msg(), argv_new(), argv_printf(), IFCONFIG_PATH, M_INFO, M_WARN, MAC_FMT, MAC_SCAN_ARG, msg, OPENVPN_ETH_ALEN, and openvpn_execve_check().
Referenced by do_open_tun(), and do_persist_tuntap().