OpenVPN: sample/sample-plugins/log/log_v3.c File Reference
log_v3.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "openvpn-plugin.h"
Data Structures
struct plugin_context
Functions
static const char * get_env (const char *name, const char *envp[])
OPENVPN_EXPORT int openvpn_plugin_open_v3 (const int v3structver, struct openvpn_plugin_args_open_in const *args, struct openvpn_plugin_args_open_return *ret)
void show (const int type, const char *argv[], const char *envp[])
static void x509_print_info (X509 *x509crt)
OPENVPN_EXPORT int openvpn_plugin_func_v3 (const int version, struct openvpn_plugin_args_func_in const *args, struct openvpn_plugin_args_func_return *retptr)
OPENVPN_EXPORT void openvpn_plugin_close_v1 (openvpn_plugin_handle_t handle)
Function Documentation
get_env()
static const char* get_env (const char * name, const char * envp[]) static
Definition at line 54 of file log_v3.c.
Referenced by openvpn_plugin_func_v3().
openvpn_plugin_close_v1()
OPENVPN_EXPORT void openvpn_plugin_close_v1 (openvpn_plugin_handle_t handle)
Definition at line 292 of file log_v3.c.
openvpn_plugin_func_v3()
OPENVPN_EXPORT int openvpn_plugin_func_v3 (const int version, struct openvpn_plugin_args_func_in const * args, struct openvpn_plugin_args_func_return * retptr)
Definition at line 250 of file log_v3.c.
References openvpn_plugin_args_func_in::argv, openvpn_plugin_args_func_in::current_cert, openvpn_plugin_args_func_in::current_cert_depth, openvpn_plugin_args_func_in::envp, get_env(), openvpn_plugin_args_func_in::handle, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_FUNC_SUCCESS, OPENVPN_PLUGIN_TLS_VERIFY, plugin_context::password, show(), openvpn_plugin_args_func_in::type, plugin_context::username, and x509_print_info().
openvpn_plugin_open_v3()
OPENVPN_EXPORT int openvpn_plugin_open_v3 (const int v3structver, struct openvpn_plugin_args_open_in const * args, struct openvpn_plugin_args_open_return * ret)
Definition at line 76 of file log_v3.c.
References openvpn_plugin_args_open_return::handle, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_CLIENT_CONNECT_V2, OPENVPN_PLUGIN_CLIENT_DISCONNECT, OPENVPN_PLUGIN_DOWN, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_FUNC_SUCCESS, OPENVPN_PLUGIN_IPCHANGE, OPENVPN_PLUGIN_LEARN_ADDRESS, OPENVPN_PLUGIN_MASK, OPENVPN_PLUGIN_ROUTE_UP, OPENVPN_PLUGIN_TLS_FINAL, OPENVPN_PLUGIN_TLS_VERIFY, OPENVPN_PLUGIN_UP, OPENVPN_PLUGINv3_STRUCTVER, openvpn_plugin_args_open_in::ovpn_version, openvpn_plugin_args_open_in::ovpn_version_major, openvpn_plugin_args_open_in::ovpn_version_minor, openvpn_plugin_args_open_in::ovpn_version_patch, openvpn_plugin_args_open_in::ssl_api, SSLAPI_OPENSSL, and openvpn_plugin_args_open_return::type_mask.
show()
void show (const int type, const char * argv[], const char * envp[])
Definition at line 133 of file log_v3.c.
References OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_CLIENT_CONNECT_V2, OPENVPN_PLUGIN_CLIENT_DISCONNECT, OPENVPN_PLUGIN_DOWN, OPENVPN_PLUGIN_IPCHANGE, OPENVPN_PLUGIN_LEARN_ADDRESS, OPENVPN_PLUGIN_ROUTE_UP, OPENVPN_PLUGIN_TLS_FINAL, OPENVPN_PLUGIN_TLS_VERIFY, and OPENVPN_PLUGIN_UP.
Referenced by openvpn_plugin_func_v3().
x509_print_info()
static void x509_print_info (X509 * x509crt) static
Definition at line 197 of file log_v3.c.
Referenced by openvpn_plugin_func_v3().