OpenVPN: src/tapctl/main.c File Reference
main.c File Reference
#include "tap.h"
#include "error.h"
#include <objbase.h>
#include <setupapi.h>
#include <stdio.h>
#include <tchar.h>
Functions
static void usage (void)
Print the help message.
int __cdecl _tmain (int argc, LPCTSTR argv[])
Program entry point.
bool dont_mute (unsigned int flags)
Check muting filter.
void x_msg_va (const unsigned int flags, const char *format, va_list arglist)
Variables
const TCHAR title_string []
static const TCHAR usage_message [] =
static const TCHAR usage_message_create [] =
static const TCHAR usage_message_list [] =
static const TCHAR usage_message_delete [] =
Function Documentation
_tmain()
int __cdecl _tmain (int argc, LPCTSTR argv[])
Program entry point.
Definition at line 138 of file main.c.
References tap_adapter_node::pNext, PRIsLPOLESTR, PRIsLPTSTR, tap_adapter_node::szName, tap_create_adapter(), tap_delete_adapter(), tap_free_adapter_list(), tap_list_adapters(), tap_set_adapter_name(), TAP_WIN_COMPONENT_ID, title_string, usage(), usage_message_create, usage_message_delete, and usage_message_list.
dont_mute()
bool dont_mute (unsigned int flags)
Check muting filter.
Definition at line 388 of file main.c.
usage()
static void usage (void) static
Print the help message.
Definition at line 126 of file main.c.
References title_string, and usage_message.
Referenced by _tmain().
x_msg_va()
void x_msg_va (const unsigned int flags, const char * format, va_list arglist)
Definition at line 397 of file main.c.
References M_ERRNO.
Variable Documentation
title_string
const TCHAR title_string[]
Initial value:
=
    TEXT(PACKAGE_NAME) TEXT(" ") TEXT(PACKAGE_VERSION)
    TEXT(" built on ") TEXT(__DATE__)
Definition at line 45 of file main.c.
Referenced by _tmain(), and usage().
usage_message
const TCHAR usage_message[] = static
Definition at line 50 of file main.c.
Referenced by usage().
usage_message_create
const TCHAR usage_message_create[] = static
Definition at line 67 of file main.c.
Referenced by _tmain().
usage_message_delete
const TCHAR usage_message_delete[] = static
Definition at line 111 of file main.c.
Referenced by _tmain().
usage_message_list
const TCHAR usage_message_list[] = static
Definition at line 92 of file main.c.
Referenced by _tmain().