OpenVPN: src/openvpn/manage.c File Reference
manage.c File Reference
#include "syshead.h"
#include "error.h"
#include "fdmisc.h"
#include "options.h"
#include "sig.h"
#include "event.h"
#include "otime.h"
#include "integer.h"
#include "misc.h"
#include "ssl.h"
#include "common.h"
#include "manage.h"
#include "memdbg.h"
Macros
#define MANAGEMENT_ECHO_PULL_INFO 0
#define MANAGEMENT_ECHO_FLAGS 0
#define AF_DID_PUSH (1<<0)
#define AF_DID_RESET (1<<1)
#define IER_RESET 0
#define IER_NEW 1
#define MN_AT_LEAST (1<<0)
#define MWCC_PASSWORD_WAIT (1<<0)
#define MWCC_HOLD_WAIT (1<<1)
#define MWCC_OTHER_WAIT (1<<2)
Functions
static void man_output_standalone (struct management *man, volatile int *signal_received)
static void man_reset_client_socket (struct management *man, const bool exiting)
static void man_help (void)
static const char * man_state_name (const int state)
static void man_welcome (struct management *man)
static bool man_password_needed (struct management *man)
static void man_check_password (struct management *man, const char *line)
static void man_update_io_state (struct management *man)
static void man_output_list_push_finalize (struct management *man)
static void man_output_list_push_str (struct management *man, const char *str)
static void man_output_list_push (struct management *man, const char *str)
static void man_prompt (struct management *man)
static void man_delete_unix_socket (struct management *man)
static void man_close_socket (struct management *man, const socket_descriptor_t sd)
static void virtual_output_callback_func (void *arg, const unsigned int flags, const char *str)
static int man_mod_signal (const struct management *man, const int signum)
static void man_signal (struct management *man, const char *name)
static void man_status (struct management *man, const int version, struct status_output *so)
static void man_bytecount (struct management *man, const int update_seconds)
void man_bytecount_output_client (struct management *man)
static void man_kill (struct management *man, const char *victim)
static void man_history (struct management *man, const char *parm, const char *type, struct log_history *log, bool *realtime, const unsigned int lep_flags)
static void man_log (struct management *man, const char *parm)
static void man_echo (struct management *man, const char *parm)
static void man_state (struct management *man, const char *parm)
static void man_up_finalize (struct management *man)
static void man_query_user_pass (struct management *man, const char *type, const char *string, const bool needed, const char *prompt, char *dest, int len)
static void man_query_username (struct management *man, const char *type, const char *string)
static void man_query_password (struct management *man, const char *type, const char *string)
static void man_query_need_ok (struct management *man, const char *type, const char *action)
static void man_query_need_str (struct management *man, const char *type, const char *action)
static void man_forget_passwords (struct management *man)
static void man_net (struct management *man)
static void man_send_cc_message (struct management *man, const char *message, const char *parameters)
static void man_hold (struct management *man, const char *cmd)
static void in_extra_reset (struct man_connection *mc, const int mode)
static void in_extra_dispatch (struct management *man)
static void man_pk_sig (struct management *man, const char *cmd_name)
static void man_certificate (struct management *man)
static void man_load_stats (struct management *man)
static bool man_need (struct management *man, const char **p, const int n, unsigned int flags)
Checks if the correct number of arguments to a management command are present and otherwise prints an error and returns false.
static void man_proxy (struct management *man, const char **p)
static void man_remote (struct management *man, const char **p)
static void set_client_version (struct management *man, const char *version)
static void man_dispatch_command (struct management *man, struct status_output *so, const char **p, const int nparms)
static void man_start_ne32 (struct management *man)
static void man_stop_ne32 (struct management *man)
static void man_record_peer_info (struct management *man)
static void man_connection_settings_reset (struct management *man)
static void man_new_connection_post (struct management *man, const char *description)
static void man_accept (struct management *man)
static void man_listen (struct management *man)
static void man_connect (struct management *man)
static void man_process_command (struct management *man, const char *line)
static bool man_io_error (struct management *man, const char *prefix)
static int man_read (struct management *man)
static int man_write (struct management *man)
static void man_connection_clear (struct man_connection *mc)
static void man_persist_init (struct management *man, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size)
static void man_persist_close (struct man_persist *mp)
static void man_settings_init (struct man_settings *ms, const char *addr, const char *port, const char *pass_file, const char *client_user, const char *client_group, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size, const char *write_peer_info_file, const int remap_sigusr1, const unsigned int flags)
static void man_settings_close (struct man_settings *ms)
static void man_connection_init (struct management *man)
static void man_connection_close (struct management *man)
struct management * management_init (void)
bool management_open (struct management *man, const char *addr, const char *port, const char *pass_file, const char *client_user, const char *client_group, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size, const char *write_peer_info_file, const int remap_sigusr1, const unsigned int flags)
void management_close (struct management *man)
void management_set_callback (struct management *man, const struct management_callback *cb)
void management_clear_callback (struct management *man)
void management_set_state (struct management *man, const int state, const char *detail, const in_addr_t *tun_local_ip, const struct in6_addr *tun_local_ip6, const struct openvpn_sockaddr *local, const struct openvpn_sockaddr *remote)
static bool env_filter_match (const char *env_str, const int env_filter_level)
static void man_output_env (const struct env_set *es, const bool tail, const int env_filter_level, const char *prefix)
static void man_output_extra_env (struct management *man, const char *prefix)
void management_up_down (struct management *man, const char *updown, const struct env_set *es)
void management_notify (struct management *man, const char *severity, const char *type, const char *text)
void management_notify_generic (struct management *man, const char *str)
void management_echo (struct management *man, const char *string, const bool pull)
void management_post_tunnel_open (struct management *man, const in_addr_t tun_local_ip)
void management_pre_tunnel_close (struct management *man)
void management_auth_failure (struct management *man, const char *type, const char *reason)
void management_auth_token (struct management *man, const char *token)
static bool man_persist_state (unsigned int *persistent, const int n)
void management_socket_set (struct management *man, struct event_set *es, void *arg, unsigned int *persistent)
void management_io (struct management *man)
static bool man_standalone_ok (const struct management *man)
static bool man_check_for_signals (volatile int *signal_received)
static int man_block (struct management *man, volatile int *signal_received, const time_t expire)
static int man_standalone_event_loop (struct management *man, volatile int *signal_received, const time_t expire)
static void man_wait_for_client_connection (struct management *man, volatile int *signal_received, const time_t expire, unsigned int flags)
void management_event_loop_n_seconds (struct management *man, int sec)
bool management_query_user_pass (struct management *man, struct user_pass *up, const char *type, const unsigned int flags, const char *static_challenge)
static int management_query_multiline (struct management *man, const char *b64_data, const char *prompt, const char *cmd, int *state, struct buffer_list **input)
static char * management_query_multiline_flatten_newline (struct management *man, const char *b64_data, const char *prompt, const char *cmd, int *state, struct buffer_list **input)
static char * management_query_multiline_flatten (struct management *man, const char *b64_data, const char *prompt, const char *cmd, int *state, struct buffer_list **input)
char * management_query_pk_sig (struct management *man, const char *b64_data, const char *algorithm)
char * management_query_cert (struct management *man, const char *cert_name)
bool management_would_hold (struct management *man)
bool management_should_daemonize (struct management *man)
bool management_hold (struct management *man, int holdtime)
struct command_line * command_line_new (const int buf_len)
void command_line_reset (struct command_line *cl)
void command_line_free (struct command_line *cl)
void command_line_add (struct command_line *cl, const unsigned char *buf, const int len)
const char * command_line_get (struct command_line *cl)
void command_line_next (struct command_line *cl)
const char * log_entry_print (const struct log_entry *e, unsigned int flags, struct gc_arena *gc)
static void log_entry_free_contents (struct log_entry *e)
static int log_index (const struct log_history *h, int i)
static void log_history_obj_init (struct log_history *h, int capacity)
struct log_history * log_history_init (const int capacity)
static void log_history_free_contents (struct log_history *h)
void log_history_close (struct log_history *h)
void log_history_add (struct log_history *h, const struct log_entry *le)
void log_history_resize (struct log_history *h, const int capacity)
const struct log_entry * log_history_ref (const struct log_history *h, const int index)
void management_sleep (const int n)
A sleep function that services the management layer for n seconds rather than doing nothing.
Variables
static const char blank_up [] = "[[BLANK]]"
struct management * management
Macro Definition Documentation
AF_DID_PUSH
#define AF_DID_PUSH (1<<0)
AF_DID_RESET
#define AF_DID_RESET (1<<1)
IER_NEW
#define IER_NEW 1
Definition at line 876 of file manage.c.
IER_RESET
#define IER_RESET 0
Definition at line 875 of file manage.c.
MANAGEMENT_ECHO_FLAGS
#define MANAGEMENT_ECHO_FLAGS 0
Definition at line 57 of file manage.c.
MANAGEMENT_ECHO_PULL_INFO
#define MANAGEMENT_ECHO_PULL_INFO 0
Definition at line 52 of file manage.c.
MN_AT_LEAST
#define MN_AT_LEAST (1<<0)
Definition at line 1210 of file manage.c.
MWCC_HOLD_WAIT
#define MWCC_HOLD_WAIT (1<<1)
Definition at line 3404 of file manage.c.
MWCC_OTHER_WAIT
#define MWCC_OTHER_WAIT (1<<2)
Definition at line 3405 of file manage.c.
MWCC_PASSWORD_WAIT
#define MWCC_PASSWORD_WAIT (1<<0)
Definition at line 3403 of file manage.c.
Function Documentation
command_line_add()
void command_line_add (struct command_line * cl, const unsigned char * buf, const int len)
Definition at line 3907 of file manage.c.
References command_line::buf, buf_clear(), buf_write_u8(), CC_NEWLINE, CC_PRINT, and char_class().
Referenced by man_read().
command_line_free()
void command_line_free (struct command_line * cl)
Definition at line 3898 of file manage.c.
References command_line::buf, command_line_reset(), free_buf(), and command_line::residual.
Referenced by man_connection_close().
command_line_get()
const char* command_line_get (struct command_line * cl)
Definition at line 3923 of file manage.c.
References BSTR, command_line::buf, buf_chomp(), buf_copy_excess(), buf_substring_len(), and command_line::residual.
Referenced by man_read().
command_line_new()
struct command_line* command_line_new (const int buf_len)
Definition at line 3881 of file manage.c.
References alloc_buf(), ALLOC_OBJ_CLEAR, command_line::buf, buf_len(), and command_line::residual.
Referenced by man_connection_init().
command_line_next()
void command_line_next (struct command_line * cl)
Definition at line 3939 of file manage.c.
References command_line::buf, buf_clear(), buf_copy(), and command_line::residual.
Referenced by man_read().
command_line_reset()
void command_line_reset (struct command_line * cl)
Definition at line 3891 of file manage.c.
References command_line::buf, buf_clear(), and command_line::residual.
Referenced by command_line_free(), and man_reset_client_socket().
env_filter_match()
static bool env_filter_match (const char * env_str, const int env_filter_level) static
Definition at line 2810 of file manage.c.
References SIZE.
Referenced by man_output_env().
in_extra_dispatch()
static void in_extra_dispatch (struct management * man) static
Definition at line 904 of file manage.c.
References management_callback::arg, buffer_list_free(), man_persist::callback, management::connection, EKS_READY, man_connection::ext_cert_input, man_connection::ext_cert_state, man_connection::ext_key_input, man_connection::ext_key_state, IEC_CERTIFICATE, IEC_CLIENT_AUTH, IEC_CLIENT_PF, IEC_PK_SIGN, IER_RESET, man_connection::in_extra, man_connection::in_extra_cmd, in_extra_reset(), M_CLIENT, msg, management::persist, and status.
Referenced by man_read().
in_extra_reset()
static void in_extra_reset (struct man_connection * mc, const int mode) static
Definition at line 879 of file manage.c.
References buffer_list_free(), buffer_list_new(), IEC_UNDEF, IER_NEW, man_connection::in_extra, and man_connection::in_extra_cmd.
Referenced by in_extra_dispatch(), man_certificate(), man_connection_close(), man_pk_sig(), man_process_command(), man_reset_client_socket(), and management_query_multiline().
log_entry_free_contents()
static void log_entry_free_contents (struct log_entry * e) static
Definition at line 4017 of file manage.c.
References CLEAR, and log_entry::string.
Referenced by log_history_add(), and log_history_free_contents().
log_entry_print()
const char* log_entry_print (const struct log_entry * e, unsigned int flags, struct gc_arena * gc)
Definition at line 3951 of file manage.c.
References openvpn_sockaddr::addr, addr_defined(), alloc_buf_gc(), BSTR, buf_printf(), D_MANAGEMENT, ERR_BUF_SIZE, IA_EMPTY_IF_UNDEF, log_entry_union::intval, log_entry::local_ip, log_entry::local_ip6, log_entry::local_sock, LOG_ECHO_TO_LOG, LOG_FATAL_NOTIFY, LOG_PRINT_CRLF, LOG_PRINT_ECHO_PREFIX, LOG_PRINT_INT_DATE, LOG_PRINT_INTVAL, LOG_PRINT_LOCAL_IP, LOG_PRINT_LOG_PREFIX, LOG_PRINT_MSG_FLAGS, LOG_PRINT_REMOTE_IP, LOG_PRINT_STATE, LOG_PRINT_STATE_PREFIX, man_state_name(), msg, log_entry_union::msg_flags, msg_flags_string(), print_in6_addr(), print_in_addr_t(), print_sockaddr_ex(), PS_DONT_SHOW_FAMILY, PS_SHOW_PORT, log_entry::remote_sock, openvpn_sockaddr::sa, log_entry_union::state, log_entry::string, log_entry::timestamp, and log_entry::u.
Referenced by man_history(), management_echo(), management_set_state(), and virtual_output_callback_func().
log_history_add()
void log_history_add (struct log_history * h, const struct log_entry * le)
Definition at line 4073 of file manage.c.
References log_history::array, ASSERT, log_history::base, log_history::capacity, log_entry_free_contents(), log_index(), log_history::size, log_entry::string, and string_alloc().
Referenced by log_history_resize(), management_echo(), management_set_state(), and virtual_output_callback_func().
log_history_close()
void log_history_close (struct log_history * h)
Definition at line 4066 of file manage.c.
References log_history_free_contents().
Referenced by man_persist_close().
log_history_free_contents()
static void log_history_free_contents (struct log_history * h) static
Definition at line 4055 of file manage.c.
References log_history::array, log_entry_free_contents(), log_index(), and log_history::size.
Referenced by log_history_close(), and log_history_resize().
log_history_init()
struct log_history* log_history_init (const int capacity)
Definition at line 4045 of file manage.c.
References ALLOC_OBJ, ASSERT, log_history::capacity, and log_history_obj_init().
Referenced by man_persist_init().
log_history_obj_init()
static void log_history_obj_init (struct log_history * h, int capacity) static
Definition at line 4037 of file manage.c.
References ALLOC_ARRAY_CLEAR, log_history::array, buffer::capacity, log_history::capacity, and CLEAR.
Referenced by log_history_init(), and log_history_resize().
log_history_ref()
const struct log_entry* log_history_ref (const struct log_history * h, const int index)
Definition at line 4115 of file manage.c.
References log_history::array, log_index(), and log_history::size.
Referenced by man_history().
log_history_resize()
void log_history_resize (struct log_history * h, const int capacity)
Definition at line 4094 of file manage.c.
References log_history::array, ASSERT, log_history::capacity, log_history_add(), log_history_free_contents(), log_history_obj_init(), log_index(), and log_history::size.
Referenced by management_open().
log_index()
static int log_index (const struct log_history * h, int i) inline static
Definition at line 4031 of file manage.c.
References log_history::base, log_history::capacity, and modulo_add().
Referenced by log_history_add(), log_history_free_contents(), log_history_ref(), and log_history_resize().
man_accept()
static void man_accept (struct management * man) static
Definition at line 1821 of file manage.c.
References CLEAR, management::connection, link_socket_actual::dest, man_settings::flags, man_new_connection_post(), man_stop_ne32(), MF_UNIX_SOCK, man_connection::remote, man_connection::sd_cli, sd_close(), man_connection::sd_top, management::settings, socket_defined(), and socket_do_accept().
Referenced by management_io().
man_block()
static int man_block (struct management * man, volatile int * signal_received, const time_t expire) static
Definition at line 3307 of file manage.c.
References management::connection, man_connection::es, event_reset(), event_wait(), man_check_for_signals(), man_standalone_ok(), management_socket_set(), now, SIGINT, status, and update_time().
Referenced by man_output_standalone(), and man_standalone_event_loop().
man_bytecount()
static void man_bytecount (struct management * man, const int update_seconds) static
Definition at line 463 of file manage.c.
References man_connection::bytecount_update_seconds, management::connection, M_CLIENT, and msg.
Referenced by man_dispatch_command().
man_bytecount_output_client()
void man_bytecount_output_client (struct management * man)
Definition at line 477 of file manage.c.
References man_connection::bytecount_last_update, man_persist::bytes_in, man_persist::bytes_out, management::connection, counter_format, M_CLIENT, msg, now, openvpn_snprintf(), and management::persist.
Referenced by man_bytecount_possible_output_client().
man_certificate()
static void man_certificate (struct management * man) static
Definition at line 1178 of file manage.c.
References management::connection, EKS_INPUT, EKS_SOLICIT, man_connection::ext_cert_state, IEC_CERTIFICATE, IER_NEW, man_connection::in_extra_cmd, in_extra_reset(), M_CLIENT, and msg.
Referenced by man_dispatch_command().
man_check_for_signals()
static bool man_check_for_signals (volatile int * signal_received) static
Definition at line 3290 of file manage.c.
References get_signal().
Referenced by man_block(), management_event_loop_n_seconds(), management_hold(), management_query_multiline(), and management_query_user_pass().
man_check_password()
static void man_check_password (struct management * man, const char * line) static
Definition at line 197 of file manage.c.
References management::connection, man_connection::halt, M_CLIENT, M_WARN, man_password_needed(), man_welcome(), MANAGEMENT_N_PASSWORD_RETRIES, msg, user_pass::password, man_connection::password_tries, man_connection::password_verified, management::settings, streq, and man_settings::up.
Referenced by man_process_command().
man_close_socket()
static void man_close_socket (struct management * man, const socket_descriptor_t sd) static
Definition at line 294 of file manage.c.
References management_callback::arg, man_persist::callback, management_callback::delete_event, openvpn_close_socket, and management::persist.
Referenced by man_connection_close(), and man_reset_client_socket().
man_connect()
static void man_connect (struct management * man) static
Definition at line 1922 of file manage.c.
References management::connection, create_socket_tcp(), D_LINK_ERRORS, man_settings::flags, gc_free(), gc_new(), man_settings::local, M_ERRNO, man_new_connection_post(), man_record_peer_info(), MF_UNIX_SOCK, MS_INITIAL, msg, openvpn_connect(), print_sockaddr(), man_connection::sd_cli, sd_close(), man_connection::sd_top, management::settings, SIGTERM, SOCKET_UNDEFINED, man_connection::state, status, throw_signal(), and throw_signal_soft().
Referenced by man_connection_init().
man_connection_clear()
static void man_connection_clear (struct man_connection * mc) static
Definition at line 2379 of file manage.c.
References CLEAR, MS_INITIAL, man_connection::sd_cli, man_connection::sd_top, SOCKET_UNDEFINED, and man_connection::state.
Referenced by man_connection_close(), and management_init().
man_connection_close()
static void man_connection_close (struct management * man) static
Definition at line 2617 of file manage.c.
References buffer_list_free(), command_line_free(), management::connection, man_connection::es, event_free(), man_connection::ext_key_input, IER_RESET, man_connection::in, in_extra_reset(), man_close_socket(), man_connection_clear(), man_delete_unix_socket(), man_connection::ne32, net_event_win32_close(), man_connection::out, man_connection::sd_cli, man_connection::sd_top, and socket_defined().
Referenced by management_close(), and management_pre_tunnel_close().
man_connection_init()
static void man_connection_init (struct management * man) static
Definition at line 2572 of file manage.c.
References buffer_list_new(), man_connection::client_version, command_line_new(), management::connection, man_connection::es, EVENT_METHOD_FAST, event_set_init(), man_settings::flags, man_connection::in, man_connect(), man_listen(), MF_CONNECT_AS_CLIENT, MS_INITIAL, man_connection::ne32, net_event_win32_init(), man_connection::out, management::settings, and man_connection::state.
Referenced by management_open(), and management_post_tunnel_open().
man_connection_settings_reset()
static void man_connection_settings_reset (struct management * man) static
Definition at line 1737 of file manage.c.
References man_connection::bytecount_update_seconds, management::connection, man_connection::echo_realtime, man_connection::halt, man_connection::log_realtime, MS_CC_WAIT_WRITE, man_connection::password_tries, man_connection::password_verified, man_connection::state, and man_connection::state_realtime.
Referenced by man_new_connection_post().
man_delete_unix_socket()
static void man_delete_unix_socket (struct management * man) static
Definition at line 283 of file manage.c.
References man_settings::flags, MF_CONNECT_AS_CLIENT, MF_UNIX_SOCK, and management::settings.
Referenced by man_connection_close(), and man_listen().
man_dispatch_command()
static void man_dispatch_command (struct management * man, struct status_output * so, const char ** p, const int nparms) static
Definition at line 1315 of file manage.c.
References ASSERT, auth_retry_print(), auth_retry_set(), management::connection, gc_free(), gc_new(), get_debug_level(), get_mute_cutoff(), man_connection::halt, M_CLIENT, man_bytecount(), man_certificate(), man_echo(), man_forget_passwords(), man_help(), man_hold(), man_kill(), man_load_stats(), man_log(), man_need(), man_net(), man_pk_sig(), man_proxy(), man_query_need_ok(), man_query_need_str(), man_query_password(), man_query_username(), man_remote(), man_send_cc_message(), man_signal(), man_state(), man_status(), MANAGEMENT_VERSION, MN_AT_LEAST, msg, platform_getpid(), set_client_version(), set_debug_level(), set_mute_cutoff(), streq, and title_string.
Referenced by man_process_command().
man_echo()
static void man_echo (struct management * man, const char * parm) static
Definition at line 646 of file manage.c.
References management::connection, man_persist::echo, man_connection::echo_realtime, LOG_PRINT_INT_DATE, man_history(), MANAGEMENT_ECHO_FLAGS, and management::persist.
Referenced by man_dispatch_command().
man_forget_passwords()
static void man_forget_passwords (struct management * man) static
Definition at line 768 of file manage.c.
References M_CLIENT, msg, ssl_clean_auth_token(), and ssl_purge_auth().
Referenced by man_dispatch_command().
man_help()
static void man_help (void) static
Definition at line 71 of file manage.c.
References M_CLIENT, msg, and title_string.
Referenced by man_dispatch_command().
man_history()
static void man_history (struct management * man, const char * parm, const char * type, struct log_history * log, bool * realtime, const unsigned int lep_flags) static
Definition at line 589 of file manage.c.
References gc_free(), gc_new(), log_entry_print(), log_history_ref(), log_history_size(), M_CLIENT, msg, streq, and virtual_output_callback_func().
Referenced by man_echo(), man_log(), and man_state().
man_hold()
static void man_hold (struct management * man, const char * cmd) static
Definition at line 845 of file manage.c.
References BOOL_CAST, man_settings::flags, man_persist::hold_release, M_CLIENT, MF_HOLD, msg, management::persist, management::settings, and streq.
Referenced by man_dispatch_command().
man_io_error()
static bool man_io_error (struct management * man, const char * prefix) static
Definition at line 2087 of file manage.c.
References D_MANAGEMENT, gc_free(), gc_new(), ignore_sys_error(), msg, and openvpn_errno_maybe_crt().
Referenced by man_read(), and man_write().
man_kill()
static void man_kill (struct management * man, const char * victim) static
Definition at line 508 of file manage.c.
References management_callback::arg, buf_parse(), buf_set_read(), man_persist::callback, gc_free(), gc_new(), getaddr(), GETADDR_HOST_ORDER, GETADDR_MSG_VIRT_OUT, in_addr_t, management_callback::kill_by_addr, management_callback::kill_by_cn, M_CLIENT, msg, management::persist, print_in_addr_t(), and status.
Referenced by man_dispatch_command().
man_listen()
static void man_listen (struct management * man) static
Definition at line 1859 of file manage.c.
References management::connection, create_socket_tcp(), D_MANAGEMENT, man_settings::flags, gc_free(), gc_new(), man_settings::local, M_ERR, man_delete_unix_socket(), man_start_ne32(), MF_UNIX_SOCK, MS_LISTEN, msg, print_sockaddr(), man_connection::sd_cli, man_connection::sd_top, set_nonblock(), management::settings, socket_bind(), SOCKET_UNDEFINED, and man_connection::state.
Referenced by man_connection_init(), and man_reset_client_socket().
man_load_stats()
static void man_load_stats (struct management * man) static
Definition at line 1194 of file manage.c.
References management_callback::arg, man_persist::callback, counter_format, link_read_bytes_global, link_write_bytes_global, M_CLIENT, msg, management_callback::n_clients, and management::persist.
Referenced by man_dispatch_command().
man_log()
static void man_log (struct management * man, const char * parm) static
Definition at line 635 of file manage.c.
References management::connection, man_persist::log, LOG_PRINT_INT_DATE, LOG_PRINT_MSG_FLAGS, man_connection::log_realtime, man_history(), and management::persist.
Referenced by man_dispatch_command().
man_mod_signal()
static int man_mod_signal (const struct management * man, const int signum) static
Definition at line 397 of file manage.c.
References man_settings::mansig, MANSIG_IGNORE_USR1_HUP, MANSIG_MAP_USR1_TO_HUP, MANSIG_MAP_USR1_TO_TERM, management::settings, SIGHUP, SIGTERM, and SIGUSR1.
Referenced by man_reset_client_socket(), and man_signal().
man_need()
static bool man_need (struct management * man, const char ** p, const int n, unsigned int flags) static
Checks if the correct number of arguments to a management command are present and otherwise prints an error and returns false.
Parameters
p pointer to the parameter array
n number of arguments required
flags if MN_AT_LEAST require at least n parameters and not exactly n
Returns
Return whether p has n (or at least n) parameters
Definition at line 1221 of file manage.c.
References ASSERT, M_CLIENT, MN_AT_LEAST, and msg.
Referenced by man_dispatch_command().
man_net()
static void man_net (struct management * man) static
Definition at line 776 of file manage.c.
References management_callback::arg, man_persist::callback, M_CLIENT, msg, management::persist, and management_callback::show_net.
Referenced by man_dispatch_command().
man_new_connection_post()
static void man_new_connection_post (struct management * man, const char * description) static
Definition at line 1750 of file manage.c.
References buffer_list_reset(), management::connection, D_MANAGEMENT, man_settings::flags, gc_free(), gc_new(), man_settings::local, man_connection_settings_reset(), man_password_needed(), man_prompt(), man_start_ne32(), man_update_io_state(), man_welcome(), MF_UNIX_SOCK, msg, man_connection::out, print_sockaddr(), man_connection::sd_cli, set_nonblock(), and management::settings.
Referenced by man_accept(), and man_connect().
man_output_env()
static void man_output_env (const struct env_set * es, const bool tail, const int env_filter_level, const char * prefix) static
Definition at line 2858 of file manage.c.
References env_filter_match(), env_set::list, M_CLIENT, msg, env_item::next, and env_item::string.
Referenced by man_output_extra_env(), and management_up_down().
man_output_extra_env()
static void man_output_extra_env (struct management * man, const char * prefix) static
Definition at line 2878 of file manage.c.
References management_callback::arg, man_persist::callback, management::connection, man_connection::env_filter_level, env_set_create(), env_set::gc, gc_free(), gc_new(), man_output_env(), management_callback::n_clients, management::persist, and setenv_int().
man_output_list_push()
static void man_output_list_push (struct management * man, const char * str) static
Definition at line 261 of file manage.c.
References man_output_list_push_finalize(), and man_output_list_push_str().
Referenced by man_prompt(), management_echo(), and management_set_state().
man_output_list_push_finalize()
static void man_output_list_push_finalize (struct management * man) static
Definition at line 238 of file manage.c.
References man_output_standalone(), man_update_io_state(), management_connected(), management::persist, and man_persist::standalone_disabled.
Referenced by man_output_list_push(), management_clear_callback(), management_close(), and virtual_output_callback_func().
man_output_list_push_str()
static void man_output_list_push_str (struct management * man, const char * str) static
Definition at line 252 of file manage.c.
References buffer_list_push(), management::connection, management_connected(), and man_connection::out.
Referenced by man_output_list_push(), and virtual_output_callback_func().
man_output_standalone()
static void man_output_standalone (struct management * man, volatile int * signal_received) static
Definition at line 3366 of file manage.c.
References management::connection, man_block(), man_standalone_ok(), management_io(), MS_CC_WAIT_WRITE, and man_connection::state.
Referenced by man_output_list_push_finalize().
man_password_needed()
static bool man_password_needed (struct management * man) inline static
Definition at line 191 of file manage.c.
References management::connection, user_pass::defined, man_connection::password_verified, management::settings, and man_settings::up.
Referenced by man_check_password(), man_new_connection_post(), man_process_command(), man_prompt(), man_wait_for_client_connection(), and virtual_output_callback_func().
man_persist_close()
static void man_persist_close (struct man_persist * mp) static
Definition at line 2430 of file manage.c.
References CLEAR, man_persist::echo, man_persist::log, log_history_close(), msg_set_virtual_output(), and man_persist::state.
Referenced by management_close().
man_persist_init()
static void man_persist_init (struct management * man, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size) static
Definition at line 2392 of file manage.c.
References virtual_output::arg, CLEAR, man_persist::defined, man_persist::echo, virtual_output::flags_default, virtual_output::func, man_persist::log, log_history_init(), M_CLIENT, msg_set_virtual_output(), management::persist, man_persist::state, virtual_output_callback_func(), and man_persist::vout.
Referenced by management_init().
man_persist_state()
static bool man_persist_state (unsigned int * persistent, const int n) inline static
Definition at line 3115 of file manage.c.
Referenced by management_socket_set().
man_pk_sig()
static void man_pk_sig (struct management * man, const char * cmd_name) static
Definition at line 1162 of file manage.c.
References management::connection, EKS_INPUT, EKS_SOLICIT, man_connection::ext_key_state, IEC_PK_SIGN, IER_NEW, man_connection::in_extra_cmd, in_extra_reset(), M_CLIENT, and msg.
Referenced by man_dispatch_command().
man_process_command()
static void man_process_command (struct management * man, const char * line) static
Definition at line 2037 of file manage.c.
References CLEAR, management::connection, D_MANAGEMENT_DEBUG, gc_free(), gc_new(), IER_RESET, in_extra_reset(), M_CLIENT, M_INFO, man_check_password(), man_dispatch_command(), man_password_needed(), MAX_PARMS, msg, parse_line(), management::persist, status_close(), status_open(), streq, and man_persist::vout.
Referenced by man_read().
man_prompt()
static void man_prompt (struct management * man) static
Definition at line 268 of file manage.c.
References man_output_list_push(), and man_password_needed().
Referenced by man_new_connection_post(), and man_read().
man_proxy()
static void man_proxy (struct management * man, const char ** p) static
Definition at line 1241 of file manage.c.
References management_callback::arg, man_persist::callback, M_CLIENT, msg, management::persist, management_callback::proxy_cmd, and status.
Referenced by man_dispatch_command().
man_query_need_ok()
static void man_query_need_ok (struct management * man, const char * type, const char * action) static
Definition at line 754 of file manage.c.
References management::connection, man_query_user_pass(), user_pass::password, man_connection::up_query, man_connection::up_query_mode, UP_QUERY_NEED_OK, man_connection::up_query_type, and USER_PASS_LEN.
Referenced by man_dispatch_command().
man_query_need_str()
static void man_query_need_str (struct management * man, const char * type, const char * action) static
Definition at line 761 of file manage.c.
References management::connection, man_query_user_pass(), user_pass::password, man_connection::up_query, man_connection::up_query_mode, UP_QUERY_NEED_STR, man_connection::up_query_type, and USER_PASS_LEN.
Referenced by man_dispatch_command().
man_query_password()
static void man_query_password (struct management * man, const char * type, const char * string) static
Definition at line 741 of file manage.c.
References blank_up, management::connection, man_query_user_pass(), user_pass::password, man_connection::up_query, man_connection::up_query_mode, UP_QUERY_PASS, man_connection::up_query_type, UP_QUERY_USER_PASS, and USER_PASS_LEN.
Referenced by man_dispatch_command().
man_query_user_pass()
static void man_query_user_pass (struct management * man, const char * type, const char * string, const bool needed, const char * prompt, char * dest, int len) static
Definition at line 699 of file manage.c.
References ASSERT, management::connection, dest, M_CLIENT, man_up_finalize(), msg, streq, strncpynt(), and man_connection::up_query_type.
Referenced by man_query_need_ok(), man_query_need_str(), man_query_password(), and man_query_username().
man_query_username()
static void man_query_username (struct management * man, const char * type, const char * string) static
Definition at line 733 of file manage.c.
References management::connection, man_query_user_pass(), man_connection::up_query, man_connection::up_query_mode, man_connection::up_query_type, UP_QUERY_USER_PASS, USER_PASS_LEN, and user_pass::username.
Referenced by man_dispatch_command().
man_read()
static int man_read (struct management * man) static
Definition at line 2243 of file manage.c.
References ASSERT, buffer_list_push(), buffer_list_reset(), command_line_add(), command_line_get(), command_line_next(), management::connection, man_connection::halt, man_connection::in, man_connection::in_extra, in_extra_dispatch(), man_io_error(), man_process_command(), man_prompt(), man_reset_client_socket(), man_update_io_state(), MSG_NOSIGNAL, man_connection::out, and man_connection::sd_cli.
Referenced by management_io().
man_record_peer_info()
static void man_record_peer_info (struct management * man) static
Definition at line 1695 of file manage.c.
References CLEAR, management::connection, D_MANAGEMENT, gc_free(), gc_new(), in_addr_t, msg, platform_fopen(), print_in_addr_t(), man_connection::sd_cli, management::settings, SIGTERM, socket_defined(), status, throw_signal_soft(), and man_settings::write_peer_info_file.
Referenced by man_connect().
man_remote()
static void man_remote (struct management * man, const char ** p) static
Definition at line 1262 of file manage.c.
References management_callback::arg, man_persist::callback, M_CLIENT, msg, management::persist, management_callback::remote_cmd, and status.
Referenced by man_dispatch_command().
man_reset_client_socket()
static void man_reset_client_socket (struct management * man, const bool exiting) static
Definition at line 1991 of file manage.c.
References buffer_list_reset(), command_line_reset(), management::connection, D_MANAGEMENT, man_settings::flags, IER_RESET, man_connection::in, in_extra_reset(), man_close_socket(), man_listen(), man_mod_signal(), man_stop_ne32(), MF_CONNECT_AS_CLIENT, MF_FORGET_DISCONNECT, MF_SIGNAL, MS_INITIAL, msg, man_connection::out, man_connection::sd_cli, management::settings, SIGTERM, SIGUSR1, socket_defined(), SOCKET_UNDEFINED, ssl_clean_auth_token(), ssl_purge_auth(), man_connection::state, and throw_signal_soft().
Referenced by man_read(), man_write(), management_io(), and virtual_output_callback_func().
man_send_cc_message()
static void man_send_cc_message (struct management * man, const char * message, const char * parameters) static
Definition at line 789 of file manage.c.
References management_callback::arg, man_persist::callback, M_CLIENT, msg, management::persist, management_callback::send_cc_message, and status.
Referenced by man_dispatch_command().
man_settings_close()
static void man_settings_close (struct man_settings * ms) static
Definition at line 2560 of file manage.c.
References CLEAR, man_settings::local, and man_settings::write_peer_info_file.
Referenced by management_close().
man_settings_init()
static void man_settings_init (struct man_settings * ms, const char * addr, const char * port, const char * pass_file, const char * client_user, const char * client_group, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size, const char * write_peer_info_file, const int remap_sigusr1, const unsigned int flags) static
Definition at line 2452 of file manage.c.
References ASSERT, CLEAR, man_settings::client_gid, man_settings::client_uid, D_MANAGEMENT, man_settings::defined, man_settings::echo_buffer_size, man_settings::flags, get_user_pass(), GET_USER_PASS_PASSWORD_ONLY, GETADDR_FATAL, GETADDR_PASSIVE, GETADDR_RESOLVE, GETADDR_WARN_ON_SIGNAL, man_settings::local, man_settings::log_history_cache, man_settings::management_over_tunnel, man_settings::mansig, MANSIG_MAP_USR1_TO_HUP, MANSIG_MAP_USR1_TO_TERM, MF_CONNECT_AS_CLIENT, MF_UNIX_SOCK, msg, openvpn_getaddrinfo(), platform_group_get(), platform_state_group_gid(), platform_state_user_uid(), platform_user_get(), SIGHUP, SIGTERM, man_settings::state_buffer_size, status, streq, string_alloc(), man_settings::up, and man_settings::write_peer_info_file.
Referenced by management_open().
man_signal()
static void man_signal (struct management * man, const char * name) static
Definition at line 423 of file manage.c.
References M_CLIENT, man_mod_signal(), msg, parse_signal(), management::persist, signal_name(), man_persist::special_state_msg, and throw_signal().
Referenced by man_dispatch_command().
man_standalone_event_loop()
static int man_standalone_event_loop (struct management * man, volatile int * signal_received, const time_t expire) static
Definition at line 3389 of file manage.c.
References man_block(), man_standalone_ok(), management_io(), and status.
Referenced by man_wait_for_client_connection(), management_event_loop_n_seconds(), management_hold(), management_query_multiline(), and management_query_user_pass().
man_standalone_ok()
static bool man_standalone_ok (const struct management * man) inline static
Definition at line 3284 of file manage.c.
References management::connection, man_settings::management_over_tunnel, MS_INITIAL, management::settings, and man_connection::state.
Referenced by man_block(), man_output_standalone(), man_standalone_event_loop(), man_wait_for_client_connection(), management_event_loop_n_seconds(), management_query_multiline(), management_query_user_pass(), and management_would_hold().
man_start_ne32()
static void man_start_ne32 (struct management * man) static
Definition at line 1668 of file manage.c.
References ASSERT, management::connection, MS_CC_WAIT_READ, MS_CC_WAIT_WRITE, MS_LISTEN, man_connection::ne32, net_event_win32_start(), man_connection::sd_cli, man_connection::sd_top, and man_connection::state.
Referenced by man_listen(), and man_new_connection_post().
man_state()
static void man_state (struct management * man, const char * parm) static
Definition at line 657 of file manage.c.
References management::connection, LOG_PRINT_INT_DATE, LOG_PRINT_LOCAL_IP, LOG_PRINT_REMOTE_IP, LOG_PRINT_STATE, man_history(), management::persist, man_persist::state, and man_connection::state_realtime.
Referenced by man_dispatch_command().
man_state_name()
static const char* man_state_name (const int state) static
Definition at line 134 of file manage.c.
References OPENVPN_STATE_ADD_ROUTES, OPENVPN_STATE_ASSIGN_IP, OPENVPN_STATE_AUTH, OPENVPN_STATE_CONNECTED, OPENVPN_STATE_CONNECTING, OPENVPN_STATE_EXITING, OPENVPN_STATE_GET_CONFIG, OPENVPN_STATE_INITIAL, OPENVPN_STATE_RECONNECTING, OPENVPN_STATE_RESOLVE, OPENVPN_STATE_TCP_CONNECT, and OPENVPN_STATE_WAIT.
Referenced by log_entry_print().
man_status()
static void man_status (struct management * man, const int version, struct status_output * so) static
Definition at line 450 of file manage.c.
References management_callback::arg, man_persist::callback, M_CLIENT, msg, management::persist, and management_callback::status.
Referenced by man_dispatch_command().
man_stop_ne32()
static void man_stop_ne32 (struct management * man) static
Definition at line 1687 of file manage.c.
References management::connection, man_connection::ne32, and net_event_win32_stop().
Referenced by man_accept(), and man_reset_client_socket().
man_up_finalize()
static void man_up_finalize (struct management * man) static
Definition at line 669 of file manage.c.
References ASSERT, management::connection, user_pass::defined, user_pass::password, man_connection::up_query, UP_QUERY_DISABLED, man_connection::up_query_mode, UP_QUERY_NEED_OK, UP_QUERY_NEED_STR, UP_QUERY_PASS, UP_QUERY_USER_PASS, and user_pass::username.
Referenced by man_query_user_pass().
man_update_io_state()
static void man_update_io_state (struct management * man) static
Definition at line 222 of file manage.c.
References buffer_list_defined(), management::connection, MS_CC_WAIT_READ, MS_CC_WAIT_WRITE, man_connection::out, man_connection::sd_cli, socket_defined(), and man_connection::state.
Referenced by man_new_connection_post(), man_output_list_push_finalize(), man_read(), and man_write().
man_wait_for_client_connection()
static void man_wait_for_client_connection (struct management * man, volatile int * signal_received, const time_t expire, unsigned int flags) static
Definition at line 3411 of file manage.c.
References ASSERT, management::connection, D_MANAGEMENT, man_password_needed(), man_standalone_event_loop(), man_standalone_ok(), MS_LISTEN, msg, MWCC_HOLD_WAIT, MWCC_OTHER_WAIT, MWCC_PASSWORD_WAIT, and man_connection::state.
Referenced by management_event_loop_n_seconds(), management_hold(), management_query_multiline(), and management_query_user_pass().
man_welcome()
static void man_welcome (struct management * man) static
Definition at line 180 of file manage.c.
References M_CLIENT, MANAGEMENT_VERSION, msg, management::persist, and man_persist::special_state_msg.
Referenced by man_check_password(), and man_new_connection_post().
man_write()
static int man_write (struct management * man) static
Definition at line 2337 of file manage.c.
References BLEN, BPTR, buffer_list_advance(), buffer_list_aggregate(), buffer_list_peek(), management::connection, buffer::len, man_io_error(), man_reset_client_socket(), man_update_io_state(), min_int(), MSG_NOSIGNAL, man_connection::out, and man_connection::sd_cli.
Referenced by management_io().
management_auth_failure()
void management_auth_failure (struct management * man, const char * type, const char * reason)
Definition at line 3096 of file manage.c.
References M_CLIENT, and msg.
Referenced by auth_user_pass_mgmt(), receive_auth_failed(), tls_ctx_load_pkcs12(), and tls_ctx_load_priv_file().
management_auth_token()
void management_auth_token (struct management * man, const char * token)
Definition at line 3109 of file manage.c.
References M_CLIENT, and msg.
Referenced by add_option().
management_clear_callback()
void management_clear_callback (struct management * man)
Definition at line 2742 of file manage.c.
References man_persist::callback, CLEAR, man_persist::hold_release, man_output_list_push_finalize(), management::persist, and man_persist::standalone_disabled.
Referenced by uninit_management_callback().
management_close()
void management_close (struct management * man)
Definition at line 2724 of file manage.c.
References man_connection_close(), man_output_list_push_finalize(), man_persist_close(), man_settings_close(), management::persist, and management::settings.
Referenced by close_management().
management_echo()
void management_echo (struct management * man, const char * string, const bool pull)
Definition at line 3033 of file manage.c.
References BOOL_CAST, CLEAR, management::connection, man_persist::echo, man_connection::echo_realtime, gc_free(), gc_new(), log_entry_union::intval, log_entry_print(), log_history_add(), LOG_PRINT_CRLF, LOG_PRINT_ECHO_PREFIX, LOG_PRINT_INT_DATE, man_output_list_push(), MANAGEMENT_ECHO_FLAGS, now, management::persist, log_entry::string, log_entry::timestamp, log_entry::u, and update_time().
Referenced by add_option().
management_event_loop_n_seconds()
void management_event_loop_n_seconds (struct management * man, int sec)
Definition at line 3446 of file manage.c.
References man_check_for_signals(), man_standalone_event_loop(), man_standalone_ok(), man_wait_for_client_connection(), now, management::persist, sleep, man_persist::standalone_disabled, and update_time().
Referenced by ce_management_query_proxy(), ce_management_query_remote(), and management_sleep().
management_hold()
bool management_hold (struct management * man, int holdtime)
Definition at line 3829 of file manage.c.
References alloc_buf_gc(), BSTR, buf_printf(), gc_free(), gc_new(), man_persist::hold_release, M_CLIENT, man_check_for_signals(), man_standalone_event_loop(), man_wait_for_client_connection(), management_would_hold(), man_settings::mansig, MANSIG_IGNORE_USR1_HUP, msg, MWCC_HOLD_WAIT, management::persist, management::settings, man_persist::special_state_msg, and man_persist::standalone_disabled.
Referenced by do_hold().
management_init()
struct management* management_init (void)
Definition at line 2651 of file manage.c.
References ALLOC_OBJ_CLEAR, management::connection, man_connection_clear(), man_persist_init(), MANAGEMENT_ECHO_BUFFER_SIZE, MANAGEMENT_LOG_HISTORY_INITIAL_SIZE, and MANAGEMENT_STATE_BUFFER_SIZE.
Referenced by init_management().
management_io()
void management_io (struct management * man)
Definition at line 3171 of file manage.c.
References management::connection, man_accept(), man_read(), man_reset_client_socket(), man_write(), MS_CC_WAIT_READ, MS_CC_WAIT_WRITE, MS_INITIAL, MS_LISTEN, man_connection::ne32, net_event_win32_clear_selected_events(), net_event_win32_get_event_mask(), net_event_win32_reset(), man_connection::state, and status.
Referenced by man_output_standalone(), man_standalone_event_loop(), multi_process_io_udp(), multi_tcp_process_io(), and process_io().
management_notify()
void management_notify (struct management * man, const char * severity, const char * type, const char * text)
Definition at line 2902 of file manage.c.
References M_CLIENT, and msg.
Referenced by server_pushed_signal().
management_notify_generic()
void management_notify_generic (struct management * man, const char * str)
Definition at line 2908 of file manage.c.
References M_CLIENT, and msg.
Referenced by ce_management_query_proxy(), ce_management_query_remote(), and server_pushed_info().
management_open()
bool management_open (struct management * man, const char * addr, const char * port, const char * pass_file, const char * client_user, const char * client_group, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size, const char * write_peer_info_file, const int remap_sigusr1, const unsigned int flags)
Definition at line 2667 of file manage.c.
References management::connection, man_persist::echo, man_settings::echo_buffer_size, man_persist::log, man_settings::log_history_cache, log_history_resize(), man_connection_init(), man_settings_init(), man_settings::management_over_tunnel, MS_INITIAL, management::persist, management::settings, man_persist::state, man_connection::state, and man_settings::state_buffer_size.
Referenced by open_management().
management_post_tunnel_open()
void management_post_tunnel_open (struct management * man, const in_addr_t tun_local_ip)
Definition at line 3064 of file manage.c.
References ASSERT, management::connection, GETADDR_PASSIVE, man_settings::local, man_connection_init(), man_settings::management_over_tunnel, MS_INITIAL, openvpn_getaddrinfo(), management::settings, and man_connection::state.
Referenced by initialization_sequence_completed().
management_pre_tunnel_close()
void management_pre_tunnel_close (struct management * man)
Definition at line 3087 of file manage.c.
References man_connection_close(), man_settings::management_over_tunnel, and management::settings.
Referenced by do_close_tun().
management_query_cert()
char* management_query_cert (struct management * man, const char * cert_name)
Definition at line 3790 of file manage.c.
References alloc_buf(), buf_bptr(), buf_write(), management::connection, man_connection::ext_cert_input, man_connection::ext_cert_state, free_buf(), and management_query_multiline_flatten_newline().
Referenced by init_ssl().
management_query_multiline()
static int management_query_multiline (struct management * man, const char * b64_data, const char * prompt, const char * cmd, int * state, struct buffer_list ** input) static
Definition at line 3628 of file manage.c.
References alloc_buf_gc(), BSTR, buf_printf(), clear_buf(), management::connection, EKS_INPUT, EKS_READY, EKS_SOLICIT, EKS_UNDEF, gc_free(), gc_new(), IER_RESET, in_extra_reset(), M_CLIENT, man_check_for_signals(), man_standalone_event_loop(), man_standalone_ok(), man_wait_for_client_connection(), msg, MWCC_OTHER_WAIT, management::persist, man_persist::special_state_msg, man_persist::standalone_disabled, and man_connection::state.
Referenced by management_query_multiline_flatten(), and management_query_multiline_flatten_newline().
management_query_multiline_flatten()
static char* management_query_multiline_flatten (struct management * man, const char * b64_data, const char * prompt, const char * cmd, int * state, struct buffer_list ** input) static
Definition at line 3734 of file manage.c.
References BLEN, buffer_list_aggregate(), buffer_list_defined(), buffer_list_free(), buffer_list_peek(), check_malloc_return(), buffer::data, and management_query_multiline().
Referenced by management_query_pk_sig().
management_query_multiline_flatten_newline()
static char* management_query_multiline_flatten_newline (struct management * man, const char * b64_data, const char * prompt, const char * cmd, int * state, struct buffer_list ** input) static
Definition at line 3705 of file manage.c.
References BLEN, buffer_list_aggregate_separator(), buffer_list_defined(), buffer_list_free(), buffer_list_peek(), check_malloc_return(), buffer::data, and management_query_multiline().
Referenced by management_query_cert().
management_query_pk_sig()
char* management_query_pk_sig (struct management * man, const char * b64_data, const char * algorithm)
Definition at line 3763 of file manage.c.
References alloc_buf(), buf_bptr(), buf_write(), man_connection::client_version, management::connection, man_connection::ext_key_input, man_connection::ext_key_state, free_buf(), and management_query_multiline_flatten().
Referenced by get_sig_from_man().
management_query_user_pass()
bool management_query_user_pass (struct management * man, struct user_pass * up, const char * type, const unsigned int flags, const char * static_challenge)
Definition at line 3498 of file manage.c.
References alloc_buf_gc(), blank_up, BOOL_CAST, BSTR, buf_printf(), CLEAR, management::connection, user_pass::defined, gc_free(), gc_new(), GET_USER_PASS_NEED_OK, GET_USER_PASS_NEED_STR, GET_USER_PASS_PASSWORD_ONLY, GET_USER_PASS_STATIC_CHALLENGE_ECHO, M_CLIENT, man_check_for_signals(), man_standalone_event_loop(), man_standalone_ok(), man_wait_for_client_connection(), msg, MWCC_PASSWORD_WAIT, user_pass::nocache, user_pass::password, management::persist, secure_memzero(), man_persist::special_state_msg, man_persist::standalone_disabled, man_connection::up_query, UP_QUERY_DISABLED, man_connection::up_query_mode, UP_QUERY_NEED_OK, UP_QUERY_NEED_STR, UP_QUERY_PASS, man_connection::up_query_type, UP_QUERY_USER_PASS, and user_pass::username.
Referenced by auth_user_pass_mgmt().
management_set_callback()
void management_set_callback (struct management * man, const struct management_callback * cb)
Definition at line 2734 of file manage.c.
References man_persist::callback, management::persist, and man_persist::standalone_disabled.
Referenced by init_management_callback_multi(), and init_management_callback_p2p().
management_set_state()
void management_set_state (struct management * man, const int state, const char * detail, const in_addr_t * tun_local_ip, const struct in6_addr * tun_local_ip6, const struct openvpn_sockaddr * local, const struct openvpn_sockaddr * remote)
Definition at line 2751 of file manage.c.
References CLEAR, management::connection, man_settings::flags, gc_free(), gc_new(), log_entry::local_ip, log_entry::local_ip6, log_entry::local_sock, LOG_ECHO_TO_LOG, log_entry_print(), log_history_add(), LOG_PRINT_CRLF, LOG_PRINT_INT_DATE, LOG_PRINT_LOCAL_IP, LOG_PRINT_REMOTE_IP, LOG_PRINT_STATE, LOG_PRINT_STATE_PREFIX, man_output_list_push(), MF_SERVER, now, OPENVPN_STATE_CLIENT_BASE, management::persist, log_entry::remote_sock, management::settings, log_entry_union::state, man_persist::state, man_connection::state_realtime, log_entry::string, log_entry::timestamp, log_entry::u, and update_time().
Referenced by add_routes(), check_connection_established(), do_ifconfig(), initialization_sequence_completed(), open_management(), openvpn_getaddrinfo(), signal_restart_status(), socket_connect(), tls_pre_decrypt(), and tls_process().
management_should_daemonize()
bool management_should_daemonize (struct management * man)
Definition at line 3819 of file manage.c.
References man_settings::flags, management_would_hold(), MF_QUERY_PASSWORDS, and management::settings.
management_sleep()
void management_sleep (const int n)
A sleep function that services the management layer for n seconds rather than doing nothing.
Definition at line 4128 of file manage.c.
References management_event_loop_n_seconds(), and sleep.
Referenced by do_up(), netsh_command(), openvpn_connect(), openvpn_getaddrinfo(), read_incoming_link(), socket_listen_accept(), socket_restart_pause(), and tuntap_set_connected().
management_socket_set()
void management_socket_set (struct management * man, struct event_set * es, void * arg, unsigned int * persistent)
Definition at line 3131 of file manage.c.
References ASSERT, management::connection, event_ctl(), EVENT_READ, EVENT_WRITE, man_persist_state(), MS_CC_WAIT_READ, MS_CC_WAIT_WRITE, MS_INITIAL, MS_LISTEN, man_connection::ne32, net_event_win32_get_event(), net_event_win32_reset_write(), and man_connection::state.
Referenced by io_wait_dowork(), man_block(), and multi_tcp_wait().
management_up_down()
void management_up_down (struct management * man, const char * updown, const struct env_set * es)
Definition at line 2892 of file manage.c.
References man_settings::flags, M_CLIENT, man_output_env(), MF_UP_DOWN, msg, and management::settings.
Referenced by do_close_tun(), and do_route().
management_would_hold()
bool management_would_hold (struct management * man)
Definition at line 3809 of file manage.c.
References man_settings::flags, man_persist::hold_release, man_standalone_ok(), MF_HOLD, management::persist, and management::settings.
Referenced by management_hold(), and management_should_daemonize().
set_client_version()
static void set_client_version (struct management * man, const char * version) static
Definition at line 1306 of file manage.c.
References man_connection::client_version, and management::connection.
Referenced by man_dispatch_command().
virtual_output_callback_func()
static void virtual_output_callback_func (void * arg, const unsigned int flags, const char * str) static
Definition at line 310 of file manage.c.
References AF_DID_PUSH, AF_DID_RESET, CLEAR, management::connection, gc_free(), gc_new(), man_persist::log, log_entry_print(), LOG_FATAL_NOTIFY, log_history_add(), LOG_PRINT_CRLF, LOG_PRINT_INT_DATE, LOG_PRINT_LOG_PREFIX, LOG_PRINT_MSG_FLAGS, man_connection::log_realtime, M_CLIENT, M_FATAL, man_output_list_push_finalize(), man_output_list_push_str(), man_password_needed(), man_reset_client_socket(), log_entry_union::msg_flags, now, management::persist, man_persist::standalone_disabled, log_entry::string, log_entry::timestamp, log_entry::u, and update_time().
Referenced by man_history(), and man_persist_init().
Variable Documentation
blank_up
const char blank_up[] = "[[BLANK]]" static
Definition at line 61 of file manage.c.
Referenced by man_query_password(), and management_query_user_pass().
management
struct management* management
Definition at line 63 of file manage.c.