OpenVPN: src/openvpn/manage.h File Reference
manage.h File Reference
#include "misc.h"
#include "event.h"
#include "socket.h"
#include "mroute.h"
Data Structures
struct command_line
union log_entry_union
struct log_entry
struct log_history
struct management_callback
struct man_persist
struct man_settings
struct man_connection
struct management
Macros
#define MANAGEMENT_VERSION 3
#define MANAGEMENT_N_PASSWORD_RETRIES 3
#define MANAGEMENT_LOG_HISTORY_INITIAL_SIZE 100
#define MANAGEMENT_ECHO_BUFFER_SIZE 100
#define MANAGEMENT_STATE_BUFFER_SIZE 100
#define LOG_PRINT_LOG_PREFIX (1<<0)
#define LOG_PRINT_ECHO_PREFIX (1<<1)
#define LOG_PRINT_STATE_PREFIX (1<<2)
#define LOG_PRINT_INT_DATE (1<<3)
#define LOG_PRINT_MSG_FLAGS (1<<4)
#define LOG_PRINT_STATE (1<<5)
#define LOG_PRINT_LOCAL_IP (1<<6)
#define LOG_PRINT_CRLF (1<<7)
#define LOG_FATAL_NOTIFY (1<<8)
#define LOG_PRINT_INTVAL (1<<9)
#define LOG_PRINT_REMOTE_IP (1<<10)
#define LOG_ECHO_TO_LOG (1<<11)
#define MCF_SERVER (1<<0) /* is OpenVPN being run as a server? */
#define MANSIG_IGNORE_USR1_HUP (1<<0)
#define MANSIG_MAP_USR1_TO_HUP (1<<1)
#define MANSIG_MAP_USR1_TO_TERM (1<<2)
#define UP_QUERY_DISABLED 0
#define UP_QUERY_USER_PASS 1
#define UP_QUERY_PASS 2
#define UP_QUERY_NEED_OK 3
#define UP_QUERY_NEED_STR 4
#define MS_INITIAL 0 /* all sockets are closed */
#define MS_LISTEN 1 /* no client is connected */
#define MS_CC_WAIT_READ 2 /* client is connected, waiting for read on socket */
#define MS_CC_WAIT_WRITE 3 /* client is connected, waiting for ability to write to socket */
#define IEC_UNDEF 0
#define IEC_CLIENT_AUTH 1
#define IEC_CLIENT_PF 2
#define IEC_RSA_SIGN 3
#define IEC_CERTIFICATE 4
#define IEC_PK_SIGN 5
#define EKS_UNDEF 0
#define EKS_SOLICIT 1
#define EKS_INPUT 2
#define EKS_READY 3
#define MF_SERVER (1<<0)
#define MF_QUERY_PASSWORDS (1<<1)
#define MF_HOLD (1<<2)
#define MF_SIGNAL (1<<3)
#define MF_FORGET_DISCONNECT (1<<4)
#define MF_CONNECT_AS_CLIENT (1<<5)
#define MF_UNIX_SOCK (1<<8)
#define MF_EXTERNAL_KEY (1<<9)
#define MF_EXTERNAL_KEY_NOPADDING (1<<10)
#define MF_EXTERNAL_KEY_PKCS1PAD (1<<11)
#define MF_UP_DOWN (1<<12)
#define MF_QUERY_REMOTE (1<<13)
#define MF_QUERY_PROXY (1<<14)
#define MF_EXTERNAL_CERT (1<<15)
#define OPENVPN_STATE_INITIAL 0 /* Initial, undefined state */
#define OPENVPN_STATE_CONNECTING 1 /* Management interface has been initialized */
#define OPENVPN_STATE_ASSIGN_IP 2 /* Assigning IP address to virtual network interface */
#define OPENVPN_STATE_ADD_ROUTES 3 /* Adding routes to system */
#define OPENVPN_STATE_CONNECTED 4 /* Initialization sequence completed */
#define OPENVPN_STATE_RECONNECTING 5 /* Restart */
#define OPENVPN_STATE_EXITING 6 /* Exit */
#define OPENVPN_STATE_WAIT 7 /* Waiting for initial response from server */
#define OPENVPN_STATE_AUTH 8 /* Authenticating with server */
#define OPENVPN_STATE_GET_CONFIG 9 /* Downloading configuration from server */
#define OPENVPN_STATE_RESOLVE 10 /* DNS lookup */
#define OPENVPN_STATE_TCP_CONNECT 11 /* Connecting to TCP server */
#define OPENVPN_STATE_CLIENT_BASE 7 /* Base index of client-only states */
Functions
struct command_line * command_line_new (const int buf_len)
void command_line_free (struct command_line *cl)
void command_line_add (struct command_line *cl, const unsigned char *buf, const int len)
const char * command_line_get (struct command_line *cl)
void command_line_reset (struct command_line *cl)
void command_line_next (struct command_line *cl)
const char * log_entry_print (const struct log_entry *e, unsigned int flags, struct gc_arena *gc)
struct log_history * log_history_init (const int capacity)
void log_history_close (struct log_history *h)
void log_history_add (struct log_history *h, const struct log_entry *le)
void log_history_resize (struct log_history *h, const int capacity)
const struct log_entry * log_history_ref (const struct log_history *h, const int index)
static int log_history_size (const struct log_history *h)
static int log_history_capacity (const struct log_history *h)
struct management * management_init (void)
bool management_open (struct management *man, const char *addr, const char *port, const char *pass_file, const char *client_user, const char *client_group, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size, const char *write_peer_info_file, const int remap_sigusr1, const unsigned int flags)
void management_close (struct management *man)
void management_post_tunnel_open (struct management *man, const in_addr_t tun_local_ip)
void management_pre_tunnel_close (struct management *man)
void management_socket_set (struct management *man, struct event_set *es, void *arg, unsigned int *persistent)
void management_io (struct management *man)
void management_set_callback (struct management *man, const struct management_callback *cb)
void management_clear_callback (struct management *man)
bool management_query_user_pass (struct management *man, struct user_pass *up, const char *type, const unsigned int flags, const char *static_challenge)
bool management_should_daemonize (struct management *man)
bool management_would_hold (struct management *man)
bool management_hold (struct management *man, int holdtime)
void management_event_loop_n_seconds (struct management *man, int sec)
void management_up_down (struct management *man, const char *updown, const struct env_set *es)
void management_notify (struct management *man, const char *severity, const char *type, const char *text)
void management_notify_generic (struct management *man, const char *str)
char * management_query_pk_sig (struct management *man, const char *b64_data, const char *algorithm)
char * management_query_cert (struct management *man, const char *cert_name)
static bool management_connected (const struct management *man)
static bool management_query_user_pass_enabled (const struct management *man)
static bool management_query_remote_enabled (const struct management *man)
static bool management_query_proxy_enabled (const struct management *man)
void management_set_state (struct management *man, const int state, const char *detail, const in_addr_t *tun_local_ip, const struct in6_addr *tun_local_ip6, const struct openvpn_sockaddr *local_addr, const struct openvpn_sockaddr *remote_addr)
void management_echo (struct management *man, const char *string, const bool pull)
void management_auth_failure (struct management *man, const char *type, const char *reason)
void management_auth_token (struct management *man, const char *token)
void man_bytecount_output_client (struct management *man)
static void man_bytecount_possible_output_client (struct management *man)
static void management_bytes_out_client (struct management *man, const int size)
static void management_bytes_in_client (struct management *man, const int size)
static void management_bytes_out (struct management *man, const int size)
static void management_bytes_in (struct management *man, const int size)
void management_sleep (const int n)
A sleep function that services the management layer for n seconds rather than doing nothing.
Variables
struct management * management
Macro Definition Documentation
EKS_INPUT
#define EKS_INPUT 2
Definition at line 296 of file manage.h.
EKS_READY
#define EKS_READY 3
Definition at line 297 of file manage.h.
EKS_SOLICIT
#define EKS_SOLICIT 1
Definition at line 295 of file manage.h.
EKS_UNDEF
#define EKS_UNDEF 0
Definition at line 294 of file manage.h.
IEC_CERTIFICATE
#define IEC_CERTIFICATE 4
Definition at line 286 of file manage.h.
IEC_CLIENT_AUTH
#define IEC_CLIENT_AUTH 1
Definition at line 283 of file manage.h.
IEC_CLIENT_PF
#define IEC_CLIENT_PF 2
Definition at line 284 of file manage.h.
IEC_PK_SIGN
#define IEC_PK_SIGN 5
Definition at line 287 of file manage.h.
IEC_RSA_SIGN
#define IEC_RSA_SIGN 3
Definition at line 285 of file manage.h.
IEC_UNDEF
#define IEC_UNDEF 0
Definition at line 282 of file manage.h.
LOG_ECHO_TO_LOG
#define LOG_ECHO_TO_LOG (1<<11)
Definition at line 116 of file manage.h.
LOG_FATAL_NOTIFY
#define LOG_FATAL_NOTIFY (1<<8)
Definition at line 110 of file manage.h.
LOG_PRINT_CRLF
#define LOG_PRINT_CRLF (1<<7)
Definition at line 109 of file manage.h.
LOG_PRINT_ECHO_PREFIX
#define LOG_PRINT_ECHO_PREFIX (1<<1)
Definition at line 101 of file manage.h.
LOG_PRINT_INT_DATE
#define LOG_PRINT_INT_DATE (1<<3)
Definition at line 104 of file manage.h.
LOG_PRINT_INTVAL
#define LOG_PRINT_INTVAL (1<<9)
Definition at line 112 of file manage.h.
LOG_PRINT_LOCAL_IP
#define LOG_PRINT_LOCAL_IP (1<<6)
Definition at line 107 of file manage.h.
LOG_PRINT_LOG_PREFIX
#define LOG_PRINT_LOG_PREFIX (1<<0)
Definition at line 100 of file manage.h.
LOG_PRINT_MSG_FLAGS
#define LOG_PRINT_MSG_FLAGS (1<<4)
Definition at line 105 of file manage.h.
LOG_PRINT_REMOTE_IP
#define LOG_PRINT_REMOTE_IP (1<<10)
Definition at line 114 of file manage.h.
LOG_PRINT_STATE
#define LOG_PRINT_STATE (1<<5)
Definition at line 106 of file manage.h.
LOG_PRINT_STATE_PREFIX
#define LOG_PRINT_STATE_PREFIX (1<<2)
Definition at line 102 of file manage.h.
MANAGEMENT_ECHO_BUFFER_SIZE
#define MANAGEMENT_ECHO_BUFFER_SIZE 100
Definition at line 37 of file manage.h.
MANAGEMENT_LOG_HISTORY_INITIAL_SIZE
#define MANAGEMENT_LOG_HISTORY_INITIAL_SIZE 100
Definition at line 36 of file manage.h.
MANAGEMENT_N_PASSWORD_RETRIES
#define MANAGEMENT_N_PASSWORD_RETRIES 3
Definition at line 35 of file manage.h.
MANAGEMENT_STATE_BUFFER_SIZE
#define MANAGEMENT_STATE_BUFFER_SIZE 100
Definition at line 38 of file manage.h.
MANAGEMENT_VERSION
#define MANAGEMENT_VERSION 3
Definition at line 34 of file manage.h.
MANSIG_IGNORE_USR1_HUP
#define MANSIG_IGNORE_USR1_HUP (1<<0)
Definition at line 245 of file manage.h.
MANSIG_MAP_USR1_TO_HUP
#define MANSIG_MAP_USR1_TO_HUP (1<<1)
Definition at line 246 of file manage.h.
MANSIG_MAP_USR1_TO_TERM
#define MANSIG_MAP_USR1_TO_TERM (1<<2)
Definition at line 247 of file manage.h.
MCF_SERVER
#define MCF_SERVER (1<<0) /* is OpenVPN being run as a server? */
Definition at line 158 of file manage.h.
MF_CONNECT_AS_CLIENT
#define MF_CONNECT_AS_CLIENT (1<<5)
Definition at line 341 of file manage.h.
MF_EXTERNAL_CERT
#define MF_EXTERNAL_CERT (1<<15)
Definition at line 355 of file manage.h.
MF_EXTERNAL_KEY
#define MF_EXTERNAL_KEY (1<<9)
Definition at line 349 of file manage.h.
MF_EXTERNAL_KEY_NOPADDING
#define MF_EXTERNAL_KEY_NOPADDING (1<<10)
Definition at line 350 of file manage.h.
MF_EXTERNAL_KEY_PKCS1PAD
#define MF_EXTERNAL_KEY_PKCS1PAD (1<<11)
Definition at line 351 of file manage.h.
MF_FORGET_DISCONNECT
#define MF_FORGET_DISCONNECT (1<<4)
Definition at line 340 of file manage.h.
MF_HOLD
#define MF_HOLD (1<<2)
Definition at line 338 of file manage.h.
MF_QUERY_PASSWORDS
#define MF_QUERY_PASSWORDS (1<<1)
Definition at line 337 of file manage.h.
MF_QUERY_PROXY
#define MF_QUERY_PROXY (1<<14)
Definition at line 354 of file manage.h.
MF_QUERY_REMOTE
#define MF_QUERY_REMOTE (1<<13)
Definition at line 353 of file manage.h.
MF_SERVER
#define MF_SERVER (1<<0)
Definition at line 336 of file manage.h.
MF_SIGNAL
#define MF_SIGNAL (1<<3)
Definition at line 339 of file manage.h.
MF_UNIX_SOCK
#define MF_UNIX_SOCK (1<<8)
Definition at line 348 of file manage.h.
MF_UP_DOWN
#define MF_UP_DOWN (1<<12)
Definition at line 352 of file manage.h.
MS_CC_WAIT_READ
#define MS_CC_WAIT_READ 2 /* client is connected, waiting for read on socket */
Definition at line 261 of file manage.h.
MS_CC_WAIT_WRITE
#define MS_CC_WAIT_WRITE 3 /* client is connected, waiting for ability to write to socket */
Definition at line 262 of file manage.h.
MS_INITIAL
#define MS_INITIAL 0 /* all sockets are closed */
Definition at line 259 of file manage.h.
MS_LISTEN
#define MS_LISTEN 1 /* no client is connected */
Definition at line 260 of file manage.h.
OPENVPN_STATE_ADD_ROUTES
#define OPENVPN_STATE_ADD_ROUTES 3 /* Adding routes to system */
Definition at line 497 of file manage.h.
OPENVPN_STATE_ASSIGN_IP
#define OPENVPN_STATE_ASSIGN_IP 2 /* Assigning IP address to virtual network interface */
Definition at line 496 of file manage.h.
OPENVPN_STATE_AUTH
#define OPENVPN_STATE_AUTH 8 /* Authenticating with server */
Definition at line 504 of file manage.h.
OPENVPN_STATE_CLIENT_BASE
#define OPENVPN_STATE_CLIENT_BASE 7 /* Base index of client-only states */
Definition at line 509 of file manage.h.
OPENVPN_STATE_CONNECTED
#define OPENVPN_STATE_CONNECTED 4 /* Initialization sequence completed */
Definition at line 498 of file manage.h.
OPENVPN_STATE_CONNECTING
#define OPENVPN_STATE_CONNECTING 1 /* Management interface has been initialized */
Definition at line 495 of file manage.h.
OPENVPN_STATE_EXITING
#define OPENVPN_STATE_EXITING 6 /* Exit */
Definition at line 500 of file manage.h.
OPENVPN_STATE_GET_CONFIG
#define OPENVPN_STATE_GET_CONFIG 9 /* Downloading configuration from server */
Definition at line 505 of file manage.h.
OPENVPN_STATE_INITIAL
#define OPENVPN_STATE_INITIAL 0 /* Initial, undefined state */
Definition at line 494 of file manage.h.
OPENVPN_STATE_RECONNECTING
#define OPENVPN_STATE_RECONNECTING 5 /* Restart */
Definition at line 499 of file manage.h.
OPENVPN_STATE_RESOLVE
#define OPENVPN_STATE_RESOLVE 10 /* DNS lookup */
Definition at line 506 of file manage.h.
OPENVPN_STATE_TCP_CONNECT
#define OPENVPN_STATE_TCP_CONNECT 11 /* Connecting to TCP server */
Definition at line 507 of file manage.h.
OPENVPN_STATE_WAIT
#define OPENVPN_STATE_WAIT 7 /* Waiting for initial response from server */
Definition at line 503 of file manage.h.
UP_QUERY_DISABLED
#define UP_QUERY_DISABLED 0
Definition at line 252 of file manage.h.
UP_QUERY_NEED_OK
#define UP_QUERY_NEED_OK 3
Definition at line 255 of file manage.h.
UP_QUERY_NEED_STR
#define UP_QUERY_NEED_STR 4
Definition at line 256 of file manage.h.
UP_QUERY_PASS
#define UP_QUERY_PASS 2
Definition at line 254 of file manage.h.
UP_QUERY_USER_PASS
#define UP_QUERY_USER_PASS 1
Definition at line 253 of file manage.h.
Function Documentation
command_line_add()
void command_line_add (struct command_line * cl, const unsigned char * buf, const int len)
Definition at line 3907 of file manage.c.
References command_line::buf, buf_clear(), buf_write_u8(), CC_NEWLINE, CC_PRINT, and char_class().
Referenced by man_read().
command_line_free()
void command_line_free (struct command_line * cl)
Definition at line 3898 of file manage.c.
References command_line::buf, command_line_reset(), free_buf(), and command_line::residual.
Referenced by man_connection_close().
command_line_get()
const char* command_line_get (struct command_line * cl)
Definition at line 3923 of file manage.c.
References BSTR, command_line::buf, buf_chomp(), buf_copy_excess(), buf_substring_len(), and command_line::residual.
Referenced by man_read().
command_line_new()
struct command_line* command_line_new (const int buf_len)
Definition at line 3881 of file manage.c.
References alloc_buf(), ALLOC_OBJ_CLEAR, command_line::buf, buf_len(), and command_line::residual.
Referenced by man_connection_init().
command_line_next()
void command_line_next (struct command_line * cl)
Definition at line 3939 of file manage.c.
References command_line::buf, buf_clear(), buf_copy(), and command_line::residual.
Referenced by man_read().
command_line_reset()
void command_line_reset (struct command_line * cl)
Definition at line 3891 of file manage.c.
References command_line::buf, buf_clear(), and command_line::residual.
Referenced by command_line_free(), and man_reset_client_socket().
log_entry_print()
const char* log_entry_print (const struct log_entry * e, unsigned int flags, struct gc_arena * gc)
Definition at line 3951 of file manage.c.
References openvpn_sockaddr::addr, addr_defined(), alloc_buf_gc(), BSTR, buf_printf(), D_MANAGEMENT, ERR_BUF_SIZE, IA_EMPTY_IF_UNDEF, log_entry_union::intval, log_entry::local_ip, log_entry::local_ip6, log_entry::local_sock, LOG_ECHO_TO_LOG, LOG_FATAL_NOTIFY, LOG_PRINT_CRLF, LOG_PRINT_ECHO_PREFIX, LOG_PRINT_INT_DATE, LOG_PRINT_INTVAL, LOG_PRINT_LOCAL_IP, LOG_PRINT_LOG_PREFIX, LOG_PRINT_MSG_FLAGS, LOG_PRINT_REMOTE_IP, LOG_PRINT_STATE, LOG_PRINT_STATE_PREFIX, man_state_name(), msg, log_entry_union::msg_flags, msg_flags_string(), print_in6_addr(), print_in_addr_t(), print_sockaddr_ex(), PS_DONT_SHOW_FAMILY, PS_SHOW_PORT, log_entry::remote_sock, openvpn_sockaddr::sa, log_entry_union::state, log_entry::string, log_entry::timestamp, and log_entry::u.
Referenced by man_history(), management_echo(), management_set_state(), and virtual_output_callback_func().
log_history_add()
void log_history_add (struct log_history * h, const struct log_entry * le)
Definition at line 4073 of file manage.c.
References log_history::array, ASSERT, log_history::base, log_history::capacity, log_entry_free_contents(), log_index(), log_history::size, log_entry::string, and string_alloc().
Referenced by log_history_resize(), management_echo(), management_set_state(), and virtual_output_callback_func().
log_history_capacity()
static int log_history_capacity (const struct log_history * h) inline static
Definition at line 145 of file manage.h.
References log_history::capacity.
log_history_close()
void log_history_close (struct log_history * h)
Definition at line 4066 of file manage.c.
References log_history_free_contents().
Referenced by man_persist_close().
log_history_init()
struct log_history* log_history_init (const int capacity)
Definition at line 4045 of file manage.c.
References ALLOC_OBJ, ASSERT, log_history::capacity, and log_history_obj_init().
Referenced by man_persist_init().
log_history_ref()
const struct log_entry* log_history_ref (const struct log_history * h, const int index)
Definition at line 4115 of file manage.c.
References log_history::array, log_index(), and log_history::size.
Referenced by man_history().
log_history_resize()
void log_history_resize (struct log_history * h, const int capacity)
Definition at line 4094 of file manage.c.
References log_history::array, ASSERT, log_history::capacity, log_history_add(), log_history_free_contents(), log_history_obj_init(), log_index(), and log_history::size.
Referenced by management_open().
log_history_size()
static int log_history_size (const struct log_history * h) inline static
Definition at line 139 of file manage.h.
References log_history::size.
Referenced by man_history().
man_bytecount_output_client()
void man_bytecount_output_client (struct management * man)
Definition at line 477 of file manage.c.
References man_connection::bytecount_last_update, man_persist::bytes_in, man_persist::bytes_out, management::connection, counter_format, M_CLIENT, msg, now, openvpn_snprintf(), and management::persist.
Referenced by man_bytecount_possible_output_client().
man_bytecount_possible_output_client()
static void man_bytecount_possible_output_client (struct management * man) inline static
Definition at line 543 of file manage.h.
References man_connection::bytecount_last_update, man_connection::bytecount_update_seconds, management::connection, man_bytecount_output_client(), and now.
Referenced by management_bytes_in_client(), and management_bytes_out_client().
management_auth_failure()
void management_auth_failure (struct management * man, const char * type, const char * reason)
Definition at line 3096 of file manage.c.
References M_CLIENT, and msg.
Referenced by auth_user_pass_mgmt(), receive_auth_failed(), tls_ctx_load_pkcs12(), and tls_ctx_load_priv_file().
management_auth_token()
void management_auth_token (struct management * man, const char * token)
Definition at line 3109 of file manage.c.
References M_CLIENT, and msg.
Referenced by add_option().
management_bytes_in()
static void management_bytes_in (struct management * man, const int size) inline static
Definition at line 577 of file manage.h.
References man_persist::callback, management_callback::flags, management_bytes_in_client(), MCF_SERVER, and management::persist.
Referenced by process_incoming_link_part1().
management_bytes_in_client()
static void management_bytes_in_client (struct management * man, const int size) inline static
Definition at line 561 of file manage.h.
References man_persist::bytes_in, man_bytecount_possible_output_client(), and management::persist.
Referenced by management_bytes_in().
management_bytes_out()
static void management_bytes_out (struct management * man, const int size) inline static
Definition at line 568 of file manage.h.
References man_persist::callback, management_callback::flags, management_bytes_out_client(), MCF_SERVER, and management::persist.
Referenced by process_outgoing_link().
management_bytes_out_client()
static void management_bytes_out_client (struct management * man, const int size) inline static
Definition at line 554 of file manage.h.
References man_persist::bytes_out, man_bytecount_possible_output_client(), and management::persist.
Referenced by management_bytes_out().
management_clear_callback()
void management_clear_callback (struct management * man)
Definition at line 2742 of file manage.c.
References man_persist::callback, CLEAR, man_persist::hold_release, man_output_list_push_finalize(), management::persist, and man_persist::standalone_disabled.
Referenced by uninit_management_callback().
management_close()
void management_close (struct management * man)
Definition at line 2724 of file manage.c.
References man_connection_close(), man_output_list_push_finalize(), man_persist_close(), man_settings_close(), management::persist, and management::settings.
Referenced by close_management().
management_connected()
static bool management_connected (const struct management * man) inline static
Definition at line 450 of file manage.h.
References management::connection, MS_CC_WAIT_READ, MS_CC_WAIT_WRITE, and man_connection::state.
Referenced by man_output_list_push_finalize(), and man_output_list_push_str().
management_echo()
void management_echo (struct management * man, const char * string, const bool pull)
Definition at line 3033 of file manage.c.
References BOOL_CAST, CLEAR, management::connection, man_persist::echo, man_connection::echo_realtime, gc_free(), gc_new(), log_entry_union::intval, log_entry_print(), log_history_add(), LOG_PRINT_CRLF, LOG_PRINT_ECHO_PREFIX, LOG_PRINT_INT_DATE, man_output_list_push(), MANAGEMENT_ECHO_FLAGS, now, management::persist, log_entry::string, log_entry::timestamp, log_entry::u, and update_time().
Referenced by add_option().
management_event_loop_n_seconds()
void management_event_loop_n_seconds (struct management * man, int sec)
Definition at line 3446 of file manage.c.
References man_check_for_signals(), man_standalone_event_loop(), man_standalone_ok(), man_wait_for_client_connection(), now, management::persist, sleep, man_persist::standalone_disabled, and update_time().
Referenced by ce_management_query_proxy(), ce_management_query_remote(), and management_sleep().
management_hold()
bool management_hold (struct management * man, int holdtime)
Definition at line 3829 of file manage.c.
References alloc_buf_gc(), BSTR, buf_printf(), gc_free(), gc_new(), man_persist::hold_release, M_CLIENT, man_check_for_signals(), man_standalone_event_loop(), man_wait_for_client_connection(), management_would_hold(), man_settings::mansig, MANSIG_IGNORE_USR1_HUP, msg, MWCC_HOLD_WAIT, management::persist, management::settings, man_persist::special_state_msg, and man_persist::standalone_disabled.
Referenced by do_hold().
management_init()
struct management* management_init (void)
Definition at line 2651 of file manage.c.
References ALLOC_OBJ_CLEAR, management::connection, man_connection_clear(), man_persist_init(), MANAGEMENT_ECHO_BUFFER_SIZE, MANAGEMENT_LOG_HISTORY_INITIAL_SIZE, and MANAGEMENT_STATE_BUFFER_SIZE.
Referenced by init_management().
management_io()
void management_io (struct management * man)
Definition at line 3171 of file manage.c.
References management::connection, man_accept(), man_read(), man_reset_client_socket(), man_write(), MS_CC_WAIT_READ, MS_CC_WAIT_WRITE, MS_INITIAL, MS_LISTEN, man_connection::ne32, net_event_win32_clear_selected_events(), net_event_win32_get_event_mask(), net_event_win32_reset(), man_connection::state, and status.
Referenced by man_output_standalone(), man_standalone_event_loop(), multi_process_io_udp(), multi_tcp_process_io(), and process_io().
management_notify()
void management_notify (struct management * man, const char * severity, const char * type, const char * text)
Definition at line 2902 of file manage.c.
References M_CLIENT, and msg.
Referenced by server_pushed_signal().
management_notify_generic()
void management_notify_generic (struct management * man, const char * str)
Definition at line 2908 of file manage.c.
References M_CLIENT, and msg.
Referenced by ce_management_query_proxy(), ce_management_query_remote(), and server_pushed_info().
management_open()
bool management_open (struct management * man, const char * addr, const char * port, const char * pass_file, const char * client_user, const char * client_group, const int log_history_cache, const int echo_buffer_size, const int state_buffer_size, const char * write_peer_info_file, const int remap_sigusr1, const unsigned int flags)
Definition at line 2667 of file manage.c.
References management::connection, man_persist::echo, man_settings::echo_buffer_size, man_persist::log, man_settings::log_history_cache, log_history_resize(), man_connection_init(), man_settings_init(), man_settings::management_over_tunnel, MS_INITIAL, management::persist, management::settings, man_persist::state, man_connection::state, and man_settings::state_buffer_size.
Referenced by open_management().
management_post_tunnel_open()
void management_post_tunnel_open (struct management * man, const in_addr_t tun_local_ip)
Definition at line 3064 of file manage.c.
References ASSERT, management::connection, GETADDR_PASSIVE, man_settings::local, man_connection_init(), man_settings::management_over_tunnel, MS_INITIAL, openvpn_getaddrinfo(), management::settings, and man_connection::state.
Referenced by initialization_sequence_completed().
management_pre_tunnel_close()
void management_pre_tunnel_close (struct management * man)
Definition at line 3087 of file manage.c.
References man_connection_close(), man_settings::management_over_tunnel, and management::settings.
Referenced by do_close_tun().
management_query_cert()
char* management_query_cert (struct management * man, const char * cert_name)
Definition at line 3790 of file manage.c.
References alloc_buf(), buf_bptr(), buf_write(), management::connection, man_connection::ext_cert_input, man_connection::ext_cert_state, free_buf(), and management_query_multiline_flatten_newline().
Referenced by init_ssl().
management_query_pk_sig()
char* management_query_pk_sig (struct management * man, const char * b64_data, const char * algorithm)
Definition at line 3763 of file manage.c.
References alloc_buf(), buf_bptr(), buf_write(), man_connection::client_version, management::connection, man_connection::ext_key_input, man_connection::ext_key_state, free_buf(), and management_query_multiline_flatten().
Referenced by get_sig_from_man().
management_query_proxy_enabled()
static bool management_query_proxy_enabled (const struct management * man) inline static
Definition at line 468 of file manage.h.
References BOOL_CAST, man_settings::flags, MF_QUERY_PROXY, and management::settings.
Referenced by next_connection_entry().
management_query_remote_enabled()
static bool management_query_remote_enabled (const struct management * man) inline static
Definition at line 462 of file manage.h.
References BOOL_CAST, man_settings::flags, MF_QUERY_REMOTE, and management::settings.
Referenced by next_connection_entry().
management_query_user_pass()
bool management_query_user_pass (struct management * man, struct user_pass * up, const char * type, const unsigned int flags, const char * static_challenge)
Definition at line 3498 of file manage.c.
References alloc_buf_gc(), blank_up, BOOL_CAST, BSTR, buf_printf(), CLEAR, management::connection, user_pass::defined, gc_free(), gc_new(), GET_USER_PASS_NEED_OK, GET_USER_PASS_NEED_STR, GET_USER_PASS_PASSWORD_ONLY, GET_USER_PASS_STATIC_CHALLENGE_ECHO, M_CLIENT, man_check_for_signals(), man_standalone_event_loop(), man_standalone_ok(), man_wait_for_client_connection(), msg, MWCC_PASSWORD_WAIT, user_pass::nocache, user_pass::password, management::persist, secure_memzero(), man_persist::special_state_msg, man_persist::standalone_disabled, man_connection::up_query, UP_QUERY_DISABLED, man_connection::up_query_mode, UP_QUERY_NEED_OK, UP_QUERY_NEED_STR, UP_QUERY_PASS, man_connection::up_query_type, UP_QUERY_USER_PASS, and user_pass::username.
Referenced by auth_user_pass_mgmt().
management_query_user_pass_enabled()
static bool management_query_user_pass_enabled (const struct management * man) inline static
Definition at line 456 of file manage.h.
References BOOL_CAST, man_settings::flags, MF_QUERY_PASSWORDS, and management::settings.
Referenced by get_user_pass_cr().
management_set_callback()
void management_set_callback (struct management * man, const struct management_callback * cb)
Definition at line 2734 of file manage.c.
References man_persist::callback, management::persist, and man_persist::standalone_disabled.
Referenced by init_management_callback_multi(), and init_management_callback_p2p().
management_set_state()
void management_set_state (struct management * man, const int state, const char * detail, const in_addr_t * tun_local_ip, const struct in6_addr * tun_local_ip6, const struct openvpn_sockaddr * local_addr, const struct openvpn_sockaddr * remote_addr)
Definition at line 2751 of file manage.c.
References CLEAR, management::connection, man_settings::flags, gc_free(), gc_new(), log_entry::local_ip, log_entry::local_ip6, log_entry::local_sock, LOG_ECHO_TO_LOG, log_entry_print(), log_history_add(), LOG_PRINT_CRLF, LOG_PRINT_INT_DATE, LOG_PRINT_LOCAL_IP, LOG_PRINT_REMOTE_IP, LOG_PRINT_STATE, LOG_PRINT_STATE_PREFIX, man_output_list_push(), MF_SERVER, now, OPENVPN_STATE_CLIENT_BASE, management::persist, log_entry::remote_sock, management::settings, log_entry_union::state, man_persist::state, man_connection::state_realtime, log_entry::string, log_entry::timestamp, log_entry::u, and update_time().
Referenced by add_routes(), check_connection_established(), do_ifconfig(), initialization_sequence_completed(), open_management(), openvpn_getaddrinfo(), signal_restart_status(), socket_connect(), tls_pre_decrypt(), and tls_process().
management_should_daemonize()
bool management_should_daemonize (struct management * man)
Definition at line 3819 of file manage.c.
References man_settings::flags, management_would_hold(), MF_QUERY_PASSWORDS, and management::settings.
management_sleep()
void management_sleep (const int n)
A sleep function that services the management layer for n seconds rather than doing nothing.
Definition at line 4128 of file manage.c.
References management_event_loop_n_seconds(), and sleep.
Referenced by do_up(), netsh_command(), openvpn_connect(), openvpn_getaddrinfo(), read_incoming_link(), socket_listen_accept(), socket_restart_pause(), and tuntap_set_connected().
management_socket_set()
void management_socket_set (struct management * man, struct event_set * es, void * arg, unsigned int * persistent)
Definition at line 3131 of file manage.c.
References ASSERT, management::connection, event_ctl(), EVENT_READ, EVENT_WRITE, man_persist_state(), MS_CC_WAIT_READ, MS_CC_WAIT_WRITE, MS_INITIAL, MS_LISTEN, man_connection::ne32, net_event_win32_get_event(), net_event_win32_reset_write(), and man_connection::state.
Referenced by io_wait_dowork(), man_block(), and multi_tcp_wait().
management_up_down()
void management_up_down (struct management * man, const char * updown, const struct env_set * es)
Definition at line 2892 of file manage.c.
References man_settings::flags, M_CLIENT, man_output_env(), MF_UP_DOWN, msg, and management::settings.
Referenced by do_close_tun(), and do_route().
management_would_hold()
bool management_would_hold (struct management * man)
Definition at line 3809 of file manage.c.
References man_settings::flags, man_persist::hold_release, man_standalone_ok(), MF_HOLD, management::persist, and management::settings.
Referenced by management_hold(), and management_should_daemonize().
Variable Documentation
management
struct management* management
Definition at line 63 of file manage.c.