OpenVPN: src/openvpn/mbuf.h File Reference
mbuf.h File Reference
#include "basic.h"
#include "buffer.h"
Data Structures
struct mbuf_buffer
struct mbuf_item
struct mbuf_set
Macros
#define MBUF_INDEX(head, offset, size) (((head) + (offset)) & ((size)-1))
#define MF_UNICAST (1<<0)
Functions
struct mbuf_set * mbuf_init (unsigned int size)
void mbuf_free (struct mbuf_set *ms)
struct mbuf_buffer * mbuf_alloc_buf (const struct buffer *buf)
void mbuf_free_buf (struct mbuf_buffer *mb)
void mbuf_add_item (struct mbuf_set *ms, const struct mbuf_item *item)
bool mbuf_extract_item (struct mbuf_set *ms, struct mbuf_item *item)
void mbuf_dereference_instance (struct mbuf_set *ms, struct multi_instance *mi)
static bool mbuf_defined (const struct mbuf_set *ms)
static unsigned int mbuf_len (const struct mbuf_set *ms)
static int mbuf_maximum_queued (const struct mbuf_set *ms)
struct multi_instance * mbuf_peek_dowork (struct mbuf_set *ms)
static struct multi_instance * mbuf_peek (struct mbuf_set *ms)
Macro Definition Documentation
MBUF_INDEX
#define MBUF_INDEX (head, offset, size) (((head) + (offset)) & ((size)-1))
Definition at line 41 of file mbuf.h.
MF_UNICAST
#define MF_UNICAST (1<<0)
Definition at line 48 of file mbuf.h.
Function Documentation
mbuf_add_item()
void mbuf_add_item (struct mbuf_set * ms, const struct mbuf_item * item)
Definition at line 93 of file mbuf.c.
References mbuf_set::array, ASSERT, mbuf_item::buffer, mbuf_set::capacity, D_MULTI_DROPPED, mbuf_set::head, mbuf_set::len, mbuf_set::max_queued, mbuf_extract_item(), mbuf_free_buf(), MBUF_INDEX, msg, and mbuf_buffer::refcount.
Referenced by multi_add_mbuf(), and multi_tcp_process_outgoing_link().
mbuf_alloc_buf()
struct mbuf_buffer* mbuf_alloc_buf (const struct buffer * buf)
Definition at line 69 of file mbuf.c.
References ALLOC_OBJ, mbuf_buffer::buf, clone_buf(), mbuf_buffer::flags, and mbuf_buffer::refcount.
Referenced by multi_bcast(), multi_tcp_process_outgoing_link(), and multi_unicast().
mbuf_defined()
static bool mbuf_defined (const struct mbuf_set * ms) inline static
Definition at line 82 of file mbuf.h.
References mbuf_set::len.
Referenced by mbuf_peek(), multi_process_outgoing_link_pre(), multi_tcp_process_outgoing_link(), multi_tcp_set_global_rw_flags(), and p2mp_iow_flags().
mbuf_dereference_instance()
void mbuf_dereference_instance (struct mbuf_set * ms, struct multi_instance * mi)
Definition at line 156 of file mbuf.c.
References mbuf_set::array, mbuf_item::buffer, mbuf_set::capacity, D_MBUF, mbuf_set::head, mbuf_item::instance, mbuf_set::len, mbuf_free_buf(), MBUF_INDEX, and msg.
Referenced by multi_close_instance().
mbuf_extract_item()
bool mbuf_extract_item (struct mbuf_set * ms, struct mbuf_item * item)
Definition at line 115 of file mbuf.c.
References mbuf_set::array, mbuf_set::capacity, mbuf_set::head, mbuf_item::instance, mbuf_set::len, and MBUF_INDEX.
Referenced by mbuf_add_item(), multi_get_queue(), and multi_tcp_process_outgoing_link_ready().
mbuf_free()
void mbuf_free (struct mbuf_set * ms)
Definition at line 53 of file mbuf.c.
References mbuf_set::array, mbuf_item::buffer, mbuf_set::capacity, mbuf_set::head, mbuf_set::len, mbuf_free_buf(), and MBUF_INDEX.
Referenced by multi_tcp_instance_specific_free(), and multi_uninit().
mbuf_free_buf()
void mbuf_free_buf (struct mbuf_buffer * mb)
Definition at line 80 of file mbuf.c.
References mbuf_buffer::buf, free_buf(), and mbuf_buffer::refcount.
Referenced by mbuf_add_item(), mbuf_dereference_instance(), mbuf_free(), multi_bcast(), multi_get_queue(), multi_tcp_process_outgoing_link(), multi_tcp_process_outgoing_link_ready(), and multi_unicast().
mbuf_init()
struct mbuf_set* mbuf_init (unsigned int size)
Definition at line 43 of file mbuf.c.
References adjust_power_of_2(), ALLOC_ARRAY, ALLOC_OBJ_CLEAR, mbuf_set::array, and mbuf_set::capacity.
Referenced by multi_init(), and multi_tcp_instance_specific_init().
mbuf_len()
static unsigned int mbuf_len (const struct mbuf_set * ms) inline static
Definition at line 88 of file mbuf.h.
References mbuf_set::len.
Referenced by multi_output_queue_ready().
mbuf_maximum_queued()
static int mbuf_maximum_queued (const struct mbuf_set * ms) inline static
Definition at line 94 of file mbuf.h.
References mbuf_set::max_queued.
Referenced by multi_print_status().
mbuf_peek()
static struct multi_instance* mbuf_peek (struct mbuf_set * ms) inline static
Definition at line 102 of file mbuf.h.
References mbuf_defined(), and mbuf_peek_dowork().
Referenced by multi_tcp_process_io().
mbuf_peek_dowork()
struct multi_instance* mbuf_peek_dowork (struct mbuf_set * ms)
Definition at line 136 of file mbuf.c.
References mbuf_set::array, mbuf_set::capacity, mbuf_set::head, mbuf_item::instance, mbuf_set::len, and MBUF_INDEX.
Referenced by mbuf_peek().