OpenVPN: src/openvpn/mroute.h File Reference
mroute.h File Reference
#include "buffer.h"
#include "list.h"
#include "route.h"
#include <stddef.h>
Data Structures
struct mroute_addr
struct mroute_helper
Macros
#define IP_MCAST_SUBNET_MASK ((in_addr_t)240<<24)
#define IP_MCAST_NETWORK ((in_addr_t)224<<24)
#define MROUTE_EXTRACT_SUCCEEDED (1<<0)
#define MROUTE_EXTRACT_BCAST (1<<1)
#define MROUTE_EXTRACT_MCAST (1<<2)
#define MROUTE_EXTRACT_IGMP (1<<3)
#define MROUTE_SEC_EXTRACT_SUCCEEDED (1<<(0+MROUTE_SEC_SHIFT))
#define MROUTE_SEC_EXTRACT_BCAST (1<<(1+MROUTE_SEC_SHIFT))
#define MROUTE_SEC_EXTRACT_MCAST (1<<(2+MROUTE_SEC_SHIFT))
#define MROUTE_SEC_EXTRACT_IGMP (1<<(3+MROUTE_SEC_SHIFT))
#define MROUTE_SEC_SHIFT 4
#define MR_MAX_ADDR_LEN 20
#define MR_ADDR_NONE 0
#define MR_ADDR_ETHER 1
#define MR_ADDR_IPV4 2
#define MR_ADDR_IPV6 3
#define MR_ADDR_MASK 3
#define MR_WITH_PORT 4
#define MR_WITH_NETBITS 8
#define MR_ARP 16
#define raw_addr mroute_union.raw_addr
#define ether mroute_union.ether
#define v4 mroute_union.v4
#define v6 mroute_union.v6
#define v4mappedv6 mroute_union.v4mappedv6
#define MR_HELPER_NET_LEN 129
#define MAPF_SUBNET (1<<0)
#define MAPF_IA_EMPTY_IF_UNDEF (1<<1)
#define MAPF_SHOW_ARP (1<<2)
Functions
bool mroute_extract_openvpn_sockaddr (struct mroute_addr *addr, const struct openvpn_sockaddr *osaddr, bool use_port)
bool mroute_learnable_address (const struct mroute_addr *addr, struct gc_arena *gc)
uint32_t mroute_addr_hash_function (const void *key, uint32_t iv)
bool mroute_addr_compare_function (const void *key1, const void *key2)
void mroute_addr_init (struct mroute_addr *addr)
const char * mroute_addr_print (const struct mroute_addr *ma, struct gc_arena *gc)
const char * mroute_addr_print_ex (const struct mroute_addr *ma, const unsigned int flags, struct gc_arena *gc)
void mroute_addr_mask_host_bits (struct mroute_addr *ma)
struct mroute_helper * mroute_helper_init (int ageable_ttl_secs)
void mroute_helper_free (struct mroute_helper *mh)
void mroute_helper_add_iroute46 (struct mroute_helper *mh, int netbits)
void mroute_helper_del_iroute46 (struct mroute_helper *mh, int netbits)
unsigned int mroute_extract_addr_ip (struct mroute_addr *src, struct mroute_addr *dest, const struct buffer *buf)
unsigned int mroute_extract_addr_ether (struct mroute_addr *src, struct mroute_addr *dest, struct mroute_addr *esrc, struct mroute_addr *edest, uint16_t vid, const struct buffer *buf)
static unsigned int mroute_extract_addr_from_packet (struct mroute_addr *src, struct mroute_addr *dest, struct mroute_addr *esrc, struct mroute_addr *edest, uint16_t vid, const struct buffer *buf, int tunnel_type)
static bool mroute_addr_equal (const struct mroute_addr *a1, const struct mroute_addr *a2)
static const uint8_t * mroute_addr_hash_ptr (const struct mroute_addr *a)
static uint32_t mroute_addr_hash_len (const struct mroute_addr *a)
static void mroute_extract_in_addr_t (struct mroute_addr *dest, const in_addr_t src)
static in_addr_t in_addr_t_from_mroute_addr (const struct mroute_addr *addr)
static void mroute_addr_reset (struct mroute_addr *ma)
Macro Definition Documentation
ether
#define ether mroute_union.ether
IP_MCAST_NETWORK
#define IP_MCAST_NETWORK ((in_addr_t)224<<24)
Definition at line 34 of file mroute.h.
IP_MCAST_SUBNET_MASK
#define IP_MCAST_SUBNET_MASK ((in_addr_t)240<<24)
Definition at line 33 of file mroute.h.
MAPF_IA_EMPTY_IF_UNDEF
#define MAPF_IA_EMPTY_IF_UNDEF (1<<1)
Definition at line 158 of file mroute.h.
MAPF_SHOW_ARP
#define MAPF_SHOW_ARP (1<<2)
Definition at line 159 of file mroute.h.
MAPF_SUBNET
#define MAPF_SUBNET (1<<0)
Definition at line 157 of file mroute.h.
MR_ADDR_ETHER
#define MR_ADDR_ETHER 1
Definition at line 61 of file mroute.h.
MR_ADDR_IPV4
#define MR_ADDR_IPV4 2
Definition at line 62 of file mroute.h.
MR_ADDR_IPV6
#define MR_ADDR_IPV6 3
Definition at line 63 of file mroute.h.
MR_ADDR_MASK
#define MR_ADDR_MASK 3
Definition at line 64 of file mroute.h.
MR_ADDR_NONE
#define MR_ADDR_NONE 0
Definition at line 60 of file mroute.h.
MR_ARP
#define MR_ARP 16
Definition at line 73 of file mroute.h.
MR_HELPER_NET_LEN
#define MR_HELPER_NET_LEN 129
Definition at line 126 of file mroute.h.
MR_MAX_ADDR_LEN
#define MR_MAX_ADDR_LEN 20
Definition at line 55 of file mroute.h.
MR_WITH_NETBITS
#define MR_WITH_NETBITS 8
Definition at line 70 of file mroute.h.
MR_WITH_PORT
#define MR_WITH_PORT 4
Definition at line 67 of file mroute.h.
MROUTE_EXTRACT_BCAST
#define MROUTE_EXTRACT_BCAST (1<<1)
Definition at line 39 of file mroute.h.
MROUTE_EXTRACT_IGMP
#define MROUTE_EXTRACT_IGMP (1<<3)
Definition at line 41 of file mroute.h.
MROUTE_EXTRACT_MCAST
#define MROUTE_EXTRACT_MCAST (1<<2)
Definition at line 40 of file mroute.h.
MROUTE_EXTRACT_SUCCEEDED
#define MROUTE_EXTRACT_SUCCEEDED (1<<0)
Definition at line 38 of file mroute.h.
MROUTE_SEC_EXTRACT_BCAST
#define MROUTE_SEC_EXTRACT_BCAST (1<<(1+MROUTE_SEC_SHIFT))
Definition at line 44 of file mroute.h.
MROUTE_SEC_EXTRACT_IGMP
#define MROUTE_SEC_EXTRACT_IGMP (1<<(3+MROUTE_SEC_SHIFT))
Definition at line 46 of file mroute.h.
MROUTE_SEC_EXTRACT_MCAST
#define MROUTE_SEC_EXTRACT_MCAST (1<<(2+MROUTE_SEC_SHIFT))
Definition at line 45 of file mroute.h.
MROUTE_SEC_EXTRACT_SUCCEEDED
#define MROUTE_SEC_EXTRACT_SUCCEEDED (1<<(0+MROUTE_SEC_SHIFT))
Definition at line 43 of file mroute.h.
MROUTE_SEC_SHIFT
#define MROUTE_SEC_SHIFT 4
Definition at line 48 of file mroute.h.
raw_addr
#define raw_addr mroute_union.raw_addr
v4
#define v4 mroute_union.v4
v4mappedv6
#define v4mappedv6 mroute_union.v4mappedv6
v6
#define v6 mroute_union.v6
Function Documentation
in_addr_t_from_mroute_addr()
static in_addr_t in_addr_t_from_mroute_addr (const struct mroute_addr * addr) inline static
Definition at line 252 of file mroute.h.
References mroute_addr::len, MR_ADDR_IPV4, MR_ADDR_MASK, mroute_addr::netbits, mroute_addr::type, and mroute_addr::v4.
mroute_addr_compare_function()
bool mroute_addr_compare_function (const void * key1, const void * key2)
Definition at line 441 of file mroute.c.
References mroute_addr_equal().
Referenced by multi_init().
mroute_addr_equal()
static bool mroute_addr_equal (const struct mroute_addr * a1, const struct mroute_addr * a2) inline static
Definition at line 212 of file mroute.h.
References mroute_addr::len, mroute_addr::netbits, mroute_addr::raw_addr, and mroute_addr::type.
Referenced by management_callback_kill_by_addr(), mroute_addr_compare_function(), multi_get_instance_by_virtual_addr(), and multi_learn_addr().
mroute_addr_hash_function()
uint32_t mroute_addr_hash_function (const void * key, uint32_t iv)
Definition at line 433 of file mroute.c.
References hash_func(), mroute_addr_hash_len(), and mroute_addr_hash_ptr().
Referenced by multi_init().
mroute_addr_hash_len()
static uint32_t mroute_addr_hash_len (const struct mroute_addr * a) inline static
Definition at line 237 of file mroute.h.
References mroute_addr::len.
Referenced by mroute_addr_hash_function().
mroute_addr_hash_ptr()
static const uint8_t* mroute_addr_hash_ptr (const struct mroute_addr * a) inline static
Definition at line 230 of file mroute.h.
References mroute_addr::type.
Referenced by mroute_addr_hash_function().
mroute_addr_init()
void mroute_addr_init (struct mroute_addr * addr)
Definition at line 41 of file mroute.c.
References CLEAR.
Referenced by multi_create_instance().
mroute_addr_mask_host_bits()
void mroute_addr_mask_host_bits (struct mroute_addr * ma)
Definition at line 393 of file mroute.c.
References ASSERT, in_addr_t, IPV4_NETMASK_HOST, MR_ADDR_IPV4, MR_ADDR_IPV6, MR_ADDR_MASK, mroute_addr::netbits, netbits_to_netmask(), mroute_addr::type, mroute_addr::v4, and mroute_addr::v6.
Referenced by multi_get_instance_by_virtual_addr(), and multi_learn_in6_addr().
mroute_addr_print()
const char* mroute_addr_print (const struct mroute_addr * ma, struct gc_arena * gc)
Definition at line 448 of file mroute.c.
References MAPF_IA_EMPTY_IF_UNDEF, and mroute_addr_print_ex().
Referenced by check_stale_routes(), learn_address_script(), mroute_learnable_address(), multi_create_instance(), multi_create_instance_tcp(), multi_get_create_instance_udp(), multi_get_instance_by_virtual_addr(), multi_instance_string(), multi_learn_addr(), multi_print_status(), multi_process_float(), multi_process_incoming_link(), and multi_reap_range().
mroute_addr_print_ex()
const char* mroute_addr_print_ex (const struct mroute_addr * ma, const unsigned int flags, struct gc_arena * gc)
Definition at line 455 of file mroute.c.
References alloc_buf_gc(), BSTR, buf_printf(), mroute_addr::ether, format_hex_ex(), IA_EMPTY_IF_UNDEF, IA_NET_ORDER, in_addr_t, MAPF_IA_EMPTY_IF_UNDEF, MAPF_SHOW_ARP, MAPF_SUBNET, MR_ADDR_ETHER, MR_ADDR_IPV4, MR_ADDR_IPV6, MR_ADDR_MASK, MR_ARP, MR_WITH_NETBITS, MR_WITH_PORT, mroute_addr::netbits, netbits_to_netmask(), print_in6_addr(), print_in_addr_t(), mroute_addr::type, mroute_addr::v4, mroute_addr::v4mappedv6, and mroute_addr::v6.
Referenced by mroute_addr_print(), multi_bcast(), multi_process_incoming_link(), and multi_process_incoming_tun().
mroute_addr_reset()
static void mroute_addr_reset (struct mroute_addr * ma) inline static
Definition at line 265 of file mroute.h.
References mroute_addr::len, MR_ADDR_NONE, and mroute_addr::type.
Referenced by multi_process_incoming_link(), and multi_process_incoming_tun().
mroute_extract_addr_ether()
unsigned int mroute_extract_addr_ether (struct mroute_addr * src, struct mroute_addr * dest, struct mroute_addr * esrc, struct mroute_addr * edest, uint16_t vid, const struct buffer * buf)
Definition at line 263 of file mroute.c.
References BLEN, BPTR, buf_advance(), openvpn_ethhdr::dest, dest, is_mac_mcast_addr(), mroute_copy_ether_to_addr(), mroute_extract_addr_ip(), MROUTE_EXTRACT_BCAST, MROUTE_EXTRACT_SUCCEEDED, MROUTE_SEC_SHIFT, OPENVPN_ETH_P_8021Q, OPENVPN_ETH_P_ARP, OPENVPN_ETH_P_IPV4, openvpn_ethhdr::proto, openvpn_8021qhdr::proto, SIZE_ETH_TO_8021Q_HDR, and openvpn_ethhdr::source.
Referenced by mroute_extract_addr_from_packet().
mroute_extract_addr_from_packet()
static unsigned int mroute_extract_addr_from_packet (struct mroute_addr * src, struct mroute_addr * dest, struct mroute_addr * esrc, struct mroute_addr * edest, uint16_t vid, const struct buffer * buf, int tunnel_type) inline static
Definition at line 190 of file mroute.h.
References dest, DEV_TYPE_TAP, DEV_TYPE_TUN, mroute_extract_addr_ether(), mroute_extract_addr_ip(), and verify_align_4.
Referenced by multi_process_incoming_link(), and multi_process_incoming_tun().
mroute_extract_addr_ip()
unsigned int mroute_extract_addr_ip (struct mroute_addr * src, struct mroute_addr * dest, const struct buffer * buf)
Definition at line 185 of file mroute.c.
References BLEN, BPTR, openvpn_iphdr::daddr, openvpn_ipv6hdr::daddr, dest, gc_free(), gc_new(), M_INFO, M_WARN, MROUTE_EXTRACT_IGMP, MROUTE_EXTRACT_MCAST, MROUTE_EXTRACT_SUCCEEDED, mroute_get_in6_addr(), mroute_get_in_addr_t(), mroute_is_mcast(), mroute_is_mcast_ipv6(), msg, OPENVPN_IPH_GET_VER, OPENVPN_IPPROTO_IGMP, print_in6_addr(), openvpn_iphdr::protocol, openvpn_iphdr::saddr, and openvpn_ipv6hdr::saddr.
Referenced by mroute_extract_addr_ether(), and mroute_extract_addr_from_packet().
mroute_extract_in_addr_t()
static void mroute_extract_in_addr_t (struct mroute_addr * dest, const in_addr_t src) inline static
Definition at line 243 of file mroute.h.
References dest, and MR_ADDR_IPV4.
Referenced by multi_init().
mroute_extract_openvpn_sockaddr()
bool mroute_extract_openvpn_sockaddr (struct mroute_addr * addr, const struct openvpn_sockaddr * osaddr, bool use_port)
Definition at line 336 of file mroute.c.
References openvpn_sockaddr::addr, openvpn_sockaddr::in4, openvpn_sockaddr::in6, mroute_addr::len, MR_ADDR_IPV4, MR_ADDR_IPV6, MR_WITH_PORT, mroute_addr::netbits, openvpn_sockaddr::sa, mroute_addr::type, mroute_addr::v4, and mroute_addr::v6.
Referenced by management_callback_kill_by_addr(), multi_get_create_instance_udp(), multi_learn_in_addr_t(), multi_process_float(), and multi_tcp_instance_specific_init().
mroute_helper_add_iroute46()
void mroute_helper_add_iroute46 (struct mroute_helper * mh, int netbits)
Definition at line 581 of file mroute.c.
References ASSERT, mroute_helper::cache_generation, MR_HELPER_NET_LEN, mroute_helper_regenerate(), and mroute_helper::net_len_refcount.
Referenced by multi_add_iroutes().
mroute_helper_del_iroute46()
void mroute_helper_del_iroute46 (struct mroute_helper * mh, int netbits)
Definition at line 596 of file mroute.c.
References ASSERT, mroute_helper::cache_generation, MR_HELPER_NET_LEN, mroute_helper_regenerate(), and mroute_helper::net_len_refcount.
Referenced by multi_del_iroutes().
mroute_helper_free()
void mroute_helper_free (struct mroute_helper * mh)
Definition at line 612 of file mroute.c.
Referenced by multi_uninit().
mroute_helper_init()
struct mroute_helper* mroute_helper_init (int ageable_ttl_secs)
Definition at line 543 of file mroute.c.
References mroute_helper::ageable_ttl_secs, and ALLOC_OBJ_CLEAR.
Referenced by multi_init().
mroute_learnable_address()
bool mroute_learnable_address (const struct mroute_addr * addr, struct gc_arena * gc)
Definition at line 67 of file mroute.c.
References D_MULTI_LOW, is_mac_mcast_maddr(), mroute_addr::len, MR_WITH_NETBITS, mroute_addr_print(), msg, mroute_addr::netbits, mroute_addr::raw_addr, and mroute_addr::type.
Referenced by multi_learn_addr().