OpenVPN: src/openvpnmsica/msica_arg.h File Reference
msica_arg.h File Reference
#include <windows.h>
#include <tchar.h>
#include "../tapctl/basic.h"
Data Structures
struct msica_arg
Argument list.
struct msica_arg_seq
Argument sequence.
Functions
void msica_arg_seq_init (_Inout_ struct msica_arg_seq *seq)
Initializes argument sequence.
void msica_arg_seq_free (_Inout_ struct msica_arg_seq *seq)
Frees argument sequence.
void msica_arg_seq_add_head (_Inout_ struct msica_arg_seq *seq, _In_z_ LPCTSTR argument)
Inserts argument to the beginning of the argument sequence.
void msica_arg_seq_add_tail (_Inout_ struct msica_arg_seq *seq, _Inout_ LPCTSTR argument)
Appends argument to the end of the argument sequence.
LPTSTR msica_arg_seq_join (_In_ const struct msica_arg_seq *seq)
Join arguments of the argument sequence into a space delimited string.
Function Documentation
msica_arg_seq_add_head()
void msica_arg_seq_add_head (_Inout_ struct msica_arg_seq * seq, _In_z_ LPCTSTR argument)
Inserts argument to the beginning of the argument sequence.
Parameters
seq Pointer to the argument sequence
argument Zero-terminated argument string to insert.
Definition at line 57 of file msica_arg.c.
References M_FATAL, msg, msica_arg::next, and msica_arg::val.
Referenced by schedule_adapter_create(), and schedule_adapter_delete().
msica_arg_seq_add_tail()
void msica_arg_seq_add_tail (_Inout_ struct msica_arg_seq * seq, _Inout_ LPCTSTR argument)
Appends argument to the end of the argument sequence.
Parameters
seq Pointer to the argument sequence
argument Zero-terminated argument string to append.
Definition at line 78 of file msica_arg.c.
References M_FATAL, msg, msica_arg::next, and msica_arg::val.
Referenced by EvaluateTUNTAPAdapters(), schedule_adapter_create(), and schedule_adapter_delete().
msica_arg_seq_free()
void msica_arg_seq_free (_Inout_ struct msica_arg_seq * seq)
Frees argument sequence.
Parameters
seq Pointer to the argument sequence
Definition at line 44 of file msica_arg.c.
References msica_arg::next.
Referenced by EvaluateTUNTAPAdapters().
msica_arg_seq_init()
void msica_arg_seq_init (_Inout_ struct msica_arg_seq * seq)
Initializes argument sequence.
Parameters
seq Pointer to uninitialized argument sequence
Definition at line 36 of file msica_arg.c.
Referenced by EvaluateTUNTAPAdapters().
msica_arg_seq_join()
LPTSTR msica_arg_seq_join (_In_ const struct msica_arg_seq * seq)
Join arguments of the argument sequence into a space delimited string.
Parameters
seq Pointer to the argument sequence
Returns
Joined argument string. Must be released with free() after use.
Definition at line 96 of file msica_arg.c.
References M_FATAL, msg, and msica_arg::next.
Referenced by setup_sequence().