OpenVPN: src/openvpnmsica/msiex.h File Reference
msiex.h File Reference
#include <windows.h>
#include <msi.h>
#include "../tapctl/basic.h"
Functions
UINT msi_get_string (_In_ MSIHANDLE hInstall, _In_z_ LPCTSTR szName, _Out_ LPTSTR *pszValue)
Gets MSI property value.
UINT msi_get_record_string (_In_ MSIHANDLE hRecord, _In_ unsigned int iField, _Out_ LPTSTR *pszValue)
Gets MSI record string value.
UINT msi_format_record (_In_ MSIHANDLE hInstall, _In_ MSIHANDLE hRecord, _Out_ LPTSTR *pszValue)
Formats MSI record.
UINT msi_format_field (_In_ MSIHANDLE hInstall, _In_ MSIHANDLE hRecord, _In_ unsigned int iField, _Out_ LPTSTR *pszValue)
Formats MSI record field.
Function Documentation
msi_format_field()
UINT msi_format_field (_In_ MSIHANDLE hInstall, _In_ MSIHANDLE hRecord, _In_ unsigned int iField, _Out_ LPTSTR * pszValue)
Formats MSI record field.
Parameters
hInstall Handle to the installation. This may be omitted, in which case only the record field parameters are processed and properties are not available for substitution.
hRecord Handle to the field record
iField Field index
pszValue Pointer to string to retrieve formatted value. The string must be released with free() after use.
Returns
ERROR_SUCCESS on success; Win32 error code otherwise
Definition at line 214 of file msiex.c.
References M_ERRNO, M_NONFATAL, msg, msi_format_record(), and msi_get_record_string().
Referenced by EvaluateTUNTAPAdapters().
msi_format_record()
UINT msi_format_record (_In_ MSIHANDLE hInstall, _In_ MSIHANDLE hRecord, _Out_ LPTSTR * pszValue)
Formats MSI record.
Parameters
hInstall Handle to the installation. This may be omitted, in which case only the record field parameters are processed and properties are not available for substitution.
hRecord Handle to the record to format. The template string must be stored in record field 0 followed by referenced data parameters.
pszValue Pointer to string to retrieve formatted value. The string must be released with free() after use.
Returns
ERROR_SUCCESS on success; Win32 error code otherwise
Definition at line 156 of file msiex.c.
References M_ERRNO, M_FATAL, M_NONFATAL, and msg.
Referenced by msi_format_field().
msi_get_record_string()
UINT msi_get_record_string (_In_ MSIHANDLE hRecord, _In_ unsigned int iField, _Out_ LPTSTR * pszValue)
Gets MSI record string value.
Parameters
hRecord Handle to the record
iField Field index
pszValue Pointer to string to retrieve field value. The string must be released with free() after use.
Returns
ERROR_SUCCESS on success; Win32 error code otherwise
Definition at line 98 of file msiex.c.
References M_ERRNO, M_FATAL, M_NONFATAL, and msg.
Referenced by EvaluateTUNTAPAdapters(), and msi_format_field().
msi_get_string()
UINT msi_get_string (_In_ MSIHANDLE hInstall, _In_z_ LPCTSTR szName, _Out_ LPTSTR * pszValue)
Gets MSI property value.
Parameters
hInstall Handle to the installation provided to the DLL custom action
szName Property name
pszValue Pointer to string to retrieve property value. The string must be released with free() after use.
Returns
ERROR_SUCCESS on success; Win32 error code otherwise
Definition at line 40 of file msiex.c.
References M_ERRNO, M_FATAL, M_NONFATAL, and msg.
Referenced by ProcessDeferredAction().