OpenVPN: src/openvpn/mss.c File Reference
mss.c File Reference
#include "syshead.h"
#include "error.h"
#include "mss.h"
#include "memdbg.h"
Functions
void mss_fixup_ipv4 (struct buffer *buf, int maxmss)
void mss_fixup_ipv6 (struct buffer *buf, int maxmss)
void mss_fixup_dowork (struct buffer *buf, uint16_t maxmss)
Function Documentation
mss_fixup_dowork()
void mss_fixup_dowork (struct buffer * buf, uint16_t maxmss)
Definition at line 143 of file mss.c.
References ADJUST_CHECKSUM, BLEN, BPTR, openvpn_tcphdr::check, D_MSS, dmsg, openvpn_tcphdr::doff_res, OPENVPN_TCPH_GET_DOFF, OPENVPN_TCPOLEN_MAXSEG, OPENVPN_TCPOPT_EOL, OPENVPN_TCPOPT_MAXSEG, OPENVPN_TCPOPT_NOP, and verify_align_4.
Referenced by mss_fixup_ipv4(), and mss_fixup_ipv6().
mss_fixup_ipv4()
void mss_fixup_ipv4 (struct buffer * buf, int maxmss)
Definition at line 46 of file mss.c.
References BLEN, BPTR, buf_advance(), openvpn_tcphdr::flags, openvpn_iphdr::frag_off, mss_fixup_dowork(), OPENVPN_IP_OFFMASK, OPENVPN_IPH_GET_LEN, OPENVPN_IPPROTO_TCP, OPENVPN_TCPH_SYN_MASK, openvpn_iphdr::protocol, openvpn_iphdr::tot_len, verify_align_4, and openvpn_iphdr::version_len.
Referenced by process_ip_header().
mss_fixup_ipv6()
void mss_fixup_ipv6 (struct buffer * buf, int maxmss)
Definition at line 86 of file mss.c.
References BLEN, BPTR, buf_advance(), openvpn_tcphdr::flags, mss_fixup_dowork(), openvpn_ipv6hdr::nexthdr, OPENVPN_IPPROTO_TCP, OPENVPN_TCPH_SYN_MASK, openvpn_ipv6hdr::payload_len, and verify_align_4.
Referenced by process_ip_header().