OpenVPN: src/openvpn/mtcp.h File Reference
mtcp.h File Reference
#include "event.h"
Data Structures
struct multi_tcp
Functions
struct multi_tcp * multi_tcp_init (int maxevents, int *maxclients)
void multi_tcp_free (struct multi_tcp *mtcp)
void multi_tcp_dereference_instance (struct multi_tcp *mtcp, struct multi_instance *mi)
bool multi_tcp_instance_specific_init (struct multi_context *m, struct multi_instance *mi)
void multi_tcp_instance_specific_free (struct multi_instance *mi)
void multi_tcp_link_out_deferred (struct multi_context *m, struct multi_instance *mi)
void tunnel_server_tcp (struct context *top)
Main event loop for OpenVPN in TCP server mode.
void multi_tcp_delete_event (struct multi_tcp *mtcp, event_t event)
Function Documentation
multi_tcp_delete_event()
void multi_tcp_delete_event (struct multi_tcp * mtcp, event_t event)
Definition at line 218 of file mtcp.c.
References multi_tcp::es, and event_del().
Referenced by management_delete_event().
multi_tcp_dereference_instance()
void multi_tcp_dereference_instance (struct multi_tcp * mtcp, struct multi_instance * mi)
Definition at line 241 of file mtcp.c.
References context::c2, multi_instance::context, multi_tcp::es, event_del(), context_2::link_socket, multi_tcp::n_esr, socket_event_handle(), and multi_instance::socket_set_called.
Referenced by multi_close_instance().
multi_tcp_free()
void multi_tcp_free (struct multi_tcp * mtcp)
Definition at line 227 of file mtcp.c.
References multi_tcp::es, multi_tcp::esr, and event_free().
Referenced by multi_uninit().
multi_tcp_init()
struct multi_tcp* multi_tcp_init (int maxevents, int * maxclients)
Definition at line 199 of file mtcp.c.
References ALLOC_ARRAY, ALLOC_OBJ_CLEAR, ASSERT, BASE_N_EVENTS, D_MULTI_LOW, multi_tcp::es, multi_tcp::esr, event_set_init(), max_int(), multi_tcp::maxevents, min_int(), msg, MTCP_SIG, and wait_signal().
Referenced by multi_init().
multi_tcp_instance_specific_free()
void multi_tcp_instance_specific_free (struct multi_instance * mi)
Definition at line 193 of file mtcp.c.
References mbuf_free(), and multi_instance::tcp_link_out_deferred.
Referenced by multi_close_instance().
multi_tcp_instance_specific_init()
bool multi_tcp_instance_specific_init (struct multi_context * m, struct multi_instance * mi)
Definition at line 173 of file mtcp.c.
References link_socket_addr::actual, openvpn_sockaddr::addr, ASSERT, context::c2, multi_instance::context, D_MULTI_ERRORS, link_socket_actual::dest, link_socket::info, context_2::link_socket, LS_MODE_TCP_ACCEPT_FROM, link_socket_info::lsa, mbuf_init(), link_socket::mode, mroute_extract_openvpn_sockaddr(), msg, options::n_bcast_buf, context::options, multi_instance::real, openvpn_sockaddr::sa, multi_instance::tcp_link_out_deferred, and multi_context::top.
Referenced by multi_create_instance().
multi_tcp_link_out_deferred()
void multi_tcp_link_out_deferred (struct multi_context * m, struct multi_instance * mi)
tunnel_server_tcp()
void tunnel_server_tcp (struct context * top)
Main event loop for OpenVPN in TCP server mode.
Parameters
top - Top-level context structure.
Definition at line 784 of file mtcp.c.
References context::c2, CC_HARD_USR1_TO_HUP, close_instance(), CM_TOP, context_clear_2(), D_MULTI_ERRORS, context::es, init_instance_handle_signals(), init_management_callback_multi(), initialization_sequence_completed(), IS_SIG, ISC_SERVER, M_ERRNO, MC_SINGLE_THREADED, context::mode, msg, multi_context::mtcp, MULTI_CHECK_SIG, multi_get_timeout(), multi_ifconfig_pool_persist(), multi_init(), multi_process_per_second_timers(), multi_tcp_action(), multi_tcp_process_io(), multi_tcp_wait(), multi_top_free(), multi_top_init(), multi_uninit(), PERF_EVENT_LOOP, perf_pop(), perf_push(), status, TA_TIMEOUT, context_2::timeval, multi_context::top, and uninit_management_callback().
Referenced by tunnel_server().