OpenVPN: src/openvpn/mtu.h File Reference
mtu.h File Reference
#include "buffer.h"
Data Structures
struct frame
Packet geometry parameters.
Macros
#define ETHERNET_MTU 1500
#define TUN_MTU_MIN 100
#define LINK_MTU_DEFAULT 1500
#define TUN_MTU_DEFAULT 1500
#define TAP_MTU_EXTRA_DEFAULT 32
#define MSSFIX_DEFAULT 1450
#define PAYLOAD_ALIGN 4
#define FRAME_HEADROOM_MARKER_DECRYPT (1<<0)
#define FRAME_HEADROOM_MARKER_FRAGMENT (1<<1)
#define FRAME_HEADROOM_MARKER_READ_LINK (1<<2)
#define FRAME_HEADROOM_MARKER_READ_STREAM (1<<3)
#define EXTRA_FRAME(f) ((f)->extra_frame)
#define TUN_LINK_DELTA(f) ((f)->extra_frame + (f)->extra_tun)
#define TUN_MTU_SIZE(f) ((f)->link_mtu - TUN_LINK_DELTA(f))
#define TUN_MTU_SIZE_DYNAMIC(f) ((f)->link_mtu_dynamic - TUN_LINK_DELTA(f))
#define PAYLOAD_SIZE(f) ((f)->link_mtu - (f)->extra_frame)
#define PAYLOAD_SIZE_DYNAMIC(f) ((f)->link_mtu_dynamic - (f)->extra_frame)
#define EXPANDED_SIZE(f) ((f)->link_mtu)
#define EXPANDED_SIZE_DYNAMIC(f) ((f)->link_mtu_dynamic)
#define EXPANDED_SIZE_MIN(f) (TUN_MTU_MIN + TUN_LINK_DELTA(f))
#define MAX_RW_SIZE_TUN(f) (PAYLOAD_SIZE(f))
#define MAX_RW_SIZE_LINK(f) (EXPANDED_SIZE(f) + (f)->extra_link)
#define FRAME_HEADROOM_BASE(f) (TUN_LINK_DELTA(f) + (f)->extra_buffer + (f)->extra_link)
#define FRAME_HEADROOM(f) frame_headroom(f, 0)
#define FRAME_HEADROOM_ADJ(f, fm) frame_headroom(f, fm)
#define BUF_SIZE(f) (TUN_MTU_SIZE(f) + FRAME_HEADROOM_BASE(f) * 2)
#define SET_MTU_TUN (1<<0) /* use tun/tap rather than link sizing */
#define SET_MTU_UPPER_BOUND (1<<1) /* only decrease dynamic MTU */
Functions
void frame_finalize (struct frame *frame, bool link_mtu_defined, int link_mtu, bool tun_mtu_defined, int tun_mtu)
void frame_subtract_extra (struct frame *frame, const struct frame *src)
void frame_print (const struct frame *frame, int level, const char *prefix)
void set_mtu_discover_type (int sd, int mtu_type, sa_family_t proto_af)
int translate_mtu_discover_type_name (const char *name)
void frame_set_mtu_dynamic (struct frame *frame, int mtu, unsigned int flags)
void alloc_buf_sock_tun (struct buffer *buf, const struct frame *frame, const bool tuntap_buffer, const unsigned int align_mask)
void frame_init_mssfix (struct frame *frame, const struct options *options)
Set the –mssfix option.
static int frame_headroom (const struct frame *f, const unsigned int flag_mask)
static void frame_add_to_link_mtu (struct frame *frame, const int increment)
static void frame_add_to_extra_frame (struct frame *frame, const unsigned int increment)
static void frame_remove_from_extra_frame (struct frame *frame, const unsigned int decrement)
static void frame_add_to_extra_tun (struct frame *frame, const int increment)
static void frame_add_to_extra_link (struct frame *frame, const int increment)
static void frame_add_to_extra_buffer (struct frame *frame, const int increment)
static void frame_add_to_align_adjust (struct frame *frame, const int increment)
static void frame_align_to_extra_frame (struct frame *frame)
static void frame_or_align_flags (struct frame *frame, const unsigned int flag_mask)
static bool frame_defined (const struct frame *frame)
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE (f) (TUN_MTU_SIZE(f) + FRAME_HEADROOM_BASE(f) * 2)
Definition at line 194 of file mtu.h.
ETHERNET_MTU
#define ETHERNET_MTU 1500
Definition at line 54 of file mtu.h.
EXPANDED_SIZE
#define EXPANDED_SIZE (f) ((f)->link_mtu)
Definition at line 172 of file mtu.h.
EXPANDED_SIZE_DYNAMIC
#define EXPANDED_SIZE_DYNAMIC (f) ((f)->link_mtu_dynamic)
Definition at line 173 of file mtu.h.
EXPANDED_SIZE_MIN
#define EXPANDED_SIZE_MIN (f) (TUN_MTU_MIN + TUN_LINK_DELTA(f))
Definition at line 174 of file mtu.h.
EXTRA_FRAME
#define EXTRA_FRAME (f) ((f)->extra_frame)
Definition at line 145 of file mtu.h.
FRAME_HEADROOM
#define FRAME_HEADROOM (f) frame_headroom(f, 0)
Definition at line 187 of file mtu.h.
FRAME_HEADROOM_ADJ
#define FRAME_HEADROOM_ADJ (f, fm) frame_headroom(f, fm)
Definition at line 188 of file mtu.h.
FRAME_HEADROOM_BASE
#define FRAME_HEADROOM_BASE (f) (TUN_LINK_DELTA(f) + (f)->extra_buffer + (f)->extra_link)
Definition at line 186 of file mtu.h.
FRAME_HEADROOM_MARKER_DECRYPT
#define FRAME_HEADROOM_MARKER_DECRYPT (1<<0)
Definition at line 129 of file mtu.h.
FRAME_HEADROOM_MARKER_FRAGMENT
#define FRAME_HEADROOM_MARKER_FRAGMENT (1<<1)
Definition at line 130 of file mtu.h.
FRAME_HEADROOM_MARKER_READ_LINK
#define FRAME_HEADROOM_MARKER_READ_LINK (1<<2)
Definition at line 131 of file mtu.h.
FRAME_HEADROOM_MARKER_READ_STREAM
#define FRAME_HEADROOM_MARKER_READ_STREAM (1<<3)
Definition at line 132 of file mtu.h.
LINK_MTU_DEFAULT
#define LINK_MTU_DEFAULT 1500
Definition at line 65 of file mtu.h.
MAX_RW_SIZE_LINK
#define MAX_RW_SIZE_LINK (f) (EXPANDED_SIZE(f) + (f)->extra_link)
Definition at line 181 of file mtu.h.
MAX_RW_SIZE_TUN
#define MAX_RW_SIZE_TUN (f) (PAYLOAD_SIZE(f))
Definition at line 180 of file mtu.h.
MSSFIX_DEFAULT
#define MSSFIX_DEFAULT 1450
Definition at line 80 of file mtu.h.
PAYLOAD_ALIGN
#define PAYLOAD_ALIGN 4
Definition at line 86 of file mtu.h.
PAYLOAD_SIZE
#define PAYLOAD_SIZE (f) ((f)->link_mtu - (f)->extra_frame)
Definition at line 165 of file mtu.h.
PAYLOAD_SIZE_DYNAMIC
#define PAYLOAD_SIZE_DYNAMIC (f) ((f)->link_mtu_dynamic - (f)->extra_frame)
Definition at line 166 of file mtu.h.
SET_MTU_TUN
#define SET_MTU_TUN (1<<0) /* use tun/tap rather than link sizing */
Definition at line 220 of file mtu.h.
SET_MTU_UPPER_BOUND
#define SET_MTU_UPPER_BOUND (1<<1) /* only decrease dynamic MTU */
Definition at line 221 of file mtu.h.
TAP_MTU_EXTRA_DEFAULT
#define TAP_MTU_EXTRA_DEFAULT 32
Definition at line 75 of file mtu.h.
TUN_LINK_DELTA
#define TUN_LINK_DELTA (f) ((f)->extra_frame + (f)->extra_tun)
Definition at line 151 of file mtu.h.
TUN_MTU_DEFAULT
#define TUN_MTU_DEFAULT 1500
Definition at line 70 of file mtu.h.
TUN_MTU_MIN
#define TUN_MTU_MIN 100
Definition at line 60 of file mtu.h.
TUN_MTU_SIZE
#define TUN_MTU_SIZE (f) ((f)->link_mtu - TUN_LINK_DELTA(f))
Definition at line 156 of file mtu.h.
TUN_MTU_SIZE_DYNAMIC
#define TUN_MTU_SIZE_DYNAMIC (f) ((f)->link_mtu_dynamic - TUN_LINK_DELTA(f))
Definition at line 157 of file mtu.h.
Function Documentation
alloc_buf_sock_tun()
void alloc_buf_sock_tun (struct buffer * buf, const struct frame * frame, const bool tuntap_buffer, const unsigned int align_mask)
Definition at line 43 of file mtu.c.
References alloc_buf(), ASSERT, buf_init, buf_safe(), BUF_SIZE, FRAME_HEADROOM_ADJ, buffer::len, MAX_RW_SIZE_LINK, and MAX_RW_SIZE_TUN.
Referenced by overlapped_io_init(), and socket_frame_init().
frame_add_to_align_adjust()
static void frame_add_to_align_adjust (struct frame * frame, const int increment) inline static
Definition at line 304 of file mtu.h.
References frame::align_adjust.
Referenced by do_init_frame().
frame_add_to_extra_buffer()
static void frame_add_to_extra_buffer (struct frame * frame, const int increment) inline static
Definition at line 298 of file mtu.h.
References frame::extra_buffer.
Referenced by frame_finalize_options().
frame_add_to_extra_frame()
static void frame_add_to_extra_frame (struct frame * frame, const unsigned int increment) inline static
Definition at line 274 of file mtu.h.
References frame::extra_frame.
Referenced by calc_options_string_link_mtu(), crypto_adjust_frame_parameters(), do_deferred_options(), do_init_crypto_tls(), fragment_init(), reliable_ack_adjust_frame_parameters(), socket_adjust_frame_parameters(), tls_adjust_frame_parameters(), tls_crypt_adjust_frame_parameters(), and tls_init_control_channel_frame_parameters().
frame_add_to_extra_link()
static void frame_add_to_extra_link (struct frame * frame, const int increment) inline static
Definition at line 292 of file mtu.h.
References frame::extra_link.
Referenced by do_init_frame(), and socks_adjust_frame_parameters().
frame_add_to_extra_tun()
static void frame_add_to_extra_tun (struct frame * frame, const int increment) inline static
Definition at line 286 of file mtu.h.
References frame::extra_tun.
Referenced by tun_adjust_frame_parameters().
frame_add_to_link_mtu()
static void frame_add_to_link_mtu (struct frame * frame, const int increment) inline static
Definition at line 268 of file mtu.h.
References frame::link_mtu.
Referenced by do_deferred_options().
frame_align_to_extra_frame()
static void frame_align_to_extra_frame (struct frame * frame) inline static
Definition at line 310 of file mtu.h.
References frame::align_adjust, frame::extra_frame, and frame::extra_link.
Referenced by frame_finalize_options().
frame_defined()
static bool frame_defined (const struct frame * frame) inline static
Definition at line 322 of file mtu.h.
References frame::link_mtu.
frame_finalize()
void frame_finalize (struct frame * frame, bool link_mtu_defined, int link_mtu, bool tun_mtu_defined, int tun_mtu)
Definition at line 56 of file mtu.c.
References ASSERT, frame_print(), frame::link_mtu, frame::link_mtu_dynamic, M_FATAL, M_WARN, msg, TUN_LINK_DELTA, TUN_MTU_MIN, and TUN_MTU_SIZE.
Referenced by calc_options_string_link_mtu(), frame_finalize_options(), and tls_session_update_crypto_params().
frame_headroom()
static int frame_headroom (const struct frame * f, const unsigned int flag_mask) inline static
Definition at line 255 of file mtu.h.
References http-client::f, FRAME_HEADROOM_BASE, and PAYLOAD_ALIGN.
frame_init_mssfix()
void frame_init_mssfix (struct frame * frame, const struct options * options)
Set the –mssfix option.
Definition at line 130 of file mtu.c.
References options::ce, frame_set_mtu_dynamic(), connection_entry::mssfix, and SET_MTU_UPPER_BOUND.
Referenced by init_instance(), and tls_session_update_crypto_params().
frame_or_align_flags()
static void frame_or_align_flags (struct frame * frame, const unsigned int flag_mask) inline static
Definition at line 316 of file mtu.h.
References frame::align_flags.
Referenced by do_init_frame(), and frame_finalize_options().
frame_print()
void frame_print (const struct frame * frame, int level, const char * prefix)
Definition at line 139 of file mtu.c.
References frame::align_adjust, frame::align_flags, alloc_buf_gc(), buf_printf(), buffer::data, frame::extra_buffer, frame::extra_frame, frame::extra_link, frame::extra_tun, gc_free(), gc_new(), frame::link_mtu, frame::link_mtu_dynamic, and msg.
Referenced by do_init_finalize_tls_frame(), do_print_data_channel_mtu_parms(), frame_finalize(), and tls_session_update_crypto_params().
frame_remove_from_extra_frame()
static void frame_remove_from_extra_frame (struct frame * frame, const unsigned int decrement) inline static
Definition at line 280 of file mtu.h.
References frame::extra_frame.
Referenced by calc_options_string_link_mtu(), and tls_session_update_crypto_params().
frame_set_mtu_dynamic()
void frame_set_mtu_dynamic (struct frame * frame, int mtu, unsigned int flags)
Definition at line 87 of file mtu.c.
References ASSERT, constrain_int(), D_MTU_DEBUG, dmsg, EXPANDED_SIZE, EXPANDED_SIZE_MIN, frame::link_mtu_dynamic, SET_MTU_TUN, SET_MTU_UPPER_BOUND, and TUN_LINK_DELTA.
Referenced by do_init_fragment(), do_open_tun(), frame_adjust_path_mtu(), frame_init_mssfix(), and tls_session_update_crypto_params().
frame_subtract_extra()
void frame_subtract_extra (struct frame * frame, const struct frame * src)
Definition at line 123 of file mtu.c.
References frame::extra_frame, and frame::extra_tun.
Referenced by do_init_frame().
set_mtu_discover_type()
void set_mtu_discover_type (int sd, int mtu_type, sa_family_t proto_af)
Definition at line 169 of file mtu.c.
References M_ERR, M_FATAL, msg, and MTUDISC_NOT_SUPPORTED_MSG.
Referenced by phase2_set_socket_flags().
translate_mtu_discover_type_name()
int translate_mtu_discover_type_name (const char * name)
Definition at line 205 of file mtu.c.
References M_FATAL, msg, and MTUDISC_NOT_SUPPORTED_MSG.
Referenced by add_option().