OpenVPN: src/openvpn/mtu.c File Reference
mtu.c File Reference
#include "syshead.h"
#include "common.h"
#include "buffer.h"
#include "error.h"
#include "integer.h"
#include "mtu.h"
#include "options.h"
#include "memdbg.h"
Macros
#define MTUDISC_NOT_SUPPORTED_MSG "--mtu-disc is not supported on this OS"
Functions
void alloc_buf_sock_tun (struct buffer *buf, const struct frame *frame, const bool tuntap_buffer, const unsigned int align_mask)
void frame_finalize (struct frame *frame, bool link_mtu_defined, int link_mtu, bool tun_mtu_defined, int tun_mtu)
void frame_set_mtu_dynamic (struct frame *frame, int mtu, unsigned int flags)
void frame_subtract_extra (struct frame *frame, const struct frame *src)
void frame_init_mssfix (struct frame *frame, const struct options *options)
Set the –mssfix option.
void frame_print (const struct frame *frame, int level, const char *prefix)
void set_mtu_discover_type (int sd, int mtu_type, sa_family_t proto_af)
int translate_mtu_discover_type_name (const char *name)
Macro Definition Documentation
MTUDISC_NOT_SUPPORTED_MSG
#define MTUDISC_NOT_SUPPORTED_MSG "--mtu-disc is not supported on this OS"
Definition at line 166 of file mtu.c.
Function Documentation
alloc_buf_sock_tun()
void alloc_buf_sock_tun (struct buffer * buf, const struct frame * frame, const bool tuntap_buffer, const unsigned int align_mask)
Definition at line 43 of file mtu.c.
References alloc_buf(), ASSERT, buf_init, buf_safe(), BUF_SIZE, FRAME_HEADROOM_ADJ, buffer::len, MAX_RW_SIZE_LINK, and MAX_RW_SIZE_TUN.
Referenced by overlapped_io_init(), and socket_frame_init().
frame_finalize()
void frame_finalize (struct frame * frame, bool link_mtu_defined, int link_mtu, bool tun_mtu_defined, int tun_mtu)
Definition at line 56 of file mtu.c.
References ASSERT, frame_print(), frame::link_mtu, frame::link_mtu_dynamic, M_FATAL, M_WARN, msg, TUN_LINK_DELTA, TUN_MTU_MIN, and TUN_MTU_SIZE.
Referenced by calc_options_string_link_mtu(), frame_finalize_options(), and tls_session_update_crypto_params().
frame_init_mssfix()
void frame_init_mssfix (struct frame * frame, const struct options * options)
Set the –mssfix option.
Definition at line 130 of file mtu.c.
References options::ce, frame_set_mtu_dynamic(), connection_entry::mssfix, and SET_MTU_UPPER_BOUND.
Referenced by init_instance(), and tls_session_update_crypto_params().
frame_print()
void frame_print (const struct frame * frame, int level, const char * prefix)
Definition at line 139 of file mtu.c.
References frame::align_adjust, frame::align_flags, alloc_buf_gc(), buf_printf(), buffer::data, frame::extra_buffer, frame::extra_frame, frame::extra_link, frame::extra_tun, gc_free(), gc_new(), frame::link_mtu, frame::link_mtu_dynamic, and msg.
Referenced by do_init_finalize_tls_frame(), do_print_data_channel_mtu_parms(), frame_finalize(), and tls_session_update_crypto_params().
frame_set_mtu_dynamic()
void frame_set_mtu_dynamic (struct frame * frame, int mtu, unsigned int flags)
Definition at line 87 of file mtu.c.
References ASSERT, constrain_int(), D_MTU_DEBUG, dmsg, EXPANDED_SIZE, EXPANDED_SIZE_MIN, frame::link_mtu_dynamic, SET_MTU_TUN, SET_MTU_UPPER_BOUND, and TUN_LINK_DELTA.
Referenced by do_init_fragment(), do_open_tun(), frame_adjust_path_mtu(), frame_init_mssfix(), and tls_session_update_crypto_params().
frame_subtract_extra()
void frame_subtract_extra (struct frame * frame, const struct frame * src)
Definition at line 123 of file mtu.c.
References frame::extra_frame, and frame::extra_tun.
Referenced by do_init_frame().
set_mtu_discover_type()
void set_mtu_discover_type (int sd, int mtu_type, sa_family_t proto_af)
Definition at line 169 of file mtu.c.
References M_ERR, M_FATAL, msg, and MTUDISC_NOT_SUPPORTED_MSG.
Referenced by phase2_set_socket_flags().
translate_mtu_discover_type_name()
int translate_mtu_discover_type_name (const char * name)
Definition at line 205 of file mtu.c.
References M_FATAL, msg, and MTUDISC_NOT_SUPPORTED_MSG.
Referenced by add_option().