OpenVPN: src/openvpn/mudp.c File Reference
mudp.c File Reference
#include "syshead.h"
#include "multi.h"
#include <inttypes.h>
#include "forward.h"
#include "memdbg.h"
Functions
struct multi_instance * multi_get_create_instance_udp (struct multi_context *m, bool *floated)
Get, and if necessary create, the multi_instance associated with a packet's source address.
static void multi_process_outgoing_link (struct multi_context *m, const unsigned int mpp_flags)
static void multi_process_io_udp (struct multi_context *m)
static unsigned int p2mp_iow_flags (const struct multi_context *m)
static void tunnel_server_udp_single_threaded (struct context *top)
Main event loop for OpenVPN in UDP server mode.
void tunnel_server_udp (struct context *top)
Main event loop wrapper function for OpenVPN in UDP server mode.
Function Documentation
multi_get_create_instance_udp()
struct multi_instance* multi_get_create_instance_udp (struct multi_context * m, bool * floated)
Get, and if necessary create, the multi_instance associated with a packet's source address.
This function extracts the source address of a recently read packet from m->top.c2.from and uses that source address as a hash key for the hash table m->hash. If an entry exists, this function returns it. If no entry exists, this function handles its creation, and if successful, returns the newly created instance.
Parameters
m - The single multi_context structure.
Returns
A pointer to a multi_instance if one already existed for the packet's source address or if one was a newly created successfully. NULL if one did not yet exist and a new one was not created.
Definition at line 49 of file mudp.c.
References ASSERT, BPTR, context_2::buf, context::c2, check_debug_level(), multi_instance::context, D_MULTI_DEBUG, D_MULTI_ERRORS, D_MULTI_MEDIUM, link_socket_actual::dest, multi_instance::did_real_hash, dmsg, frequency_limit_event_allowed(), context_2::from, multi_instance::gc, gc_free(), gc_new(), multi_instance::halt, multi_context::hash, hash_add_fast(), hash_bucket(), hash_lookup_fast(), hash_value(), multi_context::instances, buffer::len, link_socket_actual_match(), multi_context::max_clients, MAX_PEER_ID, mroute_addr_print(), mroute_extract_openvpn_sockaddr(), msg, multi_create_instance(), multi_context::new_connection_limiter, P_DATA_V2, P_OPCODE_SHIFT, tls_multi::peer_id, multi_instance::real, status, context_2::tls_auth_standalone, context_2::tls_multi, tls_pre_decrypt_lite(), multi_context::top, ungenerate_prefix(), and hash_element::value.
Referenced by multi_process_incoming_link().
multi_process_io_udp()
static void multi_process_io_udp (struct multi_context * m) static
Definition at line 172 of file mudp.c.
References ASSERT, context::c2, context_2::event_set_status, context_2::fast_io, IS_SIG, management_io(), MANAGEMENT_READ, MANAGEMENT_WRITE, MPP_CLOSE_ON_SIGNAL, MPP_CONDITIONAL_PRE_SELECT, MPP_PRE_SELECT, multi_process_incoming_link(), multi_process_incoming_tun(), multi_process_outgoing_link(), multi_process_outgoing_tun(), read_incoming_link(), read_incoming_tun(), SOCKET_READ, SOCKET_WRITE, status, multi_context::top, TUN_READ, and TUN_WRITE.
Referenced by tunnel_server_udp_single_threaded().
multi_process_outgoing_link()
static void multi_process_outgoing_link (struct multi_context * m, const unsigned int mpp_flags) inline static
Definition at line 159 of file mudp.c.
References multi_process_outgoing_link_dowork(), and multi_process_outgoing_link_pre().
Referenced by multi_process_io_udp().
p2mp_iow_flags()
static unsigned int p2mp_iow_flags (const struct multi_context * m) inline static
Definition at line 257 of file mudp.c.
References context::c1, multi_instance::context, IOW_MBUF, IOW_READ, IOW_READ_TUN, IOW_TO_LINK, IOW_TO_TUN, IOW_WAIT_SIGNAL, LINK_OUT, multi_context::mbuf, mbuf_defined(), multi_context::pending, multi_context::top, TUN_OUT, context_1::tuntap, and tuntap_ring_empty().
Referenced by tunnel_server_udp_single_threaded().
tunnel_server_udp()
void tunnel_server_udp (struct context * top)
Main event loop wrapper function for OpenVPN in UDP server mode.
This function simply calls tunnel_server_udp_single_threaded().
Parameters
top - Top-level context structure.
Definition at line 380 of file mudp.c.
References multi_context::top, and tunnel_server_udp_single_threaded().
Referenced by tunnel_server().
tunnel_server_udp_single_threaded()
static void tunnel_server_udp_single_threaded (struct context * top) static
Main event loop for OpenVPN in UDP server mode.
This function implements OpenVPN's main event loop for UDP server mode. At this time, OpenVPN does not yet support multithreading. This function's name is therefore slightly misleading.
Parameters
top - Top-level context structure.
Definition at line 301 of file mudp.c.
References context::c2, CC_HARD_USR1_TO_HUP, close_instance(), CM_TOP, context_clear_2(), D_MULTI_ERRORS, context::es, ES_TIMEOUT, context_2::event_set_status, init_instance_handle_signals(), init_management_callback_multi(), initialization_sequence_completed(), io_wait(), IS_SIG, ISC_SERVER, M_ERRNO, MC_SINGLE_THREADED, context::mode, MPP_CLOSE_ON_SIGNAL, MPP_PRE_SELECT, msg, MULTI_CHECK_SIG, multi_get_timeout(), multi_ifconfig_pool_persist(), multi_init(), multi_process_io_udp(), multi_process_per_second_timers(), multi_process_timeout(), multi_top_free(), multi_top_init(), multi_uninit(), p2mp_iow_flags(), PERF_EVENT_LOOP, perf_pop(), perf_push(), context_2::timeval, multi_context::top, and uninit_management_callback().
Referenced by tunnel_server_udp().