OpenVPN: src/openvpn/mudp.h File Reference
mudp.h File Reference
Functions
void tunnel_server_udp (struct context *top)
Main event loop wrapper function for OpenVPN in UDP server mode.
struct multi_instance * multi_get_create_instance_udp (struct multi_context *m, bool *floated)
Get, and if necessary create, the multi_instance associated with a packet's source address.
Function Documentation
multi_get_create_instance_udp()
struct multi_instance* multi_get_create_instance_udp (struct multi_context * m, bool * floated)
Get, and if necessary create, the multi_instance associated with a packet's source address.
This function extracts the source address of a recently read packet from m->top.c2.from and uses that source address as a hash key for the hash table m->hash. If an entry exists, this function returns it. If no entry exists, this function handles its creation, and if successful, returns the newly created instance.
Parameters
m - The single multi_context structure.
Returns
A pointer to a multi_instance if one already existed for the packet's source address or if one was a newly created successfully. NULL if one did not yet exist and a new one was not created.
Definition at line 49 of file mudp.c.
References ASSERT, BPTR, context_2::buf, context::c2, check_debug_level(), multi_instance::context, D_MULTI_DEBUG, D_MULTI_ERRORS, D_MULTI_MEDIUM, link_socket_actual::dest, multi_instance::did_real_hash, dmsg, frequency_limit_event_allowed(), context_2::from, multi_instance::gc, gc_free(), gc_new(), multi_instance::halt, multi_context::hash, hash_add_fast(), hash_bucket(), hash_lookup_fast(), hash_value(), multi_context::instances, buffer::len, link_socket_actual_match(), multi_context::max_clients, MAX_PEER_ID, mroute_addr_print(), mroute_extract_openvpn_sockaddr(), msg, multi_create_instance(), multi_context::new_connection_limiter, P_DATA_V2, P_OPCODE_SHIFT, tls_multi::peer_id, multi_instance::real, status, context_2::tls_auth_standalone, context_2::tls_multi, tls_pre_decrypt_lite(), multi_context::top, ungenerate_prefix(), and hash_element::value.
Referenced by multi_process_incoming_link().
tunnel_server_udp()
void tunnel_server_udp (struct context * top)
Main event loop wrapper function for OpenVPN in UDP server mode.
This function simply calls tunnel_server_udp_single_threaded().
Parameters
top - Top-level context structure.
Definition at line 380 of file mudp.c.
References multi_context::top, and tunnel_server_udp_single_threaded().
Referenced by tunnel_server().