OpenVPN: sample/sample-plugins/defer/multi-auth.c File Reference
multi-auth.c File Reference
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <unistd.h>
#include <stdbool.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "openvpn-plugin.h"
Data Structures
struct plugin_context
struct plugin_per_client_context
Macros
#define OPENVPN_PLUGIN_VERSION_MIN 3
#define OPENVPN_PLUGIN_STRUCTVER_MIN 5
Functions
static void plog (const struct plugin_context *ctx, int flags, char *fmt,...)
static const char * get_env (const char *name, const char *envp[])
static const char * np (const char *str)
static int atoi_null0 (const char *str)
OPENVPN_EXPORT int openvpn_plugin_min_version_required_v1 ()
OPENVPN_EXPORT int openvpn_plugin_open_v3 (const int v3structver, struct openvpn_plugin_args_open_in const *args, struct openvpn_plugin_args_open_return *ret)
static bool do_auth_user_pass (struct plugin_context *context, const char *username, const char *password)
static int auth_user_pass_verify (struct plugin_context *context, struct plugin_per_client_context *pcc, const char *argv[], const char *envp[])
OPENVPN_EXPORT int openvpn_plugin_func_v3 (const int v3structver, struct openvpn_plugin_args_func_in const *args, struct openvpn_plugin_args_func_return *ret)
OPENVPN_EXPORT void * openvpn_plugin_client_constructor_v1 (openvpn_plugin_handle_t handle)
OPENVPN_EXPORT void openvpn_plugin_client_destructor_v1 (openvpn_plugin_handle_t handle, void *per_client_context)
OPENVPN_EXPORT void openvpn_plugin_close_v1 (openvpn_plugin_handle_t handle)
Variables
static char * MODULE = "multi-auth"
static plugin_vlog_t _plugin_vlog_func = NULL
Macro Definition Documentation
OPENVPN_PLUGIN_STRUCTVER_MIN
#define OPENVPN_PLUGIN_STRUCTVER_MIN 5
Definition at line 107 of file multi-auth.c.
OPENVPN_PLUGIN_VERSION_MIN
#define OPENVPN_PLUGIN_VERSION_MIN 3
Definition at line 106 of file multi-auth.c.
Function Documentation
atoi_null0()
static int atoi_null0 (const char * str) static
Definition at line 158 of file multi-auth.c.
Referenced by openvpn_plugin_open_v3().
auth_user_pass_verify()
static int auth_user_pass_verify (struct plugin_context * context, struct plugin_per_client_context * pcc, const char * argv[], const char * envp[]) static
Definition at line 273 of file multi-auth.c.
References do_auth_user_pass(), get_env(), OPENVPN_PLUGIN_FUNC_DEFERRED, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_FUNC_SUCCESS, plugin_context::password, plog(), PLOG_ERR, PLOG_ERRNO, PLOG_NOTE, plugin_context::username, and write.
Referenced by openvpn_plugin_func_v3().
do_auth_user_pass()
static bool do_auth_user_pass (struct plugin_context * context, const char * username, const char * password) static
Definition at line 242 of file multi-auth.c.
References np(), plugin_context::password, plog(), PLOG_ERR, PLOG_NOTE, and plugin_context::username.
Referenced by auth_user_pass_verify().
get_env()
static const char* get_env (const char * name, const char * envp[]) static
Definition at line 122 of file multi-auth.c.
Referenced by auth_user_pass_verify().
np()
static const char* np (const char * str) static
Definition at line 145 of file multi-auth.c.
Referenced by ce_management_query_proxy(), ce_management_query_remote(), do_auth_user_pass(), print_key_filename(), and tls_lock_username().
openvpn_plugin_client_constructor_v1()
OPENVPN_EXPORT void* openvpn_plugin_client_constructor_v1 (openvpn_plugin_handle_t handle)
Definition at line 392 of file multi-auth.c.
References plog(), and PLOG_NOTE.
openvpn_plugin_client_destructor_v1()
OPENVPN_EXPORT void openvpn_plugin_client_destructor_v1 (openvpn_plugin_handle_t handle, void * per_client_context)
Definition at line 400 of file multi-auth.c.
References plog(), and PLOG_NOTE.
openvpn_plugin_close_v1()
OPENVPN_EXPORT void openvpn_plugin_close_v1 (openvpn_plugin_handle_t handle)
Definition at line 408 of file multi-auth.c.
References plog(), and PLOG_NOTE.
openvpn_plugin_func_v3()
OPENVPN_EXPORT int openvpn_plugin_func_v3 (const int v3structver, struct openvpn_plugin_args_func_in const * args, struct openvpn_plugin_args_func_return * ret)
Definition at line 366 of file multi-auth.c.
References openvpn_plugin_args_func_in::argv, auth_user_pass_verify(), openvpn_plugin_args_func_in::envp, openvpn_plugin_args_func_in::handle, MODULE, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_STRUCTVER_MIN, openvpn_plugin_args_func_in::per_client_context, plog(), PLOG_NOTE, and openvpn_plugin_args_func_in::type.
openvpn_plugin_min_version_required_v1()
OPENVPN_EXPORT int openvpn_plugin_min_version_required_v1 ()
Definition at line 172 of file multi-auth.c.
References OPENVPN_PLUGIN_VERSION_MIN.
openvpn_plugin_open_v3()
OPENVPN_EXPORT int openvpn_plugin_open_v3 (const int v3structver, struct openvpn_plugin_args_open_in const * args, struct openvpn_plugin_args_open_return * ret)
Definition at line 179 of file multi-auth.c.
References _plugin_vlog_func, openvpn_plugin_args_open_in::argv, atoi_null0(), openvpn_plugin_args_open_in::callbacks, openvpn_plugin_args_open_return::handle, MODULE, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_FUNC_SUCCESS, OPENVPN_PLUGIN_MASK, OPENVPN_PLUGIN_STRUCTVER_MIN, plog(), PLOG_ERR, PLOG_NOTE, openvpn_plugin_callbacks::plugin_vlog, and openvpn_plugin_args_open_return::type_mask.
plog()
static void plog (const struct plugin_context * ctx, int flags, char * fmt, ...) static
Definition at line 75 of file multi-auth.c.
References _plugin_vlog_func, plugin_context::authid, MODULE, and snprintf.
Referenced by auth_user_pass_verify(), do_auth_user_pass(), openvpn_plugin_client_constructor_v1(), openvpn_plugin_client_destructor_v1(), openvpn_plugin_close_v1(), openvpn_plugin_func_v3(), and openvpn_plugin_open_v3().
Variable Documentation
_plugin_vlog_func
plugin_vlog_t _plugin_vlog_func = NULL static
Definition at line 74 of file multi-auth.c.
Referenced by openvpn_plugin_open_v3(), and plog().
MODULE
char* MODULE = "multi-auth" static
Definition at line 60 of file multi-auth.c.
Referenced by openvpn_plugin_func_v3(), openvpn_plugin_open_v3(), and plog().