OpenVPN: src/openvpn/networking.h File Reference
networking.h File Reference
#include "syshead.h"
Typedefs
typedef void * openvpn_net_ctx_t
typedef void * openvpn_net_iface_t
Functions
static int net_ctx_init (struct context *c, openvpn_net_ctx_t *ctx)
static void net_ctx_reset (openvpn_net_ctx_t *ctx)
static void net_ctx_free (openvpn_net_ctx_t *ctx)
Typedef Documentation
openvpn_net_ctx_t
typedef void* openvpn_net_ctx_t
Definition at line 26 of file networking.h.
openvpn_net_iface_t
typedef void* openvpn_net_iface_t
Definition at line 35 of file networking.h.
Function Documentation
net_ctx_free()
static void net_ctx_free (openvpn_net_ctx_t * ctx) inline static
Definition at line 50 of file networking.h.
Referenced by do_ifconfig(), and uninit_early().
net_ctx_init()
static int net_ctx_init (struct context * c, openvpn_net_ctx_t * ctx) inline static
Definition at line 38 of file networking.h.
Referenced by add_option(), and init_early().
net_ctx_reset()
static void net_ctx_reset (openvpn_net_ctx_t * ctx) inline static
Definition at line 44 of file networking.h.
Referenced by add_route(), add_route_ipv6(), delete_route(), and delete_route_ipv6().