OpenVPN: src/openvpn/ntlm.c File Reference
ntlm.c File Reference
#include "syshead.h"
#include "common.h"
#include "buffer.h"
#include "misc.h"
#include "socket.h"
#include "fdmisc.h"
#include "proxy.h"
#include "ntlm.h"
#include "base64.h"
#include "crypto.h"
#include "memdbg.h"
Macros
#define UINTEGER64 unsigned long long
#define UINT64(c) c ## LL
Functions
static void create_des_keys (const unsigned char *hash, unsigned char *key)
static void gen_md4_hash (const uint8_t *data, int data_len, uint8_t *result)
static void gen_hmac_md5 (const uint8_t *data, int data_len, const uint8_t *key, int key_len, uint8_t *result)
static void gen_timestamp (uint8_t *timestamp)
static void gen_nonce (unsigned char *nonce)
static void my_strupr (char *str)
static int unicodize (char *dst, const char *src)
This function expects a null-terminated string in src and will copy it (including the terminating NUL byte), alternating it with 0 to dst.
static void add_security_buffer (int sb_offset, void *data, int length, unsigned char *msg_buf, int *msg_bufpos)
const char * ntlm_phase_1 (const struct http_proxy_info *p, struct gc_arena *gc)
const char * ntlm_phase_3 (const struct http_proxy_info *p, const char *phase_2, struct gc_arena *gc)
Macro Definition Documentation
UINT64
#define UINT64 (c) c ## LL
Definition at line 54 of file ntlm.c.
UINTEGER64
#define UINTEGER64 unsigned long long
Definition at line 53 of file ntlm.c.
Function Documentation
add_security_buffer()
static void add_security_buffer (int sb_offset, void * data, int length, unsigned char * msg_buf, int * msg_bufpos) static
Definition at line 174 of file ntlm.c.
Referenced by ntlm_phase_3().
create_des_keys()
static void create_des_keys (const unsigned char * hash, unsigned char * key) static
Definition at line 60 of file ntlm.c.
References key_des_fixup().
Referenced by ntlm_phase_3().
gen_hmac_md5()
static void gen_hmac_md5 (const uint8_t * data, int data_len, const uint8_t * key, int key_len, uint8_t * result) static
Definition at line 85 of file ntlm.c.
References hmac_ctx_cleanup(), hmac_ctx_final(), hmac_ctx_free(), hmac_ctx_init(), hmac_ctx_new(), hmac_ctx_update(), and md_kt_get().
Referenced by ntlm_phase_3().
gen_md4_hash()
static void gen_md4_hash (const uint8_t * data, int data_len, uint8_t * result) static
Definition at line 74 of file ntlm.c.
References MD4_DIGEST_LENGTH, md_full(), and md_kt_get().
Referenced by ntlm_phase_3().
gen_nonce()
static void gen_nonce (unsigned char * nonce) static
Definition at line 123 of file ntlm.c.
References get_random().
Referenced by ntlm_phase_3().
gen_timestamp()
static void gen_timestamp (uint8_t * timestamp) static
Definition at line 99 of file ntlm.c.
References openvpn_time(), UINT64, and UINTEGER64.
Referenced by ntlm_phase_3().
my_strupr()
static void my_strupr (char * str) static
Definition at line 135 of file ntlm.c.
Referenced by ntlm_phase_3().
ntlm_phase_1()
const char* ntlm_phase_1 (const struct http_proxy_info * p, struct gc_arena * gc)
Definition at line 188 of file ntlm.c.
References alloc_buf_gc(), BSTR, and buf_printf().
Referenced by establish_http_proxy_passthru().
ntlm_phase_3()
const char* ntlm_phase_3 (const struct http_proxy_info * p, const char * phase_2, struct gc_arena * gc)
Definition at line 205 of file ntlm.c.
References add_security_buffer(), ASSERT, http_proxy_info::auth_method, cipher_des_encrypt_ecb(), CLEAR, create_des_keys(), DES_KEY_LENGTH, gen_hmac_md5(), gen_md4_hash(), gen_nonce(), gen_timestamp(), HTTP_AUTH_NTLM2, buffer::len, M_INFO, make_base64_string2(), MD4_DIGEST_LENGTH, MD5_DIGEST_LENGTH, msg, my_strupr(), openvpn_base64_decode(), user_pass::password, unicodize(), http_proxy_info::up, and user_pass::username.
Referenced by establish_http_proxy_passthru().
unicodize()
static int unicodize (char * dst, const char * src) static
This function expects a null-terminated string in src and will copy it (including the terminating NUL byte), alternating it with 0 to dst.
This basically will transform a ASCII string into valid UTF-16. Characters that are 8bit in src, will get the same treatment, resulting in invalid or wrong unicode code points.
Note
the function will blindly assume that dst has double the space of src.
Returns
the length of the number of bytes written to dst
Definition at line 160 of file ntlm.c.
References dst.
Referenced by ntlm_phase_3().