OpenVPN: src/openvpn/ntlm.h File Reference
ntlm.h File Reference
Functions
const char * ntlm_phase_1 (const struct http_proxy_info *p, struct gc_arena *gc)
const char * ntlm_phase_3 (const struct http_proxy_info *p, const char *phase_2, struct gc_arena *gc)
Function Documentation
ntlm_phase_1()
const char* ntlm_phase_1 (const struct http_proxy_info * p, struct gc_arena * gc)
Definition at line 188 of file ntlm.c.
References alloc_buf_gc(), BSTR, and buf_printf().
Referenced by establish_http_proxy_passthru().
ntlm_phase_3()
const char* ntlm_phase_3 (const struct http_proxy_info * p, const char * phase_2, struct gc_arena * gc)
Definition at line 205 of file ntlm.c.
References add_security_buffer(), ASSERT, http_proxy_info::auth_method, cipher_des_encrypt_ecb(), CLEAR, create_des_keys(), DES_KEY_LENGTH, gen_hmac_md5(), gen_md4_hash(), gen_nonce(), gen_timestamp(), HTTP_AUTH_NTLM2, buffer::len, M_INFO, make_base64_string2(), MD4_DIGEST_LENGTH, MD5_DIGEST_LENGTH, msg, my_strupr(), openvpn_base64_decode(), user_pass::password, unicodize(), http_proxy_info::up, and user_pass::username.
Referenced by establish_http_proxy_passthru().