OpenVPN: src/openvpn/occ.c File Reference
occ.c File Reference
#include "syshead.h"
#include "occ.h"
#include "forward.h"
#include "memdbg.h"
Functions
void check_send_occ_req_dowork (struct context *c)
void check_send_occ_load_test_dowork (struct context *c)
void check_send_occ_msg_dowork (struct context *c)
void process_received_occ_msg (struct context *c)
Variables
const uint8_t occ_magic []
static const struct mtu_load_test mtu_load_test_sequence []
Function Documentation
check_send_occ_load_test_dowork()
void check_send_occ_load_test_dowork (struct context * c)
Definition at line 186 of file occ.c.
References context::c2, CONNECTION_ESTABLISHED, mtu_load_test::delta, event_timeout_clear(), EXPANDED_SIZE, context_2::frame, M_INFO, msg, mtu_load_test_sequence, context_2::occ_mtu_load_n_tries, context_2::occ_mtu_load_size, context_2::occ_mtu_load_test_interval, context_2::occ_op, mtu_load_test::op, and PACKAGE_NAME.
Referenced by check_send_occ_load_test().
check_send_occ_msg_dowork()
void check_send_occ_msg_dowork (struct context * c)
Definition at line 216 of file occ.c.
References ASSERT, context_buffers::aux_buf, BLEN, context_2::buf, buf_init, buf_safe(), buf_write(), buf_write_u16(), buf_write_u8(), context_2::buffers, context::c2, D_PACKET_CONTENT, dmsg, encrypt_sign(), EXPANDED_SIZE, EXTRA_FRAME, context_2::frame, FRAME_HEADROOM, get_random(), context_2::max_recv_size_local, MAX_RW_SIZE_TUN, context_2::max_send_size_local, min_int(), OCC_EXIT, occ_magic, OCC_MTU_LOAD, OCC_MTU_LOAD_REQUEST, context_2::occ_mtu_load_size, OCC_MTU_REPLY, OCC_MTU_REQUEST, context_2::occ_op, OCC_REPLY, OCC_REQUEST, OCC_STRING_SIZE, and context_2::options_string_local.
Referenced by check_send_occ_msg().
check_send_occ_req_dowork()
void check_send_occ_req_dowork (struct context * c)
Definition at line 149 of file occ.c.
References context::c2, options::ce, counter_format, D_SHOW_OCC, event_timeout_clear(), event_timeout_reset(), context_2::link_read_bytes, context_2::link_read_bytes_auth, msg, context_2::occ_interval, OCC_N_TRIES, context_2::occ_n_tries, context_2::occ_op, OCC_REQUEST, context::options, PACKAGE_NAME, and connection_entry::remote.
Referenced by check_send_occ_req().
process_received_occ_msg()
void process_received_occ_msg (struct context * c)
Definition at line 351 of file occ.c.
References ASSERT, BPTR, context_2::buf, buf_advance(), buf_read_u16(), buf_read_u8(), context::c2, options::ce, D_PACKET_CONTENT, dmsg, event_timeout_clear(), connection_entry::fragment, buffer::len, M_INFO, context_2::max_recv_size_local, context_2::max_recv_size_remote, context_2::max_send_size_local, context_2::max_send_size_remote, msg, options::mtu_test, options::occ, OCC_EXIT, context_2::occ_interval, OCC_MTU_LOAD, OCC_MTU_LOAD_REQUEST, context_2::occ_mtu_load_size, context_2::occ_mtu_load_test_interval, OCC_MTU_REPLY, OCC_MTU_REQUEST, context_2::occ_op, OCC_REPLY, OCC_REQUEST, OCC_STRING_SIZE, context::options, options_cmp_equal_safe(), context_2::options_string_remote, options_warning_safe(), connection_entry::proto, proto_is_dgram(), context::sig, signal_info::signal_received, signal_info::signal_text, SIGTERM, TLS_MODE, and TUN_MTU_MIN.
Referenced by process_incoming_link_part2().
Variable Documentation
mtu_load_test_sequence
const struct mtu_load_test mtu_load_test_sequence[] static
Definition at line 62 of file occ.c.
Referenced by check_send_occ_load_test_dowork().
occ_magic
const uint8_t occ_magic[]
Initial value:
= {
    0x28, 0x7f, 0x34, 0x6b, 0xd4, 0xef, 0x7a, 0x81,
    0x2d, 0x56, 0xb8, 0xd3, 0xaf, 0xc5, 0x45, 0x9c
}
Definition at line 57 of file occ.c.
Referenced by check_send_occ_msg_dowork(), and is_occ_msg().