OpenVPN: src/openvpn/openssl_compat.h File Reference
openssl_compat.h File Reference
#include "buffer.h"
#include <openssl/rsa.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
Macros
#define EVP_CIPHER_CTX_reset EVP_CIPHER_CTX_init
#define X509_get0_notBefore X509_get_notBefore
#define X509_get0_notAfter X509_get_notAfter
#define SSL_CTX_set1_groups SSL_CTX_set1_curves
#define OPENSSL_VERSION SSLEAY_VERSION
#define OpenSSL_version SSLeay_version
#define RSA_F_RSA_OSSL_PRIVATE_ENCRYPT RSA_F_RSA_EAY_PRIVATE_ENCRYPT
Functions
static int EVP_MD_CTX_reset (EVP_MD_CTX *ctx)
Reset a message digest context.
static void EVP_MD_CTX_free (EVP_MD_CTX *ctx)
Free an existing message digest context.
static EVP_MD_CTX * EVP_MD_CTX_new (void)
Allocate a new message digest object.
static int HMAC_CTX_reset (HMAC_CTX *ctx)
Reset a HMAC context.
static void HMAC_CTX_free (HMAC_CTX *ctx)
Cleanup and free an existing HMAC context.
static HMAC_CTX * HMAC_CTX_new (void)
Allocate a new HMAC context object.
static void * SSL_CTX_get_default_passwd_cb_userdata (SSL_CTX *ctx)
Fetch the default password callback user data from the SSL context.
static pem_password_cb * SSL_CTX_get_default_passwd_cb (SSL_CTX *ctx)
Fetch the default password callback from the SSL context.
static EVP_PKEY * X509_get0_pubkey (const X509 *x)
Get the public key from a X509 certificate.
static STACK_OF (X509_OBJECT) *X509_STORE_get0_objects(X509_STORE *store)
Fetch the X509 object stack from the X509 store.
static void X509_OBJECT_free (X509_OBJECT *obj)
Destroy a X509 object.
static int X509_OBJECT_get_type (const X509_OBJECT *obj)
Get the type of an X509 object.
static RSA * EVP_PKEY_get0_RSA (EVP_PKEY *pkey)
Get the RSA object of a public key.
static EC_KEY * EVP_PKEY_get0_EC_KEY (EVP_PKEY *pkey)
Get the EC_KEY object of a public key.
static DSA * EVP_PKEY_get0_DSA (EVP_PKEY *pkey)
Get the DSA object of a public key.
static void RSA_set_flags (RSA *rsa, int flags)
Set the RSA flags.
static void RSA_get0_key (const RSA *rsa, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
Get the RSA parameters.
static int RSA_set0_key (RSA *rsa, BIGNUM *n, BIGNUM *e, BIGNUM *d)
Set the RSA parameters.
static int RSA_bits (const RSA *rsa)
Number of significant RSA bits.
static void DSA_get0_pqg (const DSA *dsa, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
Get the DSA parameters.
static int DSA_bits (const DSA *dsa)
Number of significant DSA bits.
static RSA_METHOD * RSA_meth_new (const char *name, int flags)
Allocate a new RSA method object.
static void RSA_meth_free (RSA_METHOD *meth)
Free an existing RSA_METHOD object.
static int RSA_meth_set_pub_enc (RSA_METHOD *meth, int(*pub_enc)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
Set the public encoding function of an RSA_METHOD object.
static int RSA_meth_set_pub_dec (RSA_METHOD *meth, int(*pub_dec)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
Set the public decoding function of an RSA_METHOD object.
static int RSA_meth_set_priv_enc (RSA_METHOD *meth, int(*priv_enc)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
Set the private encoding function of an RSA_METHOD object.
static int RSA_meth_set_priv_dec (RSA_METHOD *meth, int(*priv_dec)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
Set the private decoding function of an RSA_METHOD object.
static int RSA_meth_set_init (RSA_METHOD *meth, int(*init)(RSA *rsa))
Set the init function of an RSA_METHOD object.
static int RSA_meth_set_sign (RSA_METHOD *meth, int(*sign)(int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, const RSA *rsa))
Set the sign function of an RSA_METHOD object.
static int RSA_meth_set_finish (RSA_METHOD *meth, int(*finish)(RSA *rsa))
Set the finish function of an RSA_METHOD object.
static int RSA_meth_set0_app_data (RSA_METHOD *meth, void *app_data)
Set the application data of an RSA_METHOD object.
static void * RSA_meth_get0_app_data (const RSA_METHOD *meth)
Get the application data of an RSA_METHOD object.
static int EC_GROUP_order_bits (const EC_GROUP *group)
Gets the number of bits of the order of an EC_GROUP.
static int SSL_CTX_get_min_proto_version (SSL_CTX *ctx)
Return the min SSL protocol version currently enabled in the context.
static int SSL_CTX_get_max_proto_version (SSL_CTX *ctx)
Return the max SSL protocol version currently enabled in the context.
static int SSL_CTX_set_min_proto_version (SSL_CTX *ctx, long tls_ver_min)
Mimics SSL_CTX_set_min_proto_version for OpenSSL < 1.1.
static int SSL_CTX_set_max_proto_version (SSL_CTX *ctx, long tls_ver_max)
Mimics SSL_CTX_set_max_proto_version for OpenSSL < 1.1.
Macro Definition Documentation
EVP_CIPHER_CTX_reset
#define EVP_CIPHER_CTX_reset EVP_CIPHER_CTX_init
Definition at line 93 of file openssl_compat.h.
OPENSSL_VERSION
#define OPENSSL_VERSION SSLEAY_VERSION
Definition at line 687 of file openssl_compat.h.
OpenSSL_version
#define OpenSSL_version SSLeay_version
Definition at line 691 of file openssl_compat.h.
RSA_F_RSA_OSSL_PRIVATE_ENCRYPT
#define RSA_F_RSA_OSSL_PRIVATE_ENCRYPT RSA_F_RSA_EAY_PRIVATE_ENCRYPT
Definition at line 695 of file openssl_compat.h.
SSL_CTX_set1_groups
#define SSL_CTX_set1_groups SSL_CTX_set1_curves
Definition at line 189 of file openssl_compat.h.
X509_get0_notAfter
#define X509_get0_notAfter X509_get_notAfter
Definition at line 101 of file openssl_compat.h.
X509_get0_notBefore
#define X509_get0_notBefore X509_get_notBefore
Definition at line 97 of file openssl_compat.h.
Function Documentation
DSA_bits()
static int DSA_bits (const DSA * dsa) inline static
Number of significant DSA bits.
Parameters
rsa The DSA object ; shall not be NULL
Returns
The number of DSA bits or 0 on error
Definition at line 430 of file openssl_compat.h.
References DSA_get0_pqg().
DSA_get0_pqg()
static void DSA_get0_pqg (const DSA * dsa, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g) inline static
Get the DSA parameters.
Parameters
dsa The DSA object
p The p parameter
q The q parameter
g The g parameter
Definition at line 404 of file openssl_compat.h.
Referenced by DSA_bits().
EC_GROUP_order_bits()
static int EC_GROUP_order_bits (const EC_GROUP * group) inline static
Gets the number of bits of the order of an EC_GROUP.
Parameters
group EC_GROUP object
Returns
number of bits of group order.
Definition at line 675 of file openssl_compat.h.
EVP_MD_CTX_free()
static void EVP_MD_CTX_free (EVP_MD_CTX * ctx) inline static
Free an existing message digest context.
Parameters
ctx The message digest context
Definition at line 71 of file openssl_compat.h.
Referenced by md_ctx_free().
EVP_MD_CTX_new()
static EVP_MD_CTX* EVP_MD_CTX_new (void) inline static
Allocate a new message digest object.
Returns
A zero'ed message digest object
Definition at line 84 of file openssl_compat.h.
References ALLOC_OBJ_CLEAR.
Referenced by md_ctx_new().
EVP_MD_CTX_reset()
static int EVP_MD_CTX_reset (EVP_MD_CTX * ctx) inline static
Reset a message digest context.
Parameters
ctx The message digest context
Returns
1 on success, 0 on error
Definition at line 57 of file openssl_compat.h.
Referenced by md_ctx_cleanup().
EVP_PKEY_get0_DSA()
static DSA* EVP_PKEY_get0_DSA (EVP_PKEY * pkey) inline static
Get the DSA object of a public key.
Parameters
pkey Public key object
Returns
The underlying DSA object
Definition at line 288 of file openssl_compat.h.
EVP_PKEY_get0_EC_KEY()
static EC_KEY* EVP_PKEY_get0_EC_KEY (EVP_PKEY * pkey) inline static
Get the EC_KEY object of a public key.
Parameters
pkey Public key object
Returns
The underlying EC_KEY object
Definition at line 274 of file openssl_compat.h.
Referenced by print_cert_details().
EVP_PKEY_get0_RSA()
static RSA* EVP_PKEY_get0_RSA (EVP_PKEY * pkey) inline static
Get the RSA object of a public key.
Parameters
pkey Public key object
Returns
The underlying RSA object
Definition at line 260 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
HMAC_CTX_free()
static void HMAC_CTX_free (HMAC_CTX * ctx) inline static
Cleanup and free an existing HMAC context.
Parameters
ctx The HMAC context
Definition at line 136 of file openssl_compat.h.
Referenced by hmac_ctx_free().
HMAC_CTX_new()
static HMAC_CTX* HMAC_CTX_new (void) inline static
Allocate a new HMAC context object.
Returns
A zero'ed HMAC context object
Definition at line 150 of file openssl_compat.h.
References ALLOC_OBJ_CLEAR.
Referenced by hmac_ctx_new().
HMAC_CTX_reset()
static int HMAC_CTX_reset (HMAC_CTX * ctx) inline static
Reset a HMAC context.
OpenSSL 1.1+ removes APIs HMAC_CTX_init() and HMAC_CTX_cleanup() and replace them with a single call that does a cleanup followed by an init. A proper _reset() for OpenSSL < 1.1 should perform a similar set of operations.
It means that before we kill a HMAC context, we'll have to cleanup again, as we probably have allocated a few resources when we forced an init.
Parameters
ctx The HMAC context
Returns
1 on success, 0 on error
Definition at line 121 of file openssl_compat.h.
Referenced by hmac_ctx_cleanup(), and hmac_ctx_init().
RSA_bits()
static int RSA_bits (const RSA * rsa) inline static
Number of significant RSA bits.
Parameters
rsa The RSA object ; shall not be NULL
Returns
The number of RSA bits or 0 on error
Definition at line 386 of file openssl_compat.h.
References RSA_get0_key().
RSA_get0_key()
static void RSA_get0_key (const RSA * rsa, const BIGNUM ** n, const BIGNUM ** e, const BIGNUM ** d) inline static
Get the RSA parameters.
Parameters
rsa The RSA object
n The n parameter
e The e parameter
d The d parameter
Definition at line 321 of file openssl_compat.h.
Referenced by RSA_bits(), ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_free()
static void RSA_meth_free (RSA_METHOD * meth) inline static
Free an existing RSA_METHOD object.
Parameters
meth The RSA_METHOD object
Definition at line 464 of file openssl_compat.h.
Referenced by finish(), openvpn_extkey_rsa_finish(), ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_get0_app_data()
static void* RSA_meth_get0_app_data (const RSA_METHOD * meth) inline static
Get the application data of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
Returns
pointer to application data, may be NULL
Definition at line 661 of file openssl_compat.h.
Referenced by finish(), rsa_priv_enc(), and rsa_sign_CNG().
RSA_meth_new()
static RSA_METHOD* RSA_meth_new (const char * name, int flags) inline static
Allocate a new RSA method object.
Parameters
name The object name
flags Configuration flags
Returns
A new RSA method object
Definition at line 447 of file openssl_compat.h.
References ALLOC_OBJ_CLEAR, and string_alloc().
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set0_app_data()
static int RSA_meth_set0_app_data (RSA_METHOD * meth, void * app_data) inline static
Set the application data of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
app_data Application data
Returns
1 on success, 0 on error
Definition at line 642 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set_finish()
static int RSA_meth_set_finish (RSA_METHOD * meth, int(*)(RSA *rsa) finish) inline static
Set the finish function of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
finish the finish function
Returns
1 on success, 0 on error
Definition at line 622 of file openssl_compat.h.
References finish().
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set_init()
static int RSA_meth_set_init (RSA_METHOD * meth, int(*)(RSA *rsa) init) inline static
Set the init function of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
init the init function
Returns
1 on success, 0 on error
Definition at line 581 of file openssl_compat.h.
References init().
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set_priv_dec()
static int RSA_meth_set_priv_dec (RSA_METHOD * meth, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) priv_dec) inline static
Set the private decoding function of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
priv_dec the private decoding function
Returns
1 on success, 0 on error
Definition at line 558 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set_priv_enc()
static int RSA_meth_set_priv_enc (RSA_METHOD * meth, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) priv_enc) inline static
Set the private encoding function of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
priv_enc the private encoding function
Returns
1 on success, 0 on error
Definition at line 535 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set_pub_dec()
static int RSA_meth_set_pub_dec (RSA_METHOD * meth, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) pub_dec) inline static
Set the public decoding function of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
pub_dec the public decoding function
Returns
1 on success, 0 on error
Definition at line 512 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set_pub_enc()
static int RSA_meth_set_pub_enc (RSA_METHOD * meth, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) pub_enc) inline static
Set the public encoding function of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
pub_enc the public encoding function
Returns
1 on success, 0 on error
Definition at line 489 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_meth_set_sign()
static int RSA_meth_set_sign (RSA_METHOD * meth, int(*)(int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, const RSA *rsa) sign) inline static
Set the sign function of an RSA_METHOD object.
Parameters
meth The RSA_METHOD object
sign The sign function
Returns
1 on success, 0 on error
Definition at line 602 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey().
RSA_set0_key()
static int RSA_set0_key (RSA * rsa, BIGNUM * n, BIGNUM * e, BIGNUM * d) inline static
Set the RSA parameters.
Parameters
rsa The RSA object
n The n parameter
e The e parameter
d The d parameter
Returns
1 on success, 0 on error
Definition at line 350 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
RSA_set_flags()
static void RSA_set_flags (RSA * rsa, int flags) inline static
Set the RSA flags.
Parameters
rsa The RSA object
flags New flags value
Definition at line 302 of file openssl_compat.h.
Referenced by ssl_ctx_set_rsakey(), and tls_ctx_use_external_rsa_key().
SSL_CTX_get_default_passwd_cb()
static pem_password_cb* SSL_CTX_get_default_passwd_cb (SSL_CTX * ctx) inline static
Fetch the default password callback from the SSL context.
Parameters
ctx SSL context
Returns
The password callback
Definition at line 180 of file openssl_compat.h.
Referenced by tls_ctx_load_cert_file(), and tls_ctx_load_priv_file().
SSL_CTX_get_default_passwd_cb_userdata()
static void* SSL_CTX_get_default_passwd_cb_userdata (SSL_CTX * ctx) inline static
Fetch the default password callback user data from the SSL context.
Parameters
ctx SSL context
Returns
The password callback user data
Definition at line 166 of file openssl_compat.h.
Referenced by tls_ctx_load_cert_file(), and tls_ctx_load_priv_file().
SSL_CTX_get_max_proto_version()
static int SSL_CTX_get_max_proto_version (SSL_CTX * ctx) inline static
Return the max SSL protocol version currently enabled in the context.
If no valid version >= TLS1.0 is found, return 0.
Definition at line 725 of file openssl_compat.h.
Referenced by SSL_CTX_use_CryptoAPI_certificate().
SSL_CTX_get_min_proto_version()
static int SSL_CTX_get_min_proto_version (SSL_CTX * ctx) inline static
Return the min SSL protocol version currently enabled in the context.
If no valid version >= TLS1.0 is found, return 0.
Definition at line 702 of file openssl_compat.h.
Referenced by SSL_CTX_use_CryptoAPI_certificate(), and tls_ctx_set_tls_versions().
SSL_CTX_set_max_proto_version()
static int SSL_CTX_set_max_proto_version (SSL_CTX * ctx, long tls_ver_max) inline static
Mimics SSL_CTX_set_max_proto_version for OpenSSL < 1.1.
Definition at line 776 of file openssl_compat.h.
Referenced by show_available_tls_ciphers_list(), SSL_CTX_use_CryptoAPI_certificate(), and tls_ctx_set_tls_versions().
SSL_CTX_set_min_proto_version()
static int SSL_CTX_set_min_proto_version (SSL_CTX * ctx, long tls_ver_min) inline static
Mimics SSL_CTX_set_min_proto_version for OpenSSL < 1.1.
Definition at line 747 of file openssl_compat.h.
Referenced by show_available_tls_ciphers_list(), and tls_ctx_set_tls_versions().
STACK_OF()
static STACK_OF (X509_OBJECT) inline static
Fetch the X509 object stack from the X509 store.
Parameters
store X509 object store
Returns
the X509 object stack
Definition at line 214 of file openssl_compat.h.
Referenced by backend_tls_ctx_reload_crl(), show_available_tls_ciphers_list(), tls_ctx_load_ca(), tls_ctx_load_pkcs12(), and tls_verify_crl_missing().
X509_get0_pubkey()
static EVP_PKEY* X509_get0_pubkey (const X509 * x) inline static
Get the public key from a X509 certificate.
Parameters
x X509 certificate
Returns
The certificate public key
Definition at line 200 of file openssl_compat.h.
Referenced by SSL_CTX_use_CryptoAPI_certificate(), and tls_ctx_use_management_external_key().
X509_OBJECT_free()
static void X509_OBJECT_free (X509_OBJECT * obj) inline static
Destroy a X509 object.
Parameters
obj X509 object
Definition at line 228 of file openssl_compat.h.
Referenced by backend_tls_ctx_reload_crl().
X509_OBJECT_get_type()
static int X509_OBJECT_get_type (const X509_OBJECT * obj) inline static
Get the type of an X509 object.
Parameters
obj X509 object
Returns
The underlying object type
Definition at line 246 of file openssl_compat.h.
Referenced by backend_tls_ctx_reload_crl(), and tls_verify_crl_missing().