OpenVPN: src/openvpn/openvpn.h File Reference
openvpn.h File Reference
#include "buffer.h"
#include "options.h"
#include "socket.h"
#include "crypto.h"
#include "ssl.h"
#include "packet_id.h"
#include "comp.h"
#include "tun.h"
#include "interval.h"
#include "status.h"
#include "fragment.h"
#include "shaper.h"
#include "route.h"
#include "proxy.h"
#include "socks.h"
#include "sig.h"
#include "misc.h"
#include "mbuf.h"
#include "pf.h"
#include "pool.h"
#include "plugin.h"
#include "manage.h"
Data Structures
struct key_schedule
struct packet_id_persist
struct context_buffers
struct context_persist
struct context_0
Level 0 context containing information related to the OpenVPN process.
struct context_1
Level 1 context containing state that persists across SIGUSR1 restarts.
struct context_2
Level 2 context containing state that is reset on both SIGHUP and SIGUSR1 restarts.
struct context
Contains all state information for one tunnel.
Macros
#define SOCKET_READ (1<<0)
#define SOCKET_WRITE (1<<1)
#define TUN_READ (1<<2)
#define TUN_WRITE (1<<3)
#define ES_ERROR (1<<4)
#define ES_TIMEOUT (1<<5)
#define MANAGEMENT_READ (1<<6)
#define MANAGEMENT_WRITE (1<<7)
#define CM_P2P 0 /* standalone point-to-point session or client */
#define CM_TOP 1 /* top level of a multi-client or point-to-multipoint server */
#define CM_TOP_CLONE 2 /* clone of a CM_TOP context for one thread */
#define CM_CHILD_UDP 3 /* child context of a CM_TOP or CM_THREAD */
#define CM_CHILD_TCP 4 /* child context of a CM_TOP or CM_THREAD */
#define EVENT_LOOP_CHECK_SIGNAL(c, func, arg)
#define TLS_MODE(c) ((c)->c2.tls_multi != NULL)
#define PROTO_DUMP_FLAGS (check_debug_level(D_LINK_RW_VERBOSE) ? (PD_SHOW_DATA|PD_VERBOSE) : 0)
#define PROTO_DUMP(buf, gc)
#define CIPHER_ENABLED(c) (c->c1.ks.key_type.cipher != NULL)
#define MAX_PEER_ID 0xFFFFFF
Functions
static void packet_id_persist_init (struct packet_id_persist *p)
static bool is_cas_pending (enum client_connect_status cas)
Macro Definition Documentation
CIPHER_ENABLED
#define CIPHER_ENABLED (c) (c->c1.ks.key_type.cipher != NULL)
Definition at line 560 of file openvpn.h.
CM_CHILD_TCP
#define CM_CHILD_TCP 4 /* child context of a CM_TOP or CM_THREAD */
Definition at line 502 of file openvpn.h.
CM_CHILD_UDP
#define CM_CHILD_UDP 3 /* child context of a CM_TOP or CM_THREAD */
Definition at line 501 of file openvpn.h.
CM_P2P
#define CM_P2P 0 /* standalone point-to-point session or client */
Definition at line 498 of file openvpn.h.
CM_TOP
#define CM_TOP 1 /* top level of a multi-client or point-to-multipoint server */
Definition at line 499 of file openvpn.h.
CM_TOP_CLONE
#define CM_TOP_CLONE 2 /* clone of a CM_TOP context for one thread */
Definition at line 500 of file openvpn.h.
ES_ERROR
#define ES_ERROR (1<<4)
Definition at line 246 of file openvpn.h.
ES_TIMEOUT
#define ES_TIMEOUT (1<<5)
Definition at line 247 of file openvpn.h.
EVENT_LOOP_CHECK_SIGNAL
#define EVENT_LOOP_CHECK_SIGNAL (c, func, arg)
Value:
    if (IS_SIG(c))                           \
    {                                       \
        const int brk = func(arg);           \
        perf_pop();                          \
        if (brk) {                              \
            break;}                              \
        else {                                  \
            continue;}                           \
    }
Definition at line 536 of file openvpn.h.
MANAGEMENT_READ
#define MANAGEMENT_READ (1<<6)
Definition at line 249 of file openvpn.h.
MANAGEMENT_WRITE
#define MANAGEMENT_WRITE (1<<7)
Definition at line 250 of file openvpn.h.
MAX_PEER_ID
#define MAX_PEER_ID 0xFFFFFF
Definition at line 563 of file openvpn.h.
PROTO_DUMP
#define PROTO_DUMP (buf, gc)
Value:
                                          protocol_dump((buf), \
                                          PROTO_DUMP_FLAGS   \
                                          |(c->c2.tls_multi ? PD_TLS : 0)   \
                                          |(c->options.tls_auth_file ? c->c1.ks.key_type.hmac_length : 0), \
                                          gc)
Definition at line 554 of file openvpn.h.
PROTO_DUMP_FLAGS
#define PROTO_DUMP_FLAGS (check_debug_level(D_LINK_RW_VERBOSE) ? (PD_SHOW_DATA|PD_VERBOSE) : 0)
Definition at line 553 of file openvpn.h.
SOCKET_READ
#define SOCKET_READ (1<<0)
Definition at line 242 of file openvpn.h.
SOCKET_WRITE
#define SOCKET_WRITE (1<<1)
Definition at line 243 of file openvpn.h.
TLS_MODE
#define TLS_MODE (c) ((c)->c2.tls_multi != NULL)
Definition at line 552 of file openvpn.h.
TUN_READ
#define TUN_READ (1<<2)
Definition at line 244 of file openvpn.h.
TUN_WRITE
#define TUN_WRITE (1<<3)
Definition at line 245 of file openvpn.h.
Function Documentation
is_cas_pending()
static bool is_cas_pending (enum client_connect_status cas) inline static
Definition at line 215 of file openvpn.h.
References CAS_PENDING, CAS_PENDING_DEFERRED, and CAS_PENDING_DEFERRED_PARTIAL.
Referenced by multi_process_post().
packet_id_persist_init()
static void packet_id_persist_init (struct packet_id_persist * p) inline static
Definition at line 84 of file openvpn.h.
Referenced by context_init_1(), and inherit_context_child().