OpenVPN: src/openvpn/openvpn.c File Reference
openvpn.c File Reference
#include "syshead.h"
#include "init.h"
#include "forward.h"
#include "multi.h"
#include "win32.h"
#include "platform.h"
#include "memdbg.h"
Macros
#define P2P_CHECK_SIG() EVENT_LOOP_CHECK_SIGNAL(c, process_signal_p2p, c);
Functions
static bool process_signal_p2p (struct context *c)
static void tunnel_point_to_point (struct context *c)
Main event loop for OpenVPN in client mode, where only one VPN tunnel is active.
void init_early (struct context *c)
static void uninit_early (struct context *c)
static int openvpn_main (int argc, char *argv[])
OpenVPN's main init-run-cleanup loop.
int wmain (int argc, wchar_t *wargv[])
Macro Definition Documentation
P2P_CHECK_SIG
#define P2P_CHECK_SIG () EVENT_LOOP_CHECK_SIGNAL(c, process_signal_p2p, c);
Definition at line 40 of file openvpn.c.
Function Documentation
init_early()
void init_early (struct context * c)
Definition at line 108 of file openvpn.c.
References crypto_load_provider(), init_verb_mute(), IVM_LEVEL_1, MAX_PARMS, provider_list::names, context::net_ctx, net_ctx_init(), context::options, provider_list::providers, and options::providers.
Referenced by openvpn_main().
openvpn_main()
static int openvpn_main (int argc, char * argv[]) static
OpenVPN's main init-run-cleanup loop.
This function contains the two outer OpenVPN loops. Its structure is as follows:
Once-per-process initialization.
Outer loop, run at startup and then once per SIGHUP:
Level 1 initialization
Inner loop, run at startup and then once per SIGUSR1:
Call event loop function depending on client or server mode:
tunnel_point_to_point()
tunnel_server()
Level 1 cleanup
Once-per-process cleanup.
Parameters
argc - Commandline argument count.
argv - Commandline argument values.
Definition at line 158 of file openvpn.c.
References ASSERT, options::chroot_dir, CLEAR, close_management(), context_clear_all_except_first_time(), context_gc_free(), context_init_1(), context::did_we_daemonize, do_genkey(), do_persist_tuntap(), do_test_crypto(), env_set_create(), env_set_destroy(), context::es, context::first_time, context::gc, gc_init(), gc_reset(), init_early(), init_management(), init_options(), init_options_dev(), init_plugins(), init_query_passwords(), init_static(), init_verb_mute(), IS_SIG, IVM_LEVEL_1, M_INFO, M_USAGE, options::management_flags, MF_QUERY_PASSWORDS, options::mode, MODE_POINT_TO_POINT, MODE_SERVER, msg, context::net_ctx, open_management(), open_plugins(), openvpn_exit(), OPENVPN_EXIT_STATUS_GOOD, OPENVPN_PLUGIN_INIT_PRE_CONFIG_PARSE, OPT_P_DEFAULT, context::options, options_postprocess(), parse_argv(), possibly_become_daemon(), pre_init_signal_catch(), pre_setup(), print_openssl_info(), print_signal(), set_win_sys_path_via_env(), setenv_settings(), show_library_versions(), show_settings(), show_windows_version(), context::sig, SIGHUP, siginfo_static, signal_info::signal_received, signal_restart_status(), SIGUSR1, title_string, tunnel_point_to_point(), tunnel_server(), uninit_early(), uninit_options(), uninit_static(), write_pid_file(), and options::writepid.
Referenced by wmain().
process_signal_p2p()
static bool process_signal_p2p (struct context * c) static
Definition at line 43 of file openvpn.c.
References process_signal(), and remap_signal().
tunnel_point_to_point()
static void tunnel_point_to_point (struct context * c) static
Main event loop for OpenVPN in client mode, where only one VPN tunnel is active.
Parameters
c - The context structure of the single active VPN tunnel.
Definition at line 59 of file openvpn.c.
References context::c2, CC_HARD_USR1_TO_HUP, close_instance(), CM_P2P, context_clear_2(), context::es, ES_TIMEOUT, context_2::event_set_status, init_instance_handle_signals(), io_wait(), IS_SIG, context::mode, P2P_CHECK_SIG, p2p_iow_flags(), PERF_EVENT_LOOP, perf_pop(), perf_push(), pre_select(), process_io(), and uninit_management_callback().
Referenced by openvpn_main().
uninit_early()
static void uninit_early (struct context * c) static
Definition at line 125 of file openvpn.c.
References crypto_unload_provider(), MAX_PARMS, provider_list::names, context::net_ctx, net_ctx_free(), context::options, provider_list::providers, and options::providers.
Referenced by openvpn_main().
wmain()
int wmain (int argc, wchar_t * wargv[])
Definition at line 358 of file openvpn.c.
References openvpn_main().