OpenVPN: src/openvpn/options.h File Reference
options.h File Reference
#include "basic.h"
#include "common.h"
#include "mtu.h"
#include "route.h"
#include "tun.h"
#include "socket.h"
#include "plugin.h"
#include "manage.h"
#include "proxy.h"
#include "comp.h"
#include "pushlist.h"
#include "clinat.h"
#include "crypto_backend.h"
Data Structures
struct options_pre_pull
struct connection_entry
struct remote_entry
struct connection_list
struct remote_list
struct provider_list
struct remote_host_store
struct options
Macros
#define MAX_PARMS 16
#define OPTION_PARM_SIZE 256
#define OPTION_LINE_SIZE 256
#define CE_DISABLED (1<<0)
#define CE_MAN_QUERY_PROXY (1<<1)
#define CE_MAN_QUERY_REMOTE_UNDEF 0
#define CE_MAN_QUERY_REMOTE_QUERY 1
#define CE_MAN_QUERY_REMOTE_ACCEPT 2
#define CE_MAN_QUERY_REMOTE_MOD 3
#define CE_MAN_QUERY_REMOTE_SKIP 4
#define CE_MAN_QUERY_REMOTE_MASK (0x07)
#define CE_MAN_QUERY_REMOTE_SHIFT (2)
#define CONNECTION_LIST_SIZE 64
#define RH_HOST_LEN 80
#define RH_PORT_LEN 20
#define MODE_POINT_TO_POINT 0
#define MODE_SERVER 1
#define PING_UNDEF 0
#define PING_EXIT 1
#define PING_RESTART 2
#define SF_NOPOOL (1<<0)
#define SF_TCP_NODELAY_HELPER (1<<1)
#define SF_NO_PUSH_ROUTE_GATEWAY (1<<2)
#define streq(x, y) (!strcmp((x), (y)))
#define OPT_P_GENERAL (1<<0)
#define OPT_P_UP (1<<1)
#define OPT_P_ROUTE (1<<2)
#define OPT_P_IPWIN32 (1<<3)
#define OPT_P_SCRIPT (1<<4)
#define OPT_P_SETENV (1<<5)
#define OPT_P_SHAPER (1<<6)
#define OPT_P_TIMER (1<<7)
#define OPT_P_PERSIST (1<<8)
#define OPT_P_PERSIST_IP (1<<9)
#define OPT_P_COMP (1<<10) /* TODO */
#define OPT_P_MESSAGES (1<<11)
#define OPT_P_NCP (1<<12)
Negotiable crypto parameters.
#define OPT_P_TLS_PARMS (1<<13) /* TODO */
#define OPT_P_MTU (1<<14) /* TODO */
#define OPT_P_NICE (1<<15)
#define OPT_P_PUSH (1<<16)
#define OPT_P_INSTANCE (1<<17)
allowed in ccd, client-connect etc
#define OPT_P_CONFIG (1<<18)
#define OPT_P_EXPLICIT_NOTIFY (1<<19)
#define OPT_P_ECHO (1<<20)
#define OPT_P_INHERIT (1<<21)
#define OPT_P_ROUTE_EXTRAS (1<<22)
#define OPT_P_PULL_MODE (1<<23)
#define OPT_P_PLUGIN (1<<24)
#define OPT_P_SOCKBUF (1<<25)
#define OPT_P_SOCKFLAGS (1<<26)
#define OPT_P_CONNECTION (1<<27)
#define OPT_P_PEER_ID (1<<28)
#define OPT_P_INLINE (1<<29)
#define OPT_P_DEFAULT (~(OPT_P_INSTANCE|OPT_P_PULL_MODE))
#define PULL_DEFINED(opt) ((opt)->pull)
#define PUSH_DEFINED(opt) ((opt)->push_list)
#define ROUTE_OPTION_FLAGS(o) ((o)->route_method & ROUTE_METHOD_MASK)
#define SHAPER_DEFINED(opt) ((opt)->shaper)
#define PLUGIN_OPTION_LIST(opt) ((opt)->plugin_list)
#define MAN_CLIENT_AUTH_ENABLED(opt) (false)
#define AR_NONE 0
#define AR_INTERACT 1
#define AR_NOINTERACT 2
Enumerations
enum vlan_acceptable_frames { VLAN_ONLY_TAGGED, VLAN_ONLY_UNTAGGED_OR_PRIORITY, VLAN_ALL }
enum genkey_type { GENKEY_SECRET, GENKEY_TLS_CRYPTV2_CLIENT, GENKEY_TLS_CRYPTV2_SERVER, GENKEY_AUTH_TOKEN }
Functions
void parse_argv (struct options *options, const int argc, char *argv[], const int msglevel, const unsigned int permission_mask, unsigned int *option_types_found, struct env_set *es)
void notnull (const char *arg, const char *description)
void usage_small (void)
void show_library_versions (const unsigned int flags)
void show_windows_version (const unsigned int flags)
void init_options (struct options *o, const bool init_gc)
void uninit_options (struct options *o)
void setenv_settings (struct env_set *es, const struct options *o)
void show_settings (const struct options *o)
bool string_defined_equal (const char *s1, const char *s2)
const char * options_string_version (const char *s, struct gc_arena *gc)
char * options_string (const struct options *o, const struct frame *frame, struct tuntap *tt, openvpn_net_ctx_t *ctx, bool remote, struct gc_arena *gc)
bool options_cmp_equal_safe (char *actual, const char *expected, size_t actual_n)
void options_warning_safe (char *actual, const char *expected, size_t actual_n)
bool options_cmp_equal (char *actual, const char *expected)
void options_warning (char *actual, const char *expected)
char * options_string_extract_option (const char *options_string, const char *opt_name, struct gc_arena *gc)
Given an OpenVPN options string, extract the value of an option.
void options_postprocess (struct options *options)
void pre_pull_save (struct options *o)
void pre_pull_restore (struct options *o, struct gc_arena *gc)
bool apply_push_options (struct options *options, struct buffer *buf, unsigned int permission_mask, unsigned int *option_types_found, struct env_set *es)
void options_detach (struct options *o)
void options_server_import (struct options *o, const char *filename, int msglevel, unsigned int permission_mask, unsigned int *option_types_found, struct env_set *es)
void pre_pull_default (struct options *o)
void rol_check_alloc (struct options *options)
int parse_line (const char *line, char *p[], const int n, const char *file, const int line_num, int msglevel, struct gc_arena *gc)
int parse_topology (const char *str, const int msglevel)
const char * print_topology (const int topology)
int auth_retry_get (void)
bool auth_retry_set (const int msglevel, const char *option)
const char * auth_retry_print (void)
void options_string_import (struct options *options, const char *config, const int msglevel, const unsigned int permission_mask, unsigned int *option_types_found, struct env_set *es)
Variables
const char title_string []
Macro Definition Documentation
AR_INTERACT
#define AR_INTERACT 1
Definition at line 852 of file options.h.
AR_NOINTERACT
#define AR_NOINTERACT 2
Definition at line 853 of file options.h.
AR_NONE
#define AR_NONE 0
Definition at line 851 of file options.h.
CE_DISABLED
#define CE_DISABLED (1<<0)
Definition at line 130 of file options.h.
CE_MAN_QUERY_PROXY
#define CE_MAN_QUERY_PROXY (1<<1)
Definition at line 131 of file options.h.
CE_MAN_QUERY_REMOTE_ACCEPT
#define CE_MAN_QUERY_REMOTE_ACCEPT 2
Definition at line 134 of file options.h.
CE_MAN_QUERY_REMOTE_MASK
#define CE_MAN_QUERY_REMOTE_MASK (0x07)
Definition at line 137 of file options.h.
CE_MAN_QUERY_REMOTE_MOD
#define CE_MAN_QUERY_REMOTE_MOD 3
Definition at line 135 of file options.h.
CE_MAN_QUERY_REMOTE_QUERY
#define CE_MAN_QUERY_REMOTE_QUERY 1
Definition at line 133 of file options.h.
CE_MAN_QUERY_REMOTE_SHIFT
#define CE_MAN_QUERY_REMOTE_SHIFT (2)
Definition at line 138 of file options.h.
CE_MAN_QUERY_REMOTE_SKIP
#define CE_MAN_QUERY_REMOTE_SKIP 4
Definition at line 136 of file options.h.
CE_MAN_QUERY_REMOTE_UNDEF
#define CE_MAN_QUERY_REMOTE_UNDEF 0
Definition at line 132 of file options.h.
CONNECTION_LIST_SIZE
#define CONNECTION_LIST_SIZE 64
Definition at line 164 of file options.h.
MAN_CLIENT_AUTH_ENABLED
#define MAN_CLIENT_AUTH_ENABLED (opt) (false)
Definition at line 741 of file options.h.
MAX_PARMS
#define MAX_PARMS 16
Definition at line 51 of file options.h.
MODE_POINT_TO_POINT
#define MODE_POINT_TO_POINT 0
Definition at line 219 of file options.h.
MODE_SERVER
#define MODE_SERVER 1
Definition at line 220 of file options.h.
OPT_P_COMP
#define OPT_P_COMP (1<<10) /* TODO */
Definition at line 684 of file options.h.
OPT_P_CONFIG
#define OPT_P_CONFIG (1<<18)
Definition at line 692 of file options.h.
OPT_P_CONNECTION
#define OPT_P_CONNECTION (1<<27)
Definition at line 701 of file options.h.
OPT_P_DEFAULT
#define OPT_P_DEFAULT (~(OPT_P_INSTANCE|OPT_P_PULL_MODE))
Definition at line 705 of file options.h.
OPT_P_ECHO
#define OPT_P_ECHO (1<<20)
Definition at line 694 of file options.h.
OPT_P_EXPLICIT_NOTIFY
#define OPT_P_EXPLICIT_NOTIFY (1<<19)
Definition at line 693 of file options.h.
OPT_P_GENERAL
#define OPT_P_GENERAL (1<<0)
Definition at line 674 of file options.h.
OPT_P_INHERIT
#define OPT_P_INHERIT (1<<21)
Definition at line 695 of file options.h.
OPT_P_INLINE
#define OPT_P_INLINE (1<<29)
Definition at line 703 of file options.h.
OPT_P_INSTANCE
#define OPT_P_INSTANCE (1<<17)
allowed in ccd, client-connect etc
Definition at line 691 of file options.h.
OPT_P_IPWIN32
#define OPT_P_IPWIN32 (1<<3)
Definition at line 677 of file options.h.
OPT_P_MESSAGES
#define OPT_P_MESSAGES (1<<11)
Definition at line 685 of file options.h.
OPT_P_MTU
#define OPT_P_MTU (1<<14) /* TODO */
Definition at line 688 of file options.h.
OPT_P_NCP
#define OPT_P_NCP (1<<12)
Negotiable crypto parameters.
Definition at line 686 of file options.h.
OPT_P_NICE
#define OPT_P_NICE (1<<15)
Definition at line 689 of file options.h.
OPT_P_PEER_ID
#define OPT_P_PEER_ID (1<<28)
Definition at line 702 of file options.h.
OPT_P_PERSIST
#define OPT_P_PERSIST (1<<8)
Definition at line 682 of file options.h.
OPT_P_PERSIST_IP
#define OPT_P_PERSIST_IP (1<<9)
Definition at line 683 of file options.h.
OPT_P_PLUGIN
#define OPT_P_PLUGIN (1<<24)
Definition at line 698 of file options.h.
OPT_P_PULL_MODE
#define OPT_P_PULL_MODE (1<<23)
Definition at line 697 of file options.h.
OPT_P_PUSH
#define OPT_P_PUSH (1<<16)
Definition at line 690 of file options.h.
OPT_P_ROUTE
#define OPT_P_ROUTE (1<<2)
Definition at line 676 of file options.h.
OPT_P_ROUTE_EXTRAS
#define OPT_P_ROUTE_EXTRAS (1<<22)
Definition at line 696 of file options.h.
OPT_P_SCRIPT
#define OPT_P_SCRIPT (1<<4)
Definition at line 678 of file options.h.
OPT_P_SETENV
#define OPT_P_SETENV (1<<5)
Definition at line 679 of file options.h.
OPT_P_SHAPER
#define OPT_P_SHAPER (1<<6)
Definition at line 680 of file options.h.
OPT_P_SOCKBUF
#define OPT_P_SOCKBUF (1<<25)
Definition at line 699 of file options.h.
OPT_P_SOCKFLAGS
#define OPT_P_SOCKFLAGS (1<<26)
Definition at line 700 of file options.h.
OPT_P_TIMER
#define OPT_P_TIMER (1<<7)
Definition at line 681 of file options.h.
OPT_P_TLS_PARMS
#define OPT_P_TLS_PARMS (1<<13) /* TODO */
Definition at line 687 of file options.h.
OPT_P_UP
#define OPT_P_UP (1<<1)
Definition at line 675 of file options.h.
OPTION_LINE_SIZE
#define OPTION_LINE_SIZE 256
Definition at line 57 of file options.h.
OPTION_PARM_SIZE
#define OPTION_PARM_SIZE 256
Definition at line 56 of file options.h.
PING_EXIT
#define PING_EXIT 1
Definition at line 299 of file options.h.
PING_RESTART
#define PING_RESTART 2
Definition at line 300 of file options.h.
PING_UNDEF
#define PING_UNDEF 0
Definition at line 298 of file options.h.
PLUGIN_OPTION_LIST
#define PLUGIN_OPTION_LIST (opt) ((opt)->plugin_list)
Definition at line 733 of file options.h.
PULL_DEFINED
#define PULL_DEFINED (opt) ((opt)->pull)
Definition at line 708 of file options.h.
PUSH_DEFINED
#define PUSH_DEFINED (opt) ((opt)->push_list)
Definition at line 709 of file options.h.
RH_HOST_LEN
#define RH_HOST_LEN 80
Definition at line 196 of file options.h.
RH_PORT_LEN
#define RH_PORT_LEN 20
Definition at line 198 of file options.h.
ROUTE_OPTION_FLAGS
#define ROUTE_OPTION_FLAGS (o) ((o)->route_method & ROUTE_METHOD_MASK)
Definition at line 721 of file options.h.
SF_NO_PUSH_ROUTE_GATEWAY
#define SF_NO_PUSH_ROUTE_GATEWAY (1<<2)
Definition at line 430 of file options.h.
SF_NOPOOL
#define SF_NOPOOL (1<<0)
Definition at line 428 of file options.h.
SF_TCP_NODELAY_HELPER
#define SF_TCP_NODELAY_HELPER (1<<1)
Definition at line 429 of file options.h.
SHAPER_DEFINED
#define SHAPER_DEFINED (opt) ((opt)->shaper)
Definition at line 727 of file options.h.
streq
#define streq (x, y) (!strcmp((x), (y)))
Definition at line 669 of file options.h.
Enumeration Type Documentation
genkey_type
enum genkey_type
Enumerator
GENKEY_SECRET
GENKEY_TLS_CRYPTV2_CLIENT
GENKEY_TLS_CRYPTV2_SERVER
GENKEY_AUTH_TOKEN
Definition at line 202 of file options.h.
vlan_acceptable_frames
enum vlan_acceptable_frames
Enumerator
VLAN_ONLY_TAGGED
VLAN_ONLY_UNTAGGED_OR_PRIORITY
VLAN_ALL
Definition at line 187 of file options.h.
Function Documentation
apply_push_options()
bool apply_push_options (struct options * options, struct buffer * buf, unsigned int permission_mask, unsigned int * option_types_found, struct env_set * es)
Definition at line 5034 of file options.c.
References add_option(), apply_pull_filter(), buf_parse(), CLEAR, D_PUSH_ERRORS, options::gc, M_OPTERR, MAX_PARMS, OPTION_PARM_SIZE, parse_line(), and SIZE.
Referenced by process_incoming_push_reply().
auth_retry_get()
int auth_retry_get (void)
Definition at line 4306 of file options.c.
References global_auth_retry.
Referenced by do_init_crypto_tls_c1(), init_instance(), receive_auth_failed(), and socket_restart_pause().
auth_retry_print()
const char* auth_retry_print (void)
Definition at line 4335 of file options.c.
References AR_INTERACT, AR_NOINTERACT, AR_NONE, and global_auth_retry.
Referenced by man_dispatch_command().
auth_retry_set()
bool auth_retry_set (const int msglevel, const char * option)
Definition at line 4312 of file options.c.
References AR_INTERACT, AR_NOINTERACT, AR_NONE, global_auth_retry, msg, and streq.
Referenced by add_option(), and man_dispatch_command().
init_options()
void init_options (struct options * o, const bool init_gc)
Definition at line 799 of file options.c.
References connection_entry::af, options::allow_recursive_routing, options::auth_token_generate, options::authname, connection_entry::bind_ipv6_only, connection_entry::bind_local, options::block_outside_dns, options::ce, CLEAR, options::connect_retry_max, connection_entry::connect_retry_seconds, connection_entry::connect_retry_seconds_max, connection_entry::connect_timeout, DEFAULT_SEQ_BACKTRACK, DEFAULT_TIME_BACKTRACK, tuntap_options::dhcp_lease_time, tuntap_options::dhcp_masq_offset, options::ecdh_curve, options::gc, gc_init(), options::gc_owned, options::handshake_window, options::ifconfig_pool_persist_refresh_freq, tuntap_options::ip_win32_type, IPW32_SET_ADAPTIVE, IPW32_SET_DHCP_MASQ, options::key_direction, KEY_DIRECTION_BIDIRECTIONAL, connection_entry::link_mtu, LINK_MTU_DEFAULT, connection_entry::local_port, options::management_echo_buffer_size, options::management_log_history_cache, options::management_state_buffer_size, options::max_clients, options::max_routes_per_client, options::mode, MODE_POINT_TO_POINT, connection_entry::mssfix, MSSFIX_DEFAULT, connection_entry::mtu_discover_type, options::n_bcast_buf, options::ncp_ciphers, options::ncp_enabled, options::occ, OPENVPN_PORT, options::persist_mode, options::prng_hash, options::prng_nonce_secret_len, connection_entry::proto, options::proto_force, PROTO_UDP, options::real_hash_size, connection_entry::remote_port, options::renegotiate_bytes, options::renegotiate_seconds, options::renegotiate_seconds_min, options::replay, options::replay_time, options::replay_window, RESOLV_RETRY_INFINITE, options::resolve_in_advance, options::resolve_retry_seconds, options::route_delay_window, options::route_method, ROUTE_METHOD_ADAPTIVE, options::scheduled_exit_interval, options::stale_routes_check_interval, options::status_file_update_freq, options::status_file_version, options::tcp_queue_limit, options::tls_cert_profile, options::tls_timeout, options::tmp_dir, TOP_NET30, options::topology, options::transition_window, connection_entry::tun_mtu, TUN_MTU_DEFAULT, options::tuntap_options, options::verbosity, options::virtual_hash_size, options::vlan_accept, VLAN_ALL, options::vlan_pvid, win_get_tempdir(), options::windows_driver, WINDOWS_DRIVER_TAP_WINDOWS6, and X509_USERNAME_FIELD_DEFAULT.
Referenced by add_option(), openvpn_main(), options_postprocess_verify_ce(), and usage().
notnull()
void notnull (const char * arg, const char * description)
Definition at line 4444 of file options.c.
References M_USAGE, and msg.
Referenced by do_persist_tuntap(), options_postprocess_mutate(), and options_postprocess_verify_ce().
options_cmp_equal()
bool options_cmp_equal (char * actual, const char * expected)
Definition at line 3976 of file options.c.
References options_cmp_equal_safe().
Referenced by key_method_2_read().
options_cmp_equal_safe()
bool options_cmp_equal_safe (char * actual, const char * expected, size_t actual_n)
Definition at line 4118 of file options.c.
References D_SHOW_OCC, gc_free(), gc_new(), msg, and options_warning_safe_ml().
Referenced by options_cmp_equal(), and process_received_occ_msg().
options_detach()
void options_detach (struct options * o)
Definition at line 1411 of file options.c.
References options::client_nat, clone_push_list(), options::gc, gc_detach(), and options::routes.
Referenced by do_test_crypto(), inherit_context_child(), and inherit_context_top().
options_postprocess()
void options_postprocess (struct options * options)
Definition at line 3561 of file options.c.
References options_postprocess_filechecks(), options_postprocess_mutate(), and options_postprocess_verify().
Referenced by openvpn_main().
options_server_import()
void options_server_import (struct options * o, const char * filename, int msglevel, unsigned int permission_mask, unsigned int * option_types_found, struct env_set * es)
Definition at line 5064 of file options.c.
References D_PUSH, msg, and read_config_file().
Referenced by multi_client_connect_post(), and multi_client_connect_source_ccd().
options_string()
char* options_string (const struct options * o, const struct frame * frame, struct tuntap * tt, openvpn_net_ctx_t * ctx, bool remote, struct gc_arena * gc)
Definition at line 3762 of file options.c.
References alloc_buf(), ASSERT, options::authname, BSTR, buf_printf(), calc_options_string_link_mtu(), options::ce, key_type::cipher, cipher_kt_name(), key_type::cipher_length, options::ciphername, options::dev, options::dev_type, dev_type_string(), key_type::digest, connection_entry::fragment, options::ifconfig_ipv6_local, options::ifconfig_ipv6_netbits, options::ifconfig_ipv6_remote, options::ifconfig_local, options::ifconfig_nowarn, ifconfig_options_string(), options::ifconfig_remote_netmask, init_key_type(), init_tun(), options::key_direction, KEY_METHOD_2, keydirection2ascii(), options::keysize, md_kt_name(), options::mode, MODE_POINT_TO_POINT, options::ncp_ciphers, options::ncp_enabled, OPTION_LINE_SIZE, PAYLOAD_SIZE, connection_entry::proto, proto_remote(), PULL_DEFINED, options::replay, options::shared_secret_file, connection_entry::tls_auth_file, TLS_CLIENT, tls_item_in_cipher_list(), TLS_SERVER, and options::topology.
Referenced by do_compute_occ_strings(), and options_string_extract_option().
options_string_extract_option()
char* options_string_extract_option (const char * options_string, const char * opt_name, struct gc_arena * gc)
Given an OpenVPN options string, extract the value of an option.
Parameters
options_string Zero-terminated, comma-separated options string
opt_name The name of the option to extract
gc The gc to allocate the return value
Returns
gc-allocated value of option with name opt_name if option was found, or NULL otherwise.
Definition at line 4155 of file options.c.
References gc_malloc(), and options_string().
Referenced by key_method_2_read().
options_string_import()
void options_string_import (struct options * options, const char * config, const int msglevel, const unsigned int permission_mask, unsigned int * option_types_found, struct env_set * es)
Definition at line 5084 of file options.c.
References read_config_string().
Referenced by multi_client_connect_mda(), multi_client_connect_post_plugin(), and open_plugins().
options_string_version()
const char* options_string_version (const char * s, struct gc_arena * gc)
Definition at line 4147 of file options.c.
References alloc_buf_gc(), BPTR, BSTR, and strncpynt().
Referenced by do_compute_occ_strings().
options_warning()
void options_warning (char * actual, const char * expected)
Definition at line 3982 of file options.c.
References options_warning_safe().
Referenced by key_method_2_read().
options_warning_safe()
void options_warning_safe (char * actual, const char * expected, size_t actual_n)
Definition at line 4141 of file options.c.
References M_WARN, and options_warning_safe_ml().
Referenced by options_warning(), and process_received_occ_msg().
parse_argv()
void parse_argv (struct options * options, const int argc, char * argv[], const int msglevel, const unsigned int permission_mask, unsigned int * option_types_found, struct env_set * es)
Definition at line 4921 of file options.c.
References add_option(), CLEAR, MAX_PARMS, msg, and usage().
Referenced by openvpn_main().
parse_line()
int parse_line (const char * line, char * p[], const int n, const char * file, const int line_num, int msglevel, struct gc_arena * gc)
Definition at line 4497 of file options.c.
References gc_malloc(), M_INFO, M_MSG_VIRT_OUT, M_NOPREFIX, M_OPTERR, msg, OPTION_PARM_SIZE, PACKAGE, SIZE, and space().
Referenced by apply_push_options(), argv_parse_cmd(), make_arg_array(), man_process_command(), read_config_file(), read_config_string(), and remove_iroutes_from_push_route_list().
parse_topology()
int parse_topology (const char * str, const int msglevel)
Definition at line 4254 of file options.c.
References msg, streq, TOP_NET30, TOP_P2P, TOP_SUBNET, and TOP_UNDEF.
Referenced by add_option().
pre_pull_default()
void pre_pull_default (struct options * o)
pre_pull_restore()
void pre_pull_restore (struct options * o, struct gc_arena * gc)
Definition at line 3612 of file options.c.
References CLEAR, options_pre_pull::client_nat, options::client_nat, options_pre_pull::client_nat_defined, cnol_check_alloc(), copy_client_nat_option_list(), copy_route_ipv6_option_list(), copy_route_option_list(), options_pre_pull::foreign_option_index, options::foreign_option_index, options_pre_pull::ping_rec_timeout, options::ping_rec_timeout, options_pre_pull::ping_rec_timeout_action, options::ping_rec_timeout_action, options_pre_pull::ping_send_timeout, options::ping_send_timeout, options::pre_pull, options::push_continuation, options::push_option_types_found, rol6_check_alloc(), rol_check_alloc(), options_pre_pull::route_default_gateway, options::route_default_gateway, options_pre_pull::route_ipv6_default_gateway, options::route_ipv6_default_gateway, options_pre_pull::routes, options::routes, options_pre_pull::routes_defined, options_pre_pull::routes_ipv6, options::routes_ipv6, options_pre_pull::routes_ipv6_defined, options_pre_pull::tuntap_options, options::tuntap_options, and options_pre_pull::tuntap_options_defined.
Referenced by process_incoming_push_reply().
pre_pull_save()
void pre_pull_save (struct options * o)
Definition at line 3577 of file options.c.
References ALLOC_OBJ_CLEAR_GC, options_pre_pull::client_nat, options::client_nat, options_pre_pull::client_nat_defined, clone_client_nat_option_list(), clone_route_ipv6_option_list(), clone_route_option_list(), options_pre_pull::foreign_option_index, options::foreign_option_index, options::gc, options_pre_pull::ping_rec_timeout, options::ping_rec_timeout, options_pre_pull::ping_rec_timeout_action, options::ping_rec_timeout_action, options_pre_pull::ping_send_timeout, options::ping_send_timeout, options::pre_pull, options::pull, options_pre_pull::route_default_gateway, options::route_default_gateway, options_pre_pull::route_ipv6_default_gateway, options::route_ipv6_default_gateway, options_pre_pull::routes, options::routes, options_pre_pull::routes_defined, options_pre_pull::routes_ipv6, options::routes_ipv6, options_pre_pull::routes_ipv6_defined, options_pre_pull::tuntap_options, options::tuntap_options, and options_pre_pull::tuntap_options_defined.
Referenced by options_postprocess_mutate().
print_topology()
const char* print_topology (const int topology)
Definition at line 4276 of file options.c.
References TOP_NET30, TOP_P2P, TOP_SUBNET, and TOP_UNDEF.
Referenced by print_opt_topology().
rol_check_alloc()
void rol_check_alloc (struct options * options)
Definition at line 1420 of file options.c.
References options::gc, new_route_option_list(), and options::routes.
Referenced by add_option(), helper_add_route(), and pre_pull_restore().
setenv_settings()
void setenv_settings (struct env_set * es, const struct options * o)
Definition at line 996 of file options.c.
References connection_list::array, options::ce, options::config, options::connection_list, options::daemon, connection_list::len, options::log, platform_getpid(), setenv_connection_entry(), setenv_int(), setenv_long_long(), setenv_str(), and options::verbosity.
Referenced by openvpn_main().
show_library_versions()
void show_library_versions (const unsigned int flags)
Definition at line 4408 of file options.c.
References get_ssl_library_version(), LZO_LIB_VER_STR, and msg.
Referenced by openvpn_main(), and usage_version().
show_settings()
void show_settings (const struct options * o)
Definition at line 1532 of file options.c.
References options::client_nat, D_SHOW_PARMS, daemon(), options::key_direction, keydirection2ascii(), machine_readable_output, options::management_flags, MAX_PARMS, MF_EXTERNAL_CERT, MF_EXTERNAL_KEY, msg, options::plugin_list, plugin_option_list_print(), print_client_nat_list(), print_route_options(), options::pull_filter_list, push_peer_info(), options::routes, SHOW_BOOL, show_connection_entries(), SHOW_INT, SHOW_INT64, show_p2mp_parms(), SHOW_PARM, show_pull_filter_list(), SHOW_STR, SHOW_STR_INLINE, show_tuntap_options(), suppress_timestamps, test_crypto(), tls_verify(), and options::tuntap_options.
Referenced by openvpn_main().
show_windows_version()
void show_windows_version (const unsigned int flags)
Definition at line 4399 of file options.c.
References gc_free(), gc_new(), msg, and win32_version_string().
Referenced by openvpn_main(), and usage_version().
string_defined_equal()
bool string_defined_equal (const char * s1, const char * s2)
Definition at line 4453 of file options.c.
Referenced by options_postprocess_verify_ce().
uninit_options()
void uninit_options (struct options * o)
Definition at line 909 of file options.c.
References options::gc, gc_free(), and options::gc_owned.
Referenced by add_option(), openvpn_main(), and options_postprocess_verify_ce().
usage_small()
void usage_small (void)
Definition at line 4391 of file options.c.
References M_NOPREFIX, M_WARN, msg, openvpn_exit(), and OPENVPN_EXIT_STATUS_USAGE.
Referenced by x_msg_va().
Variable Documentation
title_string
const char title_string[]
Definition at line 67 of file options.c.
Referenced by _tmain(), do_test_crypto(), man_dispatch_command(), man_help(), multi_print_status(), openvpn_main(), usage(), and usage_version().