OpenVPN: src/openvpn/packet_id.h File Reference
packet_id.h File Reference
#include "circ_list.h"
#include "buffer.h"
#include "error.h"
#include "otime.h"
Data Structures
struct packet_id_rec
struct packet_id_persist
struct packet_id_persist_file_image
struct packet_id_send
struct packet_id_net
struct packet_id
Macros
#define PACKET_ID_MAX UINT32_MAX
#define PACKET_ID_WRAP_TRIGGER 0xFF000000
#define htonpid(x) htonl(x)
#define ntohpid(x) ntohl(x)
#define htontime(x) htonl((net_time_t)x)
#define ntohtime(x) ((time_t)ntohl(x))
#define packet_id_format "%u"
#define MIN_SEQ_BACKTRACK 0
#define MAX_SEQ_BACKTRACK 65536
#define DEFAULT_SEQ_BACKTRACK 64
#define MIN_TIME_BACKTRACK 0
#define MAX_TIME_BACKTRACK 600
#define DEFAULT_TIME_BACKTRACK 15
#define SEQ_REAP_INTERVAL 5
Typedefs
typedef uint32_t packet_id_type
typedef uint32_t net_time_t
typedef unsigned int packet_id_print_type
Functions
CIRC_LIST (seq_list, time_t)
void packet_id_init (struct packet_id *p, int seq_backtrack, int time_backtrack, const char *name, int unit)
void packet_id_free (struct packet_id *p)
bool packet_id_test (struct packet_id_rec *p, const struct packet_id_net *pin)
void packet_id_add (struct packet_id_rec *p, const struct packet_id_net *pin)
void packet_id_reap (struct packet_id_rec *p)
void packet_id_persist_init (struct packet_id_persist *p)
void packet_id_persist_close (struct packet_id_persist *p)
void packet_id_persist_load (struct packet_id_persist *p, const char *filename)
void packet_id_persist_save (struct packet_id_persist *p)
void packet_id_persist_load_obj (const struct packet_id_persist *p, struct packet_id *pid)
const char * packet_id_persist_print (const struct packet_id_persist *p, struct gc_arena *gc)
bool packet_id_read (struct packet_id_net *pin, struct buffer *buf, bool long_form)
bool packet_id_write (struct packet_id_send *p, struct buffer *buf, bool long_form, bool prepend)
Write a packet ID to buf, and update the packet ID state.
static bool packet_id_initialized (const struct packet_id *pid)
Is this struct packet_id initialized?
static bool packet_id_persist_enabled (const struct packet_id_persist *p)
static void packet_id_persist_save_obj (struct packet_id_persist *p, const struct packet_id *pid)
const char * packet_id_net_print (const struct packet_id_net *pin, bool print_timestamp, struct gc_arena *gc)
static int packet_id_size (bool long_form)
static bool packet_id_close_to_wrapping (const struct packet_id_send *p)
static bool check_timestamp_delta (time_t remote, unsigned int max_delta)
static void packet_id_reap_test (struct packet_id_rec *p)
Macro Definition Documentation
DEFAULT_SEQ_BACKTRACK
#define DEFAULT_SEQ_BACKTRACK 64
Definition at line 105 of file packet_id.h.
DEFAULT_TIME_BACKTRACK
#define DEFAULT_TIME_BACKTRACK 15
Definition at line 114 of file packet_id.h.
htonpid
#define htonpid (x) htonl(x)
Definition at line 61 of file packet_id.h.
htontime
#define htontime (x) htonl((net_time_t)x)
Definition at line 67 of file packet_id.h.
MAX_SEQ_BACKTRACK
#define MAX_SEQ_BACKTRACK 65536
Definition at line 104 of file packet_id.h.
MAX_TIME_BACKTRACK
#define MAX_TIME_BACKTRACK 600
Definition at line 113 of file packet_id.h.
MIN_SEQ_BACKTRACK
#define MIN_SEQ_BACKTRACK 0
Definition at line 103 of file packet_id.h.
MIN_TIME_BACKTRACK
#define MIN_TIME_BACKTRACK 0
Definition at line 112 of file packet_id.h.
ntohpid
#define ntohpid (x) ntohl(x)
Definition at line 64 of file packet_id.h.
ntohtime
#define ntohtime (x) ((time_t)ntohl(x))
Definition at line 70 of file packet_id.h.
packet_id_format
#define packet_id_format "%u"
Definition at line 95 of file packet_id.h.
PACKET_ID_MAX
#define PACKET_ID_MAX UINT32_MAX
Definition at line 50 of file packet_id.h.
PACKET_ID_WRAP_TRIGGER
#define PACKET_ID_WRAP_TRIGGER 0xFF000000
Definition at line 58 of file packet_id.h.
SEQ_REAP_INTERVAL
#define SEQ_REAP_INTERVAL 5
Definition at line 123 of file packet_id.h.
Typedef Documentation
net_time_t
typedef uint32_t net_time_t
Definition at line 51 of file packet_id.h.
packet_id_print_type
typedef unsigned int packet_id_print_type
Definition at line 96 of file packet_id.h.
packet_id_type
typedef uint32_t packet_id_type
Definition at line 49 of file packet_id.h.
Function Documentation
check_timestamp_delta()
static bool check_timestamp_delta (time_t remote, unsigned int max_delta) inline static
Definition at line 317 of file packet_id.h.
References now.
CIRC_LIST()
CIRC_LIST (seq_list , time_t)
packet_id_add()
void packet_id_add (struct packet_id_rec * p, const struct packet_id_net * pin)
Definition at line 115 of file packet_id.c.
References CIRC_LIST_ITEM, CIRC_LIST_PUSH, CIRC_LIST_RESET, CIRC_LIST_SIZE, get_random(), packet_id_rec::id, packet_id_net::id, now, packet_id_rec::seq_backtrack, SEQ_EXPIRED, packet_id_rec::seq_list, SEQ_UNSEEN, packet_id_rec::time, and packet_id_net::time.
Referenced by crypto_check_replay().
packet_id_close_to_wrapping()
static bool packet_id_close_to_wrapping (const struct packet_id_send * p) inline static
Definition at line 311 of file packet_id.h.
References packet_id_send::id, and PACKET_ID_WRAP_TRIGGER.
Referenced by tls_process().
packet_id_free()
void packet_id_free (struct packet_id * p)
Definition at line 101 of file packet_id.c.
References CLEAR, D_PID_DEBUG, dmsg, packet_id::rec, and packet_id_rec::seq_list.
Referenced by do_close_packet_id(), key_state_free(), test_crypto_thread(), and tls_wrap_free().
packet_id_init()
void packet_id_init (struct packet_id * p, int seq_backtrack, int time_backtrack, const char * name, int unit)
Definition at line 78 of file packet_id.c.
References ASSERT, CIRC_LIST_ALLOC, CLEAR, D_PID_DEBUG, dmsg, packet_id_rec::initialized, MAX_SEQ_BACKTRACK, MAX_TIME_BACKTRACK, MIN_SEQ_BACKTRACK, MIN_TIME_BACKTRACK, packet_id_rec::name, packet_id::rec, packet_id_rec::seq_backtrack, packet_id_rec::seq_list, packet_id_rec::time_backtrack, and packet_id_rec::unit.
Referenced by do_init_crypto_static(), key_state_init(), test_tls_crypt_setup(), and tls_session_init().
packet_id_initialized()
static bool packet_id_initialized (const struct packet_id * pid) inline static
Is this struct packet_id initialized?
Definition at line 274 of file packet_id.h.
References packet_id_rec::initialized, and packet_id::rec.
Referenced by openvpn_decrypt_aead(), openvpn_decrypt_v1(), openvpn_encrypt_aead(), openvpn_encrypt_v1(), tls_crypt_unwrap(), tls_crypt_wrap(), and tls_wrap_free().
packet_id_net_print()
const char* packet_id_net_print (const struct packet_id_net * pin, bool print_timestamp, struct gc_arena * gc)
Definition at line 391 of file packet_id.c.
References alloc_buf_gc(), BSTR, buf_printf(), packet_id_net::id, packet_id_format, packet_id_net::time, and time_string().
Referenced by crypto_check_replay(), and protocol_dump().
packet_id_persist_close()
void packet_id_persist_close (struct packet_id_persist * p)
Definition at line 419 of file packet_id.c.
References D_PID_PERSIST, packet_id_persist::fd, packet_id_persist::filename, M_ERRNO, msg, packet_id_persist_enabled(), and packet_id_persist_init().
Referenced by do_close_packet_id().
packet_id_persist_enabled()
static bool packet_id_persist_enabled (const struct packet_id_persist * p) inline static
Definition at line 281 of file packet_id.h.
References packet_id_persist::fd.
Referenced by packet_id_persist_close(), packet_id_persist_load(), packet_id_persist_load_obj(), packet_id_persist_print(), packet_id_persist_save(), packet_id_persist_save_obj(), and process_coarse_timers().
packet_id_persist_init()
void packet_id_persist_init (struct packet_id_persist * p)
Definition at line 409 of file packet_id.c.
References packet_id_persist::fd, packet_id_persist::filename, packet_id_persist::id, packet_id_persist::id_last_written, packet_id_persist::time, and packet_id_persist::time_last_written.
Referenced by packet_id_persist_close().
packet_id_persist_load()
void packet_id_persist_load (struct packet_id_persist * p, const char * filename)
Definition at line 433 of file packet_id.c.
References D_PID_PERSIST, D_PID_PERSIST_DEBUG, dmsg, packet_id_persist::fd, packet_id_persist::filename, gc_free(), gc_new(), packet_id_persist::id, packet_id_persist_file_image::id, packet_id_persist::id_last_written, M_ERR, M_ERRNO, msg, O_BINARY, packet_id_persist_enabled(), packet_id_persist_print(), platform_open(), read, S_IRUSR, S_IWUSR, ssize_t, packet_id_persist::time, packet_id_persist_file_image::time, and packet_id_persist::time_last_written.
Referenced by init_crypto_pre().
packet_id_persist_load_obj()
void packet_id_persist_load_obj (const struct packet_id_persist * p, struct packet_id * pid)
Definition at line 524 of file packet_id.c.
References packet_id_rec::id, packet_id_persist::id, packet_id_persist_enabled(), packet_id::rec, packet_id_rec::time, and packet_id_persist::time.
Referenced by do_init_crypto_static(), and tls_session_init().
packet_id_persist_print()
const char* packet_id_persist_print (const struct packet_id_persist * p, struct gc_arena * gc)
Definition at line 534 of file packet_id.c.
References alloc_buf_gc(), buf_printf(), buffer::data, packet_id_persist::id, packet_id_format, packet_id_persist_enabled(), packet_id_persist::time, and time_string().
Referenced by packet_id_persist_load(), and packet_id_persist_save().
packet_id_persist_save()
void packet_id_persist_save (struct packet_id_persist * p)
Definition at line 482 of file packet_id.c.
References D_PID_PERSIST, D_PID_PERSIST_DEBUG, dmsg, packet_id_persist::fd, packet_id_persist::filename, gc_free(), gc_new(), packet_id_persist::id, packet_id_persist_file_image::id, packet_id_persist::id_last_written, M_ERRNO, msg, packet_id_persist_enabled(), packet_id_persist_print(), ssize_t, packet_id_persist::time, packet_id_persist_file_image::time, packet_id_persist::time_last_written, and write.
Referenced by do_close_packet_id(), and process_coarse_timers().
packet_id_persist_save_obj()
static void packet_id_persist_save_obj (struct packet_id_persist * p, const struct packet_id * pid) inline static
Definition at line 288 of file packet_id.h.
References packet_id_rec::id, packet_id_persist::id, packet_id_persist_enabled(), packet_id::rec, packet_id_rec::time, and packet_id_persist::time.
Referenced by crypto_check_replay().
packet_id_read()
bool packet_id_read (struct packet_id_net * pin, struct buffer * buf, bool long_form)
Definition at line 301 of file packet_id.c.
References buf_read(), packet_id_net::id, ntohpid, ntohtime, and packet_id_net::time.
Referenced by openvpn_decrypt_aead(), openvpn_decrypt_v1(), protocol_dump(), and tls_crypt_unwrap().
packet_id_reap()
void packet_id_reap (struct packet_id_rec * p)
Definition at line 170 of file packet_id.c.
References CIRC_LIST_ITEM, CIRC_LIST_SIZE, packet_id_rec::last_reap, now, SEQ_EXPIRED, packet_id_rec::seq_list, and packet_id_rec::time_backtrack.
Referenced by packet_id_reap_test().
packet_id_reap_test()
static void packet_id_reap_test (struct packet_id_rec * p) inline static
Definition at line 334 of file packet_id.h.
References packet_id_rec::last_reap, now, packet_id_reap(), and SEQ_REAP_INTERVAL.
Referenced by crypto_check_replay().
packet_id_size()
static int packet_id_size (bool long_form) inline static
Definition at line 305 of file packet_id.h.
Referenced by crypto_adjust_frame_parameters(), crypto_max_overhead(), swap_hmac(), and tls_crypt_buf_overhead().
packet_id_test()
bool packet_id_test (struct packet_id_rec * p, const struct packet_id_net * pin)
Definition at line 202 of file packet_id.c.
References ASSERT, CIRC_LIST_ITEM, CIRC_LIST_SIZE, D_PID_DEBUG, D_PID_DEBUG_LOW, D_PID_DEBUG_MEDIUM, packet_id_rec::id, packet_id_net::id, packet_id_rec::initialized, packet_id_rec::max_backtrack_stat, packet_id_debug(), packet_id_rec::seq_backtrack, packet_id_rec::seq_list, packet_id_rec::time, and packet_id_net::time.
Referenced by crypto_check_replay().
packet_id_write()
bool packet_id_write (struct packet_id_send * p, struct buffer * buf, bool long_form, bool prepend)
Write a packet ID to buf, and update the packet ID state.
Parameters
p Packet ID state.
buf Buffer to write the packet ID too
long_form If true, also update and write time_t to buf
prepend If true, prepend to buffer, otherwise append.
Returns
true if successful, false otherwise.
Definition at line 349 of file packet_id.c.
References buf_write(), buf_write_prepend(), htonpid, htontime, packet_id_send::id, packet_id_send_update(), and packet_id_send::time.
Referenced by openvpn_encrypt_aead(), openvpn_encrypt_v1(), test_packet_id_write_long(), test_packet_id_write_long_prepend(), test_packet_id_write_long_wrap(), test_packet_id_write_short(), test_packet_id_write_short_prepend(), test_packet_id_write_short_wrap(), and tls_crypt_wrap().