OpenVPN: src/openvpn/perf.h File Reference
perf.h File Reference
Macros
#define PERF_BIO_READ_PLAINTEXT 0
#define PERF_BIO_WRITE_PLAINTEXT 1
#define PERF_BIO_READ_CIPHERTEXT 2
#define PERF_BIO_WRITE_CIPHERTEXT 3
#define PERF_TLS_MULTI_PROCESS 4
#define PERF_IO_WAIT 5
#define PERF_EVENT_LOOP 6
#define PERF_MULTI_CREATE_INSTANCE 7
#define PERF_MULTI_CLOSE_INSTANCE 8
#define PERF_MULTI_SHOW_STATS 9
#define PERF_MULTI_BCAST 10
#define PERF_MULTI_MCAST 11
#define PERF_SCRIPT 12
#define PERF_READ_IN_LINK 13
#define PERF_PROC_IN_LINK 14
#define PERF_READ_IN_TUN 15
#define PERF_PROC_IN_TUN 16
#define PERF_PROC_OUT_LINK 17
#define PERF_PROC_OUT_TUN 18
#define PERF_PROC_OUT_TUN_MTCP 19
#define PERF_N 20
Functions
static void perf_push (int type)
static void perf_pop (void)
static void perf_output_results (void)
Macro Definition Documentation
PERF_BIO_READ_CIPHERTEXT
#define PERF_BIO_READ_CIPHERTEXT 2
Definition at line 40 of file perf.h.
PERF_BIO_READ_PLAINTEXT
#define PERF_BIO_READ_PLAINTEXT 0
Definition at line 38 of file perf.h.
PERF_BIO_WRITE_CIPHERTEXT
#define PERF_BIO_WRITE_CIPHERTEXT 3
Definition at line 41 of file perf.h.
PERF_BIO_WRITE_PLAINTEXT
#define PERF_BIO_WRITE_PLAINTEXT 1
Definition at line 39 of file perf.h.
PERF_EVENT_LOOP
#define PERF_EVENT_LOOP 6
Definition at line 44 of file perf.h.
PERF_IO_WAIT
#define PERF_IO_WAIT 5
Definition at line 43 of file perf.h.
PERF_MULTI_BCAST
#define PERF_MULTI_BCAST 10
Definition at line 48 of file perf.h.
PERF_MULTI_CLOSE_INSTANCE
#define PERF_MULTI_CLOSE_INSTANCE 8
Definition at line 46 of file perf.h.
PERF_MULTI_CREATE_INSTANCE
#define PERF_MULTI_CREATE_INSTANCE 7
Definition at line 45 of file perf.h.
PERF_MULTI_MCAST
#define PERF_MULTI_MCAST 11
Definition at line 49 of file perf.h.
PERF_MULTI_SHOW_STATS
#define PERF_MULTI_SHOW_STATS 9
Definition at line 47 of file perf.h.
PERF_N
#define PERF_N 20
Definition at line 58 of file perf.h.
PERF_PROC_IN_LINK
#define PERF_PROC_IN_LINK 14
Definition at line 52 of file perf.h.
PERF_PROC_IN_TUN
#define PERF_PROC_IN_TUN 16
Definition at line 54 of file perf.h.
PERF_PROC_OUT_LINK
#define PERF_PROC_OUT_LINK 17
Definition at line 55 of file perf.h.
PERF_PROC_OUT_TUN
#define PERF_PROC_OUT_TUN 18
Definition at line 56 of file perf.h.
PERF_PROC_OUT_TUN_MTCP
#define PERF_PROC_OUT_TUN_MTCP 19
Definition at line 57 of file perf.h.
PERF_READ_IN_LINK
#define PERF_READ_IN_LINK 13
Definition at line 51 of file perf.h.
PERF_READ_IN_TUN
#define PERF_READ_IN_TUN 15
Definition at line 53 of file perf.h.
PERF_SCRIPT
#define PERF_SCRIPT 12
Definition at line 50 of file perf.h.
PERF_TLS_MULTI_PROCESS
#define PERF_TLS_MULTI_PROCESS 4
Definition at line 42 of file perf.h.
Function Documentation
perf_output_results()
static void perf_output_results (void) inline static
Definition at line 86 of file perf.h.
Referenced by openvpn_exit().
perf_pop()
static void perf_pop (void) inline static
Definition at line 82 of file perf.h.
Referenced by event_wait(), key_state_read_ciphertext(), key_state_read_plaintext(), key_state_write_ciphertext(), key_state_write_plaintext(), key_state_write_plaintext_const(), multi_bcast(), multi_close_instance(), multi_create_instance(), multi_process_incoming_link(), multi_tcp_wait_lite(), process_incoming_link(), process_incoming_tun(), process_outgoing_link(), process_outgoing_tun(), read_incoming_link(), read_incoming_tun(), tls_multi_process(), tunnel_point_to_point(), tunnel_server_tcp(), and tunnel_server_udp_single_threaded().
perf_push()
static void perf_push (int type) inline static
Definition at line 78 of file perf.h.
Referenced by event_wait(), key_state_read_ciphertext(), key_state_read_plaintext(), key_state_write_ciphertext(), key_state_write_plaintext(), key_state_write_plaintext_const(), multi_bcast(), multi_close_instance(), multi_create_instance(), multi_process_incoming_link(), multi_tcp_wait_lite(), process_incoming_link(), process_incoming_tun(), process_outgoing_link(), process_outgoing_tun(), read_incoming_link(), read_incoming_tun(), tls_multi_process(), tunnel_point_to_point(), tunnel_server_tcp(), and tunnel_server_udp_single_threaded().