OpenVPN: src/openvpn/ping.h File Reference
ping.h File Reference
#include "init.h"
#include "forward.h"
Macros
#define PRE_PULL_INITIAL_PING_RESTART 120 /* in seconds */
#define PING_STRING_SIZE 16
Functions
static bool is_ping_msg (const struct buffer *buf)
void trigger_ping_timeout_signal (struct context *c)
Trigger the correct signal on a –ping timeout depending if –ping-exit is set (SIGTERM) or not (SIGUSR1)
void check_ping_send_dowork (struct context *c)
static void check_ping_restart (struct context *c)
static void check_ping_send (struct context *c)
Variables
const uint8_t ping_string []
Macro Definition Documentation
PING_STRING_SIZE
#define PING_STRING_SIZE 16
Definition at line 38 of file ping.h.
PRE_PULL_INITIAL_PING_RESTART
#define PRE_PULL_INITIAL_PING_RESTART 120 /* in seconds */
Definition at line 33 of file ping.h.
Function Documentation
check_ping_restart()
static void check_ping_restart (struct context * c) inline static
Definition at line 60 of file ping.h.
References link_socket_addr::actual, context::c1, context::c2, ETT_DEFAULT, event_timeout_trigger(), link_socket_actual_defined(), context_1::link_socket_addr, context::options, context_2::ping_rec_interval, options::ping_rec_timeout, options::ping_timer_remote, context_2::timeval, and trigger_ping_timeout_signal().
Referenced by process_coarse_timers().
check_ping_send()
static void check_ping_send (struct context * c) inline static
Definition at line 77 of file ping.h.
References context::c2, check_ping_send_dowork(), ETT_DEFAULT, event_timeout_trigger(), context::options, context_2::ping_send_interval, options::ping_send_timeout, context_2::timeval, and TO_LINK_DEF.
Referenced by process_coarse_timers().
check_ping_send_dowork()
void check_ping_send_dowork (struct context * c)
Definition at line 79 of file ping.c.
References ASSERT, context_buffers::aux_buf, context_2::buf, buf_init, buf_safe(), buf_write(), context_2::buffers, context::c2, D_PING, dmsg, encrypt_sign(), context_2::frame, FRAME_HEADROOM, buffer::len, MAX_RW_SIZE_TUN, and ping_string.
Referenced by check_ping_send().
is_ping_msg()
static bool is_ping_msg (const struct buffer * buf) inline static
Definition at line 41 of file ping.h.
References buf_string_match(), ping_string, and PING_STRING_SIZE.
Referenced by process_incoming_link_part2().
trigger_ping_timeout_signal()
void trigger_ping_timeout_signal (struct context * c)
Trigger the correct signal on a –ping timeout depending if –ping-exit is set (SIGTERM) or not (SIGUSR1)
Definition at line 50 of file ping.c.
References ASSERT, format_common_name(), gc_free(), gc_new(), M_INFO, msg, context::options, PING_EXIT, options::ping_rec_timeout_action, PING_RESTART, context::sig, signal_info::signal_received, signal_info::signal_text, SIGTERM, and SIGUSR1.
Referenced by check_ping_restart().
Variable Documentation
ping_string
const uint8_t ping_string[]
Definition at line 44 of file ping.c.
Referenced by check_ping_send_dowork(), and is_ping_msg().