OpenVPN: src/openvpn/ping.c File Reference
ping.c File Reference
#include "syshead.h"
#include "ping.h"
#include "memdbg.h"
Functions
void trigger_ping_timeout_signal (struct context *c)
Trigger the correct signal on a –ping timeout depending if –ping-exit is set (SIGTERM) or not (SIGUSR1)
void check_ping_send_dowork (struct context *c)
Variables
const uint8_t ping_string []
Function Documentation
check_ping_send_dowork()
void check_ping_send_dowork (struct context * c)
Definition at line 79 of file ping.c.
References ASSERT, context_buffers::aux_buf, context_2::buf, buf_init, buf_safe(), buf_write(), context_2::buffers, context::c2, D_PING, dmsg, encrypt_sign(), context_2::frame, FRAME_HEADROOM, buffer::len, MAX_RW_SIZE_TUN, and ping_string.
Referenced by check_ping_send().
trigger_ping_timeout_signal()
void trigger_ping_timeout_signal (struct context * c)
Trigger the correct signal on a –ping timeout depending if –ping-exit is set (SIGTERM) or not (SIGUSR1)
Definition at line 50 of file ping.c.
References ASSERT, format_common_name(), gc_free(), gc_new(), M_INFO, msg, context::options, PING_EXIT, options::ping_rec_timeout_action, PING_RESTART, context::sig, signal_info::signal_received, signal_info::signal_text, SIGTERM, and SIGUSR1.
Referenced by check_ping_restart().
Variable Documentation
ping_string
const uint8_t ping_string[]
Initial value:
= {
    0x2a, 0x18, 0x7b, 0xf3, 0x64, 0x1e, 0xb4, 0xcb,
    0x07, 0xed, 0x2d, 0x0a, 0x98, 0x1f, 0xc7, 0x48
}
Definition at line 44 of file ping.c.
Referenced by check_ping_send_dowork(), and is_ping_msg().