OpenVPN: src/openvpn/plugin.h File Reference
plugin.h File Reference
#include "ssl_verify_openssl.h"
#include "openvpn-plugin.h"
#include "misc.h"
Data Structures
struct plugin_option
struct plugin_option_list
struct plugin
struct plugin_per_client
struct plugin_common
struct plugin_list
struct plugin_return
Macros
#define MAX_PLUGINS 16
Functions
struct plugin_option_list * plugin_option_list_new (struct gc_arena *gc)
bool plugin_option_list_add (struct plugin_option_list *list, char **p, struct gc_arena *gc)
void plugin_option_list_print (const struct plugin_option_list *list, int msglevel)
struct plugin_list * plugin_list_init (const struct plugin_option_list *list)
void plugin_list_open (struct plugin_list *pl, const struct plugin_option_list *list, struct plugin_return *pr, const struct env_set *es, const int init_point)
struct plugin_list * plugin_list_inherit (const struct plugin_list *src)
int plugin_call_ssl (const struct plugin_list *pl, const int type, const struct argv *av, struct plugin_return *pr, struct env_set *es, int current_cert_depth, openvpn_x509_cert_t *current_cert)
void plugin_list_close (struct plugin_list *pl)
bool plugin_defined (const struct plugin_list *pl, const int type)
void plugin_return_get_column (const struct plugin_return *src, struct plugin_return *dest, const char *colname)
void plugin_return_free (struct plugin_return *pr)
static int plugin_n (const struct plugin_list *pl)
static bool plugin_return_defined (const struct plugin_return *pr)
static void plugin_return_init (struct plugin_return *pr)
static int plugin_call (const struct plugin_list *pl, const int type, const struct argv *av, struct plugin_return *pr, struct env_set *es)
void plugin_abort (void)
Macro Definition Documentation
MAX_PLUGINS
#define MAX_PLUGINS 16
Definition at line 43 of file plugin.h.
Function Documentation
plugin_abort()
void plugin_abort (void)
Definition at line 924 of file plugin.c.
References plugin_common::n, plugin_abort_item(), plugin_common::plugins, and static_plugin_common.
Referenced by openvpn_exit().
plugin_call()
static int plugin_call (const struct plugin_list * pl, const int type, const struct argv * av, struct plugin_return * pr, struct env_set * es) inline static
Definition at line 202 of file plugin.h.
References plugin_call_ssl().
Referenced by do_route(), key_method_2_read(), learn_address_script(), link_socket_connection_initiated(), multi_client_connect_call_plugin_v1(), multi_client_connect_call_plugin_v2(), multi_client_disconnect_script(), run_up_down(), and verify_user_pass_plugin().
plugin_call_ssl()
int plugin_call_ssl (const struct plugin_list * pl, const int type, const struct argv * av, struct plugin_return * pr, struct env_set * es, int current_cert_depth, openvpn_x509_cert_t * current_cert)
Definition at line 799 of file plugin.c.
References plugin_list::common, gc_free(), gc_new(), plugin_return::list, M_FATAL, make_env_array(), msg, plugin_return::n, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_ENABLE_PF, OPENVPN_PLUGIN_FUNC_DEFERRED, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_FUNC_SUCCESS, plugin_list::per_client, plugin_per_client::per_client_context, plugin_call_item(), plugin_defined(), plugin_n(), plugin_return_init(), plugin_common::plugins, setenv_del(), and status.
Referenced by plugin_call(), and verify_cert_call_plugin().
plugin_defined()
bool plugin_defined (const struct plugin_list * pl, const int type)
Definition at line 940 of file plugin.c.
References plugin_list::common, plugin_common::n, OPENVPN_PLUGIN_MASK, plugin::plugin_type_mask, and plugin_common::plugins.
Referenced by do_route(), key_method_2_read(), learn_address_script(), link_socket_connection_initiated(), multi_client_connect_call_plugin_v1(), multi_client_connect_call_plugin_v2(), multi_client_disconnect_script(), plugin_call_ssl(), run_up_down(), tls_session_user_pass_enabled(), verify_cert_call_plugin(), and verify_user_pass().
plugin_list_close()
void plugin_list_close (struct plugin_list * pl)
Definition at line 905 of file plugin.c.
References plugin_list::common, plugin_list::common_owned, plugin_list::per_client, plugin_common_close(), and plugin_per_client_destroy().
Referenced by do_close_plugins().
plugin_list_inherit()
struct plugin_list* plugin_list_inherit (const struct plugin_list * src)
Definition at line 697 of file plugin.c.
References ALLOC_OBJ_CLEAR, ASSERT, plugin_list::common, plugin_list::per_client, and plugin_per_client_init().
Referenced by do_inherit_plugins().
plugin_list_init()
struct plugin_list* plugin_list_init (const struct plugin_option_list * list)
Definition at line 778 of file plugin.c.
References ALLOC_OBJ_CLEAR, plugin_list::common, plugin_list::common_owned, and plugin_common_init().
Referenced by init_plugins().
plugin_list_open()
void plugin_list_open (struct plugin_list * pl, const struct plugin_option_list * list, struct plugin_return * pr, const struct env_set * es, const int init_point)
Definition at line 788 of file plugin.c.
References plugin_list::common, plugin_list::per_client, plugin_common_open(), and plugin_per_client_init().
Referenced by open_plugins().
plugin_n()
static int plugin_n (const struct plugin_list * pl) inline static
Definition at line 152 of file plugin.h.
References plugin_list::common, and plugin_common::n.
Referenced by plugin_call_ssl().
plugin_option_list_add()
bool plugin_option_list_add (struct plugin_option_list * list, char ** p, struct gc_arena * gc)
Definition at line 170 of file plugin.c.
References plugin_option::argv, make_extended_arg_array(), MAX_PLUGINS, plugin_option_list::n, plugin_option_list::plugins, and plugin_option::so_pathname.
Referenced by add_option().
plugin_option_list_new()
struct plugin_option_list* plugin_option_list_new (struct gc_arena * gc)
Definition at line 162 of file plugin.c.
References ALLOC_OBJ_CLEAR_GC.
Referenced by add_option().
plugin_option_list_print()
void plugin_option_list_print (const struct plugin_option_list * list, int msglevel)
Definition at line 191 of file plugin.c.
References plugin_option::argv, gc_free(), gc_new(), gc_arena::list, msg, PA_BRACKET, plugin_option_list::plugins, print_argv(), and plugin_option::so_pathname.
Referenced by show_settings().
plugin_return_defined()
static bool plugin_return_defined (const struct plugin_return * pr) inline static
Definition at line 165 of file plugin.h.
References plugin_return::n.
Referenced by multi_client_connect_post_plugin(), and open_plugins().
plugin_return_free()
void plugin_return_free (struct plugin_return * pr)
Definition at line 1023 of file plugin.c.
References plugin_return::list, plugin_return::n, and openvpn_plugin_string_list_free().
Referenced by multi_client_connect_call_plugin_v2(), and open_plugins().
plugin_return_get_column()
void plugin_return_get_column (const struct plugin_return * src, struct plugin_return * dest, const char * colname)
Definition at line 1008 of file plugin.c.
References dest, plugin_return::list, plugin_return::n, and openvpn_plugin_string_list_find().
Referenced by multi_client_connect_post_plugin(), and open_plugins().
plugin_return_init()
static void plugin_return_init (struct plugin_return * pr) inline static
Definition at line 171 of file plugin.h.
References plugin_return::n.
Referenced by multi_client_connect_call_plugin_v2(), open_plugins(), plugin_call_ssl(), and plugin_common_open().