OpenVPN: src/openvpn/proto.c File Reference
proto.c File Reference
#include "syshead.h"
#include "proto.h"
#include "error.h"
#include "memdbg.h"
Functions
static bool is_ipv_X (int tunnel_type, struct buffer *buf, int ip_ver)
bool is_ipv4 (int tunnel_type, struct buffer *buf)
bool is_ipv6 (int tunnel_type, struct buffer *buf)
uint16_t ip_checksum (const sa_family_t af, const uint8_t *payload, const int len_payload, const uint8_t *src_addr, const uint8_t *dest_addr, const int proto)
Calculates an IP or IPv6 checksum with a pseudo header as required by TCP, UDP and ICMPv6.
Function Documentation
ip_checksum()
uint16_t ip_checksum (const sa_family_t af, const uint8_t * payload, const int len_payload, const uint8_t * src_addr, const uint8_t * dest_addr, const int proto)
Calculates an IP or IPv6 checksum with a pseudo header as required by TCP, UDP and ICMPv6.
Parameters
af - Address family for which the checksum is calculated AF_INET or AF_INET6
payload - the TCP, ICMPv6 or UDP packet
len_payload - length of payload
src_addr - Source address of the packet
dest_addr - Destination address of the packet
proto next - header or IP protocol of the packet
Returns
The calculated checksum in host order
Definition at line 125 of file proto.c.
Referenced by dhcp_extract_router_msg(), and ipv6_send_icmp_unreachable().
is_ipv4()
bool is_ipv4 (int tunnel_type, struct buffer * buf)
Definition at line 113 of file proto.c.
References is_ipv_X().
Referenced by process_ip_header().
is_ipv6()
bool is_ipv6 (int tunnel_type, struct buffer * buf)
Definition at line 118 of file proto.c.
References is_ipv_X().
Referenced by ipv6_send_icmp_unreachable(), and process_ip_header().
is_ipv_X()
static bool is_ipv_X (int tunnel_type, struct buffer * buf, int ip_ver) static
Definition at line 42 of file proto.c.
References BLEN, BPTR, buf_advance(), DEV_TYPE_TAP, DEV_TYPE_TUN, OPENVPN_ETH_P_8021Q, OPENVPN_ETH_P_IPV4, OPENVPN_ETH_P_IPV6, OPENVPN_IPH_GET_VER, openvpn_ethhdr::proto, openvpn_8021qhdr::proto, verify_align_4, and openvpn_iphdr::version_len.
Referenced by is_ipv4(), and is_ipv6().