OpenVPN: src/openvpn/push.h File Reference
push.h File Reference
#include "forward.h"
Macros
#define PUSH_MSG_ERROR 0
#define PUSH_MSG_REQUEST 1
#define PUSH_MSG_REPLY 2
#define PUSH_MSG_REQUEST_DEFERRED 3
#define PUSH_MSG_AUTH_FAILURE 4
#define PUSH_MSG_CONTINUATION 5
#define PUSH_MSG_ALREADY_REPLIED 6
Functions
int process_incoming_push_request (struct context *c)
int process_incoming_push_msg (struct context *c, const struct buffer *buffer, bool honor_received_options, unsigned int permission_mask, unsigned int *option_types_found)
bool send_push_request (struct context *c)
void receive_auth_failed (struct context *c, const struct buffer *buffer)
void server_pushed_signal (struct context *c, const struct buffer *buffer, const bool restart, const int adv)
void server_pushed_info (struct context *c, const struct buffer *buffer, const int adv)
void receive_cr_response (struct context *c, const struct buffer *buffer)
void incoming_push_message (struct context *c, const struct buffer *buffer)
void clone_push_list (struct options *o)
void push_option (struct options *o, const char *opt, int msglevel)
void push_options (struct options *o, char **p, int msglevel, struct gc_arena *gc)
void push_reset (struct options *o)
void push_remove_option (struct options *o, const char *p)
void remove_iroutes_from_push_route_list (struct options *o)
void send_auth_failed (struct context *c, const char *client_reason)
bool send_auth_pending_messages (struct context *c, const char *extra)
Sends the auth pending control messages to a client.
void send_restart (struct context *c, const char *kill_msg)
void send_push_reply_auth_token (struct tls_multi *multi)
Sends a push reply message only containin the auth-token to update the auth-token on the client.
Macro Definition Documentation
PUSH_MSG_ALREADY_REPLIED
#define PUSH_MSG_ALREADY_REPLIED 6
Definition at line 37 of file push.h.
PUSH_MSG_AUTH_FAILURE
#define PUSH_MSG_AUTH_FAILURE 4
Definition at line 35 of file push.h.
PUSH_MSG_CONTINUATION
#define PUSH_MSG_CONTINUATION 5
Definition at line 36 of file push.h.
PUSH_MSG_ERROR
#define PUSH_MSG_ERROR 0
Definition at line 31 of file push.h.
PUSH_MSG_REPLY
#define PUSH_MSG_REPLY 2
Definition at line 33 of file push.h.
PUSH_MSG_REQUEST
#define PUSH_MSG_REQUEST 1
Definition at line 32 of file push.h.
PUSH_MSG_REQUEST_DEFERRED
#define PUSH_MSG_REQUEST_DEFERRED 3
Definition at line 34 of file push.h.
Function Documentation
clone_push_list()
void clone_push_list (struct options * o)
Definition at line 645 of file push.c.
References options::gc, push_list::head, M_FATAL, push_entry::next, push_entry::option, options::push_list, push_option_ex(), push_reset(), and string_alloc().
Referenced by options_detach().
incoming_push_message()
void incoming_push_message (struct context * c, const struct buffer * buffer)
Definition at line 328 of file push.c.
References BSTR, context::c2, D_PUSH, D_PUSH_ERRORS, do_up(), event_timeout_clear(), gc_free(), gc_new(), msg, context::options, process_incoming_push_msg(), options::pull, pull_permission_mask(), PUSH_MSG_CONTINUATION, PUSH_MSG_ERROR, PUSH_MSG_REPLY, options::push_option_types_found, context_2::push_request_interval, register_signal(), sanitize_control_message(), SIGUSR1, status, and context_2::wait_for_connect.
Referenced by parse_incoming_control_channel_command().
process_incoming_push_msg()
int process_incoming_push_msg (struct context * c, const struct buffer * buffer, bool honor_received_options, unsigned int permission_mask, unsigned int * option_types_found)
Definition at line 856 of file push.c.
References buf_string_compare_advance(), context::c2, process_incoming_push_reply(), process_incoming_push_request(), PUSH_MSG_ERROR, push_reply_cmd, and context_2::push_request_received.
Referenced by incoming_push_message().
process_incoming_push_request()
int process_incoming_push_request (struct context * c)
Definition at line 731 of file push.c.
References key_state::authenticated, context::c2, CAS_FAILED, CAS_SUCCEEDED, gc_free(), gc_new(), tls_session::key, KS_AUTH_TRUE, KS_PRIMARY, tls_multi::multi_state, now, openvpn_time(), prepare_push_reply(), PUSH_MSG_ALREADY_REPLIED, PUSH_MSG_AUTH_FAILURE, PUSH_MSG_ERROR, PUSH_MSG_REQUEST, PUSH_MSG_REQUEST_DEFERRED, send_auth_failed(), send_push_reply(), context_2::sent_push_reply_expiry, tls_multi::session, TLS_AUTHENTICATION_FAILED, tls_authentication_status(), tls_client_reason(), context_2::tls_multi, and TM_ACTIVE.
Referenced by multi_client_connect_late_setup(), and process_incoming_push_msg().
push_option()
void push_option (struct options * o, const char * opt, int msglevel)
Definition at line 639 of file push.c.
References options::gc, options::push_list, and push_option_ex().
Referenced by helper_client_server(), helper_keepalive(), helper_tcp_nodelay(), and push_options().
push_options()
void push_options (struct options * o, char ** p, int msglevel, struct gc_arena * gc)
Definition at line 661 of file push.c.
References make_extended_arg_array(), print_argv(), and push_option().
Referenced by add_option().
push_remove_option()
void push_remove_option (struct options * o, const char * p)
Definition at line 693 of file push.c.
References D_PUSH_DEBUG, push_entry::enable, push_list::head, msg, push_entry::next, push_entry::option, options::push_ifconfig_ipv4_blocked, options::push_ifconfig_ipv6_blocked, options::push_list, and streq.
Referenced by add_option().
push_reset()
void push_reset (struct options * o)
Definition at line 687 of file push.c.
References CLEAR, and options::push_list.
Referenced by add_option(), and clone_push_list().
receive_auth_failed()
void receive_auth_failed (struct context * c, const struct buffer * buffer)
Definition at line 52 of file push.c.
References AR_INTERACT, AR_NOINTERACT, AR_NONE, ASSERT, auth_retry_get(), BLEN, BSTR, buf_advance(), buf_string_compare_advance(), buf_string_match_head_str(), M_VERB0, management_auth_failure(), msg, options::no_advance, context::options, options::pull, context::sig, signal_info::signal_received, signal_info::signal_text, SIGTERM, SIGUSR1, ssl_clean_auth_token(), ssl_purge_auth(), ssl_put_auth_challenge(), and UP_TYPE_AUTH.
Referenced by parse_incoming_control_channel_command().
receive_cr_response()
void receive_cr_response (struct context * c, const struct buffer * buffer)
Definition at line 213 of file push.c.
References BLEN, BSTR, buf_advance(), buf_read_u8(), context::c2, D_PUSH, session::key, KS_PRIMARY, msg, tls_multi::session, context_2::tls_multi, and TM_ACTIVE.
Referenced by parse_incoming_control_channel_command().
remove_iroutes_from_push_route_list()
void remove_iroutes_from_push_route_list (struct options * o)
Definition at line 886 of file push.c.
References CLEAR, D_PUSH, D_ROUTE_DEBUG, push_entry::enable, gc_free(), gc_new(), getaddr(), GETADDR_HOST_ORDER, push_list::head, in_addr_t, options::iroutes, MAX_PARMS, msg, iroute::netbits, netbits_to_netmask(), iroute::network, push_entry::next, iroute::next, push_entry::option, parse_line(), options::push_list, and SIZE.
Referenced by multi_client_connect_late_setup().
send_auth_failed()
void send_auth_failed (struct context * c, const char * client_reason)
Definition at line 262 of file push.c.
References alloc_buf_gc(), BSTR, buf_printf(), D_PUSH, gc_free(), gc_new(), buffer::len, context::options, PUSH_BUNDLE_SIZE, schedule_exit(), options::scheduled_exit_interval, send_control_channel_string(), and SIGTERM.
Referenced by process_incoming_push_request().
send_auth_pending_messages()
bool send_auth_pending_messages (struct context * c, const char * extra)
Sends the auth pending control messages to a client.
See doc/management-notes.txt under client-pending-auth for more details on message format
Definition at line 290 of file push.c.
References alloc_buf_gc(), BSTR, buf_printf(), D_PUSH, gc_free(), gc_new(), buffer::len, PUSH_BUNDLE_SIZE, and send_control_channel_string().
send_push_reply_auth_token()
void send_push_reply_auth_token (struct tls_multi * multi)
Sends a push reply message only containin the auth-token to update the auth-token on the client.
Parameters
multi - The tls_multi structure belonging to the instance to push to
Definition at line 526 of file push.c.
References alloc_buf_gc(), ASSERT, BSTR, buf_printf(), D_PUSH, push_entry::enable, gc_free(), gc_new(), push_list::head, push_entry::option, prepare_auth_token_push_reply(), PUSH_BUNDLE_SIZE, push_reply_cmd, and send_control_channel_string_dowork().
Referenced by ssl_session_fully_authenticated().
send_push_request()
bool send_push_request (struct context * c)
Definition at line 369 of file push.c.
References context::c2, D_PUSH, D_STREAM_ERRORS, options::handshake_window, msg, context_2::n_sent_push_requests, context::options, PUSH_REQUEST_INTERVAL, send_control_channel_string(), context::sig, signal_info::signal_received, signal_info::signal_text, and SIGUSR1.
Referenced by check_push_request().
send_restart()
void send_restart (struct context * c, const char * kill_msg)
Definition at line 317 of file push.c.
References D_PUSH, context::options, schedule_exit(), options::scheduled_exit_interval, send_control_channel_string(), and SIGTERM.
server_pushed_info()
void server_pushed_info (struct context * c, const struct buffer * buffer, const int adv)
Definition at line 181 of file push.c.
References alloc_buf_gc(), BLEN, BSTR, buf_advance(), buf_printf(), buf_read_u8(), D_PUSH, gc_free(), gc_new(), management_notify_generic(), and msg.
Referenced by parse_incoming_control_channel_command().
server_pushed_signal()
void server_pushed_signal (struct context * c, const struct buffer * buffer, const bool restart, const int adv)
Definition at line 121 of file push.c.
References BLEN, BSTR, buf_advance(), buf_read_u8(), D_STREAM_ERRORS, management_notify(), msg, options::no_advance, context::options, options::pull, context::sig, signal_info::signal_received, signal_info::signal_text, SIGTERM, SIGUSR1, and ssl_purge_auth().
Referenced by parse_incoming_control_channel_command().