OpenVPN: src/openvpn/push.c File Reference
push.c File Reference
#include "syshead.h"
#include "push.h"
#include "options.h"
#include "ssl.h"
#include "ssl_verify.h"
#include "ssl_ncp.h"
#include "manage.h"
#include "memdbg.h"
Functions
void receive_auth_failed (struct context *c, const struct buffer *buffer)
void server_pushed_signal (struct context *c, const struct buffer *buffer, const bool restart, const int adv)
void server_pushed_info (struct context *c, const struct buffer *buffer, const int adv)
void receive_cr_response (struct context *c, const struct buffer *buffer)
static bool push_option_fmt (struct gc_arena *gc, struct push_list *push_list, int msglevel, const char *fmt,...)
Add an option to the given push list by providing a format string.
void send_auth_failed (struct context *c, const char *client_reason)
bool send_auth_pending_messages (struct context *c, const char *extra)
Sends the auth pending control messages to a client.
void send_restart (struct context *c, const char *kill_msg)
void incoming_push_message (struct context *c, const struct buffer *buffer)
bool send_push_request (struct context *c)
void prepare_auth_token_push_reply (struct tls_multi *tls_multi, struct gc_arena *gc, struct push_list *push_list)
Prepare push option for auth-token.
bool prepare_push_reply (struct context *c, struct gc_arena *gc, struct push_list *push_list)
Prepare push options, based on local options.
static bool send_push_options (struct context *c, struct buffer *buf, struct push_list *push_list, int safe_cap, bool *push_sent, bool *multi_push)
void send_push_reply_auth_token (struct tls_multi *multi)
Sends a push reply message only containin the auth-token to update the auth-token on the client.
bool send_push_reply (struct context *c, struct push_list *per_client_push_list)
static void push_option_ex (struct gc_arena *gc, struct push_list *push_list, const char *opt, bool enable, int msglevel)
void push_option (struct options *o, const char *opt, int msglevel)
void clone_push_list (struct options *o)
void push_options (struct options *o, char **p, int msglevel, struct gc_arena *gc)
void push_reset (struct options *o)
void push_remove_option (struct options *o, const char *p)
int process_incoming_push_request (struct context *c)
static void push_update_digest (md_ctx_t *ctx, struct buffer *buf, const struct options *opt)
static int process_incoming_push_reply (struct context *c, unsigned int permission_mask, unsigned int *option_types_found, struct buffer *buf)
int process_incoming_push_msg (struct context *c, const struct buffer *buffer, bool honor_received_options, unsigned int permission_mask, unsigned int *option_types_found)
void remove_iroutes_from_push_route_list (struct options *o)
Variables
static char push_reply_cmd [] = "PUSH_REPLY"
Function Documentation
clone_push_list()
void clone_push_list (struct options * o)
Definition at line 645 of file push.c.
References options::gc, push_list::head, M_FATAL, push_entry::next, push_entry::option, options::push_list, push_option_ex(), push_reset(), and string_alloc().
Referenced by options_detach().
incoming_push_message()
void incoming_push_message (struct context * c, const struct buffer * buffer)
Definition at line 328 of file push.c.
References BSTR, context::c2, D_PUSH, D_PUSH_ERRORS, do_up(), event_timeout_clear(), gc_free(), gc_new(), msg, context::options, process_incoming_push_msg(), options::pull, pull_permission_mask(), PUSH_MSG_CONTINUATION, PUSH_MSG_ERROR, PUSH_MSG_REPLY, options::push_option_types_found, context_2::push_request_interval, register_signal(), sanitize_control_message(), SIGUSR1, status, and context_2::wait_for_connect.
Referenced by parse_incoming_control_channel_command().
prepare_auth_token_push_reply()
void prepare_auth_token_push_reply (struct tls_multi * tls_multi, struct gc_arena * gc, struct push_list * push_list)
Prepare push option for auth-token.
Parameters
tls_multi tls multi context of VPN tunnel
gc gc arena for allocating push options
push_list push list to where options are added
Returns
true on success, false on failure.
Definition at line 394 of file push.c.
References tls_multi::auth_token, tls_multi::auth_token_initial, M_USAGE, and push_option_fmt().
Referenced by prepare_push_reply(), and send_push_reply_auth_token().
prepare_push_reply()
bool prepare_push_reply (struct context * c, struct gc_arena * gc, struct push_list * push_list)
Prepare push options, based on local options.
Parameters
context context structure storing data for VPN tunnel
gc gc arena for allocating push options
push_list push list to where options are added
Returns
true on success, false on failure.
Definition at line 427 of file push.c.
References context::c2, options::ciphername, options::gc, options::ifconfig_local, in_addr_t, M_USAGE, context::options, tls_multi::peer_id, tls_multi::peer_info, prepare_auth_token_push_reply(), print_in6_addr(), print_in_addr_t(), context_2::push_ifconfig_defined, options::push_ifconfig_ipv4_blocked, options::push_ifconfig_ipv6_blocked, context_2::push_ifconfig_ipv6_defined, context_2::push_ifconfig_ipv6_local, context_2::push_ifconfig_ipv6_netbits, context_2::push_ifconfig_ipv6_remote, context_2::push_ifconfig_local, context_2::push_ifconfig_local_alias, context_2::push_ifconfig_remote_netmask, push_option_fmt(), context_2::tls_multi, tls_peer_supports_ncp(), and tls_multi::use_peer_id.
Referenced by process_incoming_push_request().
process_incoming_push_msg()
int process_incoming_push_msg (struct context * c, const struct buffer * buffer, bool honor_received_options, unsigned int permission_mask, unsigned int * option_types_found)
Definition at line 856 of file push.c.
References buf_string_compare_advance(), context::c2, process_incoming_push_reply(), process_incoming_push_request(), PUSH_MSG_ERROR, push_reply_cmd, and context_2::push_request_received.
Referenced by incoming_push_message().
process_incoming_push_reply()
static int process_incoming_push_reply (struct context * c, unsigned int permission_mask, unsigned int * option_types_found, struct buffer * buf) static
Definition at line 799 of file push.c.
References apply_push_options(), buf_read_u8(), context::c2, context_2::did_pre_pull_restore, sha256_digest::digest, context_2::es, context_2::gc, md_ctx_cleanup(), md_ctx_final(), md_ctx_free(), md_ctx_init(), md_ctx_new(), md_kt_get(), context::options, pre_pull_restore(), context_2::pulled_options_digest, context_2::pulled_options_digest_init_done, context_2::pulled_options_state, options::push_continuation, PUSH_MSG_CONTINUATION, PUSH_MSG_ERROR, PUSH_MSG_REPLY, and push_update_digest().
Referenced by process_incoming_push_msg().
process_incoming_push_request()
int process_incoming_push_request (struct context * c)
Definition at line 731 of file push.c.
References key_state::authenticated, context::c2, CAS_FAILED, CAS_SUCCEEDED, gc_free(), gc_new(), tls_session::key, KS_AUTH_TRUE, KS_PRIMARY, tls_multi::multi_state, now, openvpn_time(), prepare_push_reply(), PUSH_MSG_ALREADY_REPLIED, PUSH_MSG_AUTH_FAILURE, PUSH_MSG_ERROR, PUSH_MSG_REQUEST, PUSH_MSG_REQUEST_DEFERRED, send_auth_failed(), send_push_reply(), context_2::sent_push_reply_expiry, tls_multi::session, TLS_AUTHENTICATION_FAILED, tls_authentication_status(), tls_client_reason(), context_2::tls_multi, and TM_ACTIVE.
Referenced by multi_client_connect_late_setup(), and process_incoming_push_msg().
push_option()
void push_option (struct options * o, const char * opt, int msglevel)
Definition at line 639 of file push.c.
References options::gc, options::push_list, and push_option_ex().
Referenced by helper_client_server(), helper_keepalive(), helper_tcp_nodelay(), and push_options().
push_option_ex()
static void push_option_ex (struct gc_arena * gc, struct push_list * push_list, const char * opt, bool enable, int msglevel) static
Definition at line 610 of file push.c.
References ALLOC_OBJ_CLEAR_GC, ASSERT, CC_ANY, CC_COMMA, push_entry::enable, push_list::head, msg, push_entry::next, push_entry::option, string_class(), and push_list::tail.
Referenced by clone_push_list(), push_option(), and push_option_fmt().
push_option_fmt()
static bool push_option_fmt (struct gc_arena * gc, struct push_list * push_list, int msglevel, const char * fmt, ...) static
Add an option to the given push list by providing a format string.
The string added to the push options is allocated in o->gc, so the caller does not have to preserve anything.
Parameters
gc GC arena where options are allocated
push_list Push list containing options
msglevel The message level to use when printing errors
fmt Format string for the option
... Format string arguments
Returns
true on success, false on failure.
Definition at line 669 of file push.c.
References push_option_ex(), and string_alloc().
Referenced by prepare_auth_token_push_reply(), and prepare_push_reply().
push_options()
void push_options (struct options * o, char ** p, int msglevel, struct gc_arena * gc)
Definition at line 661 of file push.c.
References make_extended_arg_array(), print_argv(), and push_option().
Referenced by add_option().
push_remove_option()
void push_remove_option (struct options * o, const char * p)
Definition at line 693 of file push.c.
References D_PUSH_DEBUG, push_entry::enable, push_list::head, msg, push_entry::next, push_entry::option, options::push_ifconfig_ipv4_blocked, options::push_ifconfig_ipv6_blocked, options::push_list, and streq.
Referenced by add_option().
push_reset()
void push_reset (struct options * o)
Definition at line 687 of file push.c.
References CLEAR, and options::push_list.
Referenced by add_option(), and clone_push_list().
push_update_digest()
static void push_update_digest (md_ctx_t * ctx, struct buffer * buf, const struct options * opt) static
Definition at line 777 of file push.c.
References buf_parse(), options::ce, md_ctx_update(), OPTION_PARM_SIZE, strprefix(), and connection_entry::tun_mtu_defined.
Referenced by process_incoming_push_reply().
receive_auth_failed()
void receive_auth_failed (struct context * c, const struct buffer * buffer)
Definition at line 52 of file push.c.
References AR_INTERACT, AR_NOINTERACT, AR_NONE, ASSERT, auth_retry_get(), BLEN, BSTR, buf_advance(), buf_string_compare_advance(), buf_string_match_head_str(), M_VERB0, management_auth_failure(), msg, options::no_advance, context::options, options::pull, context::sig, signal_info::signal_received, signal_info::signal_text, SIGTERM, SIGUSR1, ssl_clean_auth_token(), ssl_purge_auth(), ssl_put_auth_challenge(), and UP_TYPE_AUTH.
Referenced by parse_incoming_control_channel_command().
receive_cr_response()
void receive_cr_response (struct context * c, const struct buffer * buffer)
Definition at line 213 of file push.c.
References BLEN, BSTR, buf_advance(), buf_read_u8(), context::c2, D_PUSH, session::key, KS_PRIMARY, msg, tls_multi::session, context_2::tls_multi, and TM_ACTIVE.
Referenced by parse_incoming_control_channel_command().
remove_iroutes_from_push_route_list()
void remove_iroutes_from_push_route_list (struct options * o)
Definition at line 886 of file push.c.
References CLEAR, D_PUSH, D_ROUTE_DEBUG, push_entry::enable, gc_free(), gc_new(), getaddr(), GETADDR_HOST_ORDER, push_list::head, in_addr_t, options::iroutes, MAX_PARMS, msg, iroute::netbits, netbits_to_netmask(), iroute::network, push_entry::next, iroute::next, push_entry::option, parse_line(), options::push_list, and SIZE.
Referenced by multi_client_connect_late_setup().
send_auth_failed()
void send_auth_failed (struct context * c, const char * client_reason)
Definition at line 262 of file push.c.
References alloc_buf_gc(), BSTR, buf_printf(), D_PUSH, gc_free(), gc_new(), buffer::len, context::options, PUSH_BUNDLE_SIZE, schedule_exit(), options::scheduled_exit_interval, send_control_channel_string(), and SIGTERM.
Referenced by process_incoming_push_request().
send_auth_pending_messages()
bool send_auth_pending_messages (struct context * c, const char * extra)
Sends the auth pending control messages to a client.
See doc/management-notes.txt under client-pending-auth for more details on message format
Definition at line 290 of file push.c.
References alloc_buf_gc(), BSTR, buf_printf(), D_PUSH, gc_free(), gc_new(), buffer::len, PUSH_BUNDLE_SIZE, and send_control_channel_string().
send_push_options()
static bool send_push_options (struct context * c, struct buffer * buf, struct push_list * push_list, int safe_cap, bool * push_sent, bool * multi_push) static
Definition at line 486 of file push.c.
References BLEN, BSTR, buf_printf(), buf_reset_len(), D_PUSH, push_entry::enable, push_list::head, M_WARN, msg, push_entry::next, push_entry::option, push_reply_cmd, send_control_channel_string(), and status.
Referenced by send_push_reply().
send_push_reply()
bool send_push_reply (struct context * c, struct push_list * per_client_push_list)
Definition at line 545 of file push.c.
References alloc_buf_gc(), BCAP, BLEN, BSTR, buf_printf(), buf_reset_len(), D_PUSH, gc_free(), gc_new(), context::options, PUSH_BUNDLE_SIZE, options::push_list, push_reply_cmd, send_control_channel_string(), send_push_options(), and status.
Referenced by process_incoming_push_request().
send_push_reply_auth_token()
void send_push_reply_auth_token (struct tls_multi * multi)
Sends a push reply message only containin the auth-token to update the auth-token on the client.
Parameters
multi - The tls_multi structure belonging to the instance to push to
Definition at line 526 of file push.c.
Referenced by ssl_session_fully_authenticated().
send_push_request()
bool send_push_request (struct context * c)
Definition at line 369 of file push.c.
References context::c2, D_PUSH, D_STREAM_ERRORS, options::handshake_window, msg, context_2::n_sent_push_requests, context::options, PUSH_REQUEST_INTERVAL, send_control_channel_string(), context::sig, signal_info::signal_received, signal_info::signal_text, and SIGUSR1.
Referenced by check_push_request().
send_restart()
void send_restart (struct context * c, const char * kill_msg)
Definition at line 317 of file push.c.
References D_PUSH, context::options, schedule_exit(), options::scheduled_exit_interval, send_control_channel_string(), and SIGTERM.
server_pushed_info()
void server_pushed_info (struct context * c, const struct buffer * buffer, const int adv)
Definition at line 181 of file push.c.
References alloc_buf_gc(), BLEN, BSTR, buf_advance(), buf_printf(), buf_read_u8(), D_PUSH, gc_free(), gc_new(), management_notify_generic(), and msg.
Referenced by parse_incoming_control_channel_command().
server_pushed_signal()
void server_pushed_signal (struct context * c, const struct buffer * buffer, const bool restart, const int adv)
Definition at line 121 of file push.c.
References BLEN, BSTR, buf_advance(), buf_read_u8(), D_STREAM_ERRORS, management_notify(), msg, options::no_advance, context::options, options::pull, context::sig, signal_info::signal_received, signal_info::signal_text, SIGTERM, SIGUSR1, and ssl_purge_auth().
Referenced by parse_incoming_control_channel_command().
Variable Documentation
push_reply_cmd
char push_reply_cmd[] = "PUSH_REPLY" static
Definition at line 43 of file push.c.
Referenced by process_incoming_push_msg(), send_push_options(), send_push_reply(), and send_push_reply_auth_token().