OpenVPN: src/openvpn/route.h File Reference
route.h File Reference
#include "basic.h"
#include "tun.h"
#include "misc.h"
#include "networking.h"
Data Structures
struct route_bypass
struct route_special_addr
struct route_option
struct route_option_list
struct route_ipv6_option
struct route_ipv6_option_list
struct route_ipv4
struct route_ipv6
struct route_gateway_address
struct route_gateway_info
struct route_ipv6_gateway_address
struct route_ipv6_gateway_info
struct route_list
struct route_ipv6_list
struct iroute
struct iroute_ipv6
Macros
#define ROUTE_METHOD_ADAPTIVE 0 /* try IP helper first then route.exe */
#define ROUTE_METHOD_IPAPI 1 /* use IP helper API */
#define ROUTE_METHOD_EXE 2 /* use route.exe */
#define ROUTE_METHOD_SERVICE 3 /* use the privileged Windows service */
#define ROUTE_METHOD_MASK 3
#define ROUTE_DELETE_FIRST (1<<2)
#define ROUTE_REF_GW (1<<3)
#define N_ROUTE_BYPASS 8
#define RTSA_REMOTE_ENDPOINT (1<<0)
#define RTSA_REMOTE_HOST (1<<1)
#define RTSA_DEFAULT_METRIC (1<<2)
#define RG_ENABLE (1<<0)
#define RG_LOCAL (1<<1)
#define RG_DEF1 (1<<2)
#define RG_BYPASS_DHCP (1<<3)
#define RG_BYPASS_DNS (1<<4)
#define RG_REROUTE_GW (1<<5)
#define RG_AUTO_LOCAL (1<<6)
#define RG_BLOCK_LOCAL (1<<7)
#define RT_DEFINED (1<<0)
#define RT_ADDED (1<<1)
#define RT_METRIC_DEFINED (1<<2)
#define RGI_ADDR_DEFINED (1<<0) /* set if gateway.addr defined */
#define RGI_NETMASK_DEFINED (1<<1) /* set if gateway.netmask defined */
#define RGI_HWADDR_DEFINED (1<<2) /* set if hwaddr is defined */
#define RGI_IFACE_DEFINED (1<<3) /* set if iface is defined */
#define RGI_OVERFLOW (1<<4) /* set if more interface addresses than will fit in addrs */
#define RGI_ON_LINK (1<<5)
#define RGI_N_ADDRESSES 8
#define RGI_N_ADDRESSES 8
#define RL_DID_REDIRECT_DEFAULT_GATEWAY (1<<0)
#define RL_DID_LOCAL (1<<1)
#define RL_ROUTES_ADDED (1<<2)
#define TLA_NOT_IMPLEMENTED 0
#define TLA_NONLOCAL 1
#define TLA_LOCAL 2
Functions
struct route_option_list * new_route_option_list (struct gc_arena *a)
struct route_ipv6_option_list * new_route_ipv6_option_list (struct gc_arena *a)
struct route_option_list * clone_route_option_list (const struct route_option_list *src, struct gc_arena *a)
struct route_ipv6_option_list * clone_route_ipv6_option_list (const struct route_ipv6_option_list *src, struct gc_arena *a)
void copy_route_option_list (struct route_option_list *dest, const struct route_option_list *src, struct gc_arena *a)
void copy_route_ipv6_option_list (struct route_ipv6_option_list *dest, const struct route_ipv6_option_list *src, struct gc_arena *a)
void route_ipv6_clear_host_bits (struct route_ipv6 *r6)
void add_route_ipv6 (struct route_ipv6 *r, const struct tuntap *tt, unsigned int flags, const struct env_set *es, openvpn_net_ctx_t *ctx)
void delete_route_ipv6 (const struct route_ipv6 *r, const struct tuntap *tt, unsigned int flags, const struct env_set *es, openvpn_net_ctx_t *ctx)
void add_route (struct route_ipv4 *r, const struct tuntap *tt, unsigned int flags, const struct route_gateway_info *rgi, const struct env_set *es, openvpn_net_ctx_t *ctx)
void add_route_to_option_list (struct route_option_list *l, const char *network, const char *netmask, const char *gateway, const char *metric)
void add_route_ipv6_to_option_list (struct route_ipv6_option_list *l, const char *prefix, const char *gateway, const char *metric)
bool init_route_list (struct route_list *rl, const struct route_option_list *opt, const char *remote_endpoint, int default_metric, in_addr_t remote_host, struct env_set *es, openvpn_net_ctx_t *ctx)
bool init_route_ipv6_list (struct route_ipv6_list *rl6, const struct route_ipv6_option_list *opt6, const char *remote_endpoint, int default_metric, const struct in6_addr *remote_host, struct env_set *es, openvpn_net_ctx_t *ctx)
void route_list_add_vpn_gateway (struct route_list *rl, struct env_set *es, const in_addr_t addr)
void add_routes (struct route_list *rl, struct route_ipv6_list *rl6, const struct tuntap *tt, unsigned int flags, const struct env_set *es, openvpn_net_ctx_t *ctx)
void delete_routes (struct route_list *rl, struct route_ipv6_list *rl6, const struct tuntap *tt, unsigned int flags, const struct env_set *es, openvpn_net_ctx_t *ctx)
void setenv_routes (struct env_set *es, const struct route_list *rl)
void setenv_routes_ipv6 (struct env_set *es, const struct route_ipv6_list *rl6)
bool is_special_addr (const char *addr_str)
void get_default_gateway (struct route_gateway_info *rgi, openvpn_net_ctx_t *ctx)
void get_default_gateway_ipv6 (struct route_ipv6_gateway_info *rgi, const struct in6_addr *dest, openvpn_net_ctx_t *ctx)
void print_default_gateway (const int msglevel, const struct route_gateway_info *rgi, const struct route_ipv6_gateway_info *rgi6)
int test_local_addr (const in_addr_t addr, const struct route_gateway_info *rgi)
void print_route_options (const struct route_option_list *rol, int level)
void print_routes (const struct route_list *rl, int level)
void show_routes (int msglev)
bool test_routes (const struct route_list *rl, const struct tuntap *tt)
bool add_route_ipapi (const struct route_ipv4 *r, const struct tuntap *tt, DWORD adapter_index)
bool del_route_ipapi (const struct route_ipv4 *r, const struct tuntap *tt)
bool netmask_to_netbits (const in_addr_t network, const in_addr_t netmask, int *netbits)
int netmask_to_netbits2 (in_addr_t netmask)
static in_addr_t netbits_to_netmask (const int netbits)
static bool route_list_vpn_gateway_needed (const struct route_list *rl)
static int route_did_redirect_default_gateway (const struct route_list *rl)
Macro Definition Documentation
N_ROUTE_BYPASS
#define N_ROUTE_BYPASS 8
Definition at line 55 of file route.h.
RG_AUTO_LOCAL
#define RG_AUTO_LOCAL (1<<6)
Definition at line 90 of file route.h.
RG_BLOCK_LOCAL
#define RG_BLOCK_LOCAL (1<<7)
Definition at line 91 of file route.h.
RG_BYPASS_DHCP
#define RG_BYPASS_DHCP (1<<3)
Definition at line 87 of file route.h.
RG_BYPASS_DNS
#define RG_BYPASS_DNS (1<<4)
Definition at line 88 of file route.h.
RG_DEF1
#define RG_DEF1 (1<<2)
Definition at line 86 of file route.h.
RG_ENABLE
#define RG_ENABLE (1<<0)
Definition at line 84 of file route.h.
RG_LOCAL
#define RG_LOCAL (1<<1)
Definition at line 85 of file route.h.
RG_REROUTE_GW
#define RG_REROUTE_GW (1<<5)
Definition at line 89 of file route.h.
RGI_ADDR_DEFINED
#define RGI_ADDR_DEFINED (1<<0) /* set if gateway.addr defined */
Definition at line 147 of file route.h.
RGI_HWADDR_DEFINED
#define RGI_HWADDR_DEFINED (1<<2) /* set if hwaddr is defined */
Definition at line 149 of file route.h.
RGI_IFACE_DEFINED
#define RGI_IFACE_DEFINED (1<<3) /* set if iface is defined */
Definition at line 150 of file route.h.
RGI_N_ADDRESSES [1/2]
#define RGI_N_ADDRESSES 8
Definition at line 201 of file route.h.
RGI_N_ADDRESSES [2/2]
#define RGI_N_ADDRESSES 8
Definition at line 201 of file route.h.
RGI_NETMASK_DEFINED
#define RGI_NETMASK_DEFINED (1<<1) /* set if gateway.netmask defined */
Definition at line 148 of file route.h.
RGI_ON_LINK
#define RGI_ON_LINK (1<<5)
Definition at line 152 of file route.h.
RGI_OVERFLOW
#define RGI_OVERFLOW (1<<4) /* set if more interface addresses than will fit in addrs */
Definition at line 151 of file route.h.
RL_DID_LOCAL
#define RL_DID_LOCAL (1<<1)
Definition at line 208 of file route.h.
RL_DID_REDIRECT_DEFAULT_GATEWAY
#define RL_DID_REDIRECT_DEFAULT_GATEWAY (1<<0)
Definition at line 207 of file route.h.
RL_ROUTES_ADDED
#define RL_ROUTES_ADDED (1<<2)
Definition at line 209 of file route.h.
ROUTE_DELETE_FIRST
#define ROUTE_DELETE_FIRST (1<<2)
Definition at line 50 of file route.h.
ROUTE_METHOD_ADAPTIVE
#define ROUTE_METHOD_ADAPTIVE 0 /* try IP helper first then route.exe */
Definition at line 40 of file route.h.
ROUTE_METHOD_EXE
#define ROUTE_METHOD_EXE 2 /* use route.exe */
Definition at line 42 of file route.h.
ROUTE_METHOD_IPAPI
#define ROUTE_METHOD_IPAPI 1 /* use IP helper API */
Definition at line 41 of file route.h.
ROUTE_METHOD_MASK
#define ROUTE_METHOD_MASK 3
Definition at line 44 of file route.h.
ROUTE_METHOD_SERVICE
#define ROUTE_METHOD_SERVICE 3 /* use the privileged Windows service */
Definition at line 43 of file route.h.
ROUTE_REF_GW
#define ROUTE_REF_GW (1<<3)
Definition at line 51 of file route.h.
RT_ADDED
#define RT_ADDED (1<<1)
Definition at line 114 of file route.h.
RT_DEFINED
#define RT_DEFINED (1<<0)
Definition at line 113 of file route.h.
RT_METRIC_DEFINED
#define RT_METRIC_DEFINED (1<<2)
Definition at line 115 of file route.h.
RTSA_DEFAULT_METRIC
#define RTSA_DEFAULT_METRIC (1<<2)
Definition at line 65 of file route.h.
RTSA_REMOTE_ENDPOINT
#define RTSA_REMOTE_ENDPOINT (1<<0)
Definition at line 63 of file route.h.
RTSA_REMOTE_HOST
#define RTSA_REMOTE_HOST (1<<1)
Definition at line 64 of file route.h.
TLA_LOCAL
#define TLA_LOCAL 2
Definition at line 345 of file route.h.
TLA_NONLOCAL
#define TLA_NONLOCAL 1
Definition at line 344 of file route.h.
TLA_NOT_IMPLEMENTED
#define TLA_NOT_IMPLEMENTED 0
Definition at line 343 of file route.h.
Function Documentation
add_route()
void add_route (struct route_ipv4 * r, const struct tuntap * tt, unsigned int flags, const struct route_gateway_info * rgi, const struct env_set * es, openvpn_net_ctx_t * ctx)
Definition at line 1566 of file route.c.
References route_gateway_info::adapter_index, add_route_ipapi(), add_route_service(), argv_free(), argv_msg(), argv_new(), argv_printf(), argv_printf_cat(), ASSERT, D_ROUTE, route_ipv4::flags, route_ipv4::gateway, argv::gc, gc_free(), gc_init(), get_win_sys_path(), iface, is_on_link(), local_route(), LR_ERROR, M_FATAL, M_WARN, route_ipv4::metric, msg, net_ctx_reset(), netcmd_semaphore_lock(), netcmd_semaphore_release(), route_ipv4::netmask, netmask_to_netbits2(), route_ipv4::network, openvpn_execve_check(), openvpn_snprintf(), print_in_addr_t(), ROUTE_METHOD_ADAPTIVE, ROUTE_METHOD_EXE, ROUTE_METHOD_IPAPI, ROUTE_METHOD_MASK, ROUTE_METHOD_SERVICE, ROUTE_PATH, RT_ADDED, RT_DEFINED, RT_METRIC_DEFINED, status, TUN_ADAPTER_INDEX_INVALID, and WIN_ROUTE_PATH_SUFFIX.
Referenced by add_route3(), add_routes(), and do_ifconfig_ipv4().
add_route_ipapi()
bool add_route_ipapi (const struct route_ipv4 * r, const struct tuntap * tt, DWORD adapter_index)
Definition at line 2898 of file route.c.
References CLEAR, D_ROUTE, route_ipv4::flags, route_ipv4::gateway, gc_free(), gc_new(), M_WARN, route_ipv4::metric, METRIC_NOT_USED, msg, route_ipv4::netmask, route_ipv4::network, print_in_addr_t(), RT_METRIC_DEFINED, status, strerror_win32(), TUN_ADAPTER_INDEX_INVALID, and windows_route_find_if_index().
Referenced by add_route().
add_route_ipv6()
void add_route_ipv6 (struct route_ipv6 * r, const struct tuntap * tt, unsigned int flags, const struct env_set * es, openvpn_net_ctx_t * ctx)
Definition at line 1877 of file route.c.
References tuntap::actual_name, route_ipv6::adapter_index, tuntap::adapter_index, add_route_ipv6_service(), argv_free(), argv_msg(), argv_new(), argv_printf(), argv_printf_cat(), D_ROUTE, DEV_TYPE_TAP, DEV_TYPE_TUN, route_ipv6::flags, route_ipv6::gateway, argv::gc, gc_free(), gc_init(), gc_malloc(), get_win_sys_path(), M_FATAL, M_INFO, M_WARN, route_ipv6::metric, msg, tuntap_options::msg_channel, net_ctx_reset(), route_ipv6::netbits, netcmd_semaphore_lock(), netcmd_semaphore_release(), NETSH_PATH_SUFFIX, route_ipv6::network, openvpn_execve_check(), openvpn_snprintf(), tuntap::options, PACKAGE_NAME, print_in6_addr(), route_ipv6_clear_host_bits(), ROUTE_PATH, RT_ADDED, RT_DEFINED, RT_METRIC_DEFINED, snprintf, status, and tuntap::type.
Referenced by add_route_connected_v6_net(), and add_routes().
add_route_ipv6_to_option_list()
void add_route_ipv6_to_option_list (struct route_ipv6_option_list * l, const char * prefix, const char * gateway, const char * metric)
Definition at line 511 of file route.c.
References ALLOC_OBJ_GC, route_ipv6_option::gateway, route_ipv6_option_list::gc, route_ipv6_option::metric, route_ipv6_option::next, route_ipv6_option::prefix, and route_ipv6_option_list::routes_ipv6.
Referenced by add_option(), and do_init_route_ipv6_list().
add_route_to_option_list()
void add_route_to_option_list (struct route_option_list * l, const char * network, const char * netmask, const char * gateway, const char * metric)
Definition at line 493 of file route.c.
References ALLOC_OBJ_GC, route_option::gateway, route_option_list::gc, route_option::metric, route_option::netmask, route_option::network, route_option::next, and route_option_list::routes.
Referenced by add_option(), and helper_add_route().
add_routes()
void add_routes (struct route_list * rl, struct route_ipv6_list * rl6, const struct tuntap * tt, unsigned int flags, const struct env_set * es, openvpn_net_ctx_t * ctx)
Definition at line 1191 of file route.c.
References tuntap::actual_name, add_route(), add_route_ipv6(), check_subnet_conflict(), delete_route(), delete_route_ipv6(), tuntap::did_ifconfig_ipv6_setup, tuntap::did_ifconfig_setup, route_ipv4::flags, route_ipv6::flags, route_list::iflags, route_ipv6_list::iflags, M_INFO, management_set_state(), msg, route_ipv4::netmask, route_ipv4::network, route_ipv4::next, route_ipv6::next, OPENVPN_STATE_ADD_ROUTES, redirect_default_route_to_vpn(), route_list::rgi, RL_ROUTES_ADDED, ROUTE_DELETE_FIRST, route_list::routes, and route_ipv6_list::routes_ipv6.
Referenced by do_route().
clone_route_ipv6_option_list()
struct route_ipv6_option_list* clone_route_ipv6_option_list (const struct route_ipv6_option_list * src, struct gc_arena * a)
Definition at line 149 of file route.c.
References ALLOC_OBJ_GC.
Referenced by pre_pull_save().
clone_route_option_list()
struct route_option_list* clone_route_option_list (const struct route_option_list * src, struct gc_arena * a)
Definition at line 140 of file route.c.
References ALLOC_OBJ_GC.
Referenced by pre_pull_save().
copy_route_ipv6_option_list()
void copy_route_ipv6_option_list (struct route_ipv6_option_list * dest, const struct route_ipv6_option_list * src, struct gc_arena * a)
Definition at line 165 of file route.c.
References dest.
Referenced by pre_pull_restore().
copy_route_option_list()
void copy_route_option_list (struct route_option_list * dest, const struct route_option_list * src, struct gc_arena * a)
Definition at line 158 of file route.c.
References dest.
Referenced by pre_pull_restore().
del_route_ipapi()
bool del_route_ipapi (const struct route_ipv4 * r, const struct tuntap * tt)
Definition at line 2980 of file route.c.
References CLEAR, route_ipv4::gateway, gc_free(), gc_new(), M_WARN, msg, route_ipv4::netmask, route_ipv4::network, status, strerror_win32(), TUN_ADAPTER_INDEX_INVALID, and windows_route_find_if_index().
Referenced by delete_route().
delete_route_ipv6()
void delete_route_ipv6 (const struct route_ipv6 * r, const struct tuntap * tt, unsigned int flags, const struct env_set * es, openvpn_net_ctx_t * ctx)
Definition at line 2353 of file route.c.
References tuntap::actual_name, route_ipv6::adapter_index, tuntap::adapter_index, argv_free(), argv_msg(), argv_new(), argv_printf(), argv_printf_cat(), D_ROUTE, del_route_ipv6_service(), DEV_TYPE_TAP, DEV_TYPE_TUN, route_ipv6::flags, route_ipv6::gateway, argv::gc, gc_free(), gc_init(), gc_malloc(), get_win_sys_path(), M_FATAL, M_INFO, M_WARN, route_ipv6::metric, msg, tuntap_options::msg_channel, net_ctx_reset(), route_ipv6::netbits, netcmd_semaphore_lock(), netcmd_semaphore_release(), NETSH_PATH_SUFFIX, route_ipv6::network, openvpn_execve_check(), tuntap::options, print_in6_addr(), ROUTE_PATH, RT_ADDED, RT_DEFINED, RT_METRIC_DEFINED, snprintf, and tuntap::type.
Referenced by add_routes(), delete_route_connected_v6_net(), and delete_routes().
delete_routes()
void delete_routes (struct route_list * rl, struct route_ipv6_list * rl6, const struct tuntap * tt, unsigned int flags, const struct env_set * es, openvpn_net_ctx_t * ctx)
Definition at line 1257 of file route.c.
References clear_route_ipv6_list(), clear_route_list(), delete_route(), delete_route_ipv6(), route_ipv4::flags, route_ipv6::flags, route_list::iflags, route_ipv6_list::iflags, route_ipv4::next, route_ipv6::next, route_list::rgi, RL_ROUTES_ADDED, route_list::routes, route_ipv6_list::routes_ipv6, and undo_redirect_default_route_to_vpn().
Referenced by do_close_tun().
get_default_gateway()
void get_default_gateway (struct route_gateway_info * rgi, openvpn_net_ctx_t * ctx)
Definition at line 2742 of file route.c.
References route_gateway_info::adapter_index, adapter_index_of_ip(), route_gateway_address::addr, CLEAR, route_gateway_info::flags, route_gateway_info::gateway, gc_free(), gc_new(), get_adapter(), get_adapter_info_list(), get_default_gateway_row(), get_windows_routing_table(), route_gateway_info::hwaddr, route_gateway_address::netmask, RGI_ADDR_DEFINED, RGI_HWADDR_DEFINED, RGI_IFACE_DEFINED, RGI_NETMASK_DEFINED, and TUN_ADAPTER_INDEX_INVALID.
Referenced by add_option(), check_subnet_conflict(), init_route_list(), init_static(), push_peer_info(), and warn_on_use_of_common_subnets().
get_default_gateway_ipv6()
void get_default_gateway_ipv6 (struct route_ipv6_gateway_info * rgi, const struct in6_addr * dest, openvpn_net_ctx_t * ctx)
Definition at line 2828 of file route.c.
References route_ipv6_gateway_info::adapter_index, route_ipv6_gateway_address::addr_ipv6, CLEAR, D_ROUTE, dest, route_ipv6_gateway_info::flags, route_ipv6_gateway_info::gateway, gc_free(), gc_new(), InterfaceLuid(), msg, print_in6_addr(), RGI_ADDR_DEFINED, RGI_IFACE_DEFINED, RGI_ON_LINK, status, and strerror_win32().
Referenced by add_option(), init_route_ipv6_list(), and init_static().
init_route_ipv6_list()
bool init_route_ipv6_list (struct route_ipv6_list * rl6, const struct route_ipv6_option_list * opt6, const char * remote_endpoint, int default_metric, const struct in6_addr * remote_host, struct env_set * es, openvpn_net_ctx_t * ctx)
Definition at line 771 of file route.c.
References route_ipv6::adapter_index, route_ipv6_gateway_info::adapter_index, route_ipv6_gateway_address::addr_ipv6, ALLOC_OBJ_CLEAR_GC, ALLOC_OBJ_GC, clear_route_ipv6_list(), D_ROUTE, route_ipv6_list::default_metric, dmsg, route_ipv6_option_list::flags, route_ipv6::flags, route_ipv6_gateway_info::flags, route_ipv6_list::flags, route_ipv6::gateway, route_ipv6_gateway_info::gateway, route_ipv6_list::gc, gc_free(), gc_new(), get_default_gateway_ipv6(), inet_pton(), init_route_ipv6(), is_route_parm_defined(), M_WARN, route_ipv6::metric, msg, route_ipv6::netbits, route_ipv6::network, route_ipv6_option::next, route_ipv6::next, PACKAGE_NAME, print_default_gateway(), print_in6_addr(), route_ipv6_list::remote_endpoint_ipv6, route_ipv6_list::remote_host_ipv6, route_ipv6_list::rgi6, RGI_ADDR_DEFINED, RGI_IFACE_DEFINED, RGI_ON_LINK, route_ipv6_match_host(), route_ipv6_option_list::routes_ipv6, route_ipv6_list::routes_ipv6, RT_DEFINED, RT_METRIC_DEFINED, RTSA_DEFAULT_METRIC, RTSA_REMOTE_ENDPOINT, RTSA_REMOTE_HOST, setenv_str(), and route_ipv6_list::spec_flags.
Referenced by do_init_route_ipv6_list().
init_route_list()
bool init_route_list (struct route_list * rl, const struct route_option_list * opt, const char * remote_endpoint, int default_metric, in_addr_t remote_host, struct env_set * es, openvpn_net_ctx_t * ctx)
Definition at line 615 of file route.c.
References add_block_local(), route_gateway_address::addr, ALLOC_OBJ_GC, route_special_addr::bypass, clear_route_list(), D_ROUTE, route_special_addr::default_metric, dmsg, route_special_addr::flags, route_option_list::flags, route_gateway_info::flags, route_list::flags, route_gateway_info::gateway, route_list::gc, gc_addspecial(), gc_free(), gc_freeaddrinfo_callback(), gc_new(), get_bypass_addresses(), get_default_gateway(), getaddr(), GETADDR_HOST_ORDER, GETADDR_RESOLVE, GETADDR_WARN_ON_SIGNAL, init_route(), IPV4_INVALID_ADDR, is_route_parm_defined(), M_WARN, msg, route_ipv4::network, route_option::next, PACKAGE_NAME, print_default_gateway(), route_special_addr::remote_endpoint, route_special_addr::remote_host, route_special_addr::remote_host_local, RG_ENABLE, route_list::rgi, RGI_ADDR_DEFINED, route_option_list::routes, route_list::routes, RTSA_DEFAULT_METRIC, RTSA_REMOTE_ENDPOINT, RTSA_REMOTE_HOST, setenv_route_addr(), route_list::spec, and test_local_addr().
Referenced by do_init_route_list().
is_special_addr()
bool is_special_addr (const char * addr_str)
Definition at line 291 of file route.c.
References get_special_addr().
Referenced by add_option().
netbits_to_netmask()
static in_addr_t netbits_to_netmask (const int netbits) inline static
Definition at line 379 of file route.h.
References in_addr_t, and IPV4_NETMASK_HOST.
Referenced by mroute_addr_mask_host_bits(), mroute_addr_print_ex(), netmask_to_netbits(), netmask_to_netbits2(), print_netmask(), and remove_iroutes_from_push_route_list().
netmask_to_netbits()
bool netmask_to_netbits (const in_addr_t network, const in_addr_t netmask, int * netbits)
Definition at line 3881 of file route.c.
References in_addr_t, and netbits_to_netmask().
Referenced by do_route_ipv4_service(), helper_client_server(), and option_iroute().
netmask_to_netbits2()
int netmask_to_netbits2 (in_addr_t netmask)
Definition at line 3912 of file route.c.
References in_addr_t, and netbits_to_netmask().
Referenced by add_route(), delete_route(), do_address_service(), and do_ifconfig_ipv4().
new_route_ipv6_option_list()
struct route_ipv6_option_list* new_route_ipv6_option_list (struct gc_arena * a)
Definition at line 124 of file route.c.
References ALLOC_OBJ_CLEAR_GC, and route_ipv6_option_list::gc.
Referenced by rol6_check_alloc().
new_route_option_list()
struct route_option_list* new_route_option_list (struct gc_arena * a)
Definition at line 115 of file route.c.
References ALLOC_OBJ_CLEAR_GC, and route_option_list::gc.
Referenced by rol_check_alloc().
print_default_gateway()
void print_default_gateway (const int msglevel, const struct route_gateway_info * rgi, const struct route_ipv6_gateway_info * rgi6)
Definition at line 1336 of file route.c.
References route_gateway_info::adapter_index, route_ipv6_gateway_info::adapter_index, route_gateway_address::addr, route_ipv6_gateway_address::addr_ipv6, alloc_buf_gc(), BSTR, buf_printf(), route_gateway_info::flags, route_ipv6_gateway_info::flags, format_hex_ex(), route_gateway_info::gateway, route_ipv6_gateway_info::gateway, gc_free(), gc_new(), route_gateway_info::hwaddr, route_ipv6_gateway_info::hwaddr, msg, route_ipv6_gateway_address::netbits_ipv6, route_gateway_address::netmask, print_in6_addr(), print_in_addr_t(), RGI_ADDR_DEFINED, RGI_HWADDR_DEFINED, RGI_IFACE_DEFINED, RGI_NETMASK_DEFINED, and RGI_ON_LINK.
Referenced by add_option(), init_route_ipv6_list(), init_route_list(), and init_static().
print_route_options()
void print_route_options (const struct route_option_list * rol, int level)
Definition at line 1320 of file route.c.
References route_option_list::flags, msg, route_option::next, print_route_option(), RG_ENABLE, RG_LOCAL, and route_option_list::routes.
Referenced by show_settings().
print_routes()
void print_routes (const struct route_list * rl, int level)
Definition at line 1422 of file route.c.
References route_ipv4::next, print_route(), and route_list::routes.
route_did_redirect_default_gateway()
static int route_did_redirect_default_gateway (const struct route_list * rl) inline static
Definition at line 404 of file route.h.
References BOOL_CAST, route_list::iflags, and RL_DID_REDIRECT_DEFAULT_GATEWAY.
Referenced by do_route().
route_ipv6_clear_host_bits()
void route_ipv6_clear_host_bits (struct route_ipv6 * r6)
Definition at line 1854 of file route.c.
References route_ipv6::netbits, and route_ipv6::network.
Referenced by add_route_ipv6(), and delete_route_connected_v6_net().
route_list_add_vpn_gateway()
void route_list_add_vpn_gateway (struct route_list * rl, struct env_set * es, const in_addr_t addr)
Definition at line 540 of file route.c.
References ASSERT, route_special_addr::flags, route_special_addr::remote_endpoint, RTSA_REMOTE_ENDPOINT, setenv_route_addr(), and route_list::spec.
Referenced by process_ip_header().
route_list_vpn_gateway_needed()
static bool route_list_vpn_gateway_needed (const struct route_list * rl) inline static
Definition at line 391 of file route.h.
References route_special_addr::flags, RTSA_REMOTE_ENDPOINT, and route_list::spec.
setenv_routes()
void setenv_routes (struct env_set * es, const struct route_list * rl)
Definition at line 1452 of file route.c.
References route_ipv4::next, route_list::routes, and setenv_route().
Referenced by do_init_route_list().
setenv_routes_ipv6()
void setenv_routes_ipv6 (struct env_set * es, const struct route_ipv6_list * rl6)
Definition at line 1490 of file route.c.
References route_ipv6::next, route_ipv6_list::routes_ipv6, and setenv_route_ipv6().
Referenced by do_init_route_ipv6_list().
show_routes()
void show_routes (int msglev)
Definition at line 3169 of file route.c.
References format_route_entry(), gc_free(), gc_new(), get_windows_routing_table(), and msg.
Referenced by add_option(), check_add_routes(), do_route(), initialization_sequence_completed(), and management_show_net_callback().
test_local_addr()
int test_local_addr (const in_addr_t addr, const struct route_gateway_info * rgi)
Definition at line 4018 of file route.c.
References gc_free(), gc_new(), get_windows_routing_table(), in_addr_t, TLA_LOCAL, and TLA_NONLOCAL.
Referenced by add_host_route_if_nonlocal(), and init_route_list().
test_routes()
bool test_routes (const struct route_list * rl, const struct tuntap * tt)
Definition at line 2653 of file route.c.
References D_ROUTE, tuntap::did_ifconfig_setup, route_special_addr::flags, route_list::flags, route_ipv4::gateway, gc_free(), gc_new(), get_adapter_info_list(), is_adapter_up(), msg, route_ipv4::next, route_special_addr::remote_endpoint, RG_ENABLE, route_list::routes, RTSA_REMOTE_ENDPOINT, route_list::spec, and test_route_helper().
Referenced by check_add_routes().