OpenVPN: src/openvpn/schedule.h File Reference
schedule.h File Reference
#include "otime.h"
#include "error.h"
Data Structures
struct schedule_entry
struct schedule
Macros
#define IN_TREE(e) ((e)->pri)
Functions
struct schedule * schedule_init (void)
void schedule_free (struct schedule *s)
void schedule_remove_entry (struct schedule *s, struct schedule_entry *e)
struct schedule_entry * schedule_find_least (struct schedule_entry *e)
void schedule_add_modify (struct schedule *s, struct schedule_entry *e)
void schedule_remove_node (struct schedule *s, struct schedule_entry *e)
static void schedule_add_entry (struct schedule *s, struct schedule_entry *e, const struct timeval *tv, unsigned int sigma)
static struct schedule_entry * schedule_get_earliest_wakeup (struct schedule *s, struct timeval *wakeup)
Macro Definition Documentation
IN_TREE
#define IN_TREE (e) ((e)->pri)
Definition at line 75 of file schedule.h.
Function Documentation
schedule_add_entry()
static void schedule_add_entry (struct schedule * s, struct schedule_entry * e, const struct timeval * tv, unsigned int sigma) inline static
Definition at line 98 of file schedule.h.
References schedule::earliest_wakeup, IN_TREE, schedule_add_modify(), schedule_entry::tv, and tv_within_sigma().
Referenced by multi_push_restart_schedule_exit(), and multi_schedule_context_wakeup().
schedule_add_modify()
void schedule_add_modify (struct schedule * s, struct schedule_entry * e)
Definition at line 346 of file schedule.c.
References check_debug_level(), D_SCHEDULER, IN_TREE, schedule_entry::parent, schedule_entry::pri, schedule::root, schedule_insert(), schedule_remove_node(), schedule_rotate_up(), and schedule_set_pri().
Referenced by schedule_add_entry().
schedule_find_least()
struct schedule_entry* schedule_find_least (struct schedule_entry * e)
Definition at line 386 of file schedule.c.
References check_debug_level(), D_SCHEDULER, and schedule_entry::lt.
Referenced by schedule_get_earliest_wakeup().
schedule_free()
void schedule_free (struct schedule * s)
Definition at line 423 of file schedule.c.
Referenced by multi_uninit().
schedule_get_earliest_wakeup()
static struct schedule_entry* schedule_get_earliest_wakeup (struct schedule * s, struct timeval * wakeup) inline static
Definition at line 118 of file schedule.h.
References schedule::earliest_wakeup, schedule::root, schedule_find_least(), and schedule_entry::tv.
Referenced by multi_get_timeout().
schedule_init()
struct schedule* schedule_init (void)
Definition at line 414 of file schedule.c.
References ALLOC_OBJ_CLEAR.
Referenced by multi_init().
schedule_remove_entry()
void schedule_remove_entry (struct schedule * s, struct schedule_entry * e)
Definition at line 429 of file schedule.c.
References schedule::earliest_wakeup, and schedule_remove_node().
Referenced by multi_close_instance(), and multi_process_timeout().
schedule_remove_node()
void schedule_remove_node (struct schedule * s, struct schedule_entry * e)
Definition at line 250 of file schedule.c.
References schedule_entry::gt, schedule_entry::lt, schedule_entry::pri, schedule_detach_parent(), and schedule_rotate_up().
Referenced by schedule_add_modify(), and schedule_remove_entry().