OpenVPN: src/openvpnserv/service.c File Reference
service.c File Reference
#include "service.h"
#include <windows.h>
#include <stdio.h>
#include <process.h>
Functions
BOOL ReportStatusToSCMgr (SERVICE_STATUS_HANDLE service, SERVICE_STATUS *status)
static int CmdInstallServices ()
static int CmdStartService (openvpn_service_type type)
static int CmdRemoveServices ()
int _tmain (int argc, TCHAR *argv[])
Variables
openvpn_service_t openvpn_service [_service_max]
Function Documentation
_tmain()
int _tmain (int argc, TCHAR * argv[])
Definition at line 224 of file service.c.
References APPNAME, automatic, automatic_service, CmdInstallServices(), CmdRemoveServices(), CmdStartService(), interactive, interactive_service, MSG_FLAGS_ERROR, MsgToEventLog(), openvpn_service_t::name, openvpn_service, PACKAGE, PACKAGE_NAME, service_instance, ServiceStartAutomatic(), ServiceStartAutomaticOwn(), ServiceStartInteractive(), and ServiceStartInteractiveOwn().
CmdInstallServices()
static int CmdInstallServices () static
Definition at line 57 of file service.c.
References _service_max, GetLastErrorText(), openvpn_service, and service.
Referenced by _tmain().
CmdRemoveServices()
static int CmdRemoveServices () static
Definition at line 149 of file service.c.
References _service_max, openvpn_service_t::display_name, GetLastErrorText(), openvpn_service_t::name, openvpn_service, service, and status.
Referenced by _tmain().
CmdStartService()
static int CmdStartService (openvpn_service_type type) static
Definition at line 110 of file service.c.
References GetLastErrorText(), openvpn_service, and service.
Referenced by _tmain().
ReportStatusToSCMgr()
BOOL ReportStatusToSCMgr (SERVICE_STATUS_HANDLE service, SERVICE_STATUS * status)
Definition at line 22 of file service.c.
References MSG_FLAGS_ERROR, MsgToEventLog(), service, and status.
Referenced by ServiceCtrlAutomatic(), ServiceCtrlInteractive(), ServiceStartAutomatic(), and ServiceStartInteractive().
Variable Documentation
openvpn_service
openvpn_service_t openvpn_service[_service_max]
Definition at line 18 of file service.c.
Referenced by _tmain(), CmdInstallServices(), CmdRemoveServices(), and CmdStartService().