OpenVPN: src/openvpnserv/service.h File Reference
service.h File Reference
#include <winsock2.h>
#include <windows.h>
#include <stdlib.h>
#include <tchar.h>
Data Structures
struct openvpn_service_t
struct settings_t
Macros
#define APPNAME TEXT(PACKAGE "serv")
#define SERVICE_DEPENDENCIES TAP_WIN_COMPONENT_ID "\0Dhcp\0\0"
#define MSG_FLAGS_ERROR (1<<0)
#define MSG_FLAGS_SYS_CODE (1<<1)
#define M_INFO (0) /* informational */
#define M_SYSERR (MSG_FLAGS_ERROR|MSG_FLAGS_SYS_CODE) /* error + system code */
#define M_ERR (MSG_FLAGS_ERROR) /* error */
#define MAX_NAME 256
Enumerations
enum openvpn_service_type { automatic, interactive, _service_max }
Functions
VOID WINAPI ServiceStartAutomaticOwn (DWORD argc, LPTSTR *argv)
VOID WINAPI ServiceStartAutomatic (DWORD argc, LPTSTR *argv)
VOID WINAPI ServiceStartInteractiveOwn (DWORD argc, LPTSTR *argv)
VOID WINAPI ServiceStartInteractive (DWORD argc, LPTSTR *argv)
BOOL openvpn_vsntprintf (LPTSTR str, size_t size, LPCTSTR format, va_list arglist)
BOOL openvpn_sntprintf (LPTSTR str, size_t size, LPCTSTR format,...)
BOOL openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format,...)
DWORD GetOpenvpnSettings (settings_t *s)
BOOL ReportStatusToSCMgr (SERVICE_STATUS_HANDLE service, SERVICE_STATUS *status)
LPCTSTR GetLastErrorText ()
DWORD MsgToEventLog (DWORD flags, LPCTSTR lpszMsg,...)
wchar_t * utf8to16 (const char *utf8)
const wchar_t * get_win_sys_path (void)
Variables
openvpn_service_t automatic_service
openvpn_service_t interactive_service
LPCTSTR service_instance
Macro Definition Documentation
APPNAME
#define APPNAME TEXT(PACKAGE "serv")
Definition at line 38 of file service.h.
M_ERR
#define M_ERR (MSG_FLAGS_ERROR) /* error */
Definition at line 48 of file service.h.
M_INFO
#define M_INFO (0) /* informational */
Definition at line 46 of file service.h.
M_SYSERR
#define M_SYSERR (MSG_FLAGS_ERROR|MSG_FLAGS_SYS_CODE) /* error + system code */
Definition at line 47 of file service.h.
MAX_NAME
#define MAX_NAME 256
Definition at line 64 of file service.h.
MSG_FLAGS_ERROR
#define MSG_FLAGS_ERROR (1<<0)
Definition at line 44 of file service.h.
MSG_FLAGS_SYS_CODE
#define MSG_FLAGS_SYS_CODE (1<<1)
Definition at line 45 of file service.h.
SERVICE_DEPENDENCIES
#define SERVICE_DEPENDENCIES TAP_WIN_COMPONENT_ID "\0Dhcp\0\0"
Definition at line 39 of file service.h.
Enumeration Type Documentation
openvpn_service_type
enum openvpn_service_type
Enumerator
automatic
interactive
_service_max
Definition at line 50 of file service.h.
Function Documentation
get_win_sys_path()
const wchar_t* get_win_sys_path (void)
Definition at line 1217 of file win32.c.
References ASSERT, and win_sys_path.
Referenced by add_route(), add_route_ipv6(), delete_route(), delete_route_ipv6(), do_ifconfig_ipv6(), env_block(), HandleEnableDHCPMessage(), ipconfig_register_dns(), netsh_delete_address_dns(), netsh_dns_cmd(), netsh_enable_dhcp(), netsh_ifconfig(), netsh_ifconfig_options(), netsh_set_dns6_servers(), RegisterDNS(), and wmic_nicconfig_cmd().
GetLastErrorText()
LPCTSTR GetLastErrorText ()
Definition at line 229 of file common.c.
References openvpn_sntprintf().
Referenced by CmdInstallServices(), CmdRemoveServices(), CmdStartService(), and MsgToEventLog().
GetOpenvpnSettings()
DWORD GetOpenvpnSettings (settings_t * s)
Definition at line 101 of file common.c.
References settings_t::append, settings_t::config_dir, settings_t::exe_path, settings_t::ext_string, GetRegString(), settings_t::log_dir, M_ERR, M_SYSERR, MsgToEventLog(), openvpn_sntprintf(), OVPN_ADMIN_GROUP, settings_t::ovpn_admin_group, PACKAGE_NAME, settings_t::priority, service_instance, and status.
Referenced by ServiceStartAutomatic(), and ServiceStartInteractive().
MsgToEventLog()
DWORD MsgToEventLog (DWORD flags, LPCTSTR lpszMsg, ...)
Definition at line 260 of file common.c.
References APPNAME, GetLastErrorText(), msg, MSG_FLAGS_ERROR, MSG_FLAGS_SYS_CODE, openvpn_sntprintf(), openvpn_vsntprintf(), and service_instance.
Referenced by _tmain(), BlockDNSErrHandler(), CheckConfigPath(), ConvertInterfaceNameToIndex(), CreateClientPipeInstance(), DuplicateAndMapRing(), ExecCommand(), GetOpenvpnSettings(), GetRegString(), GetStartupData(), GetTokenGroups(), HandleBlockDNSMessage(), HandleMessage(), HandleRegisterRingBuffers(), IsAuthorizedUser(), IsUserInGroup(), OvpnDuplicateHandle(), RegisterDNS(), ReportStatusToSCMgr(), ReturnError(), RunOpenvpn(), ServiceStartAutomatic(), and ServiceStartInteractive().
openvpn_sntprintf()
BOOL openvpn_sntprintf (LPTSTR str, size_t size, LPCTSTR format, ...)
Definition at line 47 of file common.c.
References openvpn_vsntprintf().
Referenced by CreateClientPipeInstance(), GetLastErrorText(), GetOpenvpnSettings(), GetRegString(), HandleEnableDHCPMessage(), MsgToEventLog(), netsh_dns_cmd(), RunOpenvpn(), ServiceStartAutomatic(), and wmic_nicconfig_cmd().
openvpn_swprintf()
BOOL openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format, ...)
Definition at line 1521 of file win32.c.
Referenced by CheckConfigPath(), get_adapter_index_method_1(), get_openvpn_reg_value(), RegisterDNS(), ReturnProcessId(), RunOpenvpn(), set_openssl_env_vars(), and ValidateOptions().
openvpn_vsntprintf()
BOOL openvpn_vsntprintf (LPTSTR str, size_t size, LPCTSTR format, va_list arglist)
Definition at line 35 of file common.c.
Referenced by MsgToEventLog(), and openvpn_sntprintf().
ReportStatusToSCMgr()
BOOL ReportStatusToSCMgr (SERVICE_STATUS_HANDLE service, SERVICE_STATUS * status)
Definition at line 22 of file service.c.
References MSG_FLAGS_ERROR, MsgToEventLog(), service, and status.
Referenced by ServiceCtrlAutomatic(), ServiceCtrlInteractive(), ServiceStartAutomatic(), and ServiceStartInteractive().
ServiceStartAutomatic()
VOID WINAPI ServiceStartAutomatic (DWORD argc, LPTSTR * argv)
Definition at line 199 of file automatic.c.
References settings_t::append, automatic_service, CLEAR, settings_t::config_dir, create_event(), settings_t::exe_path, exit_event, settings_t::ext_string, finish(), GetOpenvpnSettings(), init_security_attributes_allow_all(), settings_t::log_dir, M_ERR, M_SYSERR, match(), modext(), MsgToEventLog(), openvpn_service_t::name, openvpn_sntprintf(), PACKAGE, settings_t::priority, ReportStatusToSCMgr(), security_attributes::sa, service, service_instance, ServiceCtrlAutomatic(), settings, and status.
Referenced by _tmain(), and ServiceStartAutomaticOwn().
ServiceStartAutomaticOwn()
VOID WINAPI ServiceStartAutomaticOwn (DWORD argc, LPTSTR * argv)
Definition at line 191 of file automatic.c.
References ServiceStartAutomatic(), and status.
Referenced by _tmain().
ServiceStartInteractive()
VOID WINAPI ServiceStartInteractive (DWORD argc, LPTSTR * argv)
Definition at line 2108 of file interactive.c.
References AddListItem(), CloseHandleEx(), CmpHandle(), CreateClientPipeInstance(), exit_event, FreeWaitHandles(), GetOpenvpnSettings(), InitOverlapped(), interactive_service, M_SYSERR, MsgToEventLog(), openvpn_service_t::name, rdns_semaphore, RemoveListItem(), ReportStatusToSCMgr(), ResetOverlapped(), ReturnError(), RunOpenvpn(), service, ServiceCtrlInteractive(), settings, status, and UpdateWaitHandles().
Referenced by _tmain(), and ServiceStartInteractiveOwn().
ServiceStartInteractiveOwn()
VOID WINAPI ServiceStartInteractiveOwn (DWORD argc, LPTSTR * argv)
Definition at line 2100 of file interactive.c.
References ServiceStartInteractive(), and status.
Referenced by _tmain().
utf8to16()
wchar_t* utf8to16 (const char * utf8)
Definition at line 297 of file common.c.
Referenced by HandleDNSConfigMessage(), InterfaceLuid(), and SetDNSDomain().
Variable Documentation
automatic_service
openvpn_service_t automatic_service
Definition at line 45 of file automatic.c.
Referenced by _tmain(), and ServiceStartAutomatic().
interactive_service
openvpn_service_t interactive_service
Definition at line 64 of file interactive.c.
Referenced by _tmain(), and ServiceStartInteractive().
service_instance
LPCTSTR service_instance
Definition at line 27 of file common.c.
Referenced by _tmain(), CreateClientPipeInstance(), GetOpenvpnSettings(), GetRegString(), MsgToEventLog(), RunOpenvpn(), and ServiceStartAutomatic().