OpenVPN: src/openvpn/session_id.c File Reference
session_id.c File Reference
#include "syshead.h"
#include "error.h"
#include "common.h"
#include "crypto.h"
#include "session_id.h"
#include "memdbg.h"
Functions
void session_id_random (struct session_id *sid)
const char * session_id_print (const struct session_id *sid, struct gc_arena *gc)
Variables
const struct session_id x_session_id_zero
Function Documentation
session_id_print()
const char* session_id_print (const struct session_id * sid, struct gc_arena * gc)
Definition at line 57 of file session_id.c.
References format_hex(), session_id::id, and SID_SIZE.
Referenced by print_key_id(), protocol_dump(), reliable_ack_print(), reliable_ack_read(), tls_multi_process(), tls_pre_decrypt(), tls_process(), and tls_session_init().
session_id_random()
void session_id_random (struct session_id * sid)
Definition at line 51 of file session_id.c.
References session_id::id, prng_bytes(), and SID_SIZE.
Referenced by tls_session_init().
Variable Documentation
x_session_id_zero
const struct session_id x_session_id_zero
Definition at line 48 of file session_id.c.
Referenced by session_id_defined().