OpenVPN: src/openvpn/session_id.h File Reference
session_id.h File Reference
#include "basic.h"
#include "buffer.h"
Data Structures
struct session_id
Macros
#define SID_SIZE (sizeof(x_session_id_zero.id))
Functions
static bool session_id_equal (const struct session_id *sid1, const struct session_id *sid2)
static bool session_id_defined (const struct session_id *sid1)
static bool session_id_read (struct session_id *sid, struct buffer *buf)
static bool session_id_write_prepend (const struct session_id *sid, struct buffer *buf)
static bool session_id_write (const struct session_id *sid, struct buffer *buf)
void session_id_random (struct session_id *sid)
const char * session_id_print (const struct session_id *sid, struct gc_arena *gc)
Variables
const struct session_id x_session_id_zero
Macro Definition Documentation
SID_SIZE
#define SID_SIZE (sizeof(x_session_id_zero.id))
Definition at line 45 of file session_id.h.
Function Documentation
session_id_defined()
static bool session_id_defined (const struct session_id * sid1) inline static
Definition at line 55 of file session_id.h.
References session_id::id, SID_SIZE, and x_session_id_zero.
Referenced by reliable_ack_read(), reliable_ack_write(), tls_pre_decrypt(), tls_process(), and tls_session_init().
session_id_equal()
static bool session_id_equal (const struct session_id * sid1, const struct session_id * sid2) inline static
Definition at line 48 of file session_id.h.
References session_id::id, and SID_SIZE.
Referenced by reliable_ack_read(), and tls_pre_decrypt().
session_id_print()
const char* session_id_print (const struct session_id * sid, struct gc_arena * gc)
Definition at line 57 of file session_id.c.
References format_hex(), session_id::id, and SID_SIZE.
Referenced by print_key_id(), protocol_dump(), reliable_ack_print(), reliable_ack_read(), tls_multi_process(), tls_pre_decrypt(), tls_process(), and tls_session_init().
session_id_random()
void session_id_random (struct session_id * sid)
Definition at line 51 of file session_id.c.
References session_id::id, prng_bytes(), and SID_SIZE.
Referenced by tls_session_init().
session_id_read()
static bool session_id_read (struct session_id * sid, struct buffer * buf) inline static
Definition at line 61 of file session_id.h.
References buf_read(), session_id::id, and SID_SIZE.
Referenced by protocol_dump(), reliable_ack_print(), reliable_ack_read(), and tls_pre_decrypt().
session_id_write()
static bool session_id_write (const struct session_id * sid, struct buffer * buf) inline static
Definition at line 73 of file session_id.h.
References buf_write(), session_id::id, and SID_SIZE.
Referenced by reliable_ack_write(), and write_control_auth().
session_id_write_prepend()
static bool session_id_write_prepend (const struct session_id * sid, struct buffer * buf) inline static
Definition at line 67 of file session_id.h.
References buf_write_prepend(), session_id::id, and SID_SIZE.
Referenced by write_control_auth().
Variable Documentation
x_session_id_zero
const struct session_id x_session_id_zero
Definition at line 48 of file session_id.c.
Referenced by session_id_defined().