OpenVPN: src/openvpn/socks.c File Reference
socks.c File Reference
#include "syshead.h"
#include "common.h"
#include "misc.h"
#include "win32.h"
#include "socket.h"
#include "fdmisc.h"
#include "proxy.h"
#include "memdbg.h"
Macros
#define UP_TYPE_SOCKS "SOCKS Proxy"
Functions
void socks_adjust_frame_parameters (struct frame *frame, int proto)
struct socks_proxy_info * socks_proxy_new (const char *server, const char *port, const char *authfile)
void socks_proxy_close (struct socks_proxy_info *sp)
static bool socks_username_password_auth (struct socks_proxy_info *p, socket_descriptor_t sd, volatile int *signal_received)
static bool socks_handshake (struct socks_proxy_info *p, socket_descriptor_t sd, volatile int *signal_received)
static bool recv_socks_reply (socket_descriptor_t sd, struct openvpn_sockaddr *addr, volatile int *signal_received)
static int port_from_servname (const char *servname)
void establish_socks_proxy_passthru (struct socks_proxy_info *p, socket_descriptor_t sd, const char *host, const char *servname, volatile int *signal_received)
void establish_socks_proxy_udpassoc (struct socks_proxy_info *p, socket_descriptor_t ctrl_sd, socket_descriptor_t udp_sd, struct openvpn_sockaddr *relay_addr, volatile int *signal_received)
void socks_process_incoming_udp (struct buffer *buf, struct link_socket_actual *from)
int socks_process_outgoing_udp (struct buffer *buf, const struct link_socket_actual *to)
Macro Definition Documentation
UP_TYPE_SOCKS
#define UP_TYPE_SOCKS "SOCKS Proxy"
Definition at line 50 of file socks.c.
Function Documentation
establish_socks_proxy_passthru()
void establish_socks_proxy_passthru (struct socks_proxy_info * p, socket_descriptor_t sd, const char * host, const char * servname, volatile int * signal_received)
Definition at line 451 of file socks.c.
References D_LINK_ERRORS, M_ERRNO, msg, MSG_NOSIGNAL, port_from_servname(), recv_socks_reply(), SIGUSR1, socks_handshake(), and ssize_t.
Referenced by phase2_tcp_client().
establish_socks_proxy_udpassoc()
void establish_socks_proxy_udpassoc (struct socks_proxy_info * p, socket_descriptor_t ctrl_sd, socket_descriptor_t udp_sd, struct openvpn_sockaddr * relay_addr, volatile int * signal_received)
Definition at line 514 of file socks.c.
References CLEAR, D_LINK_ERRORS, M_ERRNO, msg, MSG_NOSIGNAL, recv_socks_reply(), SIGUSR1, socks_handshake(), and ssize_t.
Referenced by phase2_socks_client().
port_from_servname()
static int port_from_servname (const char * servname) static
Definition at line 431 of file socks.c.
References service.
Referenced by establish_socks_proxy_passthru().
recv_socks_reply()
static bool recv_socks_reply (socket_descriptor_t sd, struct openvpn_sockaddr * addr, volatile int * signal_received) static
Definition at line 308 of file socks.c.
References openvpn_sockaddr::addr, D_LINK_ERRORS, gc_free(), gc_new(), get_signal(), openvpn_sockaddr::in4, M_ERRNO, M_INFO, msg, MSG_NOSIGNAL, openvpn_fd_set(), print_openvpn_sockaddr(), ssize_t, and status.
Referenced by establish_socks_proxy_passthru(), and establish_socks_proxy_udpassoc().
socks_adjust_frame_parameters()
void socks_adjust_frame_parameters (struct frame * frame, int proto)
Definition at line 53 of file socks.c.
References frame_add_to_extra_link(), and PROTO_UDP.
Referenced by do_init_frame().
socks_handshake()
static bool socks_handshake (struct socks_proxy_info * p, socket_descriptor_t sd, volatile int * signal_received) static
Definition at line 192 of file socks.c.
References socks_proxy_info::authfile, D_LINK_ERRORS, get_signal(), M_ERRNO, msg, MSG_NOSIGNAL, openvpn_fd_set(), socks_username_password_auth(), ssize_t, and status.
Referenced by establish_socks_proxy_passthru(), and establish_socks_proxy_udpassoc().
socks_process_incoming_udp()
void socks_process_incoming_udp (struct buffer * buf, struct link_socket_actual * from)
Definition at line 563 of file socks.c.
References openvpn_sockaddr::addr, BLEN, buf_read(), buf_read_u16(), buf_read_u8(), link_socket_actual::dest, openvpn_sockaddr::in4, and buffer::len.
Referenced by socks_postprocess_incoming_link().
socks_process_outgoing_udp()
int socks_process_outgoing_udp (struct buffer * buf, const struct link_socket_actual * to)
Definition at line 602 of file socks.c.
References openvpn_sockaddr::addr, ASSERT, buf_defined(), buf_sub(), buf_write(), buf_write_u16(), buf_write_u8(), link_socket_actual::dest, and openvpn_sockaddr::in4.
Referenced by socks_preprocess_outgoing_link().
socks_proxy_close()
void socks_proxy_close (struct socks_proxy_info * sp)
Definition at line 91 of file socks.c.
Referenced by uninit_proxy_dowork().
socks_proxy_new()
struct socks_proxy_info* socks_proxy_new (const char * server, const char * port, const char * authfile)
Definition at line 62 of file socks.c.
References ALLOC_OBJ_CLEAR, ASSERT, socks_proxy_info::authfile, socks_proxy_info::defined, socks_proxy_info::port, socks_proxy_info::server, and strncpynt().
Referenced by init_proxy_dowork().
socks_username_password_auth()
static bool socks_username_password_auth (struct socks_proxy_info * p, socket_descriptor_t sd, volatile int * signal_received) static
Definition at line 97 of file socks.c.
References socks_proxy_info::authfile, D_LINK_ERRORS, user_pass::defined, get_signal(), get_user_pass(), GET_USER_PASS_MANAGEMENT, M_ERRNO, M_NONFATAL, msg, MSG_NOSIGNAL, openvpn_fd_set(), openvpn_snprintf(), user_pass::password, ssize_t, status, UP_TYPE_SOCKS, and user_pass::username.
Referenced by socks_handshake().