OpenVPN: src/openvpn/socket.h File Reference
socket.h File Reference
#include "buffer.h"
#include "common.h"
#include "error.h"
#include "proto.h"
#include "mtu.h"
#include "win32.h"
#include "event.h"
#include "proxy.h"
#include "socks.h"
#include "misc.h"
Data Structures
struct openvpn_sockaddr
struct cached_dns_entry
struct link_socket_actual
struct link_socket_addr
struct link_socket_info
struct stream_buf
struct socket_buffer_size
struct link_socket
Macros
#define OPENVPN_PORT "1194"
#define RESOLV_RETRY_INFINITE 1000000000
#define htonps(x) htons(x)
#define ntohps(x) ntohs(x)
#define INETD_NONE 0
#define INETD_WAIT 1
#define INETD_NOWAIT 2
#define LS_MODE_DEFAULT 0
#define LS_MODE_TCP_LISTEN 1
#define LS_MODE_TCP_ACCEPT_FROM 2
#define SF_USE_IP_PKTINFO (1<<0)
#define SF_TCP_NODELAY (1<<1)
#define SF_PORT_SHARE (1<<2)
#define SF_HOST_RANDOMIZE (1<<3)
#define SF_GETADDRINFO_DGRAM (1<<4)
#define MSG_NOSIGNAL 0
#define openvpn_close_socket(s) closesocket(s)
#define PS_SHOW_PORT_IF_DEFINED (1<<0)
#define PS_SHOW_PORT (1<<1)
#define PS_SHOW_PKTINFO (1<<2)
#define PS_DONT_SHOW_ADDR (1<<3)
#define PS_DONT_SHOW_FAMILY (1<<4)
#define IA_EMPTY_IF_UNDEF (1<<0)
#define IA_NET_ORDER (1<<1)
#define SA_IP_PORT (1<<0)
#define SA_SET_IF_NONZERO (1<<1)
#define IPV4_INVALID_ADDR 0xffffffff
#define OIA_HOSTNAME 0
#define OIA_IP 1
#define OIA_ERROR -1
#define GETADDR_RESOLVE (1<<0)
#define GETADDR_FATAL (1<<1)
#define GETADDR_HOST_ORDER (1<<2)
#define GETADDR_MENTION_RESOLVE_RETRY (1<<3)
#define GETADDR_FATAL_ON_SIGNAL (1<<4)
#define GETADDR_WARN_ON_SIGNAL (1<<5)
#define GETADDR_MSG_VIRT_OUT (1<<6)
#define GETADDR_TRY_ONCE (1<<7)
#define GETADDR_UPDATE_MANAGEMENT_STATE (1<<8)
#define GETADDR_RANDOMIZE (1<<9)
#define GETADDR_PASSIVE (1<<10)
#define GETADDR_DATAGRAM (1<<11)
#define GETADDR_CACHE_MASK (GETADDR_DATAGRAM|GETADDR_PASSIVE)
#define IPv4_UDP_HEADER_SIZE 28
#define IPv4_TCP_HEADER_SIZE 40
#define IPv6_UDP_HEADER_SIZE 48
#define IPv6_TCP_HEADER_SIZE 60
Typedefs
typedef uint16_t packet_size_type
Enumerations
enum proto_num {
PROTO_NONE, PROTO_UDP, PROTO_TCP, PROTO_TCP_SERVER,
PROTO_TCP_CLIENT, PROTO_N
}
Functions
int socket_recv_queue (struct link_socket *sock, int maxsize)
int socket_send_queue (struct link_socket *sock, struct buffer *buf, const struct link_socket_actual *to)
int socket_finalize (SOCKET s, struct overlapped_io *io, struct buffer *buf, struct link_socket_actual *from)
struct link_socket * link_socket_new (void)
void socket_bind (socket_descriptor_t sd, struct addrinfo *local, int af_family, const char *prefix, bool ipv6only)
int openvpn_connect (socket_descriptor_t sd, const struct sockaddr *remote, int connect_timeout, volatile int *signal_received)
void link_socket_init_phase1 (struct link_socket *sock, const char *local_host, const char *local_port, const char *remote_host, const char *remote_port, struct cached_dns_entry *dns_cache, int proto, sa_family_t af, bool bind_ipv6_only, int mode, const struct link_socket *accept_from, struct http_proxy_info *http_proxy, struct socks_proxy_info *socks_proxy, bool bind_local, bool remote_float, int inetd, struct link_socket_addr *lsa, const char *ipchange_command, const struct plugin_list *plugins, int resolve_retry_seconds, int mtu_discover_type, int rcvbuf, int sndbuf, int mark, const char *bind_dev, struct event_timeout *server_poll_timeout, unsigned int sockflags)
void link_socket_init_phase2 (struct link_socket *sock, const struct frame *frame, struct signal_info *sig_info)
void do_preresolve (struct context *c)
void socket_adjust_frame_parameters (struct frame *frame, int proto)
void frame_adjust_path_mtu (struct frame *frame, int pmtu, int proto)
void link_socket_close (struct link_socket *sock)
void sd_close (socket_descriptor_t *sd)
const char * print_sockaddr_ex (const struct sockaddr *addr, const char *separator, const unsigned int flags, struct gc_arena *gc)
static const char * print_openvpn_sockaddr_ex (const struct openvpn_sockaddr *addr, const char *separator, const unsigned int flags, struct gc_arena *gc)
static const char * print_openvpn_sockaddr (const struct openvpn_sockaddr *addr, struct gc_arena *gc)
static const char * print_sockaddr (const struct sockaddr *addr, struct gc_arena *gc)
const char * print_link_socket_actual_ex (const struct link_socket_actual *act, const char *separator, const unsigned int flags, struct gc_arena *gc)
const char * print_link_socket_actual (const struct link_socket_actual *act, struct gc_arena *gc)
const char * print_in_addr_t (in_addr_t addr, unsigned int flags, struct gc_arena *gc)
const char * print_in6_addr (struct in6_addr addr6, unsigned int flags, struct gc_arena *gc)
struct in6_addr add_in6_addr (struct in6_addr base, uint32_t add)
void setenv_sockaddr (struct env_set *es, const char *name_prefix, const struct openvpn_sockaddr *addr, const unsigned int flags)
void setenv_in_addr_t (struct env_set *es, const char *name_prefix, in_addr_t addr, const unsigned int flags)
void setenv_in6_addr (struct env_set *es, const char *name_prefix, const struct in6_addr *addr, const unsigned int flags)
void setenv_link_socket_actual (struct env_set *es, const char *name_prefix, const struct link_socket_actual *act, const unsigned int flags)
void bad_address_length (int actual, int expected)
in_addr_t link_socket_current_remote (const struct link_socket_info *info)
const struct in6_addr * link_socket_current_remote_ipv6 (const struct link_socket_info *info)
void link_socket_connection_initiated (struct link_socket_info *info, const struct link_socket_actual *addr, const char *common_name, struct env_set *es)
void link_socket_bad_incoming_addr (struct buffer *buf, const struct link_socket_info *info, const struct link_socket_actual *from_addr)
void set_actual_address (struct link_socket_actual *actual, struct addrinfo *ai)
void link_socket_bad_outgoing_addr (void)
void setenv_trusted (struct env_set *es, const struct link_socket_info *info)
bool link_socket_update_flags (struct link_socket *ls, unsigned int sockflags)
void link_socket_update_buffer_sizes (struct link_socket *ls, int rcvbuf, int sndbuf)
int openvpn_inet_aton (const char *dotted_quad, struct in_addr *addr)
bool ip_addr_dotted_quad_safe (const char *dotted_quad)
bool ip_or_dns_addr_safe (const char *addr, const bool allow_fqdn)
bool mac_addr_safe (const char *mac_addr)
bool ipv6_addr_safe (const char *ipv6_text_addr)
socket_descriptor_t create_socket_tcp (struct addrinfo *)
socket_descriptor_t socket_do_accept (socket_descriptor_t sd, struct link_socket_actual *act, const bool nowait)
bool proto_is_net (int proto)
bool proto_is_dgram (int proto)
bool proto_is_udp (int proto)
bool proto_is_tcp (int proto)
in_addr_t getaddr (unsigned int flags, const char *hostname, int resolve_retry_seconds, bool *succeeded, volatile int *signal_received)
Translate an IPv4 addr or hostname from string form to in_addr_t.
bool get_ipv6_addr (const char *hostname, struct in6_addr *network, unsigned int *netbits, int msglevel)
Translate an IPv6 addr or hostname from string form to in6_addr.
int openvpn_getaddrinfo (unsigned int flags, const char *hostname, const char *servname, int resolve_retry_seconds, volatile int *signal_received, int ai_family, struct addrinfo **res)
int ascii2proto (const char *proto_name)
sa_family_t ascii2af (const char *proto_name)
const char * proto2ascii (int proto, sa_family_t af, bool display_form)
const char * proto2ascii_all (struct gc_arena *gc)
const char * proto_remote (int proto, bool remote)
const char * addr_family_name (int af)
static int datagram_overhead (int proto)
static bool link_socket_proto_connection_oriented (int proto)
static bool link_socket_connection_oriented (const struct link_socket *sock)
static bool addr_defined (const struct openvpn_sockaddr *addr)
static bool addr_local (const struct sockaddr *addr)
static bool addr_defined_ipi (const struct link_socket_actual *lsa)
static bool link_socket_actual_defined (const struct link_socket_actual *act)
static bool addr_match (const struct openvpn_sockaddr *a1, const struct openvpn_sockaddr *a2)
static bool addrlist_match (const struct openvpn_sockaddr *a1, const struct addrinfo *addrlist)
static in_addr_t addr_host (const struct openvpn_sockaddr *addr)
static bool addrlist_port_match (const struct openvpn_sockaddr *a1, const struct addrinfo *a2)
static bool addr_port_match (const struct openvpn_sockaddr *a1, const struct openvpn_sockaddr *a2)
static bool addr_match_proto (const struct openvpn_sockaddr *a1, const struct openvpn_sockaddr *a2, const int proto)
static bool addrlist_match_proto (const struct openvpn_sockaddr *a1, struct addrinfo *addr_list, const int proto)
static void addr_zero_host (struct openvpn_sockaddr *addr)
static void addr_copy_sa (struct openvpn_sockaddr *dst, const struct openvpn_sockaddr *src)
static bool addr_inet4or6 (struct sockaddr *addr)
int addr_guess_family (sa_family_t af, const char *name)
static int af_addr_size (sa_family_t af)
static bool link_socket_actual_match (const struct link_socket_actual *a1, const struct link_socket_actual *a2)
static bool socket_connection_reset (const struct link_socket *sock, int status)
static bool link_socket_verify_incoming_addr (struct buffer *buf, const struct link_socket_info *info, const struct link_socket_actual *from_addr)
static void link_socket_get_outgoing_addr (struct buffer *buf, const struct link_socket_info *info, struct link_socket_actual **act)
static void link_socket_set_outgoing_addr (struct link_socket_info *info, const struct link_socket_actual *act, const char *common_name, struct env_set *es)
bool stream_buf_read_setup_dowork (struct link_socket *sock)
static bool stream_buf_read_setup (struct link_socket *sock)
int link_socket_read_tcp (struct link_socket *sock, struct buffer *buf)
static int link_socket_read_udp_win32 (struct link_socket *sock, struct buffer *buf, struct link_socket_actual *from)
static int link_socket_read (struct link_socket *sock, struct buffer *buf, struct link_socket_actual *from)
int link_socket_write_tcp (struct link_socket *sock, struct buffer *buf, struct link_socket_actual *to)
static int link_socket_write_win32 (struct link_socket *sock, struct buffer *buf, struct link_socket_actual *to)
static size_t link_socket_write_udp (struct link_socket *sock, struct buffer *buf, struct link_socket_actual *to)
static int link_socket_write (struct link_socket *sock, struct buffer *buf, struct link_socket_actual *to)
static bool socket_read_residual (const struct link_socket *s)
static event_t socket_event_handle (const struct link_socket *s)
event_t socket_listen_event_handle (struct link_socket *s)
unsigned int socket_set (struct link_socket *s, struct event_set *es, unsigned int rwflags, void *arg, unsigned int *persistent)
static void socket_set_listen_persistent (struct link_socket *s, struct event_set *es, void *arg)
static void socket_reset_listen_persistent (struct link_socket *s)
const char * socket_stat (const struct link_socket *s, unsigned int rwflags, struct gc_arena *gc)
Variables
const int proto_overhead []
Macro Definition Documentation
GETADDR_CACHE_MASK
#define GETADDR_CACHE_MASK (GETADDR_DATAGRAM|GETADDR_PASSIVE)
Definition at line 536 of file socket.h.
GETADDR_DATAGRAM
#define GETADDR_DATAGRAM (1<<11)
Definition at line 534 of file socket.h.
GETADDR_FATAL
#define GETADDR_FATAL (1<<1)
Definition at line 524 of file socket.h.
GETADDR_FATAL_ON_SIGNAL
#define GETADDR_FATAL_ON_SIGNAL (1<<4)
Definition at line 527 of file socket.h.
GETADDR_HOST_ORDER
#define GETADDR_HOST_ORDER (1<<2)
Definition at line 525 of file socket.h.
GETADDR_MENTION_RESOLVE_RETRY
#define GETADDR_MENTION_RESOLVE_RETRY (1<<3)
Definition at line 526 of file socket.h.
GETADDR_MSG_VIRT_OUT
#define GETADDR_MSG_VIRT_OUT (1<<6)
Definition at line 529 of file socket.h.
GETADDR_PASSIVE
#define GETADDR_PASSIVE (1<<10)
Definition at line 533 of file socket.h.
GETADDR_RANDOMIZE
#define GETADDR_RANDOMIZE (1<<9)
Definition at line 532 of file socket.h.
GETADDR_RESOLVE
#define GETADDR_RESOLVE (1<<0)
Definition at line 523 of file socket.h.
GETADDR_TRY_ONCE
#define GETADDR_TRY_ONCE (1<<7)
Definition at line 530 of file socket.h.
GETADDR_UPDATE_MANAGEMENT_STATE
#define GETADDR_UPDATE_MANAGEMENT_STATE (1<<8)
Definition at line 531 of file socket.h.
GETADDR_WARN_ON_SIGNAL
#define GETADDR_WARN_ON_SIGNAL (1<<5)
Definition at line 528 of file socket.h.
htonps
#define htonps (x) htons(x)
Definition at line 58 of file socket.h.
IA_EMPTY_IF_UNDEF
#define IA_EMPTY_IF_UNDEF (1<<0)
Definition at line 397 of file socket.h.
IA_NET_ORDER
#define IA_NET_ORDER (1<<1)
Definition at line 398 of file socket.h.
INETD_NONE
#define INETD_NONE 0
Definition at line 191 of file socket.h.
INETD_NOWAIT
#define INETD_NOWAIT 2
Definition at line 193 of file socket.h.
INETD_WAIT
#define INETD_WAIT 1
Definition at line 192 of file socket.h.
IPV4_INVALID_ADDR
#define IPV4_INVALID_ADDR 0xffffffff
Definition at line 432 of file socket.h.
IPv4_TCP_HEADER_SIZE
#define IPv4_TCP_HEADER_SIZE 40
Definition at line 597 of file socket.h.
IPv4_UDP_HEADER_SIZE
#define IPv4_UDP_HEADER_SIZE 28
Definition at line 596 of file socket.h.
IPv6_TCP_HEADER_SIZE
#define IPv6_TCP_HEADER_SIZE 60
Definition at line 599 of file socket.h.
IPv6_UDP_HEADER_SIZE
#define IPv6_UDP_HEADER_SIZE 48
Definition at line 598 of file socket.h.
LS_MODE_DEFAULT
#define LS_MODE_DEFAULT 0
Definition at line 196 of file socket.h.
LS_MODE_TCP_ACCEPT_FROM
#define LS_MODE_TCP_ACCEPT_FROM 2
Definition at line 198 of file socket.h.
LS_MODE_TCP_LISTEN
#define LS_MODE_TCP_LISTEN 1
Definition at line 197 of file socket.h.
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
Definition at line 257 of file socket.h.
ntohps
#define ntohps (x) ntohs(x)
Definition at line 61 of file socket.h.
OIA_ERROR
#define OIA_ERROR -1
Definition at line 465 of file socket.h.
OIA_HOSTNAME
#define OIA_HOSTNAME 0
Definition at line 463 of file socket.h.
OIA_IP
#define OIA_IP 1
Definition at line 464 of file socket.h.
openvpn_close_socket
#define openvpn_close_socket (s) closesocket(s)
Definition at line 262 of file socket.h.
OPENVPN_PORT
#define OPENVPN_PORT "1194"
Definition at line 41 of file socket.h.
PS_DONT_SHOW_ADDR
#define PS_DONT_SHOW_ADDR (1<<3)
Definition at line 352 of file socket.h.
PS_DONT_SHOW_FAMILY
#define PS_DONT_SHOW_FAMILY (1<<4)
Definition at line 353 of file socket.h.
PS_SHOW_PKTINFO
#define PS_SHOW_PKTINFO (1<<2)
Definition at line 351 of file socket.h.
PS_SHOW_PORT
#define PS_SHOW_PORT (1<<1)
Definition at line 350 of file socket.h.
PS_SHOW_PORT_IF_DEFINED
#define PS_SHOW_PORT_IF_DEFINED (1<<0)
Definition at line 349 of file socket.h.
RESOLV_RETRY_INFINITE
#define RESOLV_RETRY_INFINITE 1000000000
Definition at line 47 of file socket.h.
SA_IP_PORT
#define SA_IP_PORT (1<<0)
Definition at line 405 of file socket.h.
SA_SET_IF_NONZERO
#define SA_SET_IF_NONZERO (1<<1)
Definition at line 406 of file socket.h.
SF_GETADDRINFO_DGRAM
#define SF_GETADDRINFO_DGRAM (1<<4)
Definition at line 212 of file socket.h.
SF_HOST_RANDOMIZE
#define SF_HOST_RANDOMIZE (1<<3)
Definition at line 211 of file socket.h.
SF_PORT_SHARE
#define SF_PORT_SHARE (1<<2)
Definition at line 210 of file socket.h.
SF_TCP_NODELAY
#define SF_TCP_NODELAY (1<<1)
Definition at line 209 of file socket.h.
SF_USE_IP_PKTINFO
#define SF_USE_IP_PKTINFO (1<<0)
Definition at line 208 of file socket.h.
Typedef Documentation
packet_size_type
typedef uint16_t packet_size_type
Definition at line 55 of file socket.h.
Enumeration Type Documentation
proto_num
enum proto_num
Enumerator
PROTO_NONE
PROTO_UDP
PROTO_TCP
PROTO_TCP_SERVER
PROTO_TCP_CLIENT
PROTO_N
Definition at line 572 of file socket.h.
Function Documentation
add_in6_addr()
struct in6_addr add_in6_addr (struct in6_addr base, uint32_t add)
Definition at line 3043 of file socket.c.
References UINT8_MAX.
Referenced by helper_client_server(), ifconfig_pool_acquire(), and ifconfig_pool_handle_to_ipv6_base().
addr_copy_sa()
static void addr_copy_sa (struct openvpn_sockaddr * dst, const struct openvpn_sockaddr * src) inline static
Definition at line 853 of file socket.h.
References openvpn_sockaddr::addr, and dst.
Referenced by link_socket_read().
addr_defined()
static bool addr_defined (const struct openvpn_sockaddr * addr) inline static
Definition at line 634 of file socket.h.
References openvpn_sockaddr::addr, openvpn_sockaddr::in4, openvpn_sockaddr::in6, and openvpn_sockaddr::sa.
Referenced by initialization_sequence_completed(), link_socket_actual_defined(), and log_entry_print().
addr_defined_ipi()
static bool addr_defined_ipi (const struct link_socket_actual * lsa) inline static
Definition at line 672 of file socket.h.
References openvpn_sockaddr::addr, ASSERT, link_socket_actual::dest, and openvpn_sockaddr::sa.
Referenced by print_link_socket_actual_ex().
addr_family_name()
const char* addr_family_name (int af)
Definition at line 3291 of file socket.c.
Referenced by link_socket_init_phase2(), and socket_bind().
addr_guess_family()
int addr_guess_family (sa_family_t af, const char * name)
addr_host()
static in_addr_t addr_host (const struct openvpn_sockaddr * addr) inline static
Definition at line 749 of file socket.h.
References openvpn_sockaddr::addr, openvpn_sockaddr::in4, and openvpn_sockaddr::sa.
addr_inet4or6()
static bool addr_inet4or6 (struct sockaddr * addr) inline static
Definition at line 859 of file socket.h.
addr_local()
static bool addr_local (const struct sockaddr * addr) inline static
Definition at line 651 of file socket.h.
addr_match()
static bool addr_match (const struct openvpn_sockaddr * a1, const struct openvpn_sockaddr * a2) inline static
Definition at line 705 of file socket.h.
References openvpn_sockaddr::addr, ASSERT, openvpn_sockaddr::in4, openvpn_sockaddr::in6, IN6_ARE_ADDR_EQUAL, and openvpn_sockaddr::sa.
Referenced by addr_match_proto().
addr_match_proto()
static bool addr_match_proto (const struct openvpn_sockaddr * a1, const struct openvpn_sockaddr * a2, const int proto) inline static
Definition at line 817 of file socket.h.
References addr_match(), addr_port_match(), and link_socket_proto_connection_oriented().
Referenced by link_socket_set_outgoing_addr().
addr_port_match()
static bool addr_port_match (const struct openvpn_sockaddr * a1, const struct openvpn_sockaddr * a2) inline static
Definition at line 800 of file socket.h.
References openvpn_sockaddr::addr, ASSERT, openvpn_sockaddr::in4, openvpn_sockaddr::in6, IN6_ARE_ADDR_EQUAL, and openvpn_sockaddr::sa.
Referenced by addr_match_proto(), and link_socket_actual_match().
addr_zero_host()
static void addr_zero_host (struct openvpn_sockaddr * addr) inline static
Definition at line 838 of file socket.h.
References openvpn_sockaddr::addr, openvpn_sockaddr::in4, openvpn_sockaddr::in6, and openvpn_sockaddr::sa.
Referenced by phase2_socks_client().
addrlist_match()
static bool addrlist_match (const struct openvpn_sockaddr * a1, const struct addrinfo * addrlist) inline static
Definition at line 720 of file socket.h.
References openvpn_sockaddr::addr, ASSERT, openvpn_sockaddr::in4, openvpn_sockaddr::in6, IN6_ARE_ADDR_EQUAL, and openvpn_sockaddr::sa.
Referenced by addrlist_match_proto(), and socket_listen_accept().
addrlist_match_proto()
static bool addrlist_match_proto (const struct openvpn_sockaddr * a1, struct addrinfo * addr_list, const int proto) inline static
Definition at line 828 of file socket.h.
References addrlist_match(), addrlist_port_match(), and link_socket_proto_connection_oriented().
Referenced by link_socket_set_outgoing_addr(), and link_socket_verify_incoming_addr().
addrlist_port_match()
static bool addrlist_port_match (const struct openvpn_sockaddr * a1, const struct addrinfo * a2) inline static
Definition at line 765 of file socket.h.
References openvpn_sockaddr::addr, ASSERT, openvpn_sockaddr::in4, openvpn_sockaddr::in6, IN6_ARE_ADDR_EQUAL, and openvpn_sockaddr::sa.
Referenced by addrlist_match_proto().
af_addr_size()
static int af_addr_size (sa_family_t af) inline static
Definition at line 867 of file socket.h.
References ASSERT, M_ERR, and msg.
Referenced by openvpn_connect(), socket_do_accept(), socket_finalize(), and socket_recv_queue().
ascii2af()
sa_family_t ascii2af (const char * proto_name)
Definition at line 3238 of file socket.c.
References proto_names::proto_af, proto_names::short_form, and SIZE.
Referenced by add_option().
ascii2proto()
int ascii2proto (const char * proto_name)
Definition at line 3224 of file socket.c.
References proto_names::proto, proto_names::short_form, and SIZE.
Referenced by add_option().
bad_address_length()
void bad_address_length (int actual, int expected)
Definition at line 3343 of file socket.c.
References M_FATAL, and msg.
Referenced by socket_finalize(), and socket_recv_queue().
create_socket_tcp()
socket_descriptor_t create_socket_tcp (struct addrinfo *)
Definition at line 1010 of file socket.c.
References ASSERT, M_ERR, msg, and set_cloexec().
Referenced by create_socket(), man_connect(), man_listen(), and phase2_tcp_client().
datagram_overhead()
static int datagram_overhead (int proto) inline static
Definition at line 604 of file socket.h.
References ASSERT, PROTO_N, and proto_overhead.
Referenced by frame_adjust_path_mtu(), and process_outgoing_link().
do_preresolve()
void do_preresolve (struct context * c)
Definition at line 341 of file socket.c.
References connection_entry::af, connection_list::array, connection_entry::bind_local, options::connection_list, do_preresolve_host(), connection_entry::flags, GETADDR_DATAGRAM, GETADDR_FATAL, GETADDR_MENTION_RESOLVE_RETRY, GETADDR_PASSIVE, GETADDR_RANDOMIZE, GETADDR_RESOLVE, GETADDR_UPDATE_MANAGEMENT_STATE, connection_entry::http_proxy_options, options::ip_remote_hint, connection_list::len, connection_entry::local, connection_entry::local_port, context::options, http_proxy_options::port, connection_entry::proto, proto_is_dgram(), connection_entry::remote, connection_entry::remote_port, http_proxy_options::server, SF_HOST_RANDOMIZE, SIGHUP, options::sockflags, connection_entry::socks_proxy_port, connection_entry::socks_proxy_server, status, and throw_signal_soft().
Referenced by init_instance().
frame_adjust_path_mtu()
void frame_adjust_path_mtu (struct frame * frame, int pmtu, int proto)
Definition at line 1692 of file socket.c.
References datagram_overhead(), frame_set_mtu_dynamic(), and SET_MTU_UPPER_BOUND.
Referenced by check_fragment().
get_ipv6_addr()
bool get_ipv6_addr (const char * hostname, struct in6_addr * network, unsigned int * netbits, int msglevel)
Translate an IPv6 addr or hostname from string form to in6_addr.
Definition at line 224 of file socket.c.
References get_addr_generic(), and GETADDR_RESOLVE.
Referenced by add_option(), dhcp_option_dns6_parse(), ifconfig_pool_read(), init_route_ipv6(), ipv6_addr_safe_hexplusbits(), and option_iroute_ipv6().
getaddr()
in_addr_t getaddr (unsigned int flags, const char * hostname, int resolve_retry_seconds, bool * succeeded, volatile int * signal_received)
Translate an IPv4 addr or hostname from string form to in_addr_t.
In case of resolve error, it will try again for resolve_retry_seconds seconds.
Definition at line 193 of file socket.c.
References get_addr_generic(), in_addr_t, M_WARN, and status.
Referenced by add_client_nat_to_option_list(), add_host_route_array(), add_option(), get_adapter_ip_netmask(), get_ip_addr(), ifconfig_pool_read(), init_route(), init_route_list(), init_tun(), ip_addr_string_to_array(), man_kill(), option_iroute(), and remove_iroutes_from_push_route_list().
ip_addr_dotted_quad_safe()
bool ip_addr_dotted_quad_safe (const char * dotted_quad)
Definition at line 699 of file socket.c.
References OIA_IP, and openvpn_inet_aton().
Referenced by add_option(), dhcp_option_address_parse(), and ip_or_dns_addr_safe().
ip_or_dns_addr_safe()
bool ip_or_dns_addr_safe (const char * addr, const bool allow_fqdn)
Definition at line 785 of file socket.c.
References dns_addr_safe(), and ip_addr_dotted_quad_safe().
Referenced by add_option().
ipv6_addr_safe()
bool ipv6_addr_safe (const char * ipv6_text_addr)
Definition at line 749 of file socket.c.
References inet_pton().
Referenced by add_option().
link_socket_actual_defined()
static bool link_socket_actual_defined (const struct link_socket_actual * act) inline static
Definition at line 699 of file socket.h.
References addr_defined(), and link_socket_actual::dest.
Referenced by check_ping_restart(), link_socket_current_remote(), link_socket_current_remote_ipv6(), link_socket_get_outgoing_addr(), link_socket_verify_incoming_addr(), process_outgoing_link(), resolve_remote(), tls_multi_process(), tls_update_remote_addr(), and write_control_auth().
link_socket_actual_match()
static bool link_socket_actual_match (const struct link_socket_actual * a1, const struct link_socket_actual * a2) inline static
Definition at line 886 of file socket.h.
References addr_port_match(), and link_socket_actual::dest.
Referenced by handle_data_channel_packet(), multi_get_create_instance_udp(), tls_pre_decrypt(), and tls_update_remote_addr().
link_socket_bad_incoming_addr()
void link_socket_bad_incoming_addr (struct buffer * buf, const struct link_socket_info * info, const struct link_socket_actual * from_addr)
Definition at line 2520 of file socket.c.
References openvpn_sockaddr::addr, D_LINK_ERRORS, link_socket_actual::dest, gc_free(), gc_new(), buffer::len, link_socket_info::lsa, msg, print_link_socket_actual(), print_sockaddr_ex(), PS_SHOW_PORT, link_socket_addr::remote_list, and openvpn_sockaddr::sa.
Referenced by process_incoming_link_part1().
link_socket_bad_outgoing_addr()
void link_socket_bad_outgoing_addr (void)
Definition at line 2549 of file socket.c.
References D_READ_WRITE, and dmsg.
Referenced by link_socket_get_outgoing_addr().
link_socket_close()
void link_socket_close (struct link_socket * sock)
Definition at line 2385 of file socket.c.
References close_net_event_win32(), link_socket::ctrl_sd, D_LOW, free_buf(), link_socket::listen_handle, M_ERRNO, M_WARN, msg, openvpn_close_socket, overlapped_io_close(), link_socket::reads, link_socket::sd, socket_defined(), SOCKET_UNDEFINED, link_socket::stream_buf, stream_buf_close(), link_socket::stream_buf_data, and link_socket::writes.
Referenced by do_close_link_socket().
link_socket_connection_initiated()
void link_socket_connection_initiated (struct link_socket_info * info, const struct link_socket_actual * addr, const char * common_name, struct env_set * es)
Definition at line 2469 of file socket.c.
References link_socket_addr::actual, alloc_buf_gc(), argv_free(), argv_new(), BSTR, buf_printf(), link_socket_info::connection_established, argv::gc, gc_free(), gc_new(), link_socket_info::ipchange_command, ipchange_fmt(), link_socket_info::lsa, M_INFO, M_WARN, msg, OPENVPN_PLUGIN_FUNC_SUCCESS, OPENVPN_PLUGIN_IPCHANGE, openvpn_run_script(), plugin_call(), plugin_defined(), link_socket_info::plugins, print_link_socket_actual(), setenv_str(), and setenv_trusted().
Referenced by link_socket_set_outgoing_addr().
link_socket_connection_oriented()
static bool link_socket_connection_oriented (const struct link_socket * sock) inline static
Definition at line 621 of file socket.h.
References link_socket::info, link_socket_proto_connection_oriented(), and link_socket_info::proto.
Referenced by check_tls_errors(), process_incoming_link_part1(), socket_connection_reset(), socket_frame_init(), and stream_buf_read_setup().
link_socket_current_remote()
in_addr_t link_socket_current_remote (const struct link_socket_info * info)
Definition at line 2555 of file socket.c.
References link_socket_addr::actual, openvpn_sockaddr::addr, link_socket_addr::current_remote, link_socket_actual::dest, openvpn_sockaddr::in4, IPV4_INVALID_ADDR, link_socket_actual_defined(), link_socket_info::lsa, and openvpn_sockaddr::sa.
Referenced by do_init_route_list().
link_socket_current_remote_ipv6()
const struct in6_addr* link_socket_current_remote_ipv6 (const struct link_socket_info * info)
Definition at line 2590 of file socket.c.
References link_socket_addr::actual, openvpn_sockaddr::addr, link_socket_addr::current_remote, link_socket_actual::dest, openvpn_sockaddr::in6, link_socket_actual_defined(), link_socket_info::lsa, and openvpn_sockaddr::sa.
Referenced by do_init_route_ipv6_list().
link_socket_get_outgoing_addr()
static void link_socket_get_outgoing_addr (struct buffer * buf, const struct link_socket_info * info, struct link_socket_actual ** act) inline static
Definition at line 965 of file socket.h.
References link_socket_addr::actual, buffer::len, link_socket_actual_defined(), link_socket_bad_outgoing_addr(), and link_socket_info::lsa.
Referenced by encrypt_sign().
link_socket_init_phase1()
void link_socket_init_phase1 (struct link_socket * sock, const char * local_host, const char * local_port, const char * remote_host, const char * remote_port, struct cached_dns_entry * dns_cache, int proto, sa_family_t af, bool bind_ipv6_only, int mode, const struct link_socket * accept_from, struct http_proxy_info * http_proxy, struct socks_proxy_info * socks_proxy, bool bind_local, bool remote_float, int inetd, struct link_socket_addr * lsa, const char * ipchange_command, const struct plugin_list * plugins, int resolve_retry_seconds, int mtu_discover_type, int rcvbuf, int sndbuf, int mark, const char * bind_dev, struct event_timeout * server_poll_timeout, unsigned int sockflags)
Definition at line 1879 of file socket.c.
References link_socket_info::af, ASSERT, link_socket::bind_dev, link_socket_info::bind_ipv6_only, link_socket::bind_local, bind_local(), link_socket::dns_cache, link_socket::http_proxy, link_socket::inetd, inetd_socket_descriptor, link_socket::info, link_socket_info::ipchange_command, link_socket::local_host, link_socket::local_port, LS_MODE_TCP_ACCEPT_FROM, link_socket_info::lsa, link_socket::mark, link_socket::mode, link_socket::mtu_discover_type, http_proxy_info::options, link_socket_info::plugins, socks_proxy_info::port, http_proxy_options::port, link_socket_info::proto, PROTO_TCP_CLIENT, PROTO_TCP_SERVER, link_socket::proxy_dest_host, link_socket::proxy_dest_port, socket_buffer_size::rcvbuf, link_socket_info::remote_float, link_socket::remote_host, link_socket::remote_port, resolve_bind_local(), resolve_remote(), link_socket::resolve_retry_seconds, link_socket::sd, socks_proxy_info::server, http_proxy_options::server, link_socket::server_poll_timeout, set_cloexec(), socket_buffer_size::sndbuf, link_socket::socket_buffer_sizes, socket_defined(), link_socket::sockflags, and link_socket::socks_proxy.
Referenced by do_init_socket_1().
link_socket_init_phase2()
void link_socket_init_phase2 (struct link_socket * sock, const struct frame * frame, struct signal_info * sig_info)
Definition at line 2261 of file socket.c.
References link_socket_addr::actual, openvpn_sockaddr::addr, addr_family_name(), link_socket_info::af, ASSERT, link_socket_addr::bind_local, link_socket::bind_local, create_socket(), link_socket_addr::current_remote, link_socket_actual::dest, link_socket::inetd, link_socket::info, linksock_print_addr(), link_socket_info::lsa, M_WARN, msg, phase2_inetd(), phase2_set_socket_flags(), phase2_socks_client(), phase2_tcp_client(), phase2_tcp_server(), link_socket_info::proto, PROTO_TCP_CLIENT, PROTO_TCP_SERVER, PROTO_UDP, link_socket::remote_host, resolve_remote(), link_socket::resolve_retry_seconds, openvpn_sockaddr::sa, link_socket::sd, signal_info::signal_received, SIGUSR1, socket_frame_init(), SOCKET_UNDEFINED, and link_socket::socks_proxy.
Referenced by do_init_socket_2().
link_socket_new()
struct link_socket* link_socket_new (void)
Definition at line 1868 of file socket.c.
References ALLOC_OBJ_CLEAR, link_socket::ctrl_sd, link_socket::sd, and SOCKET_UNDEFINED.
Referenced by do_link_socket_new().
link_socket_proto_connection_oriented()
static bool link_socket_proto_connection_oriented (int proto) inline static
Definition at line 615 of file socket.h.
References proto_is_dgram().
Referenced by addr_match_proto(), addrlist_match_proto(), do_init_crypto_tls(), link_socket_connection_oriented(), and socket_adjust_frame_parameters().
link_socket_read()
static int link_socket_read (struct link_socket * sock, struct buffer * buf, struct link_socket_actual * from) inline static
Definition at line 1050 of file socket.h.
References link_socket_addr::actual, addr_copy_sa(), ASSERT, link_socket_actual::dest, link_socket::info, link_socket_read_tcp(), link_socket_read_udp_win32(), link_socket_info::lsa, link_socket_info::proto, proto_is_tcp(), and proto_is_udp().
Referenced by read_incoming_link().
link_socket_read_tcp()
int link_socket_read_tcp (struct link_socket * sock, struct buffer * buf)
Definition at line 3355 of file socket.c.
References BLEN, BPTR, buffer::len, MSG_NOSIGNAL, link_socket::reads, stream_buf::residual_fully_formed, link_socket::sd, socket_finalize(), link_socket::stream_buf, stream_buf_added(), stream_buf_get_final(), stream_buf_get_next(), stream_buf_reset(), and link_socket::stream_reset.
Referenced by link_socket_read().
link_socket_read_udp_win32()
static int link_socket_read_udp_win32 (struct link_socket * sock, struct buffer * buf, struct link_socket_actual * from) inline static
Definition at line 1033 of file socket.h.
References link_socket::reads, link_socket::sd, and socket_finalize().
Referenced by link_socket_read().
link_socket_set_outgoing_addr()
static void link_socket_set_outgoing_addr (struct link_socket_info * info, const struct link_socket_actual * act, const char * common_name, struct env_set * es) inline static
Definition at line 986 of file socket.h.
References link_socket_addr::actual, addr_match_proto(), addrlist_match_proto(), link_socket_info::connection_established, link_socket_actual::dest, link_socket_connection_initiated(), link_socket_info::lsa, link_socket_info::proto, link_socket_info::remote_float, and link_socket_addr::remote_list.
Referenced by process_incoming_link_part2(), and tls_process().
link_socket_update_buffer_sizes()
void link_socket_update_buffer_sizes (struct link_socket * ls, int rcvbuf, int sndbuf)
Definition at line 994 of file socket.c.
References socket_buffer_size::rcvbuf, link_socket::sd, socket_buffer_size::sndbuf, link_socket::socket_buffer_sizes, socket_defined(), and socket_set_buffers().
Referenced by do_deferred_options().
link_socket_update_flags()
bool link_socket_update_flags (struct link_socket * ls, unsigned int sockflags)
Definition at line 981 of file socket.c.
References link_socket::sd, socket_defined(), socket_set_flags(), and link_socket::sockflags.
Referenced by do_deferred_options().
link_socket_verify_incoming_addr()
static bool link_socket_verify_incoming_addr (struct buffer * buf, const struct link_socket_info * info, const struct link_socket_actual * from_addr) inline static
Definition at line 937 of file socket.h.
References openvpn_sockaddr::addr, addrlist_match_proto(), link_socket_actual::dest, buffer::len, link_socket_actual_defined(), link_socket_info::lsa, link_socket_info::proto, link_socket_info::remote_float, link_socket_addr::remote_list, and openvpn_sockaddr::sa.
Referenced by process_incoming_link_part1().
link_socket_write()
static int link_socket_write (struct link_socket * sock, struct buffer * buf, struct link_socket_actual * to) inline static
Definition at line 1164 of file socket.h.
References ASSERT, link_socket::info, link_socket_write_tcp(), link_socket_write_udp(), link_socket_info::proto, proto_is_tcp(), and proto_is_udp().
Referenced by process_outgoing_link().
link_socket_write_tcp()
int link_socket_write_tcp (struct link_socket * sock, struct buffer * buf, struct link_socket_actual * to)
Definition at line 3509 of file socket.c.
References ASSERT, BLEN, buf_write_prepend(), D_STREAM_DEBUG, dmsg, htonps, link_socket_write_win32(), stream_buf::maxlen, and buffer::offset.
Referenced by link_socket_write().
link_socket_write_udp()
static size_t link_socket_write_udp (struct link_socket * sock, struct buffer * buf, struct link_socket_actual * to) inline static
Definition at line 1151 of file socket.h.
References link_socket_write_win32().
Referenced by link_socket_write().
link_socket_write_win32()
static int link_socket_write_win32 (struct link_socket * sock, struct buffer * buf, struct link_socket_actual * to) inline static
Definition at line 1089 of file socket.h.
References BLEN, overlapped_io_active(), link_socket::sd, socket_finalize(), socket_send_queue(), status, and link_socket::writes.
Referenced by link_socket_write_tcp(), and link_socket_write_udp().
mac_addr_safe()
bool mac_addr_safe (const char * mac_addr)
Definition at line 802 of file socket.c.
Referenced by add_option().
openvpn_connect()
int openvpn_connect (socket_descriptor_t sd, const struct sockaddr * remote, int connect_timeout, volatile int * signal_received)
Definition at line 1451 of file socket.c.
References af_addr_size(), get_signal(), management_sleep(), openvpn_errno, openvpn_fd_set(), set_nonblock(), and status.
Referenced by man_connect(), and socket_connect().
openvpn_getaddrinfo()
int openvpn_getaddrinfo (unsigned int flags, const char * hostname, const char * servname, int resolve_retry_seconds, volatile int * signal_received, int ai_family, struct addrinfo ** res)
Definition at line 442 of file socket.c.
References ASSERT, CLEAR, D_RESOLVE_ERRORS, D_SOCKET_DEBUG, dmsg, gc_free(), gc_new(), get_signal(), GETADDR_DATAGRAM, GETADDR_FATAL, GETADDR_FATAL_ON_SIGNAL, GETADDR_HOST_ORDER, GETADDR_MENTION_RESOLVE_RETRY, GETADDR_MSG_VIRT_OUT, GETADDR_PASSIVE, GETADDR_RANDOMIZE, GETADDR_RESOLVE, GETADDR_TRY_ONCE, GETADDR_UPDATE_MANAGEMENT_STATE, GETADDR_WARN_ON_SIGNAL, hostname_randomize(), M_FATAL, M_MSG_VIRT_OUT, M_WARN, management_set_state(), management_sleep(), msg, OPENVPN_STATE_RESOLVE, SIGUSR1, and status.
Referenced by do_preresolve_host(), get_addr_generic(), init_route(), man_settings_init(), management_post_tunnel_open(), resolve_bind_local(), resolve_remote(), and socket_listen_accept().
openvpn_inet_aton()
int openvpn_inet_aton (const char * dotted_quad, struct in_addr * addr)
Definition at line 675 of file socket.c.
References CC_DIGIT, CC_DOT, CLEAR, OIA_ERROR, OIA_HOSTNAME, OIA_IP, and string_class().
Referenced by ip_addr_dotted_quad_safe().
print_in6_addr()
const char* print_in6_addr (struct in6_addr addr6, unsigned int flags, struct gc_arena * gc)
Definition at line 3021 of file socket.c.
References alloc_buf_gc(), BSTR, buf_printf(), IA_EMPTY_IF_UNDEF, and inet_ntop().
Referenced by add_route_ipv6(), delete_route_ipv6(), do_address_service(), do_ifconfig_ipv6(), do_ifconfig_setenv(), get_default_gateway_ipv6(), helper_client_server(), ifconfig_pool_init(), ifconfig_pool_list(), init_route_ipv6_list(), log_entry_print(), mroute_addr_print_ex(), mroute_extract_addr_ip(), multi_add_iroutes(), multi_client_connect_late_setup(), multi_print_status(), multi_select_virtual_addr(), netsh_delete_address_dns(), netsh_set_dns6_servers(), prepare_push_reply(), print_default_gateway(), setenv_route_ipv6(), and show_p2mp_parms().
print_in_addr_t()
const char* print_in_addr_t (in_addr_t addr, unsigned int flags, struct gc_arena * gc)
Definition at line 3001 of file socket.c.
References alloc_buf_gc(), BSTR, buf_printf(), CLEAR, IA_EMPTY_IF_UNDEF, and IA_NET_ORDER.
Referenced by adapter_index_of_ip(), add_route(), add_route_ipapi(), check_addr_clash(), check_subnet_conflict(), delete_route(), dhcp_extract_router_msg(), dhcp_masq_addr(), do_address_service(), do_close_tun(), do_ifconfig_ipv4(), do_ifconfig_setenv(), do_open_tun(), format_route_entry(), get_default_gateway_row(), helper_add_route(), helper_client_server(), ifconfig_options_string(), ifconfig_pool_init(), ifconfig_pool_list(), ifconfig_pool_verify_range(), ifconfig_sanity_check(), ip_addr_string_to_array(), log_entry_print(), man_kill(), man_record_peer_info(), mroute_addr_print_ex(), multi_add_iroutes(), multi_client_connect_late_setup(), multi_print_status(), multi_select_virtual_addr(), netsh_delete_address_dns(), netsh_ifconfig(), netsh_ifconfig_options(), prepare_push_reply(), print_client_nat_list(), print_default_gateway(), print_netmask(), print_opt_route(), print_opt_route_gateway(), print_pkt(), route_string(), setenv_route_addr(), show_dhcp_option_addrs(), show_p2mp_parms(), tuntap_dhcp_mask(), tuntap_set_ip_addr(), tuntap_set_ptp(), verify_255_255_255_252(), verify_common_subnet(), and windows_route_find_if_index().
print_link_socket_actual()
const char* print_link_socket_actual (const struct link_socket_actual * act, struct gc_arena * gc)
Definition at line 2921 of file socket.c.
References print_link_socket_actual_ex(), PS_SHOW_PKTINFO, and PS_SHOW_PORT.
Referenced by drop_if_recursive_routing(), handle_data_channel_packet(), link_socket_bad_incoming_addr(), link_socket_connection_initiated(), multi_process_float(), process_incoming_link_part1(), process_outgoing_link(), read_control_auth(), resolve_remote(), socket_listen_accept(), tcp_connection_established(), tls_multi_process(), tls_pre_decrypt(), tls_pre_decrypt_lite(), and tls_update_remote_addr().
print_link_socket_actual_ex()
const char* print_link_socket_actual_ex (const struct link_socket_actual * act, const char * separator, const unsigned int flags, struct gc_arena * gc)
Definition at line 2931 of file socket.c.
References openvpn_sockaddr::addr, addr_defined_ipi(), alloc_buf_gc(), BSTR, buf_printf(), CLEAR, link_socket_actual::dest, IF_NAMESIZE, print_sockaddr_ex(), PS_SHOW_PKTINFO, and openvpn_sockaddr::sa.
Referenced by linksock_print_addr(), and print_link_socket_actual().
print_openvpn_sockaddr()
static const char* print_openvpn_sockaddr (const struct openvpn_sockaddr * addr, struct gc_arena * gc) inline static
Definition at line 372 of file socket.h.
References openvpn_sockaddr::addr, print_sockaddr_ex(), PS_SHOW_PORT, and openvpn_sockaddr::sa.
Referenced by recv_socks_reply().
print_openvpn_sockaddr_ex()
static const char* print_openvpn_sockaddr_ex (const struct openvpn_sockaddr * addr, const char * separator, const unsigned int flags, struct gc_arena * gc) inline static
Definition at line 362 of file socket.h.
References openvpn_sockaddr::addr, print_sockaddr_ex(), and openvpn_sockaddr::sa.
print_sockaddr()
static const char* print_sockaddr (const struct sockaddr * addr, struct gc_arena * gc) inline static
Definition at line 380 of file socket.h.
References print_sockaddr_ex(), and PS_SHOW_PORT.
Referenced by linksock_print_addr(), man_connect(), man_listen(), man_new_connection_post(), socket_connect(), and socket_do_listen().
print_sockaddr_ex()
const char* print_sockaddr_ex (const struct sockaddr * addr, const char * separator, const unsigned int flags, struct gc_arena * gc)
Definition at line 2840 of file socket.c.
References alloc_buf_gc(), ASSERT, BSTR, buf_printf(), buf_puts(), PS_DONT_SHOW_ADDR, PS_DONT_SHOW_FAMILY, PS_SHOW_PORT, PS_SHOW_PORT_IF_DEFINED, and status.
Referenced by ipchange_fmt(), link_socket_bad_incoming_addr(), log_entry_print(), print_link_socket_actual_ex(), print_openvpn_sockaddr(), print_openvpn_sockaddr_ex(), print_sockaddr(), and socket_bind().
proto2ascii()
const char* proto2ascii (int proto, sa_family_t af, bool display_form)
Definition at line 3252 of file socket.c.
References proto_names::display_form, proto_names::proto, proto_names::proto_af, proto_names::short_form, and SIZE.
Referenced by ce_management_query_remote(), linksock_print_addr(), phase2_inetd(), process_incoming_link_part1(), process_outgoing_link(), setenv_connection_entry(), show_connection_entry(), and x_check_status().
proto2ascii_all()
const char* proto2ascii_all (struct gc_arena * gc)
Definition at line 3274 of file socket.c.
References alloc_buf_gc(), BSTR, buf_printf(), and SIZE.
Referenced by add_option().
proto_is_dgram()
bool proto_is_dgram (int proto)
Definition at line 3198 of file socket.c.
References proto_names::proto, and proto_is_udp().
Referenced by do_preresolve(), inherit_context_child(), inherit_context_top(), link_socket_proto_connection_oriented(), multi_process_signal(), options_postprocess_verify_ce(), process_received_occ_msg(), resolve_bind_local(), resolve_remote(), tunnel_server(), and update_options_ce_post().
proto_is_net()
bool proto_is_net (int proto)
Definition at line 3188 of file socket.c.
References ASSERT, proto_names::proto, PROTO_N, and PROTO_NONE.
Referenced by options_postprocess_verify_ce().
proto_is_tcp()
bool proto_is_tcp (int proto)
Definition at line 3214 of file socket.c.
References ASSERT, proto_names::proto, PROTO_N, PROTO_TCP_CLIENT, and PROTO_TCP_SERVER.
Referenced by link_socket_read(), link_socket_write(), socket_recv_queue(), and socket_send_queue().
proto_is_udp()
bool proto_is_udp (int proto)
Definition at line 3204 of file socket.c.
References ASSERT, proto_names::proto, PROTO_N, and PROTO_UDP.
Referenced by ce_management_query_proxy(), do_deferred_options(), do_setup_fast_io(), link_socket_read(), link_socket_write(), options_postprocess_mutate_ce(), options_postprocess_verify_ce(), proto_is_dgram(), socket_recv_queue(), and socket_send_queue().
proto_remote()
const char* proto_remote (int proto, bool remote)
Definition at line 3315 of file socket.c.
References ASSERT, PROTO_N, PROTO_TCP_CLIENT, PROTO_TCP_SERVER, and PROTO_UDP.
Referenced by options_string().
sd_close()
void sd_close (socket_descriptor_t * sd)
Definition at line 3998 of file socket.c.
References openvpn_close_socket, socket_defined(), and SOCKET_UNDEFINED.
Referenced by man_accept(), and man_connect().
set_actual_address()
void set_actual_address (struct link_socket_actual * actual, struct addrinfo * ai)
Definition at line 1555 of file socket.c.
References openvpn_sockaddr::addr, ASSERT, CLEAR, link_socket_actual::dest, openvpn_sockaddr::in4, and openvpn_sockaddr::in6.
Referenced by resolve_remote().
setenv_in6_addr()
void setenv_in6_addr (struct env_set * es, const char * name_prefix, const struct in6_addr * addr, const unsigned int flags)
Definition at line 3132 of file socket.c.
References openvpn_sockaddr::addr, CLEAR, openvpn_sockaddr::in6, SA_SET_IF_NONZERO, and setenv_sockaddr().
Referenced by multi_set_virtual_addr_env().
setenv_in_addr_t()
void setenv_in_addr_t (struct env_set * es, const char * name_prefix, in_addr_t addr, const unsigned int flags)
Definition at line 3119 of file socket.c.
References openvpn_sockaddr::addr, CLEAR, openvpn_sockaddr::in4, SA_SET_IF_NONZERO, and setenv_sockaddr().
Referenced by multi_set_virtual_addr_env().
setenv_link_socket_actual()
void setenv_link_socket_actual (struct env_set * es, const char * name_prefix, const struct link_socket_actual * act, const unsigned int flags)
Definition at line 3148 of file socket.c.
References link_socket_actual::dest, and setenv_sockaddr().
Referenced by setenv_trusted(), and setenv_untrusted().
setenv_sockaddr()
void setenv_sockaddr (struct env_set * es, const char * name_prefix, const struct openvpn_sockaddr * addr, const unsigned int flags)
Definition at line 3066 of file socket.c.
References openvpn_sockaddr::addr, openvpn_sockaddr::in4, openvpn_sockaddr::in6, openvpn_snprintf(), openvpn_sockaddr::sa, SA_IP_PORT, setenv_int(), and setenv_str().
Referenced by setenv_in6_addr(), setenv_in_addr_t(), and setenv_link_socket_actual().
setenv_trusted()
void setenv_trusted (struct env_set * es, const struct link_socket_info * info)
Definition at line 2447 of file socket.c.
References link_socket_addr::actual, link_socket_info::lsa, SA_IP_PORT, and setenv_link_socket_actual().
Referenced by link_socket_connection_initiated(), multi_client_connect_setenv(), and multi_client_disconnect_setenv().
socket_adjust_frame_parameters()
void socket_adjust_frame_parameters (struct frame * frame, int proto)
Definition at line 2438 of file socket.c.
References frame_add_to_extra_frame(), and link_socket_proto_connection_oriented().
Referenced by do_init_crypto_tls(), and do_init_frame().
socket_bind()
void socket_bind (socket_descriptor_t sd, struct addrinfo * local, int af_family, const char * prefix, bool ipv6only)
Definition at line 1397 of file socket.c.
References addr_family_name(), ASSERT, gc_free(), gc_new(), IPV6_V6ONLY, M_ERRNO, M_FATAL, M_INFO, M_NONFATAL, msg, print_sockaddr_ex(), and PS_SHOW_PORT.
Referenced by bind_local(), and man_listen().
socket_connection_reset()
static bool socket_connection_reset (const struct link_socket * sock, int status) inline static
Definition at line 915 of file socket.h.
References stream_buf::error, link_socket_connection_oriented(), openvpn_errno, status, link_socket::stream_buf, and link_socket::stream_reset.
Referenced by read_incoming_link().
socket_do_accept()
socket_descriptor_t socket_do_accept (socket_descriptor_t sd, struct link_socket_actual * act, const bool nowait)
Definition at line 1216 of file socket.c.
References openvpn_sockaddr::addr, af_addr_size(), CLEAR, D_LINK_ERRORS, link_socket_actual::dest, M_ERRNO, M_WARN, msg, openvpn_close_socket, openvpn_sockaddr::sa, set_cloexec(), socket_defined(), and SOCKET_UNDEFINED.
Referenced by man_accept(), phase2_tcp_server(), and socket_listen_accept().
socket_event_handle()
static event_t socket_event_handle (const struct link_socket * s) inline static
Definition at line 1225 of file socket.h.
References link_socket::rw_handle, and link_socket::sd.
Referenced by multi_tcp_dereference_instance(), and socket_set().
socket_finalize()
int socket_finalize (SOCKET s, struct overlapped_io * io, struct buffer * buf, struct link_socket_actual * from)
Definition at line 3829 of file socket.c.
References openvpn_sockaddr::addr, overlapped_io::addr, overlapped_io::addr6, overlapped_io::addr_defined, overlapped_io::addrlen, af_addr_size(), ASSERT, bad_address_length(), overlapped_io::buf, CLEAR, D_WIN32_IO, link_socket_actual::dest, dmsg, overlapped_io::flags, openvpn_sockaddr::in4, openvpn_sockaddr::in6, overlapped_io::iostate, IOSTATE_IMMEDIATE_RETURN, IOSTATE_INITIAL, IOSTATE_QUEUED, buffer::len, M_ERRNO, msg, overlapped_io::overlapped, overlapped_io::size, status, and overlapped_io::status.
Referenced by link_socket_read_tcp(), link_socket_read_udp_win32(), and link_socket_write_win32().
socket_listen_event_handle()
event_t socket_listen_event_handle (struct link_socket * s)
Definition at line 2822 of file socket.c.
References defined_net_event_win32(), init_net_event_win32(), link_socket::listen_handle, and link_socket::sd.
Referenced by socket_set_listen_persistent().
socket_read_residual()
static bool socket_read_residual (const struct link_socket * s) inline static
Definition at line 1219 of file socket.h.
References stream_buf::residual_fully_formed, and link_socket::stream_buf.
Referenced by io_wait_dowork(), and multi_tcp_post().
socket_recv_queue()
int socket_recv_queue (struct link_socket * sock, int maxsize)
Definition at line 3611 of file socket.c.
References overlapped_io::addr, overlapped_io::addr6, overlapped_io::addr_defined, overlapped_io::addrlen, link_socket_info::af, af_addr_size(), ASSERT, bad_address_length(), BLEN, BPTR, overlapped_io::buf, overlapped_io::buf_init, D_WIN32_IO, dmsg, overlapped_io::flags, gc_free(), gc_new(), link_socket::info, overlapped_io::iostate, IOSTATE_IMMEDIATE_RETURN, IOSTATE_INITIAL, IOSTATE_QUEUED, overlapped_io::overlapped, link_socket_info::proto, proto_is_tcp(), proto_is_udp(), link_socket::reads, link_socket::sd, overlapped_io::size, status, overlapped_io::status, link_socket::stream_buf, stream_buf_get_next(), and strerror_win32().
Referenced by socket_set().
socket_reset_listen_persistent()
static void socket_reset_listen_persistent (struct link_socket * s) inline static
Definition at line 1256 of file socket.h.
References link_socket::listen_handle, reset_net_event_win32(), and link_socket::sd.
Referenced by multi_tcp_process_io().
socket_send_queue()
int socket_send_queue (struct link_socket * sock, struct buffer * buf, const struct link_socket_actual * to)
Definition at line 3721 of file socket.c.
References openvpn_sockaddr::addr, overlapped_io::addr, overlapped_io::addr6, overlapped_io::addr_defined, overlapped_io::addrlen, ASSERT, BLEN, BPTR, overlapped_io::buf, buf_copy(), overlapped_io::buf_init, D_WIN32_IO, link_socket_actual::dest, dmsg, overlapped_io::flags, gc_free(), gc_new(), openvpn_sockaddr::in4, openvpn_sockaddr::in6, link_socket::info, overlapped_io::iostate, IOSTATE_IMMEDIATE_RETURN, IOSTATE_INITIAL, IOSTATE_QUEUED, buffer::len, overlapped_io::overlapped, link_socket_info::proto, proto_is_tcp(), proto_is_udp(), openvpn_sockaddr::sa, link_socket::sd, overlapped_io::size, status, overlapped_io::status, strerror_win32(), and link_socket::writes.
Referenced by link_socket_write_win32().
socket_set()
unsigned int socket_set (struct link_socket * s, struct event_set * es, unsigned int rwflags, void * arg, unsigned int * persistent)
Definition at line 3961 of file socket.c.
References ASSERT, event_ctl(), EVENT_READ, link_socket::rwflags_debug, socket_event_handle(), socket_recv_queue(), and stream_buf_read_setup().
Referenced by io_wait_dowork(), and multi_tcp_set_global_rw_flags().
socket_set_listen_persistent()
static void socket_set_listen_persistent (struct link_socket * s, struct event_set * es, void * arg) inline static
Definition at line 1244 of file socket.h.
References event_ctl(), EVENT_READ, link_socket::listen_persistent_queued, and socket_listen_event_handle().
Referenced by multi_tcp_wait().
socket_stat()
const char* socket_stat (const struct link_socket * s, unsigned int rwflags, struct gc_arena * gc)
Definition at line 2623 of file socket.c.
References alloc_buf_gc(), BSTR, buf_printf(), EVENT_READ, EVENT_WRITE, overlapped_io_state_ascii(), link_socket::reads, link_socket::rwflags_debug, and link_socket::writes.
stream_buf_read_setup()
static bool stream_buf_read_setup (struct link_socket * sock) inline static
Definition at line 1011 of file socket.h.
References link_socket_connection_oriented(), and stream_buf_read_setup_dowork().
Referenced by multi_tcp_dispatch(), and socket_set().
stream_buf_read_setup_dowork()
bool stream_buf_read_setup_dowork (struct link_socket * sock)
Definition at line 2724 of file socket.c.
References ASSERT, stream_buf::buf, buf_copy(), buf_init, D_STREAM_DEBUG, dmsg, buffer::len, stream_buf::residual, stream_buf::residual_fully_formed, link_socket::stream_buf, stream_buf_added(), and stream_buf_set_next().
Referenced by stream_buf_read_setup().
Variable Documentation
proto_overhead
const int proto_overhead[]
Definition at line 47 of file socket.c.
Referenced by datagram_overhead().