OpenVPN: src/openvpn/socks.h File Reference
socks.h File Reference
#include "buffer.h"
Data Structures
struct socks_proxy_info
Functions
void socks_adjust_frame_parameters (struct frame *frame, int proto)
struct socks_proxy_info * socks_proxy_new (const char *server, const char *port, const char *authfile)
void socks_proxy_close (struct socks_proxy_info *sp)
void establish_socks_proxy_passthru (struct socks_proxy_info *p, socket_descriptor_t sd, const char *host, const char *servname, volatile int *signal_received)
void establish_socks_proxy_udpassoc (struct socks_proxy_info *p, socket_descriptor_t ctrl_sd, socket_descriptor_t udp_sd, struct openvpn_sockaddr *relay_addr, volatile int *signal_received)
void socks_process_incoming_udp (struct buffer *buf, struct link_socket_actual *from)
int socks_process_outgoing_udp (struct buffer *buf, const struct link_socket_actual *to)
Function Documentation
establish_socks_proxy_passthru()
void establish_socks_proxy_passthru (struct socks_proxy_info * p, socket_descriptor_t sd, const char * host, const char * servname, volatile int * signal_received)
Definition at line 451 of file socks.c.
References D_LINK_ERRORS, M_ERRNO, msg, MSG_NOSIGNAL, port_from_servname(), recv_socks_reply(), SIGUSR1, socks_handshake(), and ssize_t.
Referenced by phase2_tcp_client().
establish_socks_proxy_udpassoc()
void establish_socks_proxy_udpassoc (struct socks_proxy_info * p, socket_descriptor_t ctrl_sd, socket_descriptor_t udp_sd, struct openvpn_sockaddr * relay_addr, volatile int * signal_received)
Definition at line 514 of file socks.c.
References CLEAR, D_LINK_ERRORS, M_ERRNO, msg, MSG_NOSIGNAL, recv_socks_reply(), SIGUSR1, socks_handshake(), and ssize_t.
Referenced by phase2_socks_client().
socks_adjust_frame_parameters()
void socks_adjust_frame_parameters (struct frame * frame, int proto)
Definition at line 53 of file socks.c.
References frame_add_to_extra_link(), and PROTO_UDP.
Referenced by do_init_frame().
socks_process_incoming_udp()
void socks_process_incoming_udp (struct buffer * buf, struct link_socket_actual * from)
Definition at line 563 of file socks.c.
References openvpn_sockaddr::addr, BLEN, buf_read(), buf_read_u16(), buf_read_u8(), link_socket_actual::dest, openvpn_sockaddr::in4, and buffer::len.
Referenced by socks_postprocess_incoming_link().
socks_process_outgoing_udp()
int socks_process_outgoing_udp (struct buffer * buf, const struct link_socket_actual * to)
Definition at line 602 of file socks.c.
References openvpn_sockaddr::addr, ASSERT, buf_defined(), buf_sub(), buf_write(), buf_write_u16(), buf_write_u8(), link_socket_actual::dest, and openvpn_sockaddr::in4.
Referenced by socks_preprocess_outgoing_link().
socks_proxy_close()
void socks_proxy_close (struct socks_proxy_info * sp)
Definition at line 91 of file socks.c.
Referenced by uninit_proxy_dowork().
socks_proxy_new()
struct socks_proxy_info* socks_proxy_new (const char * server, const char * port, const char * authfile)
Definition at line 62 of file socks.c.
References ALLOC_OBJ_CLEAR, ASSERT, socks_proxy_info::authfile, socks_proxy_info::defined, socks_proxy_info::port, socks_proxy_info::server, and strncpynt().
Referenced by init_proxy_dowork().