OpenVPN: src/openvpn/ssl.c File Reference
ssl.c File Reference
#include "syshead.h"
#include "win32.h"
#include "error.h"
#include "common.h"
#include "socket.h"
#include "misc.h"
#include "fdmisc.h"
#include "interval.h"
#include "perf.h"
#include "status.h"
#include "gremlin.h"
#include "pkcs11.h"
#include "route.h"
#include "tls_crypt.h"
#include "ssl.h"
#include "ssl_verify.h"
#include "ssl_backend.h"
#include "ssl_ncp.h"
#include "auth_token.h"
#include "memdbg.h"
Macros
#define INCR_SENT
#define INCR_GENERATED
#define INCR_SUCCESS
#define INCR_ERROR
#define SWAP_BUF_SIZE 256
#define FULL_SYNC (reliable_empty(ks->send_reliable) && reliable_ack_empty(ks->rec_ack))
Functions
void print_bio_data (char *data, int len)
static void key_ctx_update_implicit_iv (struct key_ctx *ctx, uint8_t *key, size_t key_len)
Update the implicit IV for a key_ctx_bi based on TLS session ids and cipher used.
const tls_cipher_name_pair * tls_get_cipher_name_pair (const char *cipher_name, size_t len)
static void tls_limit_reneg_bytes (const cipher_kt_t *cipher, int *reneg_bytes)
Limit the reneg_bytes value when using a small-block (<128 bytes) cipher.
void tls_adjust_frame_parameters (struct frame *frame)
static void tls_init_control_channel_frame_parameters (const struct frame *data_channel_frame, struct frame *frame)
void init_ssl_lib (void)
void free_ssl_lib (void)
void pem_password_setup (const char *auth_file)
int pem_password_callback (char *buf, int size, int rwflag, void *u)
Callback to retrieve the user's password.
void enable_auth_user_pass ()
void auth_user_pass_setup (const char *auth_file, const struct static_challenge_info *sci)
void ssl_set_auth_nocache (void)
void ssl_set_auth_token (const char *token)
void ssl_set_auth_token_user (const char *username)
bool ssl_clean_auth_token (void)
void ssl_purge_auth (const bool auth_user_pass_only)
void ssl_purge_auth_challenge (void)
void ssl_put_auth_challenge (const char *cr_str)
int tls_version_parse (const char *vstr, const char *extra)
static void tls_ctx_reload_crl (struct tls_root_ctx *ssl_ctx, const char *crl_file, bool crl_file_inline)
Load (or possibly reload) the CRL file into the SSL context.
void init_ssl (const struct options *options, struct tls_root_ctx *new_ctx, bool in_chroot)
Build master SSL context object that serves for the whole of OpenVPN instantiation.
static const char * state_name (int state)
static const char * packet_opcode_name (int op)
static const char * session_index_name (int index)
static const char * print_key_id (struct tls_multi *multi, struct gc_arena *gc)
bool is_hard_reset_method2 (int op)
Given a key_method, return true if opcode represents the one of the hard_reset op codes for key-method 2.
static bool tls_session_user_pass_enabled (struct tls_session *session)
Returns whether or not the server should check for username/password.
static void move_session (struct tls_multi *multi, int dest, int src, bool reinit_src)
static void reset_session (struct tls_multi *multi, struct tls_session *session)
static void compute_earliest_wakeup (interval_t *earliest, interval_t seconds_from_now)
static bool lame_duck_must_die (const struct tls_session *session, interval_t *wakeup)
struct tls_multi * tls_multi_init (struct tls_options *tls_options)
Allocate and initialize a tls_multi structure.
void tls_multi_init_finalize (struct tls_multi *multi, const struct frame *frame)
Finalize initialization of a tls_multi structure.
struct tls_auth_standalone * tls_auth_standalone_init (struct tls_options *tls_options, struct gc_arena *gc)
void tls_auth_standalone_finalize (struct tls_auth_standalone *tas, const struct frame *frame)
void tls_multi_init_set_options (struct tls_multi *multi, const char *local, const char *remote)
void tls_multi_free (struct tls_multi *multi, bool clear)
Cleanup a tls_multi structure and free associated memory allocations.
static bool swap_hmac (struct buffer *buf, const struct crypto_options *co, bool incoming)
static void write_control_auth (struct tls_session *session, struct key_state *ks, struct buffer *buf, struct link_socket_actual **to_link_addr, int opcode, int max_ack, bool prepend_ack)
static bool read_control_auth (struct buffer *buf, struct tls_wrap_ctx *ctx, const struct link_socket_actual *from, const struct tls_options *opt)
static void key_source_print (const struct key_source *k, const char *prefix)
static void key_source2_print (const struct key_source2 *k)
static void tls1_P_hash (const md_kt_t *md_kt, const uint8_t *sec, int sec_len, const uint8_t *seed, int seed_len, uint8_t *out, int olen)
static void tls1_PRF (const uint8_t *label, int label_len, const uint8_t *sec, int slen, uint8_t *out1, int olen)
static void openvpn_PRF (const uint8_t *secret, int secret_len, const char *label, const uint8_t *client_seed, int client_seed_len, const uint8_t *server_seed, int server_seed_len, const struct session_id *client_sid, const struct session_id *server_sid, uint8_t *output, int output_len)
static bool generate_key_expansion (struct key_ctx_bi *key, const struct key_type *key_type, const struct key_source2 *key_src, const struct session_id *client_sid, const struct session_id *server_sid, bool server)
static bool tls_session_generate_data_channel_keys (struct tls_session *session)
Generate data channel keys for the supplied TLS session.
bool tls_session_update_crypto_params (struct tls_session *session, struct options *options, struct frame *frame, struct frame *frame_fragment)
Update TLS session crypto parameters (cipher and auth) and derive data channel keys based on the supplied options.
static bool random_bytes_to_buf (struct buffer *buf, uint8_t *out, int outlen)
static bool key_source2_randomize_write (struct key_source2 *k2, struct buffer *buf, bool server)
static int key_source2_read (struct key_source2 *k2, struct buffer *buf, bool server)
static void flush_payload_buffer (struct key_state *ks)
static void key_state_soft_reset (struct tls_session *session)
static bool write_empty_string (struct buffer *buf)
static bool write_string (struct buffer *buf, const char *str, const int maxlen)
static bool read_string (struct buffer *buf, char *str, const unsigned int capacity)
static char * read_string_alloc (struct buffer *buf)
static bool push_peer_info (struct buffer *buf, struct tls_session *session)
static bool key_method_2_write (struct buffer *buf, struct tls_multi *multi, struct tls_session *session)
Handle the writing of key data, peer-info, username/password, OCC to the TLS control channel (cleartext).
static bool key_method_2_read (struct buffer *buf, struct tls_multi *multi, struct tls_session *session)
Handle reading key data, peer-info, username/password, OCC from the TLS control channel (cleartext).
static int auth_deferred_expire_window (const struct tls_options *o)
static bool tls_process (struct tls_multi *multi, struct tls_session *session, struct buffer *to_link, struct link_socket_actual **to_link_addr, struct link_socket_info *to_link_socket_info, interval_t *wakeup)
int tls_multi_process (struct tls_multi *multi, struct buffer *to_link, struct link_socket_actual **to_link_addr, struct link_socket_info *to_link_socket_info, interval_t *wakeup)
static void handle_data_channel_packet (struct tls_multi *multi, const struct link_socket_actual *from, struct buffer *buf, struct crypto_options **opt, bool floated, const uint8_t **ad_start)
bool tls_pre_decrypt (struct tls_multi *multi, const struct link_socket_actual *from, struct buffer *buf, struct crypto_options **opt, bool floated, const uint8_t **ad_start)
Determine whether an incoming packet is a data channel or control channel packet, and process accordingly.
bool tls_pre_decrypt_lite (const struct tls_auth_standalone *tas, const struct link_socket_actual *from, const struct buffer *buf)
Inspect an incoming packet for which no VPN tunnel is active, and determine whether a new VPN tunnel should be created.
void tls_pre_encrypt (struct tls_multi *multi, struct buffer *buf, struct crypto_options **opt)
Choose the appropriate security parameters with which to process an outgoing packet.
void tls_prepend_opcode_v1 (const struct tls_multi *multi, struct buffer *buf)
Prepend a one-byte OpenVPN data channel P_DATA_V1 opcode to the packet.
void tls_prepend_opcode_v2 (const struct tls_multi *multi, struct buffer *buf)
Prepend an OpenVPN data channel P_DATA_V2 header to the packet.
void tls_post_encrypt (struct tls_multi *multi, struct buffer *buf)
Perform some accounting for the key state used.
bool tls_send_payload (struct tls_multi *multi, const uint8_t *data, int size)
bool tls_rec_payload (struct tls_multi *multi, struct buffer *buf)
void tls_update_remote_addr (struct tls_multi *multi, const struct link_socket_actual *addr)
Updates remote address in TLS sessions.
void show_available_tls_ciphers (const char *cipher_list, const char *cipher_list_tls13, const char *tls_cert_profile)
const char * protocol_dump (struct buffer *buffer, unsigned int flags, struct gc_arena *gc)
Functions for initialization and cleanup of key_state structures
static void key_state_init (struct tls_session *session, struct key_state *ks)
Initialize a key_state structure.
static void key_state_free (struct key_state *ks, bool clear)
Cleanup a key_state structure.
Functions for initialization and cleanup of tls_session structures
static void tls_session_init (struct tls_multi *multi, struct tls_session *session)
Initialize a tls_session structure.
static void tls_session_free (struct tls_session *session, bool clear)
Clean up a tls_session structure.
Variables
static const tls_cipher_name_pair tls_cipher_name_translation_table []
SSL/TLS Cipher suite name translation table.
static struct user_pass passbuf
static bool auth_user_pass_enabled
static struct user_pass auth_user_pass
static struct user_pass auth_token
static char * auth_challenge
Macro Definition Documentation
FULL_SYNC
#define FULL_SYNC (reliable_empty(ks->send_reliable) && reliable_ack_empty(ks->rec_ack))
Definition at line 2121 of file ssl.c.
INCR_ERROR
#define INCR_ERROR
Definition at line 94 of file ssl.c.
INCR_GENERATED
#define INCR_GENERATED
Definition at line 92 of file ssl.c.
INCR_SENT
#define INCR_SENT
Definition at line 91 of file ssl.c.
INCR_SUCCESS
#define INCR_SUCCESS
Definition at line 93 of file ssl.c.
SWAP_BUF_SIZE
#define SWAP_BUF_SIZE 256
Definition at line 1395 of file ssl.c.
Function Documentation
auth_deferred_expire_window()
static int auth_deferred_expire_window (const struct tls_options * o) static
Definition at line 2627 of file ssl.c.
References tls_options::handshake_window, and tls_options::renegotiate_seconds.
Referenced by tls_process().
auth_user_pass_setup()
void auth_user_pass_setup (const char * auth_file, const struct static_challenge_info * sci)
Definition at line 404 of file ssl.c.
References auth_challenge, auth_token, auth_user_pass, static_challenge_info::challenge_text, user_pass::defined, static_challenge_info::flags, get_user_pass(), get_user_pass_cr(), GET_USER_PASS_DYNAMIC_CHALLENGE, GET_USER_PASS_MANAGEMENT, GET_USER_PASS_STATIC_CHALLENGE, GET_USER_PASS_STATIC_CHALLENGE_ECHO, SC_ECHO, and UP_TYPE_AUTH.
Referenced by init_query_passwords(), and key_method_2_write().
compute_earliest_wakeup()
static void compute_earliest_wakeup (interval_t * earliest, interval_t seconds_from_now) inline static
Definition at line 1215 of file ssl.c.
Referenced by lame_duck_must_die(), and tls_process().
enable_auth_user_pass()
void enable_auth_user_pass ()
Definition at line 398 of file ssl.c.
References auth_user_pass_enabled.
Referenced by init_query_passwords().
flush_payload_buffer()
static void flush_payload_buffer (struct key_state * ks) static
Definition at line 2109 of file ssl.c.
References buffer_list_peek(), buffer_list_pop(), buffer::data, key_state_write_plaintext_const(), key_state::ks_ssl, buffer::len, and key_state::paybuf.
Referenced by tls_process().
free_ssl_lib()
void free_ssl_lib (void)
Definition at line 346 of file ssl.c.
References crypto_uninit_lib(), prng_uninit(), and tls_free_lib().
Referenced by uninit_static().
generate_key_expansion()
static bool generate_key_expansion (struct key_ctx_bi * key, const struct key_type * key_type, const struct key_source2 * key_src, const struct session_id * client_sid, const struct session_id * server_sid, bool server) static
Definition at line 1809 of file ssl.c.
References check_key(), key_source2::client, D_TLS_ERRORS, fixup_key(), key::hmac, init_key_ctx_bi(), key2_print(), key_ctx_update_implicit_iv(), KEY_DIRECTION_INVERSE, KEY_DIRECTION_NORMAL, KEY_EXPANSION_ID, key_source2_print(), key2::keys, MAX_HMAC_KEY_LENGTH, msg, key2::n, openvpn_PRF(), key_source::pre_master, key_source::random1, key_source::random2, secure_memzero(), and key_source2::server.
Referenced by tls_session_generate_data_channel_keys().
handle_data_channel_packet()
static void handle_data_channel_packet (struct tls_multi * multi, const struct link_socket_actual * from, struct buffer * buf, struct crypto_options ** opt, bool floated, const uint8_t ** ad_start) inline static
Definition at line 3189 of file ssl.c.
References ASSERT, key_state::authenticated, BPTR, buf_advance(), key_state::crypto_options, D_MULTI_DROPPED, D_TLS_ERRORS, D_TLS_KEYSELECT, DECRYPT_KEY_ENABLED, dmsg, gc_free(), gc_new(), key_ctx_bi::initialized, crypto_options::key_ctx_bi, key_state::key_id, tls_multi::key_scan, KEY_SCAN_SIZE, KS_AUTH_TRUE, buffer::len, link_socket_actual_match(), msg, key_state::n_bytes, key_state::n_packets, tls_multi::n_soft_errors, P_DATA_V1, P_DATA_V2, P_KEY_ID_MASK, P_OPCODE_SHIFT, print_link_socket_actual(), key_state::remote_addr, and tls_clear_error().
Referenced by tls_pre_decrypt().
init_ssl()
void init_ssl (const struct options * options, struct tls_root_ctx * new_ctx, bool in_chroot)
Build master SSL context object that serves for the whole of OpenVPN instantiation.
Definition at line 607 of file ssl.c.
References ASSERT, BSTR, options::ca_file, options::ca_file_inline, options::ca_path, options::cert_file, options::cert_file_inline, options::chroot_dir, options::cipher_list, options::cipher_list_tls13, options::crl_file, options::crl_file_inline, options::cryptoapi_cert, options::dh_file, options::dh_file_inline, options::ecdh_curve, options::extra_certs_file, options::extra_certs_file_inline, gc_free(), gc_new(), M_WARN, options::management_certificate, options::management_flags, management_query_cert(), MF_EXTERNAL_CERT, MF_EXTERNAL_KEY, msg, options::pkcs12_file, options::pkcs12_file_inline, prepend_dir(), options::priv_key_file, options::priv_key_file_inline, options::ssl_flags, SSLF_CRL_VERIFY_DIR, options::tls_cert_profile, tls_clear_error(), tls_ctx_check_cert_time(), tls_ctx_client_new(), tls_ctx_free(), tls_ctx_load_ca(), tls_ctx_load_cert_file(), tls_ctx_load_cryptoapi(), tls_ctx_load_dh_params(), tls_ctx_load_ecdh_params(), tls_ctx_load_extra_certs(), tls_ctx_load_pkcs12(), tls_ctx_load_priv_file(), tls_ctx_reload_crl(), tls_ctx_restrict_ciphers(), tls_ctx_restrict_ciphers_tls13(), tls_ctx_server_new(), tls_ctx_set_cert_profile(), tls_ctx_set_options(), tls_ctx_set_tls_groups(), tls_ctx_use_management_external_key(), options::tls_groups, and options::tls_server.
Referenced by do_init_crypto_tls_c1().
init_ssl_lib()
void init_ssl_lib (void)
Definition at line 338 of file ssl.c.
References crypto_init_lib(), and tls_init_lib().
Referenced by init_static().
is_hard_reset_method2()
bool is_hard_reset_method2 (int op)
Given a key_method, return true if opcode represents the one of the hard_reset op codes for key-method 2.
Definition at line 881 of file ssl.c.
References P_CONTROL_HARD_RESET_CLIENT_V2, P_CONTROL_HARD_RESET_CLIENT_V3, and P_CONTROL_HARD_RESET_SERVER_V2.
Referenced by process_incoming_link_part1(), and tls_pre_decrypt().
key_ctx_update_implicit_iv()
static void key_ctx_update_implicit_iv (struct key_ctx * ctx, uint8_t * key, size_t key_len) static
Update the implicit IV for a key_ctx_bi based on TLS session ids and cipher used.
Note that the implicit IV is based on the HMAC key, but only in AEAD modes where the HMAC key is not used for an actual HMAC.
Parameters
ctx Encrypt/decrypt key context
key HMAC key, used to calculate implicit IV
key_len HMAC key length
Definition at line 1889 of file ssl.c.
References ASSERT, key_ctx::cipher, cipher_ctx_get_cipher_kt(), cipher_kt_iv_size(), cipher_kt_mode_aead(), key_ctx::implicit_iv, key_ctx::implicit_iv_len, OPENVPN_AEAD_MIN_IV_LEN, and OPENVPN_MAX_IV_LENGTH.
Referenced by generate_key_expansion().
key_method_2_read()
static bool key_method_2_read (struct buffer * buf, struct tls_multi * multi, struct tls_session * session) static
Handle reading key data, peer-info, username/password, OCC from the TLS control channel (cleartext).
Definition at line 2455 of file ssl.c.
References ALLOC_ARRAY_CLEAR_GC, ALLOC_OBJ_CLEAR_GC, key_state::authenticated, buf_advance(), buf_clear(), buf_read_u8(), CLEAR, D_TLS_ERRORS, gc_free(), gc_new(), session::key, key_state::key_id, KEY_METHOD_MASK, key_source2_read(), key_state::key_src, key_state_export_keying_material(), KS_AUTH_FALSE, KS_AUTH_TRUE, KS_PRIMARY, key_state::ks_ssl, buffer::len, msg, OPENVPN_PLUGIN_FUNC_SUCCESS, OPENVPN_PLUGIN_TLS_FINAL, options_cmp_equal(), options_string_extract_option(), options_warning(), output_peer_info_env(), user_pass::password, tls_multi::peer_info, plugin_call(), plugin_defined(), read_string(), read_string_alloc(), tls_multi::remote_ciphername, secure_memzero(), setenv_del(), SSLF_AUTH_USER_PASS_OPTIONAL, SSLF_OPT_VERIFY, string_alloc(), TLS_OPTIONS_LEN, tls_session_generate_data_channel_keys(), tls_session_user_pass_enabled(), USER_PASS_LEN, user_pass::username, verify_final_auth_checks(), and verify_user_pass().
Referenced by tls_process().
key_method_2_write()
static bool key_method_2_write (struct buffer * buf, struct tls_multi * multi, struct tls_session * session) static
Handle the writing of key data, peer-info, username/password, OCC to the TLS control channel (cleartext).
Definition at line 2335 of file ssl.c.
References ASSERT, auth_token, auth_user_pass, auth_user_pass_enabled, auth_user_pass_setup(), key_state::authenticated, buf_init, buf_write_u32(), buf_write_u8(), CAS_SUCCEEDED, D_TLS_ERRORS, user_pass::defined, session::key, KEY_METHOD_2, key_source2_randomize_write(), key_state::key_src, KS_AUTH_FALSE, KS_PRIMARY, MODE_SERVER, msg, tls_multi::multi_state, user_pass::password, purge_user_pass(), push_peer_info(), secure_memzero(), strncpynt(), TLS_OPTIONS_LEN, tls_session_generate_data_channel_keys(), user_pass::token_defined, USER_PASS_LEN, user_pass::username, write_empty_string(), and write_string().
Referenced by tls_process().
key_source2_print()
static void key_source2_print (const struct key_source2 * k) static
Definition at line 1628 of file ssl.c.
References key_source2::client, key_source_print(), and key_source2::server.
Referenced by generate_key_expansion().
key_source2_randomize_write()
static bool key_source2_randomize_write (struct key_source2 * k2, struct buffer * buf, bool server) static
Definition at line 2042 of file ssl.c.
References CLEAR, key_source2::client, key_source::pre_master, key_source::random1, key_source::random2, random_bytes_to_buf(), and key_source2::server.
Referenced by key_method_2_write().
key_source2_read()
static int key_source2_read (struct key_source2 * k2, struct buffer * buf, bool server) static
Definition at line 2075 of file ssl.c.
References buf_read(), CLEAR, key_source2::client, key_source::pre_master, key_source::random1, key_source::random2, and key_source2::server.
Referenced by key_method_2_read().
key_source_print()
static void key_source_print (const struct key_source * k, const char * prefix) static
Definition at line 1602 of file ssl.c.
References D_SHOW_KEY_SOURCE, dmsg, format_hex(), gc_free(), gc_new(), key_source::pre_master, key_source::random1, key_source::random2, and VALGRIND_MAKE_READABLE.
Referenced by key_source2_print().
key_state_soft_reset()
static void key_state_soft_reset (struct tls_session * session) static
Definition at line 2129 of file ssl.c.
References session::key, key_state_free(), key_state_init(), KS_LAME_DUCK, KS_PRIMARY, key_state::must_die, now, key_state::remote_addr, and key_state::session_id_remote.
Referenced by tls_pre_decrypt(), and tls_process().
lame_duck_must_die()
static bool lame_duck_must_die (const struct tls_session * session, interval_t * wakeup) inline static
Definition at line 1232 of file ssl.c.
References ASSERT, compute_earliest_wakeup(), session::key, KS_LAME_DUCK, key_state::must_die, now, S_ERROR, S_INITIAL, and key_state::state.
Referenced by tls_multi_process(), and tls_process().
move_session()
static void move_session (struct tls_multi * multi, int dest, int src, bool reinit_src) static
Definition at line 1179 of file ssl.c.
References ASSERT, D_TLS_DEBUG, D_TLS_DEBUG_LOW, dest, dmsg, msg, secure_memzero(), tls_multi::session, session_index_name(), tls_session_free(), tls_session_init(), and TM_SIZE.
Referenced by tls_multi_process().
openvpn_PRF()
static void openvpn_PRF (const uint8_t * secret, int secret_len, const char * label, const uint8_t * client_seed, int client_seed_len, const uint8_t * server_seed, int server_seed_len, const struct session_id * client_sid, const struct session_id * server_sid, uint8_t * output, int output_len) static
Definition at line 1763 of file ssl.c.
References alloc_buf(), ASSERT, BLEN, BPTR, buf_clear(), buf_write(), free_buf(), session_id::id, SID_SIZE, tls1_PRF(), and VALGRIND_MAKE_READABLE.
Referenced by generate_key_expansion().
packet_opcode_name()
static const char* packet_opcode_name (int op) static
Definition at line 803 of file ssl.c.
References P_ACK_V1, P_CONTROL_HARD_RESET_CLIENT_V1, P_CONTROL_HARD_RESET_CLIENT_V2, P_CONTROL_HARD_RESET_CLIENT_V3, P_CONTROL_HARD_RESET_SERVER_V1, P_CONTROL_HARD_RESET_SERVER_V2, P_CONTROL_SOFT_RESET_V1, P_CONTROL_V1, P_DATA_V1, and P_DATA_V2.
Referenced by protocol_dump(), tls_pre_decrypt(), and write_control_auth().
pem_password_callback()
int pem_password_callback (char * buf, int size, int rwflag, void * u)
Callback to retrieve the user's password.
Parameters
buf Buffer to return the password in
size Size of the buffer
rwflag Unused, needed for OpenSSL compatibility
u Unused, needed for OpenSSL compatibility
Definition at line 371 of file ssl.c.
References passbuf, user_pass::password, pem_password_setup(), purge_user_pass(), and strncpynt().
Referenced by tls_ctx_load_pkcs12(), and tls_ctx_set_options().
pem_password_setup()
void pem_password_setup (const char * auth_file)
Definition at line 362 of file ssl.c.
References get_user_pass(), GET_USER_PASS_MANAGEMENT, GET_USER_PASS_PASSWORD_ONLY, passbuf, user_pass::password, and UP_TYPE_PRIVATE_KEY.
Referenced by init_query_passwords(), and pem_password_callback().
print_bio_data()
void print_bio_data (char * data, int len)
print_key_id()
static const char* print_key_id (struct tls_multi * multi, struct gc_arena * gc) static
Definition at line 865 of file ssl.c.
References alloc_buf_gc(), BSTR, buf_printf(), key_state::key_id, tls_multi::key_scan, KEY_SCAN_SIZE, session_id_print(), key_state::session_id_remote, key_state::state, and state_name().
Referenced by tls_pre_decrypt(), and tls_pre_encrypt().
protocol_dump()
const char* protocol_dump (struct buffer * buffer, unsigned int flags, struct gc_arena * gc)
Definition at line 4024 of file ssl.c.
References alloc_buf_gc(), ASSERT, BLEN, BPTR, BSTR, buf_printf(), buf_read(), format_hex(), buffer::len, MAX_HMAC_KEY_LENGTH, ntohpid, P_ACK_V1, P_DATA_V1, P_DATA_V2, P_KEY_ID_MASK, P_OPCODE_SHIFT, packet_id_format, packet_id_net_print(), packet_id_read(), packet_opcode_name(), PD_SHOW_DATA, PD_TLS, PD_TLS_AUTH_HMAC_SIZE_MASK, PD_VERBOSE, reliable_ack_print(), session_id_print(), and session_id_read().
push_peer_info()
static bool push_peer_info (struct buffer * buf, struct tls_session * session) static
Definition at line 2214 of file ssl.c.
References alloc_buf_gc(), BSTR, buf_printf(), buf_safe(), route_gateway_info::flags, format_hex_ex(), gc_free(), gc_new(), get_default_gateway(), get_ssl_library_version(), route_gateway_info::hwaddr, IV_PROTO_DATA_V2, IV_PROTO_REQUEST_PUSH, env_set::list, MODE_SERVER, env_item::next, PACKAGE_VERSION, RGI_HWADDR_DEFINED, tls_item_in_cipher_list(), win32_version_string(), write_empty_string(), and write_string().
Referenced by key_method_2_write(), options_postprocess_verify_ce(), and show_settings().
random_bytes_to_buf()
static bool random_bytes_to_buf (struct buffer * buf, uint8_t * out, int outlen) static
Definition at line 2026 of file ssl.c.
References buf_write(), M_FATAL, msg, and rand_bytes().
Referenced by key_source2_randomize_write().
read_control_auth()
static bool read_control_auth (struct buffer * buf, struct tls_wrap_ctx * ctx, const struct link_socket_actual * from, const struct tls_options * opt) static
Definition at line 1514 of file ssl.c.
References alloc_buf_gc(), ASSERT, BPTR, buf_advance(), buf_clear(), buf_copy(), buf_forward_capacity_total(), buf_init, key_ctx::cipher, clear_buf(), D_TLS_ERRORS, gc_free(), gc_new(), buffer::len, tls_wrap_ctx::mode, msg, buffer::offset, openvpn_decrypt(), tls_wrap_ctx::opt, P_CONTROL_HARD_RESET_CLIENT_V3, P_OPCODE_SHIFT, print_link_socket_actual(), SID_SIZE, swap_hmac(), tls_crypt_unwrap(), tls_crypt_v2_extract_client_key(), and tls_wrap_ctx::tls_crypt_v2_server_key.
Referenced by tls_pre_decrypt(), and tls_pre_decrypt_lite().
read_string()
static bool read_string (struct buffer * buf, char * str, const unsigned int capacity) static
Definition at line 2177 of file ssl.c.
References buf_read(), and buf_read_u16().
Referenced by key_method_2_read().
read_string_alloc()
static char* read_string_alloc (struct buffer * buf) static
Definition at line 2193 of file ssl.c.
References buf_read(), buf_read_u16(), and check_malloc_return().
Referenced by key_method_2_read().
reset_session()
static void reset_session (struct tls_multi * multi, struct tls_session * session) static
Definition at line 1204 of file ssl.c.
References tls_session_free(), and tls_session_init().
Referenced by tls_multi_process().
session_index_name()
static const char* session_index_name (int index) static
Definition at line 843 of file ssl.c.
References TM_ACTIVE, TM_LAME_DUCK, and TM_UNTRUSTED.
Referenced by move_session().
show_available_tls_ciphers()
void show_available_tls_ciphers (const char * cipher_list, const char * cipher_list_tls13, const char * tls_cert_profile)
Definition at line 3997 of file ssl.c.
References show_available_tls_ciphers_list(), TLS_VER_1_3, and tls_version_max().
Referenced by print_openssl_info().
ssl_clean_auth_token()
bool ssl_clean_auth_token (void)
Definition at line 465 of file ssl.c.
References auth_token, user_pass::defined, and purge_user_pass().
Referenced by man_forget_passwords(), man_reset_client_socket(), and receive_auth_failed().
ssl_purge_auth()
void ssl_purge_auth (const bool auth_user_pass_only)
Definition at line 476 of file ssl.c.
References auth_user_pass, passbuf, purge_user_pass(), and ssl_purge_auth_challenge().
Referenced by do_init_crypto_tls_c1(), man_forget_passwords(), man_reset_client_socket(), receive_auth_failed(), and server_pushed_signal().
ssl_purge_auth_challenge()
void ssl_purge_auth_challenge (void)
Definition at line 494 of file ssl.c.
References auth_challenge.
Referenced by ssl_purge_auth(), and ssl_put_auth_challenge().
ssl_put_auth_challenge()
void ssl_put_auth_challenge (const char * cr_str)
Definition at line 501 of file ssl.c.
References auth_challenge, ssl_purge_auth_challenge(), and string_alloc().
Referenced by receive_auth_failed().
ssl_set_auth_nocache()
void ssl_set_auth_nocache (void)
Definition at line 440 of file ssl.c.
References auth_user_pass, user_pass::nocache, and passbuf.
Referenced by add_option().
ssl_set_auth_token()
void ssl_set_auth_token (const char * token)
Definition at line 450 of file ssl.c.
References auth_token, auth_user_pass, and set_auth_token().
Referenced by add_option().
ssl_set_auth_token_user()
void ssl_set_auth_token_user (const char * username)
Definition at line 456 of file ssl.c.
References auth_token, set_auth_token_user(), and user_pass::username.
Referenced by add_option().
state_name()
static const char* state_name (int state) static
Definition at line 769 of file ssl.c.
References S_ACTIVE, S_ERROR, S_GOT_KEY, S_INITIAL, S_PRE_START, S_SENT_KEY, S_START, and S_UNDEF.
Referenced by print_key_id(), tls_multi_process(), tls_pre_decrypt(), and tls_process().
swap_hmac()
static bool swap_hmac (struct buffer * buf, const struct crypto_options * co, bool incoming) static
Definition at line 1398 of file ssl.c.
References ASSERT, BPTR, key_ctx_bi::decrypt, key_ctx_bi::encrypt, key_ctx::hmac, hmac_ctx_size(), crypto_options::key_ctx_bi, buffer::len, packet_id_size(), SID_SIZE, and SWAP_BUF_SIZE.
Referenced by read_control_auth(), and write_control_auth().
tls1_P_hash()
static void tls1_P_hash (const md_kt_t * md_kt, const uint8_t * sec, int sec_len, const uint8_t * seed, int seed_len, uint8_t * out, int olen) static
Definition at line 1646 of file ssl.c.
References D_SHOW_KEY_SOURCE, dmsg, format_hex(), gc_free(), gc_new(), hmac_ctx_cleanup(), hmac_ctx_final(), hmac_ctx_free(), hmac_ctx_init(), hmac_ctx_new(), hmac_ctx_reset(), hmac_ctx_update(), MAX_HMAC_KEY_LENGTH, md_kt_size(), and secure_memzero().
Referenced by tls1_PRF().
tls1_PRF()
static void tls1_PRF (const uint8_t * label, int label_len, const uint8_t * sec, int slen, uint8_t * out1, int olen) static
Definition at line 1729 of file ssl.c.
References D_SHOW_KEY_SOURCE, dmsg, format_hex(), gc_free(), gc_malloc(), gc_new(), md_kt_get(), secure_memzero(), and tls1_P_hash().
Referenced by openvpn_PRF().
tls_adjust_frame_parameters()
void tls_adjust_frame_parameters (struct frame * frame)
Definition at line 305 of file ssl.c.
References frame_add_to_extra_frame().
Referenced by do_init_crypto_tls(), and tls_init_control_channel_frame_parameters().
tls_ctx_reload_crl()
static void tls_ctx_reload_crl (struct tls_root_ctx * ssl_ctx, const char * crl_file, bool crl_file_inline) static
Load (or possibly reload) the CRL file into the SSL context.
No reload is performed under the following conditions:
the CRL file was passed inline
the CRL file was not modified since the last (re)load
Parameters
ssl_ctx The TLS context to use when reloading the CRL
crl_file The file name to load the CRL from, or "[[INLINE]]" in the case of inline files.
crl_inline A string containing the CRL
Definition at line 556 of file ssl.c.
References backend_tls_ctx_reload_crl(), tls_root_ctx::crl_last_mtime, tls_root_ctx::crl_last_size, M_FATAL, M_WARN, msg, and platform_stat().
Referenced by init_ssl(), and tls_process().
tls_get_cipher_name_pair()
const tls_cipher_name_pair* tls_get_cipher_name_pair (const char * cipher_name, size_t len)
Definition at line 259 of file ssl.c.
References tls_cipher_name_pair::iana_name, tls_cipher_name_pair::openssl_name, and tls_cipher_name_translation_table.
Referenced by convert_tls_list_to_openssl(), and show_available_tls_ciphers_list().
tls_init_control_channel_frame_parameters()
static void tls_init_control_channel_frame_parameters (const struct frame * data_channel_frame, struct frame * frame) static
Definition at line 315 of file ssl.c.
References ASSERT, CONTROL_SEND_ACK_MAX, frame::extra_link, frame_add_to_extra_frame(), frame::link_mtu, frame::link_mtu_dynamic, min_int(), reliable_ack_adjust_frame_parameters(), SID_SIZE, tls_adjust_frame_parameters(), and TUN_LINK_DELTA.
Referenced by tls_auth_standalone_finalize(), and tls_multi_init_finalize().
tls_limit_reneg_bytes()
static void tls_limit_reneg_bytes (const cipher_kt_t * cipher, int * reneg_bytes) static
Limit the reneg_bytes value when using a small-block (<128 bytes) cipher.
Parameters
cipher The current cipher (may be NULL).
reneg_bytes Pointer to the current reneg_bytes, updated if needed. May not be NULL.
Definition at line 285 of file ssl.c.
References cipher_kt_insecure(), M_WARN, and msg.
Referenced by tls_session_generate_data_channel_keys().
tls_multi_process()
int tls_multi_process (struct tls_multi * multi, struct buffer * to_link, struct link_socket_actual ** to_link_addr, struct link_socket_info * to_link_socket_info, interval_t * wakeup)
Definition at line 3021 of file ssl.c.
References link_socket_addr::actual, D_TLS_DEBUG, D_TLS_DEBUG_LOW, DECRYPT_KEY_ENABLED, dmsg, gc_free(), gc_new(), tls_options::gremlin, session::key, tls_session::key, tls_multi::key_scan, KS_LAME_DUCK, KS_PRIMARY, lame_duck_must_die(), link_socket_actual_defined(), link_socket_info::lsa, move_session(), msg, tls_multi::n_hard_errors, tls_multi::n_soft_errors, tls_multi::opt, perf_pop(), perf_push(), PERF_TLS_MULTI_PROCESS, print_link_socket_actual(), key_state::remote_addr, reset_session(), S_ACTIVE, S_ERROR, S_INITIAL, tls_multi::session, session_id_print(), key_state::session_id_remote, tls_options::single_session, SIZE, key_state::state, state_name(), TLS_AUTHENTICATION_FAILED, tls_authentication_status(), TLS_AUTHENTICATION_SUCCEEDED, tls_clear_error(), TLS_MULTI_AUTH_STATUS_INTERVAL, tls_process(), tls_session_free(), TLSMP_ACTIVE, TLSMP_INACTIVE, TLSMP_KILL, TM_ACTIVE, TM_LAME_DUCK, TM_SIZE, TM_UNTRUSTED, tls_multi::to_link_addr, and update_time().
Referenced by check_tls().
tls_pre_decrypt()
bool tls_pre_decrypt (struct tls_multi * multi, const struct link_socket_actual * from, struct buffer * buf, struct crypto_options ** opt, bool floated, const uint8_t ** ad_start)
Determine whether an incoming packet is a data channel or control channel packet, and process accordingly.
When OpenVPN is in TLS mode, this is the first function to process an incoming packet. It inspects the packet's one-byte header which contains the packet's opcode and key ID. Depending on the opcode, the packet is processed as a data channel or as a control channel packet.
Data channel packets
If the opcode indicates the packet is a data channel packet, then the packet's key ID is used to find the local TLS state it is associated with. This state is checked whether it is active, authenticated, and its remote peer is the source of this packet. If these checks passed, the state's security parameters are loaded into the opt crypto options so that openvpn_decrypt() can later use them to authenticate and decrypt the packet.
This function then returns false. The buf buffer has not been modified, except for removing the header.
Control channel packets
If the opcode indicates the packet is a control channel packet, then this function will process it based on its plaintext header. depending on the packet's opcode and session ID this function determines if it is destined for an active TLS session, or whether a new TLS session should be started. This function also initiates data channel session key renegotiation if the received opcode requests that.
If the incoming packet is destined for an active TLS session, then the packet is inserted into the Reliability Layer and will be handled later.
Parameters
multi - The TLS multi structure associated with the VPN tunnel of this packet.
from - The source address of the packet.
buf - A buffer structure containing the incoming packet.
opt - Returns a crypto options structure with the appropriate security parameters to handle the packet if it is a data channel packet.
ad_start - Returns a pointer to the start of the authenticated data of of this packet
Returns
True if the packet is a control channel packet that has been processed successfully.
False if the packet is a data channel packet, or if an error occurred during processing of a control channel packet.
Definition at line 3303 of file ssl.c.
References ASSERT, BPTR, buf_advance(), buf_copy(), D_MULTI_DROPPED, D_TLS_DEBUG, D_TLS_DEBUG_LOW, D_TLS_ERRORS, DECRYPT_KEY_ENABLED, dmsg, gc_free(), gc_new(), handle_data_channel_packet(), is_hard_reset_method2(), session::key, key_state::key_id, key_state_soft_reset(), KS_PRIMARY, reliable_ack::len, buffer::len, link_socket_actual_match(), management_set_state(), msg, tls_multi::n_sessions, tls_multi::n_soft_errors, OPENVPN_STATE_AUTH, tls_multi::opt, P_ACK_V1, P_CONTROL_HARD_RESET_CLIENT_V1, P_CONTROL_HARD_RESET_CLIENT_V2, P_CONTROL_HARD_RESET_CLIENT_V3, P_CONTROL_HARD_RESET_SERVER_V1, P_CONTROL_HARD_RESET_SERVER_V2, P_CONTROL_SOFT_RESET_V1, P_DATA_V1, P_DATA_V2, P_KEY_ID_MASK, P_LAST_OPCODE, P_OPCODE_SHIFT, packet_opcode_name(), print_key_id(), print_link_socket_actual(), read_control_auth(), key_state::rec_ack, key_state::rec_reliable, reliable_ack_acknowledge_packet_id(), reliable_ack_read(), reliable_ack_read_packet_id(), reliable_can_get(), reliable_get_buf(), reliable_mark_active_incoming(), reliable_not_replay(), reliable_schedule_now(), reliable_send_purge(), reliable_wont_break_sequentiality(), key_state::remote_addr, S_ERROR, S_UNDEF, key_state::send_reliable, tls_options::server, tls_multi::session, session_id_defined(), session_id_equal(), session_id_print(), session_id_read(), key_state::session_id_remote, tls_options::single_session, key_state::state, state_name(), tls_clear_error(), TM_ACTIVE, TM_LAME_DUCK, TM_SIZE, and TM_UNTRUSTED.
Referenced by process_incoming_link_part1().
tls_process()
static bool tls_process (struct tls_multi * multi, struct tls_session * session, struct buffer * to_link, struct link_socket_actual ** to_link_addr, struct link_socket_info * to_link_socket_info, interval_t * wakeup) static
Definition at line 2649 of file ssl.c.
References key_state::ack_write_buf, ASSERT, key_state::auth_deferred_expire, auth_deferred_expire_window(), buf_init, check_debug_level(), compute_earliest_wakeup(), CONTROL_SEND_ACK_MAX, counter_format, key_state::crypto_options, D_HANDSHAKE, D_TLS_DEBUG, D_TLS_DEBUG_LOW, D_TLS_DEBUG_MED, D_TLS_ERRORS, dmsg, key_state::established, flush_payload_buffer(), tls_options::frame, FRAME_HEADROOM, FULL_SYNC, gc_free(), gc_new(), INCR_ERROR, INCR_GENERATED, INCR_SENT, INCR_SUCCESS, key_state::initial_opcode, session::key, key_method_2_read(), key_method_2_write(), key_state_free(), key_state_read_ciphertext(), key_state_read_plaintext(), key_state_soft_reset(), key_state_write_ciphertext(), key_state_write_plaintext(), KS_LAME_DUCK, KS_PRIMARY, key_state::ks_ssl, lame_duck_must_die(), buffer::len, link_socket_set_outgoing_addr(), management_set_state(), msg, key_state::must_negotiate, key_state::n_bytes, key_state::n_packets, now, OPENVPN_STATE_WAIT, tls_multi::opt, P_ACK_V1, P_CONTROL_SOFT_RESET_V1, P_CONTROL_V1, crypto_options::packet_id, packet_id_close_to_wrapping(), PAYLOAD_SIZE_DYNAMIC, key_state::plaintext_read_buf, key_state::plaintext_write_buf, print_details(), key_state::rec_ack, key_state::rec_reliable, reliable_ack_empty(), RELIABLE_ACK_SIZE, reliable_can_send(), reliable_get_buf_output_sequenced(), reliable_get_buf_sequenced(), reliable_mark_active_outgoing(), reliable_mark_deleted(), reliable_send(), reliable_send_timeout(), key_state::remote_addr, S_ACTIVE, S_ERROR, S_GOT_KEY, S_INITIAL, S_PRE_START, S_SENT_KEY, S_START, S_UNDEF, packet_id::send, key_state::send_reliable, session_id_defined(), session_id_print(), SSLF_CRL_VERIFY_DIR, key_state::state, state_name(), status, TLS_CHANNEL_BUF_SIZE, tls_clear_error(), tls_ctx_reload_crl(), tls_x509_clear_env(), update_time(), and write_control_auth().
Referenced by tls_multi_process().
tls_rec_payload()
bool tls_rec_payload (struct tls_multi * multi, struct buffer * buf)
Definition at line 3940 of file ssl.c.
References ASSERT, BLEN, buf_copy(), session::key, KS_PRIMARY, buffer::len, key_state::plaintext_read_buf, S_ACTIVE, tls_multi::session, key_state::state, tls_clear_error(), and TM_ACTIVE.
Referenced by check_incoming_control_channel().
tls_send_payload()
bool tls_send_payload (struct tls_multi * multi, const uint8_t * data, int size)
Definition at line 3901 of file ssl.c.
References ASSERT, buffer_list_new(), buffer_list_push_data(), session::key, key_state_write_plaintext_const(), KS_PRIMARY, key_state::ks_ssl, key_state::paybuf, S_ACTIVE, tls_multi::session, key_state::state, tls_clear_error(), and TM_ACTIVE.
Referenced by send_control_channel_string_dowork().
tls_session_generate_data_channel_keys()
static bool tls_session_generate_data_channel_keys (struct tls_session * session) static
Generate data channel keys for the supplied TLS session.
This erases the source material used to generate the data channel keys, and can thus be called only once per session.
Definition at line 1913 of file ssl.c.
References key_state::authenticated, key_state::crypto_options, D_TLS_ERRORS, crypto_options::flags, generate_key_expansion(), session::key, crypto_options::key_ctx_bi, key_state::key_src, KS_AUTH_FALSE, KS_PRIMARY, msg, secure_memzero(), key_state::session_id_remote, and tls_limit_reneg_bytes().
Referenced by key_method_2_read(), key_method_2_write(), and tls_session_update_crypto_params().
tls_session_update_crypto_params()
bool tls_session_update_crypto_params (struct tls_session * session, struct options * options, struct frame * frame, struct frame * frame_fragment)
Update TLS session crypto parameters (cipher and auth) and derive data channel keys based on the supplied options.
Does nothing if keys are already generated.
Parameters
session The TLS session to update.
options The options to use when updating session.
frame The frame options for this session (frame overhead is adjusted based on the selected cipher/auth).
frame_fragment The fragment frame options.
Returns
true if updating succeeded or keys are already generated, false otherwise.
Definition at line 1946 of file ssl.c.
References options::authname, options::ce, cipher_kt_mode_ofb_cfb(), options::ciphername, CO_PACKET_ID_LONG_FORM, crypto_adjust_frame_parameters(), crypto_max_overhead(), D_HANDSHAKE, D_MTU_INFO, D_TLS_ERRORS, options::enable_ncp_fallback, connection_entry::fragment, frame_finalize(), frame_init_mssfix(), frame_print(), frame_remove_from_extra_frame(), frame_set_mtu_dynamic(), init_key_type(), session::key, options::keysize, KS_PRIMARY, connection_entry::link_mtu, connection_entry::link_mtu_defined, msg, options::ncp_ciphers, options::replay, SET_MTU_UPPER_BOUND, streq, tls_item_in_cipher_list(), tls_session_generate_data_channel_keys(), connection_entry::tun_mtu, and connection_entry::tun_mtu_defined.
Referenced by do_deferred_options(), and multi_client_generate_tls_keys().
tls_session_user_pass_enabled()
static bool tls_session_user_pass_enabled (struct tls_session * session) inline static
Returns whether or not the server should check for username/password.
Parameters
session The current TLS session
Returns
true if username and password verification is enabled, false if not.
Definition at line 1056 of file ssl.c.
References OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, and plugin_defined().
Referenced by key_method_2_read().
tls_update_remote_addr()
void tls_update_remote_addr (struct tls_multi * multi, const struct link_socket_actual * addr)
Updates remote address in TLS sessions.
Parameters
multi - Tunnel to update
addr - new address
Definition at line 3969 of file ssl.c.
References D_TLS_KEYSELECT, dmsg, gc_free(), gc_new(), session::key, KS_SIZE, link_socket_actual_defined(), link_socket_actual_match(), print_link_socket_actual(), key_state::remote_addr, tls_multi::session, and TM_SIZE.
Referenced by multi_process_float().
tls_version_parse()
int tls_version_parse (const char * vstr, const char * extra)
Definition at line 515 of file ssl.c.
References TLS_VER_1_0, TLS_VER_1_1, TLS_VER_1_2, TLS_VER_1_3, TLS_VER_BAD, and tls_version_max().
Referenced by add_option().
write_control_auth()
static void write_control_auth (struct tls_session * session, struct key_state * ks, struct buffer * buf, struct link_socket_actual ** to_link_addr, int opcode, int max_ack, bool prepend_ack) static
Definition at line 1452 of file ssl.c.
References ASSERT, buf_copy(), buf_init, buf_write(), buf_write_prepend(), clear_buf(), D_TLS_DEBUG, D_TLS_ERRORS, key_state::key_id, buffer::len, link_socket_actual_defined(), msg, buffer::offset, openvpn_encrypt(), P_CONTROL_HARD_RESET_CLIENT_V3, P_OPCODE_SHIFT, packet_opcode_name(), key_state::rec_ack, reliable_ack_write(), key_state::remote_addr, key_state::session_id_remote, session_id_write(), session_id_write_prepend(), swap_hmac(), and tls_crypt_wrap().
Referenced by tls_process().
write_empty_string()
static bool write_empty_string (struct buffer * buf) static
Definition at line 2148 of file ssl.c.
References buf_write_u16().
Referenced by key_method_2_write(), and push_peer_info().
write_string()
static bool write_string (struct buffer * buf, const char * str, const int maxlen) static
Definition at line 2158 of file ssl.c.
References buf_write(), and buf_write_u16().
Referenced by key_method_2_write(), and push_peer_info().
Variable Documentation
auth_challenge
char* auth_challenge static
Definition at line 394 of file ssl.c.
Referenced by auth_user_pass_mgmt(), auth_user_pass_setup(), get_auth_challenge(), get_user_pass_cr(), ssl_purge_auth_challenge(), and ssl_put_auth_challenge().
auth_token
struct user_pass auth_token static
Definition at line 391 of file ssl.c.
Referenced by auth_user_pass_setup(), key_method_2_write(), ssl_clean_auth_token(), ssl_set_auth_token(), and ssl_set_auth_token_user().
auth_user_pass
struct user_pass auth_user_pass static
Definition at line 390 of file ssl.c.
Referenced by auth_user_pass_setup(), key_method_2_write(), ssl_purge_auth(), ssl_set_auth_nocache(), and ssl_set_auth_token().
auth_user_pass_enabled
bool auth_user_pass_enabled static
Definition at line 389 of file ssl.c.
Referenced by enable_auth_user_pass(), and key_method_2_write().
passbuf
struct user_pass passbuf static
Definition at line 359 of file ssl.c.
Referenced by pem_password_callback(), pem_password_setup(), ssl_purge_auth(), and ssl_set_auth_nocache().
tls_cipher_name_translation_table
const tls_cipher_name_pair tls_cipher_name_translation_table[] static
SSL/TLS Cipher suite name translation table.
Definition at line 101 of file ssl.c.
Referenced by tls_get_cipher_name_pair().