OpenVPN: src/openvpn/ssl_verify.h File Reference
ssl_verify.h File Reference
#include "syshead.h"
#include "misc.h"
#include "ssl_common.h"
#include "ssl_verify_openssl.h"
#include "ssl_verify_backend.h"
Data Structures
struct cert_hash
Structure containing the hash for a single certificate.
struct cert_hash_set
Structure containing the hashes for a full certificate chain.
struct x509_track
Macros
#define MAX_CERT_DEPTH 16
Maximum certificate depth we will allow.
#define VERIFY_X509_NONE 0
#define VERIFY_X509_SUBJECT_DN 1
#define VERIFY_X509_SUBJECT_RDN 2
#define VERIFY_X509_SUBJECT_RDN_PREFIX 3
#define TLS_AUTHENTICATION_SUCCEEDED 0
#define TLS_AUTHENTICATION_FAILED 1
#define TLS_AUTHENTICATION_DEFERRED 2
#define TLS_AUTHENTICATION_UNDEFINED 3
#define DECRYPT_KEY_ENABLED(multi, ks) ((ks)->state >= (S_GOT_KEY - (multi)->opt.server))
Check whether the ks key_state is ready to receive data channel packets.
#define XT_FULL_CHAIN (1<<0)
#define NS_CERT_CHECK_NONE (0)
Do not perform Netscape certificate type verification.
#define NS_CERT_CHECK_SERVER (1<<0)
Do not perform Netscape certificate type verification.
#define NS_CERT_CHECK_CLIENT (1<<1)
Do not perform Netscape certificate type verification.
#define OPENVPN_KU_REQUIRED (0xFFFF)
Require keyUsage to be present in cert (0xFFFF is an invalid KU value)
Functions
int tls_authentication_status (struct tls_multi *multi, const int latency)
void key_state_rm_auth_control_file (struct key_state *ks)
Remove the given key state's auth control file, if it exists.
void cert_hash_free (struct cert_hash_set *chs)
Frees the given set of certificate hashes.
void tls_lock_cert_hash_set (struct tls_multi *multi)
Locks the certificate hash set used in the given tunnel.
void tls_lock_common_name (struct tls_multi *multi)
Locks the common name field for the given tunnel.
const char * tls_common_name (const struct tls_multi *multi, const bool null)
Returns the common name field for the given tunnel.
const char * tls_username (const struct tls_multi *multi, const bool null)
Returns the username field for the given tunnel.
bool cert_hash_compare (const struct cert_hash_set *chs1, const struct cert_hash_set *chs2)
Compares certificates hashes, returns true if hashes are equal.
void verify_user_pass (struct user_pass *up, struct tls_multi *multi, struct tls_session *session)
Verify the given username and password, using either an external script, a plugin, or the management interface.
void verify_final_auth_checks (struct tls_multi *multi, struct tls_session *session)
Perform final authentication checks, including locking of the cn, the allowed certificate hashes, and whether a client config entry exists in the client config directory.
void auth_set_client_reason (struct tls_multi *multi, const char *client_reason)
Sets the reason why authentication of a client failed.
static const char * tls_client_reason (struct tls_multi *multi)
void tls_x509_clear_env (struct env_set *es)
Remove any X509_ env variables from env_set es.
Macro Definition Documentation
MAX_CERT_DEPTH
#define MAX_CERT_DEPTH 16
Maximum certificate depth we will allow.
Definition at line 51 of file ssl_verify.h.
NS_CERT_CHECK_CLIENT
#define NS_CERT_CHECK_CLIENT (1<<1)
Do not perform Netscape certificate type verification.
Definition at line 216 of file ssl_verify.h.
NS_CERT_CHECK_NONE
#define NS_CERT_CHECK_NONE (0)
Do not perform Netscape certificate type verification.
Definition at line 212 of file ssl_verify.h.
NS_CERT_CHECK_SERVER
#define NS_CERT_CHECK_SERVER (1<<0)
Do not perform Netscape certificate type verification.
Definition at line 214 of file ssl_verify.h.
OPENVPN_KU_REQUIRED
#define OPENVPN_KU_REQUIRED (0xFFFF)
Require keyUsage to be present in cert (0xFFFF is an invalid KU value)
Definition at line 219 of file ssl_verify.h.
TLS_AUTHENTICATION_DEFERRED
#define TLS_AUTHENTICATION_DEFERRED 2
Definition at line 70 of file ssl_verify.h.
TLS_AUTHENTICATION_FAILED
#define TLS_AUTHENTICATION_FAILED 1
Definition at line 69 of file ssl_verify.h.
TLS_AUTHENTICATION_SUCCEEDED
#define TLS_AUTHENTICATION_SUCCEEDED 0
Definition at line 68 of file ssl_verify.h.
TLS_AUTHENTICATION_UNDEFINED
#define TLS_AUTHENTICATION_UNDEFINED 3
Definition at line 71 of file ssl_verify.h.
VERIFY_X509_NONE
#define VERIFY_X509_NONE 0
Definition at line 63 of file ssl_verify.h.
VERIFY_X509_SUBJECT_DN
#define VERIFY_X509_SUBJECT_DN 1
Definition at line 64 of file ssl_verify.h.
VERIFY_X509_SUBJECT_RDN
#define VERIFY_X509_SUBJECT_RDN 2
Definition at line 65 of file ssl_verify.h.
VERIFY_X509_SUBJECT_RDN_PREFIX
#define VERIFY_X509_SUBJECT_RDN_PREFIX 3
Definition at line 66 of file ssl_verify.h.
XT_FULL_CHAIN
#define XT_FULL_CHAIN (1<<0)
Definition at line 203 of file ssl_verify.h.
Function Documentation
auth_set_client_reason()
void auth_set_client_reason (struct tls_multi * multi, const char * client_reason)
Sets the reason why authentication of a client failed.
This be will send to the client when the AUTH_FAILED message is sent An example would be "SESSION: Token expired"
Parameters
multi The multi tls struct
client_reason The string to send to the client as part of AUTH_FAILED
Definition at line 817 of file ssl_verify.c.
References tls_multi::client_reason, and string_alloc().
Referenced by multi_client_set_protocol_options(), tls_multi_free(), and verify_auth_token().
cert_hash_compare()
bool cert_hash_compare (const struct cert_hash_set * chs1, const struct cert_hash_set * chs2)
Compares certificates hashes, returns true if hashes are equal.
Parameters
chs1 cert 1 hash set
chs2 cert 2 hash set
Definition at line 250 of file ssl_verify.c.
References cert_hash_set::ch, MAX_CERT_DEPTH, and cert_hash::sha256_hash.
Referenced by multi_process_float(), and verify_final_auth_checks().
cert_hash_free()
void cert_hash_free (struct cert_hash_set * chs)
Frees the given set of certificate hashes.
Parameters
chs The certificate hash set to free.
Definition at line 236 of file ssl_verify.c.
References cert_hash_set::ch, and MAX_CERT_DEPTH.
Referenced by tls_multi_free(), and tls_session_free().
key_state_rm_auth_control_file()
void key_state_rm_auth_control_file (struct key_state * ks)
Remove the given key state's auth control file, if it exists.
Parameters
ks The key state the remove the file for
Referenced by key_state_free(), and verify_user_pass_plugin().
tls_authentication_status()
int tls_authentication_status (struct tls_multi * multi, const int latency)
Definition at line 950 of file ssl_verify.c.
References ASSERT, key_state::auth_deferred_expire, key_state::authenticated, D_TLS_ERRORS, DECRYPT_KEY_ENABLED, dmsg, tls_multi::key_scan, KEY_SCAN_SIZE, KS_AUTH_DEFERRED, KS_AUTH_FALSE, KS_AUTH_TRUE, now, tls_multi::session, ssl_session_fully_authenticated(), TLS_AUTHENTICATION_DEFERRED, TLS_AUTHENTICATION_FAILED, TLS_AUTHENTICATION_SUCCEEDED, TLS_AUTHENTICATION_UNDEFINED, and TM_ACTIVE.
Referenced by multi_connection_established(), process_incoming_push_request(), and tls_multi_process().
tls_client_reason()
static const char* tls_client_reason (struct tls_multi * multi) inline static
Definition at line 239 of file ssl_verify.h.
References tls_multi::client_reason.
Referenced by process_incoming_push_request().
tls_common_name()
const char* tls_common_name (const struct tls_multi * multi, const bool null)
Returns the common name field for the given tunnel.
Parameters
multi The tunnel to return the common name for
null Whether null may be returned. If not, "UNDEF" will be returned.
Definition at line 129 of file ssl_verify.c.
References tls_session::common_name, tls_multi::session, and TM_ACTIVE.
Referenced by format_common_name(), learn_address_script(), management_callback_kill_by_cn(), multi_client_connect_setenv(), multi_client_connect_source_ccd(), multi_delete_dup(), multi_instance_string(), multi_print_status(), multi_process_float(), multi_select_virtual_addr(), and send_control_channel_string_dowork().
tls_lock_cert_hash_set()
void tls_lock_cert_hash_set (struct tls_multi * multi)
Locks the certificate hash set used in the given tunnel.
Parameters
multi The tunnel to lock
Definition at line 308 of file ssl_verify.c.
References cert_hash_copy(), tls_session::cert_hash_set, tls_multi::locked_cert_hash_set, tls_multi::session, and TM_ACTIVE.
Referenced by multi_client_connect_early_setup().
tls_lock_common_name()
void tls_lock_common_name (struct tls_multi * multi)
Locks the common name field for the given tunnel.
Parameters
multi The tunnel to lock
Definition at line 154 of file ssl_verify.c.
References tls_session::common_name, tls_multi::locked_cn, tls_multi::session, string_alloc(), and TM_ACTIVE.
Referenced by multi_client_connect_early_setup().
tls_username()
const char* tls_username (const struct tls_multi * multi, const bool null)
Returns the username field for the given tunnel.
Parameters
multi The tunnel to return the username for
null Whether null may be returned. If not, "UNDEF" will be returned.
Definition at line 193 of file ssl_verify.c.
References tls_multi::locked_username.
Referenced by multi_print_status().
tls_x509_clear_env()
void tls_x509_clear_env (struct env_set * es)
Remove any X509_ env variables from env_set es.
Definition at line 1515 of file ssl_verify.c.
References env_set_del(), env_set::list, env_item::next, and env_item::string.
Referenced by tls_process().
verify_final_auth_checks()
void verify_final_auth_checks (struct tls_multi * multi, struct tls_session * session)
Perform final authentication checks, including locking of the cn, the allowed certificate hashes, and whether a client config entry exists in the client config directory.
Parameters
multi The TLS multi structure to verify locked structures.
session The current TLS session
Definition at line 1453 of file ssl_verify.c.
References key_state::authenticated, CCD_DEFAULT, cert_hash_compare(), D_TLS_ERRORS, gc_free(), gc_new(), session::key, KS_AUTH_FALSE, KS_PRIMARY, tls_multi::locked_cert_hash_set, tls_multi::locked_cn, msg, platform_gen_path(), platform_test_file(), set_common_name(), tls_deauthenticate(), and wipe_auth_token().
Referenced by key_method_2_read().
verify_user_pass()
void verify_user_pass (struct user_pass * up, struct tls_multi * multi, struct tls_session * session)
Verify the given username and password, using either an external script, a plugin, or the management interface.
If authentication succeeds, the appropriate state is filled into the session's primary key state's authenticated field. Authentication may also be deferred, in which case the key state's auth_deferred field is filled in.
Parameters
up The username and password to verify.
multi The TLS multi structure to verify usernames against.
session The current TLS session
Definition at line 1279 of file ssl_verify.c.
References tls_multi::auth_token, AUTH_TOKEN_EXPIRED, AUTH_TOKEN_HMAC_OK, key_state::auth_token_state_flags, key_state::authenticated, CC_CRLF, CC_PRINT, D_HANDSHAKE, D_TLS_ERRORS, generate_auth_token(), is_auth_token(), session::key, KS_AUTH_DEFERRED, KS_AUTH_FALSE, KS_AUTH_TRUE, KS_PRIMARY, M_WARN, msg, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_FUNC_DEFERRED, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_FUNC_SUCCESS, user_pass::password, plugin_defined(), set_common_name(), set_verify_user_pass_env(), ssl_session_fully_authenticated(), SSLF_USERNAME_AS_COMMON_NAME, string_mod(), string_mod_remap_name(), tls_lock_username(), TLS_USERNAME_LEN, user_pass::username, verify_auth_token(), verify_user_pass_plugin(), verify_user_pass_script(), and wipe_auth_token().
Referenced by key_method_2_read().