OpenVPN: src/openvpn/ssl_verify.c File Reference
ssl_verify.c File Reference
#include "syshead.h"
#include "base64.h"
#include "manage.h"
#include "otime.h"
#include "run_command.h"
#include "ssl_verify.h"
#include "ssl_verify_backend.h"
#include "ssl_verify_openssl.h"
#include "auth_token.h"
#include "push.h"
Macros
#define TLS_USERNAME_LEN 64
Maximum length of common name.
Functions
static void string_mod_remap_name (char *str)
static void setenv_untrusted (struct tls_session *session)
static void tls_deauthenticate (struct tls_multi *multi)
static void set_common_name (struct tls_session *session, const char *common_name)
const char * tls_common_name (const struct tls_multi *multi, const bool null)
Returns the common name field for the given tunnel.
void tls_lock_common_name (struct tls_multi *multi)
Locks the common name field for the given tunnel.
static bool tls_lock_username (struct tls_multi *multi, const char *username)
const char * tls_username (const struct tls_multi *multi, const bool null)
Returns the username field for the given tunnel.
void cert_hash_remember (struct tls_session *session, const int error_depth, const struct buffer *cert_hash)
void cert_hash_free (struct cert_hash_set *chs)
Frees the given set of certificate hashes.
bool cert_hash_compare (const struct cert_hash_set *chs1, const struct cert_hash_set *chs2)
Compares certificates hashes, returns true if hashes are equal.
static struct cert_hash_set * cert_hash_copy (const struct cert_hash_set *chs)
void tls_lock_cert_hash_set (struct tls_multi *multi)
Locks the certificate hash set used in the given tunnel.
static const char * print_nsCertType (int type)
static result_t verify_peer_cert (const struct tls_options *opt, openvpn_x509_cert_t *peer_cert, const char *subject, const char *common_name)
static void verify_cert_set_env (struct env_set *es, openvpn_x509_cert_t *peer_cert, int cert_depth, const char *subject, const char *common_name, const struct x509_track *x509_track)
static result_t verify_cert_call_plugin (const struct plugin_list *plugins, struct env_set *es, int cert_depth, openvpn_x509_cert_t *cert, char *subject)
static const char * verify_cert_export_cert (openvpn_x509_cert_t *peercert, const char *tmp_dir, struct gc_arena *gc)
static result_t verify_cert_call_command (const char *verify_command, struct env_set *es, int cert_depth, openvpn_x509_cert_t *cert, char *subject, const char *verify_export_cert)
static result_t verify_check_crl_dir (const char *crl_dir, openvpn_x509_cert_t *cert, const char *subject, int cert_depth)
result_t verify_cert (struct tls_session *session, openvpn_x509_cert_t *cert, int cert_depth)
void auth_set_client_reason (struct tls_multi *multi, const char *client_reason)
Sets the reason why authentication of a client failed.
void ssl_session_fully_authenticated (struct tls_multi *multi, struct tls_session *session)
int tls_authentication_status (struct tls_multi *multi, const int latency)
static bool verify_user_pass_script (struct tls_session *session, struct tls_multi *multi, const struct user_pass *up)
static int verify_user_pass_plugin (struct tls_session *session, struct tls_multi *multi, const struct user_pass *up)
static bool set_verify_user_pass_env (struct user_pass *up, struct tls_multi *multi, struct tls_session *session)
void verify_user_pass (struct user_pass *up, struct tls_multi *multi, struct tls_session *session)
Verify the given username and password, using either an external script, a plugin, or the management interface.
void verify_final_auth_checks (struct tls_multi *multi, struct tls_session *session)
Perform final authentication checks, including locking of the cn, the allowed certificate hashes, and whether a client config entry exists in the client config directory.
void tls_x509_clear_env (struct env_set *es)
Remove any X509_ env variables from env_set es.
Macro Definition Documentation
TLS_USERNAME_LEN
#define TLS_USERNAME_LEN 64
Maximum length of common name.
Definition at line 51 of file ssl_verify.c.
Function Documentation
auth_set_client_reason()
void auth_set_client_reason (struct tls_multi * multi, const char * client_reason)
Sets the reason why authentication of a client failed.
This be will send to the client when the AUTH_FAILED message is sent An example would be "SESSION: Token expired"
Parameters
multi The multi tls struct
client_reason The string to send to the client as part of AUTH_FAILED
Definition at line 817 of file ssl_verify.c.
Referenced by multi_client_set_protocol_options(), tls_multi_free(), and verify_auth_token().
cert_hash_compare()
bool cert_hash_compare (const struct cert_hash_set * chs1, const struct cert_hash_set * chs2)
Compares certificates hashes, returns true if hashes are equal.
Parameters
chs1 cert 1 hash set
chs2 cert 2 hash set
Definition at line 250 of file ssl_verify.c.
References cert_hash_set::ch, MAX_CERT_DEPTH, and cert_hash::sha256_hash.
Referenced by multi_process_float(), and verify_final_auth_checks().
cert_hash_copy()
static struct cert_hash_set* cert_hash_copy (const struct cert_hash_set * chs) static
Definition at line 287 of file ssl_verify.c.
References ALLOC_OBJ, ALLOC_OBJ_CLEAR, cert_hash_set::ch, dest, MAX_CERT_DEPTH, and cert_hash::sha256_hash.
Referenced by tls_lock_cert_hash_set().
cert_hash_free()
void cert_hash_free (struct cert_hash_set * chs)
Frees the given set of certificate hashes.
Parameters
chs The certificate hash set to free.
Definition at line 236 of file ssl_verify.c.
References cert_hash_set::ch, and MAX_CERT_DEPTH.
Referenced by tls_multi_free(), and tls_session_free().
cert_hash_remember()
void cert_hash_remember (struct tls_session * session, const int error_depth, const struct buffer * cert_hash)
Definition at line 215 of file ssl_verify.c.
References ALLOC_OBJ, ALLOC_OBJ_CLEAR, ASSERT, BLEN, BPTR, MAX_CERT_DEPTH, and cert_hash::sha256_hash.
Referenced by verify_callback().
print_nsCertType()
static const char* print_nsCertType (int type) static
Definition at line 321 of file ssl_verify.c.
References NS_CERT_CHECK_CLIENT, and NS_CERT_CHECK_SERVER.
Referenced by verify_peer_cert().
set_common_name()
static void set_common_name (struct tls_session * session, const char * common_name) static
Definition at line 91 of file ssl_verify.c.
References hash_func(), setenv_str(), and string_alloc().
Referenced by verify_cert(), verify_final_auth_checks(), and verify_user_pass().
set_verify_user_pass_env()
static bool set_verify_user_pass_env (struct user_pass * up, struct tls_multi * multi, struct tls_session * session) static
Definition at line 1244 of file ssl_verify.c.
References add_session_token_env(), D_TLS_ERRORS, msg, setenv_str(), setenv_untrusted(), SSLF_AUTH_USER_PASS_OPTIONAL, and user_pass::username.
Referenced by verify_user_pass().
setenv_untrusted()
static void setenv_untrusted (struct tls_session * session) static
Definition at line 63 of file ssl_verify.c.
References SA_IP_PORT, and setenv_link_socket_actual().
Referenced by set_verify_user_pass_env(), and verify_cert().
ssl_session_fully_authenticated()
void ssl_session_fully_authenticated (struct tls_multi * multi, struct tls_session * session)
Definition at line 912 of file ssl_verify.c.
References tls_multi::auth_token_initial, session::key, key_state::key_id, KS_PRIMARY, and send_push_reply_auth_token().
Referenced by tls_authentication_status(), and verify_user_pass().
string_mod_remap_name()
static void string_mod_remap_name (char * str) static
Definition at line 54 of file ssl_verify.c.
References CC_CRLF, CC_PRINT, and string_mod().
Referenced by verify_cert(), and verify_user_pass().
tls_authentication_status()
int tls_authentication_status (struct tls_multi * multi, const int latency)
Definition at line 950 of file ssl_verify.c.
References ASSERT, key_state::auth_deferred_expire, key_state::authenticated, D_TLS_ERRORS, DECRYPT_KEY_ENABLED, dmsg, tls_multi::key_scan, KEY_SCAN_SIZE, KS_AUTH_DEFERRED, KS_AUTH_FALSE, KS_AUTH_TRUE, now, tls_multi::session, ssl_session_fully_authenticated(), TLS_AUTHENTICATION_DEFERRED, TLS_AUTHENTICATION_FAILED, TLS_AUTHENTICATION_SUCCEEDED, TLS_AUTHENTICATION_UNDEFINED, and TM_ACTIVE.
Referenced by multi_connection_established(), process_incoming_push_request(), and tls_multi_process().
tls_common_name()
const char* tls_common_name (const struct tls_multi * multi, const bool null)
Returns the common name field for the given tunnel.
Parameters
multi The tunnel to return the common name for
null Whether null may be returned. If not, "UNDEF" will be returned.
Definition at line 129 of file ssl_verify.c.
References tls_session::common_name, tls_multi::session, and TM_ACTIVE.
Referenced by format_common_name(), learn_address_script(), management_callback_kill_by_cn(), multi_client_connect_setenv(), multi_client_connect_source_ccd(), multi_delete_dup(), multi_instance_string(), multi_print_status(), multi_process_float(), multi_select_virtual_addr(), and send_control_channel_string_dowork().
tls_deauthenticate()
static void tls_deauthenticate (struct tls_multi * multi) static
Definition at line 72 of file ssl_verify.c.
References key_state::authenticated, tls_session::key, KS_AUTH_FALSE, KS_SIZE, tls_multi::session, TM_SIZE, and wipe_auth_token().
Referenced by tls_lock_username(), and verify_final_auth_checks().
tls_lock_cert_hash_set()
void tls_lock_cert_hash_set (struct tls_multi * multi)
Locks the certificate hash set used in the given tunnel.
Parameters
multi The tunnel to lock
Definition at line 308 of file ssl_verify.c.
References cert_hash_copy(), tls_session::cert_hash_set, tls_multi::locked_cert_hash_set, tls_multi::session, and TM_ACTIVE.
Referenced by multi_client_connect_early_setup().
tls_lock_common_name()
void tls_lock_common_name (struct tls_multi * multi)
Locks the common name field for the given tunnel.
Parameters
multi The tunnel to lock
Definition at line 154 of file ssl_verify.c.
References tls_session::common_name, tls_multi::locked_cn, tls_multi::session, string_alloc(), and TM_ACTIVE.
Referenced by multi_client_connect_early_setup().
tls_lock_username()
static bool tls_lock_username (struct tls_multi * multi, const char * username) static
Definition at line 167 of file ssl_verify.c.
References D_TLS_ERRORS, tls_multi::locked_username, msg, np(), string_alloc(), and tls_deauthenticate().
Referenced by verify_user_pass().
tls_username()
const char* tls_username (const struct tls_multi * multi, const bool null)
Returns the username field for the given tunnel.
Parameters
multi The tunnel to return the username for
null Whether null may be returned. If not, "UNDEF" will be returned.
Definition at line 193 of file ssl_verify.c.
References tls_multi::locked_username.
Referenced by multi_print_status().
tls_x509_clear_env()
void tls_x509_clear_env (struct env_set * es)
Remove any X509_ env variables from env_set es.
Definition at line 1515 of file ssl_verify.c.
References env_set_del(), env_set::list, env_item::next, and env_item::string.
Referenced by tls_process().
verify_cert()
result_t verify_cert (struct tls_session * session, openvpn_x509_cert_t * cert, int cert_depth)
Definition at line 646 of file ssl_verify.c.
References ASSERT, backend_x509_get_username(), BLEN, BPTR, tls_options::crl_file, D_HANDSHAKE, D_TLS_ERRORS, tls_options::es, FAILURE, gc_free(), gc_new(), M_WARN, MAX_CERT_DEPTH, max_int(), MD_SHA1, MD_SHA256, msg, tls_options::plugins, set_common_name(), setenv_untrusted(), tls_options::ssl_flags, SSLF_CRL_VERIFY_DIR, string_mod_remap_name(), string_replace_leading(), SUCCESS, tls_clear_error(), TLS_USERNAME_LEN, tls_verify_crl_missing(), verify_cert_call_command(), verify_cert_call_plugin(), verify_cert_set_env(), verify_check_crl_dir(), tls_options::verify_command, tls_options::verify_export_cert, tls_options::verify_hash, tls_options::verify_hash_algo, verify_peer_cert(), x509_get_sha1_fingerprint(), x509_get_sha256_fingerprint(), x509_get_subject(), tls_options::x509_track, and tls_options::x509_username_field.
Referenced by verify_callback().
verify_cert_call_command()
static result_t verify_cert_call_command (const char * verify_command, struct env_set * es, int cert_depth, openvpn_x509_cert_t * cert, char * subject, const char * verify_export_cert) static
Definition at line 549 of file ssl_verify.c.
References argv_free(), argv_msg_prefix(), argv_new(), argv_parse_cmd(), argv_printf_cat(), D_HANDSHAKE, D_TLS_DEBUG, FAILURE, argv::gc, gc_free(), gc_new(), msg, openvpn_run_script(), platform_unlink(), setenv_str(), SUCCESS, and verify_cert_export_cert().
Referenced by verify_cert().
verify_cert_call_plugin()
static result_t verify_cert_call_plugin (const struct plugin_list * plugins, struct env_set * es, int cert_depth, openvpn_x509_cert_t * cert, char * subject) static
Definition at line 481 of file ssl_verify.c.
References argv_free(), argv_new(), argv_printf(), D_HANDSHAKE, FAILURE, msg, OPENVPN_PLUGIN_FUNC_SUCCESS, OPENVPN_PLUGIN_TLS_VERIFY, plugin_call_ssl(), plugin_defined(), and SUCCESS.
Referenced by verify_cert().
verify_cert_export_cert()
static const char* verify_cert_export_cert (openvpn_x509_cert_t * peercert, const char * tmp_dir, struct gc_arena * gc) static
Definition at line 511 of file ssl_verify.c.
References argv::gc, M_ERRNO, M_NONFATAL, msg, platform_create_temp_file(), platform_unlink(), SUCCESS, and x509_write_pem().
Referenced by verify_cert_call_command().
verify_cert_set_env()
static void verify_cert_set_env (struct env_set * es, openvpn_x509_cert_t * peer_cert, int cert_depth, const char * subject, const char * common_name, const struct x509_track * x509_track) static
Definition at line 421 of file ssl_verify.c.
References backend_x509_get_serial(), backend_x509_get_serial_hex(), BLEN, BPTR, format_hex_ex(), gc_free(), gc_new(), openvpn_snprintf(), setenv_str(), x509_get_sha1_fingerprint(), x509_get_sha256_fingerprint(), x509_setenv(), and x509_setenv_track().
Referenced by verify_cert().
verify_check_crl_dir()
static result_t verify_check_crl_dir (const char * crl_dir, openvpn_x509_cert_t * cert, const char * subject, int cert_depth) static
Definition at line 604 of file ssl_verify.c.
References backend_x509_get_serial(), D_HANDSHAKE, FAILURE, gc_free(), gc_new(), msg, openvpn_snprintf(), OS_SPECIFIC_DIRSEP, platform_open(), and SUCCESS.
Referenced by verify_cert().
verify_final_auth_checks()
void verify_final_auth_checks (struct tls_multi * multi, struct tls_session * session)
Perform final authentication checks, including locking of the cn, the allowed certificate hashes, and whether a client config entry exists in the client config directory.
Parameters
multi The TLS multi structure to verify locked structures.
session The current TLS session
Definition at line 1453 of file ssl_verify.c.
References key_state::authenticated, CCD_DEFAULT, cert_hash_compare(), D_TLS_ERRORS, gc_free(), gc_new(), session::key, KS_AUTH_FALSE, KS_PRIMARY, tls_multi::locked_cert_hash_set, tls_multi::locked_cn, msg, platform_gen_path(), platform_test_file(), set_common_name(), tls_deauthenticate(), and wipe_auth_token().
Referenced by key_method_2_read().
verify_peer_cert()
static result_t verify_peer_cert (const struct tls_options * opt, openvpn_x509_cert_t * peer_cert, const char * subject, const char * common_name) static
Definition at line 345 of file ssl_verify.c.
References D_HANDSHAKE, FAILURE, MAX_PARMS, msg, NS_CERT_CHECK_NONE, tls_options::ns_cert_type, print_nsCertType(), tls_options::remote_cert_eku, tls_options::remote_cert_ku, SUCCESS, tls_options::verify_x509_name, VERIFY_X509_NONE, VERIFY_X509_SUBJECT_DN, VERIFY_X509_SUBJECT_RDN, VERIFY_X509_SUBJECT_RDN_PREFIX, tls_options::verify_x509_type, x509_verify_cert_eku(), x509_verify_cert_ku(), and x509_verify_ns_cert_type().
Referenced by verify_cert().
verify_user_pass()
void verify_user_pass (struct user_pass * up, struct tls_multi * multi, struct tls_session * session)
Verify the given username and password, using either an external script, a plugin, or the management interface.
If authentication succeeds, the appropriate state is filled into the session's primary key state's authenticated field. Authentication may also be deferred, in which case the key state's auth_deferred field is filled in.
Parameters
up The username and password to verify.
multi The TLS multi structure to verify usernames against.
session The current TLS session
Definition at line 1279 of file ssl_verify.c.
References tls_multi::auth_token, AUTH_TOKEN_EXPIRED, AUTH_TOKEN_HMAC_OK, key_state::auth_token_state_flags, key_state::authenticated, CC_CRLF, CC_PRINT, D_HANDSHAKE, D_TLS_ERRORS, generate_auth_token(), is_auth_token(), session::key, KS_AUTH_DEFERRED, KS_AUTH_FALSE, KS_AUTH_TRUE, KS_PRIMARY, M_WARN, msg, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_FUNC_DEFERRED, OPENVPN_PLUGIN_FUNC_ERROR, OPENVPN_PLUGIN_FUNC_SUCCESS, user_pass::password, plugin_defined(), set_common_name(), set_verify_user_pass_env(), ssl_session_fully_authenticated(), SSLF_USERNAME_AS_COMMON_NAME, string_mod(), string_mod_remap_name(), tls_lock_username(), TLS_USERNAME_LEN, user_pass::username, verify_auth_token(), verify_user_pass_plugin(), verify_user_pass_script(), and wipe_auth_token().
Referenced by key_method_2_read().
verify_user_pass_plugin()
static int verify_user_pass_plugin (struct tls_session * session, struct tls_multi * multi, const struct user_pass * up) static
Definition at line 1172 of file ssl_verify.c.
References D_TLS_ERRORS, session::key, key_state_rm_auth_control_file(), KS_PRIMARY, msg, OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY, OPENVPN_PLUGIN_FUNC_DEFERRED, OPENVPN_PLUGIN_FUNC_ERROR, user_pass::password, plugin_call(), setenv_del(), and setenv_str().
Referenced by verify_user_pass().
verify_user_pass_script()
static bool verify_user_pass_script (struct tls_session * session, struct tls_multi * multi, const struct user_pass * up) static
Definition at line 1104 of file ssl_verify.c.
References argv_free(), argv_new(), argv_parse_cmd(), argv_printf_cat(), D_TLS_ERRORS, gc_free(), gc_new(), msg, openvpn_run_script(), user_pass::password, platform_create_temp_file(), platform_unlink(), setenv_del(), setenv_str(), status_close(), status_open(), STATUS_OUTPUT_WRITE, status_printf(), and user_pass::username.
Referenced by verify_user_pass().