OpenVPN: src/openvpn/ssl.h File Reference
ssl.h File Reference
#include "basic.h"
#include "common.h"
#include "crypto.h"
#include "packet_id.h"
#include "session_id.h"
#include "reliable.h"
#include "socket.h"
#include "mtu.h"
#include "options.h"
#include "plugin.h"
#include "ssl_common.h"
#include "ssl_backend.h"
Data Structures
struct tls_auth_standalone
Macros
#define KEY_EXPANSION_ID "OpenVPN"
#define P_KEY_ID_MASK 0x07
#define P_OPCODE_SHIFT 3
#define P_CONTROL_HARD_RESET_CLIENT_V1 1 /* initial key from client, forget previous state */
#define P_CONTROL_HARD_RESET_SERVER_V1 2 /* initial key from server, forget previous state */
#define P_CONTROL_SOFT_RESET_V1 3 /* new key, graceful transition from old to new key */
#define P_CONTROL_V1 4 /* control channel packet (usually TLS ciphertext) */
#define P_ACK_V1 5 /* acknowledgement for packets received */
#define P_DATA_V1 6 /* data channel packet */
#define P_DATA_V2 9 /* data channel packet with peer-id */
#define P_CONTROL_HARD_RESET_CLIENT_V2 7 /* initial key from client, forget previous state */
#define P_CONTROL_HARD_RESET_SERVER_V2 8 /* initial key from server, forget previous state */
#define P_CONTROL_HARD_RESET_CLIENT_V3 10 /* initial key from client, forget previous state */
#define P_FIRST_OPCODE 3
#define P_LAST_OPCODE 10
#define CONTROL_SEND_ACK_MAX 4
#define TLS_RELIABLE_N_SEND_BUFFERS 4 /* also window size for reliability layer */
#define TLS_RELIABLE_N_REC_BUFFERS 8
#define TLS_MULTI_REFRESH 15 /* call tls_multi_process once every n seconds */
#define TLS_MULTI_HORIZON
#define TLS_MULTI_AUTH_STATUS_INTERVAL 10
#define TLS_OPTIONS_LEN 512
#define IV_PROTO_DATA_V2 (1<<1)
Support P_DATA_V2.
#define IV_PROTO_REQUEST_PUSH (1<<2)
Assume client will send a push request and server does not need to wait for a push-request to send a push-reply.
#define X509_USERNAME_FIELD_DEFAULT "CN"
#define KEY_METHOD_2 2
#define KEY_METHOD_MASK 0x0F
#define TLSMP_INACTIVE 0
#define TLSMP_ACTIVE 1
#define TLSMP_KILL 2
#define PD_TLS_AUTH_HMAC_SIZE_MASK 0xFF
#define PD_SHOW_DATA (1<<8)
#define PD_TLS (1<<9)
#define PD_VERBOSE (1<<10)
Functions
void init_ssl_lib (void)
void free_ssl_lib (void)
void init_ssl (const struct options *options, struct tls_root_ctx *ctx, bool in_chroot)
Build master SSL context object that serves for the whole of OpenVPN instantiation.
int tls_multi_process (struct tls_multi *multi, struct buffer *to_link, struct link_socket_actual **to_link_addr, struct link_socket_info *to_link_socket_info, interval_t *wakeup)
bool tls_pre_decrypt (struct tls_multi *multi, const struct link_socket_actual *from, struct buffer *buf, struct crypto_options **opt, bool floated, const uint8_t **ad_start)
Determine whether an incoming packet is a data channel or control channel packet, and process accordingly.
void pem_password_setup (const char *auth_file)
void enable_auth_user_pass ()
void auth_user_pass_setup (const char *auth_file, const struct static_challenge_info *sc_info)
void ssl_set_auth_nocache (void)
void ssl_purge_auth (const bool auth_user_pass_only)
void ssl_set_auth_token (const char *token)
void ssl_set_auth_token_user (const char *username)
bool ssl_clean_auth_token (void)
void ssl_purge_auth_challenge (void)
void ssl_put_auth_challenge (const char *cr_str)
void tls_adjust_frame_parameters (struct frame *frame)
bool tls_send_payload (struct tls_multi *multi, const uint8_t *data, int size)
bool tls_rec_payload (struct tls_multi *multi, struct buffer *buf)
void tls_update_remote_addr (struct tls_multi *multi, const struct link_socket_actual *addr)
Updates remote address in TLS sessions.
bool tls_session_update_crypto_params (struct tls_session *session, struct options *options, struct frame *frame, struct frame *frame_fragment)
Update TLS session crypto parameters (cipher and auth) and derive data channel keys based on the supplied options.
static void tls_wrap_free (struct tls_wrap_ctx *tls_wrap)
Free the elements of a tls_wrap_ctx structure.
static bool tls_initial_packet_received (const struct tls_multi *multi)
static bool tls_test_auth_deferred_interval (const struct tls_multi *multi)
static int tls_test_payload_len (const struct tls_multi *multi)
static void tls_set_single_session (struct tls_multi *multi)
const char * protocol_dump (struct buffer *buffer, unsigned int flags, struct gc_arena *gc)
void extract_x509_field_test (void)
bool is_hard_reset_method2 (int op)
Given a key_method, return true if opcode represents the one of the hard_reset op codes for key-method 2.
void show_available_tls_ciphers (const char *cipher_list, const char *cipher_list_tls13, const char *tls_cert_profile)
Functions for initialization and cleanup of tls_multi structures
struct tls_multi * tls_multi_init (struct tls_options *tls_options)
Allocate and initialize a tls_multi structure.
void tls_multi_init_finalize (struct tls_multi *multi, const struct frame *frame)
Finalize initialization of a tls_multi structure.
struct tls_auth_standalone * tls_auth_standalone_init (struct tls_options *tls_options, struct gc_arena *gc)
void tls_auth_standalone_finalize (struct tls_auth_standalone *tas, const struct frame *frame)
void tls_multi_init_set_options (struct tls_multi *multi, const char *local, const char *remote)
void tls_multi_free (struct tls_multi *multi, bool clear)
Cleanup a tls_multi structure and free associated memory allocations.
Functions for managing security parameter state for data channel packets
bool tls_pre_decrypt_lite (const struct tls_auth_standalone *tas, const struct link_socket_actual *from, const struct buffer *buf)
Inspect an incoming packet for which no VPN tunnel is active, and determine whether a new VPN tunnel should be created.
void tls_pre_encrypt (struct tls_multi *multi, struct buffer *buf, struct crypto_options **opt)
Choose the appropriate security parameters with which to process an outgoing packet.
void tls_prepend_opcode_v1 (const struct tls_multi *multi, struct buffer *buf)
Prepend a one-byte OpenVPN data channel P_DATA_V1 opcode to the packet.
void tls_prepend_opcode_v2 (const struct tls_multi *multi, struct buffer *buf)
Prepend an OpenVPN data channel P_DATA_V2 header to the packet.
void tls_post_encrypt (struct tls_multi *multi, struct buffer *buf)
Perform some accounting for the key state used.
Macro Definition Documentation
CONTROL_SEND_ACK_MAX
#define CONTROL_SEND_ACK_MAX 4
Definition at line 79 of file ssl.h.
IV_PROTO_DATA_V2
#define IV_PROTO_DATA_V2 (1<<1)
Support P_DATA_V2.
Definition at line 112 of file ssl.h.
IV_PROTO_REQUEST_PUSH
#define IV_PROTO_REQUEST_PUSH (1<<2)
Assume client will send a push request and server does not need to wait for a push-request to send a push-reply.
Definition at line 116 of file ssl.h.
KEY_EXPANSION_ID
#define KEY_EXPANSION_ID "OpenVPN"
Definition at line 47 of file ssl.h.
KEY_METHOD_2
#define KEY_METHOD_2 2
Definition at line 122 of file ssl.h.
KEY_METHOD_MASK
#define KEY_METHOD_MASK 0x0F
Definition at line 125 of file ssl.h.
P_ACK_V1
#define P_ACK_V1 5 /* acknowledgement for packets received */
Definition at line 58 of file ssl.h.
P_CONTROL_HARD_RESET_CLIENT_V1
#define P_CONTROL_HARD_RESET_CLIENT_V1 1 /* initial key from client, forget previous state */
Definition at line 54 of file ssl.h.
P_CONTROL_HARD_RESET_CLIENT_V2
#define P_CONTROL_HARD_RESET_CLIENT_V2 7 /* initial key from client, forget previous state */
Definition at line 63 of file ssl.h.
P_CONTROL_HARD_RESET_CLIENT_V3
#define P_CONTROL_HARD_RESET_CLIENT_V3 10 /* initial key from client, forget previous state */
Definition at line 67 of file ssl.h.
P_CONTROL_HARD_RESET_SERVER_V1
#define P_CONTROL_HARD_RESET_SERVER_V1 2 /* initial key from server, forget previous state */
Definition at line 55 of file ssl.h.
P_CONTROL_HARD_RESET_SERVER_V2
#define P_CONTROL_HARD_RESET_SERVER_V2 8 /* initial key from server, forget previous state */
Definition at line 64 of file ssl.h.
P_CONTROL_SOFT_RESET_V1
#define P_CONTROL_SOFT_RESET_V1 3 /* new key, graceful transition from old to new key */
Definition at line 56 of file ssl.h.
P_CONTROL_V1
#define P_CONTROL_V1 4 /* control channel packet (usually TLS ciphertext) */
Definition at line 57 of file ssl.h.
P_DATA_V1
#define P_DATA_V1 6 /* data channel packet */
Definition at line 59 of file ssl.h.
P_DATA_V2
#define P_DATA_V2 9 /* data channel packet with peer-id */
Definition at line 60 of file ssl.h.
P_FIRST_OPCODE
#define P_FIRST_OPCODE 3
Definition at line 72 of file ssl.h.
P_KEY_ID_MASK
#define P_KEY_ID_MASK 0x07
Definition at line 50 of file ssl.h.
P_LAST_OPCODE
#define P_LAST_OPCODE 10
Definition at line 73 of file ssl.h.
P_OPCODE_SHIFT
#define P_OPCODE_SHIFT 3
Definition at line 51 of file ssl.h.
PD_SHOW_DATA
#define PD_SHOW_DATA (1<<8)
Definition at line 579 of file ssl.h.
PD_TLS
#define PD_TLS (1<<9)
Definition at line 580 of file ssl.h.
PD_TLS_AUTH_HMAC_SIZE_MASK
#define PD_TLS_AUTH_HMAC_SIZE_MASK 0xFF
Definition at line 578 of file ssl.h.
PD_VERBOSE
#define PD_VERBOSE (1<<10)
Definition at line 581 of file ssl.h.
TLS_MULTI_AUTH_STATUS_INTERVAL
#define TLS_MULTI_AUTH_STATUS_INTERVAL 10
Definition at line 94 of file ssl.h.
TLS_MULTI_HORIZON
#define TLS_MULTI_HORIZON
Value:
                                 2     /* call tls_multi_process frequently for n seconds after
                                 * every packet sent/received action */
Definition at line 91 of file ssl.h.
TLS_MULTI_REFRESH
#define TLS_MULTI_REFRESH 15 /* call tls_multi_process once every n seconds */
Definition at line 90 of file ssl.h.
TLS_OPTIONS_LEN
#define TLS_OPTIONS_LEN 512
Definition at line 101 of file ssl.h.
TLS_RELIABLE_N_REC_BUFFERS
#define TLS_RELIABLE_N_REC_BUFFERS 8
Definition at line 85 of file ssl.h.
TLS_RELIABLE_N_SEND_BUFFERS
#define TLS_RELIABLE_N_SEND_BUFFERS 4 /* also window size for reliability layer */
Definition at line 84 of file ssl.h.
TLSMP_ACTIVE
#define TLSMP_ACTIVE 1
Definition at line 237 of file ssl.h.
TLSMP_INACTIVE
#define TLSMP_INACTIVE 0
Definition at line 236 of file ssl.h.
TLSMP_KILL
#define TLSMP_KILL 2
Definition at line 238 of file ssl.h.
X509_USERNAME_FIELD_DEFAULT
#define X509_USERNAME_FIELD_DEFAULT "CN"
Definition at line 120 of file ssl.h.
Function Documentation
auth_user_pass_setup()
void auth_user_pass_setup (const char * auth_file, const struct static_challenge_info * sc_info)
Definition at line 404 of file ssl.c.
References auth_challenge, auth_token, auth_user_pass, static_challenge_info::challenge_text, user_pass::defined, static_challenge_info::flags, get_user_pass(), get_user_pass_cr(), GET_USER_PASS_DYNAMIC_CHALLENGE, GET_USER_PASS_MANAGEMENT, GET_USER_PASS_STATIC_CHALLENGE, GET_USER_PASS_STATIC_CHALLENGE_ECHO, SC_ECHO, and UP_TYPE_AUTH.
Referenced by init_query_passwords(), and key_method_2_write().
enable_auth_user_pass()
void enable_auth_user_pass ()
Definition at line 398 of file ssl.c.
References auth_user_pass_enabled.
Referenced by init_query_passwords().
extract_x509_field_test()
void extract_x509_field_test (void)
Referenced by init_static().
free_ssl_lib()
void free_ssl_lib (void)
Definition at line 346 of file ssl.c.
References crypto_uninit_lib(), prng_uninit(), and tls_free_lib().
Referenced by uninit_static().
init_ssl()
void init_ssl (const struct options * options, struct tls_root_ctx * ctx, bool in_chroot)
Build master SSL context object that serves for the whole of OpenVPN instantiation.
Definition at line 607 of file ssl.c.
References ASSERT, BSTR, options::ca_file, options::ca_file_inline, options::ca_path, options::cert_file, options::cert_file_inline, options::chroot_dir, options::cipher_list, options::cipher_list_tls13, options::crl_file, options::crl_file_inline, options::cryptoapi_cert, options::dh_file, options::dh_file_inline, options::ecdh_curve, options::extra_certs_file, options::extra_certs_file_inline, gc_free(), gc_new(), M_WARN, options::management_certificate, options::management_flags, management_query_cert(), MF_EXTERNAL_CERT, MF_EXTERNAL_KEY, msg, options::pkcs12_file, options::pkcs12_file_inline, prepend_dir(), options::priv_key_file, options::priv_key_file_inline, options::ssl_flags, SSLF_CRL_VERIFY_DIR, options::tls_cert_profile, tls_clear_error(), tls_ctx_check_cert_time(), tls_ctx_client_new(), tls_ctx_free(), tls_ctx_load_ca(), tls_ctx_load_cert_file(), tls_ctx_load_cryptoapi(), tls_ctx_load_dh_params(), tls_ctx_load_ecdh_params(), tls_ctx_load_extra_certs(), tls_ctx_load_pkcs12(), tls_ctx_load_priv_file(), tls_ctx_reload_crl(), tls_ctx_restrict_ciphers(), tls_ctx_restrict_ciphers_tls13(), tls_ctx_server_new(), tls_ctx_set_cert_profile(), tls_ctx_set_options(), tls_ctx_set_tls_groups(), tls_ctx_use_management_external_key(), options::tls_groups, and options::tls_server.
Referenced by do_init_crypto_tls_c1().
init_ssl_lib()
void init_ssl_lib (void)
Definition at line 338 of file ssl.c.
References crypto_init_lib(), and tls_init_lib().
Referenced by init_static().
is_hard_reset_method2()
bool is_hard_reset_method2 (int op)
Given a key_method, return true if opcode represents the one of the hard_reset op codes for key-method 2.
Definition at line 881 of file ssl.c.
References P_CONTROL_HARD_RESET_CLIENT_V2, P_CONTROL_HARD_RESET_CLIENT_V3, and P_CONTROL_HARD_RESET_SERVER_V2.
Referenced by process_incoming_link_part1(), and tls_pre_decrypt().
pem_password_setup()
void pem_password_setup (const char * auth_file)
Definition at line 362 of file ssl.c.
References get_user_pass(), GET_USER_PASS_MANAGEMENT, GET_USER_PASS_PASSWORD_ONLY, passbuf, user_pass::password, and UP_TYPE_PRIVATE_KEY.
Referenced by init_query_passwords(), and pem_password_callback().
protocol_dump()
const char* protocol_dump (struct buffer * buffer, unsigned int flags, struct gc_arena * gc)
Definition at line 4024 of file ssl.c.
References alloc_buf_gc(), ASSERT, BLEN, BPTR, BSTR, buf_printf(), buf_read(), format_hex(), buffer::len, MAX_HMAC_KEY_LENGTH, ntohpid, P_ACK_V1, P_DATA_V1, P_DATA_V2, P_KEY_ID_MASK, P_OPCODE_SHIFT, packet_id_format, packet_id_net_print(), packet_id_read(), packet_opcode_name(), PD_SHOW_DATA, PD_TLS, PD_TLS_AUTH_HMAC_SIZE_MASK, PD_VERBOSE, reliable_ack_print(), session_id_print(), and session_id_read().
show_available_tls_ciphers()
void show_available_tls_ciphers (const char * cipher_list, const char * cipher_list_tls13, const char * tls_cert_profile)
Definition at line 3997 of file ssl.c.
References show_available_tls_ciphers_list(), TLS_VER_1_3, and tls_version_max().
Referenced by print_openssl_info().
ssl_clean_auth_token()
bool ssl_clean_auth_token (void)
Definition at line 465 of file ssl.c.
References auth_token, user_pass::defined, and purge_user_pass().
Referenced by man_forget_passwords(), man_reset_client_socket(), and receive_auth_failed().
ssl_purge_auth()
void ssl_purge_auth (const bool auth_user_pass_only)
Definition at line 476 of file ssl.c.
References auth_user_pass, passbuf, purge_user_pass(), and ssl_purge_auth_challenge().
Referenced by do_init_crypto_tls_c1(), man_forget_passwords(), man_reset_client_socket(), receive_auth_failed(), and server_pushed_signal().
ssl_purge_auth_challenge()
void ssl_purge_auth_challenge (void)
Definition at line 494 of file ssl.c.
References auth_challenge.
Referenced by ssl_purge_auth(), and ssl_put_auth_challenge().
ssl_put_auth_challenge()
void ssl_put_auth_challenge (const char * cr_str)
Definition at line 501 of file ssl.c.
References auth_challenge, ssl_purge_auth_challenge(), and string_alloc().
Referenced by receive_auth_failed().
ssl_set_auth_nocache()
void ssl_set_auth_nocache (void)
Definition at line 440 of file ssl.c.
References auth_user_pass, user_pass::nocache, and passbuf.
Referenced by add_option().
ssl_set_auth_token()
void ssl_set_auth_token (const char * token)
Definition at line 450 of file ssl.c.
References auth_token, auth_user_pass, and set_auth_token().
Referenced by add_option().
ssl_set_auth_token_user()
void ssl_set_auth_token_user (const char * username)
Definition at line 456 of file ssl.c.
References auth_token, set_auth_token_user(), and user_pass::username.
Referenced by add_option().
tls_adjust_frame_parameters()
void tls_adjust_frame_parameters (struct frame * frame)
Definition at line 305 of file ssl.c.
References frame_add_to_extra_frame().
Referenced by do_init_crypto_tls(), and tls_init_control_channel_frame_parameters().
tls_initial_packet_received()
static bool tls_initial_packet_received (const struct tls_multi * multi) inline static
Definition at line 536 of file ssl.h.
References tls_multi::n_sessions.
Referenced by check_server_poll_timeout(), and process_outgoing_link().
tls_multi_process()
int tls_multi_process (struct tls_multi * multi, struct buffer * to_link, struct link_socket_actual ** to_link_addr, struct link_socket_info * to_link_socket_info, interval_t * wakeup)
Definition at line 3021 of file ssl.c.
References link_socket_addr::actual, D_TLS_DEBUG, D_TLS_DEBUG_LOW, DECRYPT_KEY_ENABLED, dmsg, gc_free(), gc_new(), tls_options::gremlin, session::key, tls_session::key, tls_multi::key_scan, KS_LAME_DUCK, KS_PRIMARY, lame_duck_must_die(), link_socket_actual_defined(), link_socket_info::lsa, move_session(), msg, tls_multi::n_hard_errors, tls_multi::n_soft_errors, tls_multi::opt, perf_pop(), perf_push(), PERF_TLS_MULTI_PROCESS, print_link_socket_actual(), key_state::remote_addr, reset_session(), S_ACTIVE, S_ERROR, S_INITIAL, tls_multi::session, session_id_print(), key_state::session_id_remote, tls_options::single_session, SIZE, key_state::state, state_name(), TLS_AUTHENTICATION_FAILED, tls_authentication_status(), TLS_AUTHENTICATION_SUCCEEDED, tls_clear_error(), TLS_MULTI_AUTH_STATUS_INTERVAL, tls_process(), tls_session_free(), TLSMP_ACTIVE, TLSMP_INACTIVE, TLSMP_KILL, TM_ACTIVE, TM_LAME_DUCK, TM_SIZE, TM_UNTRUSTED, tls_multi::to_link_addr, and update_time().
Referenced by check_tls().
tls_pre_decrypt()
bool tls_pre_decrypt (struct tls_multi * multi, const struct link_socket_actual * from, struct buffer * buf, struct crypto_options ** opt, bool floated, const uint8_t ** ad_start)
Determine whether an incoming packet is a data channel or control channel packet, and process accordingly.
When OpenVPN is in TLS mode, this is the first function to process an incoming packet. It inspects the packet's one-byte header which contains the packet's opcode and key ID. Depending on the opcode, the packet is processed as a data channel or as a control channel packet.
Data channel packets
If the opcode indicates the packet is a data channel packet, then the packet's key ID is used to find the local TLS state it is associated with. This state is checked whether it is active, authenticated, and its remote peer is the source of this packet. If these checks passed, the state's security parameters are loaded into the opt crypto options so that openvpn_decrypt() can later use them to authenticate and decrypt the packet.
This function then returns false. The buf buffer has not been modified, except for removing the header.
Control channel packets
If the opcode indicates the packet is a control channel packet, then this function will process it based on its plaintext header. depending on the packet's opcode and session ID this function determines if it is destined for an active TLS session, or whether a new TLS session should be started. This function also initiates data channel session key renegotiation if the received opcode requests that.
If the incoming packet is destined for an active TLS session, then the packet is inserted into the Reliability Layer and will be handled later.
Parameters
multi - The TLS multi structure associated with the VPN tunnel of this packet.
from - The source address of the packet.
buf - A buffer structure containing the incoming packet.
opt - Returns a crypto options structure with the appropriate security parameters to handle the packet if it is a data channel packet.
ad_start - Returns a pointer to the start of the authenticated data of of this packet
Returns
True if the packet is a control channel packet that has been processed successfully.
False if the packet is a data channel packet, or if an error occurred during processing of a control channel packet.
Definition at line 3303 of file ssl.c.
References ASSERT, BPTR, buf_advance(), buf_copy(), D_MULTI_DROPPED, D_TLS_DEBUG, D_TLS_DEBUG_LOW, D_TLS_ERRORS, DECRYPT_KEY_ENABLED, dmsg, gc_free(), gc_new(), handle_data_channel_packet(), is_hard_reset_method2(), session::key, key_state::key_id, key_state_soft_reset(), KS_PRIMARY, reliable_ack::len, buffer::len, link_socket_actual_match(), management_set_state(), msg, tls_multi::n_sessions, tls_multi::n_soft_errors, OPENVPN_STATE_AUTH, tls_multi::opt, P_ACK_V1, P_CONTROL_HARD_RESET_CLIENT_V1, P_CONTROL_HARD_RESET_CLIENT_V2, P_CONTROL_HARD_RESET_CLIENT_V3, P_CONTROL_HARD_RESET_SERVER_V1, P_CONTROL_HARD_RESET_SERVER_V2, P_CONTROL_SOFT_RESET_V1, P_DATA_V1, P_DATA_V2, P_KEY_ID_MASK, P_LAST_OPCODE, P_OPCODE_SHIFT, packet_opcode_name(), print_key_id(), print_link_socket_actual(), read_control_auth(), key_state::rec_ack, key_state::rec_reliable, reliable_ack_acknowledge_packet_id(), reliable_ack_read(), reliable_ack_read_packet_id(), reliable_can_get(), reliable_get_buf(), reliable_mark_active_incoming(), reliable_not_replay(), reliable_schedule_now(), reliable_send_purge(), reliable_wont_break_sequentiality(), key_state::remote_addr, S_ERROR, S_UNDEF, key_state::send_reliable, tls_options::server, tls_multi::session, session_id_defined(), session_id_equal(), session_id_print(), session_id_read(), key_state::session_id_remote, tls_options::single_session, key_state::state, state_name(), tls_clear_error(), TM_ACTIVE, TM_LAME_DUCK, TM_SIZE, and TM_UNTRUSTED.
Referenced by process_incoming_link_part1().
tls_rec_payload()
bool tls_rec_payload (struct tls_multi * multi, struct buffer * buf)
Definition at line 3940 of file ssl.c.
References ASSERT, BLEN, buf_copy(), session::key, KS_PRIMARY, buffer::len, key_state::plaintext_read_buf, S_ACTIVE, tls_multi::session, key_state::state, tls_clear_error(), and TM_ACTIVE.
Referenced by check_incoming_control_channel().
tls_send_payload()
bool tls_send_payload (struct tls_multi * multi, const uint8_t * data, int size)
Definition at line 3901 of file ssl.c.
References ASSERT, buffer_list_new(), buffer_list_push_data(), session::key, key_state_write_plaintext_const(), KS_PRIMARY, key_state::ks_ssl, key_state::paybuf, S_ACTIVE, tls_multi::session, key_state::state, tls_clear_error(), and TM_ACTIVE.
Referenced by send_control_channel_string_dowork().
tls_session_update_crypto_params()
bool tls_session_update_crypto_params (struct tls_session * session, struct options * options, struct frame * frame, struct frame * frame_fragment)
Update TLS session crypto parameters (cipher and auth) and derive data channel keys based on the supplied options.
Does nothing if keys are already generated.
Parameters
session The TLS session to update.
options The options to use when updating session.
frame The frame options for this session (frame overhead is adjusted based on the selected cipher/auth).
frame_fragment The fragment frame options.
Returns
true if updating succeeded or keys are already generated, false otherwise.
Definition at line 1946 of file ssl.c.
References options::authname, options::ce, cipher_kt_mode_ofb_cfb(), options::ciphername, CO_PACKET_ID_LONG_FORM, crypto_adjust_frame_parameters(), crypto_max_overhead(), D_HANDSHAKE, D_MTU_INFO, D_TLS_ERRORS, options::enable_ncp_fallback, connection_entry::fragment, frame_finalize(), frame_init_mssfix(), frame_print(), frame_remove_from_extra_frame(), frame_set_mtu_dynamic(), init_key_type(), session::key, options::keysize, KS_PRIMARY, connection_entry::link_mtu, connection_entry::link_mtu_defined, msg, options::ncp_ciphers, options::replay, SET_MTU_UPPER_BOUND, streq, tls_item_in_cipher_list(), tls_session_generate_data_channel_keys(), connection_entry::tun_mtu, and connection_entry::tun_mtu_defined.
Referenced by do_deferred_options(), and multi_client_generate_tls_keys().
tls_set_single_session()
static void tls_set_single_session (struct tls_multi * multi) inline static
Definition at line 567 of file ssl.h.
References tls_multi::opt, and tls_options::single_session.
Referenced by schedule_exit().
tls_test_auth_deferred_interval()
static bool tls_test_auth_deferred_interval (const struct tls_multi * multi) inline static
Definition at line 542 of file ssl.h.
References key_state::auth_deferred_expire, tls_session::key, KS_PRIMARY, now, tls_multi::session, and TM_ACTIVE.
tls_test_payload_len()
static int tls_test_payload_len (const struct tls_multi * multi) inline static
Definition at line 553 of file ssl.h.
References BLEN, tls_session::key, KS_PRIMARY, key_state::plaintext_read_buf, S_ACTIVE, tls_multi::session, key_state::state, and TM_ACTIVE.
Referenced by check_incoming_control_channel(), and pre_select().
tls_update_remote_addr()
void tls_update_remote_addr (struct tls_multi * multi, const struct link_socket_actual * addr)
Updates remote address in TLS sessions.
Parameters
multi - Tunnel to update
addr - new address
Definition at line 3969 of file ssl.c.
References D_TLS_KEYSELECT, dmsg, gc_free(), gc_new(), session::key, KS_SIZE, link_socket_actual_defined(), link_socket_actual_match(), print_link_socket_actual(), key_state::remote_addr, tls_multi::session, and TM_SIZE.
Referenced by multi_process_float().
tls_wrap_free()
static void tls_wrap_free (struct tls_wrap_ctx * tls_wrap) inline static
Free the elements of a tls_wrap_ctx structure.
Definition at line 519 of file ssl.h.
References tls_wrap_ctx::cleanup_key_ctx, free_buf(), free_key_ctx_bi(), crypto_options::key_ctx_bi, tls_wrap_ctx::opt, crypto_options::packet_id, packet_id_free(), packet_id_initialized(), tls_wrap_ctx::tls_crypt_v2_metadata, tls_auth_standalone::tls_wrap, and tls_wrap_ctx::work.
Referenced by tls_crypt_v2_wrap_unwrap_max_metadata(), and tls_session_free().