OpenVPN: src/openvpn/status.h File Reference
status.h File Reference
#include "interval.h"
Data Structures
struct virtual_output
struct status_output
Macros
#define STATUS_OUTPUT_READ (1<<0)
#define STATUS_OUTPUT_WRITE (1<<1)
Functions
static void virtual_output_print (const struct virtual_output *vo, const unsigned int flags, const char *str)
struct status_output * status_open (const char *filename, const int refresh_freq, const int msglevel, const struct virtual_output *vout, const unsigned int flags)
bool status_trigger (struct status_output *so)
void status_reset (struct status_output *so)
void status_flush (struct status_output *so)
bool status_close (struct status_output *so)
void status_printf (struct status_output *so, const char *format,...)
bool status_read (struct status_output *so, struct buffer *buf)
static unsigned int status_rw_flags (const struct status_output *so)
Macro Definition Documentation
STATUS_OUTPUT_READ
#define STATUS_OUTPUT_READ (1<<0)
Definition at line 50 of file status.h.
STATUS_OUTPUT_WRITE
#define STATUS_OUTPUT_WRITE (1<<1)
Definition at line 51 of file status.h.
Function Documentation
status_close()
bool status_close (struct status_output * so)
Definition at line 190 of file status.c.
References buf_defined(), status_output::errors, status_output::fd, status_output::filename, free_buf(), and status_output::read_buf.
Referenced by do_close_status_output(), ifconfig_pool_msg(), ifconfig_pool_persist_close(), init_static(), man_process_command(), multi_process_signal(), process_sigusr2(), and verify_user_pass_script().
status_flush()
void status_flush (struct status_output * so)
Definition at line 159 of file status.c.
References ASSERT, buf_defined(), buf_init, status_output::fd, status_output::flags, M_ERRNO, M_WARN, msg, status_output::read_buf, and STATUS_OUTPUT_WRITE.
Referenced by ifconfig_pool_write(), multi_print_status(), and print_status().
status_open()
struct status_output* status_open (const char * filename, const int refresh_freq, const int msglevel, const struct virtual_output * vout, const unsigned int flags)
Definition at line 63 of file status.c.
References alloc_buf(), ALLOC_OBJ_CLEAR, ASSERT, buf_reset(), status_output::errors, status_output::et, event_timeout_clear(), event_timeout_init(), status_output::fd, status_output::filename, status_output::flags, M_WARN, msg, status_output::msglevel, platform_open(), print_status_mode(), status_output::read_buf, S_IRUSR, S_IWUSR, set_cloexec(), STATUS_OUTPUT_READ, STATUS_OUTPUT_WRITE, string_alloc(), and status_output::vout.
Referenced by do_open_status_output(), ifconfig_pool_msg(), ifconfig_pool_persist_init(), init_static(), man_process_command(), multi_process_signal(), process_sigusr2(), and verify_user_pass_script().
status_printf()
void status_printf (struct status_output * so, const char * format, ...)
Definition at line 226 of file status.c.
References virtual_output::arg, chomp(), status_output::errors, status_output::fd, status_output::flags, virtual_output::flags_default, virtual_output::func, msg, status_output::msglevel, STATUS_OUTPUT_WRITE, STATUS_PRINTF_MAXLEN, status_output::vout, and write.
Referenced by ifconfig_pool_list(), ifconfig_pool_msg(), init_static(), multi_print_status(), print_status(), and verify_user_pass_script().
status_read()
bool status_read (struct status_output * so, struct buffer * buf)
Definition at line 272 of file status.c.
References ASSERT, BCAP, BPTR, buf_defined(), buf_inc_len(), buf_init, buf_null_terminate(), buf_read_u8(), buf_write_u8(), status_output::fd, status_output::flags, read, status_output::read_buf, and STATUS_OUTPUT_READ.
Referenced by ifconfig_pool_read().
status_reset()
void status_reset (struct status_output * so)
Definition at line 150 of file status.c.
References status_output::fd.
Referenced by ifconfig_pool_write(), multi_print_status(), and print_status().
status_rw_flags()
static unsigned int status_rw_flags (const struct status_output * so) inline static
Definition at line 93 of file status.h.
References status_output::flags.
Referenced by ifconfig_pool_write().
status_trigger()
bool status_trigger (struct status_output * so)
Definition at line 135 of file status.c.
References CLEAR, status_output::et, ETT_DEFAULT, and event_timeout_trigger().
Referenced by ifconfig_pool_write_trigger(), and multi_process_per_second_timers_dowork().
virtual_output_print()
static void virtual_output_print (const struct virtual_output * vo, const unsigned int flags, const char * str) inline static
Definition at line 39 of file status.h.
References virtual_output::arg, and virtual_output::func.
Referenced by x_msg_va().