OpenVPN: virtual_output Struct Reference
virtual_output Struct Reference
#include <status.h>
Data Fields
void * arg
unsigned int flags_default
void(* func)(void *arg, const unsigned int flags, const char *str)
Detailed Description
Definition at line 32 of file status.h.
Field Documentation
arg
void* virtual_output::arg
Definition at line 33 of file status.h.
Referenced by man_persist_init(), status_printf(), and virtual_output_print().
flags_default
unsigned int virtual_output::flags_default
Definition at line 34 of file status.h.
Referenced by man_persist_init(), and status_printf().
func
void(* virtual_output::func) (void *arg, const unsigned int flags, const char *str)
Definition at line 35 of file status.h.
Referenced by man_persist_init(), status_printf(), and virtual_output_print().
The documentation for this struct was generated from the following file:
src/openvpn/status.h