OpenVPN: management_callback Struct Reference
management_callback Struct Reference
#include <manage.h>
Data Fields
void * arg
unsigned int flags
void(* status)(void *arg, const int version, struct status_output *so)
void(* show_net)(void *arg, const int msglevel)
int(* kill_by_cn)(void *arg, const char *common_name)
int(* kill_by_addr)(void *arg, const in_addr_t addr, const int port)
void(* delete_event)(void *arg, event_t event)
int(* n_clients)(void *arg)
bool(* send_cc_message)(void *arg, const char *message, const char *parameter)
bool(* proxy_cmd)(void *arg, const char **p)
bool(* remote_cmd)(void *arg, const char **p)
Detailed Description
Definition at line 154 of file manage.h.
Field Documentation
arg
void* management_callback::arg
Definition at line 156 of file manage.h.
Referenced by in_extra_dispatch(), init_management_callback_multi(), init_management_callback_p2p(), man_close_socket(), man_kill(), man_load_stats(), man_net(), man_output_extra_env(), man_proxy(), man_remote(), man_send_cc_message(), and man_status().
delete_event
void(* management_callback::delete_event) (void *arg, event_t event)
Definition at line 165 of file manage.h.
Referenced by init_management_callback_multi(), and man_close_socket().
flags
unsigned int management_callback::flags
Definition at line 159 of file manage.h.
Referenced by init_instance_handle_signals(), init_management_callback_multi(), management_bytes_in(), management_bytes_out(), and open_management().
kill_by_addr
int(* management_callback::kill_by_addr) (void *arg, const in_addr_t addr, const int port)
Definition at line 164 of file manage.h.
Referenced by init_management_callback_multi(), and man_kill().
kill_by_cn
int(* management_callback::kill_by_cn) (void *arg, const char *common_name)
Definition at line 163 of file manage.h.
Referenced by init_management_callback_multi(), and man_kill().
n_clients
int(* management_callback::n_clients) (void *arg)
Definition at line 166 of file manage.h.
Referenced by init_management_callback_multi(), man_load_stats(), and man_output_extra_env().
proxy_cmd
bool(* management_callback::proxy_cmd) (void *arg, const char **p)
Definition at line 187 of file manage.h.
Referenced by init_management_callback_p2p(), and man_proxy().
remote_cmd
bool(* management_callback::remote_cmd) (void *arg, const char **p)
Definition at line 188 of file manage.h.
Referenced by init_management_callback_p2p(), and man_remote().
send_cc_message
bool(* management_callback::send_cc_message) (void *arg, const char *message, const char *parameter)
Definition at line 167 of file manage.h.
Referenced by init_management_callback_p2p(), and man_send_cc_message().
show_net
void(* management_callback::show_net) (void *arg, const int msglevel)
Definition at line 162 of file manage.h.
Referenced by init_management_callback_multi(), init_management_callback_p2p(), and man_net().
status
void(* management_callback::status) (void *arg, const int version, struct status_output *so)
Definition at line 161 of file manage.h.
Referenced by init_management_callback_multi(), init_management_callback_p2p(), and man_status().
The documentation for this struct was generated from the following file:
src/openvpn/manage.h