OpenVPN: event_set_functions Struct Reference
event_set_functions Struct Reference
#include <event.h>
Data Fields
void(* free)(struct event_set *es)
void(* reset)(struct event_set *es)
void(* del)(struct event_set *es, event_t event)
void(* ctl)(struct event_set *es, event_t event, unsigned int rwflags, void *arg)
int(* wait)(struct event_set *es, const struct timeval *tv, struct event_set_return *out, int outlen)
Detailed Description
Definition at line 61 of file event.h.
Field Documentation
ctl
void(* event_set_functions::ctl) (struct event_set *es, event_t event, unsigned int rwflags, void *arg)
Definition at line 66 of file event.h.
Referenced by event_ctl(), and we_init().
del
void(* event_set_functions::del) (struct event_set *es, event_t event)
Definition at line 65 of file event.h.
Referenced by event_del(), and we_init().
free
void(* event_set_functions::free) (struct event_set *es)
Definition at line 63 of file event.h.
Referenced by event_free(), and we_init().
reset
void(* event_set_functions::reset) (struct event_set *es)
Definition at line 64 of file event.h.
Referenced by event_reset(), and we_init().
wait
int(* event_set_functions::wait) (struct event_set *es, const struct timeval *tv, struct event_set_return *out, int outlen)
Definition at line 74 of file event.h.
Referenced by event_wait(), and we_init().
The documentation for this struct was generated from the following file:
src/openvpn/event.h