OpenVPN: src/openvpn/syshead.h File Reference
syshead.h File Reference
#include "compat.h"
#include <stdbool.h>
#include <windows.h>
#include <winsock2.h>
#include <tlhelp32.h>
#include <naptypes.h>
#include <ntddndis.h>
#include <iphlpapi.h>
#include <wininet.h>
#include <shellapi.h>
#include <ws2tcpip.h>
Macros
#define likely(x) (x)
#define unlikely(x) (x)
#define sleep(x) Sleep((x)*1000)
#define random rand
#define srandom srand
#define PASSTOS_CAPABILITY 0
#define HAVE_GETTIMEOFDAY_NANOSECONDS 1
#define EXTENDED_SOCKET_ERROR_CAPABILITY 0
#define ENABLE_IP_PKTINFO 0
#define SOL_IP IPPROTO_IP
#define SYSLOG_CAPABILITY 0
#define O_BINARY 0
#define OS_SPECIFIC_DIRSEP '\\'
#define SOCKET_UNDEFINED (INVALID_SOCKET)
#define USE_64_BIT_COUNTERS
#define P2MP 1
#define PORT_SHARE 0
#define UNIX_SOCK_SUPPORT 0
#define NTLM 1
#define PROXY_DIGEST_AUTH 1
#define ENABLE_CRYPTOAPI
#define POLL 0
#define EPOLL 0
#define TIME_BACKTRACK_PROTECTION 1
#define ENABLE_FEATURE_SHAPER 1
Typedefs
typedef int MIB_TCP_STATE
typedef unsigned short sa_family_t
typedef SOCKET socket_descriptor_t
Functions
static int socket_defined (const socket_descriptor_t sd)
Macro Definition Documentation
ENABLE_CRYPTOAPI
#define ENABLE_CRYPTOAPI
Definition at line 586 of file syshead.h.
ENABLE_FEATURE_SHAPER
#define ENABLE_FEATURE_SHAPER 1
Definition at line 625 of file syshead.h.
ENABLE_IP_PKTINFO
#define ENABLE_IP_PKTINFO 0
Definition at line 433 of file syshead.h.
EPOLL
#define EPOLL 0
Definition at line 604 of file syshead.h.
EXTENDED_SOCKET_ERROR_CAPABILITY
#define EXTENDED_SOCKET_ERROR_CAPABILITY 0
Definition at line 423 of file syshead.h.
HAVE_GETTIMEOFDAY_NANOSECONDS
#define HAVE_GETTIMEOFDAY_NANOSECONDS 1
Definition at line 414 of file syshead.h.
likely
#define likely (x) (x)
Definition at line 35 of file syshead.h.
NTLM
#define NTLM 1
Definition at line 575 of file syshead.h.
O_BINARY
#define O_BINARY 0
Definition at line 472 of file syshead.h.
OS_SPECIFIC_DIRSEP
#define OS_SPECIFIC_DIRSEP '\\'
Definition at line 479 of file syshead.h.
P2MP
#define P2MP 1
Definition at line 519 of file syshead.h.
PASSTOS_CAPABILITY
#define PASSTOS_CAPABILITY 0
Definition at line 407 of file syshead.h.
POLL
#define POLL 0
Definition at line 595 of file syshead.h.
PORT_SHARE
#define PORT_SHARE 0
Definition at line 530 of file syshead.h.
PROXY_DIGEST_AUTH
#define PROXY_DIGEST_AUTH 1
Definition at line 580 of file syshead.h.
random
#define random rand
Definition at line 44 of file syshead.h.
sleep
#define sleep (x) Sleep((x)*1000)
Definition at line 43 of file syshead.h.
SOCKET_UNDEFINED
#define SOCKET_UNDEFINED (INVALID_SOCKET)
Definition at line 488 of file syshead.h.
SOL_IP
#define SOL_IP IPPROTO_IP
Definition at line 441 of file syshead.h.
srandom
#define srandom srand
Definition at line 45 of file syshead.h.
SYSLOG_CAPABILITY
#define SYSLOG_CAPABILITY 0
Definition at line 465 of file syshead.h.
TIME_BACKTRACK_PROTECTION
#define TIME_BACKTRACK_PROTECTION 1
Definition at line 618 of file syshead.h.
UNIX_SOCK_SUPPORT
#define UNIX_SOCK_SUPPORT 0
Definition at line 569 of file syshead.h.
unlikely
#define unlikely (x) (x)
Definition at line 36 of file syshead.h.
USE_64_BIT_COUNTERS
#define USE_64_BIT_COUNTERS
Definition at line 504 of file syshead.h.
Typedef Documentation
MIB_TCP_STATE
typedef int MIB_TCP_STATE
Definition at line 369 of file syshead.h.
sa_family_t
typedef unsigned short sa_family_t
Definition at line 448 of file syshead.h.
socket_descriptor_t
typedef SOCKET socket_descriptor_t
Definition at line 489 of file syshead.h.
Function Documentation
socket_defined()
static int socket_defined (const socket_descriptor_t sd) inline static
Definition at line 496 of file syshead.h.
References SOCKET_UNDEFINED.
Referenced by close_net_event_win32(), link_socket_close(), link_socket_init_phase1(), link_socket_update_buffer_sizes(), link_socket_update_flags(), man_accept(), man_connection_close(), man_record_peer_info(), man_reset_client_socket(), man_update_io_state(), net_event_win32_start(), phase2_tcp_server(), sd_close(), socket_do_accept(), and socket_listen_accept().