OpenVPN: tests/unit_tests/openvpn/test_packet_id.c File Reference
test_packet_id.c File Reference
#include "syshead.h"
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>
#include "packet_id.h"
#include "mock_msg.h"
Data Structures
struct test_packet_id_write_data
Functions
static int test_packet_id_write_setup (void **state)
static int test_packet_id_write_teardown (void **state)
static void test_packet_id_write_short (void **state)
static void test_packet_id_write_long (void **state)
static void test_packet_id_write_short_prepend (void **state)
static void test_packet_id_write_long_prepend (void **state)
static void test_packet_id_write_short_wrap (void **state)
static void test_packet_id_write_long_wrap (void **state)
int main (void)
Function Documentation
main()
int main (void)
Definition at line 160 of file test_packet_id.c.
References test_packet_id_write_long(), test_packet_id_write_long_prepend(), test_packet_id_write_long_wrap(), test_packet_id_write_setup(), test_packet_id_write_short(), test_packet_id_write_short_prepend(), test_packet_id_write_short_wrap(), and test_packet_id_write_teardown().
test_packet_id_write_long()
static void test_packet_id_write_long (void ** state) static
Definition at line 89 of file test_packet_id.c.
References test_packet_id_write_data::buf_id, test_packet_id_write_data::buf_time, packet_id_send::id, now, packet_id_write(), test_packet_id_write_data::pis, test_packet_id_write_data::test_buf, test_packet_id_write_data::test_buf_data, and packet_id_send::time.
Referenced by main().
test_packet_id_write_long_prepend()
static void test_packet_id_write_long_prepend (void ** state) static
Definition at line 115 of file test_packet_id.c.
References test_packet_id_write_data::buf_id, test_packet_id_write_data::buf_time, packet_id_send::id, now, buffer::offset, packet_id_write(), test_packet_id_write_data::pis, test_packet_id_write_data::test_buf, test_packet_id_write_data::test_buf_data, and packet_id_send::time.
Referenced by main().
test_packet_id_write_long_wrap()
static void test_packet_id_write_long_wrap (void ** state) static
Definition at line 138 of file test_packet_id.c.
References test_packet_id_write_data::buf_id, test_packet_id_write_data::buf_time, packet_id_send::id, now, packet_id_write(), test_packet_id_write_data::pis, test_packet_id_write_data::test_buf, test_packet_id_write_data::test_buf_data, and packet_id_send::time.
Referenced by main().
test_packet_id_write_setup()
static int test_packet_id_write_setup (void ** state) static
Definition at line 52 of file test_packet_id.c.
References buffer::capacity, buffer::data, test_packet_id_write_data::test_buf, and test_packet_id_write_data::test_buf_data.
Referenced by main().
test_packet_id_write_short()
static void test_packet_id_write_short (void ** state) static
Definition at line 77 of file test_packet_id.c.
References test_packet_id_write_data::buf_id, test_packet_id_write_data::buf_time, packet_id_send::id, now, packet_id_write(), test_packet_id_write_data::pis, test_packet_id_write_data::test_buf, and test_packet_id_write_data::test_buf_data.
Referenced by main().
test_packet_id_write_short_prepend()
static void test_packet_id_write_short_prepend (void ** state) static
Definition at line 102 of file test_packet_id.c.
References test_packet_id_write_data::buf_id, test_packet_id_write_data::buf_time, packet_id_send::id, now, buffer::offset, packet_id_write(), test_packet_id_write_data::pis, test_packet_id_write_data::test_buf, and test_packet_id_write_data::test_buf_data.
Referenced by main().
test_packet_id_write_short_wrap()
static void test_packet_id_write_short_wrap (void ** state) static
Definition at line 129 of file test_packet_id.c.
References packet_id_send::id, packet_id_write(), test_packet_id_write_data::pis, and test_packet_id_write_data::test_buf.
Referenced by main().
test_packet_id_write_teardown()
static int test_packet_id_write_teardown (void ** state) static
Definition at line 70 of file test_packet_id.c.
Referenced by main().