OpenVPN: tests/unit_tests/openvpn/test_ncp.c File Reference
test_ncp.c File Reference
#include "syshead.h"
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <setjmp.h>
#include <cmocka.h>
#include "ssl_ncp.c"
Functions
static void test_check_ncp_ciphers_list (void **state)
static void test_extract_client_ciphers (void **state)
static void test_poor_man (void **state)
static void test_ncp_best (void **state)
int main (void)
Variables
const char * bf_chacha = "BF-CBC:CHACHA20-POLY1305"
const char * aes_chacha = "AES-128-CBC:CHACHA20-POLY1305"
const char * aes_ciphers = "AES-256-GCM:AES-128-GCM"
const struct CMUnitTest ncp_tests []
Function Documentation
main()
int main (void)
Definition at line 259 of file test_ncp.c.
References ncp_tests.
test_check_ncp_ciphers_list()
static void test_check_ncp_ciphers_list (void ** state) static
Definition at line 49 of file test_ncp.c.
References aes_chacha, aes_ciphers, bf_chacha, cipher_kt_get(), gc_free(), gc_new(), and mutate_ncp_cipher_list().
test_extract_client_ciphers()
static void test_extract_client_ciphers (void ** state) static
Definition at line 123 of file test_ncp.c.
References aes_ciphers, gc_free(), gc_new(), tls_peer_ncp_list(), and tls_peer_supports_ncp().
test_ncp_best()
static void test_ncp_best (void ** state) static
Definition at line 211 of file test_ncp.c.
References gc_free(), gc_new(), and ncp_get_best_cipher().
test_poor_man()
static void test_poor_man (void ** state) static
Definition at line 162 of file test_ncp.c.
References gc_free(), gc_new(), and ncp_get_best_cipher().
Variable Documentation
aes_chacha
const char* aes_chacha = "AES-128-CBC:CHACHA20-POLY1305"
Definition at line 45 of file test_ncp.c.
Referenced by test_check_ncp_ciphers_list().
aes_ciphers
const char* aes_ciphers = "AES-256-GCM:AES-128-GCM"
Definition at line 46 of file test_ncp.c.
Referenced by test_check_ncp_ciphers_list(), and test_extract_client_ciphers().
bf_chacha
const char* bf_chacha = "BF-CBC:CHACHA20-POLY1305"
Definition at line 44 of file test_ncp.c.
Referenced by test_check_ncp_ciphers_list().
ncp_tests
const struct CMUnitTest ncp_tests[]
Initial value:
= {
    cmocka_unit_test(test_check_ncp_ciphers_list),
    cmocka_unit_test(test_extract_client_ciphers),
    cmocka_unit_test(test_poor_man),
    cmocka_unit_test(test_ncp_best)
}
Definition at line 250 of file test_ncp.c.
Referenced by main().