OpenVPN: tests/unit_tests/example_test/test.c File Reference
test.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <setjmp.h>
#include <cmocka.h>
Functions
static int setup (void **state)
static int teardown (void **state)
static void null_test_success (void **state)
static void int_test_success (void **state)
static void failing_test (void **state)
int main (void)
Function Documentation
failing_test()
static void failing_test (void ** state) static
Definition at line 42 of file test.c.
int_test_success()
static void int_test_success (void ** state) static
Definition at line 35 of file test.c.
Referenced by main().
main()
int main (void)
Definition at line 49 of file test.c.
References int_test_success(), null_test_success(), setup(), and teardown().
null_test_success()
static void null_test_success (void ** state) static
Definition at line 29 of file test.c.
Referenced by main().
setup()
static int setup (void ** state) static
Definition at line 10 of file test.c.
Referenced by main().
teardown()
static int teardown (void ** state) static
Definition at line 21 of file test.c.
Referenced by main().