OpenVPN: tests/unit_tests/openvpn/test_networking.c File Reference
test_networking.c File Reference
#include "config.h"
#include "syshead.h"
#include "networking.h"
Functions
static int net__iface_up (bool up)
static int net__iface_mtu_set (int mtu)
static int net__addr_v4_add (const char *addr_str, int prefixlen)
static int net__addr_v6_add (const char *addr_str, int prefixlen)
static int net__route_v4_add (const char *dst_str, int prefixlen, int metric)
static int net__route_v4_add_gw (const char *dst_str, int prefixlen, const char *gw_str, int metric)
static int net__route_v6_add (const char *dst_str, int prefixlen, int metric)
static int net__route_v6_add_gw (const char *dst_str, int prefixlen, const char *gw_str, int metric)
static void usage (char *name)
int main (int argc, char *argv[])
Variables
static char * iface = "ovpn-dummy0"
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 198 of file test_networking.c.
References iface, net__addr_v4_add(), net__addr_v6_add(), net__iface_mtu_set(), net__iface_up(), net__route_v4_add(), net__route_v4_add_gw(), net__route_v6_add(), net__route_v6_add_gw(), and usage().
net__addr_v4_add()
static int net__addr_v4_add (const char * addr_str, int prefixlen) static
Definition at line 25 of file test_networking.c.
References iface, in_addr_t, and inet_pton().
Referenced by main().
net__addr_v6_add()
static int net__addr_v6_add (const char * addr_str, int prefixlen) static
Definition at line 44 of file test_networking.c.
References iface, and inet_pton().
Referenced by main().
net__iface_mtu_set()
static int net__iface_mtu_set (int mtu) static
Definition at line 17 of file test_networking.c.
References iface.
Referenced by main().
net__iface_up()
static int net__iface_up (bool up) static
Definition at line 9 of file test_networking.c.
References iface.
Referenced by main().
net__route_v4_add()
static int net__route_v4_add (const char * dst_str, int prefixlen, int metric) static
Definition at line 61 of file test_networking.c.
References dst, iface, in_addr_t, and inet_pton().
Referenced by main().
net__route_v4_add_gw()
static int net__route_v4_add_gw (const char * dst_str, int prefixlen, const char * gw_str, int metric) static
Definition at line 91 of file test_networking.c.
References dst, iface, in_addr_t, and inet_pton().
Referenced by main().
net__route_v6_add()
static int net__route_v6_add (const char * dst_str, int prefixlen, int metric) static
Definition at line 129 of file test_networking.c.
References dst, iface, and inet_pton().
Referenced by main().
net__route_v6_add_gw()
static int net__route_v6_add_gw (const char * dst_str, int prefixlen, const char * gw_str, int metric) static
Definition at line 157 of file test_networking.c.
References dst, iface, and inet_pton().
Referenced by main().
usage()
static void usage (char * name) static
Definition at line 192 of file test_networking.c.
Referenced by main().
Variable Documentation
iface
char* iface = "ovpn-dummy0" static
Definition at line 6 of file test_networking.c.
Referenced by add_route(), main(), net__addr_v4_add(), net__addr_v6_add(), net__iface_mtu_set(), net__iface_up(), net__route_v4_add(), net__route_v4_add_gw(), net__route_v6_add(), and net__route_v6_add_gw().