OpenVPN: tests/unit_tests/openvpn/test_crypto.c File Reference
test_crypto.c File Reference
#include "syshead.h"
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <setjmp.h>
#include <cmocka.h>
#include "crypto.h"
#include "mock_msg.h"
Functions
static void crypto_pem_encode_decode_loopback (void **state)
static void test_translate_cipher (const char *ciphername, const char *openvpn_name)
static void test_cipher_names (const char *ciphername, const char *openvpn_name)
static void crypto_translate_cipher_names (void **state)
int main (void)
Variables
static const char testtext [] = "Dummy text to test PEM encoding"
Function Documentation
crypto_pem_encode_decode_loopback()
static void crypto_pem_encode_decode_loopback (void ** state) static
Definition at line 47 of file test_crypto.c.
References BLEN, BPTR, buf_set_read(), buf_set_write(), crypto_pem_decode(), crypto_pem_encode(), gc_free(), gc_new(), and testtext.
Referenced by main().
crypto_translate_cipher_names()
static void crypto_translate_cipher_names (void ** state) static
Definition at line 127 of file test_crypto.c.
References test_cipher_names().
Referenced by main().
main()
int main (void)
Definition at line 140 of file test_crypto.c.
References crypto_pem_encode_decode_loopback(), and crypto_translate_cipher_names().
test_cipher_names()
static void test_cipher_names (const char * ciphername, const char * openvpn_name) static
Definition at line 89 of file test_crypto.c.
References gc_free(), gc_new(), string_alloc(), and test_translate_cipher().
Referenced by crypto_translate_cipher_names().
test_translate_cipher()
static void test_translate_cipher (const char * ciphername, const char * openvpn_name) static
Definition at line 73 of file test_crypto.c.
References cipher_kt_get(), and cipher_kt_name().
Referenced by test_cipher_names().
Variable Documentation
testtext
const char testtext[] = "Dummy text to test PEM encoding" static
Definition at line 44 of file test_crypto.c.
Referenced by crypto_pem_encode_decode_loopback().