OpenVPN: tests/unit_tests/plugins/auth-pam/test_search_and_replace.c File Reference
test_search_and_replace.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <setjmp.h>
#include <cmocka.h>
#include "utils.h"
Functions
static void pass_any_null_param__returns_null ()
static void pass_any_empty_string__returns_null ()
static void replace_single_char__one_time__match_is_replaced ()
static void replace_single_char__multiple_times__match_all_matches_are_replaced ()
static void replace_longer_text__multiple_times__match_all_matches_are_replaced ()
static void pattern_not_found__returns_original ()
int main (void)
Function Documentation
main()
int main (void)
Definition at line 74 of file test_search_and_replace.c.
References pass_any_empty_string__returns_null(), pass_any_null_param__returns_null(), pattern_not_found__returns_original(), replace_longer_text__multiple_times__match_all_matches_are_replaced(), replace_single_char__multiple_times__match_all_matches_are_replaced(), and replace_single_char__one_time__match_is_replaced().
pass_any_empty_string__returns_null()
static void pass_any_empty_string__returns_null () static
Definition at line 22 of file test_search_and_replace.c.
References searchandreplace().
Referenced by main().
pass_any_null_param__returns_null()
static void pass_any_null_param__returns_null () static
Definition at line 12 of file test_search_and_replace.c.
References searchandreplace().
Referenced by main().
pattern_not_found__returns_original()
static void pattern_not_found__returns_original () static
Definition at line 63 of file test_search_and_replace.c.
References searchandreplace().
Referenced by main().
replace_longer_text__multiple_times__match_all_matches_are_replaced()
static void replace_longer_text__multiple_times__match_all_matches_are_replaced () static
Definition at line 53 of file test_search_and_replace.c.
References searchandreplace().
Referenced by main().
replace_single_char__multiple_times__match_all_matches_are_replaced()
static void replace_single_char__multiple_times__match_all_matches_are_replaced () static
Definition at line 43 of file test_search_and_replace.c.
References searchandreplace().
Referenced by main().
replace_single_char__one_time__match_is_replaced()
static void replace_single_char__one_time__match_is_replaced () static
Definition at line 33 of file test_search_and_replace.c.
References searchandreplace().
Referenced by main().