OpenVPN: tests/unit_tests/openvpn/test_buffer.c File Reference
test_buffer.c File Reference
#include "syshead.h"
#include <setjmp.h>
#include <cmocka.h>
#include "buffer.h"
#include "buffer.c"
Data Structures
struct test_buffer_list_aggregate_ctx
Macros
#define testsep ","
#define testnosep ""
#define teststr1 "one"
#define teststr2 "two"
#define teststr3 "three"
#define teststr4 "four"
#define assert_buf_equals_str(buf, str)
Functions
static void test_buffer_strprefix (void **state)
static int test_buffer_list_setup (void **state)
static int test_buffer_list_teardown (void **state)
static void test_buffer_list_full (void **state)
static void test_buffer_list_aggregate_separator_empty (void **state)
static void test_buffer_list_aggregate_separator_noop (void **state)
static void test_buffer_list_aggregate_separator_two (void **state)
static void test_buffer_list_aggregate_separator_all (void **state)
static void test_buffer_list_aggregate_separator_nosep (void **state)
static void test_buffer_list_aggregate_separator_zerolen (void **state)
static void test_buffer_list_aggregate_separator_emptybuffers (void **state)
static void test_buffer_free_gc_one (void **state)
static void test_buffer_free_gc_two (void **state)
int main (void)
Macro Definition Documentation
assert_buf_equals_str
#define assert_buf_equals_str (buf, str)
Value:
    assert_int_equal(BLEN(buf), strlen(str)); \
    assert_memory_equal(BPTR(buf), str, BLEN(buf));
Definition at line 55 of file test_buffer.c.
testnosep
#define testnosep ""
Definition at line 49 of file test_buffer.c.
testsep
#define testsep ","
Definition at line 48 of file test_buffer.c.
teststr1
#define teststr1 "one"
Definition at line 50 of file test_buffer.c.
teststr2
#define teststr2 "two"
Definition at line 51 of file test_buffer.c.
teststr3
#define teststr3 "three"
Definition at line 52 of file test_buffer.c.
teststr4
#define teststr4 "four"
Definition at line 53 of file test_buffer.c.
Function Documentation
main()
int main (void)
Definition at line 246 of file test_buffer.c.
References test_buffer_free_gc_one(), test_buffer_free_gc_two(), test_buffer_list_aggregate_separator_all(), test_buffer_list_aggregate_separator_empty(), test_buffer_list_aggregate_separator_emptybuffers(), test_buffer_list_aggregate_separator_noop(), test_buffer_list_aggregate_separator_nosep(), test_buffer_list_aggregate_separator_two(), test_buffer_list_aggregate_separator_zerolen(), test_buffer_list_full(), test_buffer_list_setup(), test_buffer_list_teardown(), and test_buffer_strprefix().
test_buffer_free_gc_one()
static void test_buffer_free_gc_one (void ** state) static
Definition at line 204 of file test_buffer.c.
References alloc_buf_gc(), buffer::data, free_buf_gc(), gc_free(), gc_new(), and gc_arena::list.
Referenced by main().
test_buffer_free_gc_two()
static void test_buffer_free_gc_two (void ** state) static
Definition at line 217 of file test_buffer.c.
References alloc_buf_gc(), buffer::data, free_buf_gc(), gc_free(), gc_new(), gc_arena::list, and gc_entry::next.
Referenced by main().
test_buffer_list_aggregate_separator_all()
static void test_buffer_list_aggregate_separator_all (void ** state) static
Definition at line 153 of file test_buffer.c.
References assert_buf_equals_str, buffer_list_aggregate_separator(), buffer_list_peek(), test_buffer_list_aggregate_ctx::one_two_three, buffer_list::size, testsep, teststr1, teststr2, and teststr3.
Referenced by main().
test_buffer_list_aggregate_separator_empty()
static void test_buffer_list_aggregate_separator_empty (void ** state) static
Definition at line 115 of file test_buffer.c.
References buffer_list_aggregate_separator(), test_buffer_list_aggregate_ctx::empty, buffer_list::head, and testsep.
Referenced by main().
test_buffer_list_aggregate_separator_emptybuffers()
static void test_buffer_list_aggregate_separator_emptybuffers (void ** state) static
Definition at line 191 of file test_buffer.c.
References BLEN, buffer_list_aggregate_separator(), buffer_list_peek(), test_buffer_list_aggregate_ctx::empty_buffers, buffer_list::size, and testnosep.
Referenced by main().
test_buffer_list_aggregate_separator_noop()
static void test_buffer_list_aggregate_separator_noop (void ** state) static
Definition at line 125 of file test_buffer.c.
References assert_buf_equals_str, buffer_list_aggregate_separator(), buffer_list_peek(), test_buffer_list_aggregate_ctx::one_two_three, buffer_list::size, testsep, and teststr1.
Referenced by main().
test_buffer_list_aggregate_separator_nosep()
static void test_buffer_list_aggregate_separator_nosep (void ** state) static
Definition at line 166 of file test_buffer.c.
References assert_buf_equals_str, buffer_list_aggregate_separator(), buffer_list_peek(), test_buffer_list_aggregate_ctx::one_two_three, buffer_list::size, testnosep, teststr1, teststr2, and teststr3.
Referenced by main().
test_buffer_list_aggregate_separator_two()
static void test_buffer_list_aggregate_separator_two (void ** state) static
Definition at line 137 of file test_buffer.c.
References assert_buf_equals_str, buffer_list_aggregate_separator(), buffer_list_peek(), test_buffer_list_aggregate_ctx::one_two_three, buffer_list::size, testsep, teststr1, and teststr2.
Referenced by main().
test_buffer_list_aggregate_separator_zerolen()
static void test_buffer_list_aggregate_separator_zerolen (void ** state) static
Definition at line 178 of file test_buffer.c.
References assert_buf_equals_str, buffer_list_aggregate_separator(), buffer_list_peek(), buffer_list::size, testnosep, and test_buffer_list_aggregate_ctx::zero_length_strings.
Referenced by main().
test_buffer_list_full()
static void test_buffer_list_full (void ** state) static
Definition at line 104 of file test_buffer.c.
References buffer_list_push(), test_buffer_list_aggregate_ctx::one_two_three, buffer_list::size, and teststr4.
Referenced by main().
test_buffer_list_setup()
static int test_buffer_list_setup (void ** state) static
Definition at line 67 of file test_buffer.c.
References buffer_list_new(), buffer_list_push(), buffer_list_push_data(), test_buffer_list_aggregate_ctx::empty, test_buffer_list_aggregate_ctx::empty_buffers, test_buffer_list_aggregate_ctx::one_two_three, teststr1, teststr2, teststr3, and test_buffer_list_aggregate_ctx::zero_length_strings.
Referenced by main().
test_buffer_list_teardown()
static int test_buffer_list_teardown (void ** state) static
Definition at line 91 of file test_buffer.c.
References buffer_list_free(), test_buffer_list_aggregate_ctx::empty, test_buffer_list_aggregate_ctx::empty_buffers, test_buffer_list_aggregate_ctx::one_two_three, and test_buffer_list_aggregate_ctx::zero_length_strings.
Referenced by main().
test_buffer_strprefix()
static void test_buffer_strprefix (void ** state) static
Definition at line 39 of file test_buffer.c.
References strprefix().
Referenced by main().