OpenVPN: src/openvpnserv/validate.h File Reference
validate.h File Reference
#include "service.h"
Macros
#define SYSTEM_ADMIN_GROUP TEXT("Administrators")
#define OVPN_ADMIN_GROUP TEXT("OpenVPN Administrators")
Functions
BOOL IsAuthorizedUser (PSID sid, const HANDLE token, const WCHAR *ovpn_admin_group)
BOOL CheckOption (const WCHAR *workdir, int narg, WCHAR *argv[], const settings_t *s)
static BOOL IsOption (const WCHAR *o)
Macro Definition Documentation
OVPN_ADMIN_GROUP
#define OVPN_ADMIN_GROUP TEXT("OpenVPN Administrators")
Definition at line 32 of file validate.h.
SYSTEM_ADMIN_GROUP
#define SYSTEM_ADMIN_GROUP TEXT("Administrators")
Definition at line 31 of file validate.h.
Function Documentation
CheckOption()
BOOL CheckOption (const WCHAR * workdir, int narg, WCHAR * argv[], const settings_t * s)
Definition at line 329 of file validate.c.
References CheckConfigPath(), OptionLookup(), and white_list.
Referenced by ValidateOptions().
IsAuthorizedUser()
BOOL IsAuthorizedUser (PSID sid, const HANDLE token, const WCHAR * ovpn_admin_group)
Definition at line 160 of file validate.c.
References GetBuiltinAdminGroupName(), GetTokenGroups(), IsUserInGroup(), M_INFO, M_SYSERR, MAX_NAME, MsgToEventLog(), and SYSTEM_ADMIN_GROUP.
Referenced by RunOpenvpn().
IsOption()
static BOOL IsOption (const WCHAR * o) inline static
Definition at line 42 of file validate.h.
Referenced by ValidateOptions().