OpenVPN: src/openvpn/vlan.c File Reference
vlan.c File Reference
#include "syshead.h"
#include "multi.h"
#include "options.h"
#include "vlan.h"
Functions
static uint16_t vlanhdr_get_vid (const struct openvpn_8021qhdr *hdr)
static void vlanhdr_set_vid (struct openvpn_8021qhdr *hdr, const uint16_t vid)
int16_t vlan_decapsulate (const struct context *c, struct buffer *buf)
void vlan_encapsulate (const struct context *c, struct buffer *buf)
bool vlan_is_tagged (const struct buffer *buf)
void vlan_process_outgoing_tun (struct multi_context *m, struct multi_instance *mi)
Function Documentation
vlan_decapsulate()
int16_t vlan_decapsulate (const struct context * c, struct buffer * buf)
Definition at line 84 of file vlan.c.
References BLEN, BPTR, buf_advance(), D_VLAN_DEBUG, buffer::len, msg, OPENVPN_ETH_P_8021Q, context::options, openvpn_ethhdr::proto, openvpn_8021qhdr::proto, SIZE_ETH_TO_8021Q_HDR, options::vlan_accept, VLAN_ALL, VLAN_ONLY_TAGGED, VLAN_ONLY_UNTAGGED_OR_PRIORITY, options::vlan_pvid, and vlanhdr_get_vid().
Referenced by multi_process_incoming_tun().
vlan_encapsulate()
void vlan_encapsulate (const struct context * c, struct buffer * buf)
Definition at line 188 of file vlan.c.
References BLEN, BPTR, buf_prepend(), buf_reverse_capacity(), D_VLAN_DEBUG, buffer::len, msg, OPENVPN_ETH_P_8021Q, context::options, openvpn_8021qhdr::pcp_cfi_vid, openvpn_ethhdr::proto, openvpn_8021qhdr::proto, SIZE_ETH_TO_8021Q_HDR, openvpn_8021qhdr::tpid, options::vlan_pvid, vlanhdr_get_vid(), and vlanhdr_set_vid().
Referenced by vlan_process_outgoing_tun().
vlan_is_tagged()
bool vlan_is_tagged (const struct buffer * buf)
Definition at line 268 of file vlan.c.
References BLEN, BPTR, OPENVPN_ETH_P_8021Q, openvpn_8021qhdr::tpid, and vlanhdr_get_vid().
Referenced by multi_process_incoming_link().
vlan_process_outgoing_tun()
void vlan_process_outgoing_tun (struct multi_context * m, struct multi_instance * mi)
Definition at line 298 of file vlan.c.
References context::c2, multi_instance::context, buffer::len, context::options, context_2::to_tun, multi_context::top, options::vlan_accept, VLAN_ALL, vlan_encapsulate(), VLAN_ONLY_TAGGED, VLAN_ONLY_UNTAGGED_OR_PRIORITY, options::vlan_pvid, and options::vlan_tagging.
Referenced by multi_process_outgoing_tun().
vlanhdr_get_vid()
static uint16_t vlanhdr_get_vid (const struct openvpn_8021qhdr * hdr) static
Definition at line 44 of file vlan.c.
References OPENVPN_8021Q_MASK_VID, and openvpn_8021qhdr::pcp_cfi_vid.
Referenced by vlan_decapsulate(), vlan_encapsulate(), and vlan_is_tagged().
vlanhdr_set_vid()
static void vlanhdr_set_vid (struct openvpn_8021qhdr * hdr, const uint16_t vid) static
Definition at line 56 of file vlan.c.
References OPENVPN_8021Q_MASK_VID, and openvpn_8021qhdr::pcp_cfi_vid.
Referenced by vlan_encapsulate().