OpenVPN: src/openvpn/vlan.h File Reference
vlan.h File Reference
#include "buffer.h"
#include "mroute.h"
#include "openvpn.h"
Functions
int16_t vlan_decapsulate (const struct context *c, struct buffer *buf)
bool vlan_is_tagged (const struct buffer *buf)
void vlan_process_outgoing_tun (struct multi_context *m, struct multi_instance *mi)
Function Documentation
vlan_decapsulate()
int16_t vlan_decapsulate (const struct context * c, struct buffer * buf)
Definition at line 84 of file vlan.c.
References BLEN, BPTR, buf_advance(), D_VLAN_DEBUG, buffer::len, msg, OPENVPN_ETH_P_8021Q, context::options, openvpn_ethhdr::proto, openvpn_8021qhdr::proto, SIZE_ETH_TO_8021Q_HDR, options::vlan_accept, VLAN_ALL, VLAN_ONLY_TAGGED, VLAN_ONLY_UNTAGGED_OR_PRIORITY, options::vlan_pvid, and vlanhdr_get_vid().
Referenced by multi_process_incoming_tun().
vlan_is_tagged()
bool vlan_is_tagged (const struct buffer * buf)
Definition at line 268 of file vlan.c.
References BLEN, BPTR, OPENVPN_ETH_P_8021Q, openvpn_8021qhdr::tpid, and vlanhdr_get_vid().
Referenced by multi_process_incoming_link().
vlan_process_outgoing_tun()
void vlan_process_outgoing_tun (struct multi_context * m, struct multi_instance * mi)
Definition at line 298 of file vlan.c.
References context::c2, multi_instance::context, buffer::len, context::options, context_2::to_tun, multi_context::top, options::vlan_accept, VLAN_ALL, vlan_encapsulate(), VLAN_ONLY_TAGGED, VLAN_ONLY_UNTAGGED_OR_PRIORITY, options::vlan_pvid, and options::vlan_tagging.
Referenced by multi_process_outgoing_tun().