OpenVPN: src/openvpn/win32.h File Reference
win32.h File Reference
#include <winioctl.h>
#include "mtu.h"
#include "openvpn-msg.h"
#include "argv.h"
Data Structures
struct security_attributes
struct window_title
struct rw_handle
struct net_event_win32
struct win32_signal
struct overlapped_io
struct semaphore
Macros
#define SYS_PATH_ENV_VAR_NAME "SystemRoot" /* environmental variable name that normally contains the system path */
#define NETSH_PATH_SUFFIX "\\system32\\netsh.exe"
#define WIN_ROUTE_PATH_SUFFIX "\\system32\\route.exe"
#define WIN_IPCONFIG_PATH_SUFFIX "\\system32\\ipconfig.exe"
#define WIN_NET_PATH_SUFFIX "\\system32\\net.exe"
#define IN6_ARE_ADDR_EQUAL(a, b) (memcmp((const void *)(a), (const void *)(b), sizeof(struct in6_addr)) == 0)
#define HANDLE_DEFINED(h) ((h) != NULL && (h) != INVALID_HANDLE_VALUE)
#define NE32_PERSIST_EVENT (1<<0)
#define NE32_WRITE_EVENT (1<<1)
#define WSO_MODE_UNDEF 0
#define WSO_MODE_SERVICE 1
#define WSO_MODE_CONSOLE 2
#define WSO_NOFORCE 0
#define WSO_FORCE_SERVICE 1
#define WSO_FORCE_CONSOLE 2
#define IOSTATE_INITIAL 0
#define IOSTATE_QUEUED 1 /* overlapped I/O has been queued */
#define IOSTATE_IMMEDIATE_RETURN 2 /* I/O function returned immediately without queueing */
#define WIN_XP 0
#define WIN_VISTA 1
#define WIN_7 2
#define WIN_8 3
#define WIN_8_1 4
#define WIN_10 5
Functions
void init_win32 (void)
void uninit_win32 (void)
void set_pause_exit_win32 (void)
static bool defined_net_event_win32 (const struct rw_handle *event)
void init_net_event_win32 (struct rw_handle *event, long network_events, socket_descriptor_t sd, unsigned int flags)
long reset_net_event_win32 (struct rw_handle *event, socket_descriptor_t sd)
void close_net_event_win32 (struct rw_handle *event, socket_descriptor_t sd, unsigned int flags)
void net_event_win32_init (struct net_event_win32 *ne)
void net_event_win32_start (struct net_event_win32 *ne, long network_events, socket_descriptor_t sd)
void net_event_win32_reset (struct net_event_win32 *ne)
void net_event_win32_reset_write (struct net_event_win32 *ne)
void net_event_win32_stop (struct net_event_win32 *ne)
void net_event_win32_close (struct net_event_win32 *ne)
static bool net_event_win32_defined (const struct net_event_win32 *ne)
static struct rw_handle * net_event_win32_get_event (struct net_event_win32 *ne)
static long net_event_win32_get_event_mask (const struct net_event_win32 *ne)
static void net_event_win32_clear_selected_events (struct net_event_win32 *ne, long selected_events)
void win32_signal_clear (struct win32_signal *ws)
void win32_signal_open (struct win32_signal *ws, int force, const char *exit_event_name, bool exit_event_initial_state)
void win32_signal_close (struct win32_signal *ws)
int win32_signal_get (struct win32_signal *ws)
void win32_pause (struct win32_signal *ws)
bool win32_service_interrupt (struct win32_signal *ws)
void window_title_clear (struct window_title *wt)
void window_title_save (struct window_title *wt)
void window_title_restore (const struct window_title *wt)
void window_title_generate (const char *title)
void overlapped_io_init (struct overlapped_io *o, const struct frame *frame, BOOL event_state, bool tuntap_buffer)
void overlapped_io_close (struct overlapped_io *o)
static bool overlapped_io_active (struct overlapped_io *o)
char * overlapped_io_state_ascii (const struct overlapped_io *o)
void semaphore_clear (struct semaphore *s)
void semaphore_open (struct semaphore *s, const char *name)
bool semaphore_lock (struct semaphore *s, int timeout_milliseconds)
void semaphore_release (struct semaphore *s)
void semaphore_close (struct semaphore *s)
void netcmd_semaphore_init (void)
void netcmd_semaphore_close (void)
void netcmd_semaphore_lock (void)
void netcmd_semaphore_release (void)
bool init_security_attributes_allow_all (struct security_attributes *obj)
bool win_safe_filename (const char *fn)
void set_win_sys_path (const char *newpath, struct env_set *es)
void set_win_sys_path_via_env (struct env_set *es)
char * get_win_sys_path (void)
void fork_to_self (const char *cmdline)
const char * win_get_tempdir (void)
WCHAR * wide_string (const char *utf8, struct gc_arena *gc)
bool win_wfp_block_dns (const NET_IFINDEX index, const HANDLE msg_channel)
bool win_wfp_uninit (const NET_IFINDEX index, const HANDLE msg_channel)
int win32_version_info (void)
const char * win32_version_string (struct gc_arena *gc, bool add_name)
bool send_msg_iservice (HANDLE pipe, const void *data, size_t size, ack_message_t *ack, const char *context)
int openvpn_execve (const struct argv *a, const struct env_set *es, const unsigned int flags)
bool openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format,...)
bool get_openvpn_reg_value (const WCHAR *key, WCHAR *value, DWORD size)
Fetches a registry value for OpenVPN registry key.
bool plugin_in_trusted_dir (const WCHAR *plugin_path)
Checks if a plugin is located in a trusted directory.
Variables
struct win32_signal win32_signal
struct window_title window_title
struct semaphore netcmd_semaphore
Macro Definition Documentation
HANDLE_DEFINED
#define HANDLE_DEFINED (h) ((h) != NULL && (h) != INVALID_HANDLE_VALUE)
Definition at line 64 of file win32.h.
IN6_ARE_ADDR_EQUAL
#define IN6_ARE_ADDR_EQUAL (a, b) (memcmp((const void *)(a), (const void *)(b), sizeof(struct in6_addr)) == 0)
Definition at line 48 of file win32.h.
IOSTATE_IMMEDIATE_RETURN
#define IOSTATE_IMMEDIATE_RETURN 2 /* I/O function returned immediately without queueing */
Definition at line 201 of file win32.h.
IOSTATE_INITIAL
#define IOSTATE_INITIAL 0
Definition at line 199 of file win32.h.
IOSTATE_QUEUED
#define IOSTATE_QUEUED 1 /* overlapped I/O has been queued */
Definition at line 200 of file win32.h.
NE32_PERSIST_EVENT
#define NE32_PERSIST_EVENT (1<<0)
Definition at line 84 of file win32.h.
NE32_WRITE_EVENT
#define NE32_WRITE_EVENT (1<<1)
Definition at line 85 of file win32.h.
NETSH_PATH_SUFFIX
#define NETSH_PATH_SUFFIX "\\system32\\netsh.exe"
Definition at line 36 of file win32.h.
SYS_PATH_ENV_VAR_NAME
#define SYS_PATH_ENV_VAR_NAME "SystemRoot" /* environmental variable name that normally contains the system path */
Definition at line 35 of file win32.h.
WIN_10
#define WIN_10 5
Definition at line 306 of file win32.h.
WIN_7
#define WIN_7 2
Definition at line 303 of file win32.h.
WIN_8
#define WIN_8 3
Definition at line 304 of file win32.h.
WIN_8_1
#define WIN_8_1 4
Definition at line 305 of file win32.h.
WIN_IPCONFIG_PATH_SUFFIX
#define WIN_IPCONFIG_PATH_SUFFIX "\\system32\\ipconfig.exe"
Definition at line 38 of file win32.h.
WIN_NET_PATH_SUFFIX
#define WIN_NET_PATH_SUFFIX "\\system32\\net.exe"
Definition at line 39 of file win32.h.
WIN_ROUTE_PATH_SUFFIX
#define WIN_ROUTE_PATH_SUFFIX "\\system32\\route.exe"
Definition at line 37 of file win32.h.
WIN_VISTA
#define WIN_VISTA 1
Definition at line 302 of file win32.h.
WIN_XP
#define WIN_XP 0
Definition at line 301 of file win32.h.
WSO_FORCE_CONSOLE
#define WSO_FORCE_CONSOLE 2
Definition at line 167 of file win32.h.
WSO_FORCE_SERVICE
#define WSO_FORCE_SERVICE 1
Definition at line 166 of file win32.h.
WSO_MODE_CONSOLE
#define WSO_MODE_CONSOLE 2
Definition at line 152 of file win32.h.
WSO_MODE_SERVICE
#define WSO_MODE_SERVICE 1
Definition at line 151 of file win32.h.
WSO_MODE_UNDEF
#define WSO_MODE_UNDEF 0
Definition at line 150 of file win32.h.
WSO_NOFORCE
#define WSO_NOFORCE 0
Definition at line 165 of file win32.h.
Function Documentation
close_net_event_win32()
void close_net_event_win32 (struct rw_handle * event, socket_descriptor_t sd, unsigned int flags)
Definition at line 280 of file win32.c.
References M_ERRNO, M_WARN, msg, NE32_PERSIST_EVENT, rw_handle::read, socket_defined(), and rw_handle::write.
Referenced by link_socket_close(), net_event_win32_close(), and net_event_win32_stop().
defined_net_event_win32()
static bool defined_net_event_win32 (const struct rw_handle * event) inline static
Definition at line 88 of file win32.h.
Referenced by net_event_win32_defined(), and socket_listen_event_handle().
fork_to_self()
void fork_to_self (const char * cmdline)
Definition at line 1177 of file win32.c.
References CLEAR, M_ERRNO, M_WARN, msg, status, and string_alloc().
Referenced by fork_dhcp_action(), and fork_register_dns_action().
get_openvpn_reg_value()
bool get_openvpn_reg_value (const WCHAR * key, WCHAR * value, DWORD size)
Fetches a registry value for OpenVPN registry key.
Parameters
key Registry value name to fetch.
value Buffer to store the fetched string value.
size Size of value buffer in bytes.
Returns
true if successful, false otherwise.
Definition at line 1536 of file win32.c.
References openvpn_swprintf(), PACKAGE_NAME, and status.
Referenced by plugin_in_trusted_dir(), and set_openssl_env_vars().
get_win_sys_path()
char* get_win_sys_path (void)
Definition at line 1217 of file win32.c.
init_net_event_win32()
void init_net_event_win32 (struct rw_handle * event, long network_events, socket_descriptor_t sd, unsigned int flags)
Definition at line 226 of file win32.c.
References M_ERR, M_ERRNO, M_FATAL, msg, NE32_PERSIST_EVENT, NE32_WRITE_EVENT, rw_handle::read, and rw_handle::write.
Referenced by net_event_win32_start(), and socket_listen_event_handle().
init_security_attributes_allow_all()
bool init_security_attributes_allow_all (struct security_attributes * obj)
Definition at line 154 of file win32.c.
References CLEAR, security_attributes::sa, and security_attributes::sd.
Referenced by create_event(), semaphore_open(), ServiceStartAutomatic(), tap_allow_nonadmin_access_handle(), and win32_signal_open().
init_win32()
void init_win32 (void)
Definition at line 111 of file win32.c.
References M_ERR, msg, set_openssl_env_vars(), win32_signal_clear(), window_title_clear(), and wsa_state.
Referenced by init_static().
net_event_win32_clear_selected_events()
static void net_event_win32_clear_selected_events (struct net_event_win32 * ne, long selected_events) inline static
Definition at line 141 of file win32.h.
References net_event_win32::event_mask.
Referenced by management_io().
net_event_win32_close()
void net_event_win32_close (struct net_event_win32 * ne)
Definition at line 378 of file win32.c.
References close_net_event_win32(), net_event_win32::handle, net_event_win32_defined(), net_event_win32_init(), and net_event_win32::sd.
Referenced by man_connection_close().
net_event_win32_defined()
static bool net_event_win32_defined (const struct net_event_win32 * ne) inline static
Definition at line 123 of file win32.h.
References defined_net_event_win32(), and net_event_win32::handle.
Referenced by net_event_win32_close(), and net_event_win32_stop().
net_event_win32_get_event()
static struct rw_handle* net_event_win32_get_event (struct net_event_win32 * ne) inline static
Definition at line 129 of file win32.h.
References net_event_win32::handle.
Referenced by management_socket_set().
net_event_win32_get_event_mask()
static long net_event_win32_get_event_mask (const struct net_event_win32 * ne) inline static
Definition at line 135 of file win32.h.
References net_event_win32::event_mask.
Referenced by management_io().
net_event_win32_init()
void net_event_win32_init (struct net_event_win32 * ne)
Definition at line 327 of file win32.c.
References CLEAR, net_event_win32::sd, and SOCKET_UNDEFINED.
Referenced by man_connection_init(), and net_event_win32_close().
net_event_win32_reset()
void net_event_win32_reset (struct net_event_win32 * ne)
Definition at line 361 of file win32.c.
References net_event_win32::event_mask, net_event_win32::handle, reset_net_event_win32(), and net_event_win32::sd.
Referenced by management_io().
net_event_win32_reset_write()
void net_event_win32_reset_write (struct net_event_win32 * ne)
Definition at line 343 of file win32.c.
References net_event_win32::event_mask, net_event_win32::handle, M_ERRNO, M_WARN, msg, status, and rw_handle::write.
Referenced by management_socket_set().
net_event_win32_start()
void net_event_win32_start (struct net_event_win32 * ne, long network_events, socket_descriptor_t sd)
Definition at line 334 of file win32.c.
References ASSERT, net_event_win32::event_mask, net_event_win32::handle, init_net_event_win32(), NE32_PERSIST_EVENT, NE32_WRITE_EVENT, net_event_win32::sd, and socket_defined().
Referenced by man_start_ne32().
net_event_win32_stop()
void net_event_win32_stop (struct net_event_win32 * ne)
Definition at line 367 of file win32.c.
References close_net_event_win32(), net_event_win32::event_mask, net_event_win32::handle, NE32_PERSIST_EVENT, net_event_win32_defined(), net_event_win32::sd, and SOCKET_UNDEFINED.
Referenced by man_stop_ne32().
netcmd_semaphore_close()
void netcmd_semaphore_close (void)
Definition at line 861 of file win32.c.
References netcmd_semaphore, and semaphore_close().
Referenced by uninit_win32().
netcmd_semaphore_init()
void netcmd_semaphore_init (void)
Definition at line 855 of file win32.c.
References netcmd_semaphore, PACKAGE, and semaphore_open().
Referenced by netcmd_semaphore_lock().
netcmd_semaphore_lock()
void netcmd_semaphore_lock (void)
Definition at line 867 of file win32.c.
References semaphore::hand, M_FATAL, msg, netcmd_semaphore, netcmd_semaphore_init(), and semaphore_lock().
Referenced by add_route(), add_route_ipv6(), delete_route(), delete_route_ipv6(), ipconfig_register_dns(), and netsh_command().
netcmd_semaphore_release()
void netcmd_semaphore_release (void)
Definition at line 883 of file win32.c.
References netcmd_semaphore, semaphore_close(), and semaphore_release().
Referenced by add_route(), add_route_ipv6(), delete_route(), delete_route_ipv6(), ipconfig_register_dns(), and netsh_command().
openvpn_execve()
int openvpn_execve (const struct argv * a, const struct env_set * es, const unsigned int flags)
Definition at line 1096 of file win32.c.
References argv::argv, CLEAR, env_block(), gc_free(), gc_new(), M_ERRNO, M_WARN, msg, openvpn_execve_allowed(), OPENVPN_EXECVE_ERROR, OPENVPN_EXECVE_NOT_ALLOWED, script_security(), SCRIPT_SECURITY_WARNING, SSEC_SCRIPTS, wide_cmd_line(), and wide_string().
Referenced by openvpn_execve_check().
openvpn_swprintf()
bool openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format, ...)
Definition at line 1521 of file win32.c.
overlapped_io_active()
static bool overlapped_io_active (struct overlapped_io * o) inline static
Definition at line 225 of file win32.h.
References overlapped_io::iostate, IOSTATE_IMMEDIATE_RETURN, and IOSTATE_QUEUED.
Referenced by link_socket_write_win32(), and tun_write_win32().
overlapped_io_close()
void overlapped_io_close (struct overlapped_io * o)
Definition at line 192 of file win32.c.
References overlapped_io::buf_init, free_buf(), M_ERRNO, M_WARN, msg, and overlapped_io::overlapped.
Referenced by close_tun(), and link_socket_close().
overlapped_io_init()
void overlapped_io_init (struct overlapped_io * o, const struct frame * frame, BOOL event_state, bool tuntap_buffer)
Definition at line 173 of file win32.c.
References alloc_buf_sock_tun(), overlapped_io::buf_init, CLEAR, M_ERR, msg, and overlapped_io::overlapped.
Referenced by init_tun_post(), and socket_frame_init().
overlapped_io_state_ascii()
char* overlapped_io_state_ascii (const struct overlapped_io * o)
Definition at line 205 of file win32.c.
References overlapped_io::iostate, IOSTATE_IMMEDIATE_RETURN, IOSTATE_INITIAL, and IOSTATE_QUEUED.
Referenced by socket_stat(), and tun_stat().
plugin_in_trusted_dir()
bool plugin_in_trusted_dir (const WCHAR * plugin_path)
Checks if a plugin is located in a trusted directory.
Verifies the plugin's path against a trusted directory, which is:
"plugin_dir" registry value or installation path, if the registry key is missing
system directory
UNC paths are explicitly disallowed.
Parameters
plugin_path Normalized path to the plugin.
Returns
true if the plugin is in a trusted directory and not a UNC path; false otherwise.
Definition at line 1598 of file win32.c.
References get_openvpn_reg_value(), M_ERRNO, M_NONFATAL, M_WARN, and msg.
Referenced by plugin_init_item().
reset_net_event_win32()
long reset_net_event_win32 (struct rw_handle * event, socket_descriptor_t sd)
Definition at line 265 of file win32.c.
References M_ERRNO, M_FATAL, msg, and rw_handle::read.
Referenced by net_event_win32_reset(), and socket_reset_listen_persistent().
semaphore_clear()
void semaphore_clear (struct semaphore * s)
Definition at line 755 of file win32.c.
References CLEAR.
semaphore_close()
void semaphore_close (struct semaphore * s)
Definition at line 835 of file win32.c.
References D_SEMAPHORE, dmsg, semaphore::hand, semaphore::locked, semaphore::name, and semaphore_release().
Referenced by netcmd_semaphore_close(), and netcmd_semaphore_release().
semaphore_lock()
bool semaphore_lock (struct semaphore * s, int timeout_milliseconds)
Definition at line 785 of file win32.c.
References ASSERT, D_SEMAPHORE, D_SEMAPHORE_LOW, dmsg, semaphore::hand, semaphore::locked, M_ERR, msg, semaphore::name, and status.
Referenced by netcmd_semaphore_lock().
semaphore_open()
void semaphore_open (struct semaphore * s, const char * name)
Definition at line 761 of file win32.c.
References D_SEMAPHORE, dmsg, semaphore::hand, init_security_attributes_allow_all(), semaphore::locked, M_ERRNO, M_WARN, msg, semaphore::name, and security_attributes::sa.
Referenced by netcmd_semaphore_init().
semaphore_release()
void semaphore_release (struct semaphore * s)
Definition at line 819 of file win32.c.
References ASSERT, D_SEMAPHORE, dmsg, semaphore::hand, semaphore::locked, M_ERRNO, M_WARN, msg, and semaphore::name.
Referenced by netcmd_semaphore_release(), and semaphore_close().
send_msg_iservice()
bool send_msg_iservice (HANDLE pipe, const void * data, size_t size, ack_message_t * ack, const char * context)
Definition at line 1500 of file win32.c.
References gc_free(), gc_new(), M_WARN, msg, and strerror_win32().
Referenced by do_address_service(), do_dns_domain_service(), do_dns_service(), do_route_service(), do_set_mtu_service(), register_dns_service(), service_enable_dhcp(), service_register_ring_buffers(), tuntap_set_ip_addr(), and win_block_dns_service().
set_pause_exit_win32()
void set_pause_exit_win32 (void)
Definition at line 148 of file win32.c.
References pause_exit_enabled.
Referenced by add_option().
set_win_sys_path()
void set_win_sys_path (const char * newpath, struct env_set * es)
Definition at line 1224 of file win32.c.
References setenv_str(), string_alloc(), SYS_PATH_ENV_VAR_NAME, and win_sys_path.
Referenced by add_option(), and set_win_sys_path_via_env().
set_win_sys_path_via_env()
void set_win_sys_path_via_env (struct env_set * es)
Definition at line 1232 of file win32.c.
References M_ERR, M_FATAL, msg, set_win_sys_path(), status, and SYS_PATH_ENV_VAR_NAME.
Referenced by openvpn_main().
uninit_win32()
void uninit_win32 (void)
Definition at line 124 of file win32.c.
References win32_signal::mode, netcmd_semaphore_close(), pause_exit_enabled, win32_pause(), win32_signal_close(), win32_signal_open(), win_sys_path, window_title_restore(), WSO_FORCE_CONSOLE, and WSO_MODE_UNDEF.
Referenced by openvpn_exit().
wide_string()
WCHAR* wide_string (const char * utf8, struct gc_arena * gc)
Definition at line 1165 of file win32.c.
References gc_malloc().
Referenced by find_certificate_in_store(), openvpn_execve(), platform_access(), platform_chdir(), platform_fopen(), platform_open(), platform_stat(), platform_unlink(), plugin_init_item(), redirect_stdout_stderr(), and wide_cmd_line().
win32_pause()
void win32_pause (struct win32_signal * ws)
Definition at line 692 of file win32.c.
References HANDLE_DEFINED, win32_signal::in, M_INFO, M_NOPREFIX, win32_signal::mode, msg, rw_handle::read, win32_keyboard_get(), and WSO_MODE_CONSOLE.
Referenced by uninit_win32().
win32_service_interrupt()
bool win32_service_interrupt (struct win32_signal * ws)
Definition at line 627 of file win32.c.
References HANDLE_DEFINED, win32_signal::in, win32_signal::mode, rw_handle::read, and WSO_MODE_SERVICE.
Referenced by get_console_input_win32(), and win32_signal_get().
win32_signal_clear()
void win32_signal_clear (struct win32_signal * ws)
Definition at line 450 of file win32.c.
References CLEAR.
Referenced by init_win32().
win32_signal_close()
void win32_signal_close (struct win32_signal * ws)
Definition at line 607 of file win32.c.
References CLEAR, win32_signal::console_mode_save, win32_signal::console_mode_save_defined, HANDLE_DEFINED, win32_signal::in, M_ERR, win32_signal::mode, msg, rw_handle::read, and WSO_MODE_SERVICE.
Referenced by halt_non_edge_triggered_signals(), and uninit_win32().
win32_signal_get()
int win32_signal_get (struct win32_signal * ws)
Definition at line 641 of file win32.c.
References win32_signal::mode, SIG_SOURCE_HARD, SIGHUP, siginfo_static, signal_info::signal_received, SIGTERM, SIGUSR1, SIGUSR2, signal_info::source, win32_keyboard_get(), win32_service_interrupt(), WSO_MODE_CONSOLE, and WSO_MODE_SERVICE.
Referenced by get_signal().
win32_signal_open()
void win32_signal_open (struct win32_signal * ws, int force, const char * exit_event_name, bool exit_event_initial_state)
Definition at line 456 of file win32.c.
References CLEAR, win32_signal::console_mode_save, win32_signal::console_mode_save_defined, HANDLE_DEFINED, win32_signal::in, init_security_attributes_allow_all(), M_ERR, M_ERRNO, M_FATAL, M_WARN, win32_signal::mode, msg, rw_handle::read, security_attributes::sa, win_ctrl_handler(), rw_handle::write, WSO_FORCE_CONSOLE, WSO_FORCE_SERVICE, WSO_MODE_CONSOLE, WSO_MODE_SERVICE, WSO_MODE_UNDEF, and WSO_NOFORCE.
Referenced by pre_setup(), and uninit_win32().
win32_version_info()
int win32_version_info (void)
Definition at line 1407 of file win32.c.
References M_FATAL, msg, WIN_10, WIN_7, WIN_8, WIN_8_1, WIN_VISTA, and WIN_XP.
Referenced by netsh_ifconfig_options(), netsh_set_dns6_servers(), and win32_version_string().
win32_version_string()
const char* win32_version_string (struct gc_arena * gc, bool add_name)
Definition at line 1457 of file win32.c.
References alloc_buf_gc(), buf_printf(), buffer::data, M_NONFATAL, msg, win32_is_64bit(), win32_version_info(), WIN_10, WIN_7, WIN_8, WIN_8_1, WIN_VISTA, and WIN_XP.
Referenced by push_peer_info(), and show_windows_version().
win_get_tempdir()
const char* win_get_tempdir (void)
Definition at line 1249 of file win32.c.
References M_WARN, and msg.
Referenced by init_options().
win_safe_filename()
bool win_safe_filename (const char * fn)
Definition at line 943 of file win32.c.
References cmp_prefix().
Referenced by platform_gen_path().
win_wfp_block_dns()
bool win_wfp_block_dns (const NET_IFINDEX index, const HANDLE msg_channel)
Definition at line 1330 of file win32.c.
References add_block_dns_filters(), BLOCK_DNS_IFACE_METRIC, block_dns_msg_handler(), D_LOW, dmsg, get_interface_metric(), M_ERRNO, m_hEngineHandle, M_WARN, msg, set_interface_metric(), status, tap_metric_v4, tap_metric_v6, and win_block_dns_service().
Referenced by do_open_tun().
win_wfp_uninit()
bool win_wfp_uninit (const NET_IFINDEX index, const HANDLE msg_channel)
Definition at line 1380 of file win32.c.
References D_LOW, delete_block_dns_filters(), dmsg, m_hEngineHandle, msg, set_interface_metric(), tap_metric_v4, tap_metric_v6, and win_block_dns_service().
Referenced by do_close_tun().
window_title_clear()
void window_title_clear (struct window_title * wt)
Definition at line 707 of file win32.c.
References CLEAR.
Referenced by init_win32().
window_title_generate()
void window_title_generate (const char * title)
Definition at line 739 of file win32.c.
References alloc_buf_gc(), BSTR, buf_printf(), gc_free(), gc_new(), PACKAGE_NAME, and PACKAGE_VERSION.
Referenced by pre_setup().
window_title_restore()
void window_title_restore (const struct window_title * wt)
Definition at line 730 of file win32.c.
References window_title::old_window_title, and window_title::saved.
Referenced by uninit_win32().
window_title_save()
void window_title_save (struct window_title * wt)
Definition at line 713 of file win32.c.
References window_title::old_window_title, and window_title::saved.
Referenced by pre_setup().
Variable Documentation
netcmd_semaphore
struct semaphore netcmd_semaphore
Definition at line 97 of file win32.c.
Referenced by netcmd_semaphore_close(), netcmd_semaphore_init(), netcmd_semaphore_lock(), and netcmd_semaphore_release().
win32_signal
struct win32_signal win32_signal
Definition at line 84 of file win32.c.
window_title
struct window_title window_title
Definition at line 90 of file win32.c.