OpenVPN: src/openvpn/win32.c File Reference
win32.c File Reference
#include "syshead.h"
#include "buffer.h"
#include "error.h"
#include "mtu.h"
#include "run_command.h"
#include "sig.h"
#include "win32.h"
#include "openvpn-msg.h"
#include "memdbg.h"
#include "compat-versionhelpers.h"
#include "block_dns.h"
Functions
static void set_openssl_env_vars ()
Set OpenSSL environment variables to a safe directory.
void init_win32 (void)
void uninit_win32 (void)
void set_pause_exit_win32 (void)
bool init_security_attributes_allow_all (struct security_attributes *obj)
void overlapped_io_init (struct overlapped_io *o, const struct frame *frame, BOOL event_state, bool tuntap_buffer)
void overlapped_io_close (struct overlapped_io *o)
char * overlapped_io_state_ascii (const struct overlapped_io *o)
void init_net_event_win32 (struct rw_handle *event, long network_events, socket_descriptor_t sd, unsigned int flags)
long reset_net_event_win32 (struct rw_handle *event, socket_descriptor_t sd)
void close_net_event_win32 (struct rw_handle *event, socket_descriptor_t sd, unsigned int flags)
void net_event_win32_init (struct net_event_win32 *ne)
void net_event_win32_start (struct net_event_win32 *ne, long network_events, socket_descriptor_t sd)
void net_event_win32_reset_write (struct net_event_win32 *ne)
void net_event_win32_reset (struct net_event_win32 *ne)
void net_event_win32_stop (struct net_event_win32 *ne)
void net_event_win32_close (struct net_event_win32 *ne)
static void win_trigger_event (struct win32_signal *ws)
static bool WINAPI win_ctrl_handler (DWORD signum)
void win32_signal_clear (struct win32_signal *ws)
void win32_signal_open (struct win32_signal *ws, int force, const char *exit_event_name, bool exit_event_initial_state)
static bool keyboard_input_available (struct win32_signal *ws)
static unsigned int keyboard_ir_to_key (INPUT_RECORD *ir)
static unsigned int win32_keyboard_get (struct win32_signal *ws)
void win32_signal_close (struct win32_signal *ws)
bool win32_service_interrupt (struct win32_signal *ws)
int win32_signal_get (struct win32_signal *ws)
void win32_pause (struct win32_signal *ws)
void window_title_clear (struct window_title *wt)
void window_title_save (struct window_title *wt)
void window_title_restore (const struct window_title *wt)
void window_title_generate (const char *title)
void semaphore_clear (struct semaphore *s)
void semaphore_open (struct semaphore *s, const char *name)
bool semaphore_lock (struct semaphore *s, int timeout_milliseconds)
void semaphore_release (struct semaphore *s)
void semaphore_close (struct semaphore *s)
void netcmd_semaphore_init (void)
void netcmd_semaphore_close (void)
void netcmd_semaphore_lock (void)
void netcmd_semaphore_release (void)
static bool cmp_prefix (const char *str, const bool n, const char *pre)
bool win_safe_filename (const char *fn)
static char * env_block (const struct env_set *es)
static WCHAR * wide_cmd_line (const struct argv *a, struct gc_arena *gc)
int openvpn_execve (const struct argv *a, const struct env_set *es, const unsigned int flags)
WCHAR * wide_string (const char *utf8, struct gc_arena *gc)
void fork_to_self (const char *cmdline)
char * get_win_sys_path (void)
void set_win_sys_path (const char *newpath, struct env_set *es)
void set_win_sys_path_via_env (struct env_set *es)
const char * win_get_tempdir (void)
static bool win_block_dns_service (bool add, int index, const HANDLE pipe)
static void block_dns_msg_handler (DWORD err, const char *msg)
bool win_wfp_block_dns (const NET_IFINDEX index, const HANDLE msg_channel)
bool win_wfp_uninit (const NET_IFINDEX index, const HANDLE msg_channel)
int win32_version_info (void)
bool win32_is_64bit (void)
const char * win32_version_string (struct gc_arena *gc, bool add_name)
bool send_msg_iservice (HANDLE pipe, const void *data, size_t size, ack_message_t *ack, const char *context)
bool openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format,...)
bool get_openvpn_reg_value (const WCHAR *key, WCHAR *value, DWORD size)
Fetches a registry value for OpenVPN registry key.
bool plugin_in_trusted_dir (const WCHAR *plugin_path)
Checks if a plugin is located in a trusted directory.
Variables
static HANDLE m_hEngineHandle = NULL
static int tap_metric_v4 = -1
static int tap_metric_v6 = -1
static struct WSAData wsa_state
static bool pause_exit_enabled = false
struct win32_signal win32_signal
struct window_title window_title
struct semaphore netcmd_semaphore
static char * win_sys_path = NULL
Function Documentation
block_dns_msg_handler()
static void block_dns_msg_handler (DWORD err, const char * msg) static
Definition at line 1312 of file win32.c.
References gc_free(), gc_new(), M_INFO, M_WARN, msg, and strerror_win32().
Referenced by win_wfp_block_dns().
close_net_event_win32()
void close_net_event_win32 (struct rw_handle * event, socket_descriptor_t sd, unsigned int flags)
Definition at line 280 of file win32.c.
References M_ERRNO, M_WARN, msg, NE32_PERSIST_EVENT, rw_handle::read, socket_defined(), and rw_handle::write.
Referenced by link_socket_close(), net_event_win32_close(), and net_event_win32_stop().
cmp_prefix()
static bool cmp_prefix (const char * str, const bool n, const char * pre) static
Definition at line 902 of file win32.c.
Referenced by win_safe_filename().
env_block()
static char* env_block (const struct env_set * es) static
Definition at line 981 of file win32.c.
References check_malloc_return(), env_allowed(), get_win_sys_path(), env_set::list, M_INFO, M_WARN, msg, env_item::next, openvpn_snprintf(), and env_item::string.
Referenced by openvpn_execve().
fork_to_self()
void fork_to_self (const char * cmdline)
Definition at line 1177 of file win32.c.
References CLEAR, M_ERRNO, M_WARN, msg, status, and string_alloc().
Referenced by fork_dhcp_action(), and fork_register_dns_action().
get_openvpn_reg_value()
bool get_openvpn_reg_value (const WCHAR * key, WCHAR * value, DWORD size)
Fetches a registry value for OpenVPN registry key.
Parameters
key Registry value name to fetch.
value Buffer to store the fetched string value.
size Size of value buffer in bytes.
Returns
true if successful, false otherwise.
Definition at line 1536 of file win32.c.
References openvpn_swprintf(), PACKAGE_NAME, and status.
Referenced by plugin_in_trusted_dir(), and set_openssl_env_vars().
get_win_sys_path()
char* get_win_sys_path (void)
Definition at line 1217 of file win32.c.
Referenced by add_route(), add_route_ipv6(), delete_route(), delete_route_ipv6(), do_ifconfig_ipv6(), env_block(), HandleEnableDHCPMessage(), ipconfig_register_dns(), netsh_delete_address_dns(), netsh_dns_cmd(), netsh_enable_dhcp(), netsh_ifconfig(), netsh_ifconfig_options(), netsh_set_dns6_servers(), RegisterDNS(), and wmic_nicconfig_cmd().
init_net_event_win32()
void init_net_event_win32 (struct rw_handle * event, long network_events, socket_descriptor_t sd, unsigned int flags)
Definition at line 226 of file win32.c.
References M_ERR, M_ERRNO, M_FATAL, msg, NE32_PERSIST_EVENT, NE32_WRITE_EVENT, rw_handle::read, and rw_handle::write.
Referenced by net_event_win32_start(), and socket_listen_event_handle().
init_security_attributes_allow_all()
bool init_security_attributes_allow_all (struct security_attributes * obj)
Definition at line 154 of file win32.c.
Referenced by semaphore_open(), tap_allow_nonadmin_access_handle(), and win32_signal_open().
init_win32()
void init_win32 (void)
Definition at line 111 of file win32.c.
References M_ERR, msg, set_openssl_env_vars(), win32_signal_clear(), window_title_clear(), and wsa_state.
Referenced by init_static().
keyboard_input_available()
static bool keyboard_input_available (struct win32_signal * ws) static
Definition at line 546 of file win32.c.
References ASSERT, HANDLE_DEFINED, win32_signal::in, win32_signal::mode, rw_handle::read, and WSO_MODE_CONSOLE.
Referenced by win32_keyboard_get().
keyboard_ir_to_key()
static unsigned int keyboard_ir_to_key (INPUT_RECORD * ir) static
Definition at line 561 of file win32.c.
Referenced by win32_keyboard_get().
net_event_win32_close()
void net_event_win32_close (struct net_event_win32 * ne)
Definition at line 378 of file win32.c.
References close_net_event_win32(), net_event_win32::handle, net_event_win32_defined(), net_event_win32_init(), and net_event_win32::sd.
Referenced by man_connection_close().
net_event_win32_init()
void net_event_win32_init (struct net_event_win32 * ne)
Definition at line 327 of file win32.c.
References CLEAR, net_event_win32::sd, and SOCKET_UNDEFINED.
Referenced by man_connection_init(), and net_event_win32_close().
net_event_win32_reset()
void net_event_win32_reset (struct net_event_win32 * ne)
Definition at line 361 of file win32.c.
References net_event_win32::event_mask, net_event_win32::handle, reset_net_event_win32(), and net_event_win32::sd.
Referenced by management_io().
net_event_win32_reset_write()
void net_event_win32_reset_write (struct net_event_win32 * ne)
Definition at line 343 of file win32.c.
References net_event_win32::event_mask, net_event_win32::handle, M_ERRNO, M_WARN, msg, status, and rw_handle::write.
Referenced by management_socket_set().
net_event_win32_start()
void net_event_win32_start (struct net_event_win32 * ne, long network_events, socket_descriptor_t sd)
Definition at line 334 of file win32.c.
References ASSERT, net_event_win32::event_mask, net_event_win32::handle, init_net_event_win32(), NE32_PERSIST_EVENT, NE32_WRITE_EVENT, net_event_win32::sd, and socket_defined().
Referenced by man_start_ne32().
net_event_win32_stop()
void net_event_win32_stop (struct net_event_win32 * ne)
Definition at line 367 of file win32.c.
References close_net_event_win32(), net_event_win32::event_mask, net_event_win32::handle, NE32_PERSIST_EVENT, net_event_win32_defined(), net_event_win32::sd, and SOCKET_UNDEFINED.
Referenced by man_stop_ne32().
netcmd_semaphore_close()
void netcmd_semaphore_close (void)
Definition at line 861 of file win32.c.
References netcmd_semaphore, and semaphore_close().
Referenced by uninit_win32().
netcmd_semaphore_init()
void netcmd_semaphore_init (void)
Definition at line 855 of file win32.c.
References netcmd_semaphore, PACKAGE, and semaphore_open().
Referenced by netcmd_semaphore_lock().
netcmd_semaphore_lock()
void netcmd_semaphore_lock (void)
Definition at line 867 of file win32.c.
References semaphore::hand, M_FATAL, msg, netcmd_semaphore, netcmd_semaphore_init(), and semaphore_lock().
Referenced by add_route(), add_route_ipv6(), delete_route(), delete_route_ipv6(), ipconfig_register_dns(), and netsh_command().
netcmd_semaphore_release()
void netcmd_semaphore_release (void)
Definition at line 883 of file win32.c.
References netcmd_semaphore, semaphore_close(), and semaphore_release().
Referenced by add_route(), add_route_ipv6(), delete_route(), delete_route_ipv6(), ipconfig_register_dns(), and netsh_command().
openvpn_execve()
int openvpn_execve (const struct argv * a, const struct env_set * es, const unsigned int flags)
Definition at line 1096 of file win32.c.
References argv::argv, CLEAR, env_block(), gc_free(), gc_new(), M_ERRNO, M_WARN, msg, openvpn_execve_allowed(), OPENVPN_EXECVE_ERROR, OPENVPN_EXECVE_NOT_ALLOWED, script_security(), SCRIPT_SECURITY_WARNING, SSEC_SCRIPTS, wide_cmd_line(), and wide_string().
Referenced by openvpn_execve_check().
openvpn_swprintf()
bool openvpn_swprintf (wchar_t *const str, const size_t size, const wchar_t *const format, ...)
Definition at line 1521 of file win32.c.
Referenced by CheckConfigPath(), get_adapter_index_method_1(), get_openvpn_reg_value(), RegisterDNS(), ReturnProcessId(), RunOpenvpn(), set_openssl_env_vars(), and ValidateOptions().
overlapped_io_close()
void overlapped_io_close (struct overlapped_io * o)
Definition at line 192 of file win32.c.
References overlapped_io::buf_init, free_buf(), M_ERRNO, M_WARN, msg, and overlapped_io::overlapped.
Referenced by close_tun(), and link_socket_close().
overlapped_io_init()
void overlapped_io_init (struct overlapped_io * o, const struct frame * frame, BOOL event_state, bool tuntap_buffer)
Definition at line 173 of file win32.c.
References alloc_buf_sock_tun(), overlapped_io::buf_init, CLEAR, M_ERR, msg, and overlapped_io::overlapped.
Referenced by init_tun_post(), and socket_frame_init().
overlapped_io_state_ascii()
char* overlapped_io_state_ascii (const struct overlapped_io * o)
Definition at line 205 of file win32.c.
References overlapped_io::iostate, IOSTATE_IMMEDIATE_RETURN, IOSTATE_INITIAL, and IOSTATE_QUEUED.
Referenced by socket_stat(), and tun_stat().
plugin_in_trusted_dir()
bool plugin_in_trusted_dir (const WCHAR * plugin_path)
Checks if a plugin is located in a trusted directory.
Verifies the plugin's path against a trusted directory, which is:
"plugin_dir" registry value or installation path, if the registry key is missing
system directory
UNC paths are explicitly disallowed.
Parameters
plugin_path Normalized path to the plugin.
Returns
true if the plugin is in a trusted directory and not a UNC path; false otherwise.
Definition at line 1598 of file win32.c.
References get_openvpn_reg_value(), M_ERRNO, M_NONFATAL, M_WARN, and msg.
Referenced by plugin_init_item().
reset_net_event_win32()
long reset_net_event_win32 (struct rw_handle * event, socket_descriptor_t sd)
Definition at line 265 of file win32.c.
References M_ERRNO, M_FATAL, msg, and rw_handle::read.
Referenced by net_event_win32_reset(), and socket_reset_listen_persistent().
semaphore_clear()
void semaphore_clear (struct semaphore * s)
Definition at line 755 of file win32.c.
References CLEAR.
semaphore_close()
void semaphore_close (struct semaphore * s)
Definition at line 835 of file win32.c.
References D_SEMAPHORE, dmsg, semaphore::hand, semaphore::locked, semaphore::name, and semaphore_release().
Referenced by netcmd_semaphore_close(), and netcmd_semaphore_release().
semaphore_lock()
bool semaphore_lock (struct semaphore * s, int timeout_milliseconds)
Definition at line 785 of file win32.c.
References ASSERT, D_SEMAPHORE, D_SEMAPHORE_LOW, dmsg, semaphore::hand, semaphore::locked, M_ERR, msg, semaphore::name, and status.
Referenced by netcmd_semaphore_lock().
semaphore_open()
void semaphore_open (struct semaphore * s, const char * name)
Definition at line 761 of file win32.c.
References D_SEMAPHORE, dmsg, semaphore::hand, init_security_attributes_allow_all(), semaphore::locked, M_ERRNO, M_WARN, msg, semaphore::name, and security_attributes::sa.
Referenced by netcmd_semaphore_init().
semaphore_release()
void semaphore_release (struct semaphore * s)
Definition at line 819 of file win32.c.
References ASSERT, D_SEMAPHORE, dmsg, semaphore::hand, semaphore::locked, M_ERRNO, M_WARN, msg, and semaphore::name.
Referenced by netcmd_semaphore_release(), and semaphore_close().
send_msg_iservice()
bool send_msg_iservice (HANDLE pipe, const void * data, size_t size, ack_message_t * ack, const char * context)
Definition at line 1500 of file win32.c.
References gc_free(), gc_new(), M_WARN, msg, and strerror_win32().
Referenced by do_address_service(), do_dns_domain_service(), do_dns_service(), do_route_service(), do_set_mtu_service(), register_dns_service(), service_enable_dhcp(), service_register_ring_buffers(), tuntap_set_ip_addr(), and win_block_dns_service().
set_openssl_env_vars()
static void set_openssl_env_vars () static
Set OpenSSL environment variables to a safe directory.
Definition at line 1556 of file win32.c.
References get_openvpn_reg_value(), openvpn_swprintf(), and SIZE.
Referenced by init_win32().
set_pause_exit_win32()
void set_pause_exit_win32 (void)
Definition at line 148 of file win32.c.
References pause_exit_enabled.
Referenced by add_option().
set_win_sys_path()
void set_win_sys_path (const char * newpath, struct env_set * es)
Definition at line 1224 of file win32.c.
References setenv_str(), string_alloc(), SYS_PATH_ENV_VAR_NAME, and win_sys_path.
Referenced by add_option(), and set_win_sys_path_via_env().
set_win_sys_path_via_env()
void set_win_sys_path_via_env (struct env_set * es)
Definition at line 1232 of file win32.c.
References M_ERR, M_FATAL, msg, set_win_sys_path(), status, and SYS_PATH_ENV_VAR_NAME.
Referenced by openvpn_main().
uninit_win32()
void uninit_win32 (void)
Definition at line 124 of file win32.c.
References win32_signal::mode, netcmd_semaphore_close(), pause_exit_enabled, win32_pause(), win32_signal_close(), win32_signal_open(), win_sys_path, window_title_restore(), WSO_FORCE_CONSOLE, and WSO_MODE_UNDEF.
Referenced by openvpn_exit().
wide_cmd_line()
static WCHAR* wide_cmd_line (const struct argv * a, struct gc_arena * gc) static
Definition at line 1042 of file win32.c.
References alloc_buf_gc(), argv::argc, argv::argv, BSTR, buf_printf(), CC_ANY, CC_CRLF, CC_DOUBLE_QUOTE, CC_PRINT, CC_SPACE, check_malloc_return(), gc_malloc(), buffer::len, string_class(), string_mod(), and wide_string().
Referenced by openvpn_execve().
wide_string()
WCHAR* wide_string (const char * utf8, struct gc_arena * gc)
Definition at line 1165 of file win32.c.
References gc_malloc().
Referenced by find_certificate_in_store(), openvpn_execve(), platform_access(), platform_chdir(), platform_fopen(), platform_open(), platform_stat(), platform_unlink(), plugin_init_item(), redirect_stdout_stderr(), and wide_cmd_line().
win32_is_64bit()
bool win32_is_64bit (void)
Definition at line 1443 of file win32.c.
Referenced by win32_version_string().
win32_keyboard_get()
static unsigned int win32_keyboard_get (struct win32_signal * ws) static
Definition at line 579 of file win32.c.
References ASSERT, HANDLE_DEFINED, win32_signal::in, keyboard_input_available(), keyboard_ir_to_key(), win32_signal::mode, rw_handle::read, and WSO_MODE_CONSOLE.
Referenced by win32_pause(), and win32_signal_get().
win32_pause()
void win32_pause (struct win32_signal * ws)
Definition at line 692 of file win32.c.
References HANDLE_DEFINED, win32_signal::in, M_INFO, M_NOPREFIX, win32_signal::mode, msg, rw_handle::read, win32_keyboard_get(), and WSO_MODE_CONSOLE.
Referenced by uninit_win32().
win32_service_interrupt()
bool win32_service_interrupt (struct win32_signal * ws)
Definition at line 627 of file win32.c.
References HANDLE_DEFINED, win32_signal::in, win32_signal::mode, rw_handle::read, and WSO_MODE_SERVICE.
Referenced by get_console_input_win32(), and win32_signal_get().
win32_signal_clear()
void win32_signal_clear (struct win32_signal * ws)
Definition at line 450 of file win32.c.
References CLEAR.
Referenced by init_win32().
win32_signal_close()
void win32_signal_close (struct win32_signal * ws)
Definition at line 607 of file win32.c.
References CLEAR, win32_signal::console_mode_save, win32_signal::console_mode_save_defined, HANDLE_DEFINED, win32_signal::in, M_ERR, win32_signal::mode, msg, rw_handle::read, and WSO_MODE_SERVICE.
Referenced by halt_non_edge_triggered_signals(), and uninit_win32().
win32_signal_get()
int win32_signal_get (struct win32_signal * ws)
Definition at line 641 of file win32.c.
References win32_signal::mode, SIG_SOURCE_HARD, SIGHUP, siginfo_static, signal_info::signal_received, SIGTERM, SIGUSR1, SIGUSR2, signal_info::source, win32_keyboard_get(), win32_service_interrupt(), WSO_MODE_CONSOLE, and WSO_MODE_SERVICE.
Referenced by get_signal().
win32_signal_open()
void win32_signal_open (struct win32_signal * ws, int force, const char * exit_event_name, bool exit_event_initial_state)
Definition at line 456 of file win32.c.
References CLEAR, win32_signal::console_mode_save, win32_signal::console_mode_save_defined, HANDLE_DEFINED, win32_signal::in, init_security_attributes_allow_all(), M_ERR, M_ERRNO, M_FATAL, M_WARN, win32_signal::mode, msg, rw_handle::read, security_attributes::sa, win_ctrl_handler(), rw_handle::write, WSO_FORCE_CONSOLE, WSO_FORCE_SERVICE, WSO_MODE_CONSOLE, WSO_MODE_SERVICE, WSO_MODE_UNDEF, and WSO_NOFORCE.
Referenced by pre_setup(), and uninit_win32().
win32_version_info()
int win32_version_info (void)
Definition at line 1407 of file win32.c.
References M_FATAL, msg, WIN_10, WIN_7, WIN_8, WIN_8_1, WIN_VISTA, and WIN_XP.
Referenced by netsh_ifconfig_options(), netsh_set_dns6_servers(), and win32_version_string().
win32_version_string()
const char* win32_version_string (struct gc_arena * gc, bool add_name)
Definition at line 1457 of file win32.c.
References alloc_buf_gc(), buf_printf(), buffer::data, M_NONFATAL, msg, win32_is_64bit(), win32_version_info(), WIN_10, WIN_7, WIN_8, WIN_8_1, WIN_VISTA, and WIN_XP.
Referenced by push_peer_info(), and show_windows_version().
win_block_dns_service()
static bool win_block_dns_service (bool add, int index, const HANDLE pipe) static
Definition at line 1276 of file win32.c.
References ack_message_t::error_number, gc_free(), gc_new(), block_dns_message_t::header, block_dns_message_t::iface, interface_t::index, M_INFO, M_WARN, msg, msg_add_block_dns, msg_del_block_dns, send_msg_iservice(), and strerror_win32().
Referenced by win_wfp_block_dns(), and win_wfp_uninit().
win_ctrl_handler()
static bool WINAPI win_ctrl_handler (DWORD signum) static
Definition at line 422 of file win32.c.
References D_LOW, msg, siginfo_static, signal_info::signal_received, SIGTERM, throw_signal(), and win_trigger_event().
Referenced by win32_signal_open().
win_get_tempdir()
const char* win_get_tempdir (void)
Definition at line 1249 of file win32.c.
References M_WARN, and msg.
Referenced by init_options().
win_safe_filename()
bool win_safe_filename (const char * fn)
Definition at line 943 of file win32.c.
References cmp_prefix().
Referenced by platform_gen_path().
win_trigger_event()
static void win_trigger_event (struct win32_signal * ws) static
Definition at line 396 of file win32.c.
References CLEAR, HANDLE_DEFINED, win32_signal::in, M_ERRNO, M_WARN, win32_signal::mode, msg, rw_handle::read, and WSO_MODE_SERVICE.
Referenced by win_ctrl_handler().
win_wfp_block_dns()
bool win_wfp_block_dns (const NET_IFINDEX index, const HANDLE msg_channel)
Definition at line 1330 of file win32.c.
References add_block_dns_filters(), BLOCK_DNS_IFACE_METRIC, block_dns_msg_handler(), D_LOW, dmsg, get_interface_metric(), M_ERRNO, m_hEngineHandle, M_WARN, msg, set_interface_metric(), status, tap_metric_v4, tap_metric_v6, and win_block_dns_service().
Referenced by do_open_tun().
win_wfp_uninit()
bool win_wfp_uninit (const NET_IFINDEX index, const HANDLE msg_channel)
Definition at line 1380 of file win32.c.
References D_LOW, delete_block_dns_filters(), dmsg, m_hEngineHandle, msg, set_interface_metric(), tap_metric_v4, tap_metric_v6, and win_block_dns_service().
Referenced by do_close_tun().
window_title_clear()
void window_title_clear (struct window_title * wt)
Definition at line 707 of file win32.c.
References CLEAR.
Referenced by init_win32().
window_title_generate()
void window_title_generate (const char * title)
Definition at line 739 of file win32.c.
References alloc_buf_gc(), BSTR, buf_printf(), gc_free(), gc_new(), PACKAGE_NAME, and PACKAGE_VERSION.
Referenced by pre_setup().
window_title_restore()
void window_title_restore (const struct window_title * wt)
Definition at line 730 of file win32.c.
References window_title::old_window_title, and window_title::saved.
Referenced by uninit_win32().
window_title_save()
void window_title_save (struct window_title * wt)
Definition at line 713 of file win32.c.
References window_title::old_window_title, and window_title::saved.
Referenced by pre_setup().
Variable Documentation
m_hEngineHandle
HANDLE m_hEngineHandle = NULL static
Definition at line 60 of file win32.c.
Referenced by win_wfp_block_dns(), and win_wfp_uninit().
netcmd_semaphore
struct semaphore netcmd_semaphore
Definition at line 97 of file win32.c.
Referenced by netcmd_semaphore_close(), netcmd_semaphore_init(), netcmd_semaphore_lock(), and netcmd_semaphore_release().
pause_exit_enabled
bool pause_exit_enabled = false static
Definition at line 76 of file win32.c.
Referenced by set_pause_exit_win32(), and uninit_win32().
tap_metric_v4
int tap_metric_v4 = -1 static
Definition at line 65 of file win32.c.
Referenced by win_wfp_block_dns(), and win_wfp_uninit().
tap_metric_v6
int tap_metric_v6 = -1 static
Definition at line 66 of file win32.c.
Referenced by win_wfp_block_dns(), and win_wfp_uninit().
win32_signal
struct win32_signal win32_signal
Definition at line 84 of file win32.c.
win_sys_path
char* win_sys_path = NULL static
Definition at line 102 of file win32.c.
Referenced by get_win_sys_path(), set_win_sys_path(), and uninit_win32().
window_title
struct window_title window_title
Definition at line 90 of file win32.c.
wsa_state
struct WSAData wsa_state static
Definition at line 71 of file win32.c.
Referenced by init_win32().